### ISSUE TITLE
Nodetool repair during mid cluster upgrade (When only node is upgraded) failed

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylladb#10469]
## Installation details

Kernel Version: 4.18.0-373.el8.x86_64
Scylla version (or git commit hash): `5.0.rc3-20220406.f92622e0d` with build-id `2b79c4744216b294fdbd2f277940044c899156ea`
Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade-master-centos-8-db-node-b63c50e7-0-4 (35.185.26.43 | 10.142.0.140) (shards: 8)
- rolling-upgrade-master-centos-8-db-node-b63c50e7-0-3 (34.138.91.165 | 10.142.0.137) (shards: 8)
- rolling-upgrade-master-centos-8-db-node-b63c50e7-0-2 (35.237.50.146 | 10.142.0.133) (shards: 8)
- rolling-upgrade-master-centos-8-db-node-b63c50e7-0-1 (35.237.5.52 | 10.142.0.41) (shards: 8)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-stream-8` (gce: us-east1)

Test: `rolling-upgrade-centos8-test`
Test id: `b63c50e7-7a90-4263-b6a2-213ed30a73e9`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-centos8-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/3615a6c5d451a30d2929dd1593784ba7c643783f/test-cases/upgrades/rolling-upgrade.yaml)

## Issue description

The rolling upgrade went as followed:
- first, we upgraded node 1
- Afterwards we upgraded node 3
- Then we rollbacked node 3
- Then we tried to repair node 1

The repair of node1, however, failed:
```
Command: "/usr/bin/nodetool -u cassandra -pw 'cassandra'  repair "

Exit code: 2

Stdout:

[2022-04-30 07:43:56,924] Repair session 4 finished
[2022-04-30 07:43:56,939] Starting repair command #5, repairing 1 ranges for keyspace ks_no_range_ghost_test (parallelism=SEQUENTIAL, full=true)
[2022-04-30 07:43:57,041] Repair session 5 
[2022-04-30 07:43:57,041] Repair session 5 finished
[2022-04-30 07:43:57,109] Starting repair command #6, repairing 1 ranges for keyspace system_traces (parallelism=SEQUENTIAL, full=true)
[2022-04-30 07:43:59,147] Repair session 6 
[2022-04-30 07:43:59,147] Repair session 6 finished
[2022-04-30 07:43:59,164] Starting repair command #7, repairing 1 ranges for keyspace ks1 (parallelism=SEQUENTIAL, full=true)
[2022-04-30 07:47:01,310] Repair session 7 failed
[2022-04-30 07:47:01,310] Repair session 7 finished

Stderr:

error: Repair job has failed with the error message: [2022-04-30 07:47:01,310] Repair session 7 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2022-04-30 07:47:01,310] Repair session 7 failed
        at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
        at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor b63c50e7-7a90-4263-b6a2-213ed30a73e9`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b63c50e7-7a90-4263-b6a2-213ed30a73e9)
- Show all stored logs command: `$ hydra investigate show-logs b63c50e7-7a90-4263-b6a2-213ed30a73e9`

## Logs:
- **db-cluster-b63c50e7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b63c50e7-7a90-4263-b6a2-213ed30a73e9/20220430_075721/db-cluster-b63c50e7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b63c50e7-7a90-4263-b6a2-213ed30a73e9/20220430_075721/db-cluster-b63c50e7.tar.gz)
- **monitor-set-b63c50e7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b63c50e7-7a90-4263-b6a2-213ed30a73e9/20220430_075721/monitor-set-b63c50e7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b63c50e7-7a90-4263-b6a2-213ed30a73e9/20220430_075721/monitor-set-b63c50e7.tar.gz)
- **loader-set-b63c50e7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b63c50e7-7a90-4263-b6a2-213ed30a73e9/20220430_075721/loader-set-b63c50e7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b63c50e7-7a90-4263-b6a2-213ed30a73e9/20220430_075721/loader-set-b63c50e7.tar.gz)
- **sct-runner-b63c50e7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b63c50e7-7a90-4263-b6a2-213ed30a73e9/20220430_075721/sct-runner-b63c50e7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b63c50e7-7a90-4263-b6a2-213ed30a73e9/20220430_075721/sct-runner-b63c50e7.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos8-test/132/)

**Comment by ShlomiBalalis** [comment]
The same exact failure occurred in the upgrade test of centos 7 (scylla master):
## Installation details

Kernel Version: 3.10.0-1160.59.1.el7.x86_64
Scylla version (or git commit hash): `5.0.rc3-20220406.f92622e0d` with build-id `2b79c4744216b294fdbd2f277940044c899156ea`
Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade-master-centos-db-node-0289f10b-0-4 (34.75.52.30 | 10.142.0.133) (shards: 8)
- rolling-upgrade-master-centos-db-node-0289f10b-0-3 (34.138.20.52 | 10.142.0.124) (shards: 8)
- rolling-upgrade-master-centos-db-node-0289f10b-0-2 (34.139.37.123 | 10.142.0.119) (shards: 8)
- rolling-upgrade-master-centos-db-node-0289f10b-0-1 (34.148.72.40 | 10.142.0.88) (shards: 8)


OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7` (gce: us-east1)

Test: `rolling-upgrade-centos7-test`
Test id: `0289f10b-77da-4cc0-9f30-c1c7e5334dd1`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-centos7-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ea4aaa1b4f8b631fea2df71d8206e815c3d7614d/test-cases/upgrades/rolling-upgrade.yaml)

## Issue description

In the same test stage as described above, the repair failed all the same:
```
Command: "/usr/bin/nodetool -u cassandra -pw 'cassandra'  repair "

Exit code: 2

Stdout:

[2022-05-07 07:37:46,293] Repair session 3 
[2022-05-07 07:37:46,293] Repair session 3 finished
[2022-05-07 07:37:58,444] Repair session 4 
[2022-05-07 07:37:58,444] Repair session 4 finished
[2022-05-07 07:37:58,498] Starting repair command #5, repairing 1 ranges for keyspace ks_no_range_ghost_test (parallelism=SEQUENTIAL, full=true)
[2022-05-07 07:37:59,599] Repair session 5 
[2022-05-07 07:37:59,600] Repair session 5 finished
[2022-05-07 07:37:59,643] Starting repair command #6, repairing 1 ranges for keyspace ks1 (parallelism=SEQUENTIAL, full=true)
[2022-05-07 07:46:59,233] Repair session 6 failed
[2022-05-07 07:46:59,234] Repair session 6 finished

Stderr:

error: Repair job has failed with the error message: [2022-05-07 07:46:59,233] Repair session 6 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2022-05-07 07:46:59,233] Repair session 6 failed
        at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
        at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 0289f10b-77da-4cc0-9f30-c1c7e5334dd1`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=0289f10b-77da-4cc0-9f30-c1c7e5334dd1)
- Show all stored logs command: `$ hydra investigate show-logs 0289f10b-77da-4cc0-9f30-c1c7e5334dd1`

## Logs:
- **db-cluster-0289f10b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0289f10b-77da-4cc0-9f30-c1c7e5334dd1/20220507_075713/db-cluster-0289f10b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0289f10b-77da-4cc0-9f30-c1c7e5334dd1/20220507_075713/db-cluster-0289f10b.tar.gz)
- **monitor-set-0289f10b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0289f10b-77da-4cc0-9f30-c1c7e5334dd1/20220507_075713/monitor-set-0289f10b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0289f10b-77da-4cc0-9f30-c1c7e5334dd1/20220507_075713/monitor-set-0289f10b.tar.gz)
- **loader-set-0289f10b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0289f10b-77da-4cc0-9f30-c1c7e5334dd1/20220507_075713/loader-set-0289f10b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0289f10b-77da-4cc0-9f30-c1c7e5334dd1/20220507_075713/loader-set-0289f10b.tar.gz)
- **sct-runner-0289f10b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/0289f10b-77da-4cc0-9f30-c1c7e5334dd1/20220507_075713/sct-runner-0289f10b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/0289f10b-77da-4cc0-9f30-c1c7e5334dd1/20220507_075713/sct-runner-0289f10b.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos7-test/230/)

**Comment by ShlomiBalalis** [comment]
And the same exact error appeared in the upgrade test of centos 8:
## Installation details

Kernel Version: 4.18.0-373.el8.x86_64
Scylla version (or git commit hash): `5.0.rc3-20220406.f92622e0d` with build-id `2b79c4744216b294fdbd2f277940044c899156ea`
Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade-master-centos-8-db-node-1594d6cf-0-4 (34.74.7.254 | 10.142.0.135) (shards: 8)
- rolling-upgrade-master-centos-8-db-node-1594d6cf-0-3 (35.237.56.19 | 10.142.0.132) (shards: 8)
- rolling-upgrade-master-centos-8-db-node-1594d6cf-0-2 (35.243.150.214 | 10.142.0.127) (shards: 8)
- rolling-upgrade-master-centos-8-db-node-1594d6cf-0-1 (34.148.3.146 | 10.142.0.122) (shards: 8)


OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-stream-8` (gce: us-east1)

Test: `rolling-upgrade-centos8-test`
Test id: `1594d6cf-e6c4-4e97-a715-99eead4c535d`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-centos8-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ea4aaa1b4f8b631fea2df71d8206e815c3d7614d/test-cases/upgrades/rolling-upgrade.yaml)

## Issue description

When attempting to repair the only (current) upgraded node (node 3) after the rollback of the other upgraded node (node 1), the repair fails:
```
Command: "/usr/bin/nodetool -u cassandra -pw 'cassandra'  repair "

Exit code: 2

Stdout:

[2022-05-07 07:47:12,845] Repair session 4 
[2022-05-07 07:47:12,845] Repair session 4 finished
[2022-05-07 07:47:12,864] Starting repair command #5, repairing 1 ranges for keyspace ks_no_range_ghost_test (parallelism=SEQUENTIAL, full=true)
[2022-05-07 07:47:13,965] Repair session 5 
[2022-05-07 07:47:13,966] Repair session 5 finished
[2022-05-07 07:47:13,981] Starting repair command #6, repairing 1 ranges for keyspace system_auth (parallelism=SEQUENTIAL, full=true)
[2022-05-07 07:47:17,076] Repair session 6 
[2022-05-07 07:47:17,077] Repair session 6 finished
[2022-05-07 07:51:21,290] Repair session 7 failed
[2022-05-07 07:51:21,290] Repair session 7 finished

Stderr:

error: Repair job has failed with the error message: [2022-05-07 07:51:21,290] Repair session 7 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2022-05-07 07:51:21,290] Repair session 7 failed
        at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
        at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 1594d6cf-e6c4-4e97-a715-99eead4c535d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=1594d6cf-e6c4-4e97-a715-99eead4c535d)
- Show all stored logs command: `$ hydra investigate show-logs 1594d6cf-e6c4-4e97-a715-99eead4c535d`

## Logs:
- **db-cluster-1594d6cf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1594d6cf-e6c4-4e97-a715-99eead4c535d/20220507_080119/db-cluster-1594d6cf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1594d6cf-e6c4-4e97-a715-99eead4c535d/20220507_080119/db-cluster-1594d6cf.tar.gz)
- **monitor-set-1594d6cf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1594d6cf-e6c4-4e97-a715-99eead4c535d/20220507_080119/monitor-set-1594d6cf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1594d6cf-e6c4-4e97-a715-99eead4c535d/20220507_080119/monitor-set-1594d6cf.tar.gz)
- **loader-set-1594d6cf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1594d6cf-e6c4-4e97-a715-99eead4c535d/20220507_080119/loader-set-1594d6cf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1594d6cf-e6c4-4e97-a715-99eead4c535d/20220507_080119/loader-set-1594d6cf.tar.gz)
- **sct-runner-1594d6cf.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1594d6cf-e6c4-4e97-a715-99eead4c535d/20220507_080119/sct-runner-1594d6cf.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1594d6cf-e6c4-4e97-a715-99eead4c535d/20220507_080119/sct-runner-1594d6cf.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos8-test/133/)

**Comment by roydahan** [comment]
@asias I vaguely remember a previous known issue with something like this.
It's a scenario that we have a "mixed" cluster (2 nodes that were upgraded and 2 haven't been upgraded yet) and running a repair.

**Comment by asias** [comment]
> @asias I vaguely remember a previous known issue with something like this. It's a scenario that we have a "mixed" cluster (2 nodes that were upgraded and 2 haven't been upgraded yet) and running a repair.

I guess you meant the issue with log warning a  off startegy update cmd is not supported on un-upgraded  node. The warning can be ignored.

https://github.com/scylladb/scylla/issues/10469#issuecomment-1123532190
https://cloudius-jenkins-test.s3.amazonaws.com/1594d6cf-e6c4-4e97-a715-99eead4c535d/20220507_080119/db-cluster-1594d6cf.tar.gz
Here, it is a real issue. It is unrelated to the warning message at all. We have a broken sstable here. 

```
$ cat db-cluster-1594d6cf/rolling-upgrade-master-centos-8-db-node-1594d6cf-0-3/messages.log|grep repair|grep -i fail
2022-05-07T07:51:13+00:00 rolling-upgrade-master-centos-8-db-node-1594d6cf-0-3 ! WARNING | [shard 6] repair - repair[68b9bc96-3a8c-461f-bf4b-93142aa334e5]: shard=6, keyspace=ks1, cf=table1, range=(9001192593464252976, 9046694614755371664], got error in row level repair: sstables::malformed_sstable_exception (Failed to read partition from SSTable /var/lib/scylla/data/ks1/table1-87cfcc00cdc011ecb53701dd87bc42ad/md-238-big-Data.db due to compressed chunk of size 4105 at file offset 2337054824 failed checksum, expected=1140850936, actual=3451565455)
2022-05-07T07:51:13+00:00 rolling-upgrade-master-centos-8-db-node-1594d6cf-0-3 ! WARNING | [shard 6] repair - repair[68b9bc96-3a8c-461f-bf4b-93142aa334e5]: shard=6, keyspace=ks1, cf=table1, range=(9001192593464252976, 9046694614755371664], got error in row level repair: sstables::malformed_sstable_exception (Failed to read partition from SSTable /var/lib/scylla/data/ks1/table1-87cfcc00cdc011ecb53701dd87bc42ad/md-238-big-Data.db due to compressed chunk of size 4105 at file offset 2337054824 failed checksum, expected=1140850936, actual=3451565455)
2022-05-07T07:51:20+00:00 rolling-upgrade-master-centos-8-db-node-1594d6cf-0-3 ! WARNING | [shard 0] repair - repair[68b9bc96-3a8c-461f-bf4b-93142aa334e5]: repair_tracker run failed: std::runtime_error ({shard 3: std::runtime_error (Failed to repair for keyspace=ks1, cf=table1_mv_0, range=(-9084693290937973417, -9057528322893552148]), shard 6: std::runtime_error (Failed to repair for keyspace=ks1, cf=table1, range=(9001192593464252976, 9046694614755371664])})
2022-05-07T07:51:20+00:00 rolling-upgrade-master-centos-8-db-node-1594d6cf-0-3 ! WARNING | [shard 0] repair - repair[68b9bc96-3a8c-461f-bf4b-93142aa334e5]: repair_tracker run failed: std::runtime_error ({shard 3: std::runtime_error (Failed to repair for keyspace=ks1, cf=table1_mv_0, range=(-9084693290937973417, -9057528322893552148]), shard 6: std::runtime_error (Failed to repair for keyspace=ks1, cf=table1, range=(9001192593464252976, 9046694614755371664])})
```

**Comment by roydahan** [comment]
So, It looks like this is the same issue as https://github.com/scylladb/scylla/issues/10543.
@asias / @ShlomiBalalis is this the same error in all the runs above?
If so, it looks like it's reproduces quite consistently.

**Comment by slivne** [comment]
According to Roy this reproduces a lot - Shlomo is running the test again to see if it reproduces every time or not

**Comment by asias** [comment]
@bhalevy  @raphaelsc Per the log  above https://github.com/scylladb/scylla/issues/10469#issuecomment-1125572027, 

```
got error in row level repair: sstables::malformed_sstable_exception (Failed to read partition from SSTable /var/lib/scylla/data/ks1/table1-87cfcc00cdc011ecb53701dd87bc42ad/md-238-big-Data.db due to compressed chunk of size 4105 at file offset 2337054824 failed checksum, expected=1140850936, actual=3451565455)
```

How could this happen? Any ideas?

**Comment by raphaelsc** [comment]
> @bhalevy @raphaelsc Per the log above [#10469 (comment)](https://github.com/scylladb/scylla/issues/10469#issuecomment-1125572027),
> 
> ```
> got error in row level repair: sstables::malformed_sstable_exception (Failed to read partition from SSTable /var/lib/scylla/data/ks1/table1-87cfcc00cdc011ecb53701dd87bc42ad/md-238-big-Data.db due to compressed chunk of size 4105 at file offset 2337054824 failed checksum, expected=1140850936, actual=3451565455)
> ```
> 
> How could this happen? Any ideas?

This usually points to data corruption. Cannot pinpoint the cause without inspecting the SSTable content.

@roydahan  I suggest next time we bump into a similar error, let's upload the SSTable referred by the message:

`"got error in row level repair: sstables::malformed_sstable_exception (Failed to read partition from SSTable /var/lib/scylla/data/ks1/table1-87cfcc00cdc011ecb53701dd87bc42ad/md-238-big-Data.db due to compressed chunk of size 4105 at file offset 2337054824 failed checksum, expected=1140850936, actual=3451565455)"`

so someone can proceed with postmortem analysis.

**Comment by roydahan** [comment]
#10543 which is suspected as dup of this was reproduced and information is being added there.

**Comment by slivne** [comment]
We have two runs

https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos7-test/229/parameters/

does nto have the issue (double check)

Run with the issue

https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos7-test/230/

Lets extract the git commits between them and then use that to check git og and see if we have a suspect - the job reproduces this easily so providing rpms we can run a reproducer job @roydahan - url ? to validate

**Comment by roydahan** [comment]
https://jenkins.scylladb.com/view/master/job/scylla-master/job/reproducers/job/10543/job/rolling-upgrade-ubuntu18.04-test-1/

**Comment by igorsimb** [comment]
## Installation details

Kernel Version: 3.10.0-1160.62.1.el7.x86_64
Scylla version (or git commit hash): `5.0.rc6-20220523.338edcc02` with build-id `60217f35371db2b1283e0c5bc67a7f5604768d41`
Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--centos-db-node-f9f62a1d-0-4 (35.196.46.97 | 10.142.0.189) (shards: 8)
- rolling-upgrade--centos-db-node-f9f62a1d-0-3 (34.138.166.47 | 10.142.0.140) (shards: 8)
- rolling-upgrade--centos-db-node-f9f62a1d-0-2 (34.148.220.109 | 10.142.0.133) (shards: 8)
- rolling-upgrade--centos-db-node-f9f62a1d-0-1 (34.138.2.217 | 10.142.0.114) (shards: 8)


OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7` (gce: us-east1)

Test: `rolling-upgrade-centos7-test`
Test id: `f9f62a1d-aba3-4e77-a8ab-a50ea1c311e7`
Test name: `scylla-master/rolling-upgrade/rolling-upgrade-centos7-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a53b3070cef02c729648aad9c88c951e11318523/test-cases/upgrades/rolling-upgrade.yaml)

## Issue description

The same issue occurred during this run.
```
Command: "/usr/bin/nodetool -u cassandra -pw 'cassandra'  repair "

Exit code: 2

Stdout:

[2022-06-04 08:15:47,724] Starting repair command #1, repairing 1 ranges for keyspace keyspace_entire_test (parallelism=SEQUENTIAL, full=true)
[2022-06-04 08:16:03,835] Repair session 1 
[2022-06-04 08:16:03,836] Repair session 1 finished
[2022-06-04 08:16:03,912] Starting repair command #2, repairing 1 ranges for keyspace ks1 (parallelism=SEQUENTIAL, full=true)
[2022-06-04 08:24:57,159] Repair session 2 failed
[2022-06-04 08:24:57,159] Repair session 2 finished

Stderr:

error: Repair job has failed with the error message: [2022-06-04 08:24:57,159] Repair session 2 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2022-06-04 08:24:57,159] Repair session 2 failed
        at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
        at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor f9f62a1d-aba3-4e77-a8ab-a50ea1c311e7`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f9f62a1d-aba3-4e77-a8ab-a50ea1c311e7)
- Show all stored logs command: `$ hydra investigate show-logs f9f62a1d-aba3-4e77-a8ab-a50ea1c311e7`

## Logs:
- **db-cluster-f9f62a1d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9f62a1d-aba3-4e77-a8ab-a50ea1c311e7/20220604_083452/db-cluster-f9f62a1d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9f62a1d-aba3-4e77-a8ab-a50ea1c311e7/20220604_083452/db-cluster-f9f62a1d.tar.gz)
- **monitor-set-f9f62a1d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9f62a1d-aba3-4e77-a8ab-a50ea1c311e7/20220604_083452/monitor-set-f9f62a1d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9f62a1d-aba3-4e77-a8ab-a50ea1c311e7/20220604_083452/monitor-set-f9f62a1d.tar.gz)
- **loader-set-f9f62a1d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9f62a1d-aba3-4e77-a8ab-a50ea1c311e7/20220604_083452/loader-set-f9f62a1d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9f62a1d-aba3-4e77-a8ab-a50ea1c311e7/20220604_083452/loader-set-f9f62a1d.tar.gz)
- **sct-runner-f9f62a1d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f9f62a1d-aba3-4e77-a8ab-a50ea1c311e7/20220604_083452/sct-runner-f9f62a1d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f9f62a1d-aba3-4e77-a8ab-a50ea1c311e7/20220604_083452/sct-runner-f9f62a1d.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos7-test/233/)

**Comment by fruch** [comment]
happened again this week:
## Logs:
- **db-cluster-95cb80ba.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/95cb80ba-5381-4bc3-9a70-f26faefaac16/20220702_095720/db-cluster-95cb80ba.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/95cb80ba-5381-4bc3-9a70-f26faefaac16/20220702_095720/db-cluster-95cb80ba.tar.gz)
- **monitor-set-95cb80ba.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/95cb80ba-5381-4bc3-9a70-f26faefaac16/20220702_095720/monitor-set-95cb80ba.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/95cb80ba-5381-4bc3-9a70-f26faefaac16/20220702_095720/monitor-set-95cb80ba.tar.gz)
- **loader-set-95cb80ba.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/95cb80ba-5381-4bc3-9a70-f26faefaac16/20220702_095720/loader-set-95cb80ba.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/95cb80ba-5381-4bc3-9a70-f26faefaac16/20220702_095720/loader-set-95cb80ba.tar.gz)
- **sct-runner-95cb80ba.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/95cb80ba-5381-4bc3-9a70-f26faefaac16/20220702_095720/sct-runner-95cb80ba.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/95cb80ba-5381-4bc3-9a70-f26faefaac16/20220702_095720/sct-runner-95cb80ba.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos7-test/237/)

**Comment by fruch** [comment]
@slivne 

first show this issue: 5.1.dev-0.20220501.7f1e368e92ce
previous run version: 5.1.dev-0.20220422.cc40685c288f

https://github.com/scylladb/scylla/compare/cc40685c288f...7f1e368e92ce

**Comment by bhalevy** [comment]
@roydahan / @fruch 
I suggest to close this as duplicate of #10543
(and close the latter once proven that it was caused by bug in the GCE infrastructure)

**Comment by roydahan** [comment]
Let's wait for the runs on the new project and if not relevant we can close together.

**Comment by slivne** [comment]
@roydahan any luck on running on new project

**Comment by ShlomiBalalis** [comment]
> @roydahan any luck on running on new project

We are currently running all of the longevity tests on the new project. I will update once the runs end.

**Comment by slivne** [comment]
@ShlomiBalalis ping

**Comment by ShlomiBalalis** [comment]
> @ShlomiBalalis ping

Sorry, we updated #10543 but forgot to update this one.
The new project seems to have helped, and we did not run into the issue again. Closing.
