### ISSUE TITLE
Scrub fails on Azure

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#10928]
## Installation details

Kernel Version: 5.13.0-1029-azure
Scylla version (or git commit hash): `5.0~rc8-20220612.f28542a71` with build-id `85cf87619b93155a574647ec252ce5a043c7fe77`
Cluster size: 6 nodes (Standard_L8s_v2)

Scylla Nodes used in this run:
- longevity-10gb-3h-5-0-db-node-41a62132-eastus-8 (20.120.112.115 | 10.0.0.14) (shards: 8)
- longevity-10gb-3h-5-0-db-node-41a62132-eastus-7 (104.211.25.135 | 10.0.0.14) (shards: 8)
- longevity-10gb-3h-5-0-db-node-41a62132-eastus-6 (20.232.152.145 | 10.0.0.10) (shards: 8)
- longevity-10gb-3h-5-0-db-node-41a62132-eastus-5 (20.124.4.43 | 10.0.0.9) (shards: 8)
- longevity-10gb-3h-5-0-db-node-41a62132-eastus-4 (20.232.158.50 | 10.0.0.8) (shards: 8)
- longevity-10gb-3h-5-0-db-node-41a62132-eastus-3 (20.231.210.241 | 10.0.0.7) (shards: 8)
- longevity-10gb-3h-5-0-db-node-41a62132-eastus-2 (20.231.2.244 | 10.0.0.6) (shards: 8)
- longevity-10gb-3h-5-0-db-node-41a62132-eastus-1 (20.25.18.192 | 10.0.0.5) (shards: 8)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/ScyllaDB-5.0.rc8-0.20220612.f28542a71-1-build-17` (azure: eastus)

Test: `longevity-10gb-3h-azure-test`
Test id: `41a62132-7e4d-40e3-bcc7-ad33ec0389ea`
Test name: `scylla-5.0/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/76ee6bf43691d11d6a40b1bb76f26ae095901768/test-cases/longevity/longevity-10gb-3h.yaml)

## Issue description

Running `nodetool scrub` command fails on Azure:
```
Command: '/usr/bin/nodetool  scrub --skip-corrupted keyspace_new_dc'

Exit code: 2

Stdout:



Stderr:

	at org.apache.cassandra.config.DatabaseDescriptor.createEndpointSnitch(DatabaseDescriptor.java:1018)
	at org.apache.cassandra.config.DatabaseDescriptor.applySnitch(DatabaseDescriptor.java:942)
	at org.apache.cassandra.config.DatabaseDescriptor.toolInitialization(DatabaseDescriptor.java:192)
	at org.apache.cassandra.config.DatabaseDescriptor.toolInitialization(DatabaseDescriptor.java:157)
	at org.apache.cassandra.tools.NodeProbe.checkJobs(NodeProbe.java:338)
	at org.apache.cassandra.tools.NodeProbe.scrub(NodeProbe.java:361)
	at org.apache.cassandra.tools.nodetool.Scrub.execute(Scrub.java:84)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:270)
	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:180)
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 41a62132-7e4d-40e3-bcc7-ad33ec0389ea`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=41a62132-7e4d-40e3-bcc7-ad33ec0389ea)
- Show all stored logs command: `$ hydra investigate show-logs 41a62132-7e4d-40e3-bcc7-ad33ec0389ea`

## Logs:
---------------------------------------------------------+
| 20220627_173219 | grafana    | https://cloudius-jenkins-test.s3.amazonaws.com/41a62132-7e4d-40e3-bcc7-ad33ec0389ea/20220627_173219/grafana-screenshot-longevity-10gb-3h-azure-test-scylla-per-server-metrics-nemesis-20220627_173441-longevity-10gb-3h-5-0-monitor-node-41a62132-eastus-1.png |
| 20220627_173219 | grafana    | https://cloudius-jenkins-test.s3.amazonaws.com/41a62132-7e4d-40e3-bcc7-ad33ec0389ea/20220627_173219/grafana-screenshot-overview-20220627_173219-longevity-10gb-3h-5-0-monitor-node-41a62132-eastus-1.png                                                       |
| 20220627_173753 | db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/41a62132-7e4d-40e3-bcc7-ad33ec0389ea/20220627_173753/db-cluster-41a62132.tar.gz                                                                                                                                 |
| 20220627_173753 | loader-set | https://cloudius-jenkins-test.s3.amazonaws.com/41a62132-7e4d-40e3-bcc7-ad33ec0389ea/20220627_173753/loader-set-41a62132.tar.gz                                                                                                                                 |
| 20220627_173753 | sct        | https://cloudius-jenkins-test.s3.amazonaws.com/41a62132-7e4d-40e3-bcc7-ad33ec0389ea/20220627_173753/sct-runner-41a62132.tar.gz                                      

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-10gb-3h-azure-test/5/)

**Comment by bhalevy** [comment]
@xemul this looks snitch related

**Comment by xemul** [comment]
I see
```
2022-06-27T13:04:24+00:00 longevity-10gb-3h-5-0-db-node-eastus-3 !    INFO |  [shard 0] init - creating snitch
2022-06-27T13:04:24+00:00 longevity-10gb-3h-5-0-db-node-eastus-3 !    INFO |  [shard 0] snitch_logger - AzureSnitch using region: eastus, zone: Too many requests.
2022-06-27T13:04:24+00:00 longevity-10gb-3h-5-0-db-node-eastus-3 !    INFO |  [shard 5] snitch_logger - AzureSnitch using region: Too many requests, zone: Too many requests.
2022-06-27T13:04:24+00:00 longevity-10gb-3h-5-0-db-node-eastus-3 !    INFO |  [shard 1] snitch_logger - AzureSnitch using region: Too many requests, zone: .
2022-06-27T13:04:24+00:00 longevity-10gb-3h-5-0-db-node-eastus-3 ! WARNING |  [shard 1] snitch_logger - org.apache.cassandra.locator.AzureSnitch snitch attempted to set rack to an empty string, falling back to UNKNOWN_RACK.
2022-06-27T13:04:24+00:00 longevity-10gb-3h-5-0-db-node-eastus-3 !    INFO |  [shard 3] snitch_logger - AzureSnitch using region: eastus, zone: .
2022-06-27T13:04:24+00:00 longevity-10gb-3h-5-0-db-node-eastus-3 ! WARNING |  [shard 3] snitch_logger - org.apache.cassandra.locator.AzureSnitch snitch attempted to set rack to an empty string, falling back to UNKNOWN_RACK.
2022-06-27T13:04:24+00:00 longevity-10gb-3h-5-0-db-node-eastus-3 !    INFO |  [shard 6] snitch_logger - AzureSnitch using region: eastus, zone: .
2022-06-27T13:04:24+00:00 longevity-10gb-3h-5-0-db-node-eastus-3 ! WARNING |  [shard 6] snitch_logger - org.apache.cassandra.locator.AzureSnitch snitch attempted to set rack to an empty string, falling back to UNKNOWN_RACK.
2022-06-27T13:04:24+00:00 longevity-10gb-3h-5-0-db-node-eastus-3 !    INFO |  [shard 4] snitch_logger - AzureSnitch using region: eastus, zone: .
2022-06-27T13:04:24+00:00 longevity-10gb-3h-5-0-db-node-eastus-3 ! WARNING |  [shard 4] snitch_logger - org.apache.cassandra.locator.AzureSnitch snitch attempted to set rack to an empty string, falling back to UNKNOWN_RACK.
2022-06-27T13:04:24+00:00 longevity-10gb-3h-5-0-db-node-eastus-3 !    INFO |  [shard 2] snitch_logger - AzureSnitch using region: eastus, zone: .
2022-06-27T13:04:24+00:00 longevity-10gb-3h-5-0-db-node-eastus-3 ! WARNING |  [shard 2] snitch_logger - org.apache.cassandra.locator.AzureSnitch snitch attempted to set rack to an empty string, falling back to UNKNOWN_RACK.
2022-06-27T13:04:24+00:00 longevity-10gb-3h-5-0-db-node-eastus-3 !    INFO |  [shard 7] snitch_logger - AzureSnitch using region: eastus, zone: .
2022-06-27T13:04:24+00:00 longevity-10gb-3h-5-0-db-node-eastus-3 ! WARNING |  [shard 7] snitch_logger - org.apache.cassandra.locator.AzureSnitch snitch attempted to set rack to an empty string, falling back to UNKNOWN_RACK.
```
in logs. Apparently `5.0~rc8-20220612.f28542a71` is old enough to suffer from #10494 and deserves c6d0bc87d024addd62962892d64b04410089cbd7.

However, this doesn't explain the nodetool error.

**Comment by slivne** [comment]
the nodetool error could be from nodetool itself not supporting the azuresnitch in scylla.yaml

@soyacz  can we please have the scylla.yaml -I expect the snitch their is not supported.

**Comment by roydahan** [comment]
I think this one isn't relevant anymore and probably was fixed by above commits.
