### ISSUE TITLE
few repairs started, but took to long to finish, making the replace node operation to timeout

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylladb#11034]
*Installation details*
Scylla version (or git commit hash): 5.0.0-0.20220628.c9e79cb4a with build-id daef393310f38c086a6e5070c8f2013684973a48
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-050b81d683f061fbd` (`eu-west-1`)

test is `performance_regression_test.PerformanceRegressionTest.test_latency_mixed_with_nemesis` and during replace node operation, we had a bunch of repair that never ended. it caused the test to wait for them, and eventually timeout

the replace node operation started at:
```
2022-07-06 01:25:41.081: (InfoEvent Severity.NORMAL) period_type=not-set event_id=903c249f-a90e-4a3d-98d9-4de5980b62ed: message=StartEvent - Adding new node to cluster
```

and the replace node operation failed at:
```
2022-07-06 02:13:03.150: (DisruptionEvent Severity.ERROR) period_type=end event_id=d10ea448-6cb9-49ee-93ed-15ffb6de54d5 duration=52m30s: nemesis_name=TerminateAndReplaceNode target_node=Node perf-latency-nemesis-perf-v12-db-node-22d6bc74-2 [63.35.251.240 | 10.0.0.238] (seed: False) errors=Not all nodes joined the cluster
Traceback (most recent call last):
  File "/home/jenkins/slave/workspace/Perf-Regression/scylla-release-perf-regression-latency-250gb-with-nemesis@4/scylla-cluster-tests/sdcm/nemesis.py", line 2889, in wrapper
    result = method(*args, **kwargs)
  File "/home/jenkins/slave/workspace/Perf-Regression/scylla-release-perf-regression-latency-250gb-with-nemesis@4/scylla-cluster-tests/sdcm/nemesis.py", line 905, in disrupt_terminate_and_replace_node
    new_node = self.replace_node(old_node_ip, rack=self.target_node.rack)
  File "/home/jenkins/slave/workspace/Perf-Regression/scylla-release-perf-regression-latency-250gb-with-nemesis@4/scylla-cluster-tests/sdcm/utils/decorators.py", line 166, in wrapped
    res = func(*args, **kwargs)
  File "/home/jenkins/slave/workspace/Perf-Regression/scylla-release-perf-regression-latency-250gb-with-nemesis@4/scylla-cluster-tests/sdcm/nemesis.py", line 839, in replace_node
    return self._add_and_init_new_cluster_node(old_node_ip, rack=rack)
  File "/home/jenkins/slave/workspace/Perf-Regression/scylla-release-perf-regression-latency-250gb-with-nemesis@4/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
    return func(*args, **kwargs)
  File "/home/jenkins/slave/workspace/Perf-Regression/scylla-release-perf-regression-latency-250gb-with-nemesis@4/scylla-cluster-tests/sdcm/nemesis.py", line 772, in _add_and_init_new_cluster_node
    self.cluster.wait_for_init(node_list=[new_node], timeout=timeout, check_node_health=False)
  File "/home/jenkins/slave/workspace/Perf-Regression/scylla-release-perf-regression-latency-250gb-with-nemesis@4/scylla-cluster-tests/sdcm/cluster.py", line 3601, in wrapper
    cl_inst.wait_for_nodes_up_and_normal(nodes=node_list, verification_node=node_list[0])
  File "/home/jenkins/slave/workspace/Perf-Regression/scylla-release-perf-regression-latency-250gb-with-nemesis@4/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
    return func(*args, **kwargs)
  File "/home/jenkins/slave/workspace/Perf-Regression/scylla-release-perf-regression-latency-250gb-with-nemesis@4/scylla-cluster-tests/sdcm/cluster.py", line 4089, in wait_for_nodes_up_and_normal
    self.check_nodes_up_and_normal(nodes=nodes, verification_node=verification_node)
  File "/home/jenkins/slave/workspace/Perf-Regression/scylla-release-perf-regression-latency-250gb-with-nemesis@4/scylla-cluster-tests/sdcm/cluster.py", line 4059, in check_nodes_up_and_normal
    raise ClusterNodesNotReady("Not all nodes joined the cluster")
sdcm.cluster.ClusterNodesNotReady: Not all nodes joined the cluster
2022-07-06 02:13:03.151: (InfoEvent Severity.NORMAL) period_type=not-set event_id=afe8901f-458e-46e5-af0b-02d340e374ff: message=Finished terminate_and_replace disruption
```

for example, repair with ID `744cc9ed-b129-4dac-8fcf-93cb4ecbfb7d` eventually finished, but it took 44 minutes:
```
< t:2022-07-06 02:14:49,869 f:file_logger.py  l:85   c:sdcm.sct_events.file_logger p:DEBUG > 2022-07-06 02:14:49.864: (RepairEvent Severity.NORMAL) period_type=end event_id=744cc9ed-b129-4dac-8fcf-93cb4ecbfb7d duration=44m13s node=perf-latency-nemesis-perf-v12-db-node-22d6bc74-4 shard=0
```
another example:
```
< t:2022-07-06 02:14:46,259 f:file_logger.py  l:85   c:sdcm.sct_events.file_logger p:DEBUG > 2022-07-06 02:14:46.254: (RepairEvent Severity.NORMAL) period_type=end event_id=d9bbd867-ce98-4091-bc71-97e42f7588b1 duration=44m9s node=perf-latency-nemesis-perf-v12-db-node-22d6bc
74-4 shard=0
```
and one more (this one took more than 1 hour):
```
< t:2022-07-06 02:35:37,775 f:file_logger.py  l:85   c:sdcm.sct_events.file_logger p:DEBUG > 2022-07-06 02:35:37.771: (RepairEvent Severity.NORMAL) period_type=end event_id=adf1518b-a276-4471-a460-12feeb41b24c duration=1h5m0s node=perf-latency-nemesis-perf-v12-db-node-22d6bc74-4 shard=2
```

i have a cut of the repair IDs that did not finish in the expected time frame:
```
[{'744cc9ed-b129-4dac-8fcf-93cb4ecbfb7d': {'begin': '2022-07-06 01:30:36'},
{'d9bbd867-ce98-4091-bc71-97e42f7588b1': {'begin': '2022-07-06 01:30:36'},
{'adf1518b-a276-4471-a460-12feeb41b24c': {'begin': '2022-07-06 01:30:36'},
{'0d8f4a59-3cc9-448c-bed7-5a0c90737c77': {'begin': '2022-07-06 01:30:36'},
{'f79b62b0-3d43-4ed3-ac03-13492657d952': {'begin': '2022-07-06 01:30:37'},
{'10d6f9c7-87d3-44ee-9e46-0c08aed0e3a7': {'begin': '2022-07-06 01:30:37'},
{'08cfdd63-ec0e-4a0a-8b6d-c3e2d4882885': {'begin': '2022-07-06 01:30:38'},
{'0f090fa5-4549-4958-bc27-c8b51d02131d': {'begin': '2022-07-06 01:30:38'},
{'16de1f3b-aa8b-43dd-ac95-a00fd97bf40e': {'begin': '2022-07-06 01:32:15'},
{'5d790f29-006d-4f3a-a8f8-6e5d50dcbb73': {'begin': '2022-07-06 01:32:16'},
{'bbb77d44-03c4-4bdb-833c-0b07dc045d7a': {'begin': '2022-07-06 01:32:16'},
{'a995afd7-5f5c-4ca8-a1d3-5d6e47f802b9': {'begin': '2022-07-06 01:32:16'},
{'a7dfa02c-0aca-47e1-8d8d-89030b21f3c3': {'begin': '2022-07-06 01:32:21'},
{'4063f03b-fdb8-47c1-975b-167a885bc0b9': {'begin': '2022-07-06 01:32:22'},
{'364d1f30-4472-4214-835f-d1977f22c701': {'begin': '2022-07-06 01:32:22'},
{'a8b954c1-4a0d-4ea5-9bda-ee70b7e32e8f': {'begin': '2022-07-06 01:32:22'},
{'a925ce00-6ef3-41ed-8d09-f45cb4c4b21c': {'begin': '2022-07-06 01:44:29'},
{'cca08d49-4795-4fed-a24d-2725b9371674': {'begin': '2022-07-06 01:44:29'},
{'a88a3eb7-5f09-47d6-965a-aa31a9eb2246': {'begin': '2022-07-06 01:44:29'},
{'03023667-42d9-4acc-9920-2534c50210e1': {'begin': '2022-07-06 01:44:29'},
{'c518861d-1802-4793-99d1-1db8b45b7353': {'begin': '2022-07-06 01:44:29'},
{'43046bf4-ff79-438a-b7cf-bace0979d5b6': {'begin': '2022-07-06 01:44:29'},
{'536a6a17-1619-4159-8138-e5e3aeef33d9': {'begin': '2022-07-06 01:44:29'},
{'58f9e0d1-e9e3-4b96-b6f3-fc088418db5b': {'begin': '2022-07-06 01:44:29'}}]
```

full logs:
[db logs](https://cloudius-jenkins-test.s3.amazonaws.com/22d6bc74-00fa-4ded-8d4c-d728ce456635/20220706_051222/db-cluster-22d6bc74.tar.gz)
[sct logs](https://cloudius-jenkins-test.s3.amazonaws.com/22d6bc74-00fa-4ded-8d4c-d728ce456635/20220706_051222/sct-runner-22d6bc74.tar.gz)

`test_id: 22d6bc74-00fa-4ded-8d4c-d728ce456635`

**Comment by fgelcer** [comment]
@asias , FYI

**Comment by asias** [comment]
@xemul could you please check if the version was exposed to the  io queue hang and rpc hang issue we found recently?

**Comment by xemul** [comment]
@asias , which IO queue hang do you mean? I cannot recall any

**Comment by xemul** [comment]
Regarding RPC hangs -- there were 3 of them, 2 not fixed at all, 1 fixed but only affecting 5.1

**Comment by asias** [comment]
> @asias , which IO queue hang do you mean? I cannot recall any

I vaguely remember there was a regression with the new io scheduler that some of the queue would not get correct bandwidth.

**Comment by asias** [comment]
I think this problem is fixed by:

reader stuck
1) Some shards get stuck in tight loop during repair #11223

rcp stuck
2) seastar: c8f9d6906b7165f32015bc6a851bf7c2dbacd2f9
rpc: Make server::connection::negotiate synchronous
