### ISSUE TITLE
sstableloader crushed on loading cassandra 4.1 tables 

### ISSUE THREAD

**Issue by ValeryDubrava** [scylladb/scylladb#11267]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.2 (latest)
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian 11

*Hardware details (for performance issues)*      
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets=? cores=12 hyperthreading=? memory=64gb
Disks: (SSD/HDD, count) md raid 1, hdd (x2)

I've tried to migrate data from cassandra cluster to scylla. I've launched the same cluster one the same servers. Cassandra was uninstalled. Created the same schema like in Cassandra was. And launched the migration process by the command below:
```
~ # sstableloader -d localhost /var/lib/cassandra/data/wax/abi-1baf0aa00b7c11ed8599530d42453801/
===== Using optimized driver!!! =====
java.lang.ArrayIndexOutOfBoundsException: Index 640228101 out of bounds for length 4
        at org.apache.cassandra.io.sstable.metadata.MetadataSerializer.deserialize(MetadataSerializer.java:114)
        at org.apache.cassandra.io.sstable.metadata.MetadataSerializer.deserialize(MetadataSerializer.java:93)
        at org.apache.cassandra.io.sstable.format.SSTableReader.openForBatch(SSTableReader.java:416)
        at com.scylladb.tools.BulkLoader.openFile(BulkLoader.java:1525)
        at com.scylladb.tools.BulkLoader.process(BulkLoader.java:1570)
        at com.scylladb.tools.BulkLoader.lambda$main$1(BulkLoader.java:1367)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
java.lang.ArrayIndexOutOfBoundsException: Index 640228101 out of bounds for length 4
        at org.apache.cassandra.io.sstable.metadata.MetadataSerializer.deserialize(MetadataSerializer.java:114)
        at org.apache.cassandra.io.sstable.metadata.MetadataSerializer.deserialize(MetadataSerializer.java:93)
        at org.apache.cassandra.io.sstable.format.SSTableReader.openForBatch(SSTableReader.java:416)
        at com.scylladb.tools.BulkLoader.openFile(BulkLoader.java:1525)
        at com.scylladb.tools.BulkLoader.process(BulkLoader.java:1570)
        at com.scylladb.tools.BulkLoader.lambda$main$1(BulkLoader.java:1367)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
java.lang.ArrayIndexOutOfBoundsException: Index 640228101 out of bounds for length 4
        at org.apache.cassandra.io.sstable.metadata.MetadataSerializer.deserialize(MetadataSerializer.java:114)
        at org.apache.cassandra.io.sstable.metadata.MetadataSerializer.deserialize(MetadataSerializer.java:93)
        at org.apache.cassandra.io.sstable.format.SSTableReader.openForBatch(SSTableReader.java:416)
        at com.scylladb.tools.BulkLoader.openFile(BulkLoader.java:1525)
        at com.scylladb.tools.BulkLoader.process(BulkLoader.java:1570)
        at com.scylladb.tools.BulkLoader.lambda$main$1(BulkLoader.java:1367)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
  0% done.        0 statements sent (in        0 batches,        0 failed).
       0 statements generated.
       0 cql rows processed in        0 partitions.
       0 cql rows and        0 partitions deleted.
       0 local and        0 remote counter shards where skipped.
```

**Comment by elcallio** [comment]
Which version of cassandra? The error above suggests that either the sstables are corrupted or in a format that the (cassandra) sstable readers used (3.x cassandra) in sstableloader cannot handle it properly. 
Best would be if you provided the actual schemas and sstables so we can try to debug it.

**Comment by ValeryDubrava** [comment]
It was clear installation of Cassandra 4.1. I mean, no update old db, just new installation. How can I get this information? Or did you ask about tables schema?

**Comment by ValeryDubrava** [comment]
So, currently there is no way to migrate data from 4.X cassandra?

**Comment by slivne** [comment]
No there is a way - you can use scylla migrator 

(https://github.com/scylladb/scylla-migrator)
