### ISSUE TITLE
`scylla_setup` fails on RAID setup when running node setup on ubuntu 22.04 (ARM)

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylladb#11359]
## Installation details

Cluster size: 1 nodes (im4gn.xlarge)

Scylla Nodes used in this run:
- artifacts-ubuntu2204-jenkins-db-node-de480894-1 (52.214.215.38 | 10.0.0.24) (shards: -1)

OS / Image: `ami-022c8ce295ce9ac4c` (aws: eu-west-1)

Test: `artifacts-ubuntu2204-arm-test`
Test id: `de480894-0e98-4f9e-832c-8f23a3133597`
Test name: `scylla-5.0/artifacts/artifacts-ubuntu2204-arm-test`
Test config file(s):

- [ubuntu2204.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d005fbcab399b37749e871fcca553e5597fda642/test-cases/artifacts/ubuntu2204.yaml)

## Issue description

**>>>>>>>**
During db node setup the `scylla_setup` script failed with the following:

`sct.log`

```
< t:2022-08-19 14:57:55,068 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "sudo /usr/lib/scylla/scylla_setup --nic ens5 --disks /dev/nvme1n1 --setup-nic-and-disks  --no-ec2-check  --swap-directory / "...
< t:2022-08-19 14:57:56,570 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > INFO  2022-08-19 14:57:56,522 [shard 0] seastar - Created fair group io-queue-0, capacity rate 2147483:2147483, limit 12582912, rate 16777216 (factor 1), threshold 2000
< t:2022-08-19 14:57:56,889 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > This is a supported kernel version.
< t:2022-08-19 14:57:58,390 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > WARN  2022-08-19 14:57:56,593 [shard 0] iotune - Available space on filesystem at /var/tmp/mnt: 121 MB: is less than recommended: 10 GB
< t:2022-08-19 14:57:58,890 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > INFO  2022-08-19 14:57:56,593 [shard 0] iotune - /var/tmp/mnt passed sanity checks
< t:2022-08-19 14:57:59,045 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > ntp is already configured, skip setup
< t:2022-08-19 14:57:59,046 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Created symlink /etc/systemd/system/multi-user.target.wants/scylla-server.service → /lib/systemd/system/scylla-server.service.
< t:2022-08-19 14:58:06,430 f:testrun.py      l:723  c:cassandra.pool       p:DEBUG > Using connection to shard_id=0 on host 13.49.166.9:9042 for routing_key=b'scylla-5.0/artifacts/artifacts-ubuntu2204-arm-test'
< t:2022-08-19 14:58:06,911 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > meta-data=/dev/nvme1n1           isize=512    agcount=4, agsize=457763672 blks
< t:2022-08-19 14:58:06,911 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >          =                       sectsz=512   attr=2, projid32bit=1
< t:2022-08-19 14:58:06,911 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >          =                       crc=1        finobt=1, sparse=1, rmapbt=0
< t:2022-08-19 14:58:06,911 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >          =                       reflink=1    bigtime=0 inobtcount=0
< t:2022-08-19 14:58:06,911 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > data     =                       bsize=1024   blocks=1831054687, imaxpct=5
< t:2022-08-19 14:58:06,911 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >          =                       sunit=0      swidth=0 blks
< t:2022-08-19 14:58:06,911 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
< t:2022-08-19 14:58:06,911 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > log      =internal log           bsize=1024   blocks=894069, version=2
< t:2022-08-19 14:58:06,911 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >          =                       sectsz=512   sunit=0 blks, lazy-count=1
< t:2022-08-19 14:58:06,911 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > realtime =none                   extsz=4096   blocks=0, rtextents=0
< t:2022-08-19 14:58:07,366 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Aug 19 14:58:07 artifacts-ubuntu2204-jenkins-db-node-de91bbe9-1 systemd[1]: /lib/systemd/system/scylla-server.service:26: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
< t:2022-08-19 14:58:07,367 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Aug 19 14:58:07 artifacts-ubuntu2204-jenkins-db-node-de91bbe9-1 systemd[1]: /lib/systemd/system/scylla-server.service:27: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
< t:2022-08-19 14:58:36,482 f:testrun.py      l:723  c:cassandra.pool       p:DEBUG > Using connection to shard_id=0 on host 13.49.166.9:9042 for routing_key=b'scylla-5.0/artifacts/artifacts-ubuntu2204-arm-test'
< t:2022-08-19 14:59:06,540 f:testrun.py      l:723  c:cassandra.pool       p:DEBUG > Using connection to shard_id=0 on host 13.49.166.9:9042 for routing_key=b'scylla-5.0/artifacts/artifacts-ubuntu2204-arm-test'
< t:2022-08-19 14:59:36,605 f:testrun.py      l:723  c:cassandra.pool       p:DEBUG > Using connection to shard_id=0 on host 13.49.166.9:9042 for routing_key=b'scylla-5.0/artifacts/artifacts-ubuntu2204-arm-test'
< t:2022-08-19 14:59:37,367 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Creating XFS volume for scylla using 1 disk(s): /dev/nvme1n1
< t:2022-08-19 14:59:37,367 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > A dependency job for var-lib-scylla.mount failed. See 'journalctl -xe' for details.
< t:2022-08-19 14:59:37,381 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > RAID setup failed.
< t:2022-08-19 14:59:37,381 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Traceback (most recent call last):
< t:2022-08-19 14:59:37,882 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >   File "/opt/scylladb/scripts/libexec/scylla_raid_setup", line 195, in <module>
< t:2022-08-19 14:59:38,382 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >     mount.start()
< t:2022-08-19 14:59:38,882 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >   File "/opt/scylladb/scripts/scylla_util.py", line 352, in start
< t:2022-08-19 14:59:39,383 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >     return run('systemctl {} start {}'.format(self.ctlparam, self._unit), shell=True, check=True)
< t:2022-08-19 14:59:39,883 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 528, in run
< t:2022-08-19 14:59:40,383 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >     raise CalledProcessError(retcode, process.args,
< t:2022-08-19 14:59:40,884 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > subprocess.CalledProcessError: Command 'systemctl  start var-lib-scylla.mount' returned non-zero exit status 1.
< t:2022-08-19 14:59:40,884 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "sudo /usr/lib/scylla/scylla_setup --nic ens5 --disks /dev/nvme1n1 --setup-nic-and-disks  --no-ec2-check  --swap-directory / "; Exit status: 1 
< t:2022-08-19 14:59:40,884 f:base.py         l:148  c:RemoteLibSSH2CmdRunner p:DEBUG > STDOUT: =894069, version=2
< t:2022-08-19 14:59:40,884 f:base.py         l:148  c:RemoteLibSSH2CmdRunner p:DEBUG >          =                       sectsz=512   sunit=0 blks, lazy-count=1
< t:2022-08-19 14:59:40,884 f:base.py         l:148  c:RemoteLibSSH2CmdRunner p:DEBUG > realtime =none                   extsz=4096   blocks=0, rtextents=0
< t:2022-08-19 14:59:40,884 f:base.py         l:148  c:RemoteLibSSH2CmdRunner p:DEBUG > Creating XFS volume for scylla using 1 disk(s): /dev/nvme1n1
< t:2022-08-19 14:59:40,884 f:base.py         l:148  c:RemoteLibSSH2CmdRunner p:DEBUG > RAID setup failed.
< t:2022-08-19 14:59:40,884 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > STDERR: INFO  2022-08-19 14:57:56,522 [shard 0] seastar - Created fair group io-queue-0, capacity rate 2147483:2147483, limit 12582912, rate 16777216 (factor 1), threshold 2000
< t:2022-08-19 14:59:40,884 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > INFO  2022-08-19 14:57:56,522 [shard 0] seastar - IO queue uses 0.75ms latency goal for device 0
< t:2022-08-19 14:59:40,884 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > INFO  2022-08-19 14:57:56,522 [shard 0] seastar - Created io group dev(0), length limit 4194304:4194304, rate 2147483647:2147483647
< t:2022-08-19 14:59:40,884 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > INFO  2022-08-19 14:57:56,522 [shard 0] seastar - Created io queue dev(0) capacities: 512:2000/2000 1024:3000/3000 2048:5000/5000 4096:9000/9000 8192:17000/17000 16384:33000/33000 32768:65000/65000 65536:129000/129000 131072:257000/257000
< t:2022-08-19 14:59:40,884 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > WARN  2022-08-19 14:57:56,593 [shard 0] iotune - Available space on filesystem at /var/tmp/mnt: 121 MB: is less than recommended: 10 GB
< t:2022-08-19 14:59:40,884 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > INFO  2022-08-19 14:57:56,593 [shard 0] iotune - /var/tmp/mnt passed sanity checks
< t:2022-08-19 14:59:40,884 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > Created symlink /etc/systemd/system/multi-user.target.wants/scylla-server.service → /lib/systemd/system/scylla-server.service.
< t:2022-08-19 14:59:40,884 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > A dependency job for var-lib-scylla.mount failed. See 'journalctl -xe' for details.
< t:2022-08-19 14:59:40,884 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > Traceback (most recent call last):
< t:2022-08-19 14:59:40,884 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >   File "/opt/scylladb/scripts/libexec/scylla_raid_setup", line 195, in <module>
< t:2022-08-19 14:59:40,884 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     mount.start()
< t:2022-08-19 14:59:40,884 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >   File "/opt/scylladb/scripts/scylla_util.py", line 352, in start
< t:2022-08-19 14:59:40,884 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     return run('systemctl {} start {}'.format(self.ctlparam, self._unit), shell=True, check=True)
< t:2022-08-19 14:59:40,884 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 528, in run
< t:2022-08-19 14:59:40,884 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     raise CalledProcessError(retcode, process.args,
< t:2022-08-19 14:59:40,884 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > subprocess.CalledProcessError: Command 'systemctl  start var-lib-scylla.mount' returned non-zero exit status 1. 
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor de480894-0e98-4f9e-832c-8f23a3133597`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=de480894-0e98-4f9e-832c-8f23a3133597)
- Show all stored logs command: `$ hydra investigate show-logs de480894-0e98-4f9e-832c-8f23a3133597`

## Logs:
- **db-cluster-de480894.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/de480894-0e98-4f9e-832c-8f23a3133597/20220807_181352/db-cluster-de480894.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/de480894-0e98-4f9e-832c-8f23a3133597/20220807_181352/db-cluster-de480894.tar.gz)
- **sct-runner-de480894.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/de480894-0e98-4f9e-832c-8f23a3133597/20220807_181352/sct-runner-de480894.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/de480894-0e98-4f9e-832c-8f23a3133597/20220807_181352/sct-runner-de480894.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/artifacts/job/artifacts-ubuntu2204-arm-test/15/)

**Comment by slivne** [comment]
@yaronkaikov / @syuu1228 please have a look - its blocking 5.0.2

**Comment by benipeled** [comment]
@KnifeyMoloko following our discussion, I didn't manage to reproduce it with the following steps

1. Install ubuntu22.04 (ami-078d455b3b6ad0d4e) on im4gn.xlarge with x2 500g-gp2 disks
2. Add the scylla.list from this build (https://s3.amazonaws.com/downloads.scylladb.com/unstable/scylla/branch-5.0/deb/unified/2022-08-07T16%3A18%3A51Z/scylladb-5.0/scylla.list)
3. Install scylla and run scylla_setup (all default YES except remote-syslog)
4. Start scylla-server service - the service is up and running and the cluster is on UN mode (var-lib-scylla is running as well)

You suspected some timing issue - please check it

**Comment by roydahan** [comment]
I think that @KnifeyMoloko ran another one and it passed.
Either it's a kernel issue that got fixed between the runs (@KnifeyMoloko can you check which kernel versions you had in each run) or it's a flakiness somewhere.

**Comment by syuu1228** [comment]
I also tried to reproduce it, but data volume initializing just worked fine.
But it's not first time we see `Command 'systemctl  start var-lib-scylla.mount' returned non-zero exit status 1`, I think there's some condition to cause timing bug there.

I do not have any evidence yet, but I'm guessing the error is related with UUID based disk path (/dev/disk/by-uuid).
I think current code does not waiting for /dev/disk/by-uuid/$UUID becomes ready, which is done by udevd.
It probably causing race condition vs mounting /dev/disk/by-uuid/$UUID and creating /dev/disk/by-uuid/$UUID by udevd.

We probably need to do very similar with 4a8ed4c but for mkfs.xfs, and wait for udev event completion.

Something like this:
```
    run('udevadm settle', shell=True, check=True)
    run(f'mkfs.xfs -b size={block_size} {fsdev} -f -K', shell=True, check=True)
    run('udevadm settle', shell=True, check=True)
    ....
    mount = systemd_unit(mntunit_bn)
    mount.start()
```

@avikivity What do you think?

**Comment by syuu1228** [comment]
@avikivity sent PR based on the comment above > #11399

**Comment by avikivity** [comment]
I want to backport, but IIRC there's a related bug in this area. Should I backport now or wait? @syuu1228

**Comment by fgelcer** [comment]
seeing it in recent build of the same job for `2022.2.0~rc3` in this [job here](https://jenkins.scylladb.com/job/enterprise-2022.2/job/artifacts-offline-install/job/artifacts-ubuntu2204-arm-test/6/)

@syuu1228 , should it be backported? other fixes too?

**Comment by avikivity** [comment]
@syuu1228 need advice about backport.

**Comment by fgelcer** [comment]
ping @syuu1228

**Comment by fgelcer** [comment]
ping @syuu1228

**Comment by syuu1228** [comment]
> I want to backport, but IIRC there's a related bug in this area. Should I backport now or wait? @syuu1228

the bug (#11617), and I sent a fix for this (#11666).
Let's merge it first, then we can backport #13999 and #11666 together.

**Comment by fgelcer** [comment]
@syuu1228 , seems like the backport fixed the issue we saw on `2022.2~rc4`, thank you

**Comment by avikivity** [comment]
Looks like it was backported to 5.1. Will backport further if problems are reported.

**Comment by yaronkaikov** [comment]
@avikivity Based on https://github.com/scylladb/scylla-enterprise/issues/2553, I think we need it also in 5.0 (and 2022.1)

**Comment by yaronkaikov** [comment]
> @avikivity Based on [scylladb/scylla-enterprise#2553](https://github.com/scylladb/scylla-enterprise/issues/2553), I think we need it also in 5.0 (and 2022.1)

@avikivity please backport to 5.0

/cc @mykaul @DoronArazii - let's track it

**Comment by DoronArazii** [comment]
@avikivity I added the "backport candidate" label back since it's needed in 5.0 - 2022.1

**Comment by avikivity** [comment]
@syuu1228 please help with the backport.

**Comment by syuu1228** [comment]
@avikivity Rebased patchset for branch-5.0: https://github.com/scylladb/scylladb/pull/13127

**Comment by yaronkaikov** [comment]
@avikivity It seems that this backport cause a regression in `5.0` , the artifacts failed with the following error:
```
File "/opt/scylladb/scripts/libexec/scylla_raid_setup", line 157, in <module>
uuid = out(f'blkid -s UUID -o value {fsdev}')
NameError: name 'out' is not defined
```
It seems that we also need https://github.com/scylladb/scylladb/commit/48b6aec16a76f8cd60babf97cede99e7c0e50db1

**Comment by avikivity** [comment]
It won't work since 5.0 doesn't have the out() function. @syuu1228 please advise.

**Comment by syuu1228** [comment]
@avikivity Looks like the patchset does not dequeued, so I sent the fix as new patch: 
 https://github.com/scylladb/scylladb/pull/13155

Does it correct way to fix?
Or do I need to send v2 patchset of https://github.com/scylladb/scylladb/pull/13127?

**Comment by avikivity** [comment]
Merged #13155.

**Comment by avikivity** [comment]
(#13127 could not be dequeued since it successfully promoted)

**Comment by DoronArazii** [comment]
We need to backport the [fix](https://github.com/scylladb/scylladb/pull/13803) once again.

**Comment by mykaul** [comment]
What's the latest status of backporting this?

**Comment by yaronkaikov** [comment]
https://github.com/scylladb/scylladb/pull/13803#issuecomment-1766018328

**Comment by yaronkaikov** [comment]
https://github.com/scylladb/scylladb/commit/5a05ccc2f897871df6d877e1d3a52a2c0981cc7c promoted to `branch-5.2` , closing
