### ISSUE TITLE
janusgraph-test: JanusGraphException: Could not commit transaction due to exception during persistence

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylladb#11371]
Janusgraph-test job [0] failed (last two runs) on testEdgesExceedCacheSize

[0] https://jenkins.scylladb.com/job/scylla-master/job/janusgraph-test/430/

```
15:07:41  Attempting to repair partially failed transaction [5@0a8e000913380-public-jenkins-builder1-qavpc38::2022-08-24T12:07:26.677Z]
15:07:41  Attempting to repair partially failed transaction [2@0a8e000913380-public-jenkins-builder1-qavpc38::2022-08-24T12:07:25.873Z]
15:16:59  [ERROR] Tests run: 182, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 926.516 s <<< FAILURE! - in org.janusgraph.graphdb.cql.CQLGraphCacheTest
15:16:59  [ERROR] testEdgesExceedCacheSize  Time elapsed: 102.512 s  <<< ERROR!
15:16:59  org.janusgraph.core.JanusGraphException: Could not commit transaction due to exception during persistence
15:16:59  Caused by: org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception
15:16:59  Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Could not successfully complete backend operation due to repeated temporary exceptions after PT1M40S
15:16:59  Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
15:16:59  Caused by: java.util.concurrent.ExecutionException: com.datastax.oss.driver.api.core.AllNodesFailedException: All 1 node(s) tried for the query failed (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=/172.17.0.1:53316, hostId=cea4eff9-1873-4815-becf-3f9726f4b6cc, hashCode=3612cc18): [com.datastax.oss.driver.api.core.NodeUnavailableException: No connection was available to Node(endPoint=/172.17.0.1:53316, hostId=cea4eff9-1873-4815-becf-3f9726f4b6cc, hashCode=3612cc18)]
15:16:59  Caused by: com.datastax.oss.driver.api.core.AllNodesFailedException: All 1 node(s) tried for the query failed (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=/172.17.0.1:53316, hostId=cea4eff9-1873-4815-becf-3f9726f4b6cc, hashCode=3612cc18): [com.datastax.oss.driver.api.core.NodeUnavailableException: No connection was available to Node(endPoint=/172.17.0.1:53316, hostId=cea4eff9-1873-4815-becf-3f9726f4b6cc, hashCode=3612cc18)]
15:16:59  
15:16:59  [INFO] Running org.janusgraph.graphdb.cql.CQLGraphTest
15:16:59  SLF4J: Class path contains multiple SLF4J bindings.
15:16:59  SLF4J: Found binding in [jar:file:/root/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.17.1/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
15:16:59  SLF4J: Found binding in [jar:file:/root/.m2/repository/ch/qos/logback/logback-classic/1.2.11/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
15:16:59  SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
15:16:59  SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
15:22:09  Failed message add
15:22:09  Failed message add
15:22:09  Failed message add
15:22:09  Failed message add
15:22:17  Attempting to repair partially failed transaction [3@0a8e000930999-public-jenkins-builder1-qavpc34::2022-08-24T12:22:02.764Z]
15:22:17  Attempting to repair partially failed transaction [4@0a8e000930999-public-jenkins-builder1-qavpc34::2022-08-24T12:22:02.775Z]
15:22:17  Attempting to repair partially failed transaction [5@0a8e000930999-public-jenkins-builder1-qavpc34::2022-08-24T12:22:02.889Z]
15:22:17  Attempting to repair partially failed transaction [2@0a8e000930999-public-jenkins-builder1-qavpc34::2022-08-24T12:22:02.084Z]
15:30:33  org.janusgraph.core.JanusGraphException: Could not commit transaction due to exception during persistence
15:30:33  	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1538)
15:30:33  	at org.janusgraph.graphdb.JanusGraphTest$4.run(JanusGraphTest.java:3194)
15:30:33  Caused by: org.janusgraph.diskstorage.locking.PermanentLockingException: Local lock contention
15:30:33  	at org.janusgraph.diskstorage.locking.AbstractLocker.writeLock(AbstractLocker.java:324)
15:30:33  	at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingStore.acquireLock(ExpectedValueCheckingStore.java:102)
15:30:33  	at org.janusgraph.diskstorage.keycolumnvalue.KCVSProxy.acquireLock(KCVSProxy.java:52)
15:30:33  	at org.janusgraph.diskstorage.BackendTransaction.acquireEdgeLock(BackendTransaction.java:234)
15:30:33  	at org.janusgraph.graphdb.database.StandardJanusGraph.prepareCommit(StandardJanusGraph.java:663)
15:30:33  	at org.janusgraph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:825)
15:30:33  	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1527)
.
.
.
15:40:10  [INFO] 
15:40:10  [INFO] Results:
15:40:10  [INFO] 
15:40:10  [ERROR] Errors: 
15:40:10  [ERROR]   CQLGraphCacheTest>JanusGraphTest.testEdgesExceedCacheSize:4423 » JanusGraph Co...
15:40:10  [INFO] 
15:40:10  [ERROR] Tests run: 587, Failures: 0, Errors: 1, Skipped: 7
15:40:10  [INFO] 
15:40:10  [INFO] ------------------------------------------------------------------------
15:40:10  [INFO] BUILD FAILURE
15:40:10  [INFO] ------------------------------------------------------------------------
15:40:10  [INFO] Total time:  01:01 h
15:40:10  [INFO] Finished at: 2022-08-24T12:39:59Z
15:40:10  [INFO] ------------------------------------------------------------------------
15:40:10  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (cql-test) on project janusgraph-cql: There are test failures.
15:40:10  [ERROR] 
15:40:10  [ERROR] Please refer to /janusgraph/janusgraph-cql/target/surefire-reports for the individual test results.
15:40:10  [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
15:40:10  [ERROR] -> [Help 1]
15:40:10  [ERROR] 
15:40:10  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
15:40:10  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
15:40:10  [ERROR] 
15:40:10  [ERROR] For more information about the errors and possible solutions, please read the following articles:
15:40:10  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
15:40:10  Docker exitcode: 1
```

**Comment by roydahan** [comment]
Is it still failing?
I think that the last few jobs passed.

**Comment by roydahan** [comment]
The test passed in later builds (e.g. https://jenkins.scylladb.com/job/scylla-master/job/janusgraph-test/433/testReport/junit/org.janusgraph.graphdb.cql/CQLGraphCacheTest/testEdgesExceedCacheSize/).

Closing.

**Comment by benipeled** [comment]
Failed again https://jenkins.scylladb.com/job/scylla-master/job/janusgraph-test/446/

**Comment by mykaul** [comment]
@benipeled - please disable the test. It's failing, yet no one is looking at it - why continue to run it?

**Comment by fruch** [comment]
the failure is different then one reported here:
```
Caused by: com.github.dockerjava.api.exception.BadRequestException: Status 400: {"message":"failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/janusgraph/janusgraph-cql/target/test-classes/scylla-murmur.yaml\" to rootfs at \"/etc/scylla/scylla.yaml\": mount /janusgraph/janusgraph-cql/target/test-classes/scylla-murmur.yaml:/etc/scylla/scylla.yaml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type"}
```

**Comment by mykaul** [comment]
> the failure is different then one reported here:
> 
> ```
> Caused by: com.github.dockerjava.api.exception.BadRequestException: Status 400: {"message":"failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/janusgraph/janusgraph-cql/target/test-classes/scylla-murmur.yaml\" to rootfs at \"/etc/scylla/scylla.yaml\": mount /janusgraph/janusgraph-cql/target/test-classes/scylla-murmur.yaml:/etc/scylla/scylla.yaml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type"}
> ```

Yes, I saw that. The request was to disable the test - no one's looking at it, it makes little sense to keep it running.

**Comment by fruch** [comment]
> > the failure is different then one reported here:
> > ```
> > Caused by: com.github.dockerjava.api.exception.BadRequestException: Status 400: {"message":"failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/janusgraph/janusgraph-cql/target/test-classes/scylla-murmur.yaml\" to rootfs at \"/etc/scylla/scylla.yaml\": mount /janusgraph/janusgraph-cql/target/test-classes/scylla-murmur.yaml:/etc/scylla/scylla.yaml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type"}
> > ```
> 
> Yes, I saw that. The request was to disable the test - no one's looking at it, it makes little sense to keep it running.

also it's on all releases, not just on master

**Comment by roydahan** [comment]
We used this test suite to ensure that our compatibility with Janus is kept on our end.

Since we moved to Argus we probably stopped monitoring it.

**Comment by mykaul** [comment]
It's worth resurrecting, I think it's a good use case.
