### ISSUE TITLE
test.py doesn't always save logs

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#11486]
Take the (broken) branch from https://github.com/xemul/scylla/tree/br-snitch-dont-mess-with-topology-data
Then 
```
15:57:47 xemul@samson:~/src/scylla $ rm -rf testlog/*
15:58:34 xemul@samson:~/src/scylla $ ./test.py --mode dev topology/test_random_tables 
Found 1 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/home/xemul/src/scylla/./test.py", line 1340, in workaround_python26789
    code = await main()
  File "/home/xemul/src/scylla/./test.py", line 1307, in main
    await run_all_tests(signaled, options)
  File "/home/xemul/src/scylla/./test.py", line 1183, in run_all_tests
    await reap(done, pending, signaled)
  File "/home/xemul/src/scylla/./test.py", line 1165, in reap
    result = coro.result()
  File "/home/xemul/src/scylla/./test.py", line 187, in run
    await test.run(options)
  File "/home/xemul/src/scylla/./test.py", line 841, in run
    async with get_cluster_manager(self.shortname, self.suite.clusters, test_path) as manager:
  File "/usr/lib64/python3.10/contextlib.py", line 206, in __aexit__
    await anext(self.gen)
  File "/home/xemul/src/scylla/test/pylib/scylla_cluster.py", line 846, in get_cluster_manager
    await manager.stop()
  File "/home/xemul/src/scylla/test/pylib/scylla_cluster.py", line 711, in stop
    self.cluster.after_test(self.test_name)
  File "/home/xemul/src/scylla/test/pylib/scylla_cluster.py", line 590, in after_test
    assert self.start_exception is None
AssertionError
15:58:46 xemul@samson:~/src/scylla $ find testlog/
testlog/
testlog/test.py.log
testlog/dev
testlog/dev/manager-rb7p3b_r
testlog/dev/manager-rb7p3b_r/api
testlog/dev/xml
testlog/dev/xml/test_random_tables.1.xunit.xml

```
No logs :(

**Comment by kostja** [comment]
Also we're observing that test.py now *eagerly * starts all suite clusters, even if one runs just one test from a suite (so other clusters will not be used at all). This is also looking like a change introduced by scylla manager, and not evident at first sight - but before, we would start clusters on demand, so if there are fewer tests than the size of the suite cluster pool, extra clusters were not started.

**Comment by alecco** [comment]
@xemul I'm still waiting my `release` build of your branch...

Meanwhile, can you try with this fix?  https://github.com/alecco/scylladb/tree/xemul-br-snitch-dont-mess-with-topology-data

**Comment by xemul** [comment]
@alecco , I tried testing your patch, but surprisingly -- it made test.py pass (I dunno why -- or the test really passed or test.py stopped treating the result as failure) :man_shrugging: 

```shell
20:00:22 xemul@samson:~/src/scylla $ rm -rf testlog/*
20:00:25 xemul@samson:~/src/scylla $ ./test.py --mode dev topology/test_random_tables 
Found 1 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/home/xemul/src/scylla/./test.py", line 1340, in workaround_python26789
    code = await main()
  File "/home/xemul/src/scylla/./test.py", line 1307, in main
    await run_all_tests(signaled, options)
  File "/home/xemul/src/scylla/./test.py", line 1183, in run_all_tests
    await reap(done, pending, signaled)
  File "/home/xemul/src/scylla/./test.py", line 1165, in reap
    result = coro.result()
  File "/home/xemul/src/scylla/./test.py", line 187, in run
    await test.run(options)
  File "/home/xemul/src/scylla/./test.py", line 841, in run
    async with get_cluster_manager(self.shortname, self.suite.clusters, test_path) as manager:
  File "/usr/lib64/python3.10/contextlib.py", line 206, in __aexit__
    await anext(self.gen)
  File "/home/xemul/src/scylla/test/pylib/scylla_cluster.py", line 846, in get_cluster_manager
    await manager.stop()
  File "/home/xemul/src/scylla/test/pylib/scylla_cluster.py", line 711, in stop
    self.cluster.after_test(self.test_name)
  File "/home/xemul/src/scylla/test/pylib/scylla_cluster.py", line 590, in after_test
    assert self.start_exception is None
AssertionError
20:00:37 xemul@samson:~/src/scylla $ find testlog/
testlog/
testlog/test.py.log
testlog/dev
testlog/dev/manager-vqepyz53
testlog/dev/manager-vqepyz53/api
testlog/dev/xml
testlog/dev/xml/test_random_tables.1.xunit.xml
20:00:39 xemul@samson:~/src/scylla $ rm -rf testlog/*                 
20:00:42 xemul@samson:~/src/scylla $ patch -p1 < patch 
patching file test/pylib/scylla_cluster.py
20:00:46 xemul@samson:~/src/scylla $ ./test.py --mode dev topology/test_random_tables 
Found 1 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------
[1/1]      topology   dev   [ PASS ] test_random_tables.1
------------------------------------------------------------------------------
20:01:23 xemul@samson:~/src/scylla $ find testlog/
testlog/
testlog/test.py.log
testlog/dev
testlog/dev/xml
testlog/dev/xml/boost.xunit.xml
testlog/dev/xml/test_random_tables.1.xunit.xml
testlog/dev/xml/junit.xml
20:01:30 xemul@samson:~/src/scylla $ rm -rf testlog/*
20:01:32 xemul@samson:~/src/scylla $ ./test.py --mode dev topology/test_random_tables 
Found 1 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------
[1/1]      topology   dev   [ PASS ] test_random_tables.1
------------------------------------------------------------------------------
```

**Comment by alecco** [comment]
@xemul yes there's a problem with handling exceptions and pre-test checks
