### ISSUE TITLE
read query timing out with mixed cluster, for no apparent reason

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylladb#11551]
i'm seeing a failure, in a mixed cluster (upgrading from `4.6.7-20220907.7c79c513d with build-id 7f2aa7967d95abbd332b0d3cfab88326c258183d` to `5.0.3-20220907.b9a61c8e9 with build-id 7be266d2954825cdf843c744de04a0443a8f156c`, during querying the DB in a step called `Verify data during mixed cluster mode`..

the error is the follows:
```
2022-09-13 21:04:05.292: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=fac95018-5457-4856-ae9f-bc47ad50e26d, source=UpgradeTest.test_rolling_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 630, in test_rolling_upgrade
    self.fill_and_verify_db_data('after rollback the second node')
  File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 465, in fill_and_verify_db_data
    self.verify_db_data()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3362, in verify_db_data
    self.run_db_queries(session, session.default_fetch_size)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3296, in run_db_queries
    self._run_db_queries(item, session)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3256, in _run_db_queries
    raise ex
  File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3252, in _run_db_queries
    res = session.execute(item['queries'][i])
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1329, in execute_verbose
    return execute_orig(*args, **kwargs)
  File "cassandra/cluster.py", line 2668, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4953, in cassandra.cluster.ResponseFuture.result
cassandra.OperationTimedOut: errors={<Host: 10.0.0.169:9042 eu-west>: ReadTimeout('Error from server: code=1200 [Coordinator node timed out waiting for replica nodes\' responses] message="Operation timed out for ks_no_range_ghost_test.users - received only 0 responses from 1 CL=QUORUM." info={\'consistency\': \'QUORUM\', \'required_responses\': 1, \'received_responses\': 0}')}, last_host=10.0.0.169:9042
```

it happened for the 2nd time in a row, during the same step, in a very similar way

following a suspicious of some regression introduced between 5.0.2..5.1.0~dev (#11459) i have listed the commits between `5.0.2` (that passed without pain, to `5.0.3` and i found this list:
```
b9a61c8e9 release: prepare for 5.0.3
32aa1e528 transport/server.cc: Return correct size of decompressed lz4 buffer
da6a126d7 cross-tree: fix header file self-sufficiency
d07e90298 Merge 'database: evict all inactive reads for table when detaching table' from Botond Dénes
3c0fc42f8 cql3: fix misleading error message for service level timeouts
964ccf919 type_json: support integers in scientific format
dfdc128fa Merge 'row_cache: Fix missing row if upper bound of population range is evicted and has adjacent dummy' from Tomasz Grabiec
```

i suspect d07e90298 Merge 'database: evict all inactive reads for table when detaching table' from Botond Dénes could be the culprit (and perhaps a similar problem as described in this issue)

## Installation details

Kernel Version: 5.11.0-1022-aws
Scylla version (or git commit hash): `4.6.7-20220907.7c79c513d` with build-id `7f2aa7967d95abbd332b0d3cfab88326c258183d`

Cluster size: 4 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- rolling-upgrade--centos-db-node-89584f3b-4 (34.240.236.130 | 10.0.0.30) (shards: 8)
- rolling-upgrade--centos-db-node-89584f3b-3 (34.246.195.193 | 10.0.0.169) (shards: 8)
- rolling-upgrade--centos-db-node-89584f3b-2 (34.252.209.163 | 10.0.3.1) (shards: 8)
- rolling-upgrade--centos-db-node-89584f3b-1 (54.247.57.156 | 10.0.2.63) (shards: 8)

OS / Image: `ami-0495d42df0c539ce9` (aws: eu-west-1)

Test: `rolling-upgrade-ami-test`
Test id: `89584f3b-0f1b-4e85-988d-87bbad985fc5`
Test name: `scylla-5.0/rolling-upgrade/rolling-upgrade-ami-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d06e8a1090eb7220914c402f8e82cd4896af1df2/test-cases/upgrades/rolling-upgrade.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor 89584f3b-0f1b-4e85-988d-87bbad985fc5`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=89584f3b-0f1b-4e85-988d-87bbad985fc5)
- Show all stored logs command: `$ hydra investigate show-logs 89584f3b-0f1b-4e85-988d-87bbad985fc5`

## Logs:
- **db-cluster-89584f3b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/89584f3b-0f1b-4e85-988d-87bbad985fc5/20220913_211336/db-cluster-89584f3b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/89584f3b-0f1b-4e85-988d-87bbad985fc5/20220913_211336/db-cluster-89584f3b.tar.gz)
- **monitor-set-89584f3b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/89584f3b-0f1b-4e85-988d-87bbad985fc5/20220913_211336/monitor-set-89584f3b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/89584f3b-0f1b-4e85-988d-87bbad985fc5/20220913_211336/monitor-set-89584f3b.tar.gz)
- **loader-set-89584f3b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/89584f3b-0f1b-4e85-988d-87bbad985fc5/20220913_211336/loader-set-89584f3b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/89584f3b-0f1b-4e85-988d-87bbad985fc5/20220913_211336/loader-set-89584f3b.tar.gz)
- **sct-runner-89584f3b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/89584f3b-0f1b-4e85-988d-87bbad985fc5/20220913_211336/sct-runner-89584f3b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/89584f3b-0f1b-4e85-988d-87bbad985fc5/20220913_211336/sct-runner-89584f3b.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/rolling-upgrade/job/rolling-upgrade-ami-test/34/)

**Comment by DoronArazii** [comment]
@denesb / @tgrabiec please check the commits above, it might cause some issues

**Comment by denesb** [comment]
> i suspect https://github.com/scylladb/scylladb/commit/d07e902983c5a787ae1c78cd562bf5770cee9245 Merge 'database: evict all inactive reads for table when detaching table' from Botond Dénes could be the culprit (and perhaps a similar problem as described in this issue)

This has nothing to do with reads, unless you are also dropping the table during the test.

Does this mixed cluster test do range scans?

**Comment by fgelcer** [comment]
> Does this mixed cluster test do range scans?

not at the point we saw the failure

**Comment by denesb** [comment]
Closing as stale.
