### ISSUE TITLE
scylla_setup script fails with: Exception: /dev/disk/by-uuid/10802a22-9562-4a01-b84f-6722eb44d300 is not found

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#11617]
## Installation details

Cluster size: 1 nodes (n1-standard-2)

Scylla Nodes used in this run:
- artifacts-debian11-jenkins-db-node-9ce521ed-0-1 (34.139.182.190 | 10.142.0.94) (shards: 2)

OS / Image: `https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-11` (gce: us-east1)

Test: `artifacts-debian11-test`
Test id: `9ce521ed-55a3-4132-914f-e93e7d310342`
Test name: `scylla-master/artifacts/artifacts-debian11-test`
Test config file(s):

- [debian11.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/801435dc23af9a7675a01e41286d77b3f20ea23a/test-cases/artifacts/debian11.yaml)

## Issue description

**>>>>>>>**
scylla_setup script got the following error:
```

2022-09-19 06:57:44.060: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=c4687a2d-af7c-47bc-abf1-6102d8c172d3, source=ArtifactsTest.SetUp()
exception=[Node artifacts-debian11-jenkins-db-node-9ce521ed-0-1 [34.139.182.190 | 10.142.0.94] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --nic ens5 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
Exit code: 1
Stdout:
data     =                       bsize=4096   blocks=98304000, imaxpct=25
=                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=4096   blocks=48000, version=2
=                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
Creating XFS volume for scylla using 1 disk(s): /dev/nvme0n1
Debug log created: /var/tmp/scylla/scylla_raid_setup-119988-debug.log
You current Scylla release is 5.2.0~dev while the latest patch release is 5.0.3, update for the latest bug fixes and improvements
RAID setup failed.
Stderr:
perl: warning: Please check that your locale settings:
LANGUAGE = (unset),
LC_ALL = "en_US.UTF-8",
LANG = "C.UTF-8"
are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
Traceback (most recent call last):
File "/opt/scylladb/scripts/libexec/scylla_raid_setup", line 163, in <module>
raise Exception(f'{uuidpath} is not found')
Exception: /dev/disk/by-uuid/10802a22-9562-4a01-b84f-6722eb44d300 is not found
Traceback (most recent call last):
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-debian11-test/scylla-cluster-tests/sdcm/cluster.py", line 3455, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-debian11-test/scylla-cluster-tests/sdcm/cluster.py", line 4155, in node_setup
self._scylla_post_install(node, install_scylla, nic_devname)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-debian11-test/scylla-cluster-tests/sdcm/cluster.py", line 4231, in _scylla_post_install
node.scylla_setup(disks, devname)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-debian11-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 116, in inner
res = func(*args, **kwargs)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-debian11-test/scylla-cluster-tests/sdcm/cluster.py", line 2165, in scylla_setup
self.remoter.run('sudo /usr/lib/scylla/scylla_setup --nic {} --disks {} --setup-nic-and-disks {}'
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-debian11-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-debian11-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
return func(*args, **kwargs)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-debian11-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-debian11-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-debian11-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/jenkins/slave/workspace/scylla-master/artifacts/artifacts-debian11-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --nic ens5 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
Exit code: 1
Stdout:
data     =                       bsize=4096   blocks=98304000, imaxpct=25
=                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=4096   blocks=48000, version=2
=                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
Creating XFS volume for scylla using 1 disk(s): /dev/nvme0n1
Debug log created: /var/tmp/scylla/scylla_raid_setup-119988-debug.log
You current Scylla release is 5.2.0~dev while the latest patch release is 5.0.3, update for the latest bug fixes and improvements
RAID setup failed.
Stderr:
perl: warning: Please check that your locale settings:
LANGUAGE = (unset),
LC_ALL = "en_US.UTF-8",
LANG = "C.UTF-8"
are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
Traceback (most recent call last):
File "/opt/scylladb/scripts/libexec/scylla_raid_setup", line 163, in <module>
raise Exception(f'{uuidpath} is not found')
Exception: /dev/disk/by-uuid/10802a22-9562-4a01-b84f-6722eb44d300 is not found
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 9ce521ed-55a3-4132-914f-e93e7d310342`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=9ce521ed-55a3-4132-914f-e93e7d310342)
- Show all stored logs command: `$ hydra investigate show-logs 9ce521ed-55a3-4132-914f-e93e7d310342`

## Logs:
- **db-cluster-9ce521ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9ce521ed-55a3-4132-914f-e93e7d310342/20220919_065818/db-cluster-9ce521ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9ce521ed-55a3-4132-914f-e93e7d310342/20220919_065818/db-cluster-9ce521ed.tar.gz)
- **sct-runner-9ce521ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9ce521ed-55a3-4132-914f-e93e7d310342/20220919_065818/sct-runner-9ce521ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9ce521ed-55a3-4132-914f-e93e7d310342/20220919_065818/sct-runner-9ce521ed.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-debian11-test/72/)

**Comment by rayakurl** [comment]
@fgelcer , @yarongilor  - I think that I hit a reproduction on enterprise-2022.2/artifacts/artifacts-debian11-test:(https://argus.scylladb.com/test/f707803f-c47e-49dc-a21b-26a1a8e6e3a6/runs?additionalRuns[]=9bc12f57-6835-4ef8-90fa-b1dd825345ce): https://argus.scylladb.com/workspace?state=WyJmNzA3ODAzZi1jNDdlLTQ5ZGMtYTIxYi0yNmExYThlNmUzYTYiXQ

which information is missing? I can probably add it

**Comment by fgelcer** [comment]
i have asked it to @yarongilor in Argus, but i copy here my questions to be share with everyone hitting this issue:

> it failed to create the disk? just failed to attach it? was the disk correctly created? did we have some failure we can see in the console?
> 
> has some code changed in scylla_setup code that might justify this new failure?

**Comment by fgelcer** [comment]
maybe @syuu1228 can help us identify the problem

**Comment by syuu1228** [comment]
Looks like recent commit #11399 introduce the error, but the change was for generating more user friendly error message, and the target device (/dev/disk/by-uuid/10802a22-9562-4a01-b84f-6722eb44d300) should exists at this point, since we mount the device just after this line.
So something is going wrong.. maybe it's still timing problem (we should wait more for the device file creation), or it's really not exists for some other reasons.

**Comment by slivne** [comment]
Who needs to wait ? 
Is this in scylla code ?
Are you sending a fix

**Comment by syuu1228** [comment]
On #11399, I was thinking `udevadm settle` after `mkfs.xfs` gurantee UUID device file existance (since the command should block the creation finishes), but the SCT result it isn't, at least on some condition.

So I sent new PR to stop checking UUID device file existance before running `systemctl start var-lib-scylla.mount`, checking it only the service failed to start, to make better error message.
https://github.com/scylladb/scylladb/pull/11666

**Comment by syuu1228** [comment]
I guess this is enough to avoid this error and also `'systemctl  start var-lib-scylla.mount' returned non-zero exit status 1` error on #11359.

But if we still get `'systemctl  start var-lib-scylla.mount' returned non-zero exit status 1` even after merging #11666, I guess we need to try more ad-hoc way, such as stop using systemd unit file to mount the volume on first boot, just run  `mount $fsdev $mount_at`  instead. We will use systemd unit file on after rebooted.

**Comment by DoronArazii** [comment]
@syuu1228 ping - what's the progress here?

**Comment by roydahan** [comment]
Removing the high label, since all runs after this fail (at least 10) on master passed without any issue.

**Comment by roydahan** [comment]
The runs of 5.1 and 2022.2 also pass now, so @syuu1228 I don't mind to close this issue.

**Comment by roydahan** [comment]
According to @rayakurl (please add the details) this is still failing in 5.1.rc3.
Adding back to 5.1 and putting the high lable.

**Comment by roydahan** [comment]
There is a PR waiting for backport - https://github.com/scylladb/scylladb/issues/11359

**Comment by rayakurl** [comment]
@roydahan - do you still need the details?

**Comment by roydahan** [comment]
Yes

**Comment by syuu1228** [comment]
I sent a PR https://github.com/scylladb/scylladb/pull/11666 to fix the issue and waiting for merge

**Comment by avikivity** [comment]
@syuu1228 I want to backport, but it doesn't backport cleanly. Are there other backports needed first?

**Comment by syuu1228** [comment]
@avikivity Please backport these 3 commits together:
`git cherry-pick 40134efee4ca23203c967f6b5eaf3b1982f6cd36 8835a34ab60f1d47215c537aa2a91a05a3504ff2 a938b009ca6a8914be582e1886d8231bfb4d13d6`
It at least works for branch-2022.2.

**Comment by avikivity** [comment]
Backported to 5.1. Please advise if backports to older versions are needed (hopefully not).

**Comment by avikivity** [comment]
@syuu1228 ^

**Comment by denesb** [comment]
All live versions have this, removing label.
