### ISSUE TITLE
Streaming failed on rebuild for 5000 tables test

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#11655]
## Installation details

Kernel Version: 5.15.0-1019-aws
Scylla version (or git commit hash): `2022.2.0~rc1-20220902.a9bc6d191031` with build-id `074a0cb9e6a5ab36ba5e7f81385e68079ab6eeda`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla-enterprise/relocatable/scylladb-2022.2/scylla-enterprise-x86_64-package-2022.2.0-rc1.0.20220902.a9bc6d191031.tar.gz
Cluster size: 1 nodes (i3.8xlarge)

Scylla Nodes used in this run:
- longevity-5000-tables-scale-te-db-node-9432a26c-7 (176.34.94.226 | 10.4.1.154) (shards: -1)
- longevity-5000-tables-scale-te-db-node-9432a26c-6 (34.247.69.21 | 10.4.1.147) (shards: 30)
- longevity-5000-tables-scale-te-db-node-9432a26c-5 (52.48.210.162 | 10.4.3.131) (shards: 30)
- longevity-5000-tables-scale-te-db-node-9432a26c-4 (52.50.144.231 | 10.4.0.121) (shards: 30)
- longevity-5000-tables-scale-te-db-node-9432a26c-3 (54.154.228.197 | 10.4.2.4) (shards: 30)
- longevity-5000-tables-scale-te-db-node-9432a26c-2 (54.75.40.247 | 10.4.3.250) (shards: 30)
- longevity-5000-tables-scale-te-db-node-9432a26c-1 (52.51.92.89 | 10.4.3.123) (shards: 30)

OS / Image: `ami-0492fd8e302e5af45` (aws: eu-west-1)

Test: `scale-5000-tables-test`
Test id: `9432a26c-4f6a-472e-82fc-12eda02a1916`
Test name: `enterprise-2022.2/scale/scale-5000-tables-test`
Test config file(s):

- [longevity-5000-tables.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/6f275e01e52e838da724c69e0416d2da8078b514/test-cases/scale/longevity-5000-tables.yaml)

## Issue description

When testing Scylla with 5000 tables, during `disrupt_destroy_data_then_rebuild` nemesis which does:
1. Stop scylla
2. Delete 5 data files
3. Start scylla
4. Run `nodetool rebuild`

During rebuild stage, Scylla started to raise multiple errors related to too many open files on target node:
```
2022-09-29T00:17:22+00:00 longevity-5000-tables-scale-te-db-node-9432a26c-4      !ERR | scylla[25009]:  [shard 10] sstable - Could not create SSTable component /var/lib/scylla/data/feeds/table95-7e959b203f2f11eda9d0905d8dc0ff2d/1360.sstable/me-1360-big-Data.db. Found exception: std::filesystem::__cxx11::filesystem_error (error system:24, filesystem error: open failed: Too many open files [/var/lib/scylla/data/feeds/table95-7e959b203f2f11eda9d0905d8dc0ff2d/1360.sstable/me-1360-big-Data.db])
```
Eventually failing rebuild process:
```
Command: '/usr/bin/nodetool  rebuild '
Exit code: 1
Stdout:
nodetool: Scylla API server HTTP POST to URL '/storage_service/rebuild' failed: streaming::stream_exception (Stream failed)
See 'nodetool help' or 'nodetool help <command>'.
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 9432a26c-4f6a-472e-82fc-12eda02a1916`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=9432a26c-4f6a-472e-82fc-12eda02a1916)
- Show all stored logs command: `$ hydra investigate show-logs 9432a26c-4f6a-472e-82fc-12eda02a1916`

## Logs:
- **db-cluster-9432a26c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/db-cluster-9432a26c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/db-cluster-9432a26c.tar.gz)
- **monitor-set-9432a26c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/monitor-set-9432a26c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/monitor-set-9432a26c.tar.gz)
- **loader-set-9432a26c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/loader-set-9432a26c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/loader-set-9432a26c.tar.gz)
- **sct-runner-9432a26c.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/sct-runner-9432a26c.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9432a26c-4f6a-472e-82fc-12eda02a1916/20220929_080439/sct-runner-9432a26c.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/scale/job/scale-5000-tables-test/5/)

**Comment by DoronArazii** [comment]
@raphaelsc we have here too many open files, please try to assist

**Comment by bhalevy** [comment]
Can use offstrategy compaction to reduce the number of (small) sstables during the rebuild process?

**Comment by soyacz** [comment]
I don't know - we didn't run this nemesis for this test in previous releases

**Comment by avikivity** [comment]
Let's have a field in the report form for regression status: yes (working in x.y), no, unknown, unknown (new test). @roydahan 

Please run the test against an older version so we know if it's a regression or not.

**Comment by fgelcer** [comment]
> Let's have a field in the report form for regression status: yes (working in x.y), no, unknown, unknown (new test). @roydahan
> 
> Please run the test against an older version so we know if it's a regression or not.

i see that running with `Scylla 2022.1.2-20220905.f1a246a8b build-id aae082a8a9a1136b4d3f3751749267327a63014b` also has similar failure, although the nemesis passed twice, and failed in the 3rd and 4th runs:

```
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3391, in wrapper
    result = method(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 839, in disrupt_destroy_data_then_rebuild
    self.repair_nodetool_rebuild()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 1464, in repair_nodetool_rebuild
    self.target_node.run_nodetool('rebuild')
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2598, in run_nodetool
    self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: '/usr/bin/nodetool  rebuild '

Exit code: 1

Stdout:

nodetool: Scylla API server HTTP POST to URL '/storage_service/rebuild' failed: streaming::stream_exception (Stream failed)
See 'nodetool help' or 'nodetool help <command>'.

Stderr:
```




## Installation details

Kernel Version: 5.15.0-1019-aws
Scylla version (or git commit hash): `2022.1.2-20220905.f1a246a8b` with build-id `aae082a8a9a1136b4d3f3751749267327a63014b`

Cluster size: 1 nodes (i3.8xlarge)

Scylla Nodes used in this run:
- longevity-5000-tables-reproduc-db-node-8db6ab30-6 (3.250.220.62 | 10.0.1.209) (shards: 30)
- longevity-5000-tables-reproduc-db-node-8db6ab30-5 (79.125.34.166 | 10.0.1.25) (shards: 30)
- longevity-5000-tables-reproduc-db-node-8db6ab30-4 (34.255.6.152 | 10.0.0.230) (shards: 30)
- longevity-5000-tables-reproduc-db-node-8db6ab30-3 (52.212.41.113 | 10.0.2.215) (shards: 30)
- longevity-5000-tables-reproduc-db-node-8db6ab30-2 (54.75.69.167 | 10.0.0.63) (shards: 30)
- longevity-5000-tables-reproduc-db-node-8db6ab30-1 (54.154.70.125 | 10.0.1.160) (shards: 30)


OS / Image: `ami-0ba5ceb867818a6ad` (aws: eu-west-1)

Test: `scale-5000-tables-test`
Test id: `8db6ab30-2633-481c-8dd0-4a0c86d3a287`
Test name: `scylla-staging/lukasz/scale-5000-tables-test`
Test config file(s):

- [longevity-5000-tables.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/62dbcd4cfd040a9b79c3db0f42ca0a1f7db4a183/test-cases/scale/longevity-5000-tables.yaml)

## Issue description

**>>>>>>>**
**Your description here...**
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 8db6ab30-2633-481c-8dd0-4a0c86d3a287`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=8db6ab30-2633-481c-8dd0-4a0c86d3a287)
- Show all stored logs command: `$ hydra investigate show-logs 8db6ab30-2633-481c-8dd0-4a0c86d3a287`

## Logs:
- **db-cluster-8db6ab30.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8db6ab30-2633-481c-8dd0-4a0c86d3a287/20220930_215309/db-cluster-8db6ab30.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8db6ab30-2633-481c-8dd0-4a0c86d3a287/20220930_215309/db-cluster-8db6ab30.tar.gz)
- **monitor-set-8db6ab30.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8db6ab30-2633-481c-8dd0-4a0c86d3a287/20220930_215309/monitor-set-8db6ab30.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8db6ab30-2633-481c-8dd0-4a0c86d3a287/20220930_215309/monitor-set-8db6ab30.tar.gz)
- **loader-set-8db6ab30.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8db6ab30-2633-481c-8dd0-4a0c86d3a287/20220930_215309/loader-set-8db6ab30.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8db6ab30-2633-481c-8dd0-4a0c86d3a287/20220930_215309/loader-set-8db6ab30.tar.gz)
- **sct-runner-8db6ab30.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8db6ab30-2633-481c-8dd0-4a0c86d3a287/20220930_215309/sct-runner-8db6ab30.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8db6ab30-2633-481c-8dd0-4a0c86d3a287/20220930_215309/sct-runner-8db6ab30.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/lukasz/job/scale-5000-tables-test/2/)

**Comment by asias** [comment]
Off strategy is not enabled for rebuild ops using the classic streaming. 

If we run rebuild with RBNO, the problem should be gone: 

--enable-repair-based-node-ops true --allowed-repair-based-node-ops rebuild

**Comment by fgelcer** [comment]
> Off strategy is not enabled for rebuild ops using the classic streaming.
> 
> If we run rebuild with RBNO, the problem should be gone:
> 
> --enable-repair-based-node-ops true --allowed-repair-based-node-ops rebuild

@asias , but it is not enabled by default on 5.1 / 2022.2 (nor 5.0 / 2022.1)...

**Comment by asias** [comment]
> > Off strategy is not enabled for rebuild ops using the classic streaming.
> > If we run rebuild with RBNO, the problem should be gone:
> > --enable-repair-based-node-ops true --allowed-repair-based-node-ops rebuild
> 
> @asias , but it is not enabled by default on 5.1 / 2022.2 (nor 5.0 / 2022.1)...

I know that. If the above helps, it at least tells us if off strategy would help.

Is this a new test? Is this a regression?

**Comment by fgelcer** [comment]
> > > Off strategy is not enabled for rebuild ops using the classic streaming.
> > > If we run rebuild with RBNO, the problem should be gone:
> > > --enable-repair-based-node-ops true --allowed-repair-based-node-ops rebuild
> > 
> > 
> > @asias , but it is not enabled by default on 5.1 / 2022.2 (nor 5.0 / 2022.1)...
> 
> I know that. If the above helps, it at least tells us if off strategy would help.
> 
> Is this a new test? Is this a regression?

not a new test, and AFAICT this is a regression

**Comment by avikivity** [comment]
@asias please see what can be done

**Comment by soyacz** [comment]
> not a new test, and AFAICT this is a regression

It failed with the same error for reproducer on 2022.1.2 - so it's not a regression for 2022.2

@asias I can start another reproducer if you want to take a look into running cluster. Ping me on slack/google chat.

**Comment by asias** [comment]
> > not a new test, and AFAICT this is a regression
> 
> It failed with the same error for reproducer on 2022.1.2 - so it's not a regression for 2022.2

I want to know if this test has ever passed? Which version has passed? E.g. if 2021.1.X has passed but 2022.1 started to fail. 

> 
> @asias I can start another reproducer if you want to take a look into running cluster. Ping me on slack/google chat.

Let's understand more before we run more tests.

**Comment by soyacz** [comment]
> > > not a new test, and AFAICT this is a regression
> > 
> > 
> > It failed with the same error for reproducer on 2022.1.2 - so it's not a regression for 2022.2
> 
> I want to know if this test has ever passed? Which version has passed? E.g. if 2021.1.X has passed but 2022.1 started to fail.
> 
> > @asias I can start another reproducer if you want to take a look into running cluster. Ping me on slack/google chat.
> 
> Let's understand more before we run more tests.

This nemesis was not run before for this test - so I cannot say.

**Comment by avikivity** [comment]
```
2022-09-29T00:17:22+00:00 longevity-5000-tables-scale-te-db-node-9432a26c-4      !ERR | scylla[25009]:  [shard 10] sstable - Could not create SSTable component /var/lib/scylla/data/feeds/table95-7e959b203f2f11eda9d0905d8dc0ff2d/1360.sstable/me-1360-big-Data.db. Found exception: std::filesystem::__cxx11::filesystem_error (error system:24, filesystem error: open failed: Too many open files [/var/lib/scylla/data/feeds/table95-7e959b203f2f11eda9d0905d8dc0ff2d/1360.sstable/me-1360-big-Data.db])
```

@asias do we need something similar to 3dc9a81d02a26d021ad1954d57b574ad4899561d for streaming?

**Comment by asias** [comment]
> ```
> 2022-09-29T00:17:22+00:00 longevity-5000-tables-scale-te-db-node-9432a26c-4      !ERR | scylla[25009]:  [shard 10] sstable - Could not create SSTable component /var/lib/scylla/data/feeds/table95-7e959b203f2f11eda9d0905d8dc0ff2d/1360.sstable/me-1360-big-Data.db. Found exception: std::filesystem::__cxx11::filesystem_error (error system:24, filesystem error: open failed: Too many open files [/var/lib/scylla/data/feeds/table95-7e959b203f2f11eda9d0905d8dc0ff2d/1360.sstable/me-1360-big-Data.db])
> ```
> 
> @asias do we need something similar to [3dc9a81](https://github.com/scylladb/scylladb/commit/3dc9a81d02a26d021ad1954d57b574ad4899561d) for streaming?

We do table by table in legacy streaming long time ago.

**Comment by asias** [comment]
This PR should help with this issue:

https://github.com/scylladb/scylladb/pull/11848

**Comment by raphaelsc** [comment]
another issue that will be gone with tablets.

**Comment by mykaul** [comment]
> another issue that will be gone with tablets.

We have! Let's re-test this!

**Comment by soyacz** [comment]
> > another issue that will be gone with tablets.
> 
> We have! Let's re-test this!

I think this falls down to @pehala team now
