### ISSUE TITLE
[Regression] scylla_prepare: fails to generate perftune.yaml for a former MQ mode

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#11701]
*Installation details*
HEAD: 2041744132344d1f7ca513152b44d73af30a230c
Introduced by: 
```
commit 80917a1054f305d08a60107d868e86757ca3ee69
Author: Vlad Zolotarov <vladz@scylladb.com>
Date:   Wed Aug 24 20:03:36 2022 -0400

    scylla_prepare: stop generating 'mode' value in perftune.yaml
```

*Description*
On setups where a former `MQ` mode is requested:
* Auto-detected on small machines of 4 or less CPUs.
* Explicitly configured by a user via cpuset.conf by choosing all present CPUs.

`scylla_prepare` is going to generate an invalid value for `irq_cpu_mask` - it will set it to `0x0`.

As a result the following service start is going to fail because `perftune.py` has a corresponding sanity check:

```
Oct 03 23:18:07 vladz-test-scylla-prepare-tiny systemd[1]: Starting Scylla Server...
Oct 03 23:18:08 vladz-test-scylla-prepare-tiny scylla_prepare[15487]: ERROR: Bad configuration: zero IRQ CPU mask is given. Your system can't be tuned until the issue is fixed.
Oct 03 23:18:08 vladz-test-scylla-prepare-tiny scylla_prepare[15466]: Traceback (most recent call last):
Oct 03 23:18:08 vladz-test-scylla-prepare-tiny scylla_prepare[15466]:   File "/opt/scylladb/scripts/libexec/scylla_prepare", line 159, in <module>
Oct 03 23:18:08 vladz-test-scylla-prepare-tiny scylla_prepare[15466]:     run("{} --options-file /etc/scylla.d/perftune.yaml".format(perftune_base_command()), shell=True, check=True)
Oct 03 23:18:08 vladz-test-scylla-prepare-tiny scylla_prepare[15466]:   File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 528, in run
Oct 03 23:18:08 vladz-test-scylla-prepare-tiny scylla_prepare[15466]:     raise CalledProcessError(retcode, process.args,
Oct 03 23:18:08 vladz-test-scylla-prepare-tiny scylla_prepare[15466]: subprocess.CalledProcessError: Command '/opt/scylladb/scripts/perftune.py --tune disks --dir /var/lib/scylla/data --dir /var/lib/scylla/commitlog --dir /var/lib/scylla/hints --dir /var/lib/scylla/view_hints --options-file /etc/scylla.d/perftune.yaml' returned non-zero exit status 1.
Oct 03 23:18:08 vladz-test-scylla-prepare-tiny scylla_prepare[15466]: Exception occurred while tuning system using perftune.yaml:
Oct 03 23:18:08 vladz-test-scylla-prepare-tiny scylla_prepare[15466]: To fix the error, please re-run scylla_setup.
Oct 03 23:18:08 vladz-test-scylla-prepare-tiny systemd[1]: scylla-server.service: Control process exited, code=exited, status=1/FAILURE
Oct 03 23:18:08 vladz-test-scylla-prepare-tiny systemd[1]: scylla-server.service: Failed with result 'exit-code'.
Oct 03 23:18:08 vladz-test-scylla-prepare-tiny systemd[1]: Failed to start Scylla Server.

```

**Comment by mykaul** [comment]
do we need to backport this to 5.1.x?

**Comment by vladzcloudius** [comment]
> Is the above ([vladzcloudius@7e3215f](https://github.com/vladzcloudius/scylla/commit/7e3215fe6f95361c5b01ba78ec68256488486a03) ) the backport to 5.1.x? @DoronArazii - let's follow on it.

Yes, this was a part of this PR: https://github.com/scylladb/scylladb/pull/14092

**Comment by DoronArazii** [comment]
> Is the above ([vladzcloudius@7e3215f](https://github.com/vladzcloudius/scylla/commit/7e3215fe6f95361c5b01ba78ec68256488486a03) ) the backport to 5.1.x? @DoronArazii - let's follow on it.

Added to our daily meeting
