### ISSUE TITLE
using scylla with trunk cassandra-stress (+trunk java-driver) fails to connect [Host does not support protocol version V5 but V4]

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#11899]
Using https://github.com/apache/cassandra/commit/4469f017c0253cbbdea9f1fa656417f704f421b1

together with Scylla version (master lastest)
```
Scylla version 5.2.0~dev-0.20221106.44f48bea0ffa initialization completed.
```

yield the following error:
```
java.lang.RuntimeException: com.datastax.driver.core.exceptions.UnsupportedProtocolVersionException: [/127.0.2.1:9042] Host does not support protocol version V5 but V4
        at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:142)
        at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:111)
        at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:66)
        at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:150)
        at org.apache.cassandra.stress.StressAction.run(StressAction.java:58)
        at org.apache.cassandra.stress.Stress.run(Stress.java:101)
        at org.apache.cassandra.stress.Stress.main(Stress.java:54)
```

seem like trunk java-driver doesn't support CQL protocol V4 anymore, while scylla only support V4 and below.

**Comment by roydahan** [comment]
At some point the drivers of Cassandra won't work with Scylla anymore...

**Comment by nyh** [comment]
Added "Cassandra 4.x compatibility tag". The protocol v5 is new to Cassandra 4, and applications written for Cassandra 4 might choose to hard-code this version. 
On the other hand, insisting on v5 can also be considered an application bug - for example the Python driver has a `protocol_version` parameter (https://docs.datastax.com/en/developer/python-driver/3.25/api/cassandra/cluster/), and it is not chosen protocol version but rather the _maximum_ version that will be used - the driver will start with v5 but fall back to v4 if v5 is not supported by the server (like Scylla).
