### ISSUE TITLE
nodetool clearsnapshot failed exit code 2 after start/stop cleanup compaction 

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#11921]
## Installation details

Kernel Version: 5.15.0-1022-aws
Scylla version (or git commit hash): `5.2.0~dev-20221105.768d77d31b6e` with build-id `31818162ae404f25877763c515a14214a03356a7`

Cluster size: 5 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- longevity-large-partitions-3h-maste-db-node-d922de78-5 (44.193.226.234 | 10.12.0.112) (shards: 7)
- longevity-large-partitions-3h-maste-db-node-d922de78-4 (34.200.246.227 | 10.12.0.203) (shards: 7)
- longevity-large-partitions-3h-maste-db-node-d922de78-3 (44.201.64.254 | 10.12.0.11) (shards: 5)
- longevity-large-partitions-3h-maste-db-node-d922de78-2 (3.239.24.216 | 10.12.0.5) (shards: 5)
- longevity-large-partitions-3h-maste-db-node-d922de78-1 (3.235.160.76 | 10.12.1.19) (shards: 5)

OS / Image: `ami-0f877498e5b7d2c47` (aws: us-east-1)

Test: `longevity-large-partition-asymmetric-cluster-3h`
Test id: `d922de78-7abf-43c9-8243-f2c5606b466e`
Test name: `scylla-master/longevity/longevity-large-partition-asymmetric-cluster-3h`
Test config file(s):

- [longevity-large-partition-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9a70030c71afb51848cbc9357078c745b97fa0ad/test-cases/longevity/longevity-large-partition-3h.yaml)

## Issue description
After start stop cleanup compaction on node, the `nodetool clearsnapshot` command failed with error:
```
Command: '/usr/bin/nodetool  clearsnapshot '

Exit code: 2

Stdout:

Requested clearing snapshot(s) for [all keyspaces]

Stderr:

	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.invoke(RMIConnector.java:1020)
	at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:298)
	at com.sun.proxy.$Proxy7.clearSnapshot(Unknown Source)
	at org.apache.cassandra.tools.NodeProbe.clearSnapshot(NodeProbe.java:753)
	at org.apache.cassandra.tools.nodetool.ClearSnapshot.execute(ClearSnapshot.java:62)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.runInternal(NodeTool.java:309)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:294)
	at org.apache.cassandra.tools.NodeTool.execute(NodeTool.java:196)
	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:62)
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor d922de78-7abf-43c9-8243-f2c5606b466e`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d922de78-7abf-43c9-8243-f2c5606b466e)
- Show all stored logs command: `$ hydra investigate show-logs d922de78-7abf-43c9-8243-f2c5606b466e`

## Logs:
- **db-cluster-d922de78.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d922de78-7abf-43c9-8243-f2c5606b466e/20221106_083351/db-cluster-d922de78.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d922de78-7abf-43c9-8243-f2c5606b466e/20221106_083351/db-cluster-d922de78.tar.gz)
- **monitor-set-d922de78.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d922de78-7abf-43c9-8243-f2c5606b466e/20221106_083351/monitor-set-d922de78.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d922de78-7abf-43c9-8243-f2c5606b466e/20221106_083351/monitor-set-d922de78.tar.gz)
- **loader-set-d922de78.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d922de78-7abf-43c9-8243-f2c5606b466e/20221106_083351/loader-set-d922de78.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d922de78-7abf-43c9-8243-f2c5606b466e/20221106_083351/loader-set-d922de78.tar.gz)
- **sct-runner-d922de78.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d922de78-7abf-43c9-8243-f2c5606b466e/20221106_083351/sct-runner-d922de78.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d922de78-7abf-43c9-8243-f2c5606b466e/20221106_083351/sct-runner-d922de78.tar.gz)
- **parallel-timelines-report-d922de78.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d922de78-7abf-43c9-8243-f2c5606b466e/20221106_083351/parallel-timelines-report-d922de78.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d922de78-7abf-43c9-8243-f2c5606b466e/20221106_083351/parallel-timelines-report-d922de78.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-large-partition-asymmetric-cluster-3h/98/)

**Comment by bhalevy** [comment]
@roydahan by the way, why do we lose the scylla log level (ERROR/WARNING/INFO/DEBUG/TRACE) in the system.log files?

**Comment by bhalevy** [comment]
From the sct log:
```
< t:2022-11-06 05:23:44,528 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2022-11-06 05:23:44.526: (CoreDumpEvent Severity.ERROR) period_type=one-time event_id=19d44923-6dcc-4398-be01-83843c7d2852 during_nemesis=StartStopScrubCompaction node=Node longevity-large-partitions-3h-maste-db-node-d922de78-5 [44.193.226.234 | 10.12.0.112] (seed: False)
< t:2022-11-06 05:23:48,236 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-11-06 05:23:48.234: (JMXServiceEvent Severity.NORMAL) period_type=begin event_id=5a3d4c22-9f8b-4cfc-a8ab-44ee4cfe8739 node=longevity-large-partitions-3h-maste-db-node-d922de78-5
< t:2022-11-06 05:23:59,007 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "/usr/bin/nodetool  clearsnapshot "; Exit status: 2
...
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > corefile_url=https://storage.cloud.google.com/upload.scylladb.com/core.scylla.114.4c0542dccfbe4548ae5b164d6600e0dc.11904.1667712086000000000000/core.scylla.114.4c0542dccfbe4548ae5b164d6600e0dc.11904.1667712086000000000000.gz
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > backtrace=           PID: 11904 (scylla)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >            UID: 114 (scylla)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >            GID: 120 (scylla)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >         Signal: 6 (ABRT)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >      Timestamp: Sun 2022-11-06 05:21:26 UTC (3min 8s ago)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >   Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 25 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1 --smp 5 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7 --lock-memory=1
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     Executable: /opt/scylladb/libexec/scylla
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >  Control Group: /scylla.slice/scylla-server.slice/scylla-server.service
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >           Unit: scylla-server.service
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >          Slice: scylla-server.slice
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >        Boot ID: 4c0542dccfbe4548ae5b164d6600e0dc
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >     Machine ID: 7b5c967ea1fa4a68ba36792cea5a04cb
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >       Hostname: longevity-large-partitions-3h-maste-db-node-d922de78-3
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >        Storage: /var/lib/systemd/coredump/core.scylla.114.4c0542dccfbe4548ae5b164d6600e0dc.11904.1667712086000000000000
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >        Message: Process 11904 (scylla) of user 114 dumped core.
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >                 
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >                 Stack trace of thread 11910:
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >                 #0  0x00007fbf231aa2a2 raise (libc.so.6 + 0x3d2a2)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >                 #1  0x00007fbf231938a4 abort (libc.so.6 + 0x268a4)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >                 #2  0x00007fbf23193789 __assert_fail_base.cold (libc.so.6 + 0x26789)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >                 #3  0x00007fbf231a2a16 __assert_fail (libc.so.6 + 0x35a16)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >                 #4  0x0000000003b52f86 _ZN28reader_concurrency_semaphore19maybe_admit_waitersEv (scylla + 0x3952f86)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >                 #5  0x0000000003b55526 _ZN28reader_concurrency_semaphore5evictERNS_13inactive_readENS_12evict_reasonE (scylla + 0x3955526)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >                 #6  0x0000000004e7a2fe _ZN7seastar7reactor23do_expire_lowres_timersEv (scylla + 0x4c7a2fe)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >                 #7  0x0000000004e9a889 _ZNSt17_Function_handlerIFbvEZN7seastar7reactor6do_runEvE4$_45E9_M_invokeERKSt9_Any_data (scylla + 0x4c9a889)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >                 #8  0x0000000004e7c372 _ZN7seastar7reactor6do_runEv (scylla + 0x4c7c372)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >                 #9  0x0000000004e9b706 _ZNSt17_Function_handlerIFvvEZN7seastar3smp9configureERKNS1_11smp_optionsERKNS1_15reactor_optionsEE4$_92E9_M_invokeERKSt9_Any_data (scylla + 0x4c9b706)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >                 #10 0x0000000004e4e20b _ZN7seastar12posix_thread13start_routineEPv (scylla + 0x4c4e20b)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >                 #11 0x00007fbf23d482a5 start_thread (libpthread.so.0 + 0x92a5)
< t:2022-11-06 05:26:01,987 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR >                 #12 0x00007fbf2326d323 __clone (libc.so.6 + 0x100323)
```

```
$ grep Assert */messages.log | grep 05:2
longevity-large-partitions-3h-maste-db-node-d922de78-1/messages.log:2022-11-06T05:20:44+00:00 longevity-large-partitions-3h-maste-db-node-d922de78-1     !INFO | scylla[7878]: scylla: reader_concurrency_semaphore.cc:213: void reader_permit::impl::on_evicted(): Assertion `_state == reader_permit::state::inactive' failed.
longevity-large-partitions-3h-maste-db-node-d922de78-3/messages.log:2022-11-06T05:21:27+00:00 longevity-large-partitions-3h-maste-db-node-d922de78-3     !INFO | scylla[11904]: scylla: reader_concurrency_semaphore.cc:213: void reader_permit::impl::on_evicted(): Assertion `_state == reader_permit::state::inactive' failed.
longevity-large-partitions-3h-maste-db-node-d922de78-5/messages.log:2022-11-06T05:21:11+00:00 longevity-large-partitions-3h-maste-db-node-d922de78-5     !INFO | scylla[10975]: scylla: reader_concurrency_semaphore.cc:213: void reader_permit::impl::on_evicted(): Assertion `_state == reader_permit::state::inactive' failed.
```

So apparently this was caused by https://github.com/scylladb/scylladb/issues/11923
and the clearsnapshot error is just a secondary failure.
