### ISSUE TITLE
Probable regression in 5.1 while running Java Driver's MapperAccessorParamsTest.should_allow_less_parameters_than_bind_markers_if_there_are_repeated_names

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylladb#11945]
When running Java Driver 3.x's integration tests with 5.1.0-rc4, `MapperAccessorParamsTest.should_allow_less_parameters_than_bind_markers_if_there_are_repeated_names` fails. This test works correctly when running the integration tests with 5.0.5.

```
Starting com.datastax.driver.mapping.MapperAccessorParamsTest.should_allow_less_parameters_than_bind_markers_if_there_are_repeated_names [Test #1]...
    31186  [cluster1-worker-1] WARN  com.datastax.driver.core.Cluster  - Re-preparing already prepared query is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once. Query='update user set home_phone = :home, work_phone = :work where key = :key'
    31186  [cluster1-worker-11] WARN  com.datastax.driver.core.Cluster  - Re-preparing already prepared query is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once. Query='update user set home_phone = :phone, work_phone = :phone where key = :key'
java.lang.RuntimeException: Error preparing queries for accessor UserPhoneAccessor
	at com.datastax.driver.mapping.AccessorMapper.prepare(AccessorMapper.java:63)
	at com.datastax.driver.mapping.MappingManager.getAccessor(MappingManager.java:359)
	at com.datastax.driver.mapping.MappingManager.createAccessor(MappingManager.java:321)
	at com.datastax.driver.mapping.MapperAccessorParamsTest.should_allow_less_parameters_than_bind_markers_if_there_are_repeated_names(MapperAccessorParamsTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:192)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:93)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
Caused by: java.lang.IllegalArgumentException: Too many arguments for method updatePhones_fallback2, found 3 but it should be at most the number of bind parameters in the @Query (2)
	at com.datastax.driver.mapping.MethodMapper.validateParameters(MethodMapper.java:125)
	at com.datastax.driver.mapping.MethodMapper.prepare(MethodMapper.java:77)
	at com.datastax.driver.mapping.AccessorMapper.prepare(AccessorMapper.java:60)
	... 32 more
FAILED : should_allow_less_parameters_than_bind_markers_if_there_are_repeated_names
Test   : 00:00:00
Elapsed: 00:00:31
```

Commands to run tests:
```
git clone https://github.com/scylladb/java-driver.git
cd java-driver
# Works:
mvn -B verify -Pshort -Dscylla.version=5.0.5 -Dtest=*MapperAccessorParamsTest* -Dsurefire.failIfNoSpecifiedTests=false -Dfmt.skip=true -Dclirr.skip=true -Danimal.sniffer.skip=true
# Doesn't work:
mvn -B verify -Pshort -Dscylla.version=5.1.0-rc4 -Dtest=*MapperAccessorParamsTest* -Dsurefire.failIfNoSpecifiedTests=false -Dfmt.skip=true -Dclirr.skip=true -Danimal.sniffer.skip=true
```

**Comment by avelanarius** [comment]
The issue looks potentially related to: https://github.com/scylladb/scylladb/issues/10956

**Comment by roydahan** [comment]
@fruch is this the test failing in java-driver-matrix?

**Comment by fruch** [comment]
> @fruch is this the test failing in java-driver-matrix?

We did encountered it on master.

And it was decided to skip the test see the issue I've opend and @avelanarius is refering to.

**Comment by Gor027** [comment]
> > @fruch is this the test failing in java-driver-matrix?
> 
> We did encountered it on master.
> 
> And it was decided to skip the test see the issue I've opend and @avelanarius is refering to.

Actually, this is a different test, a more "realistic" one than the skipped test in the referred issue.

**Comment by Gor027** [comment]
As it's mentioned in the related issue [here](https://github.com/scylladb/scylladb/issues/10956#issuecomment-1188845014), after the patch [`19a6e69`](https://github.com/scylladb/scylladb/commit/19a6e69001f26133a7f7a0a13e89935888884e1a) the prepared statement metadata does not contain full information about named markers with repeated names: 

e.g. `update user set home_phone = :phone, work_phone = :phone where key = :key`


When the user provides more binding parameters than there are named markers, the driver is expected to fallback to positional matching. The failing test tries to reinterpret the query as below and bind parameters with positonal matching:

`update user set home_phone = ?, work_phone = ? where key = ?`

After the patch, the metadata has a single "slot" for the repeated named markers, so the information about the markers' indices is ignored and it is interpreted such that there is only one named marker. Thus, the change disallows to fallback to positional matching in case the user provides more binding parameters than there are named markers.

As it is a corner case, and perhaps, as it is not often expected that while binding parameters to a prepared statement with repeated named markers the driver should fallback to positional matching, the test should be either skipped or modified properly. Otherwise, the patch [`19a6e69`](https://github.com/scylladb/scylladb/commit/19a6e69001f26133a7f7a0a13e89935888884e1a) should be reverted, as there are no good workarounds in the driver because it does not have information about the indices of the repeated named markers.

**Comment by avelanarius** [comment]
So after 19a6e69001f26133a7f7a0a13e89935888884e1a, two Java Driver tests stopped passing:

1. `should_set_all_occurrences_of_variable` (issue #10956)
2. `should_allow_less_parameters_than_bind_markers_if_there_are_repeated_names` (this issue)

The first test was essentially testing hardcoded values in PREPARED response and it wasn't a realistic scenario. Therefore, we decided to disable that test.

However, the test in this issue is a more realistic scenario.

What this test does is essentially prepare a statement with named bindings:
`SELECT * FROM ks.t WHERE a = :named AND b = :named AND c = :named ALLOW FILTERING`
 and then try to use it as if it was a statement with "positional" bind markers:
`SELECT * FROM ks.t WHERE a = ? AND b = ? AND c = ? ALLOW FILTERING`
 
After 19a6e69001f26133a7f7a0a13e89935888884e1a, `:named` markers are deduplicated and the driver has only 1 "slot" to put values to.

Is this something we'd like to fix in Scylla or it's too esoteric, so that the test should be disabled and users that hit this cornercase should fix their queries?

cc @avikivity @cvybhu

**Comment by mykaul** [comment]
If we do not fix, at least let's put it as xfail with a reference to the issue.

**Comment by avikivity** [comment]
IMO, the test enshrines incorrect Cassandra behavior. The correct fix is to change the test to fail if it currently passes, and pass if it currently fails.

I reported it to the Cassandra project: https://issues.apache.org/jira/browse/CASSANDRA-17693

**Comment by DoronArazii** [comment]
@avelanarius / @Gor027 can we close it? does the reference above ^^ fixing it?
