### ISSUE TITLE
Gemini load fails with a read quorum timeout for an MV table

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#11963]
## Installation details

Kernel Version: 5.15.0-1022-aws
Scylla version (or git commit hash): `5.1.0~rc4-20221106.0295d0c5c81d` with build-id `2e4327c4a7b39d7c4b64e75e8fdb23c73db11a1e`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla/relocatable/scylladb-5.1/scylla-x86_64-package-5.1.0-rc4.0.20221106.0295d0c5c81d.tar.gz
Cluster size: 3 nodes (i3.large)

Scylla Nodes used in this run:
- gemini-basic-3h-master-oracle-db-node-fa5389e3-1 (3.250.146.114 | 10.4.1.218) (shards: 30)
- gemini-basic-3h-master-db-node-fa5389e3-3 (54.170.180.58 | 10.4.0.228) (shards: 2)
- gemini-basic-3h-master-db-node-fa5389e3-2 (3.251.79.60 | 10.4.0.216) (shards: 2)
- gemini-basic-3h-master-db-node-fa5389e3-1 (54.72.186.100 | 10.4.1.149) (shards: 2)

OS / Image: `ami-0bd9c72fed07d08b2` (aws: eu-west-1)

Test: `gemini-byo-repo`
Test id: `fa5389e3-7382-4d6b-930c-c5dc51c5b2c2`
Test name: `scylla-staging/abykov/gemini-byo-repo`
Test config file(s):

- [gemini-3h-with-nondisruptive-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d02ce1aa92674945071200e00375269b559ffeb9/test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml)

## Issue description

**>>>>>>>**
scenario:
1. Gemini runs and gets to end of warmup step after a half an hour.
It then failed for timeout of a read quorum and reproduced with the same Gemini seed as well):
```
2022-11-11 11:56:45.882: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=4c7969a6-4100-4cd6-b6b5-710543bb1b87, source=GeminiTest.test_load_random_with_nemesis (gemini_test.GeminiTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 68, in test_load_random_with_nemesis
self.verify_results()
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 127, in verify_results
self.fail(self.gemini_results['results'])
AssertionError: [{'write_ops': 1248957, 'write_errors': 0, 'read_ops': 106, 'read_errors': 1, 'errors': [{'timestamp': '2022-11-11T11:10:44.288479004Z', 'message': 'Validation failed: unable to load check data from the test store: system failed: Operation timed out for ks1.table1_mv_0 - received only 1 responses from 2 CL=QUORUM.', 'query': "SELECT * FROM ks1.table1_mv_0 WHERE col8 IN (textasblob('303339414e754d4a496d57354354336d326e78377a6d524964'),textasblob('567633743645546951585951643964444f326b3759736970736d693548445630766a6669486d742b384f2b30463073676656')) AND pk0 IN (6445459015094923539,6923435322967853504) AND pk1 IN (864233265,1126637235) AND pk2 IN (31855,15636) AND pk3 IN (-105,120) AND pk4 IN (720096802,1839537111) "}]}]
```
The original Gemini run failed similarly with:
```

2022-10-03 11:28:54.009: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=781d29f2-4986-4554-adae-303829784d14, source=GeminiTest.test_load_random_with_nemesis (gemini_test.GeminiTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 68, in test_load_random_with_nemesis
self.verify_results()
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 127, in verify_results
self.fail(self.gemini_results['results'])
AssertionError: [{'write_ops': 1219553, 'write_errors': 0, 'read_ops': 106, 'read_errors': 1, 'errors': [{'timestamp': '2022-10-03T11:07:50.019939979Z', 'message': 'Validation failed: unable to load check data from the test store: system failed: Operation timed out for ks1.table1_mv_0 - received only 1 responses from 2 CL=QUORUM.', 'query': "SELECT * FROM ks1.table1_mv_0 WHERE col8 IN (textasblob('303339414e7766615331554d4b70785a4c6354776c38616450'),textasblob('56763374364578695731416d47614b6638655672397774577151493548445630766a6669486d742b384f2b30463073676656')) AND pk0 IN (1620607526196139086,838666361166238841) AND pk1 IN (2056891625,1282464239) AND pk2 IN (7137,-1425) AND pk3 IN (66,-5) AND pk4 IN (894412959,1687627455) "}]}]
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor fa5389e3-7382-4d6b-930c-c5dc51c5b2c2`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=fa5389e3-7382-4d6b-930c-c5dc51c5b2c2)
- Show all stored logs command: `$ hydra investigate show-logs fa5389e3-7382-4d6b-930c-c5dc51c5b2c2`

## Logs:
- **db-cluster-fa5389e3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fa5389e3-7382-4d6b-930c-c5dc51c5b2c2/20221111_120513/db-cluster-fa5389e3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fa5389e3-7382-4d6b-930c-c5dc51c5b2c2/20221111_120513/db-cluster-fa5389e3.tar.gz)
- **monitor-set-fa5389e3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fa5389e3-7382-4d6b-930c-c5dc51c5b2c2/20221111_120513/monitor-set-fa5389e3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fa5389e3-7382-4d6b-930c-c5dc51c5b2c2/20221111_120513/monitor-set-fa5389e3.tar.gz)
- **loader-set-fa5389e3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fa5389e3-7382-4d6b-930c-c5dc51c5b2c2/20221111_120513/loader-set-fa5389e3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fa5389e3-7382-4d6b-930c-c5dc51c5b2c2/20221111_120513/loader-set-fa5389e3.tar.gz)
- **sct-runner-fa5389e3.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/fa5389e3-7382-4d6b-930c-c5dc51c5b2c2/20221111_120513/sct-runner-fa5389e3.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/fa5389e3-7382-4d6b-930c-c5dc51c5b2c2/20221111_120513/sct-runner-fa5389e3.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/gemini-byo-repo/27/)

**Comment by yarongilor** [comment]
The original test failure in 2022.2 details are:

## Installation details

Kernel Version: 5.15.0-1019-aws
Scylla version (or git commit hash): `2022.2.0~rc2-20220919.75d087a2b75a` with build-id `463f1a57b82041a6c6b6441f0cbc26c8ad93091e`
Relocatable Package: http://downloads.scylladb.com/downloads/scylla-enterprise/relocatable/scylladb-2022.2/scylla-enterprise-x86_64-package-2022.2.0-rc2.0.20220919.75d087a2b75a.tar.gz
Cluster size: 3 nodes (i3.large)

Scylla Nodes used in this run:
- gemini-basic-3h-2022-2-oracle-db-node-31b47e0f-1 (34.245.97.42 | 10.4.3.175) (shards: 2)
- gemini-basic-3h-2022-2-db-node-31b47e0f-3 (34.241.252.151 | 10.4.2.72) (shards: 2)
- gemini-basic-3h-2022-2-db-node-31b47e0f-2 (3.250.68.69 | 10.4.2.66) (shards: 2)
- gemini-basic-3h-2022-2-db-node-31b47e0f-1 (52.214.62.157 | 10.4.1.6) (shards: 2)


OS / Image: `ami-00bd31f22bcf5ae1a` (aws: eu-west-1)

Test: `gemini-3h-nondisruptive-nemesis-test`
Test id: `31b47e0f-40ff-4684-af3a-0e8e0d2a6e95`
Test name: `enterprise-2022.2/gemini-/gemini-3h-nondisruptive-nemesis-test`
Test config file(s):

- [gemini-3h-with-nondisruptive-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9818d76f6d1584c8d4652429a6aa1c616b6bb3c2/test-cases/gemini/gemini-3h-with-nondisruptive-nemesis.yaml)

## Issue description

**>>>>>>>**
2022-10-03 11:28:54.009: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=781d29f2-4986-4554-adae-303829784d14, source=GeminiTest.test_load_random_with_nemesis (gemini_test.GeminiTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 68, in test_load_random_with_nemesis
self.verify_results()
File "/home/ubuntu/scylla-cluster-tests/gemini_test.py", line 127, in verify_results
self.fail(self.gemini_results['results'])
AssertionError: [{'write_ops': 1219553, 'write_errors': 0, 'read_ops': 106, 'read_errors': 1, 'errors': [{'timestamp': '2022-10-03T11:07:50.019939979Z', 'message': 'Validation failed: unable to load check data from the test store: system failed: Operation timed out for ks1.table1_mv_0 - received only 1 responses from 2 CL=QUORUM.', 'query': "SELECT * FROM ks1.table1_mv_0 WHERE col8 IN (textasblob('303339414e7766615331554d4b70785a4c6354776c38616450'),textasblob('56763374364578695731416d47614b6638655672397774577151493548445630766a6669486d742b384f2b30463073676656')) AND pk0 IN (1620607526196139086,838666361166238841) AND pk1 IN (2056891625,1282464239) AND pk2 IN (7137,-1425) AND pk3 IN (66,-5) AND pk4 IN (894412959,1687627455) "}]}]
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor 31b47e0f-40ff-4684-af3a-0e8e0d2a6e95`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=31b47e0f-40ff-4684-af3a-0e8e0d2a6e95)
- Show all stored logs command: `$ hydra investigate show-logs 31b47e0f-40ff-4684-af3a-0e8e0d2a6e95`

## Logs:
- **db-cluster-31b47e0f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/31b47e0f-40ff-4684-af3a-0e8e0d2a6e95/20221003_113743/db-cluster-31b47e0f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/31b47e0f-40ff-4684-af3a-0e8e0d2a6e95/20221003_113743/db-cluster-31b47e0f.tar.gz)
- **monitor-set-31b47e0f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/31b47e0f-40ff-4684-af3a-0e8e0d2a6e95/20221003_113743/monitor-set-31b47e0f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/31b47e0f-40ff-4684-af3a-0e8e0d2a6e95/20221003_113743/monitor-set-31b47e0f.tar.gz)
- **loader-set-31b47e0f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/31b47e0f-40ff-4684-af3a-0e8e0d2a6e95/20221003_113743/loader-set-31b47e0f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/31b47e0f-40ff-4684-af3a-0e8e0d2a6e95/20221003_113743/loader-set-31b47e0f.tar.gz)
- **sct-runner-31b47e0f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/31b47e0f-40ff-4684-af3a-0e8e0d2a6e95/20221003_113743/sct-runner-31b47e0f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/31b47e0f-40ff-4684-af3a-0e8e0d2a6e95/20221003_113743/sct-runner-31b47e0f.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/gemini-/job/gemini-3h-nondisruptive-nemesis-test/2/)

**Comment by DoronArazii** [comment]
@eliransin / @nyh please determine if this is a blocker for 5.1

**Comment by nyh** [comment]
MV reads are just normal reads, so they cannot be the whole problem. HOWEVER, if this use case has materialized views, then my guess is that this workload also has a lot of view **writes** as well (can you please confirm or deny?). If it does, these can  cause read-before-writes that compete with the user's reads - this is a known bug https://github.com/scylladb/scylladb/issues/8873  - that unfortunately we never fixed.

Whether or not this is a "blocker for 5.1" depends, in my opinion, on whether this is a regression. Would the same run have failed with 5.0 too?

**Comment by DoronArazii** [comment]
@yarongilor @fgelcer ^^

**Comment by yarongilor** [comment]
i recall previous versions Gemini failures of either writes or data inconsistency, not a read quorum timeout.

**Comment by fgelcer** [comment]
> i recall previous versions Gemini failures of either writes or data inconsistency, not a read quorum timeout.

@yarongilor , IIUC the question here is about schema used in the test, and about MV reads (read-before-writes) competing with Gemini read workload

**Comment by yarongilor** [comment]
As for the Gemini pattern, it basically has a 'warmup' step with a lot of writes, and after that (30 minutes) it reads the data in order to validate it before continuing to next step.
In the grafana it looks like the writes just ended right at the time of this failure:

![image](https://user-images.githubusercontent.com/9427929/201530987-e37f8900-a5e1-4fb4-820e-d47ef460a709.png)

**Comment by roydahan** [comment]
1. I think there is a very similar issue for the exact same job.
2. @yarongilor please extract the Gemini AssertionError information to a readable format and paste it below.

**Comment by nyh** [comment]
> As for the Gemini pattern, it basically has a 'warmup' step with a lot of writes, and after that (30 minutes) it reads the data in order to validate it before continuing to next step. In the grafana it looks like the writes just ended right at the time of this failure:

This exactly fits my theory - after 30 minutes of writes, if one replica is just a tiny bit slower than others than this replica can have a huge backlog of base-table writes ("background writes"), and when we suddenly send a barrage of read requests, they get stuck behind thousands of read-before-write requests for all those background writes - and time out.

However, I'm not sure how to read the graphana you pasted or how it comfirms my theory. When is the time that reads started happening? How much is the background write queue at that point? It can reach up to 10% of the entire memory, but does it?

**Comment by yarongilor** [comment]
> 1. I think there is a very similar issue for the exact same job.
> 2. @yarongilor please extract the Gemini AssertionError information to a readable format and paste it below.

The Gemini failure is:
```
{"L":"INFO","T":"2022-11-11T10:40:11.925Z","N":"generator","M":"starting partition key generation loop"}
Errors detected: []main.JobError{main.JobError{Timestamp:time.Date(2022, time.November, 11, 11, 10, 44, 288479004, time.Local), Message:"Validation failed: unable to load check data from the test store: system failed: Operation timed out for ks1.table1_mv_0 - received only 1 responses from 2 CL=QUORUM.",
```
```
 Query:"SELECT * FROM ks1.table1_mv_0 WHERE col8 IN (textasblob('303339414e754d4a496d57354354336d326e78377a6d524964'),textasblob('567633743645546951585951643964444f326b3759736970736d693548445630766a6669486d742b384f2b30463073676656')) AND pk0 IN (6445459015094923539,6923435322967853504) AND pk1 IN (864233265,1126637235) AND pk2 IN (31855,15636) AND pk3 IN (-105,120) AND pk4 IN (720096802,1839537111) "}}
```
```
{"L":"WARN","T":"2022-11-11T11:10:44.288Z","N":"sample_results","M":"Errors detected. Exiting."}
{"L":"INFO","T":"2022-11-11T11:10:44.288Z","N":"pump","M":"Test run stopped. Exiting."}
{"L":"INFO","T":"2022-11-11T11:10:48.099Z","M":"result channel closed"}
gemini encountered errors, exiting with non zero status
Error: gemini encountered errors, exiting with non zero status
```

**Comment by yarongilor** [comment]
See restored monitor in:
http://44.200.60.168:3000/d/advanced-2022-2/advanced?orgId=1&from=1664792695000&to=1664796295000

There are some spikes in several queues at the point of failures that might be related ( compaction/streaming/io/memtable) :

![image](https://user-images.githubusercontent.com/9427929/201534380-4d8bf31c-7215-400a-982d-3f04fa86d04b.png)

**Comment by nyh** [comment]
If I understand correctly this monitoring, there is roughly 30 minutes of constant 200-write-per-second load, until time 11:08, at which point the write stops, and the workload immediate start a few reads (maybe even just one), which time out, and causes the workload to stop.

It seems there's actually a few - even hundreds - of write failures during the write phase. How does Gemini not notice that? Or maybe it just retries failed writes?

None of nodes exceed 60% CPU utilization in this test, so my theory about overload and queuing no longer make sense - all nodes should be able to immediately clear any backlog. HOWEVER, there still is some queue - I see that when the read starts one of the nodes is still trying to clear its background write queue from about 200 to zero. 200 is not a huge number, but it is still significantly more than the number of concurrent reads (100) that we allow, so if these 200 writes take a second to finish (this seems to be this test's throughput), user reads may be delayed by a second. What is the timeout that Gemini sets for reads?

I see in the "queued sstables reads" that there is 1.8 kreads at the read failure time. It is zero all other times. I don't know what it means. Maybe it means that the background read-before-writes are filling the queue so all other reads got queued, but I don't know where 1800 reads come from suddenly.

After saying all of this, I don't know what is my conclusion. I don't see any obvious problem. I don't know why that single read failed causing Gemini to just quit, and why it didn't quit earlier when hundreds of writes timed out similar. Nor do I know why those writes timed out.

**Comment by fgelcer** [comment]
> 1. I think there is a very similar issue for the exact same job.

#10210 @roydahan , is this one you were referring to?
@nyh FYI

**Comment by fgelcer** [comment]
> > 1. I think there is a very similar issue for the exact same job.
> 
> #10210 @roydahan , is this one you were referring to? @nyh FYI

or this one #11103 ?

**Comment by nyh** [comment]
#11103 seems completely unrelated (the conclusion there seems that it is some floating point accuracy difference?). #10210 sounds like it may be the same, but I don't understand what Gemini is doing so it's hard to say.

**Comment by aleksbykov** [comment]
Also in logs for both versions at moment when gemini failed in db logs next were found:
```
2022-11-11T06:27:47+00:00 gemini-basic-3h-master-db-node-1fbe874c-1     !INFO | scylla[7571]:  [shard 0] reader_concurrency_semaphore - Semaphore sl:default_read_concurrency_sem with 27/100 count and -132851853/0 memory resources: timed out, dumping permit diagnostics:
permits	count	memory	table/description/state
26	26	10M	ks1.table1_mv_0/data-query/active/blocked
1	1	16K	ks1.table1_mv_0/data-query/active/used
3	0	0B	ks1.table1/data-query/waiting
347	0	0B	ks1.table1_mv_0/data-query/waiting

377	27	10M	total

Total: 377 permits with 27 count and 10M memory resources
2022-11-11T06:27:51+00:00 gemini-basic-3h-master-db-node-1fbe874c-1     !INFO | scylla[7571]:  [shard 1] reader_concurrency_semaphore - Semaphore sl:default_read_concurrency_sem with 35/100 count and -128585251/0 memory resources: timed out, dumping permit diagnostics:
permits	count	memory	table/description/state
34	34	14M	ks1.table1_mv_0/data-query/active/blocked
1	1	16K	ks1.table1_mv_0/data-query/active/used
7	0	0B	ks1.table1/data-query/waiting
1251	0	0B	ks1.table1_mv_0/data-query/waiting

1293	35	14M	total

Total: 1293 permits with 35 count and 14M memory resources
```

**Comment by nyh** [comment]
On first glance I thought that these messages confirm my guess that - perhaps for reasons explained in #8873 perhaps for other reasons - there are a lot of parallel reads going on, which cause the user's reads to time out.

However, on second look I'm not sure I understand the specifics which appear in that message. It looks like we only have 34 active reads, which is well below our 100 read limits, but the **memory** used by those 34 reads is 14 MB which is apparently (@denesb what does the negative number in the message mean???) our limit. But why are all these reads marked "blocked" - what does that mean? And the fact these reads are all on table1_mv_0 and not table1 suggest that these are **not** read-before-write (those would read from the base table, not the view!), unless the labels are wrong.

 @denesb can you please understand the the specific dump in the comment above and what it might mean?

**Comment by denesb** [comment]
Those negative and 0 memory resources are due to a bug in the way memory is distributed among semaphores, the bug has a cosmetic side-effect displaying 0 or negative numbers for memory. This is fixed in https://github.com/scylladb/scylla-enterprise/pull/2443. This is only in the enterprise version, why is this issue opened against OSS?

`active/blocked` means the respective read has gone to disk.
The dumps look fine to me. There is one in-cache reader `active/used`, and a bunch of reads that are gone to disk. No more reads can be admitted because there is one read (the `active/used` one, which needs only CPU to progress).

**Comment by fgelcer** [comment]
> This is only in the enterprise version, why is this issue opened against OSS?
> 

this was a decision regarding releases... if the reported issue (in this case, the issue reported is about Gemini load failing) is not related to enterprise, we report on OSS repo, as we are testing both (the parallel of OSS and enterprise) altogether

**Comment by fgelcer** [comment]
closed by mistake

**Comment by nyh** [comment]
I think this issue was seen in both 2022.2 and 5.1 but I guess the quoted message was from 2022.2. 
I found similar dumps also in the open-source (5.1) run quoted above, but they don't appear to be at the time of the failure (?), and again I don't understand the numbers - they seem to be lower than the limit, so why do we have this timeout?

```
Nov 11 11:10:29 gemini-basic-3h-master-db-node-fa5389e3-3 scylla[7679]:  [shard 0] reader_concurrency_semaphore - Semaphore _read_concurrency_sem with 32/100 count and 13141039/143696855 memory resources: timed out, dumping permit diagnostics:
                                                                        permits        count        memory        table/description/state
                                                                        31        31        13M        ks1.table1_mv_0/data-query/active/blocked
                                                                        1        1        16K        ks1.table1_mv_0/data-query/active/used
                                                                        4        0        0B        ks1.table1/data-query/waiting
                                                                        1395        0        0B        ks1.table1_mv_0/data-query/waiting
                                                                        
                                                                        1431        32        13M        total
                                                                        
                                                                        Total: 1431 permits with 32 count and 13M memory resources
```

**Comment by roydahan** [comment]
AFAIU, this is NOT a regression.
According to @aleksbykov a [reproducer](https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/gemini-byo-repo/32) with the same gemini seed failed for the same issue in 5.0.3.

**Comment by roydahan** [comment]
@yarongilor I'm not sure why you think it's the same issue.
In any case, please open a new one and explain exactly what is the test and what is the schema being used.

**Comment by yarongilor** [comment]
> @yarongilor I'm not sure why you think it's the same issue. In any case, please open a new one and explain exactly what is the test and what is the schema being used.

@roydahan , opened https://github.com/scylladb/scylla-enterprise/issues/3514

**Comment by mykaul** [comment]
Closing based on "closing for the moment. Have to retest with a stronger instance." from https://github.com/scylladb/scylla-enterprise/issues/3514
