### ISSUE TITLE
Cleanup may fail if a table is dropped concurrently

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12007]
Currently nodetool cleanup may fail if a table is dropped in the middle of cleanup.

For example, the failure looks like:
```
java.lang.IllegalStateException: Scylla API server HTTP POST to URL '/storage_service/keyspace_cleanup/ks' failed: std::_Nested_exception<no_such_column_family> $
Can't find a column family with UUID 01234567-89ab-cdef-0123-000000000000): std::out_of_range (_Map_base::at)
        at com.scylladb.jmx.api.APIClient.getException(APIClient.java:140)
        at com.scylladb.jmx.api.APIClient.post(APIClient.java:120)
        at com.scylladb.jmx.api.APIClient.post(APIClient.java:130)
        at com.scylladb.jmx.api.APIClient.post(APIClient.java:113)
        at com.scylladb.jmx.api.APIClient.postGetVal(APIClient.java:144)
        at com.scylladb.jmx.api.APIClient.postInt(APIClient.java:148)
        at org.apache.cassandra.service.StorageService.forceKeyspaceCleanup(StorageService.java:629)
        at org.apache.cassandra.service.StorageService.forceKeyspaceCleanup(StorageService.java:1665)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:276)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
        at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
        at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
        at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
        at com.scylladb.jmx.utils.APIMBeanServer.invoke(APIMBeanServer.java:188)
        at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
        at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
        at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
        at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
        at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

While on the node log, we see the table being dropped:
```
Nov 17 10:11:12 ip-127-0-0-1 scylla[12345]:  [shard 1] schema_tables - Dropping ks.t_aabbccddef_2022_11_17_01_02_03 id=01234567-89ab-cdef-0123-000000000000 version=c3ace1cd-d84b-458e-8864-c88cbafaae77
```

**Comment by bhalevy** [comment]
Reproducer here: https://github.com/bhalevy/scylla-dtest/commits/drop-table-during-cleanup
I'll submit it along with the fix to scylla

**Comment by raphaelsc** [comment]
Great. @bhalevy thanks for working on the fix in addition to writing a dtest for reproducing this. we'll probably have to forgive the unexistence of a given table when iterating through the list.

**Comment by bhalevy** [comment]
right.  fix already working, cleaning it up and will submit the PR.
it's quite comprehensive since the problem is not limited to cleanup, other operations that walk over a list of tables are susceptible too, like major compaction and friends.

**Comment by avikivity** [comment]
Also:
4. not a regression (?)

**Comment by bhalevy** [comment]
Ir's not a regression.
However applications that create and delete tables rapidly on a regular basis would cause cleanup to keep failing. Simply retrying nodetool cleanup on the keyspace may not help either since we don't so a good job in incremental cleanup and retry will rewrite most if not all sstables from scratch.  The real workaround is to script the cleanup process. start with listing all tables, then run cleanup one table at a time.  If a table is dropped in parallel, just skip it since dropping the table obviates cleanup on it.

**Comment by avikivity** [comment]
I think it's better not to backport. The bug's risk is lower than the risk of introducing a new regression in new, untested code. Let it cook in master.

**Comment by bhalevy** [comment]
> I think it's better not to backport.

Agreed

> The bug's risk is lower than the risk of introducing a new regression in new, untested code. Let it cook in master.

FWIW, I added a dtest to cover this: https://github.com/scylladb/scylla-dtest/pull/2909

The test deletes tables being cleaned up in 2 distinct phases:
1. An actively cleaned up table.  There the responsibility for handling the deletion is on compaction_manager and below.
2. A table pending cleanup.  Here the responsobility is of the api layer (what trigerred this issue).

Both cases pass reliably with this issue fixed.

**Comment by avikivity** [comment]
I'm not worried about the fix not achieving the intended effect, but about an unforeseen side effect.

**Comment by avikivity** [comment]
Conclusion was not to backport, removing backport candidate label.
