### ISSUE TITLE
nodetool rebuild fails with: ConnectException: 'Connection refused (Connection refused)' during DecommissionStreamingErr

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#12298]
## Installation details

Kernel Version: 5.15.0-1026-aws
Scylla version (or git commit hash): `5.2.0~dev-20221210.e47794ed9832` with build-id `a0d3f077099c66bf6c75707e386c6be3ba2c431f`

Cluster size: 4 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-9 (34.252.172.12 | 10.4.2.129) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-8 (54.246.172.3 | 10.4.1.151) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-7 (3.250.3.113 | 10.4.3.53) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-6 (34.246.134.56 | 10.4.3.170) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-5 (54.246.174.221 | 10.4.2.126) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-4 (34.250.98.41 | 10.4.3.125) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-3 (54.216.94.37 | 10.4.0.132) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-2 (54.217.30.72 | 10.4.1.10) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-18 (3.253.65.43 | 10.4.2.30) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-17 (3.252.162.131 | 10.4.1.107) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-16 (3.253.59.134 | 10.4.1.39) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-15 (3.251.82.127 | 10.4.3.225) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-14 (54.171.166.9 | 10.4.3.192) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-13 (34.255.0.184 | 10.4.0.53) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-12 (3.253.42.208 | 10.4.2.38) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-11 (34.241.200.97 | 10.4.1.60) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-10 (34.244.54.47 | 10.4.0.99) (shards: 7)
- longevity-lwt-parallel-24h-master-db-node-cceecfc1-1 (34.254.192.179 | 10.4.2.134) (shards: 7)

OS / Image: `ami-01edd05a94c7ebf24` (aws: eu-west-1)

Test: `longevity-lwt-parallel-schema-changes-with-disruptive-24h-raft-test`
Test id: `cceecfc1-f6b4-4c60-9731-084985c8903a`
Test name: `scylla-master/raft/longevity-lwt-parallel-schema-changes-with-disruptive-24h-raft-test`
Test config file(s):

- [longevity-lwt-parallel-24h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d007cef368b29d19563df5b4933744ae44448cb5/test-cases/longevity/longevity-lwt-parallel-24h.yaml)

## Issue description

**>>>>>>>**
raft enables configuration.
Ran a nemesis of DecommissionStreamingErr on node-6.
node-6 decommission was aborted.
Ran nodetool rebuild on node-6
command failed with a connection error.
```
< t:2022-12-12 11:15:01,933 f:nemesis.py      l:1612 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.DisruptiveMonkey: >>>>>>>>>>>>>Started random_disrupt_method decommission_streaming_err
< t:2022-12-12 11:15:01,934 f:nemesis.py      l:346  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.DisruptiveMonkey: Current Target: Node longevity-lwt-parallel-24h-master-db-node-cceecfc1-6 [34.246.134.56 | 10.4.3.170] (seed: False) with running nemesis: RepairStreamingErr Node longevity-lwt-parallel-24h-master-db-node-cceecfc1-8 [54.246.172.3 | 10.4.1.151] (seed: False)
< t:2022-12-12 11:15:01,934 f:nemesis.py      l:3782 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.DisruptiveMonkey: Start disruption at `2022-12-12 11:15:01.934947`
< t:2022-12-12 11:15:01,939 f:nemesis.py      l:1020 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.DisruptiveMonkey: Set current_disruption -> DecommissionStreamingErr Node longevity-lwt-parallel-24h-master-db-node-cceecfc1-6 [34.246.134.56 | 10.4.3.170] (seed: False)
< t:2022-12-12 11:15:04,034 f:nemesis.py      l:3770 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.DisruptiveMonkey: Data validator error: expected string or bytes-like object
< t:2022-12-12 11:15:20,051 f:nemesis.py      l:1769 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ModifyTableMonkey: _modify_table_property: ALTER TABLE cqlstress_lwt_example.blogposts WITH caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'};
< t:2022-12-12 11:15:21,679 f:nemesis.py      l:3843 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ModifyTableMonkey: ModifyTable Node longevity-lwt-parallel-24h-master-db-node-cceecfc1-7 [3.250.3.113 | 10.4.3.53] (seed: False) duration -> 205 s
< t:2022-12-12 11:15:21,684 f:nemesis.py      l:274  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ModifyTableMonkey: Update nemesis info with: {'start': 1670843516, 'end': 1670843721, 'duration': 205, 'node': 'Node longevity-lwt-parallel-24h-master-db-node-cceecfc1-7 [3.250.3.113 | 10.4.3.53] (seed: False)', 'subtype': 'end'}
< t:2022-12-12 11:15:21,904 f:nemesis_publisher.py l:103  c:sdcm.nemesis_publisher p:DEBUG > {'_index': 'nemesis_data', '_type': 'nemesis', '_id': 'k9ILBoUByHRlSQHx6MmK', '_version': 1, 'result': 'created', '_shards': {'total': 2, 'successful': 1, 'failed': 0}, '_seq_no': 268690, '_primary_term': 60}
< t:2022-12-12 11:15:21,904 f:nemesis.py      l:3858 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ModifyTableMonkey: log_info: {'start': 1670843516, 'end': 1670843721, 'duration': 205, 'node': 'Node longevity-lwt-parallel-24h-master-db-node-cceecfc1-7 [3.250.3.113 | 10.4.3.53] (seed: False)', 'subtype': 'end'}
< t:2022-12-12 11:15:22,570 f:nemesis.py      l:3770 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ModifyTableMonkey: Data validator error: expected string or bytes-like object
< t:2022-12-12 11:17:32,865 f:nemesis.py      l:3222 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.DisruptiveMonkey: The decommission of target node is successfully interrupted
< t:2022-12-12 11:17:32,868 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  rebuild "...
< t:2022-12-12 11:17:49,491 f:remote_libssh_cmd_runner.py l:66   c:RemoteLibSSH2CmdRunner p:ERROR > Command: '/usr/bin/nodetool  rebuild '
< t:2022-12-12 11:17:49,582 f:decorators.py   l:69   c:sdcm.utils.decorators p:DEBUG > '_run': failed with 'RetryableNetworkException('Failed to run a command due to exception!\n\nCommand: \'/usr/bin/nodetool  rebuild \'\n\nStdout:\n\n\n\nStderr:\n\n\n\nException:  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 589, in run\n    channel = self.open_channel()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 687, in open_channel\n    raise OpenChannelTimeout(f\'Failed to open channel in {timeout} seconds\')\n\nFailed to open channel in 15 seconds\n')', retrying [#0]
< t:2022-12-12 11:17:54,589 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  rebuild "...
< t:2022-12-12 11:17:56,605 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "/usr/bin/nodetool  rebuild "; Exit status: 1
< t:2022-12-12 11:17:56,645 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-12-12 11:17:56.640: (NodetoolEvent Severity.ERROR) period_type=end event_id=2a682055-5d4c-40d7-9730-13f4b1338f5e during_nemesis=DecommissionStreamingErr duration=23s: nodetool_command=rebuild node=longevity-lwt-parallel-24h-master-db-node-cceecfc1-6 errors=["Encountered a bad command exit code!\n\nCommand: '/usr/bin/nodetool  rebuild '\n\nExit code: 1\n\nStdout:\n\n\n\nStderr:\n\nnodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused (Connection refused)'.\n\n", 'Traceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2564, in run_nodetool\n    self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run\n    result = _run()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner\n    return func(*args, **kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run\n    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute\n    result = connection.run(**command_kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run\n    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run\n    raise UnexpectedExit(result)\nsdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!\n\nCommand: \'/usr/bin/nodetool  rebuild \'\n\nExit code: 1\n\nStdout:\n\n\n\nStderr:\n\nnodetool: Failed to connect to \'127.0.0.1:7199\' - ConnectException: \'Connection refused (Connection refused)\'.\n\n\n']
< t:2022-12-12 11:17:56,645 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Command: '/usr/bin/nodetool  rebuild '
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.DisruptiveMonkey: Unhandled exception in method <bound method Nemesis.disrupt_decommission_streaming_err of <sdcm.nemesis.DisruptiveMonkey object at 0x7f3888226a10>> < t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.DisruptiveMonkey: Unhandled exception in method <bound method Nemesis.disrupt_decommission_streaming_err of <sdcm.nemesis.DisruptiveMonkey object at 0x7f3888226a10>>
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3816, in wrapper
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >     result = method(*args[1:], **kwargs)
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3311, in disrupt_decommission_streaming_err
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >     self.start_and_interrupt_decommission_streaming()
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3250, in start_and_interrupt_decommission_streaming
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >     self.target_node.run_nodetool("rebuild")
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2564, in run_nodetool
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >     self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >     result = _run()
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >     return func(*args, **kwargs)
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >     result = connection.run(**command_kwargs)
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >     return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR >     raise UnexpectedExit(result)
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > 
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > Command: '/usr/bin/nodetool  rebuild '
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > 
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > Exit code: 1
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > 
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > Stdout:
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > 
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > 
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > 
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > Stderr:
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > 
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused (Connection refused)'.
< t:2022-12-12 11:17:56,655 f:nemesis.py      l:3826 c:sdcm.nemesis         p:ERROR > 
< t:2022-12-12 11:17:56,685 f:nemesis.py      l:3843 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.DisruptiveMonkey: DecommissionStreamingErr Node longevity-lwt-parallel-24h-master-db-node-cceecfc1-6 [34.246.134.56 | 10.4.3.170] (seed: False) duration -> 174 s

```

node-6 logs show some warnings/errors at that time like:
```
2022-12-12T11:17:13+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6     !INFO | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e0-7a0e-11ed-847b-000b983223c8] Aborted stream session, peer=10.4.1.151, is_initialized=true
2022-12-12T11:17:13+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6     !INFO | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e1-7a0e-11ed-847b-000b983223c8] Aborted stream session, peer=10.4.2.134, is_initialized=true
2022-12-12T11:17:13+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6     !INFO | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e2-7a0e-11ed-847b-000b983223c8] Aborted stream session, peer=10.4.3.53, is_initialized=true
2022-12-12T11:17:13+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6  !WARNING | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e0-7a0e-11ed-847b-000b983223c8] Streaming plan for Unbootstrap-cqlstress_lwt_example-index-0 failed, peers={10.4.1.151}, tx=5818 KiB, 44749.71 KiB/s, rx=0 KiB, 0.00 KiB/s
2022-12-12T11:17:13+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6  !WARNING | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e1-7a0e-11ed-847b-000b983223c8] Streaming plan for Unbootstrap-cqlstress_lwt_example-index-0 failed, peers={10.4.2.134}, tx=4615 KiB, 35501.62 KiB/s, rx=0 KiB, 0.00 KiB/s
2022-12-12T11:17:13+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6  !WARNING | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e2-7a0e-11ed-847b-000b983223c8] Streaming plan for Unbootstrap-cqlstress_lwt_example-index-0 failed, peers={10.4.3.53}, tx=4833 KiB, 37177.07 KiB/s, rx=0 KiB, 0.00 KiB/s
2022-12-12T11:17:20+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6  !WARNING | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e1-7a0e-11ed-847b-000b983223c8] stream_transfer_task: Fail to send STREAM_MUTATION_DONE to 10.4.2.134:0: seastar::rpc::remote_verb_error ([Stream #3d9020e1-7a0e-11ed-847b-000b983223c8] GOT STREAM_MUTATION_DONE from 10.4.3.170: Can not find stream_manager)
2022-12-12T11:17:20+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6  !WARNING | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e1-7a0e-11ed-847b-000b983223c8] stream_transfer_task: Fail to send to 10.4.2.134:0: seastar::rpc::remote_verb_error ([Stream #3d9020e1-7a0e-11ed-847b-000b983223c8] GOT STREAM_MUTATION_DONE from 10.4.3.170: Can not find stream_manager)
2022-12-12T11:17:20+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6  !WARNING | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e1-7a0e-11ed-847b-000b983223c8] Failed to send: seastar::rpc::remote_verb_error ([Stream #3d9020e1-7a0e-11ed-847b-000b983223c8] GOT STREAM_MUTATION_DONE from 10.4.3.170: Can not find stream_manager)
2022-12-12T11:17:20+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6  !WARNING | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e1-7a0e-11ed-847b-000b983223c8] Streaming error occurred, peer=10.4.2.134
2022-12-12T11:17:20+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6  !WARNING | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e2-7a0e-11ed-847b-000b983223c8] stream_transfer_task: Fail to send STREAM_MUTATION_DONE to 10.4.3.53:0: seastar::rpc::remote_verb_error ([Stream #3d9020e2-7a0e-11ed-847b-000b983223c8] GOT STREAM_MUTATION_DONE from 10.4.3.170: Can not find stream_manager)
2022-12-12T11:17:20+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6  !WARNING | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e2-7a0e-11ed-847b-000b983223c8] stream_transfer_task: Fail to send to 10.4.3.53:0: seastar::rpc::remote_verb_error ([Stream #3d9020e2-7a0e-11ed-847b-000b983223c8] GOT STREAM_MUTATION_DONE from 10.4.3.170: Can not find stream_manager)
2022-12-12T11:17:20+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6  !WARNING | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e2-7a0e-11ed-847b-000b983223c8] Failed to send: seastar::rpc::remote_verb_error ([Stream #3d9020e2-7a0e-11ed-847b-000b983223c8] GOT STREAM_MUTATION_DONE from 10.4.3.170: Can not find stream_manager)
2022-12-12T11:17:20+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6  !WARNING | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e2-7a0e-11ed-847b-000b983223c8] Streaming error occurred, peer=10.4.3.53
2022-12-12T11:17:20+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6  !WARNING | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e0-7a0e-11ed-847b-000b983223c8] stream_transfer_task: Fail to send STREAM_MUTATION_DONE to 10.4.1.151:0: seastar::rpc::remote_verb_error ([Stream #3d9020e0-7a0e-11ed-847b-000b983223c8] GOT STREAM_MUTATION_DONE from 10.4.3.170: Can not find stream_manager)
2022-12-12T11:17:20+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6  !WARNING | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e0-7a0e-11ed-847b-000b983223c8] stream_transfer_task: Fail to send to 10.4.1.151:0: seastar::rpc::remote_verb_error ([Stream #3d9020e0-7a0e-11ed-847b-000b983223c8] GOT STREAM_MUTATION_DONE from 10.4.3.170: Can not find stream_manager)
2022-12-12T11:17:20+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6  !WARNING | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e0-7a0e-11ed-847b-000b983223c8] Failed to send: seastar::rpc::remote_verb_error ([Stream #3d9020e0-7a0e-11ed-847b-000b983223c8] GOT STREAM_MUTATION_DONE from 10.4.3.170: Can not find stream_manager)
2022-12-12T11:17:20+00:00 longevity-lwt-parallel-24h-master-db-node-cceecfc1-6  !WARNING | scylla[8367]:  [shard 0] stream_session - [Stream #3d9020e0-7a0e-11ed-847b-000b983223c8] Streaming error occurred, peer=10.4.1.151
```
**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor cceecfc1-f6b4-4c60-9731-084985c8903a`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=cceecfc1-f6b4-4c60-9731-084985c8903a)
- Show all stored logs command: `$ hydra investigate show-logs cceecfc1-f6b4-4c60-9731-084985c8903a`

## Logs:
- **db-cluster-cceecfc1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/db-cluster-cceecfc1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/db-cluster-cceecfc1.tar.gz)
- **monitor-set-cceecfc1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/monitor-set-cceecfc1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/monitor-set-cceecfc1.tar.gz)
- **loader-set-cceecfc1.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/loader-set-cceecfc1.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/loader-set-cceecfc1.tar.gz)
- **normal-cceecfc1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/normal-cceecfc1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/normal-cceecfc1.log.tar.gz)
- **summary-cceecfc1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/summary-cceecfc1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/summary-cceecfc1.log.tar.gz)
- **events-cceecfc1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/events-cceecfc1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/events-cceecfc1.log.tar.gz)
- **output-cceecfc1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/output-cceecfc1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/output-cceecfc1.log.tar.gz)
- **debug-cceecfc1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/debug-cceecfc1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/debug-cceecfc1.log.tar.gz)
- **sct-cceecfc1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/sct-cceecfc1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/sct-cceecfc1.log.tar.gz)
- **error-cceecfc1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/error-cceecfc1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/error-cceecfc1.log.tar.gz)
- **critical-cceecfc1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/critical-cceecfc1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/critical-cceecfc1.log.tar.gz)
- **raw_events-cceecfc1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/raw_events-cceecfc1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/raw_events-cceecfc1.log.tar.gz)
- **warning-cceecfc1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/warning-cceecfc1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/warning-cceecfc1.log.tar.gz)
- **email_data-cceecfc1.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/email_data-cceecfc1.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/email_data-cceecfc1.json.tar.gz)
- **argus-cceecfc1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/argus-cceecfc1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/argus-cceecfc1.log.tar.gz)
- **left_processes-cceecfc1.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/left_processes-cceecfc1.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cceecfc1-f6b4-4c60-9731-084985c8903a/20221213_014730/left_processes-cceecfc1.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/raft/job/longevity-lwt-parallel-schema-changes-with-disruptive-24h-raft-test/2/)

**Comment by roydahan** [comment]
This is a dup of #11507
