### ISSUE TITLE
Failed to start the native thread for java.lang.Thread "Keep-Alive-Timer"

### ISSUE THREAD

**Issue by calvin2021y** [scylladb/scylladb#12322]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): scylladb/scylla:5.1
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu22.1

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): docker
Hardware:    privileged: true --smp 8 --memory 32G --developer-mode 0 --listen-address  
Disks: 1.5Tx1 nvme

**Comment by calvin2021y** [comment]
```sh
scylla  | INFO  2022-12-12 06:13:13,295 [shard 2] compaction - [Compact system.peers 0f324310-79e4-11ed-aa1e-63c1d8201b30] Compacted 2 sstables to [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/me-146-big-Data.db:level=0]. 159kB to 114kB (~71% of original) in 12ms = 9MB/s. ~256 total partitions merged to 2.
scylla  | [25861.060s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
scylla  | [25861.060s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Keep-Alive-Timer"
scylla  | Traceback (most recent call last):
scylla  |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 196, in <module>
scylla  |     args.func(args)
scylla  |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 122, in check_version
scylla  |     current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
scylla  |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 80, in get_api
scylla  |     return get_json_from_url("http://" + api_address + path)
scylla  |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 62, in get_json_from_url
scylla  |     pool = mp.Pool(processes=1)
scylla  |   File "/opt/scylladb/python3/lib64/python3.9/multiprocessing/context.py", line 119, in Pool
scylla  |     return Pool(processes, initializer, initargs, maxtasksperchild,
scylla  |   File "/opt/scylladb/python3/lib64/python3.9/multiprocessing/pool.py", line 232, in __init__
scylla  |     self._worker_handler.start()
scylla  |   File "/opt/scylladb/python3/lib64/python3.9/threading.py", line 899, in start
scylla  |     _start_new_thread(self._bootstrap, ())
scylla  | RuntimeError: can't start new thread
scylla  | Traceback (most recent call last):
scylla  |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 196, in <module>
scylla  |     args.func(args)
scylla  |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 122, in check_version
scylla  |     current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
scylla  |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 80, in get_api
scylla  |     return get_json_from_url("http://" + api_address + path)
scylla  |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 62, in get_json_from_url
scylla  |     pool = mp.Pool(processes=1)
scylla  |   File "/opt/scylladb/python3/lib64/python3.9/multiprocessing/context.py", line 119, in Pool
scylla  |     return Pool(processes, initializer, initargs, maxtasksperchild,
scylla  |   File "/opt/scylladb/python3/lib64/python3.9/multiprocessing/pool.py", line 232, in __init__
scylla  |     self._worker_handler.start()
scylla  |   File "/opt/scylladb/python3/lib64/python3.9/threading.py", line 899, in start
scylla  |     _start_new_thread(self._bootstrap, ())
scylla  | RuntimeError: can't start new thread
```
