### ISSUE TITLE
docker: seastar - Exiting on unhandled exception: std::system_error (error system:5, Input/output error)

### ISSUE THREAD

**Issue by Bessonov** [scylladb/scylladb#12807]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): docker image: scylladb/scylla:5.1.4
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): host: Ubuntu 22.04.1 LTS

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): VirtualBox on Win11 Pro
Hardware: sockets=1 cores=14 hyperthreading=20 (i9-12900H) memory=23.4GB
Disks: (SSD/HDD, count): SSD, 1

docker compose:
```yaml
version: "3.9"
services:

  scylla:
    image: scylladb/scylla:5.1.4
    restart: "no"
    cap_add:
      - sys_nice
    command:
      - --smp=1
      - --developer-mode=0
```

Log:
```
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '0'],)
running: (['/opt/scylladb/scripts/scylla_io_setup'],)
WARN  2023-02-11 22:08:20,315 [shard  0] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
INFO  2023-02-11 22:08:20,315 [shard  0] seastar - Created fair group io-queue-0, capacity rate 2147483:2147483, limit 12582912, rate 16777216 (factor 1), threshold 2000
INFO  2023-02-11 22:08:20,315 [shard  0] seastar - IO queue uses 0.75ms latency goal for device 0
INFO  2023-02-11 22:08:20,315 [shard  0] seastar - Created io group dev(0), length limit 4194304:4194304, rate 2147483647:2147483647
INFO  2023-02-11 22:08:20,315 [shard  0] seastar - Created io queue dev(0) capacities: 512:2000:2000 1024:3000:3000 2048:5000:5000 4096:9000:9000 8192:17000:17000 16384:33000:33000 32768:65000:65000 65536:129000:129000 131072:257000:257000
WARN  2023-02-11 22:08:20,356 [shard  8] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,356 [shard  6] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,358 [shard  5] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,359 [shard 13] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,360 [shard  3] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,361 [shard  2] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,361 [shard 12] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,362 [shard 16] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,363 [shard  9] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,363 [shard 14] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,364 [shard 10] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,364 [shard 19] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,365 [shard  4] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,366 [shard  7] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,367 [shard 17] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,367 [shard 15] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,367 [shard  1] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,368 [shard 11] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
WARN  2023-02-11 22:08:20,369 [shard 18] seastar - Creation of perf_event based stall detector failed, falling back to posix timer: std::system_error (error system:1, perf_event_open() failed: Operation not permitted)
INFO  2023-02-11 22:08:20,457 [shard  0] iotune - /var/lib/scylla/view_hints passed sanity checks
WARN  2023-02-11 22:08:20,457 [shard  0] iotune - Scheduler for /sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/queue/scheduler set to mq-deadline. It is recommend to set it to noop before evaluation so as not to skew the results.
WARN  2023-02-11 22:08:20,458 [shard  0] iotune - nomerges for /sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/queue/nomerges set to 0. It is recommend to set it to 2 before evaluation so that merges are disabled. Results can be skewed otherwise.
WARN  2023-02-11 22:08:20,458 [shard  0] iotune - write_cache for /sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/queue/write_cache is set to write back. Some disks have poor implementation of this mode, pay attention to the measurements accuracy.
INFO  2023-02-11 22:08:20,458 [shard  0] iotune - Disk parameters: max_iodepth=64 disks_per_array=1 minimum_io_size=512
Starting Evaluation. This may take a while...
ERROR 2023-02-11 22:09:32,795 [shard  0] seastar - Exiting on unhandled exception: std::system_error (error system:5, Input/output error)
ERROR:root:Command '['/usr/bin/iotune', '--format', 'envfile', '--options-file', '/etc/scylla.d/io.conf', '--properties-file', '/etc/scylla.d/io_properties.yaml', '--evaluation-directory', '/var/lib/scylla/data', '--evaluation-directory', '/var/lib/scylla/commitlog', '--evaluation-directory', '/var/lib/scylla/hints', '--evaluation-directory', '/var/lib/scylla/view_hints']' returned non-zero exit status 1.
ERROR:root:['/var/lib/scylla/data', '/var/lib/scylla/commitlog', '/var/lib/scylla/hints', '/var/lib/scylla/view_hints'] did not pass validation tests, it may not be on XFS and/or has limited disk space.
This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is required.
To override this error, enable developer mode as follow:
sudo /opt/scylladb/scripts/scylla_dev_mode_setup --developer-mode 1
Measuring sequential write bandwidth: tuning /sys/devices/virtual/block/dm-0
tuning: /sys/devices/virtual/block/dm-0/queue/nomerges 2
warning: unable to tune /sys/devices/virtual/block/dm-0/queue/nomerges to 2

tuning /sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda3
tuning /sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
tuning: /sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/queue/nomerges to 2

tuning /sys/devices/virtual/block/dm-0
tuning /sys/devices/virtual/block/dm-0
tuning /sys/devices/virtual/block/dm-0
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 27, in <module>
    setup.io()
  File "/scyllasetup.py", line 67, in io
    self._run(['/opt/scylladb/scripts/scylla_io_setup'])
  File "/scyllasetup.py", line 37, in _run
    subprocess.check_call(*args, **kwargs)
  File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_io_setup']' returned non-zero exit status 1.
```

```bash
$ df -m
Filesystem                        1M-blocks    Used Available Use% Mounted on
tmpfs                                  2393       2      2392   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv    783706  315535    436464  42% /
tmpfs                                 11965     196     11769   2% /dev/shm
tmpfs                                     5       0         5   0% /run/lock
/dev/sda2                              1946      82      1746   5% /boot
vagrant                             1951519 1052781    898738  54% /vagrant
tmpfs                                  2393       1      2393   1% /run/user/1000

$ docker -v
Docker version 20.10.21, build baeda1f

$ docker-compose -v
Docker Compose version v2.8.0
```

Tried also create a volume and even bind:
```yaml
version: "3.9"
services:

  scylla:
    image: scylladb/scylla:5.1.4
    restart: "no"
    cap_add:
      - sys_nice
    command:
      - --smp=1
      - --developer-mode=0
    volumes:
      - scylla-data:/var/lib/scylla

volumes:
  scylla-data:
  # or
  scylla-data:
    driver: local
    driver_opts:
      type: none
      device: "${PWD}/scylla"
      o: bind
```

**Comment by Bessonov** [comment]
privileged mode produces less warnings, but still the same error:
```
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '0'],)
running: (['/opt/scylladb/scripts/scylla_io_setup'],)
INFO  2023-02-11 23:01:24,119 [shard 19] seastar - Created fair group io-queue-0, capacity rate 2147483:2147483, limit 12582912, rate 16777216 (factor 1), threshold 2000
INFO  2023-02-11 23:01:24,120 [shard 19] seastar - IO queue uses 0.75ms latency goal for device 0
INFO  2023-02-11 23:01:24,120 [shard 19] seastar - Created io group dev(0), length limit 4194304:4194304, rate 2147483647:2147483647
INFO  2023-02-11 23:01:24,120 [shard  0] seastar - Created io queue dev(0) capacities: 512:2000:2000 1024:3000:3000 2048:5000:5000 4096:9000:9000 8192:17000:17000 16384:33000:33000 32768:65000:65000 65536:129000:129000 131072:257000:257000
INFO  2023-02-11 23:01:24,229 [shard  0] iotune - /var/lib/scylla/view_hints passed sanity checks
WARN  2023-02-11 23:01:24,229 [shard  0] iotune - Scheduler for /sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/queue/scheduler set to mq-deadline. It is recommend to set it to noop before evaluation so as not to skew the results.
WARN  2023-02-11 23:01:24,229 [shard  0] iotune - write_cache for /sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/queue/write_cache is set to write back. Some disks have poor implementation of this mode, pay attention to the measurements accuracy.
INFO  2023-02-11 23:01:24,229 [shard  0] iotune - Disk parameters: max_iodepth=64 disks_per_array=1 minimum_io_size=512
Starting Evaluation. This may take a while...
ERROR 2023-02-11 23:01:31,225 [shard  0] seastar - Exiting on unhandled exception: std::system_error (error system:5, Input/output error)
ERROR:root:Command '['/usr/bin/iotune', '--format', 'envfile', '--options-file', '/etc/scylla.d/io.conf', '--properties-file', '/etc/scylla.d/io_properties.yaml', '--evaluation-directory', '/var/lib/scylla/data', '--evaluation-directory', '/var/lib/scylla/commitlog', '--evaluation-directory', '/var/lib/scylla/hints', '--evaluation-directory', '/var/lib/scylla/view_hints']' returned non-zero exit status 1.
ERROR:root:['/var/lib/scylla/data', '/var/lib/scylla/commitlog', '/var/lib/scylla/hints', '/var/lib/scylla/view_hints'] did not pass validation tests, it may not be on XFS and/or has limited disk space.
This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is required.
To override this error, enable developer mode as follow:
sudo /opt/scylladb/scripts/scylla_dev_mode_setup --developer-mode 1
Measuring sequential write bandwidth: tuning /sys/devices/virtual/block/dm-0
tuning: /sys/devices/virtual/block/dm-0/queue/nomerges 2
tuning /sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda3
tuning /sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
tuning: /sys/devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/queue/nomerges 2
tuning /sys/devices/virtual/block/dm-0
tuning /sys/devices/virtual/block/dm-0
tuning /sys/devices/virtual/block/dm-0
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 27, in <module>
    setup.io()
  File "/scyllasetup.py", line 67, in io
    self._run(['/opt/scylladb/scripts/scylla_io_setup'])
  File "/scyllasetup.py", line 37, in _run
    subprocess.check_call(*args, **kwargs)
  File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_io_setup']' returned non-zero exit status 1.
```

**Comment by mykaul** [comment]
I think the important warning is:
```
ERROR:root:['/var/lib/scylla/data', '/var/lib/scylla/commitlog', '/var/lib/scylla/hints', '/var/lib/scylla/view_hints'] did not pass validation tests, it may not be on XFS and/or has limited disk space.
This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is required.
To override this error, enable developer mode as follow:
sudo /opt/scylladb/scripts/scylla_dev_mode_setup --developer-mode 1
```

Can you confirm that's the case, and using developer-mode helps?

**Comment by Bessonov** [comment]
@mykaul Yes, developer mode works. I see I misread the message, sorry for that. I thought it was not allowed on xfs, but it is required.

Are there any benchmarks related to scylla on xfs vs. other file systems? I only found a comparison file systems like https://openbenchmarking.org/result/2111298-TJ-2111232TJ87 but they don't show a clear difference between the file systems.

Digging in the reasons I found [this note]( https://docs.scylladb.com/stable/troubleshooting/error-messages/kb-fs-not-qualified-aio.html):
```
Scylla requires using the XFS filesystem, since it is the only Linux filesystem with good Asynchronous I/O support. In addition, Linux kernels before 3.15 did not have good asynchronous append support, which is required by Scylla.
```

The note also mentions CentOS 7.2 and Ubuntu 14.04. I haven't found the original docs repo to see when the note was added, but it feels like it might be outdated. Unfortunately, I haven't found any evidence.

After several retries I saw that sometimes scylla starts successfully and iotune prints benchmark results. Digging deeper into [iotune.cc](https://github.com/scylladb/seastar/blob/master/apps/iotune/iotune.cc) leads me to the idea that the problem isn't related to xfs, but to my setup. I think the message is misleading because there is no check or (hard) requirement for xfs, but for certain drive characteristics. I haven't tested this, but I think the problem is that the Host I/O Cache setting is enabled in VirtualBox, which leads to inconsistent results. I can't disable it for some other reason.

Also, I found a very old [blog post about the validation](https://www.scylladb.com/2016/02/09/qualifying-filesystems/). It would be nice if iotune could print a more detailed analysis or errors instead of just I/O errors. Or doesn't it make sense?

I am fine to close this issue, because it is a local problem.

**Comment by mykaul** [comment]
We are very happy with XFS and I'm not sure anyone has looked /  is looking at other file systems.

**Comment by nyh** [comment]
> We are happy with XFS and I'm not sure anyone has looked / is looking at other file systems.

A long time ago, when we started Scylla, only XFS supported certain features that we needed for asynchronous I/O performance, but I don't know how much of those problems remain true in ext4 and btrfs on modern Linux. I think we should describe the filesystem situation in README.md and/or a file in docs/. It's really weird that if someone installs Scylla without our AMI, they will only discover that they should have used XFS when running Scylla.
