### ISSUE TITLE
A node gets unbalanced increasing number of reads/writes + failed/blocked reads/writes and active sstables, then c-s fail

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#13169]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Scenario:
The test was running a scylla-manager repair.
Node-2 (longevity-tls-1tb-7d-2023-1-db-node-52776f27-2 [34.244.176.55 | 10.4.3.44]) got continues unproportional read/write/failure rates. All other nodes had equal and much lower rates.
The CPU load for all nodes continuesly increased over a few hours.
Then at 13.27 all nodes got to a 100% usage peak and a c-s write load failed with:
```
< t:2023-03-05 13:27:00,229 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
< t:2023-03-05 13:27:00,253 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
< t:2023-03-05 13:27:00,253 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
< t:2023-03-05 13:27:00,253 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
< t:2023-03-05 13:27:00,253 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
< t:2023-03-05 13:27:00,253 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
< t:2023-03-05 13:27:00,253 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
< t:2023-03-05 13:27:00,253 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:473)
< t:2023-03-05 13:27:00,253 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
< t:2023-03-05 13:27:00,253 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > total,    3785645806,       0,       0,       0, 20023.6, 20032.0, 20032.0, 20032.0, 20032.0, 20032.0,222758.1,  0.00101,      1,      0,       0,       0,       0,       0
< t:2023-03-05 13:27:00,253 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
< t:2023-03-05 13:27:00,253 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > java.io.IOException: Operation x10 on key(s) [37344e50373235323531]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
< t:2023-03-05 13:27:00,253 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
< t:2023-03-05 13:27:00,253 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 
< t:2023-03-05 13:27:00,253 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
< t:2023-03-05 13:27:00,254 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
< t:2023-03-05 13:27:00,254 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
< t:2023-03-05 13:27:00,254 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > 	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)

```

The unbalanced metrics for node-2 are:
![image](https://user-images.githubusercontent.com/9427929/225034124-e7afc4c8-4ada-4045-846c-21ec45a3bebf.png)

## Impact

Nodes eventually got to ~ 100% CPU and c-s load failed.

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1031-aws
Scylla version (or git commit hash): `2023.1.0~rc2-20230302.726f8a090337` with build-id `efcc950cda22875aa488c5295c6cc68f35d9cc6f`

Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-1tb-7d-2023-1-db-node-52776f27-8 (54.247.18.109 | 10.4.1.79) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-52776f27-7 (3.253.57.198 | 10.4.3.240) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-52776f27-6 (34.247.183.17 | 10.4.0.35) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-52776f27-5 (3.250.177.43 | 10.4.2.134) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-52776f27-4 (54.75.80.9 | 10.4.1.130) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-52776f27-3 (54.72.86.47 | 10.4.1.247) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-52776f27-2 (34.244.176.55 | 10.4.3.44) (shards: 14)
- longevity-tls-1tb-7d-2023-1-db-node-52776f27-1 (34.245.12.22 | 10.4.0.24) (shards: 14)

OS / Image: `ami-0336a5a646b08dc25` (aws: eu-west-1)

Test: `ics-longevity-1tb-7days-test`
Test id: `52776f27-b99b-444c-982e-89fbb62999ad`
Test name: `enterprise-2023.1/SCT_Enterprise_Features/ICS/ics-longevity-1tb-7days-test`
Test config file(s):

- [longevity-1TB-5days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9a5f163455e77d1518d00ea2a5ac14df134cf2f6/test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 52776f27-b99b-444c-982e-89fbb62999ad`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=52776f27-b99b-444c-982e-89fbb62999ad)
- Show all stored logs command: `$ hydra investigate show-logs 52776f27-b99b-444c-982e-89fbb62999ad`

## Logs:
- **db-cluster-52776f27.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/db-cluster-52776f27.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/db-cluster-52776f27.tar.gz)
- **output-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/output-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/output-52776f27.log.tar.gz)
- **debug-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/debug-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/debug-52776f27.log.tar.gz)
- **events-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/events-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/events-52776f27.log.tar.gz)
- **sct-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/sct-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/sct-52776f27.log.tar.gz)
- **normal-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/normal-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/normal-52776f27.log.tar.gz)
- **argus-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/argus-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/argus-52776f27.log.tar.gz)
- **raw_events-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/raw_events-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/raw_events-52776f27.log.tar.gz)
- **critical-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/critical-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/critical-52776f27.log.tar.gz)
- **warning-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/warning-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/warning-52776f27.log.tar.gz)
- **summary-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/summary-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/summary-52776f27.log.tar.gz)
- **error-52776f27.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/error-52776f27.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/error-52776f27.log.tar.gz)
- **monitor-set-52776f27.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/monitor-set-52776f27.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/monitor-set-52776f27.tar.gz)
- **loader-set-52776f27.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/loader-set-52776f27.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/52776f27-b99b-444c-982e-89fbb62999ad/20230307_211805/loader-set-52776f27.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/SCT_Enterprise_Features/job/ICS/job/ics-longevity-1tb-7days-test/2/)
</details>

**Comment by fgelcer** [comment]
@yarongilor , please let's gather more details about node-2 here, before, during and after the `manager-repair` operation...
let's check if the node for some reason was already overloaded or not... let's also check if there were reactor stalls during this time window.

**Comment by yarongilor** [comment]
> ere, before, during and after the `manager-repair` operation...
> let's check if the node for some reason was already overloaded or not...

@fgelcer , the grafana indicates the node was unbalanced, with `read` related metrics, right from test start
![image](https://user-images.githubusercontent.com/9427929/227235728-063e7545-829d-4b27-851f-fed99048d88f.png)

**Comment by mykaul** [comment]
Any idea what could have caused this imbalance? What should we change in the tests to ensure we do get consistent results, or fail the test sooner?

**Comment by fgelcer** [comment]
> Any idea what could have caused this imbalance? What should we change in the tests to ensure we do get consistent results, or fail the test sooner?

not sure, and we are perhaps seeing this in one of our perf tests (@aleksbykov saw this somewhere in this week's runs)

**Comment by aleksbykov** [comment]
@yarongilor , did you find Segmentation Fault or coredump?

**Comment by asias** [comment]
Looking at the time frame 2022.3.5 11:30 to 14:00 UTC. 

The 

scylla_database_total_writes 
scylla_database_total_reads

are almost the same on all nodes. 

Only 

scylla_storage_proxy_coordinator_foreground_writes 
scylla_storage_proxy_coordinator_background_writes

scylla_storage_proxy_coordinator_foreground_reads
scylla_storage_proxy_coordinator_background_reads

are have big difference between nodes.

![image](https://user-images.githubusercontent.com/320076/228150975-9cbf8fe3-5754-4d46-a91a-71fd41ae3f9d.png)

**Comment by DoronArazii** [comment]
> Looking at the time frame 2022.3.5 11:30 to 14:00 UTC.
> 
> The
> 
> scylla_database_total_writes scylla_database_total_reads
> 
> are almost the same on all nodes.
> 
> Only
> 
> scylla_storage_proxy_coordinator_foreground_writes scylla_storage_proxy_coordinator_background_writes
> 
> scylla_storage_proxy_coordinator_foreground_reads scylla_storage_proxy_coordinator_background_reads
> 
> are have big difference between nodes.
> 
> ![image](https://user-images.githubusercontent.com/320076/228150975-9cbf8fe3-5754-4d46-a91a-71fd41ae3f9d.png)

@asias what's the bottom line? nor next steps?

**Comment by DoronArazii** [comment]
@asias ping

**Comment by DoronArazii** [comment]
Missed the train to 5.2, pushing to 5.3
