### ISSUE TITLE
run default docker error: too many positional options have been specified on the command line

### ISSUE THREAD

**Issue by ultperf** [scylladb/scylladb#13182]
root@cldxs-1:/home/ubuntu# docker run -v /var/lib/scylla:/var/lib/scylla -h cldxs-1 --name cldxs-1 -it scylladb/scylla /bin/bash
```
2023-03-15 08:55:22,827 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-15 08:55:22,828 INFO exited: scylla (exit status 2; not expected)
2023-03-15 08:55:23,831 INFO spawned: 'scylla' with pid 103
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 196, in <module>
    args.func(args)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 122, in check_version
    current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 80, in get_api
    return get_json_from_url("http://" + api_address + path)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 75, in get_json_from_url
    raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
RuntimeError: Failed to get "http://localhost:10000/storage_service/scylla_release_version" due to the following error: <urlopen error [Errno 99] Cannot assign requested address>
Scylla version 5.1.6-0.20230223.530600a64674 with build-id c38178ef635d4ac7f67a8a3ce666056c81f5afb9 starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.2 --rpc-address 172.17.0.2 --seed-provider-parameters seeds=172.17.0.2 --alternator-address 172.17.0.2 --blocked-reactor-notify-ms 999999999 /bin/bash"
parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.2, rpc-address: 172.17.0.2, seed-provider-parameters: seeds=172.17.0.2, alternator-address: 172.17.0.2, blocked-reactor-notify-ms, (positional) 999999999, (positional) /bin/bash]
error: too many positional options have been specified on the command line

Try --help.
2023-03-15 08:55:25,255 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-03-15 08:55:25,256 INFO exited: scylla (exit status 2; not expected)
2023-03-15 08:55:26,259 INFO spawned: 'scylla' with pid 119
Scylla version 5.1.6-0.20230223.530600a64674 with build-id c38178ef635d4ac7f67a8a3ce666056c81f5afb9 starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.2 --rpc-address 172.17.0.2 --seed-provider-parameters seeds=172.17.0.2 --alternator-address 172.17.0.2 --blocked-reactor-notify-ms 999999999 /bin/bash"
parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.2, rpc-address: 172.17.0.2, seed-provider-parameters: seeds=172.17.0.2, alternator-address: 172.17.0.2, blocked-reactor-notify-ms, (positional) 999999999, (positional) /bin/bash]
error: too many positional options have been specified on the command line

```

having this problem running on docker. how to resolve?

**Comment by michoecho** [comment]
What are you trying to do?
You are running
```
docker run -v /var/lib/scylla:/var/lib/scylla -h cldxs-1 --name cldxs-1 -it scylladb/scylla /bin/bash
```
so you are passing `/bin/bash` as an argument to Scylla.

If you just want to run Scylla, get rid of the `/bin/bash` and run e.g.
```
docker run -v /var/lib/scylla:/var/lib/scylla -h cldxs-1 --name cldxs-1 -it scylladb/scylla
```

Or, if you are actually trying to run bash from within a Scylla image, without starting Scylla itself, then you have to change the ENTRYPOINT of the image:
```
docker run --entrypoint /bin/bash -v /var/lib/scylla:/var/lib/scylla -h cldxs-1 --name cldxs-1 -it scylladb/scylla
```

**Comment by nyh** [comment]
https://github.com/scylladb/scylladb/issues/16502 has some guesses on what might cause this problem.
One or both of these issues should probably be closed. I don't know if this can still happen in the docker image we have now, almost two years later.
