### ISSUE TITLE
scylla-api-client fail

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#13185]
*Installation details*
Scylla version (or git commit hash): 5.2-rc2 on Docker
Cluster size: 1

`scylla-api-client -l` should return a list of APIs, but it fails

```
]0;root@e5d337afe5ee: /root@e5d337afe5ee:/# scylla-api-client -l
scylla-api-client -l
Traceback (most recent call last):
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/urllib3/response.py", line 748, in _update_chunk_length
    self.chunk_left = int(line, 16)
                      ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/urllib3/response.py", line 443, in _error_catcher
    yield
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/urllib3/response.py", line 815, in read_chunked
    self._update_chunk_length()
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/urllib3/response.py", line 752, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/urllib3/response.py", line 623, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/urllib3/response.py", line 803, in read_chunked
    with self._error_catcher():
  File "/opt/scylladb/python3/lib64/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/urllib3/response.py", line 460, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scylladb/python3/bin/libexec/scylla-api-client", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/scylla_api_client/cli.py", line 95, in main
    scylla_api = load_api(node_address=node_address, port=port)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/scylla_api_client/cli.py", line 59, in load_api
    scylla_api.load()
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/scylla_api_client/api.py", line 390, in load
    module_json = self.client.get_raw_api_json(f"{module_def['path']}/")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/scylla_api_client/rest/scylla_rest_client.py", line 11, in get_raw_api_json
    if api := self.get(f"/api-doc{resource_path}"):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/scylla_api_client/rest/scylla_rest_client.py", line 16, in get
    return super().get(resource_path=resource_path, query_params=query_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/scylla_api_client/rest/__init__.py", line 69, in get
    return requests.get(url=url, params=query_params, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/requests/sessions.py", line 745, in send
    r.content
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/requests/models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/python3/lib64/python3.11/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```

**Comment by tzach** [comment]
@bhalevy FYI

**Comment by tzach** [comment]
@bhalevy ping

**Comment by bhalevy** [comment]
@benipeled can you please look into this?
Could it be a packaging issue?

**Comment by benipeled** [comment]
@tzach are you using the `scylladb/scylla:5.2` image? I can see an issue with this specific image (scylla doesn't start) but it's an old image that hasn't been updated since 5.2 is not yet released,
The image will be updated once 5.2.0 (GA) is promoted. we can remove the `scylladb/scylla:5.2` image.

**Comment by mykaul** [comment]
Is there a test in our CI for this small scenario?

**Comment by tzach** [comment]
Closing, fail to repreduce.

**Comment by benipeled** [comment]
> Is there a test in our CI for this small scenario?

AFAIK we have no docker tests on both unit/sanity stages
The docker test pipeline is triggered later by the build pipeline (CI > next > build > docker)
We might want to add docker smoke tests - start/stop etc.
