### ISSUE TITLE
Segfault while waiting on wasm::task_queue on stop

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#13228]
Seen in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/106/ while checking PR #13213 

Calltrace
```
INFO  2023-03-17 10:22:58,606 [shard 0] init - Scylla version 5.3.0~dev-0.20230317.afa8fcfcfde6 initialization completed.
INFO  2023-03-17 10:23:00,260 [shard 0] compaction_manager - Asked to stop
Segmentation fault.
Backtrace:
  0x52a35e8
  0x52d5dd6
  /jenkins/workspace/scylla-master/scylla-ci/scylla/.ccm/scylla-repository/13213/libreloc/libc.so.6+0x3cb1f
  0x52c46c0
  /jenkins/workspace/scylla-master/scylla-ci/scylla/.ccm/scylla-repository/13213/libreloc/libc.so.6+0x3cb1f
  /jenkins/workspace/scylla-master/scylla-ci/scylla/.ccm/scylla-repository/13213/libreloc/libc.so.6+0x87d13
  /jenkins/workspace/scylla-master/scylla-ci/scylla/.ccm/scylla-repository/13213/libreloc/libc.so.6+0x8a50f
  /jenkins/workspace/scylla-master/scylla-ci/scylla/.ccm/scylla-repository/13213/libreloc/libstdc++.so.6+0xd510f
  0x3ff0fb7
  /jenkins/workspace/scylla-master/scylla-ci/scylla/.ccm/scylla-repository/13213/libreloc/libstdc++.so.6+0xdbc02
  /jenkins/workspace/scylla-master/scylla-ci/scylla/.ccm/scylla-repository/13213/libreloc/libc.so.6+0x8b12c
  /jenkins/workspace/scylla-master/scylla-ci/scylla/.ccm/scylla-repository/13213/libreloc/libc.so.6+0x10cbbf

```

Decoded

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f54750afe5c in __pthread_kill_implementation () from /jenkins/workspace/scylla-master/scylla-ci/scylla/.ccm/scylla-repository/13213/libreloc/libc.so.6
[Current thread is 1 (Thread 0x7f54719ff6c0 (LWP 19863))]
(gdb) bt
#0  0x00007f54750afe5c in __pthread_kill_implementation () from /jenkins/workspace/scylla-master/scylla-ci/scylla/.ccm/scylla-repository/13213/libreloc/libc.so.6
#1  0x00000000052d5df5 in seastar::reraise_signal (signo=11) at ./seastar/src/core/reactor.cc:3873
#2  seastar::sigsegv_action () at ./seastar/src/core/reactor.cc:3878
#3  seastar::install_oneshot_signal_handler<11, (void (*)())(&seastar::sigsegv_action)>()::{lambda(int, siginfo_t*, void*)#1}::operator()(int, siginfo_t*, void*) const (this=<optimized out>, sig=<optimized out>, info=<optimized out>, 
    p=<optimized out>) at ./seastar/src/core/reactor.cc:3858
#4  seastar::install_oneshot_signal_handler<11, (void (*)())(&seastar::sigsegv_action)>()::{lambda(int, siginfo_t*, void*)#1}::__invoke(int, siginfo_t*, void*) (sig=11, info=<optimized out>, p=<optimized out>)
    at ./seastar/src/core/reactor.cc:3854
#5  <signal handler called>
#6  std::__uniq_ptr_impl<seastar::reactor_backend, std::default_delete<seastar::reactor_backend> >::_M_ptr (this=0x28) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/unique_ptr.h:191
#7  std::unique_ptr<seastar::reactor_backend, std::default_delete<seastar::reactor_backend> >::get (this=0x28) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/unique_ptr.h:462
#8  std::unique_ptr<seastar::reactor_backend, std::default_delete<seastar::reactor_backend> >::operator-> (this=0x28) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/unique_ptr.h:455
#9  seastar::reactor::signals::handle_signal(int, seastar::noncopyable_function<void ()>&&)::$_56::operator()(int, siginfo_t*, void*) const (sig=15, info=0x7f54719d2fb0, p=0x7f54719d2e80, this=<optimized out>)
    at ./seastar/src/core/reactor.cc:682
#10 seastar::reactor::signals::handle_signal(int, seastar::noncopyable_function<void ()>&&)::$_56::__invoke(int, siginfo_t*, void*) (sig=15, info=0x7f54719d2fb0, p=0x7f54719d2e80) at ./seastar/src/core/reactor.cc:681
#11 <signal handler called>
#12 0x00007f54750aad14 in __futex_abstimed_wait_common () from /jenkins/workspace/scylla-master/scylla-ci/scylla/.ccm/scylla-repository/13213/libreloc/libc.so.6
#13 0x00007f54750ad510 in pthread_cond_wait@@GLIBC_2.3.2 () from /jenkins/workspace/scylla-master/scylla-ci/scylla/.ccm/scylla-repository/13213/libreloc/libc.so.6
#14 0x00007f54752d5110 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /jenkins/workspace/scylla-master/scylla-ci/scylla/.ccm/scylla-repository/13213/libreloc/libstdc++.so.6
#15 0x0000000003ff0fb8 in std::condition_variable::wait<wasm::task_queue::pop_front()::$_1>(std::unique_lock<std::mutex>&, wasm::task_queue::pop_front()::$_1) (this=0x60000034b338, __lock=..., __p=...)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/condition_variable:102
#16 wasm::task_queue::pop_front (this=0x60000034b310) at lang/wasm_alien_thread_runner.cc:20
#17 wasm::alien_thread_runner::alien_thread_runner()::$_2::operator()() const (this=<optimized out>) at lang/wasm_alien_thread_runner.cc:36
#18 std::__invoke_impl<void, wasm::alien_thread_runner::alien_thread_runner()::$_2>(std::__invoke_other, wasm::alien_thread_runner::alien_thread_runner()::$_2&&) (__f=...)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:61
#19 std::__invoke<wasm::alien_thread_runner::alien_thread_runner()::$_2>(wasm::alien_thread_runner::alien_thread_runner()::$_2&&) (__fn=...) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:96
#20 std::thread::_Invoker<std::tuple<wasm::alien_thread_runner::alien_thread_runner()::$_2> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=<optimized out>)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_thread.h:258
#21 std::thread::_Invoker<std::tuple<wasm::alien_thread_runner::alien_thread_runner()::$_2> >::operator()() (this=<optimized out>) at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_thread.h:265
#22 std::thread::_State_impl<std::thread::_Invoker<std::tuple<wasm::alien_thread_runner::alien_thread_runner()::$_2> > >::_M_run() (this=<optimized out>)
    at /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_thread.h:210
#23 0x00007f54752dbc03 in execute_native_thread_routine () from /jenkins/workspace/scylla-master/scylla-ci/scylla/.ccm/scylla-repository/13213/libreloc/libstdc++.so.6
#24 0x00007f54750ae12d in start_thread () from /jenkins/workspace/scylla-master/scylla-ci/scylla/.ccm/scylla-repository/13213/libreloc/libc.so.6
#25 0x00007f547512fbc0 in clone3 () from /jenkins/workspace/scylla-master/scylla-ci/scylla/.ccm/scylla-repository/13213/libreloc/libc.so.6
```

**Comment by tchaikov** [comment]
weird.. just checked the lifecycle of  `alien_thread_runner`, as the indirect owner of the mutex and the condition_variable, it should outlive them. so it might be that the segfault was sent when we were handling SIGTERM ?

**Comment by wmitros** [comment]
@tchaikov it does look like there was a problem with signal handling, maybe we have to do the same workaround as you had in Ceph: https://github.com/ceph/ceph/blob/736b382767bd7a37f105325a36fe1d9a97809c25/src/crimson/os/alienstore/thread_pool.cc#L55-L66

**Comment by tchaikov** [comment]
yeah, that should be the root cause -- seastar reactor is not around in the alien thread.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
