### ISSUE TITLE
cassandra-stress with -log hdrfile options failed with error java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#13287]
Cloned from scylladb/scylla-tools-java#328

Cassandra stress command with option -log hdrfile=  and ru failed with next error:
./share/cassandra/bin/cassandra-stress write n=40000 -log hdrfile=/home/abykov/tmp/test.hdr interval=1s -node 172.17.0.2

Exception in thread "StressMetrics" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at org.HdrHistogram.HistogramLogWriter.outputIntervalHistogram(HistogramLogWriter.java:135)
	at org.HdrHistogram.HistogramLogWriter.outputIntervalHistogram(HistogramLogWriter.java:154)
	at org.HdrHistogram.HistogramLogWriter.outputIntervalHistogram(HistogramLogWriter.java:175)
	at org.apache.cassandra.stress.report.StressMetrics.logHistogram(StressMetrics.java:336)
	at org.apache.cassandra.stress.report.StressMetrics.logHistograms(StressMetrics.java:320)
	at org.apache.cassandra.stress.report.StressMetrics.recordInterval(StressMetrics.java:253)
	at org.apache.cassandra.stress.report.StressMetrics.reportingLoop(StressMetrics.java:172)
	at org.apache.cassandra.stress.report.StressMetrics.lambda$new$1(StressMetrics.java:124)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 9 more
This happend for java versions: 11, 17, 19.
This option works correctly only with 8

**Comment by avikivity** [comment]
Fixed by 6d5c242651fa51dcee7732dcb9bbbdd9e5e2dd61

**Comment by avikivity** [comment]
Backported to 5.2.
