### ISSUE TITLE
artifacts offline OEL failing with error bash: /usr/bin/cqlsh: Permission denied

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylladb#13416]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

job is failing when trying to run command `cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "desc keyspaces" 10.4.1.173 9042`:

```
2023-04-02 06:09:19.815: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=4f2cbbdc-2a34-4008-99c8-c061f3670730, source=ArtifactsTest.test_scylla_service (artifacts_test.ArtifactsTest) [check cqlsh installation]() message=Traceback (most recent call last):
File "/tmp/jenkins/workspace/scylla-enterprise/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/artifacts_test.py", line 322, in test_scylla_service
self.check_cqlsh()
File "/tmp/jenkins/workspace/scylla-enterprise/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/artifacts_test.py", line 129, in check_cqlsh
output = self.node.run_cqlsh("desc keyspaces")
File "/tmp/jenkins/workspace/scylla-enterprise/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/cluster.py", line 2782, in run_cqlsh
cqlsh_out = self.remoter.run(cmd, timeout=timeout + 30,  # we give 30 seconds to cqlsh timeout mechanism to work
File "/tmp/jenkins/workspace/scylla-enterprise/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/tmp/jenkins/workspace/scylla-enterprise/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
return func(*args, **kwargs)
File "/tmp/jenkins/workspace/scylla-enterprise/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/tmp/jenkins/workspace/scylla-enterprise/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/tmp/jenkins/workspace/scylla-enterprise/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/tmp/jenkins/workspace/scylla-enterprise/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "desc keyspaces" 10.4.1.173 9042'
Exit code: 126
Stdout:
Stderr:
/etc/bashrc: line 99: TMOUT: readonly variable
/etc/bashrc: line 100: TMOUT: readonly variable
bash: /usr/bin/cqlsh: Permission denied
```

## How frequently does it reproduce?

last 5 builds are failing with exactly the same error

## Installation details

Kernel Version: 4.18.0-147.0.3.el8_1.x86_64
Scylla version (or git commit hash): `2023.2.0.dev-20230401.85ad4482e7a` with build-id `9ff3df6b374cac1e602d7639931302ecc571c7dc`

Cluster size: 1 nodes (i3.large)

Scylla Nodes used in this run:
- artifacts-oel81-jenkins-db-node-b6469ab6-1 (3.250.3.206 | 10.4.1.173) (shards: 2)

OS / Image: `ami-0e883e67243efea62` (aws: eu-west-1)

Test: `artifacts-oel81-test`
Test id: `b6469ab6-680c-477e-a86c-3c1db2a72b48`
Test name: `scylla-enterprise/artifacts-offline-install/artifacts-oel81-test`
Test config file(s):

- [oel81.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a317398419d94861af4e5fdf7b945c7655d4cc77/test-cases/artifacts/oel81.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor b6469ab6-680c-477e-a86c-3c1db2a72b48`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b6469ab6-680c-477e-a86c-3c1db2a72b48)
- Show all stored logs command: `$ hydra investigate show-logs b6469ab6-680c-477e-a86c-3c1db2a72b48`

## Logs:
- **db-cluster-b6469ab6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6469ab6-680c-477e-a86c-3c1db2a72b48/20230402_060939/db-cluster-b6469ab6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6469ab6-680c-477e-a86c-3c1db2a72b48/20230402_060939/db-cluster-b6469ab6.tar.gz)
- **sct-runner-events-b6469ab6.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6469ab6-680c-477e-a86c-3c1db2a72b48/20230402_060939/sct-runner-events-b6469ab6.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6469ab6-680c-477e-a86c-3c1db2a72b48/20230402_060939/sct-runner-events-b6469ab6.tar.gz)
- **sct-b6469ab6.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b6469ab6-680c-477e-a86c-3c1db2a72b48/20230402_060939/sct-b6469ab6.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b6469ab6-680c-477e-a86c-3c1db2a72b48/20230402_060939/sct-b6469ab6.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-enterprise/job/artifacts-offline-install/job/artifacts-oel81-test/76/)
</details>

**Comment by fgelcer** [comment]
@yaronkaikov

**Comment by fruch** [comment]
A fix for this was merged last week, we need to check if the last run included the fix or not

**Comment by yaronkaikov** [comment]
@fruch Are you referring to https://github.com/scylladb/scylla-cqlsh/commit/f2cf2c0a6a634990ea678cc28e9f14292d75ff85 ? it's already in

**Comment by fruch** [comment]
> @fruch Are you referring to https://github.com/scylladb/scylla-cqlsh/commit/f2cf2c0a6a634990ea678cc28e9f14292d75ff85 ? it's already in

Yes, I know it's in, question is it in the mentioned run here.

**Comment by yaronkaikov** [comment]
@fruch I missed the fact it's enterprise, so no it only passed yesterday, it doesn't contain this fix. i will re-build it and verify

**Comment by yaronkaikov** [comment]
Just realized it didn't pass next-enterprise. so we will have to wait for it.

**Comment by fruch** [comment]
yeah https://github.com/scylladb/scylladb/commit/c7131a0574 isn't on enterprise yet

**Comment by yaronkaikov** [comment]
@Annamikhlin

**Comment by fruch** [comment]
> @Annamikhlin

I can confirm started passsing

**Comment by yaronkaikov** [comment]
@fruch So  we can close this?

**Comment by fruch** [comment]
yes
https://jenkins.scylladb.com/job/scylla-enterprise/job/artifacts-offline-install/job/artifacts-oel81-test/80/
