### ISSUE TITLE
Scylla crashes when running repair, then causes boot loop with same backtrace.

### ISSUE THREAD

**Issue by joeledstrom** [scylladb/scylladb#13463]
Latest version of scylla docker image 5.1.7

Scenario:
1. New node added to cluster, joined normally, completed streaming and was working normally. nodetool status reported `UN`.  `nodetool cleanup` was run on old nodes. After this node appears to work fine, CL = ALL queries requiring this node worked. 
2. Then when the repair job ran at night on the new node, it causes it to crash. (nodetool repair) with the following error: 
(Note: I just retried/reproduced the whole process from scratch running repair manually, and this is why the date from the repair job is after the bootloop). 
```
scylla-2 scylla INFO  2023-04-09 12:36:36,545 [shard 0] gossip - 60000 ms elapsed, 10.28.3.33 gossip quarantine over
scylla-2 scylla INFO  2023-04-09 12:36:52,660 [shard 0] repair - repair[e6a20185-182e-4da7-a152-34af58c8f150]: Started to repair 3 out of 10 tables in keyspace=monitoring, table=event, table_id=01be0370-4a03-11ec-8d46-6da9d195ec5a, repair_reason=repair
scylla-2 scylla ERROR 2023-04-09 12:38:45,938 [shard 0] mutation_reader - 14merging_readerI22mutation_reader_mergerE [0x60000684ae00]: permit monitoring.event:view_update_generator: was not closed before destruction, at: 0x50d5c6e 0x50d6160 0x50d6468 0x4d1ea53 0x180b680 0x17bf700 0x180b52a 0x2db5a63 0x2db4003 0x4fbaaa1
scylla-2 scylla    --------
scylla-2 scylla    seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::async<db::view::view_update_generator::start()::$_0>(seastar::thread_attributes, db::view::view_update_generator::start()::$_0&&)::{lambda()#2}, seastar::future<void>::then_impl_nrvo<seastar::async<db::view::view_update_generator::start()::$_0>(seastar::thread_attributes, db::view::view_update_generator::start()::$_0&&)::{lambda()#2}, seastar::future<void> >(db::view::view_update_generator::start()::$_0&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::async<db::view::view_update_generator::start()::$_0>(seastar::thread_attributes, auto:1&&)::{lambda()#2}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
scylla-2 scylla    --------
scylla-2 scylla    seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::finally_body<seastar::async<db::view::view_update_generator::start()::$_0>(seastar::thread_attributes, db::view::view_update_generator::start()::$_0&&)::{lambda()#3}, false>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::future<void>::finally_body<seastar::async<db::view::view_update_generator::start()::$_0>(seastar::thread_attributes, db::view::view_update_generator::start()::$_0&&)::{lambda()#3}, false> >(seastar::future<void>::finally_body<seastar::async<db::view::view_update_generator::start()::$_0>(seastar::thread_attributes, db::view::view_update_generator::start()::$_0&&)::{lambda()#3}, false>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::future<void>::finally_body<seastar::async<db::view::view_update_generator::start()::$_0>(seastar::thread_attributes, auto:1&&)::{lambda()#3}, false>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
scylla-2 scylla Aborting on shard 0.
scylla-2 scylla Backtrace:
scylla-2 scylla   0x4d3bea8
scylla-2 scylla   0x4d6b5b2
scylla-2 scylla   0x7f70205cfa1f
scylla-2 scylla   /opt/scylladb/libreloc/libc.so.6+0x3d2a1
scylla-2 scylla   /opt/scylladb/libreloc/libc.so.6+0x268a3
scylla-2 scylla   0x180b697
scylla-2 scylla   0x17bf700
scylla-2 scylla   0x180b52a
scylla-2 scylla   0x2db5a63
scylla-2 scylla   0x2db4003
scylla-2 scylla   0x4fbaaa1
scylla-2 scylla Exception in thread "Storage Service Repair" java.lang.IllegalStateException: Unable to connect to Scylla API server: java.net.ConnectException: Connection refused (Connection refused)
scylla-2 scylla 	at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:196)
scylla-2 scylla 	at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:201)
scylla-2 scylla 	at com.scylladb.jmx.api.APIClient.getStringValue(APIClient.java:213)
scylla-2 scylla 	at org.apache.cassandra.service.StorageService$CheckRepair.run(StorageService.java:755)
scylla-2 scylla 	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
scylla-2 scylla 	at java.base/java.util.TimerThread.run(Timer.java:506)
scylla-2 scylla 2023-04-09 12:38:48,319 INFO exited: scylla (terminated by SIGABRT (core dumped); not expected)
```

3. Now the scylla instance can't be started and core dumps on each time it tries to start with the same error. Just after "initialization completed.". 
```
INFO  2023-04-09 11:45:47,313 [shard 0] init - Scylla version 5.1.7-0.20230312.5c5a9633eab8 initialization completed.
ERROR 2023-04-09 11:45:47,672 [shard 0] mutation_reader - 14merging_readerI22mutation_reader_mergerE [0x600006a47880]: permit monitoring.event:view_update_generator: was not closed before destruction, at: 0x50d5c6e 0x50d6160 0x50d6468 0x4d1ea53 0x180b680 0x17bf700 0x180b52a 0x2db5a63 0x2db4003 0x4fbaaa1
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::async<db::view::view_update_generator::start()::$_0>(seastar::thread_attributes, db::view::view_update_generator::start()::$_0&&)::{lambda()#2}, seastar::future<void>::then_impl_nrvo<seastar::async<db::view::view_update_generator::start()::$_0>(seastar::thread_attributes, db::view::view_update_generator::start()::$_0&&)::{lambda()#2}, seastar::future<void> >(db::view::view_update_generator::start()::$_0&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::async<db::view::view_update_generator::start()::$_0>(seastar::thread_attributes, auto:1&&)::{lambda()#2}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::future<void>::finally_body<seastar::async<db::view::view_update_generator::start()::$_0>(seastar::thread_attributes, db::view::view_update_generator::start()::$_0&&)::{lambda()#3}, false>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::future<void>::finally_body<seastar::async<db::view::view_update_generator::start()::$_0>(seastar::thread_attributes, db::view::view_update_generator::start()::$_0&&)::{lambda()#3}, false> >(seastar::future<void>::finally_body<seastar::async<db::view::view_update_generator::start()::$_0>(seastar::thread_attributes, db::view::view_update_generator::start()::$_0&&)::{lambda()#3}, false>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::future<void>::finally_body<seastar::async<db::view::view_update_generator::start()::$_0>(seastar::thread_attributes, auto:1&&)::{lambda()#3}, false>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
Aborting on shard 0.
Backtrace:
  0x4d3bea8
  0x4d6b5b2
  0x7f026fb2ea1f
  /opt/scylladb/libreloc/libc.so.6+0x3d2a1
  /opt/scylladb/libreloc/libc.so.6+0x268a3
  0x180b697
  0x17bf700
  0x180b52a
  0x2db5a63
  0x2db4003
  0x4fbaaa1
2023-04-09 11:45:48,862 INFO exited: scylla (terminated by SIGABRT (core dumped); not expected)
```

**Comment by nuivall** [comment]
Yes, it's related. May not be direct cause, but that patch should help with recovery.

@joeledstrom please try now with newest scylla version

**Comment by joeledstrom** [comment]
Sorry for late answer. Very unfortunately I don't have the data reproduce this available anymore. I think I wiped the table in question. So I suppose we can close the ticket.
