### ISSUE TITLE
[Ec2Snitch] nodes are shown in nodetool as UNKNOWN_DC / UNKNOWN_RACK 

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#13629]
## Issue description

- [ ] This issue is a regression.
- [x] It is unknown if this issue is a regression.

node-3 and node-4 keep showing node-2 (10.12.8.26) as UNKNOWN_DC and  UNKNOWN_RACK 
```
< t:2023-04-21 03:22:34,000 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Datacenter: UNKNOWN_DC
< t:2023-04-21 03:22:34,000 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > ======================
< t:2023-04-21 03:22:34,001 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Status=Up/Down
< t:2023-04-21 03:22:34,001 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > |/ State=Normal/Leaving/Joining/Moving
< t:2023-04-21 03:22:34,001 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > --  Address       Load       Tokens       Owns    Host ID                               Rack
< t:2023-04-21 03:22:34,025 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.8.26    ?          256          ?       1ab8d138-c314-4c55-9303-1d49ba180805  UNKNOWN_RACK
< t:2023-04-21 03:22:34,025 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Datacenter: us-east
< t:2023-04-21 03:22:34,026 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > ===================
< t:2023-04-21 03:22:34,026 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Status=Up/Down
< t:2023-04-21 03:22:34,026 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > |/ State=Normal/Leaving/Joining/Moving
< t:2023-04-21 03:22:34,026 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > --  Address       Load       Tokens       Owns    Host ID                               Rack
< t:2023-04-21 03:22:34,029 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.10.238  396 KB     256          ?       0d56db08-f96b-4c0f-a769-57926e3c0b83  1c
< t:2023-04-21 03:22:34,031 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.12.11.165  1005 KB    256          ?       db5b4c16-a2fb-43e6-aa59-55e5d07957b4  1c
< t:2023-04-21 03:22:34,031 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >
< t:2023-04-21 03:22:34,031 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
< t:2023-04-21 03:22:34,531 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool -u cassandra -pw 'cassandra'  status " finished with status 0
< t:2023-04-21 03:22:34,531 f:cluster.py      l:2553 c:sdcm.cluster_aws     p:DEBUG > Node longevity-50gb-12h-master-db-node-c9363b01-3 [54.82.36.177 | 10.12.11.165] (seed: False): Command '/usr/bin/nodetool -u cassandra -pw 'cassandra'  status ' duration -> 4.0110915149999755 s
```

while on the gossipinfo calls all the correct dc/rack information is showen:
```
< t:2023-04-21 04:07:18,447 f:cluster.py      l:2553 c:sdcm.cluster_aws     p:DEBUG > Node longevity-50gb-12h-master-db-node-c9363b01-4 [54.227.185.80 | 10.12.11.201] (seed: False): Command '/usr/bin/nodetool -u cassandra -pw 'cassandra'  gossipinfo ' duration -> 1.5833854689999498 s
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG > get_gossip_info: Command exited with status 0.
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG > === stdout ===
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG > /10.12.8.26
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   generation:1682049870
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   heartbeat:237
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   RPC_ADDRESS:10.12.8.26
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   NET_VERSION:0
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   X5:0:18446744073709551615:1682049882584
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   X9:org.apache.cassandra.locator.Ec2Snitch
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   X3:3
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   LOAD:40122746880
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   STATUS:NORMAL,8730276896462402503
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   SCHEMA:80723fec-f84c-3cb5-9f17-8f5f933684ce
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   X2:system_traces.sessions:0.000000;system_distributed_everywhere.cdc_generation_descriptions_v2:0.000000;system_traces.events:0.000000;system_distributed.view_build_status:0.000000;system_distributed.service_levels:1.000000;system_traces.node_slow_log_time_idx:0.000000;audit.audit_log:0.000000;system_distributed.cdc_generation_timestamps:0.000000;system_auth.roles:0.970731;system_traces.node_slow_log:0.000000;keyspace1.standard1:0.000000;system_replicated_keys.encrypted_keys:0.000000;system_distributed.cdc_streams_descriptions_v2:0.000000;system_auth.role_permissions:0.000000;system_traces.sessions_time_idx:0.000000;system_auth.role_attributes:0.000000;system_auth.role_members:0.000000;
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   X6:14
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   HOST_ID:1ab8d138-c314-4c55-9303-1d49ba180805
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   DC:us-east
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   RACK:1c
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   X1:AGGREGATE_STORAGE_OPTIONS,ALTERNATOR_STREAMS,ALTERNATOR_TTL,CDC,CDC_GENERATIONS_V2,COLLECTION_INDEXING,COMPUTED_COLUMNS,CORRECT_COUNTER_ORDER,CORRECT_IDX_TOKEN_IN_SECONDARY_INDEX,CORRECT_NON_COMPOUND_RANGE_TOMBSTONES,CORRECT_STATIC_COMPACT_IN_MC,COUNTERS,DIGEST_FOR_NULL_VALUES,DIGEST_INSENSITIVE_TO_EXPIRY,DIGEST_MULTIPARTITION_READ,EMPTY_REPLICA_PAGES,HINTED_HANDOFF_SEPARATE_CONNECTION,INDEXES,IN_MEMORY_TABLES,KEYSPACE_STORAGE_OPTIONS,LARGE_COLLECTION_DETECTION,LARGE_PARTITIONS,LA_SSTABLE_FORMAT,LWT,MATERIALIZED_VIEWS,MC_SSTABLE_FORMAT,MD_SSTABLE_FORMAT,ME_SSTABLE_FORMAT,NONFROZEN_UDTS,PARALLELIZED_AGGREGATION,PER_TABLE_CACHING,PER_TABLE_PARTITIONERS,RANGE_SCAN_DATA_VARIANT,RANGE_TOMBSTONES,ROLES,ROW_LEVEL_REPAIR,SCHEMA_COMMITLOG,SCHEMA_TABLES_V3,SECONDARY_INDEXES_ON_STATIC_COLUMNS,SEPARATE_PAGE_SIZE_AND_SAFETY_LIMIT,STREAM_WITH_RPC_STREAM,SUPPORTS_RAFT_CLUSTER_MANAGEMENT,TOMBSTONE_GC_OPTIONS,TRUNCATION_TABLE,TYPED_ERRORS_IN_READ_RPC,UDA,UDA_NATIVE_PARALLELIZED_AGGREGATION,UNBOUNDED_RANGE_TOMBSTONES,VIEW_VIRTUAL_COLUMNS,WORKLOAD_PRIORITIZATION,WRITE_FAILURE_REPLY,XXHASH
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   X7:12
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   RELEASE_VERSION:3.0.8
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   X4:1
< t:2023-04-21 04:07:18,448 f:cluster.py      l:2689 c:sdcm.cluster         p:DEBUG >   X8:v2;1682047578135;442bb3b4-276e-43c8-969f-2c6b270bfe4e
```

## Impact

when using the information from nodetool to build `ALTER TABLE` command in `add_remove_dc` nemesis
we end up with a broken command 
```
Command: '/usr/bin/cqlsh --no-color -u cassandra -p \'cassandra\'  --request-timeout=120 --connect-timeout=60 --ssl -e "ALTER KEYSPACE keyspace_new_dc WITH replication = {\'class\': \'NetworkTopologyStrategy\', \'UNKNOWN_DC\': 3, \'us-east_nemesis_dc\': 1}" 10.12.10.238 9042'

Exit code: 2

Stdout:



Stderr:


Warning: Using a password on the command line interface can be insecure.
Recommendation: use the credentials file to securely provide the password.

<stdin>:1:ConfigurationException: Unrecognized strategy option {UNKNOWN_DC} passed to org.apache.cassandra.locator.NetworkTopologyStrategy for keyspace keyspace_new_dc
```

also it breaks c-s data validation, with the following errors: 

```
java.io.IOException: Operation x0 on key(s) [30383839313236334e30]: Data returned was not validated

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:473)
java.io.IOException: Operation x0 on key(s) [5050324e303335373631]: Data returned was not validated

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:473)
total,     350676436,   19490,   19489,   19489,    12.9,     9.2,    34.4,    80.4,   130.5,   195.6,19113.9,  0.00188,      2,      0,       0,       0,       0,       0
WARN  09:22:24,223 Error while computing token map for keyspace keyspace_new_dc with datacenter UNKNOWN_DC: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
WARN  09:27:46,341 Error while computing token map for keyspace keyspace_new_dc with datacenter UNKNOWN_DC: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
WARN  09:27:47,310 Error while computing token map for keyspace keyspace_new_dc with datacenter UNKNOWN_DC: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
WARN  09:29:19,371 Error while computing token map for keyspace keyspace_new_dc with datacenter UNKNOWN_DC: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
WARN  09:29:35,395 Error while computing token map for keyspace keyspace_new_dc with datacenter UNKNOWN_DC: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
WARN  09:29:51,041 Error while computing token map for keyspace keyspace_new_dc with datacenter UNKNOWN_DC: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
WARN  09:30:10,661 Error while computing token map for keyspace keyspace_new_dc with datacenter UNKNOWN_DC: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
WARN  09:30:21,969 Error while computing token map for keyspace keyspace_new_dc with datacenter UNKNOWN_DC: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
WARN  09:30:34,003 Error while computing token map for keyspace keyspace_new_dc with datacenter UNKNOWN_DC: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
FAILURE
java.lang.RuntimeException: Failed to execute stress action
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:101)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
```

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.19.0-1022-aws
Scylla version (or git commit hash): `2023.2.0~dev-20230414.4cead661d807` with build-id `d44896ce09326a60b8268914d8aca80e4bd67ccf`

Cluster size: 4 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-50gb-12h-master-db-node-c9363b01-6 (54.174.101.101 | 10.12.11.63) (shards: 9)
- longevity-50gb-12h-master-db-node-c9363b01-5 (52.206.185.132 | 10.12.11.141) (shards: 9)
- longevity-50gb-12h-master-db-node-c9363b01-4 (54.227.185.80 | 10.12.11.201) (shards: 10)
- longevity-50gb-12h-master-db-node-c9363b01-3 (54.82.36.177 | 10.12.11.165) (shards: 8)
- longevity-50gb-12h-master-db-node-c9363b01-2 (54.242.112.40 | 10.12.8.26) (shards: 14)
- longevity-50gb-12h-master-db-node-c9363b01-1 (54.234.97.163 | 10.12.10.238) (shards: 8)

OS / Image: `ami-0887d031e961ab238` (aws: us-east-1)

Test: `longevity-150gb-asymmetric-cluster-12h-test`
Test id: `c9363b01-a552-437a-957f-aac2cde93b2f`
Test name: `scylla-enterprise/longevity/longevity-150gb-asymmetric-cluster-12h-test`
Test config file(s):

- [longevity-150GB-12h-autorization-LimitedMonkey.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/255c26e2d4bff3c26cf665482de2ed6fb22d794b/test-cases/longevity/longevity-150GB-12h-autorization-LimitedMonkey.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor c9363b01-a552-437a-957f-aac2cde93b2f`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c9363b01-a552-437a-957f-aac2cde93b2f)
- Show all stored logs command: `$ hydra investigate show-logs c9363b01-a552-437a-957f-aac2cde93b2f`

## Logs:
- **db-cluster-c9363b01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c9363b01-a552-437a-957f-aac2cde93b2f/20230421_155533/db-cluster-c9363b01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c9363b01-a552-437a-957f-aac2cde93b2f/20230421_155533/db-cluster-c9363b01.tar.gz)
- **sct-runner-events-c9363b01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c9363b01-a552-437a-957f-aac2cde93b2f/20230421_155533/sct-runner-events-c9363b01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c9363b01-a552-437a-957f-aac2cde93b2f/20230421_155533/sct-runner-events-c9363b01.tar.gz)
- **sct-c9363b01.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c9363b01-a552-437a-957f-aac2cde93b2f/20230421_155533/sct-c9363b01.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c9363b01-a552-437a-957f-aac2cde93b2f/20230421_155533/sct-c9363b01.log.tar.gz)
- **monitor-set-c9363b01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c9363b01-a552-437a-957f-aac2cde93b2f/20230421_155533/monitor-set-c9363b01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c9363b01-a552-437a-957f-aac2cde93b2f/20230421_155533/monitor-set-c9363b01.tar.gz)
- **loader-set-c9363b01.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c9363b01-a552-437a-957f-aac2cde93b2f/20230421_155533/loader-set-c9363b01.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c9363b01-a552-437a-957f-aac2cde93b2f/20230421_155533/loader-set-c9363b01.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-enterprise/job/longevity/job/longevity-150gb-asymmetric-cluster-12h-test/13/)
</details>

**Comment by DoronArazii** [comment]
@yaronkaikov / @syuu1228 please have a look

**Comment by DoronArazii** [comment]
Last seen on April.
Reducing the priority to P3 until it will raise again.

**Comment by yaronkaikov** [comment]
Closing as it's didn't reproduce since
