### ISSUE TITLE
scylla fails to restart in `object_store/run`

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#13644]
```
Scylla is: /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/scylla.
Start scylla (dir=/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-test-42478
Booting Scylla on 127.1.165.240 in /jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-test-42478...
Boot successful (36.3 seconds).
Create keyspace (minio listening at 127.154.195.1)
Restart scylla
Booting Scylla on 127.1.179.181 in /jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-test-42478...
Boot failed after 45.5 seconds.
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/object_store/run", line 67, in <module>
    run.wait_for_services(pid, [ lambda: check_cql(ip) ])
  File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/object_store/../cql-pytest/run.py", line 373, in wait_for_services
    os.waitpid(pid, os.P_NOWAIT)
ChildProcessError: [Errno 10] No child processes
Exception ignored in atexit callback: <function cleanup_all at 0x7f49be19d760>
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/object_store/../cql-pytest/run.py", line 138, in cleanup_all
    f = abort_run_with_temporary_dir(pid)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/object_store/../cql-pytest/run.py", line 119, in abort_run_with_temporary_dir
    return abort_run_with_dir(pid, pid_to_dir(pid))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/object_store/../cql-pytest/run.py", line 110, in abort_run_with_dir
    f = open(os.path.join(tmpdir, 'log'), 'rb')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/jenkins/workspace/scylla-master/scylla-ci/scylla/testlog/x86_64/debug/scylla-test-42480/log'
```

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/830/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___object_store_run_debug_1/

**Comment by tchaikov** [comment]
have spotted this issue for 3 times in last week.
