### ISSUE TITLE
Two shards from 7 were overloaded and ran most of load after kill Scylla daemon

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#13938]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

The problem happened during `disrupt_kill_scylla` nemesis. 
Scylla on the node `longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-11 [3.252.163.225 | 10.4.1.200]` was killed with `pkill -9 scylla`.
```
< t:2023-05-16 02:58:24,534 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2023-05-16 02:58:24.523: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=0d9036e0-0f52-48bf-97a3-7171d55d8f99: nemesis_name=KillScylla target_node=Node longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-11 [3.252.163.225 | 10.4.1.200] (seed: False)
```

After Scylla started up, two shards (4 and 5) from 7 worked with 100% and most of load was run on those shards:
![Screenshot from 2023-05-18 13-42-54](https://github.com/scylladb/scylladb/assets/34435448/908d1492-525e-43e6-92ad-de00893e2fc9)
![Screenshot from 2023-05-18 13-43-48](https://github.com/scylladb/scylladb/assets/34435448/1a45e62d-baf2-4b62-a165-3f28d74a8bae)
![Screenshot from 2023-05-18 13-43-30](https://github.com/scylladb/scylladb/assets/34435448/2d042dac-cec9-42d1-8089-5771f70b76f8)

There are a lot of `reader_concurrency_semaphore`: 
```
May 16 03:01:17 longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-11 scylla[9528]:  [shard 0] reader_concurrency_semaphore - (rate limiting dropped 11039 similar messages) Semaphore sl:default_read_concurrency_
sem with 23/100 count and 2112258/170582343 memory resources: timed out, dumping permit diagnostics:
                                                                                    permits        count        memory        table/description/state
                                                                                    9        9        1414K        cqlstress_lwt_example.blogposts/data-query/active/blocked
                                                                                    2        2        314K        cqlstress_lwt_example.blogposts/data-query/active/used
                                                                                    857        0        0B        cqlstress_lwt_example.blogposts/data-query/waiting
                                                                                    
                                                                                    2036        23        2063K        total
                                                                                    
                                                                                    Total: 2036 permits with 23 count and 2063K memory resources
```

It was impossible to create cql connection with node:
```
< t:2023-05-16 03:03:21,022 f:cluster.py      l:3419 c:cassandra.cluster    p:WARNING > [control connection] Error connecting to 10.4.1.200:9042: < t:2023-05-16 03:03:21,022 f:cluster.py      l:3419 c:cassandra.cluster    p:WARNING > [control connection] Error connecting to 10.4.1.200:9042:
< t:2023-05-16 03:03:21,022 f:cluster.py      l:3419 c:cassandra.cluster    p:WARNING > Traceback (most recent call last):
< t:2023-05-16 03:03:21,022 f:cluster.py      l:3419 c:cassandra.cluster    p:WARNING >   File "cassandra/cluster.py", line 3606, in cassandra.cluster.ControlConnection._reconnect_internal
< t:2023-05-16 03:03:21,022 f:cluster.py      l:3419 c:cassandra.cluster    p:WARNING >   File "cassandra/cluster.py", line 3683, in cassandra.cluster.ControlConnection._try_connect
< t:2023-05-16 03:03:21,022 f:cluster.py      l:3419 c:cassandra.cluster    p:WARNING >   File "cassandra/cluster.py", line 3664, in cassandra.cluster.ControlConnection._try_connect
< t:2023-05-16 03:03:21,022 f:cluster.py      l:3419 c:cassandra.cluster    p:WARNING >   File "cassandra/connection.py", line 1129, in cassandra.connection.Connection.wait_for_responses
< t:2023-05-16 03:03:21,022 f:cluster.py      l:3419 c:cassandra.cluster    p:WARNING >   File "cassandra/connection.py", line 1127, in cassandra.connection.Connection.wait_for_responses
< t:2023-05-16 03:03:21,022 f:cluster.py      l:3419 c:cassandra.cluster    p:WARNING >   File "cassandra/connection.py", line 1640, in cassandra.connection.ResponseWaiter.deliver
< t:2023-05-16 03:03:21,022 f:cluster.py      l:3419 c:cassandra.cluster    p:WARNING > cassandra.OperationTimedOut: errors=None, last_host=None
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1035-aws
Scylla version (or git commit hash): `2023.1.0~rc5-20230429.a47bcb26e42e` with build-id `d2644a8364f13d14d25be6b9d3c69f84612192bd`

Cluster size: 4 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-9 (3.250.109.85 | 10.4.1.49) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-8 (18.203.223.110 | 10.4.2.52) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-7 (34.244.199.69 | 10.4.2.204) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-6 (54.154.54.73 | 10.4.2.180) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-5 (34.255.6.153 | 10.4.1.2) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-4 (34.249.51.228 | 10.4.2.134) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-3 (18.202.235.51 | 10.4.2.207) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-2 (3.252.206.24 | 10.4.1.104) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-16 (52.48.130.233 | 10.4.2.21) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-15 (34.253.181.49 | 10.4.2.70) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-14 (34.241.112.227 | 10.4.0.168) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-13 (63.32.46.61 | 10.4.0.247) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-12 (3.250.11.52 | 10.4.3.162) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-11 (3.252.163.225 | 10.4.1.200) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-10 (3.250.50.18 | 10.4.0.86) (shards: 7)
- longevity-lwt-parallel-24h-2023-1-db-node-f7a072d4-1 (52.212.121.45 | 10.4.0.88) (shards: 7)

OS / Image: `ami-05e7801837cea47d9` (aws: eu-west-1)

Test: `longevity-lwt-parallel-schema-changes-with-disruptive-24h-test`
Test id: `f7a072d4-311b-4f08-ac18-97c9a39b8378`
Test name: `enterprise-2023.1/longevity/longevity-lwt-parallel-schema-changes-with-disruptive-24h-test`
Test config file(s):

- [longevity-lwt-parallel-24h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/1dafb96f428e2691c12e03508dc5024d85552043/test-cases/longevity/longevity-lwt-parallel-24h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor f7a072d4-311b-4f08-ac18-97c9a39b8378`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f7a072d4-311b-4f08-ac18-97c9a39b8378)
- Show all stored logs command: `$ hydra investigate show-logs f7a072d4-311b-4f08-ac18-97c9a39b8378`

## Logs:
- **db-cluster-f7a072d4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/db-cluster-f7a072d4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/db-cluster-f7a072d4.tar.gz)
- **sct-runner-events-f7a072d4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/sct-runner-events-f7a072d4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/sct-runner-events-f7a072d4.tar.gz)
- **sct-f7a072d4.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/sct-f7a072d4.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/sct-f7a072d4.log.tar.gz)
- **monitor-set-f7a072d4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/monitor-set-f7a072d4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/monitor-set-f7a072d4.tar.gz)
- **loader-set-f7a072d4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/loader-set-f7a072d4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f7a072d4-311b-4f08-ac18-97c9a39b8378/20230516_154750/loader-set-f7a072d4.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/longevity/job/longevity-lwt-parallel-schema-changes-with-disruptive-24h-test/4/)
</details>

**Comment by DoronArazii** [comment]
@denesb can you please help with some first assessment?

**Comment by denesb** [comment]
> @denesb can you please help with some first assessment?

I will, but I might only get around to it next week or after.

**Comment by denesb** [comment]
From first look I think this is possibly a duplicate of https://github.com/scylladb/scylladb/issues/13938.

**Comment by juliayakovlev** [comment]
> From first look I think this is possibly a duplicate of #13938.

@denesb #13938 - it is this, current, issue.
