### ISSUE TITLE
Don't allow inserting `time` values larger than 24 hours

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylladb#14667]
The `time` CQL type represents a duration of less than 24 hours, represented as `int64_t nanoseconds`:

https://github.com/apache/cassandra/blob/f5df4b219e063cb24b9cc0c22b6e614506b8d903/doc/native_protocol_v4.spec#L941
```
6.16 time

  An 8 byte two's complement long representing nanoseconds since midnight.
  Valid values are in the range 0 to 86399999999999
```

Scylla correctly rejects `time` values >= 24 hours, when written as text:
```cql
cqlsh:tks> CREATE TABLE t (p int PRIMARY KEY, t time);
cqlsh:tks> INSERT INTO t (p, t) VALUES (0, '23:59:59');
cqlsh:tks> INSERT INTO t (p, t) VALUES (0, '24:00:00');
InvalidRequest: Error from server: code=2200 [Invalid query] message="marshaling error: Hour out of bounds (24)."
cqlsh:tks> 
```

But there's no corresponding validation when it's sent as a bound value:
```rust
session
    .query("CREATE TABLE IF NOT EXISTS tab (p int, t time, primary key (p))", ())
    .await
    .unwrap();

let time: i64 = 86400000000001;
session.query("INSERT INTO tab (p, t) VALUES (0, ?)", (time,)).await.unwrap();
// No error!
```

`cqlsh` rejects invalid time values, so trying to select the row throws an error:
```cql
cqlsh:tks> select * from tab;
Traceback (most recent call last):
  File "cassandra/obj_parser.pyx", line 72, in cassandra.obj_parser.TupleRowParser.unpack_row
  File "cassandra/deserializers.pxd", line 41, in cassandra.deserializers.from_binary
  File "cassandra/deserializers.pyx", line 173, in cassandra.deserializers.DesTimeType.deserialize
  File "cassandra/util.py", line 955, in cassandra.util.Time.__init__
  File "cassandra/util.py", line 1002, in cassandra.util.Time._from_timestamp
ValueError: value must be less than number of nanoseconds in a day (86400000000000)
```

Refs: https://github.com/scylladb/scylladb/issues/14645

**Comment by cvybhu** [comment]
I tried to write a Python reproducer as well, but I can't get it to work.

```python
import cassandra
from cassandra.cluster import Cluster
from cassandra.util import Time;

cluster = Cluster(["127.0.0.1"])
session = cluster.connect()

time_val = Time(12345)

session.execute("DROP KEYSPACE IF EXISTS ks")
session.execute("CREATE KEYSPACE IF NOT EXISTS ks WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor' : 1}")
session.execute("USE ks")
session.execute("CREATE TABLE t (p int PRIMARY KEY, t time)")
session.execute("INSERT INTO t (p, t) VALUES (0, ?)", [time_val])
```

```
Traceback (most recent call last):
  File "/home/jancio/code/python_test/test.py", line 15, in <module>
    session.execute("INSERT INTO t (p, t) VALUES (0, ?)", [time_val])
  File "cassandra/cluster.py", line 2700, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 2743, in cassandra.cluster.Session.execute_async
  File "cassandra/cluster.py", line 3002, in cassandra.cluster.Session._create_response_future
  File "cassandra/query.py", line 896, in cassandra.query.bind_params
TypeError: not all arguments converted during string formatting
```
The docs say that this should work:
>  For prepared statements, the driver accepts anything that can be used to construct the util.Date or util.Time classes. See the linked API docs for details.
https://docs.datastax.com/en/developer/python-driver/3.24/dates_and_times/

Eh I will need to debug

**Comment by cvybhu** [comment]
This would be a breaking change, so we might need to add a feature flag

**Comment by nyh** [comment]
@cvybhu I guess you mean you want to add a configuration option, not a "feature" flag (that the whole cluster picks as soon as the whole cluster supports)? Sad.

**Comment by cvybhu** [comment]
Interestingly the same happens on Cassandra 4.1.1, it doesn't reject invalid values.
So fixing this would also mean breaking compatibility with Cassandra :/

**Comment by cvybhu** [comment]
> @cvybhu I guess you mean you want to add a configuration option, not a "feature" flag (that the whole cluster picks as soon as the whole cluster supports)? Sad.

Something like `strict_allow_filtering`, `strict_is_not_null_in_views`, ...

**Comment by nyh** [comment]
@cvybhu see example in test/cql-pytest/test_type_time.py, test_type_time_from_string_prepared. Maybe this test is misnamed, but the point is that the Python driver expects the prepared statement to be a Time() structure, not a string.

**Comment by nyh** [comment]
By the way, why does this Refs: https://github.com/scylladb/scylladb/issues/14645 and not fixes?

**Comment by nyh** [comment]
> @cvybhu see example in test/cql-pytest/test_type_time.py, test_type_time_from_string_prepared. Maybe this test is misnamed, but the point is that the Python driver expects the prepared statement to be a Time() structure, not a string.

Oops, I was wrong. Strings do work. The Time() is something else :-( Please look at the example in that test - they should work.

**Comment by cvybhu** [comment]
Okay I got it.

This works:
```python3
prep = session.prepare("INSERT INTO t (p, t) VALUES (0, ?)")
session.execute(prep, [time_val])
```

This doesn't:
```
session.execute("INSERT INTO t (p, t) VALUES (0, ?)", [time_val])
```

-.-

**Comment by nyh** [comment]
> @cvybhu see example in test/cql-pytest/test_type_time.py, test_type_time_from_string_prepared. Maybe this test is misnamed, but the point is that the Python driver expects the prepared statement to be a Time() structure, not a string.

Personally I don't think we need to support old buggy behavior that only partially worked (in this case, you can insert this value but only with a prepared statement, and if you do it, you can't read the value back). But maybe @avikivity will disagree.

**Comment by cvybhu** [comment]
> By the way, why does this Refs: https://github.com/scylladb/scylladb/issues/14645 and not fixes?

#14645 is about Gemini, and I'm not sure if it's enough to fix Scylla to fix that issue. For some reason Gemini inserted an invalid value. Is this supposed to happen?

**Comment by nyh** [comment]
> Okay I got it.
> 
> This works:
> 
> ```python
> prep = session.prepare("INSERT INTO t (p, t) VALUES (0, ?)")
> session.execute(prep, [time_val])
> ```
> 
> This doesn't:
> 
> ```
> session.execute("INSERT INTO t (p, t) VALUES (0, ?)", [time_val])
> ```
> 
> -.-

Of course, the latter syntax is simply wrong - there is no such shortcut for "preparing and then executing". BTW, I added this shortcut in test/cql-pytest/cassandra_tests, but not in the toplevel test/cql-pytest. The more "convenience" shortcuts we add for testing, the harder it becomes to understand what the test is actually do.

**Comment by nyh** [comment]
> For some reason Gemini inserted an invalid value. Is this supposed to happen?

To be honest, we need to understand if this is really an "invalid" value. The Cassandra documentation says "Values of the time type are encoded as 64-bit signed integers representing the number of nanoseconds since midnight." - I don't see anybody saying it can't be more than 24 hours, and by the way note (we should test that!) that it explicitly says that the number can even be negative.

Please create tests for this (time > 24hour prepared and unprepared, time <0 prepared and unprepared - check both write and then read on these case), and run them on Scylla and Cassandra and see what happens and then we can decide what is the "correct" behavior, and make it consistent and documented.

You can look at the Gemini source code to see how random "time" values are calculated. Maybe nobody bothered to limit the random time to 24 hours. Maybe nobody thought it was important to limit it?

**Comment by cvybhu** [comment]
The CQL serialization format explicitly limits `time` values to 24 hours
https://github.com/apache/cassandra/blob/f5df4b219e063cb24b9cc0c22b6e614506b8d903/doc/native_protocol_v4.spec#L941

```
6.16 time

  An 8 byte two's complement long representing nanoseconds since midnight.
  Valid values are in the range 0 to 86399999999999
```

**Comment by nyh** [comment]
If we'll want to outlaw times more than 24 hours, we need this sort of text to appear also in the user-facing documentation (like https://cassandra.apache.org/doc/latest/cassandra/cql/types.html#times or wherever Scylla's version of this lives). Currently it doesn't.

**Comment by nyh** [comment]
@cvybhu after thinking about this some more, I  agree with you that we should implement, and document, this `0<=t<24h` limit. If I understand correctly (we should have a test), both Scylla and Cassandra already enforce this limit for non-prepared statement, and as #14645 showed, cqlsh (and perhaps even the Python driver itself?) cannot even read back the data if we manage to write it.

In my opinion, because this behavior was always half-broken and only partially worked, we can reject it without a new `strict_*` configuration option. But let's also get the opinions of @tzach or @avikivity.
