### ISSUE TITLE
test_delete_tombstone_gc_node_down: repair fails when remote node times out flushing hints

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#14712]
Seen in https://jenkins.scylladb.com/job/scylla-5.3/job/gating-dtest-release/156/testReport/junit/compaction_test/TestCompaction/FullDtest___full_split002___test_delete_tombstone_gc_node_down_LeveledCompactionStrategy_/
```
self = <compaction_test.TestCompaction object at 0x7fae3f0a0890>

    @pytest.mark.next_gating
    def test_delete_tombstone_gc_node_down(self):
        """
        Test compaction drop tombstones correctly in 'repair' tombstone_gc_mode mode
        And a node that is temporarily down.
        1. Create 4 nodes cluster + RF = 3.
        2. Write some keys.
        3. Stop node4
        4. Delete data on other nodes and flush.
        5. Run a repair on node1 where some repaired rows succeed (the repair eventually fails).
        6. Run major compaction as well.
        7. Verify node1 now has same tombstones as before the repair.
        8. Start node4.
        9. Count node4 tombstones and verify no tombstones after repairing the nodes + compact.
        """
        partition_num = 10
        self._test_compaction_delete_tombstone_gc('repair', node_num=4, r_factor=3, delete_keys=False,
                                                  partition_num=partition_num)
        node1, node2, node3, node4 = self.cluster.nodelist()
    
        logger.debug("Stopping node4")
        node4.stop(wait_other_notice=True, gently=False)
    
        self._delete_keys(verify_deleted=False, num=partition_num // 2)
        node1.flush()
        node2.flush()
        node3.flush()
    
        with self.patient_exclusive_cql_connection(node1) as session:
            total_tombstones_num_before_repair = 0
            for node in [node1, node2, node3]:
                numfound, _ = self.count_deleted(session=session, node=node)
                total_tombstones_num_before_repair += numfound
            logger.debug("Run a partially-failing repair on node1")
            with pytest.raises(NodetoolError):
                node1.repair(['ks cf'])
    
            logger.debug(
                f"Check, when node4 is down, the number of tombstones on nodes 1,2,3 is unchanged following a repair")
            total_tombstones_num_after_repair = 0
            for node in [node1, node2, node3]:
                numfound, _ = self.count_deleted(session=session, node=node)
                total_tombstones_num_after_repair += numfound
            assert total_tombstones_num_after_repair == total_tombstones_num_before_repair
    
        logger.debug("Starting node4")
        node4.start(wait_other_notice=True, wait_for_binary_proto=True)
    
        with self.patient_cql_connection(node4, consistency_level=ConsistencyLevel.QUORUM) as session:
            logger.debug("Running a repair on all nodes")
            log_mark = node4.mark_log()
            ks, cf = self.FULL_TABLE_NAME.split('.')
>           parallel_nodetool([node1, node2, node3, node4], f'repair -pr {ks} {cf}')

compaction_test.py:384: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tools/cluster.py:99: in parallel_nodetool
    results[nodes[i].name] = threads[i].result(timeout=timeout)
/usr/lib64/python3.11/concurrent/futures/_base.py:456: in result
    return self.__get_result()
/usr/lib64/python3.11/concurrent/futures/_base.py:401: in __get_result
    raise self._exception
/usr/lib64/python3.11/concurrent/futures/thread.py:58: in run
    result = self.fn(*self.args, **self.kwargs)
../scylla/.local/lib/python3.11/site-packages/ccmlib/scylla_node.py:746: in nodetool
    return super().nodetool(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ccmlib.scylla_node.ScyllaNode object at 0x7fae3e6992d0>
cmd = 'repair -pr ks cf', capture_output = True, wait = True, timeout = None
verbose = True

    def nodetool(self, cmd, capture_output=True, wait=True, timeout=None, verbose=True):
        """
        Setting wait=False makes it impossible to detect errors,
        if capture_output is also False. wait=False allows us to return
        while nodetool is still running.
        When wait=True, timeout may be set to a number, in seconds,
        to limit how long the function will wait for nodetool to complete.
        """
        if capture_output and not wait:
            raise common.ArgumentError("Cannot set capture_output while wait is False.")
        env = self.get_env()
        if self.is_scylla() and not self.is_docker():
            host = self.address()
        else:
            host = 'localhost'
        nodetool = self.get_tool('nodetool')
    
        if not isinstance(nodetool, list):
            nodetool = [nodetool]
        # see https://www.oracle.com/java/technologies/javase/8u331-relnotes.html#JDK-8278972
        nodetool.extend(['-h', host, '-p', str(self.jmx_port), '-Dcom.sun.jndi.rmiURLParsing=legacy'])
        nodetool.extend(cmd.split())
        if verbose:
            self.debug(f"nodetool cmd={cmd} wait={wait} timeout={timeout}")
        if capture_output:
            p = subprocess.Popen(nodetool, universal_newlines=True, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            stdout, stderr = p.communicate(timeout=timeout)
        else:
            p = subprocess.Popen(nodetool, env=env, universal_newlines=True)
            stdout, stderr = None, None
    
        if wait:
            exit_status = p.wait(timeout=timeout)
            if exit_status != 0:
>               raise NodetoolError(" ".join(nodetool), exit_status, stdout, stderr)
E               ccmlib.node.ToolError: Subprocess /jenkins/workspace/scylla-5.3/gating-dtest-release/scylla/.ccm/scylla-repository/bff9b459ef8956b74068f38c064c2b35d2fa9ed2/share/cassandra/bin/nodetool -h 127.0.29.1 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy repair -pr ks cf exited with non-zero status; exit status: 2; 
E               stdout: [2023-07-14 16:32:58,594] Starting repair command #2, repairing 1 ranges for keyspace ks (parallelism=SEQUENTIAL, full=true)
E               [2023-07-14 16:32:59,692] Repair session 2 failed
E               [2023-07-14 16:32:59,692] Repair session 2 finished
E               ; 
E               stderr: error: Repair job has failed with the error message: [2023-07-14 16:32:59,692] Repair session 2 failed
E               -- StackTrace --
E               java.lang.RuntimeException: Repair job has failed with the error message: [2023-07-14 16:32:59,692] Repair session 2 failed
E               	at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
E               	at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
E               	at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:633)
E               	at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:555)
E               	at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:474)
E               	at java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor.lambda$execute$0(ClientNotifForwarder.java:108)
E               	at java.base/java.lang.Thread.run(Thread.java:829)

../scylla/.local/lib/python3.11/site-packages/ccmlib/node.py:802: ToolError
```

https://jenkins.scylladb.com/job/scylla-5.3/job/gating-dtest-release/156/artifact/logs-full.release.002/1689352383498_compaction_test.py%3A%3ATestCompaction%3A%3Atest_delete_tombstone_gc_node_down%5BLeveledCompactionStrategy%5D/node1.log
```
INFO  2023-07-14 16:32:43,431 [shard 1] repair - repair[2ba465fa-7c1d-4053-a159-7728963bdd6d]: stats: repair_reason=repair, keyspace=ks, tables={cf}, ranges_nr=799, round_nr=805, round_nr_fast_path_already_synced=805, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=5359, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.28624406 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.0.29.1, 664}, {127.0.29.2, 612}, {127.0.29.3, 472}}, row_from_disk_nr={{127.0.29.1, 6}, {127.0.29.2, 5}, {127.0.29.3, 4}}, row_from_disk_bytes_per_sec={{127.0.29.1, 0.00221224}, {127.0.29.2, 0.00203899}, {127.0.29.3, 0.00157255}} MiB/s, row_from_disk_rows_per_sec={{127.0.29.1, 20.9611}, {127.0.29.2, 17.4676}, {127.0.29.3, 13.9741}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
WARN  2023-07-14 16:32:43,432 [shard 1] repair - repair[2ba465fa-7c1d-4053-a159-7728963bdd6d]: failed - 528 out of 799 ranges failed
INFO  2023-07-14 16:32:43,432 [shard 0] repair - repair[2ba465fa-7c1d-4053-a159-7728963bdd6d]: Started to shutdown off-strategy compaction updater
INFO  2023-07-14 16:32:43,432 [shard 0] repair - repair[2ba465fa-7c1d-4053-a159-7728963bdd6d]: Finished to shutdown off-strategy compaction updater
WARN  2023-07-14 16:32:43,432 [shard 0] repair - repair[2ba465fa-7c1d-4053-a159-7728963bdd6d]: repair_tracker run failed: std::runtime_error ({shard 0: std::runtime_error (repair[2ba465fa-7c1d-4053-a159-7728963bdd6d] on failed to repair 528 out of 799 ranges), shard 1: std::runtime_error (repair[2ba465fa-7c1d-4053-a159-7728963bdd6d] on failed to repair 528 out of 799 ranges)})
```

https://jenkins.scylladb.com/job/scylla-5.3/job/gating-dtest-release/156/artifact/logs-full.release.002/1689352383498_compaction_test.py%3A%3ATestCompaction%3A%3Atest_delete_tombstone_gc_node_down%5BLeveledCompactionStrategy%5D/node2.log
```
INFO  2023-07-14 16:27:43,145 [shard 0] repair - repair[2ba465fa-7c1d-4053-a159-7728963bdd6d]: Started to process repair_flush_hints_batchlog_request from node=127.0.29.1, target_nodes={127.0.29.4, 127.0.29.2, 127.0.29.3, 127.0.29.1}, hints_timeout=300s, batchlog_timeout=300s
INFO  2023-07-14 16:27:43,145 [shard 0] repair - repair[2ba465fa-7c1d-4053-a159-7728963bdd6d]: Started to flush hints for repair_flush_hints_batchlog_request from node=127.0.29.1, target_nodes={127.0.29.4, 127.0.29.2, 127.0.29.3, 127.0.29.1}
INFO  2023-07-14 16:27:43,145 [shard 0] repair - repair[2ba465fa-7c1d-4053-a159-7728963bdd6d]: Started to flush batchlog for repair_flush_hints_batchlog_request from node=127.0.29.1, target_nodes={127.0.29.4, 127.0.29.2, 127.0.29.3, 127.0.29.1}
INFO  2023-07-14 16:27:43,145 [shard 0] repair - repair[2ba465fa-7c1d-4053-a159-7728963bdd6d]: Finished to flush batchlog for repair_flush_hints_batchlog_request from node=127.0.29.1, target_nodes={127.0.29.4, 127.0.29.2, 127.0.29.3, 127.0.29.1}
WARN  2023-07-14 16:32:43,145 [shard 0] repair - repair[2ba465fa-7c1d-4053-a159-7728963bdd6d]: Failed to process repair_flush_hints_batchlog_request from node=127.0.29.1, target_hosts={127.0.29.4, 127.0.29.2, 127.0.29.3, 127.0.29.1}, seastar::timed_out_error (timedout)
```

**Comment by bhalevy** [comment]
It bothers me that other than the timeout we have no information about the hint flushing process.
We don't know if it deadlocked or maybe there are just too many hints and it's taking too long.
`hints_timeout=300` is printed to the log. Is it constant?  Is it sufficient under any circumstances?

**Comment by mykaul** [comment]
Dup of https://github.com/scylladb/scylladb/issues/10265 ?

**Comment by bhalevy** [comment]
> Dup of [#10265](https://github.com/scylladb/scylladb/issues/10265) ?

@piodul? ☝
