### ISSUE TITLE
stack-use-after-return in table::make_reader_v2_excluding_staging()

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#14812]
Caught by new test 

```
build/debug/test/boost/sstable_compaction_test_g -t test_sstables_excluding_staging_correctness  -- --smp 1 -m 1G

=================================================================
==144577==ERROR: AddressSanitizer: stack-use-after-return on address 0x7fffe86715e0 at pc 0x000018f61d1d bp 0x7fffea2cff60 sp 0x7fffea2cff58
READ of size 8 at 0x7fffe86715e0 thread T1
[Detaching after fork from child process 144582]
    #0 0x18f61d1c in seastar::noncopyable_function<bool (sstables::sstable const&)>::operator()(sstables::sstable const&) const ./seastar/include/seastar/util/noncopyable_function.hh:215:16
    #1 0x18edf1ec in sstables::sstable_set::make_local_shard_sstable_reader(seastar::lw_shared_ptr<schema const>, reader_permit, nonwrapping_interval<dht::ring_position> const&, query::partition_slice const&, tracing::trace_state_ptr, seastar::bool_class<streamed_mutation::forwarding_tag>, seastar::bool_class<mutation_reader::partition_range_forwarding_tag>, sstables::read_monitor_generator&, seastar::noncopyable_function<bool (sstables::sstable const&)> const&) const::$_29::operator()(seastar::lw_shared_ptr<sstables::sstable>&, nonwrapping_interval<dht::ring_position> const&) sstables/sstable_set.cc:1327:14
    #2 0x18f206d4 in flat_mutation_reader_v2 std::__invoke_impl<flat_mutation_reader_v2, sstables::sstable_set::make_local_shard_sstable_reader(seastar::lw_shared_ptr<schema const>, reader_permit, nonwrapping_interval<dht::ring_position> const&, query::partition_slice const&, tracing::trace_state_ptr, seastar::bool_class<streamed_mutation::forwarding_tag>, seastar::bool_class<mutation_reader::partition_range_forwarding_tag>, sstables::read_monitor_generator&, seastar::noncopyable_function<bool (sstables::sstable const&)> const&) const::$_29&, seastar::lw_shared_ptr<sstables::sstable>&, nonwrapping_interval<dht::ring_position> const&>(std::__invoke_other, sstables::sstable_set::make_local_shard_sstable_reader(seastar::lw_shared_ptr<schema const>, reader_permit, nonwrapping_interval<dht::ring_position> const&, query::partition_slice const&, tracing::trace_state_ptr, seastar::bool_class<streamed_mutation::forwarding_tag>, seastar::bool_class<mutation_reader::partition_range_forwarding_tag>, sstables::read_monitor_generator&, seastar::noncopyable_function<bool (sstables::sstable const&)> const&) const::$_29&, seastar::lw_shared_ptr<sstables::sstable>&, nonwrapping_interval<dht::ring_position> const&) /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:61:14
    #3 0x18f20534 in std::enable_if<is_invocable_r_v<flat_mutation_reader_v2, sstables::sstable_set::make_local_shard_sstable_reader(seastar::lw_shared_ptr<schema const>, reader_permit, nonwrapping_interval<dht::ring_position> const&, query::partition_slice const&, tracing::trace_state_ptr, seastar::bool_class<streamed_mutation::forwarding_tag>, seastar::bool_class<mutation_reader::partition_range_forwarding_tag>, sstables::read_monitor_generator&, seastar::noncopyable_function<bool (sstables::sstable const&)> const&) const::$_29&, seastar::lw_shared_ptr<sstables::sstable>&, nonwrapping_interval<dht::ring_position> const&>, flat_mutation_reader_v2>::type std::__invoke_r<flat_mutation_reader_v2, sstables::sstable_set::make_local_shard_sstable_reader(seastar::lw_shared_ptr<schema const>, reader_permit, nonwrapping_interval<dht::ring_position> const&, query::partition_slice const&, tracing::trace_state_ptr, seastar::bool_class<streamed_mutation::forwarding_tag>, seastar::bool_class<mutation_reader::partition_range_forwarding_tag>, sstables::read_monitor_generator&, seastar::noncopyable_function<bool (sstables::sstable const&)> const&) const::$_29&, seastar::lw_shared_ptr<sstables::sstable>&, nonwrapping_interval<dht::ring_position> const&>(sstables::sstable_set::make_local_shard_sstable_reader(seastar::lw_shared_ptr<schema const>, reader_permit, nonwrapping_interval<dht::ring_position> const&, query::partition_slice const&, tracing::trace_state_ptr, seastar::bool_class<streamed_mutation::forwarding_tag>, seastar::bool_class<mutation_reader::partition_range_forwarding_tag>, sstables::read_monitor_generator&, seastar::noncopyable_function<bool (sstables::sstable const&)> const&) const::$_29&, seastar::lw_shared_ptr<sstables::sstable>&, nonwrapping_interval<dht::ring_position> const&) /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:114:9
    #4 0x18f1fd13 in std::_Function_handler<flat_mutation_reader_v2 (seastar::lw_shared_ptr<sstables::sstable>&, nonwrapping_interval<dht::ring_position> const&), sstables::sstable_set::make_local_shard_sstable_reader(seastar::lw_shared_ptr<schema const>, reader_permit, nonwrapping_interval<dht::ring_position> const&, query::partition_slice const&, tracing::trace_state_ptr, seastar::bool_class<streamed_mutation::forwarding_tag>, seastar::bool_class<mutation_reader::partition_range_forwarding_tag>, sstables::read_monitor_generator&, seastar::noncopyable_function<bool (sstables::sstable const&)> const&) const::$_29>::_M_invoke(std::_Any_data const&, seastar::lw_shared_ptr<sstables::sstable>&, nonwrapping_interval<dht::ring_position> const&) /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_function.h:290:9
    #5 0x190174bb in std::function<flat_mutation_reader_v2 (seastar::lw_shared_ptr<sstables::sstable>&, nonwrapping_interval<dht::ring_position> const&)>::operator()(seastar::lw_shared_ptr<sstables::sstable>&, nonwrapping_interval<dht::ring_position> const&) const /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_function.h:591:9
    #6 0x19016bb7 in sstables::incremental_reader_selector::create_reader(seastar::lw_shared_ptr<sstables::sstable>) sstables/sstable_set.cc:749:16
    #7 0x19016197 in auto sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&)::'lambda0'(auto&)::operator()<seastar::lw_shared_ptr<sstables::sstable> const>(auto&) const sstables/sstable_set.cc:791:86
    #8 0x19015e54 in flat_mutation_reader_v2 boost::range_detail::default_constructible_unary_fn_wrapper<sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&)::'lambda0'(auto&), flat_mutation_reader_v2>::operator()<seastar::lw_shared_ptr<sstables::sstable>>(auto const&) const /usr/include/boost/range/detail/default_constructible_unary_fn.hpp:56:16
    #9 0x19015c60 in boost::iterators::transform_iterator<boost::range_detail::default_constructible_unary_fn_wrapper<sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&)::'lambda0'(auto&), flat_mutation_reader_v2>, boost::iterators::filter_iterator<boost::range_detail::default_constructible_unary_fn_wrapper<sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&)::'lambda'(auto&), bool>, __gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable> const*, std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable>>>>>, boost::use_default, boost::use_default>::dereference() const /usr/include/boost/iterator/transform_iterator.hpp:126:14
    #10 0x19015a48 in auto::reference boost::iterators::iterator_core_access::dereference<boost::iterators::transform_iterator<boost::range_detail::default_constructible_unary_fn_wrapper<sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&)::'lambda0'(auto&), flat_mutation_reader_v2>, boost::iterators::filter_iterator<boost::range_detail::default_constructible_unary_fn_wrapper<sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&)::'lambda'(auto&), bool>, __gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable> const*, std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable>>>>>, boost::use_default, boost::use_default>>(auto const&) /usr/include/boost/iterator/iterator_facade.hpp:550:20
    #11 0x190151ab in boost::iterators::detail::iterator_facade_base<boost::iterators::transform_iterator<boost::range_detail::default_constructible_unary_fn_wrapper<sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&)::'lambda0'(auto&), flat_mutation_reader_v2>, boost::iterators::filter_iterator<boost::range_detail::default_constructible_unary_fn_wrapper<sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&)::'lambda'(auto&), bool>, __gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable> const*, std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable>>>>>, boost::use_default, boost::use_default>, flat_mutation_reader_v2, boost::iterators::bidirectional_traversal_tag, flat_mutation_reader_v2, long, false, false>::operator*() const /usr/include/boost/iterator/iterator_facade.hpp:656:20
    #12 0x19014cc2 in void std::vector<flat_mutation_reader_v2, std::allocator<flat_mutation_reader_v2>>::_M_range_initialize<boost::iterators::transform_iterator<boost::range_detail::default_constructible_unary_fn_wrapper<sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&)::'lambda0'(auto&), flat_mutation_reader_v2>, boost::iterators::filter_iterator<boost::range_detail::default_constructible_unary_fn_wrapper<sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&)::'lambda'(auto&), bool>, __gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable> const*, std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable>>>>>, boost::use_default, boost::use_default>>(auto, auto, std::input_iterator_tag) /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/stl_vector.h:1668:21
    #13 0x19012ba4 in std::vector<flat_mutation_reader_v2, std::allocator<flat_mutation_reader_v2>>::vector<boost::iterators::transform_iterator<boost::range_detail::default_constructible_unary_fn_wrapper<sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&)::'lambda0'(auto&), flat_mutation_reader_v2>, boost::iterators::filter_iterator<boost::range_detail::default_constructible_unary_fn_wrapper<sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&)::'lambda'(auto&), bool>, __gnu_cxx::__normal_iterator<seastar::lw_shared_ptr<sstables::sstable> const*, std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable>>>>>, boost::use_default, boost::use_default>, void>(auto, auto, std::allocator<flat_mutation_reader_v2> const&) /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/stl_vector.h:706:4
    #14 0x190096e2 in auto boost::copy_range<std::vector<flat_mutation_reader_v2, std::allocator<flat_mutation_reader_v2>>, boost::range_detail::transformed_range<sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&)::'lambda0'(auto&), boost::range_detail::filtered_range<sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&)::'lambda'(auto&), std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable>>> const> const>>(boost::range_detail::transformed_range<sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&)::'lambda0'(auto&), boost::range_detail::filtered_range<sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&)::'lambda'(auto&), std::vector<seastar::lw_shared_ptr<sstables::sstable>, std::allocator<seastar::lw_shared_ptr<sstables::sstable>>> const> const> const&) /usr/include/boost/range/iterator_range_core.hpp:842:20
    #15 0x1900409d in sstables::incremental_reader_selector::create_new_readers(std::optional<dht::ring_position_view> const&) sstables/sstable_set.cc:789:23
    #16 0x180754b8 in mutation_reader_merger::maybe_add_readers(std::optional<dht::ring_position_view> const&) readers/combined.cc:312:32
    #17 0x18075f57 in mutation_reader_merger::maybe_add_readers_at_partition_boundary() readers/combined.cc:359:13
    #18 0x180845f9 in mutation_reader_merger::prepare_next()::$_1::operator()() const readers/combined.cc:378:9
    #19 0x180844f2 in seastar::future<void> seastar::futurize<void>::invoke<mutation_reader_merger::prepare_next()::$_1&>(mutation_reader_merger::prepare_next()::$_1&) ./seastar/include/seastar/core/future.hh:2003:13
    #20 0x18084476 in auto seastar::futurize_invoke<mutation_reader_merger::prepare_next()::$_1&>(mutation_reader_merger::prepare_next()::$_1&) ./seastar/include/seastar/core/future.hh:2037:12
    #21 0x18084403 in auto seastar::future<void> seastar::future<void>::then<mutation_reader_merger::prepare_next()::$_1, seastar::future<void>>(mutation_reader_merger::prepare_next()::$_1&&)::'lambda'(auto&&...)::operator()<>(auto&&...) ./seastar/include/seastar/core/future.hh:1406:24
    #22 0x1808436e in seastar::noncopyable_function<seastar::future<void> ()>::direct_vtable_for<seastar::future<void> seastar::future<void>::then<mutation_reader_merger::prepare_next()::$_1, seastar::future<void>>(mutation_reader_merger::prepare_next()::$_1&&)::'lambda'(auto&&...)>::call(seastar::noncopyable_function<seastar::future<void> ()> const*) ./seastar/include/seastar/util/noncopyable_function.hh:129:20
    #23 0x1477ca32 in seastar::noncopyable_function<seastar::future<void> ()>::operator()() const ./seastar/include/seastar/util/noncopyable_function.hh:215:16
    #24 0x1477c8a6 in seastar::future<void> std::__invoke_impl<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> ()>&>(std::__invoke_other, seastar::noncopyable_function<seastar::future<void> ()>&) /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:61:14
    #25 0x1477c826 in std::__invoke_result<seastar::noncopyable_function<seastar::future<void> ()>&>::type std::__invoke<seastar::noncopyable_function<seastar::future<void> ()>&>(seastar::noncopyable_function<seastar::future<void> ()>&) /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:96:14
    #26 0x1477c7a6 in std::invoke_result<seastar::noncopyable_function<seastar::future<void> ()>&>::type std::invoke<seastar::noncopyable_function<seastar::future<void> ()>&>(seastar::noncopyable_function<seastar::future<void> ()>&) /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/functional:110:14
    #27 0x1477c5ba in auto seastar::internal::future_invoke<seastar::noncopyable_function<seastar::future<void> ()>&, seastar::internal::monostate>(seastar::noncopyable_function<seastar::future<void> ()>&, seastar::internal::monostate&&) ./seastar/include/seastar/core/future.hh:1155:16
    #28 0x1477c37c in seastar::future<void> seastar::future<void>::then_impl_nrvo<seastar::noncopyable_function<seastar::future<void> ()>, seastar::future<void>>(seastar::noncopyable_function<seastar::future<void> ()>&&)::'lambda'(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&, seastar::future_state<seastar::internal::monostate>&&)::operator()(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&, seastar::future_state<seastar::internal::monostate>&&) const::'lambda'()::operator()() const ./seastar/include/seastar/core/future.hh:1458:28
    #29 0x1477c175 in void seastar::futurize<seastar::future<void>>::satisfy_with_result_of<seastar::future<void> seastar::future<void>::then_impl_nrvo<seastar::noncopyable_function<seastar::future<void> ()>, seastar::future<void>>(seastar::noncopyable_function<seastar::future<void> ()>&&)::'lambda'(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&, seastar::future_state<seastar::internal::monostate>&&)::operator()(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&, seastar::future_state<seastar::internal::monostate>&&) const::'lambda'()>(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&&) ./seastar/include/seastar/core/future.hh:1991:9
    #30 0x1477bef8 in seastar::future<void> seastar::future<void>::then_impl_nrvo<seastar::noncopyable_function<seastar::future<void> ()>, seastar::future<void>>(seastar::noncopyable_function<seastar::future<void> ()>&&)::'lambda'(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&, seastar::future_state<seastar::internal::monostate>&&)::operator()(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&, seastar::future_state<seastar::internal::monostate>&&) const ./seastar/include/seastar/core/future.hh:1454:17
    #31 0x1477b8d3 in seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> ()>, seastar::future<void> seastar::future<void>::then_impl_nrvo<seastar::noncopyable_function<seastar::future<void> ()>, seastar::future<void>>(seastar::noncopyable_function<seastar::future<void> ()>&&)::'lambda'(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&, seastar::future_state<seastar::internal::monostate>&&), void>::run_and_dispose() ./seastar/include/seastar/core/future.hh:741:13
    #32 0x7ffff5a41fa8 in seastar::reactor::run_tasks(seastar::reactor::task_queue&) build/debug/seastar/./seastar/src/core/reactor.cc:2590:14
    #33 0x7ffff5a4a1ae in seastar::reactor::run_some_tasks() build/debug/seastar/./seastar/src/core/reactor.cc:3053:9
    #34 0x7ffff5a4e1f0 in seastar::reactor::do_run() build/debug/seastar/./seastar/src/core/reactor.cc:3222:9
    #35 0x7ffff5a4be16 in seastar::reactor::run() build/debug/seastar/./seastar/src/core/reactor.cc:3105:16
    #36 0x7ffff55c5990 in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) build/debug/seastar/./seastar/src/core/app-template.cc:276:31
    #37 0x7ffff55c322a in seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) build/debug/seastar/./seastar/src/core/app-template.cc:167:12
    #38 0x7fffeff88e2e in seastar::testing::test_runner::start_thread(int, char**)::$_0::operator()() build/debug/seastar/./seastar/src/testing/test_runner.cc:75:26
    #39 0x7fffeff88740 in void std::__invoke_impl<void, seastar::testing::test_runner::start_thread(int, char**)::$_0&>(std::__invoke_other, seastar::testing::test_runner::start_thread(int, char**)::$_0&) /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:61:14
    #40 0x7fffeff88630 in std::enable_if<is_invocable_r_v<void, seastar::testing::test_runner::start_thread(int, char**)::$_0&>, void>::type std::__invoke_r<void, seastar::testing::test_runner::start_thread(int, char**)::$_0&>(seastar::testing::test_runner::start_thread(int, char**)::$_0&) /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:111:2
    #41 0x7fffeff8809c in std::_Function_handler<void (), seastar::testing::test_runner::start_thread(int, char**)::$_0>::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_function.h:290:9
    #42 0x14e318ba in std::function<void ()>::operator()() const /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/std_function.h:591:9
    #43 0x7ffff5819bf8 in seastar::posix_thread::start_routine(void*) build/debug/seastar/./seastar/src/core/posix.cc:90:5
    #44 0x7fffef3db12c in start_thread (/lib64/libc.so.6+0x8b12c) (BuildId: 81daba31ee66dbd63efdc4252a872949d874d136)
    #45 0x7fffef45cbbf in __GI___clone3 (/lib64/libc.so.6+0x10cbbf) (BuildId: 81daba31ee66dbd63efdc4252a872949d874d136)

Address 0x7fffe86715e0 is a wild pointer inside of access range of size 0x000000000008.
SUMMARY: AddressSanitizer: stack-use-after-return ./seastar/include/seastar/util/noncopyable_function.hh:215:16 in seastar::noncopyable_function<bool (sstables::sstable const&)>::operator()(sstables::sstable const&) const
Shadow bytes around the buggy address:
  0x10007d0c6260: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x10007d0c6270: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x10007d0c6280: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x10007d0c6290: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x10007d0c62a0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
=>0x10007d0c62b0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5[f5]f5 f5 f5
  0x10007d0c62c0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x10007d0c62d0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x10007d0c62e0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x10007d0c62f0: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x10007d0c6300: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
Shadow byte legend (one shadow byte represents 8 application bytes):
```

It's a result of closure being feeded into a noncopyable_function which is taken by reference by table::make_sstable_reader(). Only affects range reader, because the predicate is used later after the noncopyable_function was destroyed. 

Commit f5e3b8df6d2d5b93e077f9c5 introduced this problem, but it doesn't really affect view building from staging as the latter only produces single key readers, which won't defer before finishing with usage of the predicate. But this is worth backporting anyway.

If I force test to perform single key read

```
-            assert_that(ms_excluding_staging.make_reader_v2(s, env.make_reader_permit(), query::full_partition_range))
+            auto pr = dht::partition_range::make_singular(regular_sst->get_first_decorated_key());
+            assert_that(ms_excluding_staging.make_reader_v2(s, env.make_reader_permit(), pr))
```

the problem goes away

**Comment by DoronArazii** [comment]
@avikivity please backport to all versions

**Comment by avikivity** [comment]
Backported top 5.1, 5.2. While the bug likely only affected the test, as the commit notes it's worth backporting for safety.
