### ISSUE TITLE
table repair error: Repair job has failed with the error message: [xxxx-xx-xx] Repair session 24742 failed

### ISSUE THREAD

**Issue by libo-sober** [scylladb/scylladb#14852]
*Installation details*
Scylla version (or git commit hash): 5.1.13
Cluster size: 18 nodes (6 nodes per az)
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): centos
Hardware: 64cpu / 400G memory
Disks: (SSD/HDD, count) nvme

When performing `nodetool repair` on a keyspace, the following error message appears:

```bash
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [xxxx-xx-xx 15:31:59,497] Repair session 24742 failed
        at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
        at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
        at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

May I ask what meaning does this information represent? What can we do to resolve this error? Thanks.

**Comment by libo-sober** [comment]
> What do you see in the Scylla log files?
During this time period, we only saw the following log information:
```bash
xxx
[shard 39] compaction - [Compact xxx.xxx  48022630-2abd-11ee-904b-f6d8ca5c7208] Compacting [/var/lib/scylla/data/xxx/xxx-aa36c930ffa411ed889de80ffb640922/me-5015959-big-Data.db:level=0:origin=memtable,/var/lib/scylla/data/xxx/xxx-aa36c930ffa411ed889de80ffb640922/me-5015879-big-Data.db:level=0:origin=memtable]
[shard 0] storage_proxy - Exception when communicating with 192.168.1.24, to read from system_distributed.service_levels: std::bad_alloc
[shard 53] compaction - [Compact system.paxos 47d7e1e0-2abd-11ee-bfbf-f6e9ca5c7208] Compacted 2 sstables to [/var/lib/scylla/data/system/paxos-b7b7f0c2fd0a34108c053ef614bb7c2d/me-10048533-big-Data.db:level=0]. 10MB to 10MB (~98% of original) in 1039ms = 10MB/s. ~109568 total partitions merged to 109398.
[shard 53] compaction - xxx
xxx
```
There are some `bad_alloc`. It seems that the specific problem cannot be identified either.

**Comment by mykaul** [comment]
We had at least one memory allocation issue fixed in newer 5.1.14 release - https://github.com/scylladb/scylladb/pull/14375  - not sure if it's the same issue (probably will need more logs and metrics).

**Comment by libo-sober** [comment]
Thanks. We are trying to gather more information and upgrade 5.1.14.
