### ISSUE TITLE
 topology/test_topology_rejoin.py::test_start_after_sudden_stop fails

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#14944]
the client was unable to connect to the restarted node after the topology change

right after scylla-108 restarted, it stopped itself due to a `std::bad_variant_access` exception:
```
INFO  2023-08-03 09:54:21,904 [shard 0] init - starting forward service
INFO  2023-08-03 09:54:21,906 [shard 0] init - starting migration manager
INFO  2023-08-03 09:54:21,906 [shard 0] init - initializing query processor remote part
INFO  2023-08-03 09:54:21,915 [shard 0] init - initializing batchlog manager
INFO  2023-08-03 09:54:21,923 [shard 0] format_selector - Selected me sstables format
INFO  2023-08-03 09:54:21,935 [shard 0] init - Shutting down sstables format selector
INFO  2023-08-03 09:54:21,935 [shard 0] init - Shutting down sstables format selector was successful
INFO  2023-08-03 09:54:21,935 [shard 0] init - Shutting down query processor remote part
INFO  2023-08-03 09:54:21,936 [shard 0] init - Shutting down query processor remote part was successful
...
ERROR 2023-08-03 09:54:31,867 [shard 0] init - Startup failed: std::bad_variant_access (bad variant access)
------ Ending test debug/topology.test_topology_rejoin.1::test_start_after_sudden_stop ------
```

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2834/artifact/testlog/x86_64/debug/scylla-108.log

and the client gave up after its last retry
```
[2023-08-03T07:02:57.901Z] ConnectionRefusedError: [Errno 111] Tried connecting to [('127.78.36.8', 9042)]. Last error: Connection refused
[2023-08-03T07:02:57.901Z] 09:54:32.478 WARNING> Error attempting to reconnect to 127.78.36.8:9042, scheduling retry in 16.96 seconds: [Errno 111] Tried connecting to [('127.78.36.8', 9042)]. Last error: Connection refused
[2023-08-03T07:02:57.901Z] 09:54:32.478 DEBUG> Reconnection error details
[2023-08-03T07:02:57.901Z] Traceback (most recent call last):
[2023-08-03T07:02:57.901Z]   File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
[2023-08-03T07:02:57.901Z]   File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
[2023-08-03T07:02:57.901Z]   File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
[2023-08-03T07:02:57.901Z]   File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
[2023-08-03T07:02:57.901Z]     self._connect_socket()
[2023-08-03T07:02:57.901Z]   File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
[2023-08-03T07:02:57.901Z] ConnectionRefusedError: [Errno 111] Tried connecting to [('127.78.36.8', 9042)]. Last error: Connection refused
[2023-08-03T07:02:57.901Z] FAILED
```
see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2834/

not reproduciable so far.

**Comment by tchaikov** [comment]
seems when the test fails,

1. there were 2 rows in the topology table
2. "num_ranges" was missing in the query result of  `SELECT count(range_end) as cnt, num_ranges FROM system.{} WHERE id = ?", CDC_GENERATIONS_V3)`

**Comment by piodul** [comment]
@tchaikov we also just took a look together with @kbr-scylla at the failure. This is caused due to my cluster features PR that was merged yesterday. I'm preparing a fix.

**Comment by tchaikov** [comment]
@piodul thanks for the note! stopping the investigation now =)

**Comment by tchaikov** [comment]
i am adding P1, as quite a few PRs are blocked by this issue. it is reproduciable around 2 out of 7 runs.

**Comment by avikivity** [comment]
@piodul I think this doesn't merit a backport since it can only trigger in experimental paths, please confirm.

**Comment by piodul** [comment]
I confirm, it can only happen in raft topology mode (which is behind an experimental flag). Backport is not needed.
