### ISSUE TITLE
Failure to start on docker due to low aio-max-nr value

### ISSUE THREAD

**Issue by guy9** [scylladb/scylladb#15010]
*Installation details*
Scylla version (or git commit hash): 5.2.0 (appears in 5.0 and 4.6 as well)
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): docker

A three-node ScyllaDB cluster using docker, fails to start unless aio-max-nr is increased. 
This error is received:
`FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)`

It happens when I try to start a 3-node cluster on Killercoda, using docker, (see [here](https://killercoda.com/scylladb/scenario/high-availability-lab)) with Scylla version 4.6.0 or later. In version 4.5.0 or earlier, the issue does not happen.

Two docker instances start well, while the third fails with the above error. 
The command used to start the instance is:
`docker run --name Node_X -d scylladb/scylla:4.6.0 --overprovisioned 1 --smp 1
`
For ScyllaDB versions 4.6 and later, after increasing the system aio-max-nr, it is possible to start the third node as well, see below. 
It might be related to [this issue](https://github.com/scylladb/scylladb/issues/5638)

The last version where it works is 4.5. The issue first appears in version 4.6 (and continues to appear in versions 5.0, 5.2). 

**OS Version:**
```
ubuntu $ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
ubuntu $
```

**Aio-max-nr value**
The default for the machine used:
```
ubuntu $  cat /proc/sys/fs/aio-max-nr
65536
After changing the value to 10485760 it does work:
vi /etc/sysctl.conf
[03:50:06] root@ubuntu:~
=========# sysctl -p /etc/sysctl.conf
fs.inotify.max_user_watches = 524288
fs.aio-max-nr = 10485760
```
It does work. 

**Memory used:**
```
ubuntu $ free
              total        used        free      shared  buff/cache   available
Mem:        2030940      699140      141944        1212     1189856     1134452
Swap:       1048572        5668     1042904
ubuntu $ 
```

Disk:
```
ubuntu $ dmesg | grep blocks
[    6.952776] virtio_blk virtio3: [vda] 41943040 512-byte logical blocks (21.5 GB/20.0 GiB)
ubuntu $ 

**CPU:**
ubuntu $ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          1
On-line CPU(s) list:             0
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           42
Model name:                      Intel Xeon E312xx (Sandy Bridge, IBRS update)
Stepping:                        1
CPU MHz:                         2200.214
BogoMIPS:                        4400.42
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        4 MiB
L3 cache:                        16 MiB
NUMA node0 CPU(s):               0
Vulnerability Itlb multihit:     KVM: Vulnerable
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling, PBRSB-eIBRS 
                                 Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse
                                  sse2 syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pcl
                                 mulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervis
                                 or lahf_lm cpuid_fault pti ssbd ibrs ibpb stibp tsc_adjust xsaveopt arat md_clear
ubuntu $
```

**Comment by guy9** [comment]
With regards to importance,  users of ScyllaDB University, are reporting running into this issue. 
To avoid this issue, on the Killercoda platform (used for training labs), we don't run the latest ScyllaDB version.

**Comment by mykaul** [comment]
I think the solution - to increase the value, is valid. 
@guy9 - how complicated is it to implement?

**Comment by guy9** [comment]
This is the full log:

```
ubuntu $ docker logs 14d1443c7959
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '1'],)
running: (['/opt/scylladb/scripts/scylla_io_setup'],)
2023-08-13 11:01:50,240 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-08-13 11:01:50,240 INFO Included extra file "/etc/supervisord.conf.d/rsyslog.conf" during parsing
2023-08-13 11:01:50,241 INFO Included extra file "/etc/supervisord.conf.d/scylla-housekeeping.conf" during parsing
2023-08-13 11:01:50,241 INFO Included extra file "/etc/supervisord.conf.d/scylla-jmx.conf" during parsing
2023-08-13 11:01:50,241 INFO Included extra file "/etc/supervisord.conf.d/scylla-node-exporter.conf" during parsing
2023-08-13 11:01:50,241 INFO Included extra file "/etc/supervisord.conf.d/scylla-server.conf" during parsing
2023-08-13 11:01:50,241 INFO Included extra file "/etc/supervisord.conf.d/sshd-server.conf" during parsing
2023-08-13 11:01:50,245 INFO RPC interface 'supervisor' initialized
2023-08-13 11:01:50,248 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2023-08-13 11:01:50,248 INFO supervisord started with pid 25
2023-08-13 11:01:51,250 INFO spawned: 'rsyslog' with pid 26
2023-08-13 11:01:51,253 INFO spawned: 'scylla' with pid 27
2023-08-13 11:01:51,259 INFO spawned: 'scylla-housekeeping' with pid 28
2023-08-13 11:01:51,264 INFO spawned: 'scylla-jmx' with pid 29
2023-08-13 11:01:51,273 INFO spawned: 'scylla-node-exporter' with pid 30
2023-08-13 11:01:51,280 INFO spawned: 'sshd' with pid 32
rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
rsyslogd: activation of module imklog failed [v8.2112.0 try https://www.rsyslog.com/e/2145 ]
ts=2023-08-13T11:01:51.326Z caller=node_exporter.go:182 level=info msg="Starting node_exporter" version="(version=1.4.0, branch=HEAD, revision=7da1321761b3b8dfc9e496e1a60e6a476fec6018)"
ts=2023-08-13T11:01:51.326Z caller=node_exporter.go:183 level=info msg="Build context" build_context="(go=go1.19.1, user=root@83d90983e89c, date=20220926-12:32:56)"
ts=2023-08-13T11:01:51.327Z caller=node_exporter.go:185 level=warn msg="Node Exporter is running as root user. This exporter is designed to run as unprivileged user, root is not required."
ts=2023-08-13T11:01:51.327Z caller=filesystem_common.go:111 level=info collector=filesystem msg="Parsed flag --collector.filesystem.mount-points-exclude" flag=^/(dev|proc|run/credentials/.+|sys|var/lib/docker/.+|var/lib/containers/storage/.+)($|/)
ts=2023-08-13T11:01:51.328Z caller=filesystem_common.go:113 level=info collector=filesystem msg="Parsed flag --collector.filesystem.fs-types-exclude" flag=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
ts=2023-08-13T11:01:51.328Z caller=diskstats_common.go:100 level=info collector=diskstats msg="Parsed flag --collector.diskstats.device-exclude" flag=^(ram|loop|fd|(h|s|v|xv)d[a-z]|nvme\d+n\d+p)\d+$
ts=2023-08-13T11:01:51.329Z caller=diskstats_linux.go:264 level=error collector=diskstats msg="Failed to open directory, disabling udev device properties" path=/run/udev/data
ts=2023-08-13T11:01:51.329Z caller=node_exporter.go:108 level=info msg="Enabled collectors"
ts=2023-08-13T11:01:51.329Z caller=node_exporter.go:115 level=info collector=arp
ts=2023-08-13T11:01:51.329Z caller=node_exporter.go:115 level=info collector=bcache
ts=2023-08-13T11:01:51.330Z caller=node_exporter.go:115 level=info collector=bonding
ts=2023-08-13T11:01:51.330Z caller=node_exporter.go:115 level=info collector=btrfs
ts=2023-08-13T11:01:51.330Z caller=node_exporter.go:115 level=info collector=conntrack
ts=2023-08-13T11:01:51.330Z caller=node_exporter.go:115 level=info collector=cpu
ts=2023-08-13T11:01:51.331Z caller=node_exporter.go:115 level=info collector=cpufreq
ts=2023-08-13T11:01:51.331Z caller=node_exporter.go:115 level=info collector=diskstats
ts=2023-08-13T11:01:51.331Z caller=node_exporter.go:115 level=info collector=dmi
ts=2023-08-13T11:01:51.331Z caller=node_exporter.go:115 level=info collector=edac
ts=2023-08-13T11:01:51.331Z caller=node_exporter.go:115 level=info collector=entropy
ts=2023-08-13T11:01:51.332Z caller=node_exporter.go:115 level=info collector=fibrechannel
ts=2023-08-13T11:01:51.332Z caller=node_exporter.go:115 level=info collector=filefd
ts=2023-08-13T11:01:51.332Z caller=node_exporter.go:115 level=info collector=filesystem
ts=2023-08-13T11:01:51.332Z caller=node_exporter.go:115 level=info collector=hwmon
ts=2023-08-13T11:01:51.332Z caller=node_exporter.go:115 level=info collector=infiniband
ts=2023-08-13T11:01:51.332Z caller=node_exporter.go:115 level=info collector=interrupts
ts=2023-08-13T11:01:51.332Z caller=node_exporter.go:115 level=info collector=ipvs
ts=2023-08-13T11:01:51.333Z caller=node_exporter.go:115 level=info collector=loadavg
ts=2023-08-13T11:01:51.333Z caller=node_exporter.go:115 level=info collector=mdadm
ts=2023-08-13T11:01:51.333Z caller=node_exporter.go:115 level=info collector=meminfo
ts=2023-08-13T11:01:51.333Z caller=node_exporter.go:115 level=info collector=netclass
ts=2023-08-13T11:01:51.333Z caller=node_exporter.go:115 level=info collector=netdev
ts=2023-08-13T11:01:51.333Z caller=node_exporter.go:115 level=info collector=netstat
ts=2023-08-13T11:01:51.333Z caller=node_exporter.go:115 level=info collector=nfs
ts=2023-08-13T11:01:51.333Z caller=node_exporter.go:115 level=info collector=nfsd
ts=2023-08-13T11:01:51.333Z caller=node_exporter.go:115 level=info collector=nvme
ts=2023-08-13T11:01:51.333Z caller=node_exporter.go:115 level=info collector=os
ts=2023-08-13T11:01:51.333Z caller=node_exporter.go:115 level=info collector=powersupplyclass
ts=2023-08-13T11:01:51.333Z caller=node_exporter.go:115 level=info collector=pressure
ts=2023-08-13T11:01:51.334Z caller=node_exporter.go:115 level=info collector=rapl
ts=2023-08-13T11:01:51.334Z caller=node_exporter.go:115 level=info collector=schedstat
ts=2023-08-13T11:01:51.334Z caller=node_exporter.go:115 level=info collector=selinux
ts=2023-08-13T11:01:51.334Z caller=node_exporter.go:115 level=info collector=sockstat
ts=2023-08-13T11:01:51.334Z caller=node_exporter.go:115 level=info collector=softnet
ts=2023-08-13T11:01:51.334Z caller=node_exporter.go:115 level=info collector=stat
ts=2023-08-13T11:01:51.334Z caller=node_exporter.go:115 level=info collector=tapestats
ts=2023-08-13T11:01:51.334Z caller=node_exporter.go:115 level=info collector=textfile
ts=2023-08-13T11:01:51.334Z caller=node_exporter.go:115 level=info collector=thermal_zone
ts=2023-08-13T11:01:51.334Z caller=node_exporter.go:115 level=info collector=time
ts=2023-08-13T11:01:51.334Z caller=node_exporter.go:115 level=info collector=timex
ts=2023-08-13T11:01:51.335Z caller=node_exporter.go:115 level=info collector=udp_queues
ts=2023-08-13T11:01:51.335Z caller=node_exporter.go:115 level=info collector=uname
ts=2023-08-13T11:01:51.335Z caller=node_exporter.go:115 level=info collector=vmstat
ts=2023-08-13T11:01:51.335Z caller=node_exporter.go:115 level=info collector=xfs
ts=2023-08-13T11:01:51.335Z caller=node_exporter.go:115 level=info collector=zfs
ts=2023-08-13T11:01:51.335Z caller=node_exporter.go:199 level=info msg="Listening on" address=:9100
ts=2023-08-13T11:01:51.336Z caller=tls_config.go:195 level=info msg="TLS is disabled." http2=false
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
Connecting to http://localhost:100002023-08-13 11:01:52,094 INFO exited: scylla (exit status 7; not expected)

Starting the JMX server
JMX is enabled to receive remote connections on port: 7199
2023-08-13 11:01:52,479 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:01:52,479 INFO success: scylla-housekeeping entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:01:52,479 INFO success: scylla-jmx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:01:52,479 INFO success: scylla-node-exporter entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:01:52,479 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:01:53,483 INFO spawned: 'scylla' with pid 72
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
2023-08-13 11:01:54,611 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:01:54,612 INFO exited: scylla (exit status 7; not expected)
2023-08-13 11:01:55,614 INFO spawned: 'scylla' with pid 83
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 196, in <module>
    args.func(args)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 122, in check_version
    current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 80, in get_api
    return get_json_from_url("http://" + api_address + path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 75, in get_json_from_url
    raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
RuntimeError: Failed to get "http://localhost:10000/storage_service/scylla_release_version" due to the following error: <urlopen error [Errno 99] Cannot assign requested address>
2023-08-13 11:01:56,732 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:01:56,733 INFO exited: scylla (exit status 7; not expected)
2023-08-13 11:01:57,734 INFO spawned: 'scylla' with pid 106
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
2023-08-13 11:01:58,847 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:01:58,848 INFO exited: scylla (exit status 7; not expected)
2023-08-13 11:01:59,849 INFO spawned: 'scylla' with pid 117
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
2023-08-13 11:02:00,982 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:02:00,983 INFO exited: scylla (exit status 7; not expected)
2023-08-13 11:02:01,985 INFO spawned: 'scylla' with pid 128
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
2023-08-13 11:02:03,107 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:02:03,107 INFO exited: scylla (exit status 7; not expected)
2023-08-13 11:02:04,109 INFO spawned: 'scylla' with pid 139
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
2023-08-13 11:02:05,245 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:02:05,246 INFO exited: scylla (exit status 7; not expected)
2023-08-13 11:02:06,250 INFO spawned: 'scylla' with pid 150
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
2023-08-13 11:02:07,395 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:02:07,395 INFO exited: scylla (exit status 7; not expected)
2023-08-13 11:02:08,396 INFO spawned: 'scylla' with pid 161
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
2023-08-13 11:02:09,532 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:02:09,532 INFO exited: scylla (exit status 7; not expected)
2023-08-13 11:02:10,534 INFO spawned: 'scylla' with pid 172
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
2023-08-13 11:02:11,641 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:02:11,641 INFO exited: scylla (exit status 7; not expected)
2023-08-13 11:02:12,643 INFO spawned: 'scylla' with pid 183
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
2023-08-13 11:02:13,770 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:02:13,770 INFO exited: scylla (exit status 7; not expected)
2023-08-13 11:02:14,772 INFO spawned: 'scylla' with pid 194
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
2023-08-13 11:02:15,915 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:02:15,915 INFO exited: scylla (exit status 7; not expected)
2023-08-13 11:02:16,916 INFO spawned: 'scylla' with pid 205
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
2023-08-13 11:02:18,033 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:02:18,033 INFO exited: scylla (exit status 7; not expected)
2023-08-13 11:02:19,035 INFO spawned: 'scylla' with pid 216
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
2023-08-13 11:02:20,154 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:02:20,154 INFO exited: scylla (exit status 7; not expected)
2023-08-13 11:02:21,157 INFO spawned: 'scylla' with pid 227
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
2023-08-13 11:02:22,300 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-08-13 11:02:22,300 INFO exited: scylla (exit status 7; not expected)
2023-08-13 11:02:23,304 INFO spawned: 'scylla' with pid 238
ubuntu $ 
```

**Comment by guy9** [comment]
Closing this as a documentation issue (per https://github.com/scylladb/scylladb/issues/15072)
