### ISSUE TITLE
create-relocatable-package.py fails to create reloc package

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#15018]
we build multiple relocatable packages for different builds in parallel using ninja. all these relocatable packages are built using the same script of
`create-relocatable-package.py`. but this script always uses the same directory and file for the .relocatable_package_version file.

so there are chances that the jobs building the relocatable packages can race and writing / accessing the same file at the same time. this issue is manifested like
```
[2023-08-10T09:38:00.019Z] FAILED: build/debug/dist/tar/scylla-unstripped-5.4.0~dev-0.20230810.116c10a2b0c6.x86_64.tar.gz
[2023-08-10T09:38:00.019Z] scripts/create-relocatable-package.py --mode debug 'build/debug/dist/tar/scylla-unstripped-5.4.0~dev-0.20230810.116c10a2b0c6.x86_64.tar.gz'
[2023-08-10T09:38:00.019Z] Traceback (most recent call last):
[2023-08-10T09:38:00.019Z]   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/scripts/create-relocatable-package.py", line 130, in <module>
[2023-08-10T09:38:00.019Z]     os.makedirs(f'build/{SCYLLA_DIR}')
[2023-08-10T09:38:00.019Z]   File "<frozen os>", line 225, in makedirs
[2023-08-10T09:38:00.019Z] FileExistsError: [Errno 17] File exists:
'build/scylla-package'
```

**Comment by denesb** [comment]
One one hand, this seems like a fix targeted at CI. On the other hand, it could cause build failures on 5.2. @tchaikov do you think we should backport this?

**Comment by tchaikov** [comment]
@denesb hi Botond, I'd suggest not  to backport this change. It happens only when we are really "lucky". And even it happens , we are aware of this.
