### ISSUE TITLE
DecommissionStreamingErr - decommissioned node is not rebooted

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#15094]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

The nemesis of decommissioned node-3 but no expected reboot found to be issued afterwards - 
```
:2023-08-12 14:53:11,348 f:nemesis.py      l:1717 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: >>>>>>>>>>>>>Started random_disrupt_method decommission_streaming_err
< t:2023-08-12 14:53:11,352 f:nemesis.py      l:345  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Current Target: Node longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3 [34.138.253.178 | 10.142.0.208] (seed: True) with running nemesis: HotReloadingInternodeCertificate Node longevity-large-partitions-200k-pks-db-node-7ca890ce-0-4 [34.138.200.0 | 10.142.0.210] (seed: True)
< t:2023-08-12 14:54:15,500 f:nemesis.py      l:4882 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Start disruption at `2023-08-12 14:54:15.500955`
< t:2023-08-12 14:54:15,501 f:nemesis.py      l:1080 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Set current_disruption -> DecommissionStreamingErr Node longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3 [34.138.253.178 | 10.142.0.208] (seed: True)

< t:2023-08-12 14:53:53,814 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.142.0.208  1.23 TB    256          ?       ee1b70ec-116a-46b4-aed1-7ade62dab9db  d
< t:2023-08-12 14:54:05,549 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UN  10.142.0.208  1.23 TB    256          ?       ee1b70ec-116a-46b4-aed1-7ade62dab9db  d


< t:2023-08-12 14:54:16,529 f:nemesis.py      l:3627 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Reboot node after log message: 'became a group 0 non-voter'
< t:2023-08-12 14:54:16,539 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  decommission "...
< t:2023-08-12 15:04:23,113 f:nemesis.py      l:3600 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: The decommission of target node is successfully interrupted
< t:2023-08-12 15:04:27,447 f:decorators.py   l:72   c:sdcm.utils.decorators p:DEBUG > '_wait_for_nodes_up_and_normal': failed with 'ClusterNodesNotReady('Not all nodes joined the cluster')', retrying [#0]


2023-08-12T14:54:18+00:00 longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3     !INFO | scylla[33084]:  [shard  0] storage_service - DECOMMISSIONING: starts
2023-08-12T14:54:18+00:00 longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3     !INFO | scylla[33084]:  [shard  0] raft_group0 - Performing a group 0 read barrier...
2023-08-12T14:54:18+00:00 longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3     !INFO | scylla[33084]:  [shard  0] raft_group0 - Finished group 0 read barrier.
2023-08-12T14:54:18+00:00 longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3     !INFO | scylla[33084]:  [shard  0] storage_service - decommission[453de15d-7473-44dc-90db-dfbe1f7475e3]: Started heartbeat_updater (interval=10s)
2023-08-12T14:54:18+00:00 longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3     !INFO | scylla[33084]:  [shard  0] storage_service - decommission[453de15d-7473-44dc-90db-dfbe1f7475e3]: Started decommission_prepare[453de15d-7473-44dc-90db-dfbe1f7475e3]: ignore_nodes={}, leaving_nodes={10.142.0.208}, replace_nodes={}, bootstrap_nodes={}, repair_tables={}
2023-08-12T14:54:18+00:00 longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3     !INFO | scylla[33084]:  [shard  0] storage_service - decommission[453de15d-7473-44dc-90db-dfbe1f7475e3]: Added node=10.142.0.208 as leaving node, coordinator=10.142.0.208
2023-08-12T14:54:18+00:00 longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3     !INFO | scylla[33084]:  [shard  0] storage_service - decommission[453de15d-7473-44dc-90db-dfbe1f7475e3]: Finished decommission_prepare[453de15d-7473-44dc-90db-dfbe1f7475e3]: ignore_nodes={}, leaving_nodes={10.142.0.208}, replace_nodes={}, bootstrap_nodes={}, repair_tables={}
2023-08-12T14:54:18+00:00 longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3     !INFO | scylla[33084]:  [shard  0] storage_service - DECOMMISSIONING: unbootstrap starts
2023-08-12T14:54:18+00:00 longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3     !INFO | scylla[33084]:  [shard  0] storage_service - Started batchlog replay for decommission
2023-08-12T14:54:18+00:00 longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3     !INFO | scylla[33084]:  [shard  0] storage_service - Finished batchlog replay for decommission

< t:2023-08-12 15:04:18,814 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UL  10.142.0.208  1.27 TB    256          ?       ee1b70ec-116a-46b4-aed1-7ade62dab9db  d
< t:2023-08-12 15:04:22,611 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > UL  10.142.0.208  1.27 TB    256          ?       ee1b70ec-116a-46b4-aed1-7ade62dab9db  d

2023-08-12 15:14:03.293: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=fed89919-311d-441e-ac05-b99f946ffd41: type=NodeStatus node=longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3 error=Current node Node longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3 [34.138.253.178 | 10.142.0.208] (seed: True). Wrong node status. Node Node longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3 [34.138.253.178 | 10.142.0.208] (seed: True) status in nodetool.status is UL, but status in gossip NORMAL

2023-08-12T15:14:06+00:00 longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3     !INFO | scylla[33084]:  [shard 12] repair - repair[7213425b-affc-4797-a5d7-7ac8320a3630]: Started to repair 3 out of 3 tables in keyspace=scylla_bench, table=test_counters, table_id=5f881d20-38c6-11ee-b370-ddcdb35ec7f7, repair_reason=decommission
```
Then test failed with:
```
2023-08-12 15:10:18.125: (DisruptionEvent Severity.ERROR) period_type=end event_id=252949c6-f553-4cab-b0ed-fbabb1440a11 duration=16m2s: nemesis_name=DecommissionStreamingErr target_node=Node longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3 [34.138.253.178 | 10.142.0.208] (seed: True) errors=Not all nodes joined the cluster
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4907, in wrapper
result = method(*args[1:], **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3725, in disrupt_decommission_streaming_err
self.start_and_interrupt_decommission_streaming()
File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3651, in start_and_interrupt_decommission_streaming
self.target_node.wait_node_fully_start()
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3120, in wait_node_fully_start
self.parent_cluster.wait_for_nodes_up_and_normal(nodes=[self])
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4310, in wait_for_nodes_up_and_normal
_wait_for_nodes_up_and_normal()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4308, in _wait_for_nodes_up_and_normal
self.check_nodes_up_and_normal(nodes=nodes, verification_node=verification_node)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4277, in check_nodes_up_and_normal
raise ClusterNodesNotReady("Not all nodes joined the cluster")
sdcm.cluster.ClusterNodesNotReady: Not all nodes joined the cluster
```
and:
```
2023-08-12 15:12:08.776: (ClusterHealthValidatorEvent Severity.CRITICAL) period_type=one-time event_id=e88ece06-46d4-4f6a-a1d2-77fd58dbac3d: type=NodeStatus node=longevity-large-partitions-200k-pks-db-node-7ca890ce-0-1 error=Current node Node longevity-large-partitions-200k-pks-db-node-7ca890ce-0-1 [35.185.10.72 | 10.142.0.198] (seed: True). Node Node longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3 [34.138.253.178 | 10.142.0.208] (seed: True) (DecommissionStreamingErr Node longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3 [34.138.253.178 | 10.142.0.208] (seed: True) nemesis target node) status is UL
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1038-gcp
Scylla version (or git commit hash): `5.4.0~dev-20230812.d1d1b6cf6e01` with build-id `6c4f55c26164d6fe2cd25d38f5022795ce696d9c`

Cluster size: 5 nodes (n2-highmem-16)

Scylla Nodes used in this run:
- longevity-large-partitions-200k-pks-db-node-7ca890ce-0-7 (35.243.254.159 | 10.142.0.41) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-7ca890ce-0-6 (35.227.5.228 | 10.142.0.8) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-7ca890ce-0-5 (34.75.172.34 | 10.142.0.211) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-7ca890ce-0-4 (34.138.200.0 | 10.142.0.210) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-7ca890ce-0-3 (34.138.253.178 | 10.142.0.208) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-7ca890ce-0-2 (35.231.232.76 | 10.142.0.204) (shards: 14)
- longevity-large-partitions-200k-pks-db-node-7ca890ce-0-1 (35.185.10.72 | 10.142.0.198) (shards: 14)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/scylla-5-4-0-dev-x86-64-2023-08-12t02-57-40` (gce: undefined_region)

Test: `longevity-large-partition-200k-pks-4days-gce-test`
Test id: `7ca890ce-8673-425e-aed2-e336b4a60d95`
Test name: `scylla-master/longevity/longevity-large-partition-200k-pks-4days-gce-test`
Test config file(s):

- [longevity-large-partition-200k_pks-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/02ddb5b75a35bb137b37151600ec583ba7d21151/test-cases/longevity/longevity-large-partition-200k_pks-4days.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 7ca890ce-8673-425e-aed2-e336b4a60d95`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7ca890ce-8673-425e-aed2-e336b4a60d95)
- Show all stored logs command: `$ hydra investigate show-logs 7ca890ce-8673-425e-aed2-e336b4a60d95`

## Logs:
- **db-cluster-7ca890ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7ca890ce-8673-425e-aed2-e336b4a60d95/20230812_152740/db-cluster-7ca890ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7ca890ce-8673-425e-aed2-e336b4a60d95/20230812_152740/db-cluster-7ca890ce.tar.gz)
- **sct-runner-events-7ca890ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7ca890ce-8673-425e-aed2-e336b4a60d95/20230812_152740/sct-runner-events-7ca890ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7ca890ce-8673-425e-aed2-e336b4a60d95/20230812_152740/sct-runner-events-7ca890ce.tar.gz)
- **sct-7ca890ce.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7ca890ce-8673-425e-aed2-e336b4a60d95/20230812_152740/sct-7ca890ce.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7ca890ce-8673-425e-aed2-e336b4a60d95/20230812_152740/sct-7ca890ce.log.tar.gz)
- **loader-set-7ca890ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7ca890ce-8673-425e-aed2-e336b4a60d95/20230812_152740/loader-set-7ca890ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7ca890ce-8673-425e-aed2-e336b4a60d95/20230812_152740/loader-set-7ca890ce.tar.gz)
- **monitor-set-7ca890ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7ca890ce-8673-425e-aed2-e336b4a60d95/20230812_152740/monitor-set-7ca890ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7ca890ce-8673-425e-aed2-e336b4a60d95/20230812_152740/monitor-set-7ca890ce.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-large-partition-200k-pks-4days-gce-test/9/)
[Argus](https://argus.scylladb.com/test/917e825f-11f9-4493-acdb-ec5266a3af78/runs?additionalRuns[]=7ca890ce-8673-425e-aed2-e336b4a60d95)
</details>

**Comment by yarongilor** [comment]
[opened in wrong repository, closing]
