### ISSUE TITLE
topology tests: too low timeouts used for consistency checks

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#15104]
For example test/topology/test_replace.py:
```python3
@pytest.mark.asyncio
async def test_replace_different_ip(manager: ManagerClient) -> None:
    """Replace an existing node with new node using a different IP address"""
    servers = await manager.running_servers()
    await manager.server_stop(servers[0].server_id)
    replace_cfg = ReplaceConfig(replaced_id = servers[0].server_id, reuse_ip_addr = False, use_host_id = False)
    await manager.server_add(replace_cfg)
    await wait_for_token_ring_and_group0_consistency(manager, time.time() + 30)
```

The timeout used for `wait_for_token_ring_and_group0_consistency` is 30 seconds.

Turns out it's too low, because for some reason, the driver sometimes sleeps for ~30 seconds before connecting to a node, and we need the driver connected to fetch group 0 member list.

(And they said that using CQL instead of REST APIs was a good idea.)

Example logs from CI run: 
[topology.test_replace.3.log](https://github.com/scylladb/scylladb/files/12394336/topology.test_replace.3.log)

```
22:47:46.054 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:47.056 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:48.059 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:49.061 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:50.063 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:51.065 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:52.067 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:53.068 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:54.069 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:55.071 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:56.073 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:57.075 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:58.076 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:59.077 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:00.079 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:01.080 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:02.082 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:03.083 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:04.085 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:05.086 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:06.088 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:07.090 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:08.092 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:09.093 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:10.094 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:11.095 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:12.097 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:13.098 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:14.100 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:15.102 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:16.104 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:17.105 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:17.913 DEBUG> Connection 140694068603152 127.0.0.1:39308 -> 127.204.54.40:9042
```

cc @avelanarius 

what we can do in the tests is increase the timeouts...

**Comment by mykaul** [comment]
> Turns out it's too low, because for some reason, the driver sometimes sleeps for ~30 seconds before connecting to a node, and we need the driver connected to fetch group 0 member list.

DNS resolving or reverse resolving perhaps?

**Comment by avelanarius** [comment]
Relevant logs to driver reconnecting:

```
22:44:40.329 DEBUG> [control connection] Closing old connection <LibevConnection(140694450159440) 127.204.54.40:9042 (closed)>, replacing with <LibevConnection(140694406290832) 127.204.54.2:9042>
22:44:40.427 DEBUG> [control connection] Closing old connection <LibevConnection(140694406290832) 127.204.54.2:9042>, replacing with <LibevConnection(140694406292112) 127.204.54.39:9042>
22:44:40.427 DEBUG> Closing connection (140694406290832) to 127.204.54.2:9042
22:44:40.427 DEBUG> Closed socket to 127.204.54.2:9042
22:44:40.783 WARNING> Error attempting to reconnect to 127.204.54.40:9042, scheduling retry in 1.92 seconds: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:44:40.784 DEBUG> Reconnection error details
Traceback (most recent call last):
  File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
  File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
  File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
  File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:44:42.789 WARNING> Error attempting to reconnect to 127.204.54.40:9042, scheduling retry in 3.88 seconds: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:44:42.789 DEBUG> Reconnection error details
Traceback (most recent call last):
  File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
  File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
  File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
  File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:44:46.696 WARNING> Error attempting to reconnect to 127.204.54.40:9042, scheduling retry in 7.68 seconds: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:44:46.697 DEBUG> Reconnection error details
Traceback (most recent call last):
  File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
  File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
  File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
  File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:44:54.410 WARNING> Error attempting to reconnect to 127.204.54.40:9042, scheduling retry in 14.88 seconds: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:44:54.411 DEBUG> Reconnection error details
Traceback (most recent call last):
  File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
  File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
  File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
  File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:45:00.615 INFO> Driver not connected to 127.204.54.40:9042 yet
22:45:01.617 INFO> Driver not connected to 127.204.54.40:9042 yet
22:45:02.619 INFO> Driver not connected to 127.204.54.40:9042 yet
22:45:03.621 INFO> Driver not connected to 127.204.54.40:9042 yet
22:45:04.622 INFO> Driver not connected to 127.204.54.40:9042 yet
22:45:05.624 INFO> Driver not connected to 127.204.54.40:9042 yet
22:45:06.625 INFO> Driver not connected to 127.204.54.40:9042 yet
22:45:07.626 INFO> Driver not connected to 127.204.54.40:9042 yet
22:45:08.628 INFO> Driver not connected to 127.204.54.40:9042 yet
```

When you sum up reconnection delays you get roughly 30s: 1.92s, 3.88s, 7.68s, 14.88s.

**Comment by avelanarius** [comment]
Maybe for the purposes of `test.py` it would make sense to override the default reconnection policy:

https://github.com/scylladb/python-driver/blob/7c9df8500bf8260e404c6225207a4a5dc97aaab5/cassandra/cluster.py#L731

to `ConstantReconnectionPolicy` with small delay.

**Comment by kbr-scylla** [comment]
Thanks @avelanarius! This sounds like a good idea.

**Comment by mykaul** [comment]
Why does it take more than (1.92s + 3.88s + 7.68s) to connect? and even with 14.88 I still did not reach 30s?

**Comment by avelanarius** [comment]
> Why does it take more than (1.92s + 3.88s + 7.68s) to connect? and even with 14.88 I still did not reach 30s?

A second example of it in the logs shows the problem better:

```
22:47:12.206 WARNING> Error attempting to reconnect to 127.204.54.40:9042, scheduling retry in 2.04 seconds: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:47:12.206 DEBUG> Reconnection error details
Traceback (most recent call last):
  File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
  File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
  File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
  File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:47:14.310 WARNING> Error attempting to reconnect to 127.204.54.40:9042, scheduling retry in 3.6 seconds: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:47:14.311 DEBUG> Reconnection error details
Traceback (most recent call last):
  File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
  File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
  File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
  File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:47:17.917 WARNING> Error attempting to reconnect to 127.204.54.40:9042, scheduling retry in 8.96 seconds: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:47:17.918 DEBUG> Reconnection error details
Traceback (most recent call last):
  File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
  File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
  File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
  File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:47:26.933 WARNING> Error attempting to reconnect to 127.204.54.40:9042, scheduling retry in 16.32 seconds: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:47:26.934 DEBUG> Reconnection error details
Traceback (most recent call last):
  File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
  File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
  File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
  File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:47:43.259 WARNING> Error attempting to reconnect to 127.204.54.40:9042, scheduling retry in 34.56 seconds: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:47:43.260 DEBUG> Reconnection error details
Traceback (most recent call last):
  File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
  File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
  File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
  File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.204.54.40', 9042)]. Last error: Connection refused
22:47:45.834 DEBUG> ManagerClient added Server(1103, 127.204.54.40)
22:47:45.835 DEBUG> refresh driver node list
22:47:45.835 DEBUG> [control connection] Refreshing node list and token map
22:47:45.861 DEBUG> [control connection] Removing host not found in peers metadata: <Host: 127.204.54.40:9042 datacenter1>
22:47:45.862 DEBUG> [control connection] Finished fetching ring info
22:47:45.862 DEBUG> [control connection] Rebuilding token map due to topology changes
22:47:45.862 DEBUG> RESTClient fetching GET http+unix://api/cluster/running-servers
22:47:45.939 INFO> Group 0 members by Server(1093, 127.204.54.32): {('50e92e34-2182-4f2c-b687-32776f192cdb', True), ('f957057b-7b84-4044-b5a4-d0c62c8c9b96', True), ('e6c9202c-4739-4ff7-aaeb-e3b8dfd32fa5', True)}
22:47:45.939 DEBUG> RESTClient fetching GET http://127.204.54.32:10000/storage_service/tokens_endpoint
22:47:45.958 INFO> Normal endpoints' IPs by Server(1093, 127.204.54.32): {'127.204.54.40', '127.204.54.32', '127.204.54.30'}
22:47:45.958 DEBUG> RESTClient fetching GET http://127.204.54.32:10000/storage_service/host_id
22:47:45.966 INFO> All host IDs by Server(1093, 127.204.54.32): {'50e92e34-2182-4f2c-b687-32776f192cdb', 'e6c9202c-4739-4ff7-aaeb-e3b8dfd32fa5', 'f957057b-7b84-4044-b5a4-d0c62c8c9b96'}
22:47:45.966 INFO> Normal endpoints' host IDs by Server(1093, 127.204.54.32): {'50e92e34-2182-4f2c-b687-32776f192cdb', 'e6c9202c-4739-4ff7-aaeb-e3b8dfd32fa5', 'f957057b-7b84-4044-b5a4-d0c62c8c9b96'}
22:47:46.025 INFO> Group 0 members by Server(1098, 127.204.54.30): {('50e92e34-2182-4f2c-b687-32776f192cdb', True), ('f957057b-7b84-4044-b5a4-d0c62c8c9b96', True), ('e6c9202c-4739-4ff7-aaeb-e3b8dfd32fa5', True)}
22:47:46.025 DEBUG> RESTClient fetching GET http://127.204.54.30:10000/storage_service/tokens_endpoint
22:47:46.043 INFO> Normal endpoints' IPs by Server(1098, 127.204.54.30): {'127.204.54.40', '127.204.54.32', '127.204.54.30'}
22:47:46.044 DEBUG> RESTClient fetching GET http://127.204.54.30:10000/storage_service/host_id
22:47:46.053 INFO> All host IDs by Server(1098, 127.204.54.30): {'50e92e34-2182-4f2c-b687-32776f192cdb', 'e6c9202c-4739-4ff7-aaeb-e3b8dfd32fa5', 'f957057b-7b84-4044-b5a4-d0c62c8c9b96'}
22:47:46.054 INFO> Normal endpoints' host IDs by Server(1098, 127.204.54.30): {'50e92e34-2182-4f2c-b687-32776f192cdb', 'e6c9202c-4739-4ff7-aaeb-e3b8dfd32fa5', 'f957057b-7b84-4044-b5a4-d0c62c8c9b96'}
22:47:46.054 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:47.056 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:48.059 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:49.061 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:50.063 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:51.065 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:52.067 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:53.068 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:54.069 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:55.071 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:56.073 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:57.075 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:58.076 INFO> Driver not connected to 127.204.54.40:9042 yet
22:47:59.077 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:00.079 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:01.080 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:02.082 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:03.083 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:04.085 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:05.086 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:06.088 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:07.090 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:08.092 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:09.093 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:10.094 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:11.095 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:12.097 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:13.098 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:14.100 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:15.102 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:16.104 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:17.105 INFO> Driver not connected to 127.204.54.40:9042 yet
22:48:17.913 DEBUG> Connection 140694068603152 127.0.0.1:39308 -> 127.204.54.40:9042
```

`scheduling retry in 34.56 seconds`, which is more than 30s test timeout. It takes that much time to connect, because the previous connection attempts were rejected by Scylla (it was probably still bootstrapping).

**Comment by kostja** [comment]
@kbr-scylla using CQL is a good idea since as it is dog-fooding developers with the overall user experience. Now we see that our drivers need a better way to learn about topology/schema changes than sleep and retry. *All* drivers, not just the python one.

**Comment by denesb** [comment]
@kbr-scylla please evaluate for backport.

**Comment by kbr-scylla** [comment]
Backported to 5.2
