### ISSUE TITLE
test_replace_reuse_ip fails

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#15115]
seems the symptom of #14885 bites us again:

```
[2023-08-21T16:30:58.512Z] 18:54:13.093 DEBUG> Reconnection error details
[2023-08-21T16:30:58.512Z] Traceback (most recent call last):
[2023-08-21T16:30:58.512Z]   File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
[2023-08-21T16:30:58.512Z]   File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
[2023-08-21T16:30:58.512Z]   File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
[2023-08-21T16:30:58.512Z]   File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
[2023-08-21T16:30:58.512Z]     self._connect_socket()
[2023-08-21T16:30:58.512Z]   File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
[2023-08-21T16:30:58.512Z] ConnectionRefusedError: [Errno 111] Tried connecting to [('127.174.131.18', 9042)]. Last error: Connection refused
[2023-08-21T16:30:58.512Z] 18:54:14.901 WARNING> Error attempting to reconnect to 127.174.131.18:9042, scheduling retry in 3.64 seconds: [Errno 111] Tried connecting to [('127.174.131.18', 9042)]. Last error: Connection refused
...
[2023-08-21T16:30:58.516Z] manager = <test.pylib.manager_client.ManagerClient object at 0x7fcfdf96a910>
[2023-08-21T16:30:58.516Z] 
[2023-08-21T16:30:58.516Z]     @pytest.mark.asyncio
[2023-08-21T16:30:58.516Z]     async def test_replace_reuse_ip(manager: ManagerClient) -> None:
[2023-08-21T16:30:58.516Z]         """Replace an existing node with new node using the same IP address"""
[2023-08-21T16:30:58.516Z]         servers = await manager.running_servers()
[2023-08-21T16:30:58.516Z]         await manager.server_stop(servers[0].server_id)
[2023-08-21T16:30:58.516Z]         replace_cfg = ReplaceConfig(replaced_id = servers[0].server_id, reuse_ip_addr = True, use_host_id = False)
[2023-08-21T16:30:58.516Z]         await manager.server_add(replace_cfg)
[2023-08-21T16:30:58.516Z] >       await wait_for_token_ring_and_group0_consistency(manager, time.time() + 30)
[2023-08-21T16:30:58.516Z] 
[2023-08-21T16:30:58.516Z] test/topology/test_replace.py:41: 
[2023-08-21T16:30:58.516Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2023-08-21T16:30:58.516Z] test/topology/util.py:94: in wait_for_token_ring_and_group0_consistency
[2023-08-21T16:30:58.516Z]     await wait_for(token_ring_matches, deadline, period=.5)
[2023-08-21T16:30:58.516Z] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[2023-08-21T16:30:58.516Z] 
[2023-08-21T16:30:58.516Z] pred = <function wait_for_token_ring_and_group0_consistency.<locals>.token_ring_matches at 0x7fcfdcdeef20>
[2023-08-21T16:30:58.516Z] deadline = 1692633020.8797276, period = 0.5
[2023-08-21T16:30:58.516Z] 
[2023-08-21T16:30:58.516Z]     async def wait_for(
[2023-08-21T16:30:58.516Z]             pred: Callable[[], Awaitable[Optional[T]]],
[2023-08-21T16:30:58.516Z]             deadline: float, period: float = 1) -> T:
[2023-08-21T16:30:58.516Z]         while True:
[2023-08-21T16:30:58.516Z] >           assert(time.time() < deadline), "Deadline exceeded, failing test."
[2023-08-21T16:30:58.516Z] E           AssertionError: Deadline exceeded, failing test.
[2023-08-21T16:30:58.516Z] 
[2023-08-21T16:30:58.516Z] test/pylib/util.py:45: AssertionError
```
see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3160

**Comment by tchaikov** [comment]
[scylla-747.log](https://github.com/scylladb/scylladb/files/12404118/scylla-747.log)
[scylla-713.log](https://github.com/scylladb/scylladb/files/12404120/scylla-713.log)
[scylla-779.log](https://github.com/scylladb/scylladb/files/12404121/scylla-779.log)
[scylla-690.log](https://github.com/scylladb/scylladb/files/12404122/scylla-690.log)
[consoleText.zip](https://github.com/scylladb/scylladb/files/12404128/consoleText.zip)

**Comment by benipeled** [comment]
...same on enterprise build https://jenkins.scylladb.com/job/scylla-enterprise/job/build/990/
```
test/topology/util.py:94: in wait_for_token_ring_and_group0_consistency
    await wait_for(token_ring_matches, deadline, period=.5)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pred = <function wait_for_token_ring_and_group0_consistency.<locals>.token_ring_matches at 0x7fcfdcdeef20>
deadline = 1692633020.8797276, period = 0.5

    async def wait_for(
            pred: Callable[[], Awaitable[Optional[T]]],
            deadline: float, period: float = 1) -> T:
        while True:
>           assert(time.time() < deadline), "Deadline exceeded, failing test."
E           AssertionError: Deadline exceeded, failing test.

test/pylib/util.py:45: AssertionError
```

**Comment by kbr-scylla** [comment]
Will keep happening in enterprise until next master->enterprise merge.
