### ISSUE TITLE
[x86, debug]: topology_raft_disabled.test_raft_upgrade_no_schema.debug: AddressSanitizer: SEGV on unknown address 0x7f619d51b9e8 (pc 0x00000d36d05f bp 0x7fff9fe9bbc0 sp 0x7fff9fe9bb40 T0) 

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#15255]
Failed in https://jenkins.scylladb.com/job/scylla-master/job/next/6467/
```
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3790, in cassandra.cluster.ControlConnection.refresh_node_list_and_token_map
  File "cassandra/cluster.py", line 3816, in cassandra.cluster.ControlConnection._refresh_node_list_and_token_map
  File "cassandra/connection.py", line 1097, in cassandra.connection.Connection.wait_for_responses
cassandra.connection.ConnectionShutdown: Connection <LibevConnection(139836560936848) 127.21.95.23:9042 (closed)> is already closed
15:40:32.815 INFO> Server(1168, 127.21.95.23) restarted
15:40:32.815 DEBUG> [control connection] Attempting to reconnect
15:40:32.815 DEBUG> [control connection] Opening new connection to 127.21.95.53:9042
15:40:32.816 WARNING> [control connection] Error connecting to 127.21.95.53:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3607, in cassandra.cluster.ControlConnection._reconnect_internal
  File "cassandra/cluster.py", line 3629, in cassandra.cluster.ControlConnection._try_connect
  File "cassandra/cluster.py", line 1687, in cassandra.cluster.Cluster.connection_factory
  File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
  File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.21.95.53', 9042)]. Last error: Connection refused
15:40:32.816 DEBUG> [control connection] Opening new connection to 127.21.95.63:9042
15:40:32.817 WARNING> [control connection] Error connecting to 127.21.95.63:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3607, in cassandra.cluster.ControlConnection._reconnect_internal
  File "cassandra/cluster.py", line 3629, in cassandra.cluster.ControlConnection._try_connect
  File "cassandra/cluster.py", line 1687, in cassandra.cluster.Cluster.connection_factory
  File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
  File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.21.95.63', 9042)]. Last error: Connection refused
```
https://jenkins.scylladb.com/job/scylla-master/job/next/6467/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___topology_raft_disabled_test_raft_upgrade_no_schema_debug_3/

**Comment by kbr-scylla** [comment]
https://jenkins.scylladb.com/job/scylla-master/job/next/6467/artifact/testlog/x86_64/debug/scylla-1194.log

```
INFO  2023-09-03 15:40:14,431 [shard 0:main] storage_service - Shutting down native transport server
AddressSanitizer:DEADLYSIGNAL
=================================================================
==247204==ERROR: AddressSanitizer: SEGV on unknown address 0x7f619d51b9e8 (pc 0x00000d36d05f bp 0x7fff9fe9bbc0 sp 0x7fff9fe9bb40 T0)
==247204==The signal is caused by a READ memory access.
    #0 0xd36d05f  (/jenkins/workspace/scylla-master/next/scylla/build/debug/scylla+0xd36d05f) (BuildId: c1d2b6a1c3f20df0a88bf2f97666c83cb5e872ef)
    #1 0xd36ca11  (/jenkins/workspace/scylla-master/next/scylla/build/debug/scylla+0xd36ca11) (BuildId: c1d2b6a1c3f20df0a88bf2f97666c83cb5e872ef)
    #2 0xd36b1ff  (/jenkins/workspace/scylla-master/next/scylla/build/debug/scylla+0xd36b1ff) (BuildId: c1d2b6a1c3f20df0a88bf2f97666c83cb5e872ef)
    #3 0x11e79f98  (/jenkins/workspace/scylla-master/next/scylla/build/debug/scylla+0x11e79f98) (BuildId: c1d2b6a1c3f20df0a88bf2f97666c83cb5e872ef)
    #4 0x11e28063  (/jenkins/workspace/scylla-master/next/scylla/build/debug/scylla+0x11e28063) (BuildId: c1d2b6a1c3f20df0a88bf2f97666c83cb5e872ef)
    #5 0x11dd3fb7  (/jenkins/workspace/scylla-master/next/scylla/build/debug/scylla+0x11dd3fb7) (BuildId: c1d2b6a1c3f20df0a88bf2f97666c83cb5e872ef)
    #6 0x11e4d3a6  (/jenkins/workspace/scylla-master/next/scylla/build/debug/scylla+0x11e4d3a6) (BuildId: c1d2b6a1c3f20df0a88bf2f97666c83cb5e872ef)
    #7 0x7f623195cda8  (/jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x455cda8) (BuildId: 77b048d6cb9de0ce54cdf6b40bc58767d1183ca5)
    #8 0x7f6231964ebe  (/jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x4564ebe) (BuildId: 77b048d6cb9de0ce54cdf6b40bc58767d1183ca5)
    #9 0x7f6231968da0  (/jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x4568da0) (BuildId: 77b048d6cb9de0ce54cdf6b40bc58767d1183ca5)
    #10 0x7f6231966a73  (/jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x4566a73) (BuildId: 77b048d6cb9de0ce54cdf6b40bc58767d1183ca5)
    #11 0x7f62314dab3a  (/jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x40dab3a) (BuildId: 77b048d6cb9de0ce54cdf6b40bc58767d1183ca5)
    #12 0x7f62314d80da  (/jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x40d80da) (BuildId: 77b048d6cb9de0ce54cdf6b40bc58767d1183ca5)
    #13 0xd11fa7b  (/jenkins/workspace/scylla-master/next/scylla/build/debug/scylla+0xd11fa7b) (BuildId: c1d2b6a1c3f20df0a88bf2f97666c83cb5e872ef)
    #14 0xd11c51f  (/jenkins/workspace/scylla-master/next/scylla/build/debug/scylla+0xd11c51f) (BuildId: c1d2b6a1c3f20df0a88bf2f97666c83cb5e872ef)
    #15 0x7f622b731b49  (/lib64/libc.so.6+0x27b49) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
    #16 0x7f622b731c0a  (/lib64/libc.so.6+0x27c0a) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
    #17 0xd0408a4  (/jenkins/workspace/scylla-master/next/scylla/build/debug/scylla+0xd0408a4) (BuildId: c1d2b6a1c3f20df0a88bf2f97666c83cb5e872ef)
```

looks like https://github.com/scylladb/scylladb/issues/15250#issuecomment-1704876715

**Comment by kostja** [comment]
@yaronkaikov could you please give me an update on the frequency of tihs item? If it was a one-off case then I suggest we drop the ci-stability label. The problem itself is a memory corruption during shutdown - only observable during a race. @xemul is actively refactoring the services and fixing the shutdown issues in parallel. Debugging this issue and trying to nail it is not productive - we know there are shutdown dependency bugs, and we're systematically working on reducing the dependency hell.

**Comment by yaronkaikov** [comment]
> @yaronkaikov could you please give me an update on the frequency of tihs item? If it was a one-off case then I suggest we drop the ci-stability label. The problem itself is a memory corruption during shutdown - only observable during a race. @xemul is actively refactoring the services and fixing the shutdown issues in parallel. Debugging this issue and trying to nail it is not productive - we know there are shutdown dependency bugs, and we're systematically working on reducing the dependency hell.

Well, I guess it happened once, normally when we see a failure we look for an open issue based on the test name. and then post a comment with the job it occurs again. 

You can use https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_aarch64_debug/ to run only the relevant group of tests as much as you want (let's say 100 times), and then you will probably be able to reproduce it

**Comment by mykaul** [comment]
We haven't seen it in 2 months - optimistically closing.
