### ISSUE TITLE
Loader fails to read part of data after all DB nodes and sstables upgrade

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylladb#15283]
## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

After the upgrade of all the DB nodes in the `rolling upgrade` CI job from the `5.1.16-0.20230822.eae8a18fa52a with build-id dc5f0f6ab57c847c4ac69e71520176d80b5e44b2` Scylla version to the `5.2.8-0.20230831.455ab99b6cce` we run the `nodetool upgradesstables` command.
It gets finished successfully on all the nodes:
```
2023-09-01 02:53:18,116 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool -u cassandra -pw 'cassandra'  upgradesstables " finished with status 0
...
2023-09-01 02:53:18,150 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool -u cassandra -pw 'cassandra'  upgradesstables " finished with status 0
...
2023-09-01 02:53:18,168 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool -u cassandra -pw 'cassandra'  upgradesstables " finished with status 0
...
2023-09-01 02:53:18,978 f:base.py         l:142  c:RemoteLibSSH2CmdRunner p:DEBUG > Command "/usr/bin/nodetool -u cassandra -pw 'cassandra'  upgradesstables " finished with status 0
```

Then, we run stress to check the data:
```
2023-09-01 02:55:27,974 f:stress_thread.py l:287  c:sdcm.stress_thread   p:INFO  > \
  cassandra-stress read no-warmup cl=ONE n=20100200 -schema \
    'keyspace=keyspace_entire_test replication(factor=3) compression=LZ4Compressor' \
    -mode cql3 native compression=lz4  user=cassandra password=cassandra -rate threads=1000 \
    -pop seq=1..20100200 -log interval=5 -node 10.142.0.237,10.142.0.244,10.142.0.250,10.142.0.252 \
    -errors skip-unsupported-columns
```

and after `~8m` minutes we get following failure in loader logs:
```
total,      16996454,   35971,   35971,   35971,    27.8,    24.4,    60.6,    99.9,   176.6,   220.7,  505.0,  0.06286,      0,      0,       0,       0,       0,       0
java.io.IOException: Operation x0 on key(s) [4e4b35394e4c364e3131]: Data returned was not validated

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
java.io.IOException: Operation x0 on key(s) [383739323230324c4f30]: Data returned was not validated

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
java.io.IOException: Operation x0 on key(s) [4b344d34364c4e4e3930]: Data returned was not validated

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
java.io.IOException: Operation x0 on key(s) [364f4d344b4e35313231]: Data returned was not validated

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
java.io.IOException: Operation x0 on key(s) [4c4b4b39314c334d3431]: Data returned was not validated

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
java.io.IOException: Operation x0 on key(s) [4b333338353732314c30]: Data returned was not validated

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
java.io.IOException: Operation x0 on key(s) [344d4c38323832383630]: Data returned was not validated

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
java.io.IOException: Operation x0 on key(s) [4b50353939384f4c3031]: Data returned was not validated

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
java.io.IOException: Operation x0 on key(s) [34303032353032324d30]: Data returned was not validated

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:469)
total,      17142118,   36360,   36360,   36360,    27.1,    25.2,    55.1,    67.9,   118.4,   140.2,  509.0,  0.06218,      3,      0,       0,       0,       0,       0
FAILURE
java.lang.RuntimeException: Failed to execute stress action
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:101)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
```

SCT runner logs:
```
2023-09-01 02:55:32,786 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > ===== Using optimized driver!!! =====
2023-09-01 03:04:05,009 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2023-09-01 03:04:05.007: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=479fefa8-1eea-4b20-8bcf-731a4022cfc4: type=IOException regex=java\.io\.IOException line_number=205 node=Node rolling-upgrade--ubuntu-focal-loader-node-f4ed059b-0-1 [35.243.226.59 | 10.142.1.22] (seed: False)
2023-09-01 03:04:05,009 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > java.io.IOException: Operation x0 on key(s) [4e4b35394e4c364e3131]: Data returned was not validated
```

This problem is absent if we upgrade from `5.2.7` to `5.2.8`.
This problem got reproduced twice upgrading from `5.1.16` to `5.2.8` - `with` and `without` raft feature.

## Impact

Data breakage?

## How frequently does it reproduce?

2/2

## Installation details

Kernel Version: 5.15.0-1039-gcp
Scylla version (or git commit hash): `5.1.16-20230822.eae8a18fa52a` with build-id `dc5f0f6ab57c847c4ac69e71520176d80b5e44b2`
Target Scylla version (or git commit hash): `5.2.8-20230831.455ab99b6cce` with build-id `a005ab4189e1368da1a31fac941696858b2dbc2e`

Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-f4ed059b-0-4 (35.243.145.104 | 10.142.0.252) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-f4ed059b-0-3 (34.148.31.127 | 10.142.0.250) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-f4ed059b-0-2 (35.227.103.31 | 10.142.0.244) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-f4ed059b-0-1 (104.196.55.2 | 10.142.0.237) (shards: 7)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/scylladb-5-1-16` (gce: us-east1)

Test: `rolling-upgrade-ubuntu22.04-test`
Test id: `f4ed059b-2e75-49a6-a3a5-8b7b71bf14db`
Test name: `scylla-5.2/rolling-upgrade/rolling-upgrade-ubuntu22.04-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/950c559768f8993aaba998e1eafca9acbd9db555/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor f4ed059b-2e75-49a6-a3a5-8b7b71bf14db`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f4ed059b-2e75-49a6-a3a5-8b7b71bf14db)
- Show all stored logs command: `$ hydra investigate show-logs f4ed059b-2e75-49a6-a3a5-8b7b71bf14db`

## Logs:
- **db-cluster-f4ed059b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f4ed059b-2e75-49a6-a3a5-8b7b71bf14db/20230901_031927/db-cluster-f4ed059b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f4ed059b-2e75-49a6-a3a5-8b7b71bf14db/20230901_031927/db-cluster-f4ed059b.tar.gz)
- **sct-runner-events-f4ed059b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f4ed059b-2e75-49a6-a3a5-8b7b71bf14db/20230901_031927/sct-runner-events-f4ed059b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f4ed059b-2e75-49a6-a3a5-8b7b71bf14db/20230901_031927/sct-runner-events-f4ed059b.tar.gz)
- **sct-f4ed059b.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f4ed059b-2e75-49a6-a3a5-8b7b71bf14db/20230901_031927/sct-f4ed059b.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f4ed059b-2e75-49a6-a3a5-8b7b71bf14db/20230901_031927/sct-f4ed059b.log.tar.gz)
- **monitor-set-f4ed059b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f4ed059b-2e75-49a6-a3a5-8b7b71bf14db/20230901_031927/monitor-set-f4ed059b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f4ed059b-2e75-49a6-a3a5-8b7b71bf14db/20230901_031927/monitor-set-f4ed059b.tar.gz)
- **loader-set-f4ed059b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f4ed059b-2e75-49a6-a3a5-8b7b71bf14db/20230901_031927/loader-set-f4ed059b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f4ed059b-2e75-49a6-a3a5-8b7b71bf14db/20230901_031927/loader-set-f4ed059b.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.2/job/rolling-upgrade/job/rolling-upgrade-ubuntu22.04-test/21/)
[Argus](https://argus.scylladb.com/test/b865ee97-3255-4b7f-916f-fead3657d026/runs?additionalRuns[]=f4ed059b-2e75-49a6-a3a5-8b7b71bf14db)
</details>

**Comment by vponomaryov** [comment]
Second job with this bug:

## Installation details

Kernel Version: 5.15.0-1039-gcp
Scylla version (or git commit hash): `5.1.16-20230822.eae8a18fa52a` with build-id `dc5f0f6ab57c847c4ac69e71520176d80b5e44b2`
Target Scylla version (or git commit hash): `5.2.8-20230831.455ab99b6cce` with build-id `a005ab4189e1368da1a31fac941696858b2dbc2e`

Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-jammy-db-node-f19ca7ed-0-4 (34.75.202.66 | 10.142.1.28) (shards: 7)
- rolling-upgrade--ubuntu-jammy-db-node-f19ca7ed-0-3 (34.23.5.139 | 10.142.1.21) (shards: 7)
- rolling-upgrade--ubuntu-jammy-db-node-f19ca7ed-0-2 (34.23.18.91 | 10.142.1.12) (shards: 7)
- rolling-upgrade--ubuntu-jammy-db-node-f19ca7ed-0-1 (35.229.30.217 | 10.142.1.9) (shards: 7)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/scylladb-5-1-16` (gce: us-east1)

Test: `rolling-upgrade-ubuntu22.04-with-raft-test`
Test id: `f19ca7ed-5871-404e-afa8-9ab16e4caf54`
Test name: `scylla-5.2/upgrade-with-raft/rolling-upgrade-ubuntu22.04-with-raft-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/950c559768f8993aaba998e1eafca9acbd9db555/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor f19ca7ed-5871-404e-afa8-9ab16e4caf54`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f19ca7ed-5871-404e-afa8-9ab16e4caf54)
- Show all stored logs command: `$ hydra investigate show-logs f19ca7ed-5871-404e-afa8-9ab16e4caf54`

## Logs:
- **db-cluster-f19ca7ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f19ca7ed-5871-404e-afa8-9ab16e4caf54/20230901_032005/db-cluster-f19ca7ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f19ca7ed-5871-404e-afa8-9ab16e4caf54/20230901_032005/db-cluster-f19ca7ed.tar.gz)
- **sct-runner-events-f19ca7ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f19ca7ed-5871-404e-afa8-9ab16e4caf54/20230901_032005/sct-runner-events-f19ca7ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f19ca7ed-5871-404e-afa8-9ab16e4caf54/20230901_032005/sct-runner-events-f19ca7ed.tar.gz)
- **sct-f19ca7ed.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f19ca7ed-5871-404e-afa8-9ab16e4caf54/20230901_032005/sct-f19ca7ed.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f19ca7ed-5871-404e-afa8-9ab16e4caf54/20230901_032005/sct-f19ca7ed.log.tar.gz)
- **monitor-set-f19ca7ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f19ca7ed-5871-404e-afa8-9ab16e4caf54/20230901_032005/monitor-set-f19ca7ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f19ca7ed-5871-404e-afa8-9ab16e4caf54/20230901_032005/monitor-set-f19ca7ed.tar.gz)
- **loader-set-f19ca7ed.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f19ca7ed-5871-404e-afa8-9ab16e4caf54/20230901_032005/loader-set-f19ca7ed.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f19ca7ed-5871-404e-afa8-9ab16e4caf54/20230901_032005/loader-set-f19ca7ed.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.2/job/upgrade-with-raft/job/rolling-upgrade-ubuntu22.04-with-raft-test/8/)
[Argus](https://argus.scylladb.com/test/83cd18f2-aba2-427b-988b-43618803bcf5/runs?additionalRuns[]=f19ca7ed-5871-404e-afa8-9ab16e4caf54)
</details>

**Comment by DoronArazii** [comment]
java.io.IOException: Operation x0 on key(s) [4e4b35394e4c364e3131]: Data returned was not validated 

@avikivity does it point on data corruption? ^^

**Comment by mykaul** [comment]
@vponomaryov - does the validation code already using https://github.com/scylladb/scylla-cluster-tests/pull/6452 ?

**Comment by vponomaryov** [comment]
> @vponomaryov - does the validation code already using [scylladb/scylla-cluster-tests#6452](https://github.com/scylladb/scylla-cluster-tests/pull/6452) ?

It was reverted after some time here: https://github.com/scylladb/scylla-cluster-tests/pull/6493

And I don't think it is the cause because:

> This problem is absent if we upgrade from `5.2.7` to `5.2.8`.
> This problem got reproduced twice upgrading from `5.1.16` to `5.2.8` - `with` and `without` raft feature.

**Comment by DoronArazii** [comment]
@roydahan ^^

**Comment by roydahan** [comment]
This is a verification step that runs with CL=ONE and make sure that data that was written during entire test with CL=QUORUM (cannot be ALL of course) isn't missing from the cluster after the upgrade.

When some nodes are down during the upgrade, either hinted_handoff or repair should be the way to fix their gap of data.

@vponomaryov IIRC this branch still runs with hinted_handoff enabled in SCT, right?
Also, can you please verify that the test runs repair exactly as written in the documentation? (AFAICT it does).
https://opensource.docs.scylladb.com/stable/upgrade/upgrade-opensource/upgrade-guide-from-5.1-to-5.2/upgrade-guide-from-5.1-to-5.2-generic.html

If both are yes, what are the lastest backports that were done to SCT branch-5.2?
I think the only relevant thing is the upgradesstables fix that now actually does the upgradesstables (if new sstablesversion is available).

If this is the only relevant change, we may have a real problem of a data loss (either during upgradesstables) or problem with procedure that needs to be fixed.

**Comment by roydahan** [comment]
release blocker till proved otherwise.

**Comment by mykaul** [comment]
> When some nodes are down during the upgrade, either hinted_handoff or repair should be the way to fix their gap of data.

Was HH enabled?
Why would read repair run with CL=ONE? Why would there be another repair running?

**Comment by vponomaryov** [comment]
The upgrade from the `5.1.16` version to the `5.2.8` has passed after disabling of the `hinted_handoff` feature: [Argus](https://argus.scylladb.com/test/b097d5bc-5323-4589-aced-0c2396601c9b/runs?additionalRuns[]=64df0be0-48de-43e2-9cc4-51355f0afa24)

**Comment by fgelcer** [comment]
> The upgrade from the `5.1.16` version to the `5.2.8` has passed after disabling of the `hinted_handoff` feature: [Argus](https://argus.scylladb.com/test/b097d5bc-5323-4589-aced-0c2396601c9b/runs?additionalRuns%5B%5D=64df0be0-48de-43e2-9cc4-51355f0afa24)

@mykaul , as i told you, without HH it works, so perhaps the issue is around it?

**Comment by mykaul** [comment]
@roydahan - please follow up on this test as discussed in the build meeting today - when it happens, what CL and so forth. Hints should not change the results.

**Comment by roydahan** [comment]
WIP

**Comment by mykaul** [comment]
Not a release-blocker, @roydahan - please update the bug.

**Comment by roydahan** [comment]
It looks like the issue is not the timing issue as I thought, although there are several things that need to be changed in this test (e.g. change back from ONE to QUORUM).

Main suspect is https://github.com/scylladb/scylla-enterprise/issues/3232, @vponomaryov to verify.

**Comment by vponomaryov** [comment]
> Main suspect is [scylladb/scylla-enterprise#3232](https://github.com/scylladb/scylla-enterprise/issues/3232), @vponomaryov to verify.

Yes, it looks like the IO hiccup like here: https://github.com/scylladb/scylla-enterprise/issues/3232#issuecomment-1662044828 : ![Screenshot from 2023-09-13 19-43-45](https://github.com/scylladb/scylladb/assets/3796058/bc243989-26df-4203-beab-d5103b888e64) 
Even worse, it was on 2 nodes, not just 1 like in previous case.

So, I think, we can close it like the https://github.com/scylladb/scylla-enterprise/issues/3232 and start using `cl=QUORUM` in this scenario instead of the `cl=ONE`.

**Comment by fruch** [comment]
> > Main suspect is [scylladb/scylla-enterprise#3232](https://github.com/scylladb/scylla-enterprise/issues/3232), [@vponomaryov](https://github.com/vponomaryov) to verify.
> 
> Yes, it looks like the IO hiccup like here: [scylladb/scylla-enterprise#3232 (comment)](https://github.com/scylladb/scylla-enterprise/issues/3232#issuecomment-1662044828) : ![Screenshot from 2023-09-13 19-43-45](https://github.com/scylladb/scylladb/assets/3796058/bc243989-26df-4203-beab-d5103b888e64) Even worse, it was on 2 nodes, not just 1 like in previous case.
> 
> So, I think, we can close it like the [scylladb/scylla-enterprise#3232](https://github.com/scylladb/scylla-enterprise/issues/3232) and start using `cl=QUORUM` in this scenario instead of the `cl=ONE`.

@vponomaryov @roydahan, was that ever changed from ONE to QUORUM ? cause I've run into the exact same thing in this week runs.

**Comment by roydahan** [comment]
> > > Main suspect is [scylladb/scylla-enterprise#3232](https://github.com/scylladb/scylla-enterprise/issues/3232), [@vponomaryov](https://github.com/vponomaryov) to verify.
> > 
> > 
> > Yes, it looks like the IO hiccup like here: [scylladb/scylla-enterprise#3232 (comment)](https://github.com/scylladb/scylla-enterprise/issues/3232#issuecomment-1662044828) : ![Screenshot from 2023-09-13 19-43-45](https://github.com/scylladb/scylladb/assets/3796058/bc243989-26df-4203-beab-d5103b888e64) Even worse, it was on 2 nodes, not just 1 like in previous case.
> > So, I think, we can close it like the [scylladb/scylla-enterprise#3232](https://github.com/scylladb/scylla-enterprise/issues/3232) and start using `cl=QUORUM` in this scenario instead of the `cl=ONE`.
> 
> [@vponomaryov](https://github.com/vponomaryov) [@roydahan](https://github.com/roydahan), was that ever changed from ONE to QUORUM ? cause I've run into the exact same thing in this week runs.

Yes.
Maybe you have actual data issue?

**Comment by fruch** [comment]
> > > > Main suspect is [scylladb/scylla-enterprise#3232](https://github.com/scylladb/scylla-enterprise/issues/3232), [@vponomaryov](https://github.com/vponomaryov) to verify.
> > > 
> > > 
> > > Yes, it looks like the IO hiccup like here: [scylladb/scylla-enterprise#3232 (comment)](https://github.com/scylladb/scylla-enterprise/issues/3232#issuecomment-1662044828) : ![Screenshot from 2023-09-13 19-43-45](https://github.com/scylladb/scylladb/assets/3796058/bc243989-26df-4203-beab-d5103b888e64) Even worse, it was on 2 nodes, not just 1 like in previous case.
> > > So, I think, we can close it like the [scylladb/scylla-enterprise#3232](https://github.com/scylladb/scylla-enterprise/issues/3232) and start using `cl=QUORUM` in this scenario instead of the `cl=ONE`.
> > 
> > 
> > [@vponomaryov](https://github.com/vponomaryov) [@roydahan](https://github.com/roydahan), was that ever changed from ONE to QUORUM ? cause I've run into the exact same thing in this week runs.
> 
> Yes. Maybe you have actual data issue?

I'm quite sure I have a run with ONE, while the writes are with QUORUM
I think what mentioned here in this issue was forgotten, and never changed in SCT

**Comment by vponomaryov** [comment]
History of changes to this config says that CL was not changed from ONE to QUORUM.

**Comment by fruch** [comment]
> History of changes to this config says that CL was not changed from ONE to QUORUM.

Yes it seems like it was forgotten,

Let's do that change

**Comment by vponomaryov** [comment]
> > History of changes to this config says that CL was not changed from ONE to QUORUM.
> 
> Yes it seems like it was forgotten,
> 
> Let's do that change

- https://github.com/scylladb/scylla-cluster-tests/pull/10573

**Comment by fruch** [comment]
merged the fix, and backporting it to  SCT 2025.1
