### ISSUE TITLE
[dtest]  test_multi_mvs_on_different_base_tables fail to flush [failed: data_dictionary::no_such_column_family]

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#15315]
materialized_views_test.TestMaterializedViews.test_multi_mvs_on_different_base_tables failed next

during test preparation `_prefill_base_tables` is being called in multiple threads,
and flush all nodes after each table creation, and fails like that:
```
self = <materialized_views_test.TestMaterializedViews object at 0x7f45f72f9b50>

    @pytest.mark.scylla_mode('!debug')
    def test_multi_mvs_on_different_base_tables(self):
        """ Few keyspaces and every keyspace has a few tables and every table has a few MVs.
            MVs are created on the empty base tables
        """
>       self._multi_mvs_on_different_base_tables_multi_ks(rf=3, tables=3, mvs=4, prefill_start=10000,
                                                          increase_rows=10, populated_table=False)

materialized_views_test.py:1198: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
materialized_views_test.py:1220: in _multi_mvs_on_different_base_tables_multi_ks
    run_in_parallel(proc_functions)
tools/data.py:241: in run_in_parallel
    results = [task.result() for task in tasks]
tools/data.py:241: in <listcomp>
    results = [task.result() for task in tasks]
/usr/lib64/python3.11/concurrent/futures/_base.py:449: in result
    return self.__get_result()
/usr/lib64/python3.11/concurrent/futures/_base.py:401: in __get_result
    raise self._exception
/usr/lib64/python3.11/concurrent/futures/thread.py:58: in run
    result = self.fn(*self.args, **self.kwargs)
materialized_views_test.py:1246: in _multi_mvs_on_different_base_tables
    func()
materialized_views_test.py:1226: in _prefill_base_tables
    base_table.prefill_table(prefill)
tools/tables_view_manager.py:214: in prefill_table
    flush_by_node(self.cluster)
tools/misc.py:300: in flush_by_node
    node.flush()
../scylla/.local/lib/python3.11/site-packages/ccmlib/scylla_node.py:1303: in flush
    super(ScyllaNode, self).flush(ks, table, **kwargs)
../scylla/.local/lib/python3.11/site-packages/ccmlib/node.py:1367: in flush
    self.nodetool(cmd, **kwargs)
../scylla/.local/lib/python3.11/site-packages/ccmlib/scylla_node.py:754: in nodetool
    return super().nodetool(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ccmlib.scylla_node.ScyllaNode object at 0x7f45dc6f0190>, cmd = 'flush'
capture_output = True, wait = True, timeout = None, verbose = True

    def nodetool(self, cmd, capture_output=True, wait=True, timeout=None, verbose=True):
        """
        Setting wait=False makes it impossible to detect errors,
        if capture_output is also False. wait=False allows us to return
        while nodetool is still running.
        When wait=True, timeout may be set to a number, in seconds,
        to limit how long the function will wait for nodetool to complete.
        """
        if capture_output and not wait:
            raise common.ArgumentError("Cannot set capture_output while wait is False.")
        env = self.get_env()
        if self.is_scylla() and not self.is_docker():
            host = self.address()
        else:
            host = 'localhost'
        nodetool = self.get_tool('nodetool')
    
        if not isinstance(nodetool, list):
            nodetool = [nodetool]
        # see https://www.oracle.com/java/technologies/javase/8u331-relnotes.html#JDK-8278972
        nodetool.extend(['-h', host, '-p', str(self.jmx_port), '-Dcom.sun.jndi.rmiURLParsing=legacy'])
        nodetool.extend(cmd.split())
        if verbose:
            self.debug(f"nodetool cmd={cmd} wait={wait} timeout={timeout}")
        if capture_output:
            p = subprocess.Popen(nodetool, universal_newlines=True, env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            stdout, stderr = p.communicate(timeout=timeout)
        else:
            p = subprocess.Popen(nodetool, env=env, universal_newlines=True)
            stdout, stderr = None, None
    
        if wait:
            exit_status = p.wait(timeout=timeout)
            if exit_status != 0:
>               raise NodetoolError(" ".join(nodetool), exit_status, stdout, stderr)
E               ccmlib.node.ToolError: Subprocess /jenkins/workspace/scylla-master/gating-dtest-release/scylla/.ccm/scylla-repository/c52e0fd333962e54bde311cfc9636febb42fc0f4/share/cassandra/bin/nodetool -h 127.0.23.2 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy flush exited with non-zero status; exit status: 2; 
E               stderr: error: Scylla API server HTTP POST to URL '/storage_service/keyspace_flush/ks' failed: data_dictionary::no_such_column_family (Can't find a column family with UUID 4afbf810-4d55-11ee-a760-bc6c2a738bf7)
E               -- StackTrace --
E               java.lang.IllegalStateException: Scylla API server HTTP POST to URL '/storage_service/keyspace_flush/ks' failed: data_dictionary::no_such_column_family (Can't find a column family with UUID 4afbf810-4d55-11ee-a760-bc6c2a738bf7)
E               	at com.scylladb.jmx.api.APIClient.getException(APIClient.java:140)
E               	at com.scylladb.jmx.api.APIClient.post(APIClient.java:120)
E               	at com.scylladb.jmx.api.APIClient.post(APIClient.java:130)
E               	at com.scylladb.jmx.api.APIClient.post(APIClient.java:113)
E               	at org.apache.cassandra.service.StorageService.forceKeyspaceFlush(StorageService.java:731)
E               	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E               	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E               	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E               	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
E               	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
E               	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
E               	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E               	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
E               	at java.base/sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:260)
E               	at java.management/com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
E               	at java.management/com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
E               	at java.management/com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
E               	at java.management/com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
E               	at java.management/com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
E               	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809)
E               	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
E               	at com.scylladb.jmx.utils.APIMBeanServer.invoke(APIMBeanServer.java:188)
E               	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466)
E               	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
E               	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
E               	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:827)
E               	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E               	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E               	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E               	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
E               	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
E               	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
E               	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
E               	at java.base/java.security.AccessController.doPrivileged(Native Method)
E               	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
E               	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
E               	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
E               	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
E               	at java.base/java.security.AccessController.doPrivileged(Native Method)
E               	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
E               	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
E               	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
E               	at java.base/java.lang.Thread.run(Thread.java:829)

../scylla/.local/lib/python3.11/site-packages/ccmlib/node.py:802: ToolError
```
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4318/testReport/junit/materialized_views_test/TestMaterializedViews/FullDtest___full_split011___test_multi_mvs_on_different_base_tables/

### Logs
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4318/artifact/logs-full.release.011

Test failed like that only 2, since we having information in elastic:
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/bd6590d0-4d70-11ee-b96a-256b7e8b2261

**Comment by fruch** [comment]
I'm guessing it's not safe to create a table, and flush it on all nodes, since some node might not have it yet.

I'm guessing we need to wait for schema agreement first, while problematic, since thing are running in parallel.

options:
1) flush all 
2) retry few time on failures
3) switch to do the flush by api (not nodetool) - with retries

**Comment by fruch** [comment]
> I'm guessing it's not safe to create a table, and flush it on all nodes, since some node might not have it yet.
> 
> I'm guessing we need to wait for schema agreement first, while problematic, since thing are running in parallel.
> 
> options:
> 
> 1. flush all
> 2. retry few time on failures
> 3. switch to do the flush by api (not nodetool) - with retries

I'm taking it all back, flush is not done on specific keyspace:

```
def flush_by_node(cluster):
    for node in cluster.nodelist():
        node.flush()
```

so I don't expect it to fail like that...

**Comment by fruch** [comment]
this is MV that is missing on node-2:
```
INFO  2023-09-07 08:05:22,068 [shard 0:stat] schema_tables - Creating ks.tm_table2_mv_1 id=4afbf810-4d55-11ee-a760-bc6c2a738bf7 version=35967735-3610-3684-9dc2-f44d52687c28
```

**Comment by fruch** [comment]
Node2, not sure which of those were failing, but I'm guess we might have those running in parallel: 
```
INFO  2023-09-07 08:05:41,406 [shard 0:stre] api - perform_keyspace_flush: keyspace=ks tables={}
...
INFO  2023-09-07 08:05:41,597 [shard 0:stre] api - perform_keyspace_flush: keyspace=ks tables={}
...
INFO  2023-09-07 08:05:46,430 [shard 0:stre] api - perform_keyspace_flush: keyspace=ks tables={}
...
```

is `nodetool flush` safe to run in parallel ?

**Comment by mykaul** [comment]
@bhalevy - I think your team is looking into this (https://github.com/scylladb/scylladb/issues/15048 ?)

**Comment by bhalevy** [comment]
> @bhalevy - I think your team is looking into this (#15048 ?)

yes, correct

**Comment by mykaul** [comment]
@bhalevy - https://github.com/scylladb/scylladb/issues/15048 was not touched for a while and neither is this one.

**Comment by bhalevy** [comment]
> @bhalevy - #15048 was not touched for a while and neither is this one.

@mykaul this issue is unassigned.
Not sure if it even reproduced.

**Comment by mykaul** [comment]
I don't mind closing for the time being - we'll open if we see it again (although the 'no such column family' was seen elsewhere here and there).

**Comment by kostja** [comment]
@fruch is raft on or off for schema changes?

**Comment by fruch** [comment]
> @fruch is raft on or off for schema changes?

I don't know, and the logs of both tests failing with it are gone
