### ISSUE TITLE
cql_server - exception while processing connection: std::system_error (error system:107 ...

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#15462]
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/370/artifact/logs-full.release.000/dtest-gw3.log
`test_request_too_large[SSL]` timed out

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/370/artifact/logs-full.release.000/orphaned/dtest-_26ykelx/node1.log:

      INFO  2023-09-17 20:06:07,568 [shard 1:stat] cql_server - exception while processing connection: std::system_error (error system:107, Transport endpoint is not connected)

**Comment by xemul** [comment]
While processing connection EPIPE and ECONNRESET are explicitly ignored, because socket can validly close in the middle of processing. ENOTCONN this time, I wonder if it's from read/write of the socket or some maintenance syscall crept in

**Comment by xemul** [comment]
That's very weird. If the socket was connect()-ed or accept()-ed then close()-d then read-from, the EBADFD is returned.

**Comment by xemul** [comment]
A-ah, tls sockets explicitly return ENOTCON from put() if the socket was shutdown. So it can be that
* connection is shutdown
* some background woken-up task gets to the cpu and tries to push back the response
* ENOTCON is reported

**Comment by xemul** [comment]
I would say that tls sockets should mimic the behavior of TCP and return EPIPE, not ENOTCON

**Comment by bhalevy** [comment]
@xemul can this explain the timeout in https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/395/artifact/logs-full.release.000/dtest-gw4.log?
```
[many repetitions of the following]
02:36:25,715 793     cassandra.cluster              WARNING  thread.py           :58   | test_request_too_large[SSL]: [control connection] Error connecting to 127.0.26.1:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3607, in cassandra.cluster.ControlConnection._connect_host_in_lbp
  File "cassandra/cluster.py", line 3653, in cassandra.cluster.ControlConnection._try_connect
  File "cassandra/cluster.py", line 1689, in cassandra.cluster.Cluster.connection_factory
  File "cassandra/connection.py", line 885, in cassandra.connection.Connection.factory
cassandra.OperationTimedOut: errors=Timed out creating connection (5 seconds), last_host=None
02:36:29,527 793     errors                         ERROR    conftest.py         :226  | test_request_too_large[SSL]: test failed: 
self = <limits_test.TestLimits object at 0x7f2a86806090>, mode = 'SSL'

    @pytest.mark.parametrize("mode", ["SSL", "non-SSL"])
    def test_request_too_large(self, mode):
        """
        The request is considered as "too large" if it takes more than 10% of shard's memory.
        The test scenario is following:
        1. Create node with 2 shards and 1GB of memory (512MB per shard). In this case ~50MB will be reserved for CQL
        requests.
        2. Create a new keyspace and a new table.
        3. Generate a too large request: try to insert a 30MB string into the table. The memory size for the request
        is equal to 2 * (raw size) + 8KB. So the 30MB request will require about 60MB memory.
        4. Check the exception was raised.
        5. Create a new session and check the table is still empty.
        6. Try to send a regular size request (insert a small string).
        7. Check the string was inserted into the table
        """
        if mode == "SSL":
            cluster_populate = self.populate_cluster_with_ssl_enabled
            create_session = self.create_cql_session_with_ssl
        else:
            cluster_populate = self.prepare().populate
            create_session = self.patient_cql_connection
    
        logger.debug("Preparing the cluster...")
        cluster = cluster_populate(1)
        cluster.start(jvm_args=['--smp', '2', '--memory', '1G'])
        logger.debug("Cluster has been prepared...")
        node = cluster.nodelist()[0]
    
        session = create_session(node)
    
        logger.debug("Creating a keyspace...")
        create_ks(session=session, name="test_keyspace", rf=1)
    
        logger.debug("Creating a table...")
        session.execute("create table test_keyspace.test_table("
                        "id int primary key, "
                        "test_string text);")
    
        logger.info("Trying to send a large request to database (insert a large string into table)...")
        long_string = "scylla" * 5 * 1024 * 1024
        id_value = 17
        expected_error = f"Could not write mutation test_keyspace:test_table.*std::invalid_argument.*Mutation.*is too large"
        self.ignore_log_patterns.append(expected_error)
        with pytest.raises((NoHostAvailable, WriteFailure)):
>           session.execute(query=f"insert into test_keyspace.test_table (id, test_string) "
                                  f"values ({id_value}, '{long_string}');")

limits_test.py:383: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cassandra/cluster.py:2708: in cassandra.cluster.Session.execute
    ???
cassandra/cluster.py:5044: in cassandra.cluster.ResponseFuture.result
    ???
/usr/lib64/python3.11/threading.py:622: in wait
    signaled = self._cond.wait(timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Condition(<unlocked _thread.lock object at 0x7f2a76e62480>, 0)>
timeout = None

    def wait(self, timeout=None):
        """Wait until notified or until a timeout occurs.
    
        If the calling thread has not acquired the lock when this method is
        called, a RuntimeError is raised.
    
        This method releases the underlying lock, and then blocks until it is
        awakened by a notify() or notify_all() call for the same condition
        variable in another thread, or until the optional timeout occurs. Once
        awakened or timed out, it re-acquires the lock and returns.
    
        When the timeout argument is present and not None, it should be a
        floating point number specifying a timeout for the operation in seconds
        (or fractions thereof).
    
        When the underlying lock is an RLock, it is not released using its
        release() method, since this may not actually unlock the lock when it
        was acquired multiple times recursively. Instead, an internal interface
        of the RLock class is used, which really unlocks it even when it has
        been recursively acquired several times. Another internal interface is
        then used to restore the recursion level when the lock is reacquired.
    
        """
        if not self._is_owned():
            raise RuntimeError("cannot wait on un-acquired lock")
        waiter = _allocate_lock()
        waiter.acquire()
        self._waiters.append(waiter)
        saved_state = self._release_save()
        gotit = False
        try:    # restore state no matter what (e.g., KeyboardInterrupt)
            if timeout is None:
>               waiter.acquire()
E               Failed: Timeout >2700.0s

/usr/lib64/python3.11/threading.py:320: Failed
```

Node log wasn't collected.

**Comment by xemul** [comment]
@bhalevy , I don't think so. The fix is to silence the benign exception in generic_server, timeouts are of different ... nature

**Comment by bhalevy** [comment]
@fruch on slack:
> again from my finding it seems to be happening when using latest TLS version for the client
> there a deadlock happening inside the driver, and we don't know the root casue yet
> it's not realted, this print happens also when the test passes

**Comment by fruch** [comment]
yes this change sound very related to what's going on in
https://github.com/scylladb/python-driver/issues/261

@xemul is this seastar fix in scylla master already ?

**Comment by xemul** [comment]
@fruch , it's not yet in scylla master
