### ISSUE TITLE
scylla_setup failing on kernel check

### ISSUE THREAD

**Issue by stefanofornari** [scylladb/scylladb#15556]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.2
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04
Linux xxxx 6.2.6-76060206-generic #202303130630~1679424972~22.04~4a8cde1 SMP PREEMPT_DYNAMIC Tue M x86_64 x86_64 x86_64 GNU/Linux
Platform (physical/VM/cloud instance type/docker): physical
Hardware:
```
$ lscpu
Architecture:           x86_64
  CPU op-mode(s):       32-bit, 64-bit
  Address sizes:        36 bits physical, 48 bits virtual
  Byte Order:           Little Endian
CPU(s):                 2
  On-line CPU(s) list:  0,1
Vendor ID:              GenuineIntel
  Model name:           Intel(R) Atom(TM) CPU D425   @ 1.80GHz
    CPU family:         6
    Model:              28
    Thread(s) per core: 2
    Core(s) per socket: 1
    Socket(s):          1
    Stepping:           10
    BogoMIPS:           3590.94
    Flags:              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl cpuid aperfmp
                        erf pni dtes64 monitor ds_cpl tm2 ssse3 cx16 xtpr pdcm movbe lahf_lm dtherm
Caches (sum of all):    
  L1d:                  24 KiB (1 instance)
  L1i:                  32 KiB (1 instance)
  L2:                   512 KiB (1 instance)
NUMA:                   
  NUMA node(s):         1
  NUMA node0 CPU(s):    0,1
Vulnerabilities:        
  Itlb multihit:        Not affected
  L1tf:                 Not affected
  Mds:                  Not affected
  Meltdown:             Not affected
  Mmio stale data:      Not affected
  Retbleed:             Not affected
  Spec store bypass:    Not affected
  Spectre v1:           Not affected
  Spectre v2:           Not affected
  Srbds:                Not affected
  Tsx async abort:      Not affected
```

```
$ lsmem
RANGE                                 SIZE  STATE REMOVABLE BLOCK
0x0000000000000000-0x000000007fffffff   2G online       yes  0-15

Memory block size:       128M
Total online memory:       2G
Total offline memory:      0B
```

Disks: (SSD/HDD, count)
```
$ df -k
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sda1      235121772 49600136 173505244  23% /
```

The problem is when running scylla_setup:

```
$ sudo scylla_setup
Skip any of the following steps by answering 'no'
Do you want to run check your kernel version?
Yes - runs a  script to verify that the kernel for this instance qualifies to run Scylla. No - skips the kernel check.
[YES/no]
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_kernel_check", line 27, in <module>
    run('mount /var/tmp/kernel-check.img /var/tmp/mnt -o loop', shell=True, check=True, stdout=DEVNULL, stderr=DEVNULL)
  File "/opt/scylladb/python3/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'mount /var/tmp/kernel-check.img /var/tmp/mnt -o loop' returned non-zero exit status 32.
Debug log created: /var/tmp/scylla/scylla_kernel_check-1164154-debug.log
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_setup", line 331, in <module>
    run('{}/scylla_kernel_check'.format(scriptsdir()), shell=True, check=True)
  File "/opt/scylladb/python3/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/opt/scylladb/scripts/scylla_kernel_check' returned non-zero exit status 1.
Debug log created: /var/tmp/scylla/scylla_setup-1164146-debug.log
```
attached the log

**Comment by mykaul** [comment]
The code in this script is very simple, I wonder if you can do the flow manually, and see where it breaks:
```
mkdir -p /var/tmp/mnt
dd if=/dev/zero of=/var/tmp/kernel-check.img bs=1M count=128
mkfs.xfs /var/tmp/kernel-check.img
mount /var/tmp/kernel-check.img /var/tmp/mnt -o loop
```

It seems to fail the mount. Regretfully, 'mount' command is not very friendly and 32 is an elusive error code ('mount failure').

**Comment by stefanofornari** [comment]
Hi @mykaul ,
you are right, the mount is failing:

```
$ mkdir -p /var/tmp/mnt
$ sudo dd if=/dev/zero of=/var/tmp/kernel-check.img bs=1M count=128
128+0 records in
128+0 records out
134217728 bytes (134 MB, 128 MiB) copied, 2.99169 s, 44.9 MB/s
$ sudo mkfs.xfs /var/tmp/kernel-check.img
meta-data=/var/tmp/kernel-check.img isize=512    agcount=4, agsize=8192 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=1, rmapbt=0
         =                       reflink=1    bigtime=0 inobtcount=0
data     =                       bsize=4096   blocks=32768, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=4096   blocks=1368, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
$ sudo mount /var/tmp/kernel-check.img /var/tmp/mnt -o loop
mount: /var/tmp/mnt: unknown filesystem type 'xfs'.
```

**Comment by mykaul** [comment]
Thanks @stefanofornari - so for some reason, your kernel does not have XFS support, which is kinda odd. There is a setting for it ('CONFIG_XFS_FS') in the kernel config, so it is optional, but still very common.

**Comment by stefanofornari** [comment]
I guess one more think to check :)

Any way I can fix it without diverging from the distribution?

**Comment by mykaul** [comment]
> I guess one more think to check :)
> 
> Any way I can fix it without diverging from the distribution?

We trust and use XFS... You could probably skip this check, and use ext4 for your use case.

**Comment by stefanofornari** [comment]
ok, saying 'no' to all checks I still get a odd error:

```
$ sudo scylla_setup
Skip any of the following steps by answering 'no'
Do you want to run check your kernel version?
Yes - runs a  script to verify that the kernel for this instance qualifies to run Scylla. No - skips the kernel check.
[YES/no]no
Do you want to verify the ScyllaDB packages are installed?
Yes - runs a script to confirm that ScyllaDB is installed. No - skips the installation check.
[YES/no]no
Do you want the Scylla server service to automatically start when the Scylla node boots?
Yes - Scylla server service automatically starts on Scylla node boot. No - skips this step. Note you will have to start the Scylla Server service manually.
[YES/no]no
Command 'scylla --version' returned non-zero exit status: 132
----------  stdout  ----------
------------------------------
----------  stderr  ----------
Illegal instruction (core dumped)
------------------------------
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_setup", line 370, in <module>
    cur_version=out('scylla --version')
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/scripts/scylla_util.py", line 52, in out
    res.check_returncode()
  File "/opt/scylladb/python3/lib64/python3.11/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command 'scylla --version' returned non-zero exit status 132.
Debug log created: /var/tmp/scylla/scylla_setup-1171010-debug.log

```

Let me know if I can be of any help.

**Comment by mykaul** [comment]
What do you see when running 'scylla --version' manually (assuming it's installed well) ? Anything on the log?
But before that - did you manually installed the packages?

**Comment by stefanofornari** [comment]
I installed the package following the instructions here: https://www.scylladb.com/download/#open-source pickering Ubuntu 20.04 and Scylla 5.3.This is what I get running the command manually:

```
$ sudo scylla --version
Illegal instruction
```
which log should I look at?

**Comment by mykaul** [comment]
That's a crash. I'm not sure what platform (CPU? Something unique about 'Intel(R) Atom(TM) CPU D425' ?) your platform is, but I suspect Scylla isn't compatible with it. Can you try running it with 'strace' to see where it breaks perhaps? (or gdb) ? Perhaps a missing library?
5.3 is not a released version - I'd try with 5.2.

**Comment by stefanofornari** [comment]
My bad, the version is 5.1 (I guess) I just followed exactly the instructions here:

https://www.scylladb.com/download/?platform=ubuntu-18.04&version=scylla-5.1#open-source

Attached the strace.

[out.txt](https://github.com/scylladb/scylladb/files/12776880/out.txt)

**Comment by mykaul** [comment]
@avikivity - any ideas?
```
openat(AT_FDCWD, "/sys/devices/system/node/node0/meminfo", O_RDONLY) = 4
newfstatat(4, "", {st_mode=S_IFREG|0444, st_size=4096, ...}, AT_EMPTY_PATH) = 0
read(4, "Node 0 MemTotal:        1996772 "..., 4096) = 1243
read(4, "", 4096)                       = 0
close(4)                                = 0
getdents64(3, 0x600000190030 /* 0 entries */, 32768) = 0
close(3)                                = 0
sched_getaffinity(0, 512, [0, 1])       = 8
openat(AT_FDCWD, "/sys/devices/system/cpu/possible", O_RDONLY|O_CLOEXEC) = 3
read(3, "0-1\n", 1024)                  = 4
close(3)                                = 0
openat(AT_FDCWD, "/proc/self/status", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0444, st_size=0, ...}, AT_EMPTY_PATH) = 0
read(3, "Name:\tscylla\nUmask:\t0002\nState:\t"..., 1024) = 1024
read(3, "_allowed:\t3\nCpus_allowed_list:\t0"..., 1024) = 419
read(3, "", 1024)                       = 0
close(3)                                = 0
rt_sigaction(SIGILL, {sa_handler=0x7fa966012440, sa_mask=[ILL], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fa96485fb20}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigaction(SIGILL, {sa_handler=SIG_DFL, sa_mask=[ILL], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fa96485fb20}, {sa_handler=0x7fa966012440, sa_mask=[ILL], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fa96485fb20}, 8) = 0
rt_sigaction(SIGILL, {sa_handler=0x7fa966012440, sa_mask=[ILL], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fa96485fb20}, {sa_handler=SIG_DFL, sa_mask=[ILL], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fa96485fb20}, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigaction(SIGILL, {sa_handler=SIG_DFL, sa_mask=[ILL], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fa96485fb20}, {sa_handler=0x7fa966012440, sa_mask=[ILL], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fa96485fb20}, 8) = 0
rt_sigaction(SIGILL, {sa_handler=0x7fa966012440, sa_mask=[ILL], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fa96485fb20}, {sa_handler=SIG_DFL, sa_mask=[ILL], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fa96485fb20}, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigaction(SIGILL, {sa_handler=SIG_DFL, sa_mask=[ILL], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fa96485fb20}, {sa_handler=0x7fa966012440, sa_mask=[ILL], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fa96485fb20}, 8) = 0
uname({sysname="Linux", nodename="campanile", ...}) = 0
uname({sysname="Linux", nodename="campanile", ...}) = 0
getrandom("\xda\xd3\xe4\x94\xad\x97\x4b\xbe", 8, GRND_NONBLOCK) = 8
brk(NULL)                               = 0x7742000
brk(0x7763000)                          = 0x7763000
uname({sysname="Linux", nodename="campanile", ...}) = 0
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPN, si_addr=0x5262a5a} ---
+++ killed by SIGILL (core dumped) +++
Illegal instruction (core dumped)
```
