### ISSUE TITLE
[debug, aarch64]: topology_experimental_raft.test_raft_cluster_features is Flaky

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#15601]
Seen during my debug sessions in 
https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_aarch64_debug/1/console

```
01:52:06  23:52:33.408 DEBUG> Closing connection (281472352556496) to 127.202.61.1:9042
01:52:06  23:52:33.408 DEBUG> Closed socket to 127.202.61.1:9042
01:52:06  23:52:33.754 WARNING> Error attempting to reconnect to 127.202.61.12:9042, scheduling retry in 2.3 seconds: [Errno 111] Tried connecting to [('127.202.61.12', 9042)]. Last error: Connection refused
01:52:06  23:52:33.754 DEBUG> Reconnection error details
01:52:06  Traceback (most recent call last):
01:52:06    File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
01:52:06    File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
01:52:06    File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
01:52:06    File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
01:52:06      self._connect_socket()
01:52:06    File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
01:52:06  ConnectionRefusedError: [Errno 111] Tried connecting to [('127.202.61.12', 9042)]. Last error: Connection refused
01:52:06  23:52:36.057 WARNING> Error attempting to reconnect to 127.202.61.12:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.202.61.12', 9042)]. Last error: Connection refused
01:52:06  23:52:36.058 DEBUG> Reconnection error details
01:52:06  Traceback (most recent call last):
01:52:06    File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
01:52:06    File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
01:52:06    File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
01:52:06    File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
01:52:06      self._connect_socket()
01:52:06    File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
01:52:06  ConnectionRefusedError: [Errno 111] Tried connecting to [('127.202.61.12', 9042)]. Last error: Connection refused
01:52:06  23:52:40.061 WARNING> Error attempting to reconnect to 127.202.61.12:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.202.61.12', 9042)]. Last error: Connection refused
01:52:06  23:52:40.061 DEBUG> Reconnection error details
01:52:06  Traceback (most recent call last):
01:52:06    File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
01:52:06    File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
01:52:06    File "cassandra/connection.py", line 875, in cassandra.connection.Connection.factory
01:52:06    File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
01:52:06      self._connect_socket()
01:52:06    File "cassandra/connection.py", line 954, in cassandra.connection.Connection._connect_socket
01:52:06  ConnectionRefusedError: [Errno 111] Tried connecting to [('127.202.61.12', 9042)]. Last error: Connection refused
```

Full log: [here](https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_aarch64_debug/1/console)

**Comment by yaronkaikov** [comment]
We must decide whether to fix those tests or remove them from gating. We are trying to get aarch64 build and test our gating (scylladb/scylla-pkg#3521), but we need build to be stable before

/cc @mykaul @roydahan @kostja @bhalevy @avikivity

**Comment by kbr-scylla** [comment]
Logs are missing.
But I guess it's the same ASAN crash i.e. duplicate of https://github.com/scylladb/scylladb/issues/15389.

**Comment by avikivity** [comment]
Closing as duplicate of #15389
