### ISSUE TITLE
after changing topology system.peer and token ring of a node get out sync

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#15624]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

After `disrupt_grow_shrink_cluster` nemesis

node-4 sees node-8 as UJ in `nodetool status`, while other nodes sees it as UN
```
2023-09-23 05:30:52.365: (ClusterHealthValidatorEvent Severity.CRITICAL) period_type=one-time event_id=90a3813b-7299-4d36-ad2c-040ca11df030: type=NodeStatus node=longevity-tls-50gb-3d-master-db-node-8fc19eda-4 error=Current node Node longevity-tls-50gb-3d-master-db-node-8fc19eda-4 [34.243.121.198 | 10.4.8.34] (seed: True). Node Node longevity-tls-50gb-3d-master-db-node-8fc19eda-8 [3.250.198.73 | 10.4.9.240] (seed: True) (not target node) status is UJ
```

while gossip it shows as NORAML:

```
2023-09-23 05:30:52.366: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=817c1357-255a-4b2e-9d42-8a27b69ae874: type=NodeStatus node=longevity-tls-50gb-3d-master-db-node-8fc19eda-4 error=Current node Node longevity-tls-50gb-3d-master-db-node-8fc19eda-4 [34.243.121.198 | 10.4.8.34] (seed: True). Wrong node status. Node Node longevity-tls-50gb-3d-master-db-node-8fc19eda-8 [3.250.198.73 | 10.4.9.240] (seed: True) status in nodetool.status is UJ, but status in gossip NORMAL
```
and

```
2023-09-23 05:30:52.367: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=ae4235ef-0ebb-4623-bfcd-9ee095f1486c: type=NodeSchemaVersion node=longevity-tls-50gb-3d-master-db-node-8fc19eda-4 error=Current node Node longevity-tls-50gb-3d-master-db-node-8fc19eda-4 [34.243.121.198 | 10.4.8.34] (seed: True). Node Node longevity-tls-50gb-3d-master-db-node-8fc19eda-8 [3.250.198.73 | 10.4.9.240] (seed: True) (not target node) exists in the gossip but missed in SYSTEM.PEERS.
```

also node-4 shows more nodes in wrong state in nodetool, i.e. they are shown UN, while gossip states they are LEFT:
```
2023-09-23 05:30:52.366: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=1309b39d-9108-4c3a-a2d1-bddd1f3ac35f: type=NodeStatus node=longevity-tls-50gb-3d-master-db-node-8fc19eda-4 error=Current node Node longevity-tls-50gb-3d-master-db-node-8fc19eda-4 [34.243.121.198 | 10.4.8.34] (seed: True). Wrong node status. Node Node longevity-tls-50gb-3d-master-db-node-8fc19eda-1 [3.253.80.89 | 10.4.10.157] (seed: True) status in nodetool.status is UN, but status in gossip LEFT

2023-09-23 05:30:52.366: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=18567eb3-a358-4f77-9fcd-12c354fdf35e: type=NodeStatus node=longevity-tls-50gb-3d-master-db-node-8fc19eda-4 error=Current node Node longevity-tls-50gb-3d-master-db-node-8fc19eda-4 [34.243.121.198 | 10.4.8.34] (seed: True). Wrong node status. Node Node longevity-tls-50gb-3d-master-db-node-8fc19eda-9 [54.216.187.114 | 10.4.8.106] (seed: True) status in nodetool.status is UN, but status in gossip LEFT
```

also node-4 seems to be missing from the token ring, in our group0 check:
```
2023-09-23 05:30:57.065: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=ee0090ba-c4e3-4aed-bfb7-3c96853f8618: type=Group0TokenRingInconsistency node=longevity-tls-50gb-3d-master-db-node-8fc19eda-4 error=Node longevity-tls-50gb-3d-master-db-node-8fc19eda-4 has group0 member with host_id 3351608e-8ad0-4bed-8638-d8037cb39cae with can_vote True and presents in token ring False. Inconsistency between group0: [{'host_id': '1f665fd7-7f08-4c19-8794-5087c2cf8b6c', 'voter': True}, {'host_id': '3351608e-8ad0-4bed-8638-d8037cb39cae', 'voter': True}, {'host_id': '4a83ff95-4ff1-45cc-8e1d-c49ae0c78d2e', 'voter': True}, {'host_id': '5ea866e1-6613-4ab5-9d07-c628d4b61874', 'voter': True}, {'host_id': '6309fd6f-1bb4-4f62-8ef0-ba0b4b3409a9', 'voter': True}, {'host_id': '89edd4e3-80e5-4a3d-9294-fbdaa1be9ece', 'voter': True}] and tokenring: [{'host_id': '5ea866e1-6613-4ab5-9d07-c628d4b61874', 'ip_address': '10.4.8.34'}, {'host_id': '1f665fd7-7f08-4c19-8794-5087c2cf8b6c', 'ip_address': '10.4.10.157'}, {'host_id': '4a83ff95-4ff1-45cc-8e1d-c49ae0c78d2e', 'ip_address': '10.4.8.42'}, {'host_id': '89edd4e3-80e5-4a3d-9294-fbdaa1be9ece', 'ip_address': '10.4.10.139'}, {'host_id': '6309fd6f-1bb4-4f62-8ef0-ba0b4b3409a9', 'ip_address': '10.4.8.106'}]
```

## Impact

user can't do any more topology changes, since the cluster is in this state

also during that nemesis we got validation error with c-s mixed command that was running (not sure if related or not):
```
java.io.IOException: Operation x0 on key(s) [4b4e4e4e383635364e30]: Data returned was not validated

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:473)
```

## How frequently does it reproduce?

so far it been spotted once

## Installation details

Kernel Version: 5.15.0-1045-aws
Scylla version (or git commit hash): `5.4.0~dev-20230921.a56a4b6226e6` with build-id `616f734e7c7fb5e3ee8898792b3c415d2574a132`

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-master-db-node-8fc19eda-9 (54.216.187.114 | 10.4.8.106) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-8fc19eda-8 (3.250.198.73 | 10.4.9.240) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-8fc19eda-7 (52.209.213.107 | 10.4.9.172) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-8fc19eda-6 (52.210.96.250 | 10.4.11.34) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-8fc19eda-5 (18.203.154.74 | 10.4.11.172) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-8fc19eda-4 (34.243.121.198 | 10.4.8.34) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-8fc19eda-3 (34.252.111.115 | 10.4.10.139) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-8fc19eda-2 (54.73.211.67 | 10.4.8.42) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-8fc19eda-1 (3.253.80.89 | 10.4.10.157) (shards: 14)

OS / Image: `ami-00f051bf1c684c01a` (aws: undefined_region)

Test: `longevity-50gb-3days-test`
Test id: `8fc19eda-452b-4cf3-9eb5-f6e26e99d154`
Test name: `scylla-master/longevity/longevity-50gb-3days-test`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/558925b49a60a15952f3cbb0f692a73e50e7e058/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 8fc19eda-452b-4cf3-9eb5-f6e26e99d154`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=8fc19eda-452b-4cf3-9eb5-f6e26e99d154)
- Show all stored logs command: `$ hydra investigate show-logs 8fc19eda-452b-4cf3-9eb5-f6e26e99d154`

## Logs:
- **db-cluster-8fc19eda.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8fc19eda-452b-4cf3-9eb5-f6e26e99d154/20230923_054551/db-cluster-8fc19eda.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8fc19eda-452b-4cf3-9eb5-f6e26e99d154/20230923_054551/db-cluster-8fc19eda.tar.gz)
- **sct-runner-events-8fc19eda.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8fc19eda-452b-4cf3-9eb5-f6e26e99d154/20230923_054551/sct-runner-events-8fc19eda.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8fc19eda-452b-4cf3-9eb5-f6e26e99d154/20230923_054551/sct-runner-events-8fc19eda.tar.gz)
- **sct-8fc19eda.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8fc19eda-452b-4cf3-9eb5-f6e26e99d154/20230923_054551/sct-8fc19eda.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8fc19eda-452b-4cf3-9eb5-f6e26e99d154/20230923_054551/sct-8fc19eda.log.tar.gz)
- **loader-set-8fc19eda.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8fc19eda-452b-4cf3-9eb5-f6e26e99d154/20230923_054551/loader-set-8fc19eda.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8fc19eda-452b-4cf3-9eb5-f6e26e99d154/20230923_054551/loader-set-8fc19eda.tar.gz)
- **monitor-set-8fc19eda.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8fc19eda-452b-4cf3-9eb5-f6e26e99d154/20230923_054551/monitor-set-8fc19eda.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8fc19eda-452b-4cf3-9eb5-f6e26e99d154/20230923_054551/monitor-set-8fc19eda.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-50gb-3days-test/214/)
[Argus](https://argus.scylladb.com/test/5df88bc6-3ede-4a28-9586-773f93374239/runs?additionalRuns[]=8fc19eda-452b-4cf3-9eb5-f6e26e99d154)
</details>

**Comment by mykaul** [comment]
@fruch - isn't there a newer build than 5.4.0~dev-20230921 ?

**Comment by fruch** [comment]
> @fruch - isn't there a newer build than 5.4.0~dev-20230921 ?

Probably, this a test that we run once a week, and that was the latest version available at that time

**Comment by mykaul** [comment]
> > @fruch - isn't there a newer build than 5.4.0~dev-20230921 ?
> 
> Probably, this a test that we run once a week, and that was the latest version available at that time

Let's re-run then. It's a relatively old build (for master)

**Comment by fruch** [comment]
> > > @fruch - isn't there a newer build than 5.4.0~dev-20230921 ?
> > 
> > 
> > Probably, this a test that we run once a week, and that was the latest version available at that time
> 
> Let's re-run then. It's a relatively old build (for master)

it will tomorrow

**Comment by mykaul** [comment]
@fruch - any updates?

**Comment by fruch** [comment]
> @fruch - any updates?

No weekly run we're not investigated yet

**Comment by bhalevy** [comment]
What's the sequence of events that lead to this state?
Is it a regression?

Cc @asias @kbr-scylla

**Comment by juliayakovlev** [comment]
Similar happened with `5.5.0~dev-20231205`
`grow_cluster` nemesis - by test definition add 3 nodes one by one

Three nodes were added (`first`, `second`, `third`). 
The `second` node got status **UN** after itself was added 
and status **UJ** after `third` node was added


1. Add node `longevity-tls-50gb-3d-master-db-node-98d0519f-7` (3.254.197.106 | **10.4.11.28**) - added successfully. Status of the node7 **UN**
2. Add node `longevity-tls-50gb-3d-master-db-node-98d0519f-8` (34.254.178.131 | **10.4.11.210**) - added successfully. Status of the node8 **UN** 
```
< t:2023-12-09 07:33:42,444 f:base.py        > |/ State=Normal/Leaving/Joining/Moving
< t:2023-12-09 07:33:42,444 f:base.py        > --  Address      Load       Tokens       Owns    Host ID                               Rack
< t:2023-12-09 07:33:42,444 f:base.py        > UN  10.4.8.4     18.76 GB   256          ?       ad04d1ff-6f4c-45bd-99ec-1e821d7f14b7  1c
< t:2023-12-09 07:33:42,444 f:base.py        > UN  10.4.11.210  9.15 GB    256          ?       ea5c64d6-b72b-4cf1-8c84-da73a5bcfab4  1c
< t:2023-12-09 07:33:42,449 f:base.py         > UN  10.4.8.114   19.93 GB   256          ?       e9673588-16b4-4a88-8f9e-d282e9172c89  1c
< t:2023-12-09 07:33:42,454 f:base.py        > UN  10.4.8.188   17.4 GB    256          ?       6fd43221-c002-414a-92de-a0aaa27b70c5  1c
< t:2023-12-09 07:33:42,455 f:base.py        > UN  10.4.11.12   18.57 GB   256          ?       92b22070-71ef-4bb9-8606-1c198ad64805  1c
< t:2023-12-09 07:33:42,455 f:base.py         > UN  10.4.11.124  18.19 GB   256          ?       6dca4613-17e3-4fe6-9ab2-14f26a006792  1c
< t:2023-12-09 07:33:42,460 f:base.py         > UN  10.4.11.28   12.14 GB   256          ?       d1632674-d697-4ed6-90ee-14dead2ad34e  1c
< t:2023-12-09 07:33:42,460 f:base.py         > UN  10.4.11.109  22.1 GB    256          ?       07f59c69-30dc-42e2-8879-b0ff6640ec1a  1c
```

3. Add `longevity-tls-50gb-3d-master-db-node-98d0519f-9` (63.35.193.140 | **10.4.8.80**) - added successfully. Status of the node9 **UN** BUT status of the `longevity-tls-50gb-3d-master-db-node-98d0519f-8` became **UJ**
 ```
< t:2023-12-09 07:58:45,687 f:base.py         > Status=Up/Down
< t:2023-12-09 07:58:45,687 f:base.py         > |/ State=Normal/Leaving/Joining/Moving
< t:2023-12-09 07:58:45,687 f:base.py         > --  Address      Load       Tokens       Owns    Host ID                               Rack
< t:2023-12-09 07:58:45,687 f:base.py         > UN  10.4.8.4     19.29 GB   256          ?       ad04d1ff-6f4c-45bd-99ec-1e821d7f14b7  1c
< t:2023-12-09 07:58:45,687 f:base.py         > UN  10.4.8.80    11.84 GB   256          ?       bdbacada-fe0a-4bac-98f2-2a03e114ba2b  1c
< t:2023-12-09 07:58:45,687 f:base.py         > UJ  10.4.11.210  14.54 GB   256          ?       null                                  1c
< t:2023-12-09 07:58:45,687 f:base.py         > UN  10.4.8.114   13.08 GB   256          ?       e9673588-16b4-4a88-8f9e-d282e9172c89  1c
< t:2023-12-09 07:58:45,687 f:base.py         > UN  10.4.8.188   21.72 GB   256          ?       6fd43221-c002-414a-92de-a0aaa27b70c5  1c
< t:2023-12-09 07:58:45,687 f:base.py         > UN  10.4.11.12   19.96 GB   256          ?       92b22070-71ef-4bb9-8606-1c198ad64805  1c
< t:2023-12-09 07:58:45,687 f:base.py         > UN  10.4.11.124  22.23 GB   256          ?       6dca4613-17e3-4fe6-9ab2-14f26a006792  1c
< t:2023-12-09 07:58:45,687 f:base.py         > UN  10.4.11.28   14.34 GB   256          ?       d1632674-d697-4ed6-90ee-14dead2ad34e  1c
< t:2023-12-09 07:58:45,687 f:base.py         > UN  10.4.11.109  13.23 GB   256          ?       07f59c69-30dc-42e2-8879-b0ff6640ec1a  1c
```


## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1050-aws
Scylla version (or git commit hash): `5.5.0~dev-20231205.4505a86f46df` with build-id `2355da584169ed4dedccb225347f30c5896efe06`





Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-master-db-node-98d0519f-9 (63.35.193.140 | 10.4.8.80) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-98d0519f-8 (34.254.178.131 | 10.4.11.210) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-98d0519f-7 (3.254.197.106 | 10.4.11.28) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-98d0519f-6 (54.76.105.122 | 10.4.11.12) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-98d0519f-5 (3.248.214.168 | 10.4.8.114) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-98d0519f-4 (18.202.19.111 | 10.4.11.124) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-98d0519f-3 (34.250.176.122 | 10.4.8.188) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-98d0519f-2 (34.245.223.165 | 10.4.11.109) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-98d0519f-1 (54.229.251.50 | 10.4.8.4) (shards: 14)


OS / Image: `ami-0934195d8e2431362` (aws: undefined_region)

Test: `longevity-50gb-3days-test`
Test id: `98d0519f-9da0-4cb9-a786-634ac81d3da6`
Test name: `scylla-master/longevity/longevity-50gb-3days-test`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/3d32370733caa48cfe5af0014e1a1b1bb3a48a37/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 98d0519f-9da0-4cb9-a786-634ac81d3da6`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=98d0519f-9da0-4cb9-a786-634ac81d3da6)
- Show all stored logs command: `$ hydra investigate show-logs 98d0519f-9da0-4cb9-a786-634ac81d3da6`


## Logs:
- **db-cluster-98d0519f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/98d0519f-9da0-4cb9-a786-634ac81d3da6/20231209_080550/db-cluster-98d0519f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/98d0519f-9da0-4cb9-a786-634ac81d3da6/20231209_080550/db-cluster-98d0519f.tar.gz)
- **sct-runner-events-98d0519f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/98d0519f-9da0-4cb9-a786-634ac81d3da6/20231209_080550/sct-runner-events-98d0519f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/98d0519f-9da0-4cb9-a786-634ac81d3da6/20231209_080550/sct-runner-events-98d0519f.tar.gz)
- **sct-98d0519f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/98d0519f-9da0-4cb9-a786-634ac81d3da6/20231209_080550/sct-98d0519f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/98d0519f-9da0-4cb9-a786-634ac81d3da6/20231209_080550/sct-98d0519f.log.tar.gz)
- **loader-set-98d0519f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/98d0519f-9da0-4cb9-a786-634ac81d3da6/20231209_080550/loader-set-98d0519f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/98d0519f-9da0-4cb9-a786-634ac81d3da6/20231209_080550/loader-set-98d0519f.tar.gz)
- **monitor-set-98d0519f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/98d0519f-9da0-4cb9-a786-634ac81d3da6/20231209_080550/monitor-set-98d0519f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/98d0519f-9da0-4cb9-a786-634ac81d3da6/20231209_080550/monitor-set-98d0519f.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-50gb-3days-test/226/)
[Argus](https://argus.scylladb.com/test/5df88bc6-3ede-4a28-9586-773f93374239/runs?additionalRuns[]=98d0519f-9da0-4cb9-a786-634ac81d3da6)
</details>

**Comment by mykaul** [comment]
@kostja , @kbr-scylla - please take a look.

**Comment by kostja** [comment]
Inconsistency between the token ring and group0 is possible if you disrupt the node joining process. You need to remove the node from the group0 manually then. If you keep performing nemeses, e.g. removing the nodes from the cluster, you can even lose the majority this way, since group0 size will be in fact bigger than the cluster size. 

The procedure is documented here:
https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/handling-membership-change-failures.html

consistent-topology-changes is supposed to address that. 

Now, I can't verify whether or not this exact scenario has happened,but the end state of the cluster matches the state documented in our manual.

**Comment by kbr-scylla** [comment]
I'm confused -- in https://github.com/scylladb/scylladb/issues/15624#issuecomment-1852139744, was there a disruption? @juliayakovlev you mentioned `grow_cluster` but not `disrupt_grow_shrink_cluster` like the original post. If there was no disruption, why post in this issue?

Regarding the original post, what @kostja said is likely, but to confirm, it would be extremely useful to provide the sequence of events which lead to this state. It's much easier to do for someone who is familiar with SCT and works with it every day, instead of a core developer who looks at SCT logs maybe once in 3 months to dig up the sequence of events from this huge set of logs.

"After `disrupt_grow_shrink_cluster` nemesis" is not descriptive enough.

Also @kostja, the issue describes not only a discrepancy between group 0 and gossip or group 0 and system.peers; it actually described a discrepancy between gossip and system.peers and `nodetool status`, that part may be (and is likely to be) unrelated to group 0 whatsoever and may be caused by a bug in gossip / gossip-based topology changes.

**Comment by juliayakovlev** [comment]
> I'm confused -- in [#15624 (comment)](https://github.com/scylladb/scylladb/issues/15624#issuecomment-1852139744), was there a disruption? @juliayakovlev you mentioned `grow_cluster` but not `disrupt_grow_shrink_cluster` like the original post. If there was no disruption, why post in this issue?

@kbr-scylla `grow_cluster` is part of `disrupt_grow_shrink_cluster`. In the test that I described defined to add 3 nodes (not one) during grow_cluster. I put it here because after adding of third node (topology changes), the node that was added before and was up and normal, got status UJ.
If you think that this problem is not connected to original issue, I can separate it and open new one

> 
> Regarding the original post, what @kostja said is likely, but to confirm, it would be extremely useful to provide the sequence of events which lead to this state. It's much easier to do for someone who is familiar with SCT and works with it every day, instead of a core developer who looks at SCT logs maybe once in 3 months to dig up the sequence of events from this huge set of logs.
> 
> "After `disrupt_grow_shrink_cluster` nemesis" is not descriptive enough.
> 
> Also @kostja, the issue describes not only a discrepancy between group 0 and gossip or group 0 and system.peers; it actually described a discrepancy between gossip and system.peers and `nodetool status`, that part may be (and is likely to be) unrelated to group 0 whatsoever and may be caused by a bug in gossip / gossip-based topology changes.

**Comment by kostja** [comment]
nodetool status is reporting the local state of the peers table, which is updated when the node becomes normal, so different nodes see other nodes becoming normal in different order, so a discrepancy is explicable (at least to me).

**Comment by kbr-scylla** [comment]
> nodetool status is reporting the local state of the peers table

IIRC it is looking into in-memory `token_metadata` actually (which is updated together with system.peers), but yes, what you say still holds.

**Comment by kbr-scylla** [comment]
How much time has passed between the disrupted bootstrap and the health check? Was there at least a ring_delay (30s) in-between?

**Comment by juliayakovlev** [comment]
> How much time has passed between the disrupted bootstrap and the health check? Was there at least a ring_delay (30s) in-between?

@kbr-scylla 
do you ask me? 
Which node bootstrap you ask about: longevity-tls-50gb-3d-master-db-node-98d0519f-8 or longevity-tls-50gb-3d-master-db-node-98d0519f-9?

**Comment by fruch** [comment]
> Regarding the original post, what @kostja said is likely, but to confirm, it would be extremely useful to provide the sequence of events which lead to this state. It's much easier to do for someone who is familiar with SCT and works with it every day, instead of a core developer who looks at SCT logs maybe once in 3 months to dig up the sequence of events from this huge set of logs.
> 

One needs to start from some point, and others can help out as needed.

The ping pong that starts here isn't going to be faster

@temichus and @aleksbykov probably know better about any raft related logic there is in SCT

**Comment by kbr-scylla** [comment]
> @kbr-scylla
> do you ask me?
> Which node bootstrap you ask about: longevity-tls-50gb-3d-master-db-node-98d0519f-8 or longevity-tls-50gb-3d-master-db-node-98d0519f-9?

The report from original post.

> @temichus and @aleksbykov probably know better about any raft related logic there is in SCT

Why Raft related logic matters? IIUC `disrupt_grow_shrink_cluster` is a simple nemesis that starts to boot a node and kills it at random moment (?) there is nothing related to Raft there.

What I ask for is just a simple description of the sequence of events like following (just an example to show the idea):
1. 4 nodes A,B,C,D were bootstrapped
2. node D was decommissioned
3. we started bootstrapping node E at time T
4. at time T + 20 seconds we kill node E (`kill -9`)
5. at time T + 30 seconds after kill, health check was performed, with the following discrepancies: (the stuff you described in the post)

etc.

No need to know any internals of Scylla, no need to know even that something like Raft exists -- except maybe the last step (the discrepancies), but that is already in the original post.

Mostly it's the ability to quickly dig through SCT logs.

My point is that the events leading up to the final state are important for the failure report, not just the final state.

If the test ran for a very long time, probably starting from scratch is not necessary, I'd guess something like the last 3 topology changes would suffice, plus state of the cluster at the moment of that first of the last 3 topology changes.
