### ISSUE TITLE
test_request_too_large[SSL] get stuck on endloop of trying to connect to scylla

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#15661]
test goes into a loop like the following:
```
01:34:30,919 790     cassandra.cluster              WARNING  thread.py           :58   | test_request_too_large[SSL]: Node 127.0.46.1:9042 is reporting a schema disagreement: None
01:34:59,357 790     cassandra.connection           WARNING  threading.py        :1038 | test_request_too_large[SSL]: Heartbeat failed for connection (140630522150416) to 127.0.46.1:9042
01:35:04,358 790     cassandra.cluster              WARNING  thread.py           :58   | test_request_too_large[SSL]: [control connection] Error connecting to 127.0.46.1:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3607, in cassandra.cluster.ControlConnection._connect_host_in_lbp
  File "cassandra/cluster.py", line 3653, in cassandra.cluster.ControlConnection._try_connect
  File "cassandra/cluster.py", line 1689, in cassandra.cluster.Cluster.connection_factory
  File "cassandra/connection.py", line 885, in cassandra.connection.Connection.factory
cassandra.OperationTimedOut: errors=Timed out creating connection (5 seconds), last_host=None
01:35:09,360 790     cassandra.cluster              WARNING  thread.py           :58   | test_request_too_large[SSL]: [control connection] Error connecting to 127.0.46.1:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3607, in cassandra.cluster.ControlConnection._connect_host_in_lbp
  File "cassandra/cluster.py", line 3653, in cassandra.cluster.ControlConnection._try_connect
  File "cassandra/cluster.py", line 1689, in cassandra.cluster.Cluster.connection_factory
  File "cassandra/connection.py", line 885, in cassandra.connection.Connection.factory
cassandra.OperationTimedOut: errors=Timed out creating connection (5 seconds), last_host=None
01:35:14,361 790     cassandra.cluster              WARNING  thread.py           :58   | test_request_too_large[SSL]: [control connection] Error connecting to 127.0.46.1:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3607, in cassandra.cluster.ControlConnection._connect_host_in_lbp
  File "cassandra/cluster.py", line 3653, in cassandra.cluster.ControlConnection._try_connect
  File "cassandra/cluster.py", line 1689, in cassandra.cluster.Cluster.connection_factory
  File "cassandra/connection.py", line 885, in cassandra.connection.Connection.factory
cassandra.OperationTimedOut: errors=Timed out creating connection (5 seconds), last_host=None
```

**Comment by fruch** [comment]
I can see it locally (but not 100% of the times), trying to bisect if it's a specific scylla commit that introduced it.

**Comment by fruch** [comment]
reproducer:

```
pytest limits_test.py::TestLimits::test_request_too_large -k "[SSL" --scylla-version=unstable/master:2023-09-26T21:50:54Z --log-cli-level=debug -n 2 --count=10
```

**Comment by fruch** [comment]
reproduce on:
- 5.4.0~dev-0.20230924.5e8b7a9cef2d with build-id cd4b337695d964e34e73439c81966ef6edd14ee9
- 5.4.0~dev-0.20230925.6bd489e9507b with build-id 77c377eeb37bd43190206d4d83d74b9a399d86b3
- 2023.1.1

seems like it's an issue can happen regardless of which scylla version.

**Comment by elcallio** [comment]
I can't repro this, neither locally (enterprise) or in docker (2023.1). Do we have CI runs where this happened?

**Comment by fruch** [comment]
> I can't repro this, neither locally (enterprise) or in docker (2023.1). Do we have CI runs where this happened?

we are seeing it on master, and as I wrote above with enough runs and parallelism of the same test is reproduces locally for me


happend on:
https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/386/ 
to 
https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/389/

It's a bit hard to see it on CI, since it case the timeout of the whole tests, but on here you can see the node log of it:
https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/389/artifact/logs-full.release.000/orphaned/dtest-2i5lu3jo/

**Comment by elcallio** [comment]
Well, the log indicates that the CQL connection gets a `ENOTCONN` on the scylla side, right after the new table is created. This also happens when the test succeeds, and should maybe be considered a part of the CONNRESET logic...

Why the next connection attempt fails is a mystery. I am leaning on the client side being the issue, but as I still cannot repro this in either relocated or local env, I really don't know. 

I am also perplexed by the: 
`Node 127.0.46.1:9042 is reporting a schema disagreement: None` in your/the failing log. This is _not_ expected in the log.

**Comment by fruch** [comment]
I've run it locally a few times, and my conclusion it's a driver bug

failed one:
```
21:43:31,906 69      cassandra.pool                 DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: Received a connection 140560399457232 for shard_id=0 on host 127.0.88.1:9042
21:43:31,910 69      cassandra.pool                 DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: New connection (140560399457232) created to shard_id=0 on host 127.0.88.1:9042
21:43:32,119 69      cassandra.io.libevreactor      DEBUG    libevreactor.py     :372  | test_request_too_large[SSL-13-15]: Connection <LibevConnection(140560398787984) 127.0.88.1:9042> closed by server
21:43:32,119 69      cassandra.io.libevreactor      DEBUG    libevreactor.py     :287  | test_request_too_large[SSL-13-15]: Closing connection (140560398787984) to 127.0.88.1:9042
21:43:32,119 69      cassandra.io.libevreactor      DEBUG    libevreactor.py     :291  | test_request_too_large[SSL-13-15]: Closed socket to 127.0.88.1:9042
21:43:32,120 69      cassandra.pool                 DEBUG    libevreactor.py     :295  | test_request_too_large[SSL-13-15]: Defunct or closed connection (140560398787984) returned to pool, potentially marking host 127.0.88.1:9042 as down
21:43:32,120 69      cassandra.pool                 DEBUG    libevreactor.py     :295  | test_request_too_large[SSL-13-15]: Shutting down connections to 127.0.88.1:9042
21:43:32,720 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Waiting for schema agreement
21:43:38,721 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Timed out waiting for response during schema agreement check: errors=None, last_host=None
21:43:44,726 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Timed out waiting for response during schema agreement check: errors=None, last_host=None
21:43:50,729 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Timed out waiting for response during schema agreement check: errors=None, last_host=None
21:43:56,730 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Timed out waiting for response during schema agreement check: errors=None, last_host=None
21:44:01,711 69      cassandra.connection           DEBUG    threading.py        :1038 | test_request_too_large[SSL-13-15]: Cannot send heartbeat message on connection (140560398787984) to 127.0.88.1:9042
21:44:02,731 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Timed out waiting for response during schema agreement check: errors=None, last_host=None
21:44:08,733 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Timed out waiting for response during schema agreement check: errors=None, last_host=None
21:44:14,735 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Timed out waiting for response during schema agreement check: errors=None, last_host=None
21:44:20,736 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Timed out waiting for response during schema agreement check: errors=None, last_host=None
21:44:26,737 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Timed out waiting for response during schema agreement check: errors=None, last_host=None
21:44:31,713 69      cassandra.connection           DEBUG    threading.py        :1038 | test_request_too_large[SSL-13-15]: Cannot send heartbeat message on connection (140560398787984) to 127.0.88.1:9042
21:44:31,714 69      cassandra.connection           DEBUG    threading.py        :1038 | test_request_too_large[SSL-13-15]: Sending options message heartbeat on idle connection (140560390349456) 127.0.88.1:9042
21:44:32,720 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Timed out waiting for response during schema agreement check: errors=None, last_host=None
21:44:32,721 69      cassandra.cluster              WARNING  thread.py           :58   | test_request_too_large[SSL-13-15]: Node 127.0.88.1:9042 is reporting a schema disagreement: None
21:44:32,722 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: Skipping schema refresh due to lack of schema agreement
21:44:32,733 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Waiting for schema agreement
21:44:38,737 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Timed out waiting for response during schema agreement check: errors=None, last_host=None
21:44:44,739 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Timed out waiting for response during schema agreement check: errors=None, last_host=None
21:44:50,740 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Timed out waiting for response during schema agreement check: errors=None, last_host=None
21:44:56,741 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Timed out waiting for response during schema agreement check: errors=None, last_host=None
21:45:01,715 69      cassandra.connection           WARNING  threading.py        :1038 | test_request_too_large[SSL-13-15]: Heartbeat failed for connection (140560390349456) to 127.0.88.1:9042
21:45:01,715 69      cassandra.connection           DEBUG    threading.py        :1038 | test_request_too_large[SSL-13-15]: Defuncting connection (140560390349456) to 127.0.88.1:9042: errors=Connection heartbeat timeout after 30 seconds, last_host=127.0.88.1:9042
21:45:01,716 69      cassandra.io.libevreactor      DEBUG    libevreactor.py     :287  | test_request_too_large[SSL-13-15]: Closing connection (140560390349456) to 127.0.88.1:9042
21:45:01,716 69      cassandra.io.libevreactor      DEBUG    libevreactor.py     :291  | test_request_too_large[SSL-13-15]: Closed socket to 127.0.88.1:9042
21:45:01,717 69      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-13-15]: [control connection] Error refreshing schema
```

working one:
```
21:43:45,413 66      limits_test                    INFO     limits_test.py      :377  | test_request_too_large[SSL-7-15]: Trying to send a large request to database (insert a large string into table)...
21:43:45,507 66      cassandra.protocol_features    DEBUG    protocol_features.py:56   | test_request_too_large[SSL-7-15]: Parsing sharding info from message options {'COMPRESSION': ['lz4', 'snappy'], 'SCYLLA_LWT_ADD_METADATA_MARK': ['LWT_OPTIMIZATION_META_BIT_MASK=2147483648'], 'SCYLLA_NR_SHARDS': ['2'], 'SCYLLA_PARTITIONER': ['org.apache.cassandra.dht.Murmur3Partitioner'], 'SCYLLA_RATE_LIMIT_ERROR': ['ERROR_CODE=61440'], 'SCYLLA_SHARD': ['0'], 'SCYLLA_SHARDING_ALGORITHM': ['biased-token-round-robin'], 'SCYLLA_SHARDING_IGNORE_MSB': ['12'], 'SCYLLA_SHARD_AWARE_PORT': ['19042']}
21:43:45,507 66      cassandra.connection           DEBUG    libevreactor.py     :370  | test_request_too_large[SSL-7-15]: Received options response on new connection (140588010907728) from 127.0.29.1:9042
21:43:45,507 66      cassandra.connection           DEBUG    libevreactor.py     :370  | test_request_too_large[SSL-7-15]: No available compression types supported on both ends. locally supported: odict_keys([]). remotely supported: ['lz4', 'snappy']
21:43:45,508 66      cassandra.connection           DEBUG    libevreactor.py     :370  | test_request_too_large[SSL-7-15]: Sending StartupMessage on <LibevConnection(140588010907728) 127.0.29.1:9042>
21:43:45,508 66      cassandra.connection           DEBUG    libevreactor.py     :370  | test_request_too_large[SSL-7-15]: Sent StartupMessage on <LibevConnection(140588010907728) 127.0.29.1:9042>
21:43:45,508 66      cassandra.io.libevreactor      DEBUG    libevreactor.py     :372  | test_request_too_large[SSL-7-15]: Connection <LibevConnection(140588240189008) 127.0.29.1:9042> closed by server
21:43:45,508 66      cassandra.io.libevreactor      DEBUG    libevreactor.py     :287  | test_request_too_large[SSL-7-15]: Closing connection (140588240189008) to 127.0.29.1:9042
21:43:45,508 66      cassandra.io.libevreactor      DEBUG    libevreactor.py     :291  | test_request_too_large[SSL-7-15]: Closed socket to 127.0.29.1:9042
21:43:45,508 66      cassandra.pool                 DEBUG    libevreactor.py     :295  | test_request_too_large[SSL-7-15]: Defunct or closed connection (140588240189008) returned to pool, potentially marking host 127.0.29.1:9042 as down
21:43:45,508 66      cassandra.pool                 DEBUG    libevreactor.py     :295  | test_request_too_large[SSL-7-15]: Shutting down connections to 127.0.29.1:9042
21:43:45,508 66      cassandra.pool                 DEBUG    libevreactor.py     :295  | test_request_too_large[SSL-7-15]: Closing connection (140588240189008) to 127.0.29.1:9042
21:43:45,508 66      cassandra.cluster              WARNING  libevreactor.py     :295  | test_request_too_large[SSL-7-15]: Host 127.0.29.1:9042 has been marked down
21:43:45,508 66      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-7-15]: [control connection] Control connection host (127.0.29.1:9042) is considered down, starting reconnection
21:43:45,508 66      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-7-15]: Removed connection pool for <Host: 127.0.29.1:9042 datacenter1>
21:43:45,509 66      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-7-15]: Starting reconnector for host 127.0.29.1:9042
21:43:45,509 66      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-7-15]: [control connection] Attempting to reconnect
21:43:45,509 66      cassandra.connection           DEBUG    libevreactor.py     :370  | test_request_too_large[SSL-7-15]: Got ReadyMessage on new connection (140588010907728) from 127.0.29.1:9042
21:43:45,509 66      cassandra.pool                 DEBUG    thread.py           :58   | test_request_too_large[SSL-7-15]: Host 127.0.29.1:9042 is now marked up
21:43:45,509 66      cassandra.pool                 DEBUG    thread.py           :58   | test_request_too_large[SSL-7-15]: Received a connection 140588010907728 for shard_id=0 on host 127.0.29.1:9042
21:43:45,510 66      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-7-15]: [control connection] Opening new connection to 127.0.29.1:9042
21:43:45,510 66      cassandra.pool                 DEBUG    thread.py           :58   | test_request_too_large[SSL-7-15]: Pool for host 127.0.29.1:9042 is in shutdown, closing the new connection (140588010907728)
21:43:45,510 66      cassandra.io.libevreactor      DEBUG    libevreactor.py     :287  | test_request_too_large[SSL-7-15]: Closing connection (140588010907728) to 127.0.29.1:9042
21:43:45,510 66      cassandra.io.libevreactor      DEBUG    libevreactor.py     :291  | test_request_too_large[SSL-7-15]: Closed socket to 127.0.29.1:9042
21:43:45,511 66      cassandra.pool                 DEBUG    thread.py           :58   | test_request_too_large[SSL-7-15]: Shutting down connections to 127.0.29.1:9042
21:43:45,511 66      cassandra.pool                 DEBUG    thread.py           :58   | test_request_too_large[SSL-7-15]: Initializing connection for host 127.0.29.1:9042
21:43:45,512 66      cassandra.cluster              DEBUG    dtest_setup.py      :436  | test_request_too_large[SSL-7-15]: Connecting to cluster, contact points: ['127.0.29.1']; protocol version: 4
21:43:45,512 66      cassandra.pool                 DEBUG    dtest_setup.py      :436  | test_request_too_large[SSL-7-15]: Host 127.0.29.1:9042 is now marked up
21:43:45,513 66      cassandra.cluster              DEBUG    dtest_setup.py      :436  | test_request_too_large[SSL-7-15]: [control connection] Opening new connection to 127.0.29.1:9042
21:43:45,514 66      cassandra.connection           DEBUG    libevreactor.py     :267  | test_request_too_large[SSL-7-15]: Connection 140588010976016 127.0.0.1:40320 -> 127.0.29.1:9042
21:43:45,515 66      cassandra.connection           DEBUG    libevreactor.py     :274  | test_request_too_large[SSL-7-15]: Sending initial options message for new connection (140588010976016) to 127.0.29.1:9042
21:43:45,515 66      cassandra.connection           DEBUG    libevreactor.py     :267  | test_request_too_large[SSL-7-15]: Connection 140588011015248 127.0.0.1:40332 -> 127.0.29.1:9042
21:43:45,516 66      cassandra.connection           DEBUG    libevreactor.py     :274  | test_request_too_large[SSL-7-15]: Sending initial options message for new connection (140588011015248) to 127.0.29.1:9042
21:43:45,519 66      cassandra.connection           DEBUG    libevreactor.py     :267  | test_request_too_large[SSL-7-15]: Connection 140588011024912 127.0.0.1:40348 -> 127.0.29.1:9042
21:43:45,519 66      cassandra.connection           DEBUG    libevreactor.py     :274  | test_request_too_large[SSL-7-15]: Sending initial options message for new connection (140588011024912) to 127.0.29.1:9042
21:43:45,560 66      cassandra.protocol_features    DEBUG    protocol_features.py:56   | test_request_too_large[SSL-7-15]: Parsing sharding info from message options {'COMPRESSION': ['lz4', 'snappy'], 'SCYLLA_LWT_ADD_METADATA_MARK': ['LWT_OPTIMIZATION_META_BIT_MASK=2147483648'], 'SCYLLA_NR_SHARDS': ['2'], 'SCYLLA_PARTITIONER': ['org.apache.cassandra.dht.Murmur3Partitioner'], 'SCYLLA_RATE_LIMIT_ERROR': ['ERROR_CODE=61440'], 'SCYLLA_SHARD': ['0'], 'SCYLLA_SHARDING_ALGORITHM': ['biased-token-round-robin'], 'SCYLLA_SHARDING_IGNORE_MSB': ['12'], 'SCYLLA_SHARD_AWARE_PORT': ['19042']}
21:43:45,560 66      cassandra.connection           DEBUG    libevreactor.py     :370  | test_request_too_large[SSL-7-15]: Received options response on new connection (140588011015248) from 127.0.29.1:9042
21:43:45,560 66      cassandra.connection           DEBUG    libevreactor.py     :370  | test_request_too_large[SSL-7-15]: No available compression types supported on both ends. locally supported: odict_keys([]). remotely supported: ['lz4', 'snappy']
21:43:45,560 66      cassandra.connection           DEBUG    libevreactor.py     :370  | test_request_too_large[SSL-7-15]: Sending StartupMessage on <LibevConnection(140588011015248) 127.0.29.1:9042>
21:43:45,560 66      cassandra.connection           DEBUG    libevreactor.py     :370  | test_request_too_large[SSL-7-15]: Sent StartupMessage on <LibevConnection(140588011015248) 127.0.29.1:9042>
21:43:45,561 66      cassandra.protocol_features    DEBUG    protocol_features.py:56   | test_request_too_large[SSL-7-15]: Parsing sharding info from message options {'COMPRESSION': ['lz4', 'snappy'], 'SCYLLA_LWT_ADD_METADATA_MARK': ['LWT_OPTIMIZATION_META_BIT_MASK=2147483648'], 'SCYLLA_NR_SHARDS': ['2'], 'SCYLLA_PARTITIONER': ['org.apache.cassandra.dht.Murmur3Partitioner'], 'SCYLLA_RATE_LIMIT_ERROR': ['ERROR_CODE=61440'], 'SCYLLA_SHARD': ['1'], 'SCYLLA_SHARDING_ALGORITHM': ['biased-token-round-robin'], 'SCYLLA_SHARDING_IGNORE_MSB': ['12'], 'SCYLLA_SHARD_AWARE_PORT': ['19042']}
21:43:45,561 66      cassandra.connection           DEBUG    libevreactor.py     :370  | test_request_too_large[SSL-7-15]: Received options response on new connection (140588010976016) from 127.0.29.1:9042
21:43:45,561 66      cassandra.connection           DEBUG    libevreactor.py     :370  | test_request_too_large[SSL-7-15]: No available compression types supported on both ends. locally supported: odict_keys([]). remotely supported: ['lz4', 'snappy']
21:43:45,561 66      cassandra.connection           DEBUG    libevreactor.py     :370  | test_request_too_large[SSL-7-15]: Sending StartupMessage on <LibevConnection(140588010976016) 127.0.29.1:9042>
21:43:45,561 66      cassandra.connection           DEBUG    libevreactor.py     :370  | test_request_too_large[SSL-7-15]: Sent StartupMessage on <LibevConnection(140588010976016) 127.0.29.1:9042>
21:43:45,561 66      cassandra.connection           DEBUG    libevreactor.py     :370  | test_request_too_large[SSL-7-15]: Got ReadyMessage on new connection (140588011015248) from 127.0.29.1:9042
21:43:45,561 66      cassandra.pool                 DEBUG    thread.py           :58   | test_request_too_large[SSL-7-15]: First connection created to 127.0.29.1:9042 for shard_id=0
21:43:45,561 66      cassandra.connection           DEBUG    libevreactor.py     :370  | test_request_too_large[SSL-7-15]: Got ReadyMessage on new connection (140588010976016) from 127.0.29.1:9042
21:43:45,561 66      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-7-15]: [control connection] Established new connection <LibevConnection(140588010976016) 127.0.29.1:9042>, registering watchers and refreshing schema and topology
21:43:45,562 66      cassandra.pool                 DEBUG    thread.py           :58   | test_request_too_large[SSL-7-15]: Finished initializing connection for host 127.0.29.1:9042
21:43:45,562 66      cassandra.cluster              DEBUG    thread.py           :58   | test_request_too_large[SSL-7-15]: Added pool for host 127.0.29.1:9042 to session
21:43:45,562 66      cassandra.pool                 DEBUG    thread.py           :58   | test_request_too_large[SSL-7-15]: shard_aware_endpoint=None
```

looks like there are case the driver doesn't always reconnect after the connection closed by scylla (cause of the too big request)
and keep on fails on trying to connect, not clear why.

@roydahan @mykaul, can you move this one to scylladb/python-driver ?

**Comment by fruch** [comment]
after debug it more on the driver end, seems like it's happening as the following
1) we connect to one shard
2) 2nd shard is starting connection on the background
3) we send out the big request that goes to the 2nd connection, and scylla closes it, while are inside `set_keyspace_blocking` and holding the pool lock 

also, seems like we are doing a query inside `set_keyspace_blocking` without timeout

**Comment by avikivity** [comment]
Aha, very tricky.

**Comment by avikivity** [comment]
Any idea why the connection is closed by the server? Of course, the driver should be prepared for it.
