### ISSUE TITLE
[dtest]  compaction_additional_test.TestCompactionAdditional.test_refresh_and_restart_after_compaction_strategy_change[ is flakey

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#15712]
https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/6663/testReport/junit/compaction_additional_test/TestCompactionAdditional/Tests___Sanity_Tests___test_refresh_and_restart_after_compaction_strategy_change_SizeTieredCompactionStrategy_SizeTieredCompactionStrategy_/

```
ccmlib.node.ToolError: Subprocess ['stress', 'write', 'no-warmup', 'n=5000', '-pop', 'seq=23600..28600', '-rate', 'threads=10', '-col', 'size=FIXED(1024)'] exited with non-zero status; exit status: 1; 
stdout: ******************** Stress Settings ********************
Command:
  Type: write
  Count: 5,000
  No Warmup: true
  Consistency Level: LOCAL_ONE
  Serial Consistency Level: SERIAL
  Target Uncertainty: not applicable
  Key Size (bytes): 10
  Counter Increment Distibution: add=fixed(1)
Rate:
  Auto: false
  Thread Count: 10
  OpsPer Sec: 0
Population:
  Sequence: 23600..28600
  Order: ARBITRARY
  Wrap: true
Insert:
  Revisits: Uniform:  min=1,max=1000000
  Visits: Fixed:  key=1
  Row Population Ratio: Ratio: divisor=1.000000;delegate=Fixed:  key=1
  Batch Type: not batching
Columns:
  Max Columns Per Key: 5
  Column Names: [C0, C1, C2, C3, C4]
  Comparator: AsciiType
  Timestamp: null
  Variable Column Count: false
  Slice: false
  Size Distribution: Fixed:  key=1024
  Count Distribution: Fixed:  key=5
Errors:
  Ignore: false
  Tries: 10
Log:
  No Summary: false
  No Settings: false
  File: null
  Interval Millis: 1000
  Level: NORMAL
Mode:
  API: JAVA_DRIVER_NATIVE
  Connection Style: CQL_PREPARED
  CQL Version: CQL3
  Protocol Version: V4
  Username: null
  Password: null
  Auth Provide Class: null
  Max Pending Per Connection: null
  Connections Per Host: 8
  Compression: NONE
Node:
  Nodes: [127.0.36.1]
  Is White List: false
  Datacenter: null
  Rack: null
Schema:
  Keyspace: keyspace1
  Replication Strategy: org.apache.cassandra.locator.SimpleStrategy
  Replication Strategy Options: {replication_factor=1}
  Table Compression: null
  Table Compaction Strategy: null
  Table Compaction Strategy Options: {}
Transport:
  factory=org.apache.cassandra.thrift.TFramedTransportFactory; truststore=null; truststore-password=null; keystore=null; keystore-password=null; ssl-protocol=TLS; ssl-alg=SunX509; store-type=JKS; ssl-ciphers=TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA; 
Port:
  Native Port: 9042
  Thrift Port: 9160
  JMX Port: 7199
Send To Daemon:
  *not set*
Graph:
  File: null
  Revision: unknown
  Title: null
  Operation: WRITE
TokenRange:
  Wrap: false
  Split Factor: 1
CloudConf:
  File: null

===== Using optimized driver!!! =====
Connected to cluster: test, max pending requests per connection null, max connections per host 8
Datatacenter: datacenter1; Host: /127.0.36.1; Rack: rack1
; 
stderr: java.lang.RuntimeException: Encountered exception creating schema
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:100)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:69)
	at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:230)
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:58)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/127.0.36.1:9042] Timed out waiting for server response
	at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:43)
	at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:25)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:293)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
	at org.apache.cassandra.stress.util.JavaDriverClient.execute(JavaDriverClient.java:214)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:84)
	... 5 more
Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/127.0.36.1:9042] Timed out waiting for server response
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onTimeout(RequestHandler.java:1026)
	at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1925)
	at com.datastax.shaded.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at com.datastax.shaded.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at com.datastax.shaded.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at com.datastax.shaded.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at com.datastax.shaded.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

```
self = <compaction_additional_test.TestCompactionAdditional object at 0x7f48e0223190>
strategy1 = {'bucket_high': 1.5, 'bucket_low': 0.5, 'class': 'SizeTieredCompactionStrategy', 'min_sstable_size': 1, ...}
strategy2 = {'bucket_high': 1.5, 'bucket_low': 0.5, 'class': 'SizeTieredCompactionStrategy', 'min_sstable_size': 1, ...}

    @pytest.mark.single_node
    @pytest.mark.parametrize("strategy1,strategy2", get_strategies_upgrade_options(), ids=generate_ids)
    def test_refresh_and_restart_after_compaction_strategy_change(self, strategy1, strategy2):
        """
        This test tries to load backup sstable by refresh and restart after changing the compaction strategy.
        refreshing loads sstable from upload directory, and sstable in staging or main sstable directory will
        be loaded in cf populating during restart.
    
        Reshaping will only be triggered conditionally if current compaction strategy isn't satisfied.
    
        LeveledCompactionStrategy:
        - level 0 has more sstables than min_threshold (strict mode) or max_compaction_threshold (relax_mode) (covered in the test)
        - have 10% overlapping sstables on same level
        - sstable level out of MAX level (9)
    
        SizeTieredCompactionStrategy:
        - have more than min_threshold similar-sized SSTables
    
        TimeWindowCompactionStrategy:
        - have sstables that span more than 1 window
        - a given window has more than min_threshold SSTables.
        - Time-Window Compaction Strategy compacts SSTables within each time window
          using Size-tiered Compaction Strategy (STCS)
    
        DateTieredCompactionStrategy:
        - doesn't support reshaping
        """
        cluster = self.cluster
        cluster.populate(1)
        node1 = cluster.nodelist()[0]
        node1.start(wait_for_binary_proto=True)
    
        node1 = self.cluster.nodelist()[0]
        session = self.patient_cql_connection(node1)
        session.execute("DROP KEYSPACE IF EXISTS keyspace1")
    
        logger.debug(f"Create test table with {strategy1}")
        node1.stress(['write', 'n=0', 'no-warmup', '-schema', 'replication(factor=1)', '-rate', 'threads=1'])
    
        session.execute(f"ALTER TABLE keyspace1.standard1 WITH compaction={strategy1}")
    
        logger.debug("Insert test data by cassandra-stress and compact")
        # Use multiple workloads to generate multiple sstables, then it's easy to reach the threshold for reshaping
    
        fill_data_by_cs(node1, n_range=[500, 550, 600, 650])
        # Compact initially, make sure there are some compacted sstables before disable autocompaction
        node1.compact()
    
        # Here we disable autocompaction for leaving all sstables in level 0, then
        # it's easy to trigger reshape with small dataset during restart (strict mode).
        # Actually it's not always necessary.
        #
        # Refreshing from upload will use strict mode reshape, restart population
        # from staging or main sstable directory will use relax mode reshape.
        # Only in relaxed mode, all sstables will be mutated to level to 0, reshaping
        # will be trigger very easily.
    
        logger.debug('disable autocompaction to leave all sstables in level 0')
        node1.nodetool('disableautocompaction keyspace1 standard1')
    
        logger.debug("Insert test data by cassandra-stress without compacting, leave it for next strategy")
    
        if (strategy2['class'] == 'TimeWindowCompactionStrategy'):
            # Prepare a sstable spans two 1 window, (window unit is 60 seconds)
            fill_data_by_cs(node1, n_range=[], duration_range=[70],
                            other_opt=['-rate', 'threads=1', '-col', 'size=FIXED(1024)'])
        elif (strategy2['class'] == 'LeveledCompactionStrategy'):
            # Need more than 10% overlapping sstables on same level
            fill_data_by_cs(node1, n_range=[500, 550, 600, 650, 1000], start=5000)
        elif (strategy2['class'] == 'SizeTieredCompactionStrategy'):
>           fill_data_by_cs(node1, n_range=[500, 550, 600, 650, 2000, 5000] * 2, start=10000)

compaction_additional_test.py:655: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tools/stress.py:51: in fill_data_by_cs
    node.stress(cs_cmdline)
../scylla/.local/lib/python3.11/site-packages/ccmlib/node.py:1303: in stress
    return handle_external_tool_process(p, ['stress'] + stress_options)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

process = <Popen: returncode: 1 args: ['/jenkins/workspace/scylla-master/gating-dtest-...>
cmd_args = ['stress', 'write', 'no-warmup', 'n=5000', '-pop', 'seq=23600..28600', ...]

    def handle_external_tool_process(process, cmd_args):
        out, err = process.communicate()
        if (out is not None) and isinstance(out, bytes):
            out = out.decode()
        if (err is not None) and isinstance(err, bytes):
            err = err.decode()
        rc = process.returncode
    
        if rc != 0:
>           raise ToolError(cmd_args, rc, out, err)
E           ccmlib.node.ToolError: Subprocess ['stress', 'write', 'no-warmup', 'n=5000', '-pop', 'seq=23600..28600', '-rate', 'threads=10', '-col', 'size=FIXED(1024)'] exited with non-zero status; exit status: 1; 
E           stdout: ******************** Stress Settings ********************
E           Command:
E             Type: write
E             Count: 5,000
E             No Warmup: true
E             Consistency Level: LOCAL_ONE
E             Serial Consistency Level: SERIAL
E             Target Uncertainty: not applicable
E             Key Size (bytes): 10
E             Counter Increment Distibution: add=fixed(1)
E           Rate:
E             Auto: false
E             Thread Count: 10
E             OpsPer Sec: 0
E           Population:
E             Sequence: 23600..28600
E             Order: ARBITRARY
E             Wrap: true
E           Insert:
E             Revisits: Uniform:  min=1,max=1000000
E             Visits: Fixed:  key=1
E             Row Population Ratio: Ratio: divisor=1.000000;delegate=Fixed:  key=1
E             Batch Type: not batching
E           Columns:
E             Max Columns Per Key: 5
E             Column Names: [C0, C1, C2, C3, C4]
E             Comparator: AsciiType
E             Timestamp: null
E             Variable Column Count: false
E             Slice: false
E             Size Distribution: Fixed:  key=1024
E             Count Distribution: Fixed:  key=5
E           Errors:
E             Ignore: false
E             Tries: 10
E           Log:
E             No Summary: false
E             No Settings: false
E             File: null
E             Interval Millis: 1000
E             Level: NORMAL
E           Mode:
E             API: JAVA_DRIVER_NATIVE
E             Connection Style: CQL_PREPARED
E             CQL Version: CQL3
E             Protocol Version: V4
E             Username: null
E             Password: null
E             Auth Provide Class: null
E             Max Pending Per Connection: null
E             Connections Per Host: 8
E             Compression: NONE
E           Node:
E             Nodes: [127.0.36.1]
E             Is White List: false
E             Datacenter: null
E             Rack: null
E           Schema:
E             Keyspace: keyspace1
E             Replication Strategy: org.apache.cassandra.locator.SimpleStrategy
E             Replication Strategy Options: {replication_factor=1}
E             Table Compression: null
E             Table Compaction Strategy: null
E             Table Compaction Strategy Options: {}
E           Transport:
E             factory=org.apache.cassandra.thrift.TFramedTransportFactory; truststore=null; truststore-password=null; keystore=null; keystore-password=null; ssl-protocol=TLS; ssl-alg=SunX509; store-type=JKS; ssl-ciphers=TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA; 
E           Port:
E             Native Port: 9042
E             Thrift Port: 9160
E             JMX Port: 7199
E           Send To Daemon:
E             *not set*
E           Graph:
E             File: null
E             Revision: unknown
E             Title: null
E             Operation: WRITE
E           TokenRange:
E             Wrap: false
E             Split Factor: 1
E           CloudConf:
E             File: null
E           
E           ===== Using optimized driver!!! =====
E           Connected to cluster: test, max pending requests per connection null, max connections per host 8
E           Datatacenter: datacenter1; Host: /127.0.36.1; Rack: rack1
E           ; 
E           stderr: java.lang.RuntimeException: Encountered exception creating schema
E           	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:100)
E           	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:69)
E           	at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:230)
E           	at org.apache.cassandra.stress.StressAction.run(StressAction.java:58)
E           	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
E           	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
E           Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/127.0.36.1:9042] Timed out waiting for server response
E           	at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:43)
E           	at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:25)
E           	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
E           	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:293)
E           	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
E           	at org.apache.cassandra.stress.util.JavaDriverClient.execute(JavaDriverClient.java:214)
E           	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:84)
E           	... 5 more
E           Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/127.0.36.1:9042] Timed out waiting for server response
E           	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onTimeout(RequestHandler.java:1026)
E           	at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1925)
E           	at com.datastax.shaded.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
E           	at com.datastax.shaded.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
E           	at com.datastax.shaded.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
E           	at com.datastax.shaded.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
E           	at com.datastax.shaded.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
E           	at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
E           	at java.base/java.lang.Thread.run(Thread.java:829)

../scylla/.local/lib/python3.11/site-packages/ccmlib/node.py:2127: ToolError
```

**Comment by mykaul** [comment]
I don't understand it - all I see in the logs at the time of failure is (from https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/5228/artifact/logs-full.release.006/1697359095589_compaction_additional_test.py%3A%3ATestCompactionAdditional%3A%3Atest_refresh_and_restart_after_compaction_strategy_change%5BSizeTieredCompactionStrategy-SizeTieredCompactionStrategy%5D/node1.log ):
```
WARN  2023-10-15 08:37:54,227 [shard 0:stat] create_keyspace - Using Replication Factor replication_factor=1 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.
INFO  2023-10-15 08:38:12,581 [shard 0:main] compaction_manager - Asked to stop
```

dtest log (https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/5228/artifact/logs-full.release.006/dtest-gw3.log):
```
08:37:51,439 790     tools.stress                   DEBUG    stress.py           :53   | test_refresh_and_restart_after_compaction_strategy_change[SizeTieredCompactionStrategy-SizeTieredCompactionStrategy]: Flush after writing data .....
08:37:51,440 790     ccm                            DEBUG    cluster.py          :709  | test_refresh_and_restart_after_compaction_strategy_change[SizeTieredCompactionStrategy-SizeTieredCompactionStrategy]: node1: nodetool cmd=flush wait=True timeout=None
08:38:06,863 790     errors                         ERROR    conftest.py         :225  | test_refresh_and_restart_after_compaction_strategy_change[SizeTieredCompactionStrategy-SizeTieredCompactionStrategy]: test failed: 
self = <compaction_additional_test.TestCompactionAdditional object at 0x7f48e0223190>
strategy1 = {'bucket_high': 1.5, 'bucket_low': 0.5, 'class': 'SizeTieredCompactionStrategy', 'min_sstable_size': 1, ...}
...
```

**Comment by mykaul** [comment]
BTW, and probably unrelated, but it's still using SimpleStrategy.

**Comment by bhalevy** [comment]
Also client-side timeout:
```
E           stderr: java.lang.RuntimeException: Encountered exception creating schema
...
E           Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/127.0.36.1:9042] Timed out waiting for server response
```

**Comment by avikivity** [comment]
> 
> * who asked the node to stop and why?
> 


Most likely, after the test fails, the test framework tears down the cluster.

**Comment by bhalevy** [comment]
> > * who asked the node to stop and why?
> 
> Most likely, after the test fails, the test framework tears down the cluster.

Correct

**Comment by mykaul** [comment]
https://github.com/scylladb/scylladb/issues/15334#issuecomment-1724149265 (by @kbr-scylla ) has the same client-side failures, failing to create the schema - and that was Sep 18th (could be a different root issue of course).

**Comment by bhalevy** [comment]
> [#15334 (comment)](https://github.com/scylladb/scylladb/issues/15334#issuecomment-1724149265) (by @kbr-scylla ) has the same client-side failures, failing to create the schema - and that was Sep 18th (could be a different root issue of course).

But there the reported error was different:
```
com.datastax.driver.core.exceptions.TransportException: [/127.0.62.3:9042] Connection has been closed
```

vs.  client timeout in https://github.com/scylladb/scylladb/issues/15712#issuecomment-1763355151

**Comment by mykaul** [comment]
Ah, nested exceptions... Yes, close vs. timeout.

**Comment by avikivity** [comment]
Seen again: https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/5627/testReport/junit/compaction_additional_test/TestCompactionAdditional/FullDtest___full_split006___test_refresh_and_restart_after_compaction_strategy_change_LeveledCompactionStrategy_TimeWindowCompactionStrategy_/

**Comment by bhalevy** [comment]
@ShlomiBalalis let's try to reproduce this issue by running the test 1000 times.

**Comment by nyh** [comment]
I suggest that we close this issue. It hasn't been reproduced in a year, and more recently we did see a similar (but different) flakiness in https://github.com/scylladb/scylladb/issues/19596 and fixed that, and today I see yet another sort of flakiness in the same test so I'm forced to open yet another issue on this same test. So this one is not helping.
