### ISSUE TITLE
sstabledump exception: Exception in thread "main" java.lang.NumberFormatException: For input string: "3gb9_1qwk_0ffk02ajb2hufw5t4z"

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#16147]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

```
Command: 'for i in `sudo find /var/lib/scylla/data/keyspace_complex/ -type f |grep -v manifest.json |grep -v snapshots |head -n 1`; do echo $i; sudo sstabledump $i 1>/tmp/sstabledump.output || exit 1; done'
Exit code: 1
Stdout:
/var/lib/scylla/data/keyspace_complex/user_with_ck-18a17f1088b111eeb0d807f87d935fcf/me-3gb9_1qwk_0ffk02ajb2hufw5t4z-big-Index.db
Stderr:
WARN  23:04:25,108 Only 27.541GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
Exception in thread "main" java.lang.NumberFormatException: For input string: "3gb9_1qwk_0ffk02ajb2hufw5t4z"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.base/java.lang.Integer.parseInt(Integer.java:652)
at java.base/java.lang.Integer.parseInt(Integer.java:770)
at org.apache.cassandra.io.sstable.Descriptor.fromFilename(Descriptor.java:280)
at org.apache.cassandra.io.sstable.Descriptor.fromFilename(Descriptor.java:228)
at org.apache.cassandra.io.sstable.Descriptor.fromFilename(Descriptor.java:217)
at org.apache.cassandra.tools.SSTableExport.run(SSTableExport.java:188)
at com.scylladb.tools.SSTableExport.main(SSTableExport.java:44)
```

*Installation details*
Backend: gce
Region: us-east1
Image id: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-11
SCT Commit SHA: 2836e4517f605f44c6c3838af3510b79852cb7fb
Kernel version: 5.10.0-26-cloud-amd64
Base scylla version: 5.2.10-20231102.454e5a711099
Build id: 1cabeff053229b347a86aefb619c61419e5b647e
Upgraded scylla version: 5.4.0~rc2-20231121.219adcea7187
Build id: 145a9fecb823faf30f58b790f5550927257625ba
Instance type: n2-highmem-48
Node amount: 4

Job - https://jenkins.scylladb.com/job/scylla-5.4/job/rolling-upgrade/job/rolling-upgrade-debian11-test/4/

**Comment by mykaul** [comment]
Ah - now I see there's a better template for the bug:
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 3.10.0-1160.102.1.el7.x86_64
Scylla version (or git commit hash): `5.2.10-20231102.454e5a711099` with build-id `1cabeff053229b347a86aefb619c61419e5b647e`
Target Scylla version (or git commit hash): `5.4.0~rc2-20231121.219adcea7187` with build-id `145a9fecb823faf30f58b790f5550927257625ba`




Cluster size: 4 nodes (n2-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--centos-db-node-561bf7a4-0-4 (35.243.172.110 | 10.142.0.162) (shards: 7)
- rolling-upgrade--centos-db-node-561bf7a4-0-3 (35.190.169.172 | 10.142.0.161) (shards: 7)
- rolling-upgrade--centos-db-node-561bf7a4-0-2 (34.75.8.62 | 10.142.0.156) (shards: 7)
- rolling-upgrade--centos-db-node-561bf7a4-0-1 (34.148.196.207 | 10.142.0.153) (shards: 7)


OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7` (gce: undefined_region)

Test: `rolling-upgrade-centos7-test`
Test id: `561bf7a4-a9ca-48be-acd2-c39753048d03`
Test name: `scylla-5.4/rolling-upgrade/rolling-upgrade-centos7-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/2836e4517f605f44c6c3838af3510b79852cb7fb/test-cases/upgrades/rolling-upgrade.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 561bf7a4-a9ca-48be-acd2-c39753048d03`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=561bf7a4-a9ca-48be-acd2-c39753048d03)
- Show all stored logs command: `$ hydra investigate show-logs 561bf7a4-a9ca-48be-acd2-c39753048d03`


## Logs:
- **db-cluster-561bf7a4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/561bf7a4-a9ca-48be-acd2-c39753048d03/20231121_234209/db-cluster-561bf7a4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/561bf7a4-a9ca-48be-acd2-c39753048d03/20231121_234209/db-cluster-561bf7a4.tar.gz)
- **sct-runner-events-561bf7a4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/561bf7a4-a9ca-48be-acd2-c39753048d03/20231121_234209/sct-runner-events-561bf7a4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/561bf7a4-a9ca-48be-acd2-c39753048d03/20231121_234209/sct-runner-events-561bf7a4.tar.gz)
- **sct-561bf7a4.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/561bf7a4-a9ca-48be-acd2-c39753048d03/20231121_234209/sct-561bf7a4.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/561bf7a4-a9ca-48be-acd2-c39753048d03/20231121_234209/sct-561bf7a4.log.tar.gz)
- **loader-set-561bf7a4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/561bf7a4-a9ca-48be-acd2-c39753048d03/20231121_234209/loader-set-561bf7a4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/561bf7a4-a9ca-48be-acd2-c39753048d03/20231121_234209/loader-set-561bf7a4.tar.gz)
- **monitor-set-561bf7a4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/561bf7a4-a9ca-48be-acd2-c39753048d03/20231121_234209/monitor-set-561bf7a4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/561bf7a4-a9ca-48be-acd2-c39753048d03/20231121_234209/monitor-set-561bf7a4.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.4/job/rolling-upgrade/job/rolling-upgrade-centos7-test/4/)
[Argus](https://argus.scylladb.com/test/208f7671-2567-483e-ba9f-03d135cfe7b0/runs?additionalRuns[]=561bf7a4-a9ca-48be-acd2-c39753048d03)
</details>

**Comment by mykaul** [comment]
Dup of https://github.com/scylladb/scylla-tools-java/issues/333

**Comment by tchaikov** [comment]
i am reopening this issue, because we were testing the 5.4 release, and sct's branch-5.4 includes a fix of https://github.com/scylladb/scylla-cluster-tests/commit/cd69a6171a5e2e1ca268e712b7c88c733cbb60c7. which uses `scylla sstable dump-data` for verifying the correctness of sstables. if we are using `sstabledump` instead, something went wrong when checking version of scylla instance under test.

**Comment by fruch** [comment]
> i am reopening this issue, because we were testing the 5.4 release, and sct's branch-5.4 includes a fix of [scylladb/scylla-cluster-tests@cd69a61](https://github.com/scylladb/scylla-cluster-tests/commit/cd69a6171a5e2e1ca268e712b7c88c733cbb60c7). which uses `scylla sstable dump-data` for verifying the correctness of sstables. if we are using `sstabledump` instead, something went wrong when checking version of scylla instance under test.

yeah, added support to help us test older versions, which doesn't have `scylla sstable dump-data`, and we need to check why this logic didn't work.

**Comment by tchaikov** [comment]
my hunch is that the `scylla_version` property was cached. so the old version was used.

**Comment by fruch** [comment]
> my hunch is that the `scylla_version` property was cached. so the old version was used.

could be, even that it should have it cache cleared, need to check why it wasn't

**Comment by tchaikov** [comment]
lemme cook a fix. i have a theory.

**Comment by fruch** [comment]
> lemme cook a fix. i have a theory.

I've found it, there a code for it, but it was used only on some specific path, and not on the code upgrading a node
I'm sending a PR for fixing it

**Comment by tchaikov** [comment]
@fruch i am already writing the commit message. =)

**Comment by tchaikov** [comment]
@fruch Israel, i am assigning this issue to you. as it seems you wanted to take it. please free free to reassign it, if you am wrong.
