### ISSUE TITLE
[dtest] cleanup_test.TestCleanup.test_drop_table_during_cleanup seastar::gate_closed_exception

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#16400]
Seen in https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2689/
https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2689/testReport/junit/cleanup_test/TestCleanup/Build___x86___dtest___test_drop_table_during_cleanup_2/

```
ccmlib.node.ToolError: Subprocess /jenkins/workspace/scylla-enterprise/gating-dtest-release/scylla/.ccm/scylla-repository/992af98ff9743c7da5e91678b3c0a0309edade44/share/cassandra/bin/nodetool -h 127.0.78.1 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy cleanup ks exited with non-zero status; exit status: 2; 
stderr: error: Scylla API server HTTP POST to URL '/storage_service/keyspace_cleanup/ks' failed: seastar::gate_closed_exception (gate closed)
-- StackTrace --
java.lang.IllegalStateException: Scylla API server HTTP POST to URL '/storage_service/keyspace_cleanup/ks' failed: seastar::gate_closed_exception (gate closed)
	at com.scylladb.jmx.api.APIClient.getException(APIClient.java:140)
	at com.scylladb.jmx.api.APIClient.post(APIClient.java:120)
	at com.scylladb.jmx.api.APIClient.post(APIClient.java:130)
	at com.scylladb.jmx.api.APIClient.post(APIClient.java:113)
	at com.scylladb.jmx.api.APIClient.postGetVal(APIClient.java:144)
	at com.scylladb.jmx.api.APIClient.postInt(APIClient.java:148)
	at org.apache.cassandra.service.StorageService.forceKeyspaceCleanup(StorageService.java:709)
	at org.apache.cassandra.service.StorageService.forceKeyspaceCleanup(StorageService.java:1768)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:260)
	at java.management/com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
	at java.management/com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
	at java.management/com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at java.management/com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
	at java.management/com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at com.scylladb.jmx.utils.APIMBeanServer.invoke(APIMBeanServer.java:188)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:827)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

@bhalevy could this be fallout from https://github.com/scylladb/scylladb/pull/16351?

**Comment by bhalevy** [comment]
> @bhalevy could this be fallout from https://github.com/scylladb/scylladb/pull/16351?

next-enterprise merges master d62a5fc60beb9d0cec9c59c5a0027641199f2ea8
which doesn't include 493b6bc65f175fdd755d253bb51bc18ef943b40a
so it looks like it is still https://github.com/scylladb/scylladb/issues/16305

**Comment by denesb** [comment]
Can we close this as duplicate of #16305 then?

**Comment by bhalevy** [comment]
I'm looking at the run again and I can't find `b1ced4ce3d3dd2193dc146af50ed5d7233bba156`.
After fetching the repo I still see next-enterprise at 992af98ff9743c7da5e91678b3c0a0309edade44
so I'm not sure if the branch under test included the fix or not.

**Comment by bhalevy** [comment]
In any case this issue needs to be moved to scylla-enterprise since the job that failed is https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2689/
@mykaul can you please move it?

**Comment by bhalevy** [comment]
https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2690/ passed so let's close this one as dup.
