### ISSUE TITLE
[x86, dev]: non-boost tests.topology_experimental_raft.test_raft_ignore_nodes Failed 

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#16435]
Failed during https://jenkins.scylladb.com/job/scylla-master/job/next/6951

https://jenkins.scylladb.com/job/scylla-master/job/next/6951/testReport/junit/(root)/non-boost%20tests/Build___x86___Unit_Tests_x86___topology_experimental_raft_test_raft_ignore_nodes_dev_3/

```
Traceback (most recent call last):
  File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
  File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
  File "cassandra/connection.py", line 876, in cassandra.connection.Connection.factory
  File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 955, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.15.216.15', 9042)]. Last error: Connection refused
```

**Comment by mykaul** [comment]
@kbr-scylla - please assign someone to look at this.

**Comment by kbr-scylla** [comment]
Relevant logs:
[scylla-1232.log](https://github.com/scylladb/scylladb/files/13703036/scylla-1232.log)
[scylla-1233.log](https://github.com/scylladb/scylladb/files/13703038/scylla-1233.log)
[scylla-1235.log](https://github.com/scylladb/scylladb/files/13703039/scylla-1235.log)
[scylla-1239.log](https://github.com/scylladb/scylladb/files/13703040/scylla-1239.log)
[scylla-1241.log](https://github.com/scylladb/scylladb/files/13703041/scylla-1241.log)
[scylla-1244.log](https://github.com/scylladb/scylladb/files/13703042/scylla-1244.log)
[scylla-1246.log](https://github.com/scylladb/scylladb/files/13703043/scylla-1246.log)
[topology_experimental_raft.test_raft_ignore_nodes.3.log](https://github.com/scylladb/scylladb/files/13703044/topology_experimental_raft.test_raft_ignore_nodes.3.log)


```


=================================== FAILURES ===================================
________________________ test_raft_remove_ignore_nodes _________________________

manager = <test.pylib.manager_client.ManagerClient object at 0x7f0f0c73d450>

    @pytest.mark.asyncio
    async def test_raft_remove_ignore_nodes(manager: ManagerClient) -> None:
        """Remove 3 dead nodes.
    
           This is a slow test with a 7 node cluster and 3 removenode operations,
           we want to run it only in dev mode.
        """
        logger.info(f"Booting initial cluster")
        servers = [await manager.server_add() for _ in range(7)]
        s1_id = await manager.get_host_id(servers[1].server_id)
        s2_id = await manager.get_host_id(servers[2].server_id)
        logger.info(f"Stopping servers {servers[:3]}")
        await manager.server_stop_gracefully(servers[0].server_id)
>       await manager.server_stop_gracefully(servers[1].server_id)

test/topology_experimental_raft/test_raft_ignore_nodes.py:68: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/pylib/manager_client.py:148: in server_stop_gracefully
    await self.client.put_json(f"/cluster/server/{server_id}/stop_gracefully")
test/pylib/rest_client.py:104: in put_json
    ret = await self._fetch("PUT", resource_uri, response_type = response_type, host = host,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.pylib.rest_client.UnixRESTClient object at 0x7f0f0c6e9990>
method = 'PUT', resource = '/cluster/server/1233/stop_gracefully'
response_type = None, host = None, port = None, params = None, json = None
timeout = None

    async def _fetch(self, method: str, resource: str, response_type: Optional[str] = None,
                     host: Optional[str] = None, port: Optional[int] = None,
                     params: Optional[Mapping[str, str]] = None,
                     json: Optional[Mapping] = None, timeout: Optional[float] = None) -> Any:
        # Can raise exception. See https://docs.aiohttp.org/en/latest/web_exceptions.html
        assert method in ["GET", "POST", "PUT", "DELETE"], f"Invalid HTTP request method {method}"
        assert response_type is None or response_type in ["text", "json"], \
                f"Invalid response type requested {response_type} (expected 'text' or 'json')"
        # Build the URI
        port = port if port else self.default_port if hasattr(self, "default_port") else None
        port_str = f":{port}" if port else ""
        assert host is not None or hasattr(self, "default_host"), "_fetch: missing host for " \
                "{method} {resource}"
        host_str = host if host is not None else self.default_host
        uri = self.uri_scheme + "://" + host_str + port_str + resource
        logging.debug(f"RESTClient fetching {method} {uri}")
    
        client_timeout = ClientTimeout(total = timeout if timeout is not None else 300)
        async with request(method, uri,
                           connector = self.connector if hasattr(self, "connector") else None,
                           params = params, json = json, timeout = client_timeout) as resp:
            if resp.status != 200:
                text = await resp.text()
>               raise HTTPError(uri, resp.status, params, json, text)
E               test.pylib.rest_client.HTTPError: HTTP error 500, uri: http+unix://api/cluster/server/1233/stop_gracefully, params: None, json: None, body:
E               Stopping server ScyllaServer(1233, 127.15.216.48, 90884ab4-32f8-4a4f-b1f4-0fbc313b3706) gracefully took longer than 60s
```


Apparently server 1233 hanged during shutdown:
```
INFO  2023-12-17 18:16:19,309 [shard 0:main] init - Shutting down tracing
INFO  2023-12-17 18:16:19,309 [shard 0:main] init - Shutting down tracing was successful
INFO  2023-12-17 18:16:19,309 [shard 0:main] init - Shutting down group 0 usage in local storage
INFO  2023-12-17 18:16:19,309 [shard 0:strm] storage_service - raft_state_monitor_fiber aborted with seastar::abort_requested_exception (abort requested)
INFO  2023-12-17 18:16:20,073 [shard 0:main] raft_group_registry - marking Raft server e607f4f4-094d-484b-9cad-2a0f732f11d3 as dead for raft groups
INFO  2023-12-17 18:16:20,079 [shard 0:main] raft_group_registry - marking Raft server 919c43f9-077a-4dd3-8be4-71116130b6df as dead for raft groups
INFO  2023-12-17 18:16:20,096 [shard 0:main] raft_group_registry - marking Raft server 5247ac40-5971-4267-8e99-f2adfff82724 as dead for raft groups
INFO  2023-12-17 18:16:20,147 [shard 0:main] raft_group_registry - marking Raft server 4ad67b93-1437-4fab-a70f-04350ab82739 as dead for raft groups
INFO  2023-12-17 18:16:20,270 [shard 0:main] raft_group_registry - marking Raft server 7a42a5bd-9000-4db4-87cd-20d6ddee2172 as dead for raft groups
------ Ending test dev/topology_experimental_raft.test_raft_ignore_nodes.3::test_raft_remove_ignore_nodes ------
```

**Comment by mykaul** [comment]
@kbr-scylla - what's the next step here?

**Comment by kbr-scylla** [comment]
I prioritized it. It's waiting for free hands.

**Comment by yaronkaikov** [comment]
Seen again https://jenkins.scylladb.com/job/scylla-master/job/next/7033/consoleFull

**Comment by yaronkaikov** [comment]
Seen again https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2731/consoleFull

**Comment by nyh** [comment]
I think this is a duplicate of https://github.com/scylladb/scylladb/issues/16420, which has its own list of failures :-( It seems that this failure is happening fairly frequently in CI runs, and must be fixed.
