### ISSUE TITLE
[aarch64, debug]: topology.test_topology_rejoin Failed

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#16460]
Happened during https://jenkins.scylladb.com/job/scylla-master/job/next/6963/ 

```
08:27:41.297 DEBUG> Sending options message heartbeat on idle connection (281470763079056) 127.58.46.26:9042
08:27:41.298 DEBUG> Sending options message heartbeat on idle connection (281470762745424) 127.58.46.26:9042
08:27:41.298 DEBUG> Sending options message heartbeat on idle connection (281470762757264) 127.58.46.9:9042
08:27:41.298 DEBUG> Sending options message heartbeat on idle connection (281470780922768) 127.58.46.26:9042
08:27:41.302 DEBUG> Received options response on connection (281470762757264) from 127.58.46.9:9042
08:27:41.302 DEBUG> Received options response on connection (281470762745424) from 127.58.46.26:9042
08:27:41.303 DEBUG> Received options response on connection (281470780922768) from 127.58.46.26:9042
08:27:41.304 DEBUG> Received options response on connection (281470763079056) from 127.58.46.26:9042
08:27:42.759 WARNING> Error attempting to reconnect to 127.58.46.34:9042, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.58.46.34', 9042)]. Last error: Connection refused
08:27:42.759 DEBUG> Reconnection error details
Traceback (most recent call last):
  File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
  File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
  File "cassandra/connection.py", line 876, in cassandra.connection.Connection.factory
  File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 955, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.58.46.34', 9042)]. Last error: Connection refused
```
Full log: https://jenkins.scylladb.com/job/scylla-master/job/next/6963/artifact/testlog/aarch64/debug/topology.test_topology_rejoin.1.log

**Comment by kbr-scylla** [comment]
@yaronkaikov JFYI these logs excerpts you're attaching have nothing to do with the failure. Topology tests are constantly stopping servers and restarting them, it's normal that the driver cannot connect to a server while it's dead. The driver likes to be verbose in its logs.

**Comment by yaronkaikov** [comment]
> @yaronkaikov JFYI these logs excerpts you're attaching have nothing to do with the failure. Topology tests are constantly stopping servers and restarting them, it's normal that the driver cannot connect to a server while it's dead. The driver likes to be verbose in its logs.

@kbr-scylla Thanks for the info. Where should i look then? which logs are relevant for the actual failures?

**Comment by kbr-scylla** [comment]
In the log file you attached (https://jenkins.scylladb.com/job/scylla-master/job/next/6963/artifact/testlog/aarch64/debug/topology.test_topology_rejoin.1.log) look for === FAILURES === section
```
=================================== FAILURES ===================================
_________________________ test_start_after_sudden_stop _________________________

manager = <test.pylib.manager_client.ManagerClient object at 0xffff05e72510>
random_tables = <test.pylib.random_tables.RandomTables object at 0xffff04d42890>

    @pytest.mark.asyncio
    async def test_start_after_sudden_stop(manager: ManagerClient, random_tables) -> None:
        """Tests a server can rejoin the cluster after being stopped suddenly"""
        servers = await manager.running_servers()
        table = await random_tables.add_table(ncolumns=5)
        await manager.server_stop(servers[0].server_id)
        await table.add_column()
>       await manager.server_start(servers[0].server_id)

test/topology/test_topology_rejoin.py:20: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/pylib/manager_client.py:155: in server_start
    await self.client.put_json(f"/cluster/server/{server_id}/start", data)
test/pylib/rest_client.py:104: in put_json
    ret = await self._fetch("PUT", resource_uri, response_type = response_type, host = host,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.pylib.rest_client.UnixRESTClient object at 0xffff05e41550>
method = 'PUT', resource = '/cluster/server/151/start', response_type = None
host = None, port = None, params = None, json = {'expected_error': None}
timeout = None

    async def _fetch(self, method: str, resource: str, response_type: Optional[str] = None,
                     host: Optional[str] = None, port: Optional[int] = None,
                     params: Optional[Mapping[str, str]] = None,
                     json: Optional[Mapping] = None, timeout: Optional[float] = None) -> Any:
        # Can raise exception. See https://docs.aiohttp.org/en/latest/web_exceptions.html
        assert method in ["GET", "POST", "PUT", "DELETE"], f"Invalid HTTP request method {method}"
        assert response_type is None or response_type in ["text", "json"], \
                f"Invalid response type requested {response_type} (expected 'text' or 'json')"
        # Build the URI
        port = port if port else self.default_port if hasattr(self, "default_port") else None
        port_str = f":{port}" if port else ""
        assert host is not None or hasattr(self, "default_host"), "_fetch: missing host for " \
                "{method} {resource}"
        host_str = host if host is not None else self.default_host
        uri = self.uri_scheme + "://" + host_str + port_str + resource
        logging.debug(f"RESTClient fetching {method} {uri}")
    
        client_timeout = ClientTimeout(total = timeout if timeout is not None else 300)
        async with request(method, uri,
                           connector = self.connector if hasattr(self, "connector") else None,
                           params = params, json = json, timeout = client_timeout) as resp:
            if resp.status != 200:
                text = await resp.text()
>               raise HTTPError(uri, resp.status, params, json, text)
E               test.pylib.rest_client.HTTPError: HTTP error 500, uri: http+unix://api/cluster/server/151/start, params: None, json: {'expected_error': None}, body:
E               failed to start the node, server_id 151, IP 127.58.46.34, workdir scylla-151, host_id e4a1e0c8-0ef1-4712-a91c-6164672721ce, cql [not connected]
E               Check the log files:
E               /scylladir/testlog/aarch64/test.py.debug-release-dev.log
E               /scylladir/testlog/aarch64/debug/scylla-151.log

test/pylib/rest_client.py:69: HTTPError

```


It's also useful to check which nodes participated in the failed test. This is above == FAILURES == in the log teardown section:

```
08:27:47.310 DEBUG> Closing connection (281470762936272) to 127.58.46.34:9042
08:27:47.310 DEBUG> Closed socket to 127.58.46.34:9042
FAILED
------------------------------ live log teardown -------------------------------
08:27:48.367 DEBUG> after_test for test_start_after_sudden_stop (success: False)
08:27:48.367 DEBUG> RESTClient fetching PUT http+unix://api/cluster/after-test/False
08:27:48.373 INFO> Cluster after test test_start_after_sudden_stop: ScyllaCluster(name: f95097ca-9e47-11ee-9943-043f72d77e12, running: ScyllaServer(156, 127.58.46.26, 28a63a1c-5909-4f92-ad8e-bd505e76c27f), ScyllaServer(161, 127.58.46.9, 36aa8a66-548d-47c4-a54b-98103aeaeccf), ScyllaServer(151, 127.58.46.34, e4a1e0c8-0ef1-4712-a91c-6164672721ce), stopped: )
08:27:48.374 DEBUG> shutting down driver
```

The `Cluster after test` part.

So in this case the nodes which participated are 156, 161, 151
https://jenkins.scylladb.com/job/scylla-master/job/next/6963/artifact/testlog/aarch64/debug/scylla-161.log
https://jenkins.scylladb.com/job/scylla-master/job/next/6963/artifact/testlog/aarch64/debug/scylla-151.log
https://jenkins.scylladb.com/job/scylla-master/job/next/6963/artifact/testlog/aarch64/debug/scylla-156.log

**Comment by kbr-scylla** [comment]
In scylla-151.log:

```
INFO  2023-12-19 08:27:46,482 [shard 0:main] init - Scylla version 5.5.0~dev-0.20231219.c1a2e9c8f30d initialization completed.
INFO  2023-12-19 08:27:46,790 [shard 0: gms] gossip - Node 127.58.46.9 has restarted, now UP, status = NORMAL
INFO  2023-12-19 08:27:46,938 [shard 0: gms] gossip - InetAddress 127.58.46.9 is now UP, status = NORMAL
ERROR 2023-12-19 08:27:46,944 [shard 0:main] gossip - Attempted to add saved endpoint after endpoint_state was already established with gossip: { generation = 1702974301, version = 230 }, at: 0xcfc2a63 /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x504b927 /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x504b68f /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x504ddff /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x504e82b /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3a96b3f /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3a97333 0x1a7515e7 0xd4c8db7 0xd4c8987 /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3d48573 /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3d51327 /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3d54f13 /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3d5300f /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x379b4d3 /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3798bfb 0xd06425f 0xe0d3fe7 0xe0d3bab 0xe0d33bb 0xd293b53 0xd061c27 /lib64/libc.so.6+0x3059b /lib64/libc.so.6+0x3066f 0xcf7ca2f
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
Aborting on shard 0.
Backtrace:
  0xcfc2a63
  /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3f44adf
  /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3f446bb
  /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3d266b7
  /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3d569db
  /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3e8a47f
  /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3e8a7c7
  /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3e8a5eb
  linux-vdso.so.1+0x7db
  /lib64/libc.so.6+0x90a6f
  /lib64/libc.so.6+0x44b3f
  /lib64/libc.so.6+0x30287
  /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3a97353
  0x1a7515e7
  0xd4c8db7
  0xd4c8987
  /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3d48573
  /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3d51327
  /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3d54f13
  /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3d5300f
  /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x379b4d3
  /jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so+0x3798bfb
  0xd06425f
  0xe0d3fe7
  0xe0d3bab
  0xe0d33bb
  0xd293b53
  0xd061c27
  /lib64/libc.so.6+0x3059b
  /lib64/libc.so.6+0x3066f
  0xcf7ca2f
------ Ending test debug/topology.test_topology_rejoin.1::test_start_after_sudden_stop ------
```

cc @bhalevy @gusev-p

**Comment by kbr-scylla** [comment]
> Attempted to add saved endpoint after endpoint_state was already established with gossip

Is adding saved endpoints racing with gossiping? Weird. We should not start gossip until after we add saved endpoints

**Comment by gusev-p** [comment]
> Is adding saved endpoints racing with gossiping? Weird. We should not start gossip until after we add saved endpoints

In `raft_topology` `add_saved_endpoint` is called from `topology_state_load`, this can happen after gossiper is started.

**Comment by kbr-scylla** [comment]
> In raft_topology add_saved_endpoint is called from topology_state_load

Hm, is this new? Or were we always calling `add_saved_endpoint`?

**Comment by gusev-p** [comment]
> > In raft_topology add_saved_endpoint is called from topology_state_load
> 
> Hm, is this new? Or were we always calling `add_saved_endpoint`?

I added `add_saved_endpoint` into `topology_state_load` several months ago. I can't find 'Attempted' in the `gms` directory, so this check is a recent addition.

**Comment by kbr-scylla** [comment]
Argh
it's a queued patch
```
commit 3c30ec23a0e0d224dc04abdcffb05f71eb9feae9 (HEAD -> next, origin/next)
Author: Benny Halevy <bhalevy@scylladb.com>
Date:   Sun Dec 17 08:36:35 2023 +0200

    gossiper: add_saved_endpoint: keep heart_beat_state if ep_state is found
    
    Currently, when loading peers' endpoint state from system.peers,
    add_saved_endpoint is called.
    The first instance of the endpoint state is created with the default
    heart_beat_state, with both generation and version set to zero.
    However, if add_saved_endpoint finds an existing instance of the
    endpoint state, it reuses it, but it updates its heart_beat_state
    with the local heart_beat_state() rather than keeping the existing
    heart_beat_state, as it should.
    
    This is a problem since it may confuse updates over gossip
    later on via do_apply_state_locally that compares the remote
    generation vs. the local generation, so they must stem from
    the same root that is the endpoint itself.
    
    Also, call on_internal_error_noexccept if add_saved_endpoint is called
    while there's already an endpoint_state for the node with
    non-zero generation, as it indicates it was received from
    gossip and should not be updated with local information
    loaded from system.peers. This will abort in testing or just
    print an error in production and do nothing more.
    
    Fixes #16429
    
    Signed-off-by: Benny Halevy <bhalevy@scylladb.com>
    
    Closes scylladb/scylladb#16432
```
I'll dequeue

cc @bhalevy

**Comment by kbr-scylla** [comment]
Dequeued, closing issue

**Comment by bhalevy** [comment]
Backtrace not very useful due to coroutine :-/
```
[Backtrace #0]
gms::gossiper::add_saved_endpoint(gms::inet_address) at ./gms/gossiper.cc:2092
std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<void>::promise_type>::resume() const at /usr/bin/../lib/gcc/aarch64-redhat-linux/13/../../../../include/c++/13/coroutine:240
seastar::internal::coroutine_traits_base<void>::promise_type::run_and_dispose() at ././seastar/include/seastar/core/coroutine.hh:125
/jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so 0x3d48573 
/jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so 0x3d51327 
/jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so 0x3d54f13 
/jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so 0x3d5300f 
/jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so 0x379b4d3 
/jenkins/workspace/scylla-master/next/scylla/build/debug/seastar/libseastar.so 0x3798bfb 
scylla_main(int, char**) at ./main.cc:657
int std::__invoke_impl<int, int (*&)(int, char**), int, char**>(std::__invoke_other, int (*&)(int, char**), int&&, char**&&) at /usr/bin/../lib/gcc/aarch64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:61
std::enable_if<is_invocable_r_v<int, int (*&)(int, char**), int, char**>, int>::type std::__invoke_r<int, int (*&)(int, char**), int, char**>(int (*&)(int, char**), int&&, char**&&) at /usr/bin/../lib/gcc/aarch64-redhat-linux/13/../../../../include/c++/13/bits/invoke.h:114
std::_Function_handler<int (int, char**), int (*)(int, char**)>::_M_invoke(std::_Any_data const&, int&&, char**&&) at /usr/bin/../lib/gcc/aarch64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:290
std::function<int (int, char**)>::operator()(int, char**) const at /usr/bin/../lib/gcc/aarch64-redhat-linux/13/../../../../include/c++/13/bits/std_function.h:591
main at ./main.cc:2031
```

**Comment by bhalevy** [comment]
I's possible it found a real issue though.
Was worth it
