### ISSUE TITLE
Maintenance socket follow-up: fix cqlsh

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#16489]
The maintenance socket documentation gives an example of connecting through Python driver:
```python3
from cassandra.cluster import Cluster
from cassandra.connection import UnixSocketEndPoint
from cassandra.policies import HostFilterPolicy, RoundRobinPolicy

socket = "<node's workdir>/cql.m"
cluster = Cluster([UnixSocketEndPoint(socket)],
                  # Driver tries to connect to other nodes in the cluster, so we need to filter them out.
                  load_balancing_policy=HostFilterPolicy(RoundRobinPolicy(), lambda h: h.address == socket))
session = cluster.connect()
```

This works for the latest https://github.com/scylladb/python-driver/ `master` branch (with https://github.com/scylladb/python-driver/pull/279) -- soon new version of the driver should be released.

But `cqlsh` breaks:
```
$ cqlsh /tmp/scylla-workdir/cql.m 
Traceback (most recent call last):
  File "/home/kbr/dev/scylla/tools/cqlsh/bin/cqlsh.py", line 2706, in <module>
    main(*read_options(sys.argv[1:], os.environ))
  File "/home/kbr/dev/scylla/tools/cqlsh/bin/cqlsh.py", line 2647, in main
    shell = Shell(hostname,
            ^^^^^^^^^^^^^^^
  File "/home/kbr/dev/scylla/tools/cqlsh/bin/cqlsh.py", line 491, in __init__
    profiles[EXEC_PROFILE_DEFAULT].load_balancing_policy = WhiteListRoundRobinPolicy([self.hostname])
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kbr/dev/scylla/pyenv/lib64/python3.11/site-packages/cassandra/policies.py", line 425, in __init__
    self._allowed_hosts_resolved = [endpoint[4][0] for a in self._allowed_hosts
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kbr/dev/scylla/pyenv/lib64/python3.11/site-packages/cassandra/policies.py", line 426, in <listcomp>
    for endpoint in socket.getaddrinfo(a, None, socket.AF_UNSPEC, socket.SOCK_STREAM)]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
```

This is a different problem than https://github.com/scylladb/python-driver/pull/279, so maybe cqlsh is calling some API that does not support unix-domain socket?

Needs to be investigated and fixed.

**Comment by kbr-scylla** [comment]
Ah, it's because it uses `WhiteListRoundRobinPolicy`.
@margdoc in https://github.com/scylladb/scylladb/pull/16172#discussion_r1430431042 you said that you had to change to `HostFilterPolicy` because of that.
We most likely need to fix Python driver again.

**Comment by kbr-scylla** [comment]
I opened https://github.com/scylladb/python-driver/issues/280

**Comment by kbr-scylla** [comment]
Reopening until we update the cqlsh submodule in Scylla
