### ISSUE TITLE
docker node crashes with error: `too many positional options have been specified on the command line`

### ISSUE THREAD

**Issue by cholcombe973** [scylladb/scylladb#16502]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): docker image: `c794507c446f`
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

Launching the Docker image with the default command given on the instructions results in a failure. I've tried Scylla 5.4 and 5.2 thinking maybe the older version might still work but the same error comes up. 
```
Scylla version 5.4.0-0.20231205.58a89e7a4231 with build-id 9b77be91b1fc75d71c99e1de13a69ea2ddb1f4d7 starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address fd42:dead:beef:fefe:0:242:ac11:3 172.17.0.3 --rpc-address fd42:dead:beef:fefe:0:242:ac11:3 172.17.0.3 --seed-provider-parameters seeds=fd42:dead:beef:fefe:0:242:ac11:3 172.17.0.3 --alternator-address fd42:dead:beef:fefe:0:242:ac11:3 172.17.0.3 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, overprovisioned, listen-address: fd42:dead:beef:fefe:0:242:ac11:3, (positional) 172.17.0.3, rpc-address: fd42:dead:beef:fefe:0:242:ac11:3, (positional) 172.17.0.3, seed-provider-parameters: seeds=fd42:dead:beef:fefe:0:242:ac11:3, (positional) 172.17.0.3, alternator-address: fd42:dead:beef:fefe:0:242:ac11:3, (positional) 172.17.0.3, blocked-reactor-notify-ms, (positional) 999999999]
error: too many positional options have been specified on the command line
```

```
Scylla version 5.2.3-0.20230608.ea08d409f155 with build-id ec8d1c19fc354f34c19e07e35880e0f40cc7d8cd starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address fd42:dead:beef:fefe:0:242:ac11:3 172.17.0.3 --rpc-address fd42:dead:beef:fefe:0:242:ac11:3 172.17.0.3 --seed-provider-parameters seeds=fd42:dead:beef:fefe:0:242:ac11:3 172.17.0.3 --alternator-address fd42:dead:beef:fefe:0:242:ac11:3 172.17.0.3 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, overprovisioned, listen-address: fd42:dead:beef:fefe:0:242:ac11:3, (positional) 172.17.0.3, rpc-address: fd42:dead:beef:fefe:0:242:ac11:3, (positional) 172.17.0.3, seed-provider-parameters: seeds=fd42:dead:beef:fefe:0:242:ac11:3, (positional) 172.17.0.3, alternator-address: fd42:dead:beef:fefe:0:242:ac11:3, (positional) 172.17.0.3, blocked-reactor-notify-ms, (positional) 999999999]
error: too many positional options have been specified on the command line
```
Has the command to launch a single docker scylla container changed recently?

**Comment by mykaul** [comment]
Aren't you missing commas between the IPv6 and IPv4 addresses?

(and I'm not sure what --blocked-reactor-notify-ms 999999999 means - what's the uze case)

**Comment by cholcombe973** [comment]
These command params aren't really under my control (I think?) because I just docker run it with: `docker run --name some-scylla --hostname some-scylla -d scylladb/scylla --smp 1` and all that stuff is run under the hood.

**Comment by mykaul** [comment]
@cholcombe973 - and the above works? without all the excess params?

**Comment by demming** [comment]
@cholcombe973 I'm having the same issue. It's likely due to the multiple IP addresses. I want the nodes to listen on multiple networks at the same time. I'm just going to edit the entrypoint script. As you see, your IPv4 address is interpreted as positional arg, like @mykaul noticed there should be commas in between. So it's either a bug in the entrypoint script or Scylla can't listen on multiple addresses. Same sort of issue here:

```
Scylla version 5.4.0-0.20231205.58a89e7a4231 with build-id 7486a70ced30f7c89053f5c5a230c20ad31ffc1f starting ...
2024-01-02T17:50:36.683555627Z command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 192.168.128.6 192.168.192.3 --rpc-address 192.168.128.6 192.168.192.3 --seed-provider-parameters seeds=192.168.128.6 192.168.192.3 --alternator-address 192.168.128.6 192.168.192.3 --blocked-reactor-notify-ms 999999999"
2024-01-02T17:50:36.683563627Z parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, overprovisioned, listen-address: 192.168.128.6, (positional) 192.168.192.3, rpc-address: 192.168.128.6, (positional) 192.168.192.3, seed-provider-parameters: seeds=192.168.128.6, (positional) 192.168.192.3, alternator-address: 192.168.128.6, (positional) 192.168.192.3, blocked-reactor-notify-ms, (positional) 999999999]
2024-01-02T17:50:36.686455294Z error: too many positional options have been specified on the command line
2024-01-02T17:50:36.686502877Z 
2024-01-02T17:50:36.686507377Z Try --help.
2024-01-02T17:50:36.697136127Z 2024-01-02 17:50:36,696 INFO exited: scylla (exit status 2; not expected)
2024-01-02T17:50:37.479605461Z Traceback (most recent call last):
2024-01-02T17:50:37.479670461Z   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 196, in <module>
2024-01-02T17:50:37.479699544Z     args.func(args)
2024-01-02T17:50:37.479705169Z   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 122, in check_version
2024-01-02T17:50:37.479709586Z     current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
2024-01-02T17:50:37.479713586Z                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-02T17:50:37.479717586Z   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 80, in get_api
2024-01-02T17:50:37.479721544Z     return get_json_from_url("http://" + api_address + path)
2024-01-02T17:50:37.479725669Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-02T17:50:37.479729461Z   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 75, in get_json_from_url
2024-01-02T17:50:37.479733419Z     raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
2024-01-02T17:50:37.479737544Z RuntimeError: Failed to get "http://localhost:10000/storage_service/scylla_release_version" due to the following error: <urlopen error [Errno 99] Cannot assign requested address>
```

But running it on a single-network single IPv4 address is just fine:

```
2024-01-02T17:54:24.243506969Z INFO  2024-01-02 17:54:24,240 [shard 0:stat] cql_server_controller - Starting listening for CQL clients on 192.168.128.6:9042 (unencrypted, non-shard-aware)
2024-01-02T17:54:24.243964052Z INFO  2024-01-02 17:54:24,243 [shard 0:stat] cql_server_controller - Starting listening for CQL clients on 192.168.128.6:19042 (unencrypted, shard-aware)
2024-01-02T17:54:24.261425635Z INFO  2024-01-02 17:54:24,260 [shard 0:main] init - serving
2024-01-02T17:54:24.262653760Z INFO  2024-01-02 17:54:24,261 [shard 0:main] init - Scylla version 5.4.0-0.20231205.58a89e7a4231 initialization completed.
```

though still getting an error

```
2024-01-02T17:58:34.966135501Z Traceback (most recent call last):
2024-01-02T17:58:34.966360376Z   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 196, in <module>
2024-01-02T17:58:34.967481960Z     args.func(args)
2024-01-02T17:58:34.967497251Z   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 122, in check_version
2024-01-02T17:58:34.967499751Z     current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
2024-01-02T17:58:34.967501876Z                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-02T17:58:34.967503751Z   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 80, in get_api
2024-01-02T17:58:34.967505585Z     return get_json_from_url("http://" + api_address + path)
2024-01-02T17:58:34.967507418Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-01-02T17:58:34.967509293Z   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 75, in get_json_from_url
2024-01-02T17:58:34.967511168Z     raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
2024-01-02T17:58:34.967513168Z RuntimeError: Failed to get "http://localhost:10000/storage_service/scylla_release_version" due to the following error: HTTP Error 404: Not Found
```

**Comment by erulabs** [comment]
Heya @demming - I think [scylla_dev_mode_setup is here](https://github.com/scylladb/scylladb/blob/master/dist/common/scripts/scylla_dev_mode_setup), although I dont know why it doesn't show up in your search!

It appears the default for `listen-address` should come from `hostname -i` ([code here](https://github.com/scylladb/scylladb/blob/master/dist/docker/scyllasetup.py#L104-L106)).

**Comment by fee-mendes** [comment]
Reported on Users Slack: https://scylladb-users.slack.com/archives/C2NLNBXLN/p1710924957374639 - same thingy involving multiple addresses during `ScyllaSetup`
