### ISSUE TITLE
scylla_util.py: apt_install() conflicts with unattended-upgr

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylladb#16537]
This will not happens on our machine-image, but would happens on normal Ubuntu image.
When we run apt_install(), it will cause Traceback if unattended-upgr is running on same time:
```
Do you want to enable coredumps?
Yes - sets up coredump to allow a post-mortem analysis of the Scylla state just prior to a crash. No - skips this step.
[YES/no]
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 4440 (unattended-upgr)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_coredump_setup", line 46, in <module>
    pkg_install('systemd-coredump')
  File "/opt/scylladb/scripts/scylla_util.py", line 350, in pkg_install
    return apt_install(pkg)
           ^^^^^^^^^^^^^^^^
  File "/opt/scylladb/scripts/scylla_util.py", line 321, in apt_install
    return run(f'apt-get install -y {pkg}', shell=True, check=True, env=apt_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/python3/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'apt-get install -y systemd-coredump' returned non-zero exit status 100.
Debug log created: /var/tmp/scylla/scylla_coredump_setup-11673-debug.log
coredump setup failed. Press any key to continue...
```

We should detect dpkg is locking, and retry to run apt-get install.

**Comment by syuu1228** [comment]
I guess this would easily happens when the instance is just newly launched, since the instance should have package to upgrade, and package upgrading may takes a while to finish.
