### ISSUE TITLE
nodetool.test_drain is flaky: the mock server returns something cannot be decoded as JSON

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#16542]
```
failed on setup with "requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"
...

    @pytest.fixture(scope="session")
    def rest_api_mock_server():
        ip = f"127.{random.randint(0, 255)}.{random.randint(0, 255)}.{random.randint(0, 255)}"
        port = random.randint(10000, 65535)
 ...
        while True:
            try:
>               rest_api_mock.get_expected_requests(server)

...
test/nodetool/rest_api_mock.py:236: in get_expected_requests
    return [_make_expected_request(r) for r in r.json()]

...
    def json(self, **kwargs):
        r"""Returns the json-encoded content of a response, if any.
...
>           raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
E           requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5388/testReport/junit/test.nodetool/test_drain/Tests___Unit_Tests___test_drain/

**Comment by nyh** [comment]
Seen again in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5754/. I don't think  the problem is the JSON, it's a setup problem which causes all the tests to fail in the same way, check out https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5754/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___nodetool_test_snapshot_release_2/ : 
```
=== TEST.PY TEST nodetool.test_snapshot.2 OUTPUT ===
============================= test session starts ==============================
platform linux -- Python 3.11.6, pytest-7.2.2, pluggy-1.0.0
rootdir: /jenkins/workspace/scylla-master/scylla-ci/scylla, configfile: tox.ini
plugins: asyncio-0.20.3
asyncio: mode=Mode.STRICT
collected 46 items

test/nodetool/test_snapshot.py EEEE/jenkins/workspace/scylla-master/scylla-ci/scylla/test/nodetool/rest_api_mock.py:204: DeprecationWarning: router argument is deprecated
  app = aiohttp.web.Application(router=server)
08:49:10.694 INFO __main__ - start serving
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/nodetool/rest_api_mock.py", line 268, in <module>
    sys.exit(asyncio.run(run_server(sys.argv[1], int(sys.argv[2]))))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/nodetool/rest_api_mock.py", line 211, in run_server
    await site.start()
  File "/usr/lib64/python3.11/site-packages/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 1525, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.233.129.44', 44271): address already in use
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
```

**Comment by tchaikov** [comment]
spotted again,  see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5754/testReport/junit/test.nodetool/test_snapshot/Tests___Unit_Tests___test_clearnapshot/

```
failed on setup with "requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"
...
self = <Response [200]>, kwargs = {}

    def json(self, **kwargs):
...
self = <json.decoder.JSONDecoder object at 0x7f2ffc63d650>
s = '<!doctype html><html lang="en"><head><meta charset="utf-8"/><base href="/"/><meta content="width=device-width,initial..."./images/background-wave-orig2.svg"/></div><div id="loader-block"><img src="./Loader.svg"/></div></div></body></html>'
idx = 0

    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
        a JSON document) and return a 2-tuple of the Python
        representation and the index in ``s`` where the document ended.
    
        This can be used to decode a JSON document from a string that may
        have extraneous data at the end.
    
        """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration as err:
>           raise JSONDecodeError("Expecting value", s, err.value) from None
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/usr/lib64/python3.11/json/decoder.py:355: JSONDecodeError

During handling of the above exception, another exception occurred:

    @pytest.fixture(scope="session")
    def rest_api_mock_server():
        ip = f"127.{random.randint(0, 255)}.{random.randint(0, 255)}.{random.randint(0, 255)}"
        port = random.randint(10000, 65535)
    
        server_process = subprocess.Popen([
            sys.executable,
            os.path.join(os.path.dirname(__file__), "rest_api_mock.py"),
            ip,
            str(port)])
    
        server = (ip, port)
    
        i = 0
        while True:
            try:
>               rest_api_mock.get_expected_requests(server)

test/nodetool/conftest.py:48: 
...
self = <Response [200]>, kwargs = {}

    def json(self, **kwargs):
    
        try:
            return complexjson.loads(self.text, **kwargs)
        except JSONDecodeError as e:
            # Catch JSON-related errors and raise as requests.JSONDecodeError
            # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
>           raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
E           requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by denesb** [comment]
Backport note: we will possibly want to backport to 5.4, to make CI more stable.
<=5.2 is not affected.
