### ISSUE TITLE
test.py teardown: `'NoneType' object has no attribute 'kill'`

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#16651]
To investigate https://github.com/scylladb/scylladb/issues/16570 I created a reproducer
```python3
@pytest.mark.asyncio
async def test_graceful_shutdown(manager: ManagerClient) -> None:
    logger.info(f"Booting initial cluster")
    servers = await manager.servers_add(5)

    async def task(srv_id: ServerNum) -> None:
        for _ in range(10):
            log = await manager.server_open_log(srv_id)
            mark = await log.mark()
            logger.info(f"Stopping {srv_id}")
            await manager.server_stop_gracefully(srv_id)
            logger.info(f"Starting {srv_id}")
            await manager.server_start(srv_id)
            logger.info(f"Started {srv_id}")
            matches = await log.grep("ERROR ", from_mark = mark)
            if matches:
                line, _ = matches[0]
                pytest.fail(f"ERROR detected in {srv_id}: {line}")

    tasks = [asyncio.create_task(task(s.server_id)) for s in servers]
    await asyncio.gather(*tasks)
```

looks like there's some kind of race, perhaps between `stop_gracefully()` and `stop()` -- the latter called during test/suite teardown -- when one of the concurrent `task` fails while another is still trying to stop one of the servers gracefully.

The result:
```
$ ./test.py --mode dev test_graceful_shutdown --repeat 10
Found 10 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------
[1/10]     topology_custom   dev   [ FAIL ] topology_custom.test_graceful_shutdown.1
[2/10]     topology_custom   dev   [ FAIL ] topology_custom.test_graceful_shutdown.2
[3/10]     topology_custom   dev   [ FAIL ] topology_custom.test_graceful_shutdown.10
'NoneType' object has no attribute 'kill'
Traceback (most recent call last):
  File "/home/kbr/dev/scylla/./test.py", line 1615, in workaround_python26789
    code = await main()
           ^^^^^^^^^^^^
  File "/home/kbr/dev/scylla/./test.py", line 1582, in main
    await run_all_tests(signaled, options)
  File "/home/kbr/dev/scylla/./test.py", line 1365, in run_all_tests
    await reap(done, pending, signaled)
  File "/home/kbr/dev/scylla/./test.py", line 1342, in reap
    result = coro.result()
             ^^^^^^^^^^^^^
  File "/home/kbr/dev/scylla/./test.py", line 201, in run
    await test.run(options)
  File "/home/kbr/dev/scylla/./test.py", line 957, in run
    async with get_cluster_manager(self.mode + '/' + self.uname, self.suite.clusters, test_path) as manager:
  File "/usr/lib64/python3.11/contextlib.py", line 211, in __aexit__
    await anext(self.gen)
  File "/home/kbr/dev/scylla/test/pylib/scylla_cluster.py", line 1398, in get_cluster_manager
    await manager.stop()
  File "/home/kbr/dev/scylla/test/pylib/scylla_cluster.py", line 1070, in stop
    await self.clusters.put(self.cluster, is_dirty=True)
  File "/home/kbr/dev/scylla/test/pylib/pool.py", line 104, in put
    await self.destroy(obj)
  File "/home/kbr/dev/scylla/./test.py", line 368, in recycle_cluster
    await cluster.stop()
  File "/home/kbr/dev/scylla/test/pylib/scylla_cluster.py", line 687, in stop
    await asyncio.gather(*(server.stop() for server in self.running.values()))
  File "/home/kbr/dev/scylla/test/pylib/scylla_cluster.py", line 516, in stop
    self.cmd.kill()
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'kill'
```

I see that `stop()` is protected with a `stop_lock`, perhaps `stop_gracefully()` requires the same lock.

```python3
$ ./test.py --mode dev test_graceful_shutdown --repeat 10
Found 10 tests.
================================================================================
[N/TOTAL]   SUITE    MODE   RESULT   TEST
------------------------------------------------------------------------------
[1/10]     topology_custom   dev   [ FAIL ] topology_custom.test_graceful_shutdown.1
[2/10]     topology_custom   dev   [ FAIL ] topology_custom.test_graceful_shutdown.2
[3/10]     topology_custom   dev   [ FAIL ] topology_custom.test_graceful_shutdown.10
'NoneType' object has no attribute 'kill'
Traceback (most recent call last):
  File "/home/kbr/dev/scylla/./test.py", line 1615, in workaround_python26789
    code = await main()
           ^^^^^^^^^^^^
  File "/home/kbr/dev/scylla/./test.py", line 1582, in main
    await run_all_tests(signaled, options)
  File "/home/kbr/dev/scylla/./test.py", line 1365, in run_all_tests
    await reap(done, pending, signaled)
  File "/home/kbr/dev/scylla/./test.py", line 1342, in reap
    result = coro.result()
             ^^^^^^^^^^^^^
  File "/home/kbr/dev/scylla/./test.py", line 201, in run
    await test.run(options)
  File "/home/kbr/dev/scylla/./test.py", line 957, in run
    async with get_cluster_manager(self.mode + '/' + self.uname, self.suite.clusters, test_path) as manager:
  File "/usr/lib64/python3.11/contextlib.py", line 211, in __aexit__
    await anext(self.gen)
  File "/home/kbr/dev/scylla/test/pylib/scylla_cluster.py", line 1398, in get_cluster_manager
    await manager.stop()
  File "/home/kbr/dev/scylla/test/pylib/scylla_cluster.py", line 1070, in stop
    await self.clusters.put(self.cluster, is_dirty=True)
  File "/home/kbr/dev/scylla/test/pylib/pool.py", line 104, in put
    await self.destroy(obj)
  File "/home/kbr/dev/scylla/./test.py", line 368, in recycle_cluster
    await cluster.stop()
  File "/home/kbr/dev/scylla/test/pylib/scylla_cluster.py", line 687, in stop
    await asyncio.gather(*(server.stop() for server in self.running.values()))
  File "/home/kbr/dev/scylla/test/pylib/scylla_cluster.py", line 516, in stop
    self.cmd.kill()
    ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'kill'
```

**Comment by xtrey** [comment]
@kbr-scylla I've tried to reproduce this issue, but unfortunately without success. I have another error:
```
shard 0:strm] rpc - client 127.168.59.18:53142: server connection dropped: Semaphore broken
```
There is some error but this error is not from test.py. It seems Seastar or Scylla is throwing this error. I've seen such errors while working on a fix https://github.com/scylladb/scylladb/pull/17781 but it was an indicator of incorrect usage of gather in asyncio.
Have you happened to see this issue recently?

**Comment by temichus** [comment]
@kbr-scylla here is exactly the same situation as in https://github.com/scylladb/scylladb/pull/17781 (https://github.com/scylladb/scylladb/issues/16472)

there is concurrent  stop(recycle_cluster)+stop_gracefully(test body) and stop(recycle_cluster)+start(test body) 
and the problem is the same recycle_cluster started when COROs triggered by the test are still running.

with safe_gather(and other sujjested solutions in [PR](https://github.com/scylladb/scylladb/pull/17781)) it will work. going to discuss with @kostja @xtrey  how else we can deal with such races

**Comment by kbr-scylla** [comment]
>  Have you happened to see this issue recently?

No, IIRC I only stumbled upon this with the reproducer provided in original post, that reproducer wasn't merged into the repository.
