### ISSUE TITLE
Docker on macOS fails with: "Could not setup Async I/O: Resource temporarily unavailable." (solution: add '--reactor-backend=epoll' to the command line)

### ISSUE THREAD

**Issue by GeoffMontee** [scylladb/scylladb#16806]
When a multi-node cluster is setup on macOS using Docker, it fails with:

```
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
```

The suggested workaround is not valid for macOS.

### macOS Information

* MacBook Pro
* Apple M3 Pro CPU
* 36 GB Memory
* macOS 14.2.1
* Docker is installed via Homebrew: https://dev.to/elliotalexander/how-to-use-docker-without-docker-desktop-on-macos-217m

### Steps to reproduce

1. Try to tweak the Async I/O settings for the macOS kernel:

```
sysctl -a | grep aio
```
```
kern.aiomax: 90
kern.aioprocmax: 16
kern.aiothreads: 4
```

```
sudo sysctl kern.aiomax=1000 
```
```
kern.aiomax: 90 -> 1000
```

```
sudo sysctl kern.aioprocmax=1000
```
```
kern.aioprocmax: 16 -> 1000
```

```
sudo sysctl kern.aiothreads=1000
```
```
kern.aiothreads: 4 -> 1000
```

```
sysctl -a | grep aio     
```
```
kern.aiomax: 1000
kern.aioprocmax: 1000
kern.aiothreads: 1000
```

2. Create a first node:

```
 docker run --name Node_X -d scylladb/scylla:5.2.0 --overprovisioned 1 --smp 1
```

3. Create two more nodes:

```
docker run --name Node_Y -d scylladb/scylla:5.2.0 --seeds="$(docker inspect --format='{{ .NetworkSettings.IPAddress }}' Node_X)" --overprovisioned 1 --smp 1
```

```
docker run --name Node_Z -d scylladb/scylla:5.2.0 --seeds="$(docker inspect --format='{{ .NetworkSettings.IPAddress }}' Node_X)" --overprovisioned 1 --smp 1
```

4. Check the cluster status:

```
docker exec -it Node_X nodetool status  
```

5. Check the node logs:

```
docker logs Node_Y
```

```
docker logs Node_Z 
```

### Actual results

Only the first node started successfully:

```
% docker exec -it Node_X nodetool status  
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  172.17.0.3  204 KB     256          ?       efcf9bb9-c015-48cb-9a2a-f6a2e4c647ea  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

The other nodes have an Async I/O error in their logs:

```
% docker logs Node_Y             
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '1'],)
running: (['/opt/scylladb/scripts/scylla_io_setup'],)
2024-01-16 18:40:41,898 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-01-16 18:40:41,898 INFO Included extra file "/etc/supervisord.conf.d/rsyslog.conf" during parsing
2024-01-16 18:40:41,898 INFO Included extra file "/etc/supervisord.conf.d/scylla-housekeeping.conf" during parsing
2024-01-16 18:40:41,898 INFO Included extra file "/etc/supervisord.conf.d/scylla-jmx.conf" during parsing
2024-01-16 18:40:41,898 INFO Included extra file "/etc/supervisord.conf.d/scylla-node-exporter.conf" during parsing
2024-01-16 18:40:41,898 INFO Included extra file "/etc/supervisord.conf.d/scylla-server.conf" during parsing
2024-01-16 18:40:41,898 INFO Included extra file "/etc/supervisord.conf.d/sshd-server.conf" during parsing
2024-01-16 18:40:41,899 INFO RPC interface 'supervisor' initialized
2024-01-16 18:40:41,899 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2024-01-16 18:40:41,899 INFO supervisord started with pid 26
2024-01-16 18:40:42,905 INFO spawned: 'rsyslog' with pid 27
2024-01-16 18:40:42,909 INFO spawned: 'scylla' with pid 28
2024-01-16 18:40:42,911 INFO spawned: 'scylla-housekeeping' with pid 29
2024-01-16 18:40:42,913 INFO spawned: 'scylla-jmx' with pid 30
2024-01-16 18:40:42,915 INFO spawned: 'scylla-node-exporter' with pid 31
2024-01-16 18:40:42,923 INFO spawned: 'sshd' with pid 33
rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
rsyslogd: activation of module imklog failed [v8.2112.0 try https://www.rsyslog.com/e/2145 ]
ts=2024-01-16T18:40:42.946Z caller=node_exporter.go:182 level=info msg="Starting node_exporter" version="(version=1.4.0, branch=HEAD, revision=7da1321761b3b8dfc9e496e1a60e6a476fec6018)"
ts=2024-01-16T18:40:42.946Z caller=node_exporter.go:183 level=info msg="Build context" build_context="(go=go1.19.1, user=root@83d90983e89c, date=20220926-12:33:37)"
ts=2024-01-16T18:40:42.946Z caller=node_exporter.go:185 level=warn msg="Node Exporter is running as root user. This exporter is designed to run as unprivileged user, root is not required."
ts=2024-01-16T18:40:42.946Z caller=diskstats_common.go:100 level=info collector=diskstats msg="Parsed flag --collector.diskstats.device-exclude" flag=^(ram|loop|fd|(h|s|v|xv)d[a-z]|nvme\d+n\d+p)\d+$
ts=2024-01-16T18:40:42.946Z caller=diskstats_linux.go:264 level=error collector=diskstats msg="Failed to open directory, disabling udev device properties" path=/run/udev/data
ts=2024-01-16T18:40:42.946Z caller=filesystem_common.go:111 level=info collector=filesystem msg="Parsed flag --collector.filesystem.mount-points-exclude" flag=^/(dev|proc|run/credentials/.+|sys|var/lib/docker/.+|var/lib/containers/storage/.+)($|/)
ts=2024-01-16T18:40:42.947Z caller=filesystem_common.go:113 level=info collector=filesystem msg="Parsed flag --collector.filesystem.fs-types-exclude" flag=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:108 level=info msg="Enabled collectors"
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=arp
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=bcache
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=bonding
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=btrfs
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=conntrack
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=cpu
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=cpufreq
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=diskstats
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=dmi
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=edac
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=entropy
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=fibrechannel
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=filefd
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=filesystem
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=hwmon
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=infiniband
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=interrupts
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=ipvs
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=loadavg
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=mdadm
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=meminfo
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=netclass
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=netdev
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=netstat
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=nfs
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=nfsd
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=nvme
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=os
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=powersupplyclass
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=pressure
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=rapl
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=schedstat
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=selinux
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=sockstat
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=softnet
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=stat
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=tapestats
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=textfile
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=thermal_zone
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=time
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=timex
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=udp_queues
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=uname
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=vmstat
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=xfs
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:115 level=info collector=zfs
ts=2024-01-16T18:40:42.947Z caller=node_exporter.go:199 level=info msg="Listening on" address=:9100
ts=2024-01-16T18:40:42.947Z caller=tls_config.go:195 level=info msg="TLS is disabled." http2=false
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
Connecting to http://localhost:100002024-01-16 18:40:43,158 INFO exited: scylla (exit status 7; not expected)

Starting the JMX server
JMX is enabled to receive remote connections on port: 7199
2024-01-16 18:40:44,260 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-01-16 18:40:44,262 INFO spawned: 'scylla' with pid 77
2024-01-16 18:40:44,263 INFO success: scylla-housekeeping entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-01-16 18:40:44,263 INFO success: scylla-jmx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-01-16 18:40:44,263 INFO success: scylla-node-exporter entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-01-16 18:40:44,263 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
2024-01-16 18:40:44,356 INFO exited: scylla (exit status 7; not expected)
2024-01-16 18:40:46,365 INFO spawned: 'scylla' with pid 88
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
2024-01-16 18:40:46,458 INFO exited: scylla (exit status 7; not expected)
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 196, in <module>
    args.func(args)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 122, in check_version
    current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 80, in get_api
    return get_json_from_url("http://" + api_address + path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 75, in get_json_from_url
    raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
RuntimeError: Failed to get "http://localhost:10000/storage_service/scylla_release_version" due to the following error: <urlopen error [Errno 99] Cannot assign requested address>
2024-01-16 18:40:50,157 INFO spawned: 'scylla' with pid 111
FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)
2024-01-16 18:40:50,250 INFO exited: scylla (exit status 7; not expected)
2024-01-16 18:40:51,257 INFO gave up: scylla entered FATAL state, too many start retries too quickly
```

### Expected results

I would have expexcted all 3 nodes to start properly and join the cluster.

**Comment by GeoffMontee** [comment]
The above commands use the "5.2.0" image, because that is the one deployed in the Scylla University labs. However, the same problem is seen with the "latest" image.

**Comment by GeoffMontee** [comment]
Someone else reported the same problem in the forum a few months ago: https://forum.scylladb.com/t/running-3-node-scylladb-in-docker/1057

**Comment by roydahan** [comment]
On a intel based chip with “2.8 GHz Quad-Core Intel Core i7” I’m able to start a 3 node cluster, each with --smp 1.

$ sysctl -n hw.ncpu
8

sysctl -a | grep aio
kern.aiomax: 90
kern.aioprocmax: 16
kern.aiothreads: 4

 $ docker exec -it some-scylla nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  172.17.0.3  572 KB     256          ?       0028d9e0-e771-45eb-b922-f15660b7b3a8  rack1
UN  172.17.0.2  500 KB     256          ?       06a0db13-20a1-43a8-a7ff-c60c0128066b  rack1
UN  172.17.0.4  696 KB     256          ?       f136cc48-1b17-4626-b584-d2898d87f8f1  rack1

However, on a apple chip based (Apple M3 Pro), 2 nodes starts ok with --smp 1, but the 3 node has the issue of max-aio-nr.

sysctl -n hw.ncpu
11

sysctl -a | grep aio
kern.aiomax: 90
kern.aioprocmax: 16
kern.aiothreads: 4

**Comment by roydahan** [comment]
We could relax the requirement of the max-aio-nr calculation when using developer-mode, however we think it may hit this issue: https://github.com/scylladb/seastar/issues/1784, although @bhalevy suggested a fix for it.

**Comment by gjjohnson** [comment]
FYI:  It is happening on Ubuntu Linux too.

I have a similar problem running on Ubuntu 22.04 on an Intel Core i5-4570 (4 core / 24GB memory)

I am attempting to set up a 3-node cluster on Docker as documented in S101: ScyllaDB Essentials.
On a 3-node Docker cluster, I am able to start Node_X and Node_Y, but Node_Z fails with the following error:

FATAL: Exception during startup, aborting: std::runtime_error (Could not setup Async I/O: Resource temporarily unavailable. The most common cause is not enough request capacity in /proc/sys/fs/aio-max-nr. Try increasing that number or reducing the amount of logical CPUs available for your application)

This is after applying the update to aio-max-nr documented in the 3-node container install
gjjohnson@M93p:~$ sudo sysctl -a|grep -i aio
fs.aio-max-nr = 1048576
fs.aio-nr = 0

**Comment by mxsdev** [comment]
Having the same issue here :/

**Comment by roydahan** [comment]
@bhalevy can you help promoting your seastar fix?

@yaronkaikov FYI for the docker CI test.

**Comment by bhalevy** [comment]
> @bhalevy can you help promoting your seastar fix?
> 

It's up to @avikivity.
The thing is that, IIRC, we're not supposed to need it if aio_max_nr is set up correctly and only scylla is consuming from it.
Can you please comment on the seastar issue about this need so we have the discussion there?

**Comment by avikivity** [comment]
@syuu1228 I thought we added automatic fallback to epoll? Maybe I misremember.

**Comment by roydahan** [comment]
As @avikivity wrote in the relevant sestar issue, there is an easy workaround that works also in macOS.
You can start scylla with the following flag: "**--reactor-backend=epoll**"

For Example:
```
docker run --name some-scylla --hostname some-scylla -d scylladb/scylla --reactor-backend=epoll
docker run --name some-scylla2  --hostname some-scylla2 -d scylladb/scylla --reactor-backend=epoll --seeds="$(docker inspect --format='{{ .NetworkSettings.IPAddress }}' some-scylla)"
docker run --name some-scylla3  --hostname some-scylla3 -d scylladb/scylla --reactor-backend=epoll --seeds="$(docker inspect --format='{{ .NetworkSettings.IPAddress }}' some-scylla)"

15:53 roy@macbook-pro ~ () $ docker exec -it some-scylla nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  172.17.0.3  369.39 KB  256          ?       dd207e02-468e-48c2-91ca-336cafff8f2f  rack1
UN  172.17.0.2  186.78 KB  256          ?       fa67ef85-468d-4c7c-8275-46bc3a6931e5  rack1
UN  172.17.0.4  566.11 KB  256          ?       444b5568-4500-410b-b1b0-2676c4f908cc  rack1

```

**Comment by gjjohnson** [comment]
That seems to work for me -- I am able to start three nodes successfully.

docker run --name scylla-node1a --hostname scylla-node1a -d
scylladb/scylla:5.2.0 --reactor-backend=epoll
docker run --name scylla-node2a --hostname scylla-node2a -d
scylladb/scylla:5.2.0 --reactor-backend=epoll --seeds="$(docker inspect
--format='{{ .NetworkSettings.IPAddress }}' scylla-node1a)"
docker run --name scylla-node3a --hostname scylla-node3a -d
scylladb/scylla:5.2.0 --reactor-backend=epoll --seeds="$(docker inspect
--format='{{ .NetworkSettings.IPAddress }}' scylla-node1a)"


#Log scylla-node1a
2024-01-25 07:34:23 INFO  2024-01-25 15:34:23,899 [shard 0]
cql_server_controller - Starting listening for CQL clients on
172.17.0.2:19042 (unencrypted, shard-aware)
2024-01-25 07:34:23 INFO  2024-01-25 15:34:23,903 [shard 0] init - serving
2024-01-25 07:34:23 INFO  2024-01-25 15:34:23,903 [shard 0] init - Scylla
version 5.2.0-0.20230427.429b696bbc1b initialization completed.

#Log scylla-node2a
2024-01-25 07:37:13 INFO  2024-01-25 15:37:13,021 [shard 0]
cql_server_controller - Starting listening for CQL clients on
172.17.0.3:19042 (unencrypted, shard-aware)
2024-01-25 07:37:13 INFO  2024-01-25 15:37:13,023 [shard 0] init - serving
2024-01-25 07:37:13 INFO  2024-01-25 15:37:13,023 [shard 0] init - Scylla
version 5.2.0-0.20230427.429b696bbc1b initialization completed.

#Log scylla-node3a
2024-01-25 07:40:51 INFO  2024-01-25 15:40:51,553 [shard 0]
cql_server_controller - Starting listening for CQL clients on
172.17.0.4:19042 (unencrypted, shard-aware)
2024-01-25 07:40:51 INFO  2024-01-25 15:40:51,557 [shard 0] init - serving
2024-01-25 07:40:51 INFO  2024-01-25 15:40:51,557 [shard 0] init - Scylla
version 5.2.0-0.20230427.429b696bbc1b initialization completed.




docker exec -it scylla-node1a nodetool status

***@***.***:~$ docker exec -it scylla-node1a nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID
          Rack
UN  172.17.0.3  1.12 MB    256          ?
70bb9259-2378-430e-bd79-87b696c9ce63  rack1
UN  172.17.0.2  712 KB     256          ?
f0ef003b-d9b8-4a39-826d-42b5b4cbc802  rack1
UN  172.17.0.4  1.33 MB    256          ?
134c69d6-a1ac-4e89-a4a4-d322a0ec831d  rack1


Will the Scylla University lab instructions be updated to include:
 --reactor-backend=epoll

Thanks!

George J Johnson

**Comment by mykaul** [comment]
CC @guy9 for including this info in Scylla Uni (or a KB?)

**Comment by tzach** [comment]
Best will be to add it in the docker pages:
https://opensource.docs.scylladb.com/stable/operating-scylla/procedures/tips/best-practices-scylla-on-docker.html
https://hub.docker.com/r/scylladb/scylla/

**Comment by pogzie** [comment]
MacBook Pro 13-inch 2019
2.8 GHz Quad-Core Intel Core i7
Intel Iris Plus Graphics 655 1536 MB
16 GB 2133 MHz LPDDR3
Sonoma 14.2.1 (23C71)

Docker Desktop 4.25.0 (126437)
Engine: 24.0.6
CPU limit: 8
Memory limit: 12GB
Swap: 4GB
Virtual disk limit 64GB
Docker subnet: 192.168.65.0/24

Trying `docker run --name scylla-node1 -d scylladb/scylla:5.2.0 -–reactor-backend=epoll` im not having any luck: 

```
2024-02-05 13:08:41 2024-02-05 05:08:41,675 INFO exited: scylla (exit status 2; not expected)
2024-02-05 13:08:43 2024-02-05 05:08:43,681 INFO spawned: 'scylla' with pid 87
2024-02-05 13:08:43 Scylla version 5.2.0-0.20230427.429b696bbc1b with build-id 9736db0414bad938b1d5d959bb25fbb4fb8558ce starting ...
2024-02-05 13:08:43 command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.2 --rpc-address 172.17.0.2 --seed-provider-parameters seeds=172.17.0.2 --alternator-address 172.17.0.2 --blocked-reactor-notify-ms 999999999 -–reactor-backend=epoll"
2024-02-05 13:08:43 parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.2, rpc-address: 172.17.0.2, seed-provider-parameters: seeds=172.17.0.2, alternator-address: 172.17.0.2, blocked-reactor-notify-ms, (positional) 999999999, -�: ��reactor-backend=epoll]
2024-02-05 13:08:43 error: unrecognised option '-–reactor-backend=epoll'
2024-02-05 13:08:43 
2024-02-05 13:08:43 Try --help.
2024-02-05 13:08:43 2024-02-05 05:08:43,868 INFO exited: scylla (exit status 2; not expected)
2024-02-05 13:08:45 Traceback (most recent call last):
2024-02-05 13:08:45   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 196, in <module>
2024-02-05 13:08:45     args.func(args)
2024-02-05 13:08:45   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 122, in check_version
2024-02-05 13:08:45     current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
2024-02-05 13:08:45                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-05 13:08:45   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 80, in get_api
2024-02-05 13:08:45     return get_json_from_url("http://" + api_address + path)
2024-02-05 13:08:45            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-05 13:08:45   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 75, in get_json_from_url
2024-02-05 13:08:45     raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
2024-02-05 13:08:45 RuntimeError: Failed to get "http://localhost:10000/storage_service/scylla_release_version" due to the following error: <urlopen error [Errno 99] Cannot assign requested address>
2024-02-05 13:08:47 2024-02-05 05:08:47,217 INFO spawned: 'scylla' with pid 110
2024-02-05 13:08:47 Scylla version 5.2.0-0.20230427.429b696bbc1b with build-id 9736db0414bad938b1d5d959bb25fbb4fb8558ce starting ...
2024-02-05 13:08:47 command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.2 --rpc-address 172.17.0.2 --seed-provider-parameters seeds=172.17.0.2 --alternator-address 172.17.0.2 --blocked-reactor-notify-ms 999999999 -–reactor-backend=epoll"
2024-02-05 13:08:47 parsed command line options: [log-to-syslog, (positional) 0, log-to-stdout, (positional) 1, default-log-level, (positional) info, network-stack, (positional) posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.2, rpc-address: 172.17.0.2, seed-provider-parameters: seeds=172.17.0.2, alternator-address: 172.17.0.2, blocked-reactor-notify-ms, (positional) 999999999, -�: ��reactor-backend=epoll]
2024-02-05 13:08:47 error: unrecognised option '-–reactor-backend=epoll'
2024-02-05 13:08:47 
2024-02-05 13:08:47 Try --help.
2024-02-05 13:08:47 2024-02-05 05:08:47,402 INFO exited: scylla (exit status 2; not expected)
2024-02-05 13:08:48 2024-02-05 05:08:48,404 INFO gave up: scylla entered FATAL state, too many start retries too quickly
```

Flag doesnt seem to exist in 5.2.0 (following Scylla University steps)? I did try again on `5.4.2-0.20240117` same issue tho.

**Comment by mykaul** [comment]
@pogzie - can you please try again, make sure you are using '--' and not '-–' ?

**Comment by avikivity** [comment]
Yes we did:

```c++
    auto aio_max_nr = read_first_line_as<unsigned>("/proc/sys/fs/aio-max-nr");
    auto aio_nr = read_first_line_as<unsigned>("/proc/sys/fs/aio-nr");
    auto available_aio = aio_max_nr - aio_nr;
    auto requested_aio_network = network_iocbs * smp::count;
```

**Comment by avikivity** [comment]
ah, that just fails, we should fall back to epoll

**Comment by guy9** [comment]
> star issue, there is an easy workaround that works also in macOS.
> You can start scylla with the following flag: "**--reactor-backend=epoll**"

CC @annastuchlik

**Comment by pdbossman** [comment]
Some earlier versions of Docker Desktop on Mac , the '--reactor-backend=epoll' was not recognized.
Unfortunately, we did not capture the affected version before upgrading and resolving the issue.

Additional remedies:
1. On the older version, Rosetta option was available and selected, de-selecting Rosetta worked.
2. Upgrading Docker Desktop to 4.28.0+ also resolved the issue.  (Rosetta could be selecteded or not)
