### ISSUE TITLE
test/topology/test_mutation_schema_change.py::test_mutation_schema_change_restart fails due to "failed to start the node" when setup the test

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#16926]
```
06:36:04  23:42:39.854 DEBUG> RESTClient fetching GET http+unix://api/cluster/is-dirty
06:36:04  23:42:40.556 DEBUG> after_test for test_mutation_schema_change_restart (success: True)
06:36:04  23:42:40.556 DEBUG> RESTClient fetching PUT http+unix://api/cluster/after-test/True
06:36:04  23:42:40.812 WARNING> Error attempting to reconnect to 127.227.191.12:9042, scheduling retry in 1.9 seconds: [Errno 111] Tried connecting to [('127.227.191.12', 9042)]. Last error: Connection refused
06:36:04  23:42:40.812 DEBUG> Reconnection error details
06:36:04  Traceback (most recent call last):
06:36:04    File "cassandra/pool.py", line 285, in cassandra.pool._ReconnectionHandler.run
06:36:04    File "cassandra/pool.py", line 356, in cassandra.pool._HostReconnectionHandler.try_reconnect
06:36:04    File "cassandra/connection.py", line 876, in cassandra.connection.Connection.factory
06:36:04    File "/usr/local/lib64/python3.11/site-packages/cassandra/io/libevreactor.py", line 267, in __init__
06:36:04      self._connect_socket()
06:36:04    File "cassandra/connection.py", line 955, in cassandra.connection.Connection._connect_socket
06:36:04  ConnectionRefusedError: [Errno 111] Tried connecting to [('127.227.191.12', 9042)]. Last error: Connection refused
06:36:04  23:42:40.974 INFO> Cluster after test test_mutation_schema_change_restart: ScyllaCluster(name: fe6ba8d4-b96e-11ee-9cbf-12b739c9b4c9, running: ScyllaServer(82, 127.227.191.14, 98866c81-433f-4c32-9e0a-f31945c87cb3), ScyllaServer(84, 127.227.191.13, 1a69ab13-0d68-4568-b105-988e5158ad6a), stopped: ScyllaServer(83, 127.227.191.12, a46447ea-2694-4508-b51e-7f4ca6b26b0b))
...
06:36:04  ==================================== ERRORS ====================================
06:36:04  ________________ ERROR at setup of test_mutation_schema_change _________________
06:36:04  
...
06:36:04  test/topology/conftest.py:174: in manager
06:36:04      await manager_internal.before_test(test_case_name)
06:36:04  test/pylib/manager_client.py:92: in before_test
06:36:04      cluster_str = await self.client.put_json(f"/cluster/before-test/{test_case_name}", timeout=600,
06:36:04  test/pylib/rest_client.py:111: in put_json
06:36:04      ret = await self._fetch("PUT", resource_uri, response_type = response_type, host = host,
...
06:36:04      async def _fetch(self, method: str, resource: str, response_type: Optional[str] = None,
06:36:04                       host: Optional[str] = None, port: Optional[int] = None,
06:36:04                       params: Optional[Mapping[str, str]] = None,
06:36:04                       json: Optional[Mapping] = None, timeout: Optional[float] = None) -> Any:
06:36:04          # Can raise exception. See https://docs.aiohttp.org/en/latest/web_exceptions.html
06:36:04          assert method in ["GET", "POST", "PUT", "DELETE"], f"Invalid HTTP request method {method}"
06:36:04          assert response_type is None or response_type in ["text", "json"], \
06:36:04                  f"Invalid response type requested {response_type} (expected 'text' or 'json')"
06:36:04          # Build the URI
06:36:04          port = port if port else self.default_port if hasattr(self, "default_port") else None
06:36:04          port_str = f":{port}" if port else ""
06:36:04          assert host is not None or hasattr(self, "default_host"), "_fetch: missing host for " \
06:36:04                  "{method} {resource}"
06:36:04          host_str = host if host is not None else self.default_host
06:36:04          uri = self.uri_scheme + "://" + host_str + port_str + resource
06:36:04          logging.debug(f"RESTClient fetching {method} {uri}")
06:36:04      
06:36:04          client_timeout = ClientTimeout(total = timeout if timeout is not None else 300)
06:36:04          async with request(method, uri,
06:36:04                             connector = self.connector if hasattr(self, "connector") else None,
06:36:04                             params = params, json = json, timeout = client_timeout) as resp:
06:36:04              if resp.status != 200:
06:36:04                  text = await resp.text()
06:36:04  >               raise HTTPError(uri, resp.status, params, json, text)
06:36:04  E               test.pylib.rest_client.HTTPError: HTTP error 500, uri: http+unix://api/cluster/before-test/test_mutation_schema_change, params: None, json: None, body:
06:36:04  E               Exception when starting cluster ScyllaCluster(name: e8e888d8-b96e-11ee-9cbf-12b739c9b4c9, running: ScyllaServer(79, 127.227.191.12, ab66e994-b239-4ccf-bffd-19f47b33d919), ScyllaServer(81, 127.227.191.14, 6343f1aa-dc2e-4d62-a644-6666dcf3b6f0), stopped: ):
06:36:04  E               failed to start the node, server_id 80, IP 127.227.191.13, workdir scylla-80, host_id 32dddc4e-5abf-4a2a-8a65-5d845a0863a3, cql [not connected]
06:36:04  E               Check the log files:
06:36:04  E               /scylladir/testlog/x86_64/test.py.debug-release-dev.log
06:36:04  E               /scylladir/testlog/x86_64/debug/scylla-80.log
```
see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5988/console

**Comment by tchaikov** [comment]
in `debug/scylla-80.log`:
```
INFO  2024-01-22 23:40:53,975 [shard 0:stmt] cql_server_controller - Setting up maintenance socket on /scylladir/testlog/x86_64/debug/scylla-80/cql.m
INFO  2024-01-22 23:40:53,977 [shard 0:stmt] cql_server_controller - Starting listening for CQL clients on /scylladir/testlog/x86_64/debug/scylla-80/cql.m (unencrypted, non-shard-aware)
INFO  2024-01-22 23:40:53,977 [shard 1:comp] compaction - [Compact system.truncated eb24e970-b96e-11ee-939c-9ecefde385a5] Compacted 2 sstables to [/scylladir/testlog/x86_64/debug/scylla-80/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/md-7-big-Data.db:level=0]. 79kB to 74kB (~93% of original) in 189ms = 420kB/s. ~256 total partitions merged to 6.
WARN  2024-01-22 23:40:53,978 [shard 0:stmt] gossip - Fail to apply application_state: std::runtime_error (endpoint_state_map does not contain endpoint = 127.227.191.13, application_states = {{RPC_READY -> Value(1,1)}})
INFO  2024-01-22 23:40:53,985 [shard 0:main] raft_group0 - Disabling migration_manager schema pulls because Raft is enabled and we're bootstrapping.
...
INFO  2024-01-22 23:41:20,004 [shard 0: gms] repair - repair[272d6489-02cc-4e8a-bb59-fea5848093a7]: sync data for keyspace=system_auth, status=started
INFO  2024-01-22 23:41:20,007 [shard 0: gms] repair - repair[272d6489-02cc-4e8a-bb59-fea5848093a7]: Started to repair 1 out of 3 tables in keyspace=system_auth, table=roles, table_id=5bc52802-de25-35ed-aeab-188eecebb090, repair_reason=bootstrap
INFO  2024-01-22 23:41:20,008 [shard 1: gms] repair - repair[272d6489-02cc-4e8a-bb59-fea5848093a7]: Started to repair 1 out of 3 tables in keyspace=system_auth, table=roles, table_id=5bc52802-de25-35ed-aeab-188eecebb090, repair_reason=bootstrap
WARN  2024-01-22 23:41:20,305 [shard 0: gms] repair - repair[272d6489-02cc-4e8a-bb59-fea5848093a7]: put_row_diff: got error from node=127.227.191.13, keyspace=system_auth, table=roles, range=(-705276614101176816,1298061283201471209], error=std::runtime_error (put_row_diff: Repair follower=127.227.191.14 failed in put_row_diff handler, status=0)
WARN  2024-01-22 23:41:20,305 [shard 0: gms] repair - repair[272d6489-02cc-4e8a-bb59-fea5848093a7]: shard=0, keyspace=system_auth, cf=roles, range=(-705276614101176816,1298061283201471209], got error in row level repair: std::runtime_error (put_row_diff: Repair follower=127.227.191.14 failed in put_row_diff handler, status=0)
INFO  2024-01-22 23:41:20,336 [shard 1: gms] repair - repair[272d6489-02cc-4e8a-bb59-fea5848093a7]: Started to repair 2 out of 3 tables in keyspace=system_auth, table=role_attributes, table_id=6b8c7359-a843-33f2-a1d8-5dc6a187436f, repair_reason=bootstrap
INFO  2024-01-22 23:41:20,347 [shard 0: gms] repair - repair[272d6489-02cc-4e8a-bb59-fea5848093a7]: stats: repair_reason=bootstrap, keyspace=system_auth, tables={roles, role_attributes, role_members}, ranges_nr=17, round_nr=17, round_nr_fast_path_already_synced=16, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=88, tx_hashes_nr=0, rx_hashes_nr=1, duration=0.3426151 seconds, tx_row_nr=1, rx_row_nr=0, tx_row_bytes=178, rx_row_bytes=0, row_from_disk_bytes={{127.227.191.12, 0}, {127.227.191.13, 178}, {127.227.191.14, 0}}, row_from_disk_nr={{127.227.191.12, 0}, {127.227.191.13, 1}, {127.227.191.14, 0}}, row_from_disk_bytes_per_sec={{127.227.191.12, 0}, {127.227.191.13, 0.000495466}, {127.227.191.14, 0}} MiB/s, row_from_disk_rows_per_sec={{127.227.191.12, 0}, {127.227.191.13, 2.91873}, {127.227.191.14, 0}} Rows/s, tx_row_nr_peer={{127.227.191.14, 1}}, rx_row_nr_peer={}
WARN  2024-01-22 23:41:20,347 [shard 0: gms] repair - repair[272d6489-02cc-4e8a-bb59-fea5848093a7]: 1 out of 51 ranges failed, keyspace=system_auth, tables={roles, role_attributes, role_members}, repair_reason=bootstrap, nodes_down_during_repair={}, aborted_by_user=false, failed_because=seastar::nested_exception: std::runtime_error (Failed to repair for keyspace=system_auth, cf=roles, range=(-705276614101176816,1298061283201471209]) (while cleaning up after std::runtime_error (put_row_diff: Repair follower=127.227.191.14 failed in put_row_diff handler, status=0))
INFO  2024-01-22 23:41:20,622 [shard 1: gms] repair - repair[272d6489-02cc-4e8a-bb59-fea5848093a7]: Started to repair 3 out of 3 tables in keyspace=system_auth, table=role_members, table_id=0ecdaa87-f8fb-3e60-88d1-74fb36fe5c0d, repair_reason=bootstrap
INFO  2024-01-22 23:41:20,911 [shard 1: gms] repair - repair[272d6489-02cc-4e8a-bb59-fea5848093a7]: stats: repair_reason=bootstrap, keyspace=system_auth, tables={roles, role_attributes, role_members}, ranges_nr=17, round_nr=51, round_nr_fast_path_already_synced=51, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=0, rpc_call_nr=255, tx_hashes_nr=0, rx_hashes_nr=0, duration=0.90273887 seconds, tx_row_nr=0, rx_row_nr=0, tx_row_bytes=0, rx_row_bytes=0, row_from_disk_bytes={{127.227.191.12, 0}, {127.227.191.13, 0}, {127.227.191.14, 0}}, row_from_disk_nr={{127.227.191.12, 0}, {127.227.191.13, 0}, {127.227.191.14, 0}}, row_from_disk_bytes_per_sec={{127.227.191.12, 0}, {127.227.191.13, 0}, {127.227.191.14, 0}} MiB/s, row_from_disk_rows_per_sec={{127.227.191.12, 0}, {127.227.191.13, 0}, {127.227.191.14, 0}} Rows/s, tx_row_nr_peer={}, rx_row_nr_peer={}
INFO  2024-01-22 23:41:20,911 [shard 1: gms] repair - repair[272d6489-02cc-4e8a-bb59-fea5848093a7]: completed successfully, keyspace=system_auth
WARN  2024-01-22 23:41:20,913 [shard 0: gms] repair - repair[272d6489-02cc-4e8a-bb59-fea5848093a7]: sync data for keyspace=system_auth, status=failed: std::runtime_error ({shard 0: std::runtime_error (repair[272d6489-02cc-4e8a-bb59-fea5848093a7]: 1 out of 51 ranges failed, keyspace=system_auth, tables={roles, role_attributes, role_members}, repair_reason=bootstrap, nodes_down_during_repair={}, aborted_by_user=false, failed_because=seastar::nested_exception: std::runtime_error (Failed to repair for keyspace=system_auth, cf=roles, range=(-705276614101176816,1298061283201471209]) (while cleaning up after std::runtime_error (put_row_diff: Repair follower=127.227.191.14 failed in put_row_diff handler, status=0)))})
ERROR 2024-01-22 23:41:20,914 [shard 0: gms] raft_topology - raft_topology_cmd failed with: std::runtime_error ({shard 0: std::runtime_error (repair[272d6489-02cc-4e8a-bb59-fea5848093a7]: 1 out of 51 ranges failed, keyspace=system_auth, tables={roles, role_attributes, role_members}, repair_reason=bootstrap, nodes_down_during_repair={}, aborted_by_user=false, failed_because=seastar::nested_exception: std::runtime_error (Failed to repair for keyspace=system_auth, cf=roles, range=(-705276614101176816,1298061283201471209]) (while cleaning up after std::runtime_error (put_row_diff: Repair follower=127.227.191.14 failed in put_row_diff handler, status=0)))})
...
INFO  2024-01-22 23:41:21,260 [shard 0:main] init - Shutting down group 0 usage in local storage
ERROR 2024-01-22 23:41:21,260 [shard 0: gms] raft_topology - raft_topology_cmd failed with: raft::request_aborted (Request is aborted by a caller)
INFO  2024-01-22 23:41:21,261 [shard 0:strm] raft_topology - raft_state_monitor_fiber aborted with seastar::abort_requested_exception (abort requested)
INFO  2024-01-22 23:41:21,261 [shard 0:strm] raft_topology - cleanup fiber aborted
INFO  2024-01-22 23:41:21,262 [shard 0:main] init - Shutting down group 0 usage in local storage was successful
...
ERROR 2024-01-22 23:41:24,374 [shard 0:main] init - Startup failed: std::runtime_error (Bootstrap failed. See earlier errors (Rolled back: Failed stream ranges: std::runtime_error (failed status returned from 32dddc4e-5abf-4a2a-8a65-5d845a0863a3/127.227.191.13)))
```

**Comment by tchaikov** [comment]
[scylla-80.log](https://github.com/scylladb/scylladb/files/14017161/scylla-80.log)

**Comment by tchaikov** [comment]
see also https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5992/testReport/junit/(root)/test_mv_tablets/Tests___Unit_Tests___test_tablet_alternator_lsi_consistency/

**Comment by kbr-scylla** [comment]
Duplicate of https://github.com/scylladb/scylladb/issues/16821?

**Comment by tchaikov** [comment]
@kbr-scylla i am not quite sure. as the `runtime_error` in #16821 was `std::out_of_range (regular column id 0 >= 0)`, while this one has `std::runtime_error (put_row_diff: Repair follower=127.227.191.14 failed in put_row_diff handler, status=0)`.

**Comment by kbr-scylla** [comment]
Ah, but the out_of_range appears on one of the other servers participating in repair:
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5988/artifact/testlog/x86_64/debug/scylla-81.log

```
WARN  2024-01-22 23:41:12,516 [shard 0:main] storage_proxy - Failed to apply mutation from 127.227.191.12#0: std::out_of_range (regular column id 0 >= 0)
INFO  2024-01-22 23:41:12,520 [shard 0:comp] compaction - [Compact system.topology_requests f651ef50-b96e-11ee-b082-c46b61a0305d] Compacting [/scylladir/testlog/x86_64/debug/scylla-81/data/system/topology_requests-b3068525d0f239c28250584f9b1bf460/me-3gcz_1o8m_4jr282omrtgawo1d25-big-Data.db:level=0:origin=memtable,/scylladir/testlog/x86_64/debug/scylla-81/data/system/topology_requests-b3068525d0f239c28250584f9b1bf460/md-2-big-Data.db:level=0:origin=memtable]
INFO  2024-01-22 23:41:12,604 [shard 0:comp] compaction - [Compact system.topology_requests f651ef50-b96e-11ee-b082-c46b61a0305d] Compacted 2 sstables to [/scylladir/testlog/x86_64/debug/scylla-81/data/system/topology_requests-b3068525d0f239c28250584f9b1bf460/me-3gcz_1o8o_35li82omrtgawo1d25-big-Data.db:level=0]. 11kB to 6038 bytes (~53% of original) in 66ms = 171kB/s. ~256 total partitions merged to 3.
INFO  2024-01-22 23:41:12,694 [shard 0:main] migration_manager - Schema agreement check passed.
WARN  2024-01-22 23:41:16,605 [shard 0:main] storage_proxy - Failed to apply mutation from 127.227.191.12#0: std::out_of_range (regular column id 0 >= 0)
INFO  2024-01-22 23:41:16,761 [shard 0:main] migration_manager - Schema agreement check passed.
WARN  2024-01-22 23:41:20,303 [shard 0:strm] repair - repair_put_row_diff_with_rpc_stream_handler: from=127.227.191.13 repair_meta_id=868 error=std::out_of_range (regular column id 0 >= 0)
DEBUG 2024-01-22 23:41:21,003 [shard 0:strm] raft_topology - reload raft topology state
DEBUG 2024-01-22 23:41:21,010 [shard 0: gms] raft_topology - topology cmd rpc barrier_and_drain is called
DEBUG 2024-01-22 23:41:21,056 [shard 0:strm] raft_topology - topology_state_load: current CDC generation ID: (2024/01/22 21:41:10, f506cbca-b96e-11ee-9597-814b4a7f0b3b)
DEBUG 2024-01-22 23:41:21,059 [shard 0: gms] raft_topology - Got raft_topology_cmd::barrier_and_drain, version 7, current version 7
DEBUG 2024-01-22 23:41:21,060 [shard 0: gms] raft_topology - raft_topology_cmd::barrier_and_drain done
DEBUG 2024-01-22 23:41:21,060 [shard 1: gms] raft_topology - Got raft_topology_cmd::barrier_and_drain, version 7, current version 7
DEBUG 2024-01-22 23:41:21,061 [shard 1: gms] raft_topology - raft_topology_cmd::barrier_and_drain done
DEBUG 2024-01-22 23:41:21,106 [shard 0:strm] raft_topology - reload raft topology state
DEBUG 2024-01-22 23:41:21,142 [shard 0:strm] raft_topology - topology_state_load: current CDC generation ID: (2024/01/22 21:41:10, f506cbca-b96e-11ee-9597-814b4a7f0b3b)
DEBUG 2024-01-22 23:41:21,212 [shard 0:strm] raft_topology - reload raft topology state
DEBUG 2024-01-22 23:41:21,251 [shard 0:strm] raft_topology - topology_state_load: current CDC generation ID: (2024/01/22 21:41:10, f506cbca-b96e-11ee-9597-814b4a7f0b3b)
INFO  2024-01-22 23:41:21,287 [shard 0:main] raft_group_registry - marking Raft server 32dddc4e-5abf-4a2a-8a65-5d845a0863a3 as dead for raft groups
DEBUG 2024-01-22 23:41:21,390 [shard 0:strm] raft_topology - reload raft topology state
INFO  2024-01-22 23:41:21,419 [shard 0:strm] gossip - Removed endpoint 127.227.191.13
INFO  2024-01-22 23:41:21,419 [shard 0:strm] gossip - InetAddress 127.227.191.13 is now DOWN, status = UNKNOWN
INFO  2024-01-22 23:41:21,430 [shard 0:strm] gossip - Finished to force remove node 127.227.191.13
DEBUG 2024-01-22 23:41:21,466 [shard 0:strm] raft_topology - topology_state_load: current CDC generation ID: (2024/01/22 21:41:10, f506cbca-b96e-11ee-9597-814b4a7f0b3b)
WARN  2024-01-22 23:41:24,667 [shard 0:main] storage_proxy - Failed to apply mutation from 127.227.191.12#0: std::out_of_range (regular column id 0 >= 0)
```

**Comment by tchaikov** [comment]
thanks! i see. so these two errors/exceptions are correlated. i am closing this one.
