### ISSUE TITLE
Scylla attempts to set RPC_READY endpoint state on gossip after starting to listen on the maintenance post

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#16932]
Seen locally with test_change_rpc_address that timed out (I'm not sure if the timeout is related to this issue).
But I see it present also here: https://github.com/scylladb/scylladb/issues/16926#issuecomment-1905126031
```
INFO  2024-01-22 23:40:53,975 [shard 0:stmt] cql_server_controller - Setting up maintenance socket on /scylladir/testlog/x86_64/debug/scylla-80/cql.m
INFO  2024-01-22 23:40:53,977 [shard 0:stmt] cql_server_controller - Starting listening for CQL clients on /scylladir/testlog/x86_64/debug/scylla-80/cql.m (unencrypted, non-shard-aware)

WARN  2024-01-22 23:40:53,978 [shard 0:stmt] gossip - Fail to apply application_state: std::runtime_error (endpoint_state_map does not contain endpoint = 127.227.191.13, application_states = {{RPC_READY -> Value(1,1)}})
```

We shouldn't declare ourselves RPC_READY before we start listening on broadcast_rpc_address

**Comment by bhalevy** [comment]
would this work?

```diff
diff --git a/transport/controller.cc b/transport/controller.cc
index 010b0bf7f9..3e3689dadc 100644
--- a/transport/controller.cc
+++ b/transport/controller.cc
@@ -212,7 +212,9 @@ future<> controller::do_start_server() {
             });
         }).get();
 
-        set_cql_ready(true).get();
+        if (!_used_by_maintenance_socket) {
+            set_cql_ready(true).get();
+        }
 
         on_error.cancel();
         on_error_unsub.cancel();
```

**Comment by kbr-scylla** [comment]
Thanks for the issue.

The diff you proposed looks good to me.

**Comment by tchaikov** [comment]
the test failed *before* the fix got merged. i am posting the log just for the record.

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6581/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___topology_experimental_raft_test_topology_recovery_basic_dev_2/
```
=== TEST.PY STARTING TEST topology_experimental_raft.test_topology_recovery_basic.2 ===
export UBSAN_OPTIONS='halt_on_error=1:abort_on_error=1:suppressions=/jenkins/workspace/scylla-master/scylla-ci/scylla/ubsan-suppressions.supp'
export ASAN_OPTIONS='disable_coredump=0:abort_on_error=1:detect_stack_use_after_return=1'
pytest --manager-api=/tmp/manager-is520gje/api --mode=dev -s --log-level=DEBUG -o junit_family=xunit2 --junit-xml=/scylladir/testlog/x86_64/dev/xml/topology_experimental_raft.test_topology_recovery_basic.2.xunit.xml -rs test/topology_experimental_raft/test_topology_recovery_basic.py
=== TEST.PY TEST topology_experimental_raft.test_topology_recovery_basic.2 OUTPUT ===
Driver name Scylla Python Driver, version 3.26.5
============================= test session starts ==============================
platform linux -- Python 3.11.7, pytest-7.2.2, pluggy-1.0.0
rootdir: /jenkins/workspace/scylla-master/scylla-ci/scylla/test/topology_experimental_raft, configfile: pytest.ini
plugins: asyncio-0.20.3
asyncio: mode=Mode.AUTO
...
09:27:52.492 WARNING> [control connection] Error connecting to 127.198.7.18:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3626, in cassandra.cluster.ControlConnection._connect_host_in_lbp
  File "cassandra/cluster.py", line 3675, in cassandra.cluster.ControlConnection._try_connect
cassandra.DriverException: Reconnecting during shutdown
09:27:52.492 DEBUG> [control connection] error reconnecting
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3747, in cassandra.cluster.ControlConnection._reconnect
  File "cassandra/cluster.py", line 3648, in cassandra.cluster.ControlConnection._reconnect_internal
  File "cassandra/cluster.py", line 3635, in cassandra.cluster.ControlConnection._connect_host_in_lbp
cassandra.DriverException: [control connection] Reconnection in progress during shutdown
09:27:54.780 WARNING> [control connection] Error connecting to 127.198.7.18:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3626, in cassandra.cluster.ControlConnection._connect_host_in_lbp
  File "cassandra/cluster.py", line 3672, in cassandra.cluster.ControlConnection._try_connect
  File "cassandra/cluster.py", line 1700, in cassandra.cluster.Cluster.connection_factory
  File "cassandra/connection.py", line 885, in cassandra.connection.Connection.factory
cassandra.OperationTimedOut: errors=Timed out creating connection (200 seconds), last_host=None
09:27:54.780 DEBUG> [control connection] error reconnecting
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3747, in cassandra.cluster.ControlConnection._reconnect
  File "cassandra/cluster.py", line 3648, in cassandra.cluster.ControlConnection._reconnect_internal
  File "cassandra/cluster.py", line 3635, in cassandra.cluster.ControlConnection._connect_host_in_lbp
cassandra.DriverException: [control connection] Reconnection in progress during shutdown
09:27:54.781 DEBUG> Using selector: EpollSelector
```

[topology_experimental_raft.test_topology_recovery_basic.2.log](https://github.com/scylladb/scylladb/files/14274698/topology_experimental_raft.test_topology_recovery_basic.2.log)
[scylla-2081.log](https://github.com/scylladb/scylladb/files/14274699/scylla-2081.log)
[scylla-2080.log](https://github.com/scylladb/scylladb/files/14274700/scylla-2080.log)
[scylla-2079.log](https://github.com/scylladb/scylladb/files/14274701/scylla-2079.log)

**Comment by kbr-scylla** [comment]
@tchaikov this is https://github.com/scylladb/scylladb/issues/17305
