### ISSUE TITLE
test_coordinator_queue_management: failed to add server, coordinator stuck on `removing node ... from group 0 configuration`

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#17186]
ARM debug mode failure
uploaded logs:
[scylla-162.log](https://github.com/scylladb/scylladb/files/14179363/scylla-162.log)
[scylla-163.log](https://github.com/scylladb/scylladb/files/14179364/scylla-163.log)
[scylla-164.log](https://github.com/scylladb/scylladb/files/14179365/scylla-164.log)
[scylla-172.log](https://github.com/scylladb/scylladb/files/14179366/scylla-172.log)
[scylla-173.log](https://github.com/scylladb/scylladb/files/14179367/scylla-173.log)
[scylla-187.log](https://github.com/scylladb/scylladb/files/14179368/scylla-187.log)
[test.py.debug-release-dev.log](https://github.com/scylladb/scylladb/files/14179369/test.py.debug-release-dev.log)
[topology.test_coordinator_queue_management.1.log](https://github.com/scylladb/scylladb/files/14179370/topology.test_coordinator_queue_management.1.log)

The test started concurrent tasks and got stuck waiting for them:
```python3
        tasks = [asyncio.create_task(manager.server_add()),
                 asyncio.create_task(manager.remove_node(servers[0].server_id, servers[3].server_id)),
                 asyncio.create_task(manager.remove_node(servers[1].server_id, servers[4].server_id, [s3_id]))]

        search = [asyncio.create_task(l.wait_for("received request to join from host_id", m) for l, m in zip(logs[:3], marks[:3]))]
        done, pending = await asyncio.wait(search, return_when = asyncio.FIRST_COMPLETED)
        for t in pending: t.cancel()
    
        [await l.wait_for("raft_topology - removenode: wait for completion", m) for l, m in zip(logs[:2], marks[:2])]
    
        [await manager.api.message_injection(s.ip_addr, inj) for s in servers[:3]]
    
>       await asyncio.gather(*tasks)

```

The task that timed out eventually was `server_add()`
```
        except Exception as exc:
>           raise Exception("Failed to add server") from exc
E           Exception: Failed to add server
```

`scylla-187` was the server being added, which we can see from the `test.py.debug-release-dev.log` file
```
11:17:44.322 ERROR> [debug/topology.test_coordinator_queue_management.1] Exception when executing _cluster_server_add: failed to start the node, timeout reached, server_id 187, IP 127.78.0.3, workdir scylla-187, host_id b27a9b06-9da4-4faa-b383-9c58c59418df, cql [not connected]
Check the log files:
/scylladir/testlog/aarch64/test.py.debug-release-dev.log
/scylladir/testlog/aarch64/debug/scylla-187.log
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/next/scylla/test/pylib/scylla_cluster.py", line 1143, in catching_handler
    ret = await handler(request)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/jenkins/workspace/scylla-master/next/scylla/test/pylib/scylla_cluster.py", line 1291, in _cluster_server_add
    s_info = await self.cluster.add_server(replace_cfg, data.get('cmdline'), data.get('config'),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jenkins/workspace/scylla-master/next/scylla/test/pylib/scylla_cluster.py", line 816, in add_server
    await server.install_and_start(self.api, expected_error)
  File "/jenkins/workspace/scylla-master/next/scylla/test/pylib/scylla_cluster.py", line 285, in install_and_start
    await self.start(api, expected_error)
  File "/jenkins/workspace/scylla-master/next/scylla/test/pylib/scylla_cluster.py", line 511, in start
    report_error('failed to start the node, timeout reached')
  File "/jenkins/workspace/scylla-master/next/scylla/test/pylib/scylla_cluster.py", line 485, in report_error
    raise RuntimeError(message + "\nCheck the log files:\n"
RuntimeError: failed to start the node, timeout reached, server_id 187, IP 127.78.0.3, workdir scylla-187, host_id b27a9b06-9da4-4faa-b383-9c58c59418df, cql [not connected]
Check the log files:
/scylladir/testlog/aarch64/test.py.debug-release-dev.log
/scylladir/testlog/aarch64/debug/scylla-187.log
```

The other servers were
```
11:17:43.468 INFO> Cluster after test test_coordinator_queue_management: ScyllaCluster(name: 92ae70f6-c4de-11ee-a5fc-043f72d77e12, running: ScyllaServer(162, 127.78.0.37, cc9ab29b-2767-48e6-a335-8e99e1aac14f), ScyllaServer(164, 127.78.0.9, 8e8f5b1e-6d94-4acb-8ad0-9b42dbdc8b80), ScyllaServer(163, 127.78.0.7, 0164314f-670d-417f-804f-687ea0327072), stopped: ScyllaServer(172, 127.78.0.41, bcced5e6-4017-4111-9d58-ec24e208aaf8), ScyllaServer(173, 127.78.0.10, ca1b9907-b507-45ea-b2cd-f2d44d2bcf60))
```

browsing the logs, `scylla-162` was the coordinator. It got stuck at tablet load balancing:
```
INFO  2024-02-06 11:01:19,133 [shard 0: gms] gossip - InetAddress 127.78.0.3 is now UP, status = UNKNOWN
INFO  2024-02-06 11:02:08,899 [shard 0:strm] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 endpoints
WARN  2024-02-06 11:02:08,912 [shard 0:strm] raft_topology - Found error while refreshing load stats for tablets: seastar::rpc::closed_error (connection is closed), retrying...
INFO  2024-02-06 11:03:08,913 [shard 0:strm] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 endpoints
WARN  2024-02-06 11:03:08,925 [shard 0:strm] raft_topology - Found error while refreshing load stats for tablets: seastar::rpc::closed_error (connection is closed), retrying...
INFO  2024-02-06 11:04:08,926 [shard 0:strm] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 endpoints
WARN  2024-02-06 11:04:08,954 [shard 0:strm] raft_topology - Found error while refreshing load stats for tablets: seastar::rpc::closed_error (connection is closed), retrying...
INFO  2024-02-06 11:05:08,955 [shard 0:strm] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 endpoints
WARN  2024-02-06 11:05:08,968 [shard 0:strm] raft_topology - Found error while refreshing load stats for tablets: seastar::rpc::closed_error (connection is closed), retrying...
INFO  2024-02-06 11:06:08,969 [shard 0:strm] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 endpoints
WARN  2024-02-06 11:06:08,986 [shard 0:strm] raft_topology - Found error while refreshing load stats for tablets: seastar::rpc::closed_error (connection is closed), retrying...
INFO  2024-02-06 11:07:08,990 [shard 0:strm] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 endpoints
WARN  2024-02-06 11:07:09,004 [shard 0:strm] raft_topology - Found error while refreshing load stats for tablets: seastar::rpc::closed_error (connection is closed), retrying...
INFO  2024-02-06 11:08:09,005 [shard 0:strm] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 endpoints
WARN  2024-02-06 11:08:09,021 [shard 0:strm] raft_topology - Found error while refreshing load stats for tablets: seastar::rpc::closed_error (connection is closed), retrying...
INFO  2024-02-06 11:09:09,022 [shard 0:strm] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 endpoints
WARN  2024-02-06 11:09:09,040 [shard 0:strm] raft_topology - Found error while refreshing load stats for tablets: seastar::rpc::closed_error (connection is closed), retrying...
INFO  2024-02-06 11:10:09,046 [shard 0:strm] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 endpoints
WARN  2024-02-06 11:10:09,063 [shard 0:strm] raft_topology - Found error while refreshing load stats for tablets: seastar::rpc::closed_error (connection is closed), retrying...
INFO  2024-02-06 11:11:09,064 [shard 0:strm] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 endpoints
WARN  2024-02-06 11:11:09,122 [shard 0:strm] raft_topology - Found error while refreshing load stats for tablets: seastar::rpc::closed_error (connection is closed), retrying...
INFO  2024-02-06 11:12:09,125 [shard 0:strm] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 endpoints
WARN  2024-02-06 11:12:09,145 [shard 0:strm] raft_topology - Found error while refreshing load stats for tablets: seastar::rpc::closed_error (connection is closed), retrying...
INFO  2024-02-06 11:13:09,146 [shard 0:strm] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 endpoints
WARN  2024-02-06 11:13:09,175 [shard 0:strm] raft_topology - Found error while refreshing load stats for tablets: seastar::rpc::closed_error (connection is closed), retrying...
INFO  2024-02-06 11:14:09,176 [shard 0:strm] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 endpoints
WARN  2024-02-06 11:14:09,190 [shard 0:strm] raft_topology - Found error while refreshing load stats for tablets: seastar::rpc::closed_error (connection is closed), retrying...
INFO  2024-02-06 11:15:09,197 [shard 0:strm] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 endpoints
WARN  2024-02-06 11:15:09,252 [shard 0:strm] raft_topology - Found error while refreshing load stats for tablets: seastar::rpc::closed_error (connection is closed), retrying...
INFO  2024-02-06 11:16:09,253 [shard 0:strm] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 endpoints
WARN  2024-02-06 11:16:09,329 [shard 0:strm] raft_topology - Found error while refreshing load stats for tablets: seastar::rpc::closed_error (connection is closed), retrying...
INFO  2024-02-06 11:17:09,336 [shard 0:strm] raft_topology - raft topology: Refreshing table load stats for DC datacenter1 that has 5 endpoints
WARN  2024-02-06 11:17:09,383 [shard 0:strm] raft_topology - Found error while refreshing load stats for tablets: seastar::rpc::closed_error (connection is closed), retrying...
```

cc @tgrabiec @gleb-cloudius

**Comment by kbr-scylla** [comment]
`seastar::rpc::closed_error (connection is closed)`

The error should probably say which server could not be reached, would be easier to debug.
i.e. https://github.com/scylladb/scylladb/issues/16923

**Comment by kbr-scylla** [comment]
Could it be that we're trying to reach one of the nodes we call `removenode` on, and this would get unstuck by https://github.com/scylladb/scylladb/issues/16108#issuecomment-1916868714 (`change the way ignored nodes are handled by the topology coordinator` on mailing list?)

**Comment by raphaelsc** [comment]
@kbr-scylla I think this might be a symptom of something else. The "load table stats" happens orthogonally to foreground coordinator activity. If it fails, it's ok. It means that load balancer won't take any decisions as stats weren't pulled. And if change of leadership is needed, the retry loop of "load table stats" checks for abort request and async gate of coordinator, meaning the fiber finishes. It's a background fiber like cdc_generation_publisher_fiber.


> Could it be that we're trying to reach one of the nodes we call `removenode` on, and this would get unstuck by [#16108 (comment)](https://github.com/scylladb/scylladb/issues/16108#issuecomment-1916868714) (`change the way ignored nodes are handled by the topology coordinator` on mailing list?)

It's possible as the "load table stats" issues a RPC against every available node in topology, even dead nodes. So that node gets listed in topology despite it was removed, right? Which is why the fiber keeps finding that node in topology on every attempt.

**Comment by kbr-scylla** [comment]
Hm, right, so the "refreshing load stats" is a red herring.

Looking at the logs again, the actual place where topology coordinator gets stuck seems to be
```
INFO  2024-02-06 11:01:18,398 [shard 0:strm] raft_topology - removing node ca1b9907-b507-45ea-b2cd-f2d44d2bcf60 from group 0 configuration...
```

so one of the `removenode`s got stuck, and that's the reason why the `add_server` got stuck, it's waiting in the queue.

**Comment by gleb-cloudius** [comment]
If it stuck in `change_config` it would be hard to guess where without raft trace log. Node 164 also added an entry to the log around the same time ad 162 tried to change config. May be it somehow related, though I do not see how.
