### ISSUE TITLE
Sporadic failure of test_cluster_features.test_downgrade_after_successful_upgrade_fails

### ISSUE THREAD

**Issue by pwrobelse** [scylladb/scylladb#17394]
The mentioned test failed during CI run https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6730/

The root cause seems to be related with setting up the nodes.
```
failed on setup with "TimeoutError"
```

The log contains the following information:
```
18:45:56.592 INFO> [debug/topology.test_cluster_features.1] Leasing Scylla cluster ScyllaCluster(name: 86dcb06e-cce8-11ee-8288-128a19b32f8b, running: ScyllaServer(121, 127.58.163.19, 889d242a-98de-480f-b298-14d646bede48), ScyllaServer(123, 127.58.163.4, 27a793c3-7dee-41ca-8263-f4bf7f838395), stopped: ) for test debug/topology.test_cluster_features.1::test_downgrade_after_successful_upgrade_fails
18:45:56.594 ERROR> [debug/topology.test_cluster_features.1] Exception when executing _before_test_req: Exception when starting cluster ScyllaCluster(name: 86dcb06e-cce8-11ee-8288-128a19b32f8b, running: ScyllaServer(121, 127.58.163.19, 889d242a-98de-480f-b298-14d646bede48), ScyllaServer(123, 127.58.163.4, 27a793c3-7dee-41ca-8263-f4bf7f838395), stopped: ):
failed to start the node, timeout reached, server_id 122, IP 127.58.163.7, workdir scylla-122, host_id 14c23642-75d0-48f0-be39-9ad735139545, cql [not connected]
Check the log files:
/scylladir/testlog/x86_64/test.py.debug-release-dev.log
/scylladir/testlog/x86_64/debug/scylla-122.log
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/pylib/scylla_cluster.py", line 1143, in catching_handler
    ret = await handler(request)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/pylib/scylla_cluster.py", line 1222, in _before_test_req
    cluster_str = await self._before_test(request.match_info['test_case_name'])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/pylib/scylla_cluster.py", line 1112, in _before_test
    self.cluster.before_test(self.current_test_case_full_name)
  File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/pylib/scylla_cluster.py", line 901, in before_test
    raise Exception(f'Exception when starting cluster {self}:\n{self.start_exception}')
Exception: Exception when starting cluster ScyllaCluster(name: 86dcb06e-cce8-11ee-8288-128a19b32f8b, running: ScyllaServer(121, 127.58.163.19, 889d242a-98de-480f-b298-14d646bede48), ScyllaServer(123, 127.58.163.4, 27a793c3-7dee-41ca-8263-f4bf7f838395), stopped: ):
failed to start the node, timeout reached, server_id 122, IP 127.58.163.7, workdir scylla-122, host_id 14c23642-75d0-48f0-be39-9ad735139545, cql [not connected]
Check the log files:
/scylladir/testlog/x86_64/test.py.debug-release-dev.log
/scylladir/testlog/x86_64/debug/scylla-122.log
```

The log from the instance 122 has the following information:
```
ERROR 2024-02-16 18:29:34,291 [shard 1:main] rpc - client 127.58.163.4:7000: client connection dropped: recv: Connection reset by peer

[...]

WARN  2024-02-16 18:29:35,593 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.58.163.4, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-16 18:29:37,595 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.58.163.4, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-16 18:29:39,597 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.58.163.4, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-16 18:29:41,602 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.58.163.4, status = failed: seastar::rpc::closed_error (connection is closed)
WARN  2024-02-16 18:29:43,604 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 127.58.163.4, status = failed: seastar::rpc::closed_error (connection is closed)
```

Links to the logs:
- https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6730/testReport/
- https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6730/artifact/testlog/x86_64/test.py.debug-release-dev.log
- https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6730/artifact/testlog/x86_64/debug/scylla-122.log

**Comment by mykaul** [comment]
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/6730/artifact/testlog/x86_64/debug/scylla-123.log has this:
```
INFO  2024-02-16 18:29:32,982 [shard 0:main] init - Scylla version 5.5.0~dev-0.20240216.85aa54dc266d initialization completed.
ERROR 2024-02-16 18:29:33,897 [shard 1:main] database - regular column id 0 >= 0, at: 0xd32598a /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x5685f9c /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x5685cf7 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x5688075 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x5688acf /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x44bb40e /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x44bafc6 0xed86359 0xec92343 0xe8d881a 0xe7c3328 0xe5d7444 0xe36b732 0xe406dfd 0xd577686 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4715728 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x471dce8 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4721d80 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4821856 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x481fa00 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x481f8f0 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x481f05c /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x44c6518 /lib64/libc.so.6+0x8c946 /lib64/libc.so.6+0x11296f
   --------
   seastar::internal::coroutine_traits_base<void>::promise_type
```

Which is a dup of https://github.com/scylladb/scylladb/issues/16821
