### ISSUE TITLE
[Azure][5.2] sstabledump fails to upgrade sstables with `Unable to find snitch class 'org.apache.cassandra.locator.AzureSnitch'` error

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylladb#17659]
## Packages

Base Scylla version: `5.2.15-20240211.1fa8327504ca` with build-id `5016cd97a9e262112dbb550f99f6bc5bc0aea077`
Target Scylla version (or git commit hash): `5.2.16-20240304.f4a78045960d` with build-id `194355fdfe2fffef917bfb27cabde48de5e80a1d`

Kernel Version: `5.15.0-1054-azure`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Recently we started running `upgrade` CI jobs on Azure it is first run of it using `scylla-5.2` branch.

So, after successful cluster upgrade we have step where we upgrade existing sstables and this step failed:
```
2024-03-05 01:12:45,369 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-03-05 01:12:45.367: (InfoEvent Severity.NORMAL) period_type=not-set event_id=942a015f-1a47-413c-98f1-70a9a7611082: message=Step7 - Upgrade sstables to latest supported version
...
2024-03-05 01:12:58,342 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "for i in `sudo find /var/lib/scylla/data/keyspace_complex/ -type f |grep -v manifest.json |grep -v snapshots |head -n 1`; do echo $i; sudo sstabledump $i 1>/tmp/sstabledump.output || exit 1; done"; Exit status: 1
2024-03-05 01:12:58,342 f:base.py         l:148  c:RemoteLibSSH2CmdRunner p:DEBUG > STDOUT: /var/lib/scylla/data/keyspace_complex/user_with_ck-fb4dc1f0da7511eea65079b32e2145f8/me-61-big-TOC.txt
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > STDERR: WARN  01:12:49,259 Only 24.597GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > Exception in thread "main" java.lang.ExceptionInInitializerError
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > Caused by: org.apache.cassandra.exceptions.ConfigurationException: Unable to find snitch class 'org.apache.cassandra.locator.AzureSnitch'
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     at org.apache.cassandra.utils.FBUtilities.classForName(FBUtilities.java:560)
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     at org.apache.cassandra.utils.FBUtilities.construct(FBUtilities.java:593)
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     at org.apache.cassandra.config.DatabaseDescriptor.createEndpointSnitch(DatabaseDescriptor.java:1088)
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     at org.apache.cassandra.config.DatabaseDescriptor.applySnitch(DatabaseDescriptor.java:1016)
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     at org.apache.cassandra.config.DatabaseDescriptor.toolInitialization(DatabaseDescriptor.java:203)
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     at org.apache.cassandra.config.DatabaseDescriptor.toolInitialization(DatabaseDescriptor.java:168)
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     at org.apache.cassandra.tools.SSTableExport.<clinit>(SSTableExport.java:69)
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > Caused by: java.lang.ClassNotFoundException: org.apache.cassandra.locator.AzureSnitch
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     at java.lang.Class.forName0(Native Method)
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     at java.lang.Class.forName(Class.java:264)
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     at org.apache.cassandra.utils.FBUtilities.classForName(FBUtilities.java:556)
2024-03-05 01:12:58,342 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG >     ... 6 more
2024-03-05 01:12:58,343 f:tester.py       l:228  c:silence              p:DEBUG > Finished 'Sending test end event'. No errors were silenced.
...
2024-03-05 01:12:58,343 f:tester.py       l:2829 c:UpgradeTest          p:INFO  > TearDown is starting...
```

## Impact

SStables cannot be upgraded after a DB cluster upgrade on Azure.

## How frequently does it reproduce?

1/1

## Installation details

Cluster size: 4 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-b1b064c7-eastus-4 (172.208.54.170 | 10.0.0.8) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-b1b064c7-eastus-3 (172.208.54.157 | 10.0.0.7) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-b1b064c7-eastus-2 (172.208.54.78 | 10.0.0.6) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-b1b064c7-eastus-1 (172.208.54.20 | 10.0.0.5) (shards: 7)

OS / Image: `/CommunityGalleries/scylladb-7e8d8a04-23db-487d-87ec-0e175c0615bb/Images/scylla-5.2/Versions/5.2.15` (azure: undefined_region)

Test: `rolling-upgrade-azure-image-test`
Test id: `b1b064c7-0a3c-4599-8e44-4931af23d85c`
Test name: `scylla-5.2/rolling-upgrade/rolling-upgrade-azure-image-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/b7636f85243c29f56d4573ba0aa69faf0fff6486/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor b1b064c7-0a3c-4599-8e44-4931af23d85c`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b1b064c7-0a3c-4599-8e44-4931af23d85c)
- Show all stored logs command: `$ hydra investigate show-logs b1b064c7-0a3c-4599-8e44-4931af23d85c`

## Logs:
- **db-cluster-b1b064c7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b1b064c7-0a3c-4599-8e44-4931af23d85c/20240305_012829/db-cluster-b1b064c7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b1b064c7-0a3c-4599-8e44-4931af23d85c/20240305_012829/db-cluster-b1b064c7.tar.gz)
- **sct-runner-events-b1b064c7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b1b064c7-0a3c-4599-8e44-4931af23d85c/20240305_012829/sct-runner-events-b1b064c7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b1b064c7-0a3c-4599-8e44-4931af23d85c/20240305_012829/sct-runner-events-b1b064c7.tar.gz)
- **sct-b1b064c7.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b1b064c7-0a3c-4599-8e44-4931af23d85c/20240305_012829/sct-b1b064c7.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b1b064c7-0a3c-4599-8e44-4931af23d85c/20240305_012829/sct-b1b064c7.log.tar.gz)
- **monitor-set-b1b064c7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b1b064c7-0a3c-4599-8e44-4931af23d85c/20240305_012829/monitor-set-b1b064c7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b1b064c7-0a3c-4599-8e44-4931af23d85c/20240305_012829/monitor-set-b1b064c7.tar.gz)
- **loader-set-b1b064c7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b1b064c7-0a3c-4599-8e44-4931af23d85c/20240305_012829/loader-set-b1b064c7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b1b064c7-0a3c-4599-8e44-4931af23d85c/20240305_012829/loader-set-b1b064c7.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.2/job/rolling-upgrade/job/rolling-upgrade-azure-image-test/3/)
[Argus](https://argus.scylladb.com/test/bb31edf1-38a5-42b3-9928-af2adf474c2e/runs?additionalRuns[]=b1b064c7-0a3c-4599-8e44-4931af23d85c)
</details>

**Comment by mykaul** [comment]
Dup of https://github.com/scylladb/scylla-tools-java/issues/338

**Comment by vponomaryov** [comment]
> Dup of [scylladb/scylla-tools-java#338](https://github.com/scylladb/scylla-tools-java/issues/338)

The referenced bug report was also closed not having fix.
So, Azure upgrade job will always fail this fail.
Does it mean we should disable that new job for 5.2 branch?

**Comment by mykaul** [comment]
> > Dup of [scylladb/scylla-tools-java#338](https://github.com/scylladb/scylla-tools-java/issues/338)
> 
> The referenced bug report was also closed not having fix. So, Azure upgrade job will always fail this way. Does it mean we should disable that new job for 5.2 branch?

I think we need to remove that check from 5.2 upgrade jobs.
