### ISSUE TITLE
2 alive nodes started having query (rf=3,cl=quorum) timeouts right after third node got terminated

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylladb#17687]
## Packages

Scylla version: `5.5.0~dev-20240301.94cd23588832` with build-id `d010caa35e3ede60b884b4c94bcc945bfd3ccd4b`

Operator Image: `scylladb/scylla-operator:latest`
Operator Helm Version: `v1.13.0-alpha.0-14-g0308d14-latest`
Operator Helm Repository: `https://storage.googleapis.com/scylla-operator-charts/latest`
Kernel Version: `5.10.209-198.858.amzn2.x86_64`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

Setup details:
Platform: K8S/EKS.
We had 4 K8S nodes dedicated for Scylla pods.
We ran 2 DB clusters with 3 members each (multitenant setup).
All Scylla pods of each DB cluster were located on separate K8S nodes.
2 K8S nodes had 2 Scylla pods from different DB clusters and 2 K8S nodes had just 1 Scylla pod from some of DB clusters.
Each of the DB clusters/tenants has it's own 2 loader pods which run `write` and `read` loads.

Then, at some point, after running bunch of nemesis we reach the `disrupt_terminate_kubernetes_host_then_decommission_and_add_scylla_node` nemesis.
It's steps:
- `terminate EC2 instance` (one of K8S VMs dedicated for Scylla pods) step as the first one.
- Reduce number of pods in the configuration of the `ScyllaCluster` K8S object from 3 to 2 which removes the disrupted member-pod.
- Add new Scylla node

The first `terminate EC2 instance` step brings down 1 pod from each of the DB clusters, because was picked up a K8S node with 2 pods

```
2024-03-03 06:44:35,711 f:nemesis.py      l:1479 c:sdcm.nemesis | db2   p:INFO  > sdcm.nemesis.K8sSetMonkey: \
    Running 'terminate_k8s_host' method on the 'ip-10-0-2-180.eu-north-1.compute.internal' K8S node \
    that hosts 'Node sct-cluster-2-eu-north-1-rack-1-2 [10.0.2.180 | 10.0.0.128] (seed: False)' target pod \
    and '['scylla/sct-cluster-eu-north-1-rack-1-0']' neighbour pods.
2024-03-03 06:44:35,753 f:eks.py          l:745  c:sdcm.cluster_k8s     p:INFO  > eu-north-1: terminate_k8s_host: EC2 instance of kubernetes node will be terminated, the following is affected :
2024-03-03 06:44:35,753 f:eks.py          l:745  c:sdcm.cluster_k8s     p:INFO  > 
2024-03-03 06:44:35,753 f:eks.py          l:745  c:sdcm.cluster_k8s     p:INFO  > EC2 instance  X  <-
2024-03-03 06:44:35,753 f:eks.py          l:745  c:sdcm.cluster_k8s     p:INFO  > K8s node      X
2024-03-03 06:44:35,753 f:eks.py          l:745  c:sdcm.cluster_k8s     p:INFO  > Scylla Pod    X
2024-03-03 06:44:35,753 f:eks.py          l:745  c:sdcm.cluster_k8s     p:INFO  > Scylla node   X
```

Each of the loaders uses `CL=QUORUM`. So, we expected 2 alive nodes satisfy small load from loaders.
The first DB cluster behaved as expected.
But second DB cluster started having lots of the following loader errors:

```
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
```

It is mixed with the expected failures where there is no connectivity to the dead pod:
```
com.datastax.driver.core.exceptions.OperationTimedOutException: [/172.20.53.56:9042] Timed out waiting for server response
```

In 30 seconds we see following:

```
com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
java.io.IOException: Operation x10 on key(s) [313932314d384b343331]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)

	at org.apache.cassandra.stress.Operation.error(Operation.java:141)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:119)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:101)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:109)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:264)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:473)
```

2 alive DB nodes don't have anything related to the query timeouts, only expected dead peer info:

node-0:
```
INFO  2024-03-03 06:41:58,295 [shard 3:comp] compaction - [Compact keyspace1.standard1 20055150-d929-11ee-a42f-0d81fe5ea0b8] Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-9c38dd50d91f11eea0070d7dfe5ea0b8/me-3ge4_0ilu_5gz1s2hvtpgb3semd4-big-Data.db:level=0]. 2GB to 2GB (~100% of original) in 3377ms = 642MB/s. ~413696 total partitions merged to 413613.
INFO  2024-03-03 06:44:44,579 [shard 0:main] raft_group_registry - marking Raft server cd2b98ca-996c-4852-a664-8c336248f6c2 as dead for raft groups
WARN  2024-03-03 06:45:06,042 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 172.20.53.56, status = failed: seastar::rpc::timeout_error (rpc call timed out)
INFO  2024-03-03 06:45:06,042 [shard 0:strm] gossip - failure_detector_loop: Mark node 172.20.53.56 as DOWN
INFO  2024-03-03 06:45:06,042 [shard 0:strm] gossip - InetAddress 172.20.53.56 is now DOWN, status = NORMAL
INFO  2024-03-03 06:48:56,409 [shard 0: gms] gossip - Node 172.20.53.56 has restarted, now UP, status = UNKNOWN
WARN  2024-03-03 06:48:56,410 [shard 0: gms] gossip - Fail to send EchoMessage to 172.20.53.56: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
```

node-1:
```
INFO  2024-03-03 06:44:06,411 [shard 3:comp] compaction - [Compact keyspace1.standard1 6c523f00-d929-11ee-8b4e-d99d8d7169b1] Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-9c38dd50d91f11eea0070d7dfe5ea0b8/me-3ge4_0ipe_5j47k249k4vr95icoh-big-Data.db:level=0]. 1GB to 1GB (~100% of original) in 3481ms = 538MB/s. ~357120 total partitions merged to 356965.
INFO  2024-03-03 06:44:44,544 [shard 0:main] raft_group_registry - marking Raft server cd2b98ca-996c-4852-a664-8c336248f6c2 as dead for raft groups
WARN  2024-03-03 06:45:06,042 [shard 0:strm] gossip - failure_detector_loop: Send echo to node 172.20.53.56, status = failed: seastar::rpc::timeout_error (rpc call timed out)
INFO  2024-03-03 06:45:06,042 [shard 0:strm] gossip - failure_detector_loop: Mark node 172.20.53.56 as DOWN
INFO  2024-03-03 06:45:06,042 [shard 0:strm] gossip - InetAddress 172.20.53.56 is now DOWN, status = NORMAL
INFO  2024-03-03 06:48:56,710 [shard 0: gms] gossip - Node 172.20.53.56 has restarted, now UP, status = UNKNOWN
WARN  2024-03-03 06:48:56,711 [shard 0: gms] gossip - Fail to send EchoMessage to 172.20.53.56: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
```

Monitoring info of the second (problematic) DB cluster:
![Screenshot from 2024-03-07 18-51-48](https://github.com/scylladb/scylladb/assets/3796058/0c933ba5-5671-4ee9-87ec-00a649999683)

Monitoring info of the first OK DB cluster for comparison at the same time range:
![Screenshot from 2024-03-07 18-53-13](https://github.com/scylladb/scylladb/assets/3796058/ec18543f-c883-4789-a929-d0e8c4adc53c)

On the monitoring screenshots we see that both alive nodes from the second cluster did have query timeouts
whereas the alive nodes of the first DB cluster don't have timeouts.

As a result test run failed with critical error based on the loader failures.

Note that this scenario worked ok in couple of other test runs using `2024.1.1` Scylla version.

## Impact

Query timeouts.

## How frequently does it reproduce?

Observed first time

## Installation details

Cluster size: 3 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: `eu-north-1`)

Test: `longevity-scylla-operator-3h-multitenant-eks-test`
Test id: `e069246d-a2e7-4c22-a00a-70028eb2e15a`
Test name: `scylla-operator/operator-master/eks/longevity-scylla-operator-3h-multitenant-eks-test`
Test config file(s):

- [longevity-scylla-operator-3h-multitenant.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/19a0f45cd759e2c4d0ae07c75c04da701a14073f/test-cases/scylla-operator/longevity-scylla-operator-3h-multitenant.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor e069246d-a2e7-4c22-a00a-70028eb2e15a`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e069246d-a2e7-4c22-a00a-70028eb2e15a)
- Show all stored logs command: `$ hydra investigate show-logs e069246d-a2e7-4c22-a00a-70028eb2e15a`

## Logs:
- **kubernetes-e069246d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e069246d-a2e7-4c22-a00a-70028eb2e15a/20240303_070242/kubernetes-e069246d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e069246d-a2e7-4c22-a00a-70028eb2e15a/20240303_070242/kubernetes-e069246d.tar.gz)
- **kubernetes-must-gather-e069246d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e069246d-a2e7-4c22-a00a-70028eb2e15a/20240303_070242/kubernetes-must-gather-e069246d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e069246d-a2e7-4c22-a00a-70028eb2e15a/20240303_070242/kubernetes-must-gather-e069246d.tar.gz)
- **db-cluster-e069246d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e069246d-a2e7-4c22-a00a-70028eb2e15a/20240303_070242/db-cluster-e069246d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e069246d-a2e7-4c22-a00a-70028eb2e15a/20240303_070242/db-cluster-e069246d.tar.gz)
- **sct-runner-events-e069246d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e069246d-a2e7-4c22-a00a-70028eb2e15a/20240303_070242/sct-runner-events-e069246d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e069246d-a2e7-4c22-a00a-70028eb2e15a/20240303_070242/sct-runner-events-e069246d.tar.gz)
- **sct-e069246d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e069246d-a2e7-4c22-a00a-70028eb2e15a/20240303_070242/sct-e069246d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e069246d-a2e7-4c22-a00a-70028eb2e15a/20240303_070242/sct-e069246d.log.tar.gz)
- **loader-set-e069246d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e069246d-a2e7-4c22-a00a-70028eb2e15a/20240303_070242/loader-set-e069246d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e069246d-a2e7-4c22-a00a-70028eb2e15a/20240303_070242/loader-set-e069246d.tar.gz)
- **monitor-set-e069246d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e069246d-a2e7-4c22-a00a-70028eb2e15a/20240303_070242/monitor-set-e069246d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e069246d-a2e7-4c22-a00a-70028eb2e15a/20240303_070242/monitor-set-e069246d.tar.gz)
- **parallel-timelines-report-e069246d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e069246d-a2e7-4c22-a00a-70028eb2e15a/20240303_070242/parallel-timelines-report-e069246d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e069246d-a2e7-4c22-a00a-70028eb2e15a/20240303_070242/parallel-timelines-report-e069246d.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/eks/job/longevity-scylla-operator-3h-multitenant-eks-test/7/)
[Argus](https://argus.scylladb.com/test/888dac29-9c69-44d3-94fe-54e1a3328127/runs?additionalRuns[]=e069246d-a2e7-4c22-a00a-70028eb2e15a)
</details>

**Comment by vponomaryov** [comment]
@mykaul this is what we walked through on the latest call.
