### ISSUE TITLE
[Alternator] test_load_older_snapshot_and_refresh dtest fails with tablets: AssertionError: The following items are missing:

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#17733]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/dtest-byo/164/testReport/alternator_tests/TesterAlternator/FullDtest___full_split001___test_load_older_snapshot_and_refresh/
with scylla 5.5.0~dev-0.20240310.af9091068720
```
self = <alternator_tests.TesterAlternator object at 0x7fd2416ba790>

    @pytest.mark.next_gating
    def test_load_older_snapshot_and_refresh(self):
        """
        The test loading older snapshot files and checking the refresh command works
        Test will:
           - Create a cluster of 3 nodes.
           - Load older snapshot files
           - Execute nodetool `refresh` command
           - Verify after `refresh` commands are equal to snapshot data
        """
        table_name, node_idx = TABLE_NAME, 0
        snapshot_folder = os.path.join(ALTERNATOR_SNAPSHOT_FOLDER, "scylla4.0.rc1")
    
        self.prepare_dynamodb_cluster(num_of_nodes=3)
        node1 = self.cluster.nodelist()[node_idx]
        self.create_table(table_name=table_name, node=node1)
        table_data = self.create_items()
        self.load_snapshot_and_refresh(table_name=table_name, node=node1, snapshot_folder=snapshot_folder)
        diff = self.compare_table_data(table_name=table_name, expected_table_data=table_data, node=node1)
>       assert not diff, f"The following items are missing:\n{pformat(diff)}"
E       AssertionError: The following items are missing:
E         {'iterable_item_removed': {'root[10]': {'hash_key': 'test10',
E                                                 'x': {'hello': 'world10'}},
E                                    'root[11]': {'hash_key': 'test11',
E                                                 'x': {'hello': 'world11'}},
E                                    'root[12]': {'hash_key': 'test12',
E                                                 'x': {'hello': 'world12'}},
E                                    'root[13]': {'hash_key': 'test13',
E                                                 'x': {'hello': 'world13'}},
E                                    'root[14]': {'hash_key': 'test14',
E                                                 'x': {'hello': 'world14'}},
E                                    'root[15]': {'hash_key': 'test15',
E                                                 'x': {'hello': 'world15'}},
E                                    'root[16]': {'hash_key': 'test16',
E                                                 'x': {'hello': 'world16'}},
E                                    'root[18]': {'hash_key': 'test18',
E                                                 'x': {'hello': 'world18'}},
E                                    'root[19]': {'hash_key': 'test19',
E                                                 'x': {'hello': 'world19'}},
E                                    'root[1]': {'hash_key': 'test1',
E                                                'x': {'hello': 'world1'}},
E                                    'root[21]': {'hash_key': 'test21',
E                                                 'x': {'hello': 'world21'}},
E                                    'root[23]': {'hash_key': 'test23',
E                                                 'x': {'hello': 'world23'}},
E                                    'root[25]': {'hash_key': 'test25',
E                                                 'x': {'hello': 'world25'}},
E                                    'root[26]': {'hash_key': 'test26',
E                                                 'x': {'hello': 'world26'}},
E                                    'root[28]': {'hash_key': 'test28',
E                                                 'x': {'hello': 'world28'}},
E                                    'root[30]': {'hash_key': 'test30',
E                                                 'x': {'hello': 'world30'}},
E                                    'root[32]': {'hash_key': 'test32',
E                                                 'x': {'hello': 'world32'}},
E                                    'root[36]': {'hash_key': 'test36',
E                                                 'x': {'hello': 'world36'}},
E                                    'root[38]': {'hash_key': 'test38',
E                                                 'x': {'hello': 'world38'}},
E                                    'root[42]': {'hash_key': 'test42',
E                                                 'x': {'hello': 'world42'}},
E                                    'root[43]': {'hash_key': 'test43',
E                                                 'x': {'hello': 'world43'}},
E                                    'root[48]': {'hash_key': 'test48',
E                                                 'x': {'hello': 'world48'}},
E                                    'root[52]': {'hash_key': 'test52',
E                                                 'x': {'hello': 'world52'}},
E                                    'root[53]': {'hash_key': 'test53',
E                                                 'x': {'hello': 'world53'}},
E                                    'root[57]': {'hash_key': 'test57',
E                                                 'x': {'hello': 'world57'}},
E                                    'root[58]': {'hash_key': 'test58',
E                                                 'x': {'hello': 'world58'}},
E                                    'root[59]': {'hash_key': 'test59',
E                                                 'x': {'hello': 'world59'}},
E                                    'root[5]': {'hash_key': 'test5',
E                                                'x': {'hello': 'world5'}},
E                                    'root[61]': {'hash_key': 'test61',
E                                                 'x': {'hello': 'world61'}},
E                                    'root[69]': {'hash_key': 'test69',
E                                                 'x': {'hello': 'world69'}},
E                                    'root[71]': {'hash_key': 'test71',
E                                                 'x': {'hello': 'world71'}},
E                                    'root[74]': {'hash_key': 'test74',
E                                                 'x': {'hello': 'world74'}},
E                                    'root[77]': {'hash_key': 'test77',
E                                                 'x': {'hello': 'world77'}},
E                                    'root[79]': {'hash_key': 'test79',
E                                                 'x': {'hello': 'world79'}},
E                                    'root[80]': {'hash_key': 'test80',
E                                                 'x': {'hello': 'world80'}},
E                                    'root[81]': {'hash_key': 'test81',
E                                                 'x': {'hello': 'world81'}},
E                                    'root[82]': {'hash_key': 'test82',
E                                                 'x': {'hello': 'world82'}},
E                                    'root[84]': {'hash_key': 'test84',
E                                                 'x': {'hello': 'world84'}},
E                                    'root[85]': {'hash_key': 'test85',
E                                                 'x': {'hello': 'world85'}},
E                                    'root[89]': {'hash_key': 'test89',
E                                                 'x': {'hello': 'world89'}},
E                                    'root[8]': {'hash_key': 'test8',
E                                                'x': {'hello': 'world8'}},
E                                    'root[90]': {'hash_key': 'test90',
E                                                 'x': {'hello': 'world90'}},
E                                    'root[91]': {'hash_key': 'test91',
E                                                 'x': {'hello': 'world91'}},
E                                    'root[94]': {'hash_key': 'test94',
E                                                 'x': {'hello': 'world94'}},
E                                    'root[95]': {'hash_key': 'test95',
E                                                 'x': {'hello': 'world95'}},
E                                    'root[96]': {'hash_key': 'test96',
E                                                 'x': {'hello': 'world96'}},
E                                    'root[98]': {'hash_key': 'test98',
E                                                 'x': {'hello': 'world98'}},
E                                    'root[99]': {'hash_key': 'test99',
E                                                 'x': {'hello': 'world99'}},
E                                    'root[9]': {'hash_key': 'test9',
E                                                'x': {'hello': 'world9'}}}}
E       assert not {'iterable_item_removed': {'root[59]': {'hash_key': 'test59', 'x': {'hello': 'world59'}}, 'root[99]': {'hash_key': 'test99', 'x': {'hello': 'world99'}}, 'root[43]': {'hash_key': 'test43', 'x': {'hello': 'world43'}}, 'root[30]': {'hash_key': 'test30', 'x': {'hello': 'world30'}}, 'root[38]': {'hash_key': 'test38', 'x': {'hello': 'world38'}}, 'root[26]': {'hash_key': 'test26', 'x': {'hello': 'world26'}}, 'root[11]': {'hash_key': 'test11', 'x': {'hello': 'world11'}}, 'root[5]': {'hash_key': 'test5', 'x': {'hello': 'world5'}}, 'root[81]': {'hash_key': 'test81', 'x': {'hello': 'world81'}}, 'root[85]': {'hash_key': 'test85', 'x': {'hello': 'world85'}}, 'root[69]': {'hash_key': 'test69', 'x': {'hello': 'world69'}}, 'root[89]': {'hash_key': 'test89', 'x': {'hello': 'world89'}}, 'root[98]': {'hash_key': 'test98', 'x': {'hello': 'world98'}}, 'root[79]': {'hash_key': 'test79', 'x': {'hello': 'world79'}}, 'root[74]': {'hash_key': 'test74', 'x': {'hello': 'world74'}}, 'root[8]': {'hash_key': 'test8', 'x': {'hello': 'world8'}}, 'root[80]': {'hash_key': 'test80', 'x': {'hello': 'world80'}}, 'root[19]': {'hash_key': 'test19', 'x': {'hello': 'world19'}}, 'root[32]': {'hash_key': 'test32', 'x': {'hello': 'world32'}}, 'root[61]': {'hash_key': 'test61', 'x': {'hello': 'world61'}}, 'root[10]': {'hash_key': 'test10', 'x': {'hello': 'world10'}}, 'root[52]': {'hash_key': 'test52', 'x': {'hello': 'world52'}}, 'root[53]': {'hash_key': 'test53', 'x': {'hello': 'world53'}}, 'root[91]': {'hash_key': 'test91', 'x': {'hello': 'world91'}}, 'root[21]': {'hash_key': 'test21', 'x': {'hello': 'world21'}}, 'root[23]': {'hash_key': 'test23', 'x': {'hello': 'world23'}}, 'root[84]': {'hash_key': 'test84', 'x': {'hello': 'world84'}}, 'root[25]': {'hash_key': 'test25', 'x': {'hello': 'world25'}}, 'root[15]': {'hash_key': 'test15', 'x': {'hello': 'world15'}}, 'root[18]': {'hash_key': 'test18', 'x': {'hello': 'world18'}}, 'root[82]': {'hash_key': 'test82', 'x': {'hello': 'world82'}}, 'root[13]': {'hash_key': 'test13', 'x': {'hello': 'world13'}}, 'root[48]': {'hash_key': 'test48', 'x': {'hello': 'world48'}}, 'root[94]': {'hash_key': 'test94', 'x': {'hello': 'world94'}}, 'root[9]': {'hash_key': 'test9', 'x': {'hello': 'world9'}}, 'root[96]': {'hash_key': 'test96', 'x': {'hello': 'world96'}}, 'root[28]': {'hash_key': 'test28', 'x': {'hello': 'world28'}}, 'root[14]': {'hash_key': 'test14', 'x': {'hello': 'world14'}}, 'root[12]': {'hash_key': 'test12', 'x': {'hello': 'world12'}}, 'root[90]': {'hash_key': 'test90', 'x': {'hello': 'world90'}}, 'root[71]': {'hash_key': 'test71', 'x': {'hello': 'world71'}}, 'root[95]': {'hash_key': 'test95', 'x': {'hello': 'world95'}}, 'root[57]': {'hash_key': 'test57', 'x': {'hello': 'world57'}}, 'root[16]': {'hash_key': 'test16', 'x': {'hello': 'world16'}}, 'root[58]': {'hash_key': 'test58', 'x': {'hello': 'world58'}}, 'root[42]': {'hash_key': 'test42', 'x': {'hello': 'world42'}}, 'root[1]': {'hash_key': 'test1', 'x': {'hello': 'world1'}}, 'root[36]': {'hash_key': 'test36', 'x': {'hello': 'world36'}}, 'root[77]': {'hash_key': 'test77', 'x': {'hello': 'world77'}}}}

alternator_tests.py:80: AssertionError
```

**Comment by bhalevy** [comment]
@nyh can you please look into this?
Is it a known issue?

**Comment by nyh** [comment]
I have never personally seen this failure before, but don't know how to check the history of this test more rigorously (@fruch always knows, @bhalevy maybe you know too?).

Looking at the test code it seems to start with an empty 3-node cluster, and then just on node1 copy some old sstables and run "nodetool refresh", while the two other nodes remain empty. It then sends a `Scan` Alternator request to read the data and expects it to be found.

In theory, the test is wrong: `Scan` uses CL=QUORUM, which in theory may read from the two nodes that don't have any data, and miss the data. However, in practice, there is no reason why sending a scan to node1 will not use the node itself and instead send the read to the two **other** node. If this is the first time that we ever saw this test fail, I wonder what could have possibly caused this run to be different and send part of the scan to two other nodes instead of performing it locally. 

We could have made this test correct by invoking **repair** on the cluster before reading from it. Perhaps we should do that (CC @fruch). 
But I'm still a bit worried that I don't know what could have caused the read on coordinator node1 to decide to use node2 and node3 as replicas instead of itself. HWLB could have caused this in theory, but 1. shouldn't have, and 2. why haven't we seen this before.

**Comment by fruch** [comment]
@bhalevy is those runs with tablets enabled ?

Causing history of this test shows only those BYO you are running failing with that specific issue:
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/644a3850-e0a7-11ee-81c7-3986d18dafd5

**Comment by nyh** [comment]
> @bhalevy is those runs with tablets enabled ?

I didn't notice the run name had "byo" in it. @bhalevy what does this mean? What did you run there?

**Comment by nyh** [comment]
I wanted to ask for advice from @tgrabiec or @bhalevy or anyone who might know:

Did we change / update **range scan** (full-table scan, not a single partition) implementation for tablets?
What happens when, in a table with RF=3 on 3 nodes, a coordinator shard begins to scan a tablet (a token range) and finds its three replicas are: one on a **different shard** on this node, and two on the two **other nodes**? Does our scan code give priority to reading from the different shard on this node before other nodes? It should - for better performance - but does it? If it does not, it can explain why this (faulty) test failed.

**Comment by nyh** [comment]
I confirmed in a few local runs that this test consistently passes with vnodes, and consistently fails with tablets (adding "--tablets" to dtest). It's not even flaky - it always seems to fail with tablets.

**Comment by nyh** [comment]
The plot thickens. A repair does **not** help. So apparently the refreshed data is not available at all even on the first node - it has nothing to do with this node vs the other nodes.

So I have a new question: The test takes some ancient snapshot of sstables from Scylla 4.0 and does "nodetool refresh" on them. Did we ever check that "nodetool refresh" work correctly with tablets? Did we ever test (and not mixing in Alternator like this test does)?

To reproduce this bug, run
```
SCYLLA=$HOME/scylla/build/dev/scylla ./dtest-dbuild --tablets alternator_tests.py::TesterAlternator::test_load_older_snapshot_and_refresh
```
(change the command to how you run dtests, just don't forget the "--tablets").

**Comment by bhalevy** [comment]
@asias nodetool refresh with tablets is supposed to use load-and-stream.  Can you please look into this issue?

**Comment by asias** [comment]
OK. In my queue.

**Comment by asias** [comment]
The test failed to run nodetool refresh in my run. The nodetool is latest from scylla.git. I build it inside dbuild.

```
        if wait: 
            exit_status = p.wait(timeout=timeout) 
            if exit_status != 0:
>               raise NodetoolError(" ".join(nodetool), exit_status, stdout, stderr)
E               ccmlib.node.ToolError: Subprocess /home/asias/src/cloudius-systems/scylla/resources/cassandra/bin/nodetool -h 127.0.5.1 -p 7199 -Dcom.sun.jndi.rmiURLParsing=legacy -Dcom.scylladb.apiPort=10000 refresh -- alternator_user_table user_table exited with non-zero status; exit status: 2; 
E               stderr: error: loadNewSSTables(java.lang.String, java.lang.String, boolean, boolean)
E               -- StackTrace --
E               java.lang.NoSuchMethodException: loadNewSSTables(java.lang.String, java.lang.String, boolean, boolean)
E                   at com.sun.jmx.mbeanserver.PerInterface.noSuchMethod(PerInterface.java:169)
E                   at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:135)
E                   at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
E                   at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:809)
E                   at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
E                   at com.scylladb.jmx.utils.APIMBeanServer.invoke(APIMBeanServer.java:188)
E                   at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466)
E                   at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307)
E                   at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399)
E                   at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:827)
E                   at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                   at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E                   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E                   at java.lang.reflect.Method.invoke(Method.java:566)
E                   at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
E                   at sun.rmi.transport.Transport$1.run(Transport.java:200)
E                   at sun.rmi.transport.Transport$1.run(Transport.java:197)
E                   at java.security.AccessController.doPrivileged(Native Method)
E                   at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
E                   at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
E                   at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
E                   at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
E                   at java.security.AccessController.doPrivileged(Native Method)
E                   at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
E                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
E                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
E                   at java.lang.Thread.run(Thread.java:829)

../scylla-ccm/ccmlib/node.py:845: ToolError
15:13:35,632 101806  dtest_setup                    DEBUG    dtest_setup.py      :85   | test_load_older_snapshot_and_refresh: Freeing cluster ID 5: link /home/asias/.dtest/5
```

**Comment by mykaul** [comment]
@asias - I'm surprised it's not running the native nodetool, but the Java one?

**Comment by asias** [comment]
Looking at the logs:

Load and stream is turned on. 

```
INFO  2024-03-11 10:58:22,090 [shard 0:strm] sstables_loader - Loading new SSTables for keyspace=alternator_user_table, table=user_table, load_and_stream=auto-enabled-for-tablets, primary_replica_only=false
INFO  2024-03-11 10:58:22,095 [shard 1:strm] sstables_loader - load_and_stream: started ops_uuid=9db08700-22a6-4c11-aff0-267f2363ce56, process [0-1] out of 1 sstables={/jenkins/workspace/scylla-master/byo/dtest-byo/scylla/.dtest/dtest-r69ic54m/test/node1/data/alternator_user_table/user_table-458de680df9611eeb5d2f007d83d5b6d/upload/mc-1-big-Data.db}
INFO  2024-03-11 10:58:22,109 [shard 1:strm] stream_session - [Stream #9db08700-22a6-4c11-aff0-267f2363ce56] Write to sstable for ks=alternator_user_table, cf=user_table, estimated_partitions=128, received_partitions=51
INFO  2024-03-11 10:58:22,111 [shard 1:strm] sstables_loader - load_and_stream: ops_uuid=9db08700-22a6-4c11-aff0-267f2363ce56, ks=alternator_user_table, table=user_table, target_node=127.0.97.1, num_partitions_sent=51, num_bytes_sent=14013
INFO  2024-03-11 10:58:22,111 [shard 1:strm] sstables_loader - load_and_stream: ops_uuid=9db08700-22a6-4c11-aff0-267f2363ce56, ks=alternator_user_table, table=user_table, target_node=127.0.97.3, num_partitions_sent=51, num_bytes_sent=14013
INFO  2024-03-11 10:58:22,111 [shard 1:strm] sstables_loader - load_and_stream: ops_uuid=9db08700-22a6-4c11-aff0-267f2363ce56, ks=alternator_user_table, table=user_table, target_node=127.0.97.2, num_partitions_sent=51, num_bytes_sent=14013
INFO  2024-03-11 10:58:22,111 [shard 1:strm] sstables_loader - load_and_stream: finished ops_uuid=9db08700-22a6-4c11-aff0-267f2363ce56, ks=alternator_user_table, table=user_table, partitions_processed=51 partitions, bytes_processed=14013 bytes, partitions_per_second=3197.7327 partitions/s, bytes_per_second=0.8379212 MiB/s, duration=0.0159488 s, status=succeeded
INFO  2024-03-11 10:58:22,111 [shard 0:strm] sstables_loader - Done loading new SSTables for keyspace=alternator_user_table, table=user_table, load_and_stream=true, primary_replica_only=false, status=succeeded
```

**Comment by mykaul** [comment]
> > @asias - I'm surprised it's not running the native nodetool, but the Java one?
> 
> Have we converted all the java nodetool usage in dtest.git?

I'm surprised we need to - there's this wrapper that is supposed to auto-magically pick the right nodetool.

**Comment by nyh** [comment]
@asias when I first ran this test I also had a nodetool problem which I didn't understand (I don't remember if it's the same one you're seeing), which went away when I rebuilt nodetool - you need to do this once in a while unless you run some sort of build job that builds **everything** (do you?):
```
git submodule update
cd tools/java
ant realclean
JAVA_HOME=/usr/lib/jvm/java-11 JAVA8_HOME=/usr/lib/jvm/java-1.8.0 ant jar
```

(I did this outside of dbuild, YMMV).

Anyway, since nodetool refresh now works for me, and worked in the CI, something must be wrong in your setup...

**Comment by asias** [comment]
I have figured out something that is problematic. I will send a fix to tablet load and stream.

**Comment by asias** [comment]
The fix is here: https://github.com/scylladb/scylladb/pull/17882
