### ISSUE TITLE
"Synchronize labels between PR and the issue(s) fixed by it" fails due to "Resource not accessible by integration"

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#18102]
```
Run python .github/scripts/sync_labels.py --repo scylladb/scylladb --number 18100 --action labeled --label backport/5.2
  python .github/scripts/sync_labels.py --repo scylladb/scylladb --number 18100 --action labeled --label backport/5.2
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***
Found issue number: 18099
Traceback (most recent call last):
  File "/home/runner/work/scylladb/scylladb/.github/scripts/sync_labels.py", line 93, in <module>
    main()
  File "/home/runner/work/scylladb/scylladb/.github/scripts/sync_labels.py", line 89, in main
    sync_labels(repo, args.number, args.label, args.action, args.is_issue)
  File "/home/runner/work/scylladb/scylladb/.github/scripts/sync_labels.py", line 74, in sync_labels
    target.add_to_labels(label)
  File "/usr/lib/python3/dist-packages/github/Issue.py", line 321, in add_to_labels
    headers, data = self._requester.requestJsonAndCheck(
  File "/usr/lib/python3/dist-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/usr/lib/python3/dist-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/issues/labels#add-labels-to-an-issue"}
Error: Process completed with exit code 1.
```

see https://github.com/scylladb/scylladb/actions/runs/8480109476/job/23235253406?pr=18100

**Comment by tchaikov** [comment]
@yaronkaikov could you please take a look?

**Comment by tchaikov** [comment]
after a little bit researching, is it possible the token does not have the necessary permission for mutating an issue?

**Comment by yaronkaikov** [comment]
@tchaikov already working on a fix, thanks for opening an issue, assigned to my self , will fix it soon
