### ISSUE TITLE
test_raft_service_levels.test_service_levels_work_during_recovery: the driver fails to reconnect within 60s after rolling restart

### ISSUE THREAD

**Issue by piodul** [scylladb/scylladb#18231]
Link to the failure in Jenkins: https://jenkins.scylladb.com/job/scylla-enterprise/job/next/2897/testReport/junit/(root)/non-boost%20tests/Build___x86___Unit_Tests_x86___auth_cluster_test_raft_service_levels_debug_2/

Relevant logs: [logs.zip](https://github.com/scylladb/scylladb/files/14975088/logs.zip)

```
manager = <test.pylib.manager_client.ManagerClient object at 0x7f825f626610>

    @pytest.mark.asyncio
    async def test_service_levels_work_during_recovery(manager: ManagerClient):
        servers = await manager.servers_add(3)
    
        logging.info("Waiting until driver connects to every server")
        cql = manager.get_cql()
        hosts = await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
    
        logging.info("Creating a bunch of service levels")
        sls = ["sl" + unique_name() for _ in range(10)]
        for sl in sls:
            await cql.run_async(f"CREATE SERVICE LEVEL {sl}")
    
        # insert a service levels into old table as if it was created before upgrade to v2 and later removed after upgrade
        sl_v1 = "sl" + unique_name()
        await cql.run_async(f"INSERT INTO system_distributed.service_levels (service_level) VALUES ('{sl_v1}')")
    
        logging.info("Validating service levels were created in v2 table")
        result = await cql.run_async("SELECT service_level FROM system.service_levels_v2")
        for sl in result:
            assert sl.service_level in sls
    
        logging.info(f"Restarting hosts {hosts} in recovery mode")
        await asyncio.gather(*(enter_recovery_state(cql, h) for h in hosts))
        for srv in servers:
            await restart(manager, srv)
        cql = await reconnect_driver(manager)
    
        logging.info("Cluster restarted, waiting until driver reconnects to every server")
        hosts = await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)
    
        logging.info("Checking service levels can be read and v2 table is used")
        recovery_result = await cql.run_async("LIST ALL SERVICE LEVELS")
        assert sl_v1 not in [sl.service_level for sl in recovery_result]
        assert set([sl.service_level for sl in recovery_result]) == set(sls)
    
        logging.info("Restoring cluster to normal status")
        await asyncio.gather(*(delete_raft_topology_state(cql, h) for h in hosts))
        await asyncio.gather(*(delete_raft_data_and_upgrade_state(cql, h) for h in hosts))
    
        for srv in servers:
            await restart(manager, srv)
        cql = await reconnect_driver(manager)
>       hosts = await wait_for_cql_and_get_hosts(cql, servers, time.time() + 60)

test/auth_cluster/test_raft_service_levels.py:148: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test/pylib/util.py:98: in wait_for_cql_and_get_hosts
    await asyncio.gather(*(wait_for_cql(cql, h, deadline) for h in hosts))
test/pylib/util.py:65: in wait_for_cql
    await wait_for(cql_ready, deadline)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pred = <function wait_for_cql.<locals>.cql_ready at 0x7f825c95f240>
deadline = 1713146882.1260338, period = 1, before_retry = None

    async def wait_for(
            pred: Callable[[], Awaitable[Optional[T]]],
            deadline: float,
            period: float = 1,
            before_retry: Optional[Callable[[], Any]] = None) -> T:
        while True:
>           assert(time.time() < deadline), "Deadline exceeded, failing test."
E           AssertionError: Deadline exceeded, failing test.

test/pylib/util.py:48: AssertionError
```

**Comment by piodul** [comment]
Note that the failure happened in scylla-enterprise, but I don't think that this is an enterprise-specific issue.

**Comment by piodul** [comment]
In the logs, I see the following:

```
05:07:01.964 DEBUG> Defuncting connection (140197876037264) to 127.98.141.7:9042:
Traceback (most recent call last):
  File "cassandra/connection.py", line 608, in cassandra.connection.defunct_on_error.wrapper
  File "cassandra/connection.py", line 1498, in cassandra.connection.Connection._handle_auth_response
cassandra.AuthenticationFailed: Failed to authenticate to 127.98.141.7:9042: Error from server: code=0100 [Bad credentials] message="Cannot achieve consistency level for cl QUORUM. Requires 1, alive 0"
05:07:01.965 DEBUG> Closing connection (140197876037264) to 127.98.141.7:9042
05:07:01.965 DEBUG> Closed socket to 127.98.141.7:9042
05:07:01.965 WARNING> Host 127.98.141.7:9042 has been marked down
```

Like in https://github.com/scylladb/scylladb/issues/18089#issuecomment-2031245348, the driver seems to give up reconnecting because of an authentication failure. However, now the failure happens in a different place and the error is different.

cc: @nuivall

**Comment by nuivall** [comment]
If we don't want to improve on driver there is https://github.com/scylladb/scylladb/issues/10481 which could help, it's planned to be fixed.

**Comment by nuivall** [comment]
So the cluster 
- starts in v2
- switches off raft
- restarts with raft and fails? 

Then it'd indicate that we start serving traffic before cql is ready, is this possible? Why alive indicate 0 when it should be local read? (quorum message I suspect is a remain we need to keep for auth v1, in v2 this effectively becomes CL=local_one)

**Comment by nuivall** [comment]
Recovery works by disabling raft and rebuilding it's state from scratch.

**Comment by kostja** [comment]
@piodul hasn't happened in a while, suggest to cloe

**Comment by piodul** [comment]
Closing, didn't happen in a while.
