### ISSUE TITLE
Scylla stop times out during secondary_indexes_test.TestSecondaryIndexes.test_stop_node_during_index_build

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#18279]
Happened while validating #18272 (unrelated, because the PR touches only tablets moving API, that's unused by this test).
https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/9016/

```
       found_cores, ignored_cores = self.find_cores()
        if found_cores:
>           raise AssertionError("Core file(s) found. Marking test as failed.")
E           AssertionError: Core file(s) found. Marking test as failed.

```

core file generated by node2

```
./archive/logs-full.release.006/last/node2.log
./archive/logs-full.release.006/last/node2-scylla.30548.1713357658.core.gz
```

in logs there's no indication of dumped core, but likely it happened during node restart

```
...
INFO  2024-04-17 12:38:53,281 [shard 1:main] messaging_service - Stopped clients
WARN  2024-04-17 12:38:53,281 [shard 1:strm] view - Error applying view update to 127.0.83.4 (view: ks.b_index_index, base token: 4191402332341273215, view token: 6358006420993385383): exceptions::mutation_write_failure_exception (Operat>
WARN  2024-04-17 12:38:53,281 [shard 1:strm] view - Error executing build step for base ks.cf: exceptions::mutation_write_failure_exception (Operation failed for ks.b_index_index - received 0 responses and 1 failures from 1 CL=ONE.)
INFO  2024-04-17 12:38:53,281 [shard 1:main] messaging_service - Shutting down nontls server - Done
INFO  2024-04-17 12:38:53,281 [shard 0:main] storage_service - Stop transport: shutdown messaging_service done
INFO  2024-04-17 12:38:53,281 [shard 0:main] storage_service - Stop transport: shutdown stream_manager done
INFO  2024-04-17 12:38:53,281 [shard 0:main] storage_service - Stop transport: done
INFO  2024-04-17 12:38:53,281 [shard 0:main] tracing - Asked to shut down
INFO  2024-04-17 12:38:53,281 [shard 0:main] tracing - Tracing is down
INFO  2024-04-17 12:38:53,281 [shard 1:main] tracing - Asked to shut down
INFO  2024-04-17 12:38:53,281 [shard 1:main] tracing - Tracing is down
INFO  2024-04-17 12:38:53,281 [shard 0:main] batchlog_manager - Asked to drain
INFO  2024-04-17 12:38:53,281 [shard 0:main] batchlog_manager - Drained
INFO  2024-04-17 12:38:53,281 [shard 1:main] batchlog_manager - Asked to drain
INFO  2024-04-17 12:38:53,281 [shard 1:main] batchlog_manager - Drained
INFO  2024-04-17 12:38:53,281 [shard 0:main] compaction_manager - Asked to drain
INFO  2024-04-17 12:38:53,281 [shard 0:main] compaction_manager - Drained
INFO  2024-04-17 12:38:53,281 [shard 1:main] compaction_manager - Asked to drain
INFO  2024-04-17 12:38:53,281 [shard 1:main] compaction_manager - Drained
INFO  2024-04-17 12:38:53,282 [shard 0:main] database - Flushing non-system tables
INFO  2024-04-17 12:38:53,282 [shard 1:main] database - Flushing non-system tables
INFO  2024-04-17 12:38:53,472 [shard 1:main] database - Flushed non-system tables
INFO  2024-04-17 12:38:53,489 [shard 0:main] database - Flushed non-system tables
INFO  2024-04-17 12:38:53,489 [shard 1:main] database - Flushing system tables
INFO  2024-04-17 12:38:53,490 [shard 0:main] database - Flushing system tables
INFO  2024-04-17 12:38:53,500 [shard 1:main] database - Flushed system tables
INFO  2024-04-17 12:38:53,543 [shard 0:main] database - Flushed system tables
INFO  2024-04-17 12:38:53,553 [shard 0:main] view - Draining view builder
INFO  2024-04-17 12:38:53,553 [shard 1:main] view - Draining view builder
WARN  2024-04-17 12:38:53,553 [shard 1:strm] view - Unexcepted error executing build step: <no exception>. Ignored.
INFO  2024-04-17 12:38:54,083 [shard 0:main] raft_group_registry - marking Raft server 7aac855b-d34b-40e2-be8f-2f6a22d08101 as dead for raft groups
INFO  2024-04-17 12:38:54,098 [shard 0:main] raft_group_registry - marking Raft server f395cd6d-278a-441d-bead-ec5421a8e6e5 as dead for raft groups
INFO  2024-04-17 12:38:54,134 [shard 0:main] raft_group_registry - marking Raft server 0e52a6b3-ab36-4649-a106-78317dba6c3e as dead for raft groups
WARN  2024-04-17 12:39:52,569 [shard 0:main] gossip - Fail to apply application_state: seastar::abort_requested_exception (abort requested)
WARN  2024-04-17 12:40:31,630 [shard 0:main] service_level_controller - update_from_distributed_data: failed to update configuration for more than  90 seconds : exceptions::read_timeout_exception (Operation timed out for system_distribut>
WARN  2024-04-17 12:40:52,569 [shard 0:main] gossip - Fail to apply application_state: seastar::abort_requested_exception (abort requested)
```

then new instance starting logs pop up

@benipeled , how can I get scylla binary for this CI run?

**Comment by benipeled** [comment]
> @benipeled , how can I get scylla binary for this CI run?

Check the build metadata file `00-Build.txt` for the reloc package path, In this case
https://downloads.scylladb.com/unstable/scylla/master/relocatable/2024-04-17T13:39:39Z/

**Comment by xemul** [comment]
Pretty weird

```
Program terminated with signal SIGQUIT, Quit.
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
38              cmpq $-4095, %rax       /* Check %rax for error.  */                                                                                                                                                                          
[Current thread is 1 (Thread 0x7fc83f41fdc0 (LWP 30548))]
(gdb) thread apply all bt

Thread 4 (Thread 0x7fc837dff6c0 (LWP 30558)):
#0  0x00007fc83f52310a in __GI___libc_read (nbytes=8, buf=0x7fc837dcf350, fd=9) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __GI___libc_read (fd=9, buf=0x7fc837dcf350, nbytes=8) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x0000000005e9b025 in seastar::thread_pool::work(seastar::basic_sstring<char, unsigned int, 15u, true>) ()
#3  0x0000000005e9b333 in std::_Function_handler<void (), seastar::thread_pool::thread_pool(seastar::reactor&, seastar::basic_sstring<char, unsigned int, 15u, true>)::$_0>::_M_invoke(std::_Any_data const&) ()
#4  0x0000000005e1350b in seastar::posix_thread::start_routine(void*) ()
#5  0x00007fc83f4ae947 in start_thread (arg=<optimized out>) at pthread_create.c:444
#6  0x00007fc83f534970 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 3 (Thread 0x7fc83c7ff6c0 (LWP 30557)):
#0  0x00007fc83f52310a in __GI___libc_read (nbytes=8, buf=0x7fc83c7cf350, fd=5) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __GI___libc_read (fd=5, buf=0x7fc83c7cf350, nbytes=8) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x0000000005e9b025 in seastar::thread_pool::work(seastar::basic_sstring<char, unsigned int, 15u, true>) ()
#3  0x0000000005e9b333 in std::_Function_handler<void (), seastar::thread_pool::thread_pool(seastar::reactor&, seastar::basic_sstring<char, unsigned int, 15u, true>)::$_0>::_M_invoke(std::_Any_data const&) ()
#4  0x0000000005e1350b in seastar::posix_thread::start_routine(void*) ()
#5  0x00007fc83f4ae947 in start_thread (arg=<optimized out>) at pthread_create.c:444
#6  0x00007fc83f534970 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 2 (Thread 0x7fc83cdff6c0 (LWP 30556)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x0000000005ea0d01 in seastar::internal::io_pgetevents(unsigned long, long, long, seastar::internal::linux_abi::io_event*, timespec const*, __sigset_t const*, bool) ()
#2  0x0000000005e9cc13 in seastar::reactor_backend_aio::await_events(int, __sigset_t const*) ()
#3  0x0000000005e9d33d in seastar::reactor_backend_aio::wait_and_process_events(__sigset_t const*) ()
#4  0x0000000005e541ad in seastar::reactor::do_run() ()
#5  0x0000000005e77df1 in std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_0>::_M_invoke(std::_Any_data const&) ()
#6  0x0000000005e1350b in seastar::posix_thread::start_routine(void*) ()
#7  0x00007fc83f4ae947 in start_thread (arg=<optimized out>) at pthread_create.c:444
#8  0x00007fc83f534970 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 1 (Thread 0x7fc83f41fdc0 (LWP 30548)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x0000000005ea0d01 in seastar::internal::io_pgetevents(unsigned long, long, long, seastar::internal::linux_abi::io_event*, timespec const*, __sigset_t const*, bool) ()
#2  0x0000000005e9cc13 in seastar::reactor_backend_aio::await_events(int, __sigset_t const*) ()
#3  0x0000000005e9d33d in seastar::reactor_backend_aio::wait_and_process_events(__sigset_t const*) ()
#4  0x0000000005e541ad in seastar::reactor::do_run() ()
#5  0x0000000005e53219 in seastar::reactor::run() ()
#6  0x0000000005de0fe8 in seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) ()
#7  0x0000000005de019d in seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) ()
#8  0x00000000013b4a5a in scylla_main(int, char**) ()
#9  0x00000000013b64b1 in ?? ()
#10 0x00000000013b30dd in main ()
```

**Comment by xemul** [comment]
Ah
```
12:40:58,297 793     ccm                            WARNING  cluster.py          :768  | test_stop_node_during_index_build: node2: node2 is still running after 127 seconds. Trying to generate coredump using kill(30548, SIGQUIT)...
```
