### ISSUE TITLE
Nodetool repair fails with error: error executing POST request to http://localhost:10000/storage_service/repair_async/drop_table_during_repair_ks_0 with parameters: remote replied with status code 500 Internal Server Error

### ISSUE THREAD

**Issue by dimakr** [scylladb/scylladb#18341]
## Packages

Scylla version: `5.5.0~dev-20240411.0be61e51d329` with build-id `54e018bb43eb2ae707aac127097747cd39532532`
Kernel Version: `5.15.0-1057-aws`

## Issue description

- [X] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

The NoCorruptRepairMonkey nemesis is executed during the test.
The nemesis performs the following:
1. Creates 10 test tables, fills them in with the command
```
cassandra-stress write n=400000 cl=QUORUM -mode native cql3 -schema 'replication(strategy=NetworkTopologyStrategy, replication_factor=6' -log interval=5
```
2. Starts node repair
3. Drops tables one by one during repair

During `disrupt_no_corrupt_repair` Nemesis, before any table is dropped, the 'nodetool repair' command fails with the following error:
sct logs
```
< t:2024-04-13 07:37:24,838 f:remote_base.py  l:521  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool -u cassandra -pw 'cassandra'  repair "...
< t:2024-04-13 07:37:24,844 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-04-13 07:37:24.827: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=49486fa2-8a9b-48b1-b2e2-13d4093af2bf: nodetool_command=repair node=longevity-tls-50gb-3d-master-db-node-1e2fb19f-3
...
< t:2024-04-13 07:37:25,417 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > error executing POST request to http://localhost:10000/storage_service/repair_async/drop_table_during_repair_ks_0 with parameters {{jobThreads -> 1}, {primaryRange -> false}, {pullRepair -> false}, {incremental -> false}, {parallelism -> parallel}, {ignoreUnreplicatedKeyspaces -> false}, {trace -> false}}: remote replied with status code 500 Internal Server Error:
< t:2024-04-13 07:37:25,638 f:db_log_reader.py l:123  c:sdcm.db_log_reader   p:DEBUG > 2024-04-13T07:37:25.543+00:00 longevity-tls-50gb-3d-master-db-node-1e2fb19f-3     !INFO | scylla[8522]:  [shard  0:strm] repair - repair[86280921-e685-46d9-af2f-18d02fad8412]: starting user-requested repair for keyspace drop_table_during_repair_ks_0, repair id 7, options {{trace -> false}, {primaryRange -> false}, {jobThreads -> 1}, {incremental -> false}, {parallelism -> parallel}}
< t:2024-04-13 07:37:25,934 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > std::runtime_error (Node is not in NORMAL status yet!)
< t:2024-04-13 07:37:25,934 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "/usr/bin/nodetool -u cassandra -pw 'cassandra'  repair "; Exit status: 4
< t:2024-04-13 07:37:25,940 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > STDERR: error executing POST request to http://localhost:10000/storage_service/repair_async/drop_table_during_repair_ks_0 with parameters {{jobThreads -> 1}, {primaryRange -> false}, {pullRepair -> false}, {incremental -> false}, {parallelism -> parallel}, {ignoreUnreplicatedKeyspaces -> false}, {trace -> false}}: remote replied with status code 500 Internal Server Error:
< t:2024-04-13 07:37:25,940 f:base.py         l:150  c:RemoteLibSSH2CmdRunner p:DEBUG > std::runtime_error (Node is not in NORMAL status yet!)
< t:2024-04-13 07:37:25,951 f:load_info_store.py l:221  c:sdcm.utils.adaptive_timeouts.load_info_store p:DEBUG > Storing adaptive timeout info: a9c7d96b-dec0-460d-99a3-ce7592caf3ec={'node_name': 'longevity-tls-50gb-3d-master-db-node-1e2fb19f-3', 'cpu_load_5': 0.36, 'shards_count': 14, 'read_bandwidth_mb': 2944.594482421875, 'write_bandwidth_mb': 2183.228759765625, 'read_iops': 385400, 'write_iops': 240628, 'node_data_size_mb': 11857, 'scylla_version': '5.5.0~dev-0.20240411.0be61e51d329 with build-id 54e018bb43eb2ae707aac127097747cd39532532', 'n_db_nodes': 6, 'test_id': '1e2fb19f-7e5b-48a3-b968-fad1e17be057', 'end_time': datetime.datetime(2024, 4, 13, 7, 37, 25, 951644), 'operation': 'REPAIR', 'duration': 1.124155044555664, 'timeout': 172800, 'timeout_occurred': False}
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-04-13 07:37:25.945: (NodetoolEvent Severity.ERROR) period_type=end event_id=49486fa2-8a9b-48b1-b2e2-13d4093af2bf during_nemesis=NoCorruptRepair duration=1s: nodetool_command=repair node=longevity-tls-50gb-3d-master-db-node-1e2fb19f-3 errors=['Encountered a bad command exit code!\n\nCommand: "/usr/bin/nodetool -u cassandra -pw \'cassandra\'  repair "\n\nExit code: 4\n\nStdout:\n\n\n\nStderr:\n\nerror executing POST request to http://localhost:10000/storage_service/repair_async/drop_table_during_repair_ks_0 with parameters {{jobThreads -> 1}, {primaryRange -> false}, {pullRepair -> false}, {incremental -> false}, {parallelism -> parallel}, {ignoreUnreplicatedKeyspaces -> false}, {trace -> false}}: remote replied with status code 500 Internal Server Error:\nstd::runtime_error (Node is not in NORMAL status yet!)\n\n', 'Traceback (most recent call last):\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2518, in run_nodetool\n    self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run\n    result = _run()\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner\n    return func(*args, **kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run\n    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute\n    result = connection.run(**command_kwargs)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run\n    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)\n  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run\n    raise UnexpectedExit(result)\nsdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!\n\nCommand: "/usr/bin/nodetool -u cassandra -pw \'cassandra\'  repair "\n\nExit code: 4\n\nStdout:\n\n\n\nStderr:\n\nerror executing POST request to http://localhost:10000/storage_service/repair_async/drop_table_during_repair_ks_0 with parameters {{jobThreads -> 1}, {primaryRange -> false}, {pullRepair -> false}, {incremental -> false}, {parallelism -> parallel}, {ignoreUnreplicatedKeyspaces -> false}, {trace -> false}}: remote replied with status code 500 Internal Server Error:\nstd::runtime_error (Node is not in NORMAL status yet!)\n\n\n']
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Traceback (most recent call last):
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2518, in run_nodetool
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     result = _run()
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     return func(*args, **kwargs)
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     result = connection.run(**command_kwargs)
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >   File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  >     raise UnexpectedExit(result)
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Command: "/usr/bin/nodetool -u cassandra -pw 'cassandra'  repair "
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Exit code: 4
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Stdout:
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > Stderr:
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > error executing POST request to http://localhost:10000/storage_service/repair_async/drop_table_during_repair_ks_0 with parameters {{jobThreads -> 1}, {primaryRange -> false}, {pullRepair -> false}, {incremental -> false}, {parallelism -> parallel}, {ignoreUnreplicatedKeyspaces -> false}, {trace -> false}}: remote replied with status code 500 Internal Server Error:
< t:2024-04-13 07:37:25,953 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > std::runtime_error (Node is not in NORMAL status yet!)
```

Logs of scylladb nodes look ok - no erros, failures, segfault, etc. during the Nemesis run.

## Impact

'nodetool repair' command execution fails with the 500 internal server error.

## How frequently does it reproduce?

The issue was observed for the first time.

## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-master-db-node-1e2fb19f-8 (52.30.228.31 | 10.4.9.61) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-1e2fb19f-7 (18.203.157.89 | 10.4.10.198) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-1e2fb19f-6 (3.253.33.204 | 10.4.9.95) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-1e2fb19f-5 (34.249.49.128 | 10.4.10.146) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-1e2fb19f-4 (54.74.6.242 | 10.4.9.129) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-1e2fb19f-3 (3.248.202.161 | 10.4.10.64) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-1e2fb19f-2 (18.203.244.67 | 10.4.10.160) (shards: 14)
- longevity-tls-50gb-3d-master-db-node-1e2fb19f-1 (3.255.77.22 | 10.4.11.36) (shards: 14)

OS / Image: `ami-03a7123d7bfc23027` (aws: undefined_region)

Test: `longevity-50gb-3days-test`
Test id: `1e2fb19f-7e5b-48a3-b968-fad1e17be057`
Test name: `scylla-master/tier1/longevity-50gb-3days-test`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ead2529c1f5f3816f04e3b23de737a359134c053/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 1e2fb19f-7e5b-48a3-b968-fad1e17be057`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=1e2fb19f-7e5b-48a3-b968-fad1e17be057)
- Show all stored logs command: `$ hydra investigate show-logs 1e2fb19f-7e5b-48a3-b968-fad1e17be057`

## Logs:
- **db-cluster-1e2fb19f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1e2fb19f-7e5b-48a3-b968-fad1e17be057/20240414_025240/db-cluster-1e2fb19f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1e2fb19f-7e5b-48a3-b968-fad1e17be057/20240414_025240/db-cluster-1e2fb19f.tar.gz)
- **sct-runner-events-1e2fb19f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1e2fb19f-7e5b-48a3-b968-fad1e17be057/20240414_025240/sct-runner-events-1e2fb19f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1e2fb19f-7e5b-48a3-b968-fad1e17be057/20240414_025240/sct-runner-events-1e2fb19f.tar.gz)
- **sct-1e2fb19f.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1e2fb19f-7e5b-48a3-b968-fad1e17be057/20240414_025240/sct-1e2fb19f.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1e2fb19f-7e5b-48a3-b968-fad1e17be057/20240414_025240/sct-1e2fb19f.log.tar.gz)
- **loader-set-1e2fb19f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1e2fb19f-7e5b-48a3-b968-fad1e17be057/20240414_025240/loader-set-1e2fb19f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1e2fb19f-7e5b-48a3-b968-fad1e17be057/20240414_025240/loader-set-1e2fb19f.tar.gz)
- **monitor-set-1e2fb19f.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/1e2fb19f-7e5b-48a3-b968-fad1e17be057/20240414_025240/monitor-set-1e2fb19f.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1e2fb19f-7e5b-48a3-b968-fad1e17be057/20240414_025240/monitor-set-1e2fb19f.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-50gb-3days-test/10/)
[Argus](https://argus.scylladb.com/test/98050732-dfe3-464c-a66a-f235bad30829/runs?additionalRuns[]=1e2fb19f-7e5b-48a3-b968-fad1e17be057)
</details>

**Comment by mykaul** [comment]
@dimakr - without 'triage/...' label, it may not be triaged - this one wasn't even looked at.

**Comment by temichus** [comment]
seen in SCT only once on 2024-04-13
