### ISSUE TITLE
A new node init does not complete (test timeout after waiting for 1 hour)

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#18802]
## Packages

Scylla version: `5.5.0~dev-20240520.a517fcf970ec` with build-id `156473840db1bc25a83a123598850e7a1e07f184`

Kernel Version: `5.15.0-1061-aws`

## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*
The test started with a nemesis that adds a new node: node-7.
IIRC this should take about few minutes in such a test scenario.
The initialization of the new node takes a bit more than an hour.
The test has a 1 hour timeout so the BootstrapStreamingError nemesis fails for that duration.
```
< t:2024-05-21 10:02:18,261 f:nemesis.py      l:1137 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Set current_disruption -> BootstrapStreamingError
< t:2024-05-21 10:02:18,261 f:nemesis.py      l:406  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Current Target: Node longevity-100gb-4h-master-db-node-9d8db95e-1 [18.201.254.160 | 10.4.9.90] with running nemesis: BootstrapStreamingError
< t:2024-05-21 10:02:47,985 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-05-21 10:02:47.980: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=97924dec-4c2b-4994-8151-6542ef916fdc: nemesis_name=BootstrapStreamingError target_node=Node longevity-100gb-4h-master-db-node-9d8db95e-1 [18.201.254.160 | 10.4.9.90]
< t:2024-05-21 10:08:42,729 f:db_log_reader.py l:123  c:sdcm.db_log_reader   p:DEBUG > 2024-05-21T10:08:42.660+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[6858]:  [shard  0:main] init - Scylla version 5.5.0~dev-0.20240520.a517fcf970ec with build-id 156473840db1bc25a83a123598850e7a1e07f184 starting ...
< t:2024-05-21 10:08:52,410 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2024-05-21 10:08:52.014 <2024-05-21 10:08:51.935>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=bb90d180-0cd5-4a05-b46f-32e49b560e22 during_nemesis=BootstrapStreamingError: type=DATABASE_ERROR regex=(^ERROR|!\s*?ERR).*\[shard.*\] line_number=1857 node=longevity-100gb-4h-master-db-node-9d8db95e-7
< t:2024-05-21 10:09:52,684 f:db_log_reader.py l:123  c:sdcm.db_log_reader   p:DEBUG > 2024-05-21T10:09:52.594+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - Scylla version 5.5.0~dev-0.20240520.a517fcf970ec with build-id 156473840db1bc25a83a123598850e7a1e07f184 starting ...
< t:2024-05-21 11:10:15,314 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2024-05-21 11:10:15.311: (SoftTimeoutEvent Severity.ERROR) period_type=one-time event_id=06ee7bac-1433-4509-ae93-3812710e70a8 during_nemesis=BootstrapStreamingError, source=SoftTimeout message=operation 'NEW_NODE' took 3625.333893299103s and soft-timeout was set to 3600s
```
```
Nemesis Information
Class: Sisyphus
Name: disrupt_bootstrap_streaming_error
Status: Failed
Failure reason
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 70, in wait_for
    res = retry(func, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 194, in reraise
    raise self
tenacity.RetryError: RetryError[<Future at 0x7fedaa78dc00 state=finished returned bool>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/raft/common.py", line 146, in clean_and_restart_bootstrap_after_abort
    self.bootstrap_node.start_scylla_server(verify_up_timeout=bootstrap_timeout, verify_down=True)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2423, in start_scylla_server
    self.wait_db_up(timeout=verify_up_timeout)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 1364, in wait_db_up
    wait.wait_for(func=self.db_up, step=60, text=text, timeout=timeout,
  File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 86, in wait_for
    raise raising_exc from ex
sdcm.exceptions.WaitForTimeoutError: Wait for: longevity-100gb-4h-master-db-node-9d8db95e-7: Waiting for DB services to be up: timeout - 3600 seconds - expired

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5117, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4973, in disrupt_bootstrap_streaming_error
    bootstrapabortmanager.clean_and_restart_bootstrap_after_abort()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/raft/common.py", line 153, in clean_and_restart_bootstrap_after_abort
    raise BootstrapStreamErrorFailure(f"Rebootstrap failed with error: {exc}") from exc
sdcm.exceptions.BootstrapStreamErrorFailure: Rebootstrap failed with error: Wait for: longevity-100gb-4h-master-db-node-9d8db95e-7: Waiting for DB services to be up: timeout - 3600 seconds - expired

```
node-7 log had:
```
2024-05-21T10:09:52.594+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - Scylla version 5.5.0~dev-0.20240520.a517fcf970ec with build-id 156473840db1bc25a83a123598850e7a1e07f184 starting ...
2024-05-21T10:09:52.594+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting API server
2024-05-21T10:09:52.594+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting prometheus API server
2024-05-21T10:09:52.594+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - creating snitch
2024-05-21T10:09:52.594+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting tokens manager
2024-05-21T10:09:52.594+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting effective_replication_map factory
2024-05-21T10:09:52.594+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting migration manager notifier
2024-05-21T10:09:52.594+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting per-shard database core
2024-05-21T10:09:52.594+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - creating and verifying directories
2024-05-21T10:09:52.594+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting compaction_manager
2024-05-21T10:09:52.595+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting database
2024-05-21T10:09:52.595+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting storage proxy
2024-05-21T10:09:52.595+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting query processor
2024-05-21T10:09:52.595+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting lifecycle notifier
2024-05-21T10:09:52.595+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - creating tracing
2024-05-21T10:09:52.596+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - Scylla API server listening on 127.0.0.1:10000 ...
2024-05-21T10:09:52.596+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting system keyspace
2024-05-21T10:09:52.596+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - loading system sstables
2024-05-21T10:09:52.885+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting messaging service
2024-05-21T10:09:52.885+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting gossiper
2024-05-21T10:09:52.886+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - seeds={10.4.8.245, 10.4.8.31, 10.4.8.104, 10.4.9.90, 10.4.10.116, 10.4.10.118}, listen_address=10.4.10.65, broadcast_address=10.4.10.65
2024-05-21T10:09:52.886+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting Raft address map
2024-05-21T10:09:52.886+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting direct failure detector pinger service
2024-05-21T10:09:52.886+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting direct failure detector service
2024-05-21T10:09:52.886+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting forward service
2024-05-21T10:09:52.886+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting migration manager
2024-05-21T10:09:52.886+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - initializing query processor remote part
2024-05-21T10:09:52.886+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - initializing storage service
2024-05-21T10:09:52.886+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - initializing virtual tables
2024-05-21T10:09:52.886+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting Raft Group Registry service
2024-05-21T10:09:53.134+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - loading tablet metadata
2024-05-21T10:09:53.134+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - loading non-system sstables
2024-05-21T10:09:53.135+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting view update generator
2024-05-21T10:09:53.135+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting commit log
2024-05-21T10:09:53.135+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - initializing storage proxy RPC verbs
2024-05-21T10:09:53.135+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting streaming service
2024-05-21T10:09:53.135+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting hinted handoff manager
2024-05-21T10:09:53.135+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting repair service
2024-05-21T10:09:53.138+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting CDC Generation Management service
2024-05-21T10:09:53.138+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting CDC log service
2024-05-21T10:09:53.138+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting storage service
2024-05-21T10:09:53.138+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting sstables loader
2024-05-21T10:09:53.138+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]:  [shard  0:main] init - starting the view builder
```
So it looks like init process doesn't get to the step of `init - starting system distributed keyspace` at all. (it did get to it before the initial scylla-service stop/start)

## Impact

*Describe the impact this issue causes to the user.*
long new node initialization duration
## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*
always
## Installation details

Cluster size: 6 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
- longevity-100gb-4h-master-db-node-9d8db95e-8 (3.253.69.231 | 10.4.10.61) (shards: 14)
- longevity-100gb-4h-master-db-node-9d8db95e-7 (34.240.4.28 | 10.4.10.65) (shards: -1)
- longevity-100gb-4h-master-db-node-9d8db95e-6 (3.254.73.113 | 10.4.10.116) (shards: 14)
- longevity-100gb-4h-master-db-node-9d8db95e-5 (34.248.49.36 | 10.4.8.245) (shards: 14)
- longevity-100gb-4h-master-db-node-9d8db95e-4 (52.212.245.139 | 10.4.10.118) (shards: 14)
- longevity-100gb-4h-master-db-node-9d8db95e-3 (34.244.78.242 | 10.4.8.31) (shards: 14)
- longevity-100gb-4h-master-db-node-9d8db95e-2 (3.249.169.206 | 10.4.8.104) (shards: 14)
- longevity-100gb-4h-master-db-node-9d8db95e-1 (18.201.254.160 | 10.4.9.90) (shards: 14)

OS / Image: `ami-02f085ed51efb22a5` (aws: undefined_region)

Test: `longevity-100gb-4h-test-no-tablets`
Test id: `9d8db95e-fd8c-4efb-bf36-6299ef6709a5`
Test name: `scylla-staging/yarongilor/longevity-100gb-4h-test-no-tablets`
Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f602bf2b31e5e939da49bcd59d27f4b06967ee9e/test-cases/longevity/longevity-100gb-4h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 9d8db95e-fd8c-4efb-bf36-6299ef6709a5`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=9d8db95e-fd8c-4efb-bf36-6299ef6709a5)
- Show all stored logs command: `$ hydra investigate show-logs 9d8db95e-fd8c-4efb-bf36-6299ef6709a5`

## Logs:
- **db-cluster-9d8db95e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9d8db95e-fd8c-4efb-bf36-6299ef6709a5/20240521_121559/db-cluster-9d8db95e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9d8db95e-fd8c-4efb-bf36-6299ef6709a5/20240521_121559/db-cluster-9d8db95e.tar.gz)
- **sct-runner-events-9d8db95e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9d8db95e-fd8c-4efb-bf36-6299ef6709a5/20240521_121559/sct-runner-events-9d8db95e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9d8db95e-fd8c-4efb-bf36-6299ef6709a5/20240521_121559/sct-runner-events-9d8db95e.tar.gz)
- **sct-9d8db95e.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9d8db95e-fd8c-4efb-bf36-6299ef6709a5/20240521_121559/sct-9d8db95e.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9d8db95e-fd8c-4efb-bf36-6299ef6709a5/20240521_121559/sct-9d8db95e.log.tar.gz)
- **loader-set-9d8db95e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9d8db95e-fd8c-4efb-bf36-6299ef6709a5/20240521_121559/loader-set-9d8db95e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9d8db95e-fd8c-4efb-bf36-6299ef6709a5/20240521_121559/loader-set-9d8db95e.tar.gz)
- **monitor-set-9d8db95e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9d8db95e-fd8c-4efb-bf36-6299ef6709a5/20240521_121559/monitor-set-9d8db95e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9d8db95e-fd8c-4efb-bf36-6299ef6709a5/20240521_121559/monitor-set-9d8db95e.tar.gz)
- **parallel-timelines-report-9d8db95e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/9d8db95e-fd8c-4efb-bf36-6299ef6709a5/20240521_121559/parallel-timelines-report-9d8db95e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/9d8db95e-fd8c-4efb-bf36-6299ef6709a5/20240521_121559/parallel-timelines-report-9d8db95e.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/longevity-100gb-4h-test-no-tablets/3/)
[Argus](https://argus.scylladb.com/test/94c31ab5-b48c-4059-bb07-d6bb4a9be733/runs?additionalRuns[]=9d8db95e-fd8c-4efb-bf36-6299ef6709a5)
</details>

**Comment by fruch** [comment]
> > I would recommend finding a reference of this nemesis last working on master, so we can understand when this regression starts
> 
> In the original job of tablets 100-gb-4h it fails since job started at [march](https://argus.scylladb.com/test/bfb2ef96-b741-43ea-9e7d-82e652c0ebdc/runs?additionalRuns%5B%5D=80524eef-d4d1-4e26-a3eb-c4888f617693)

so basily you are it's failing with tablets since the every tablets are used.
so it's not a degregarding in specific version, but caused directly by tablets.

**Comment by fruch** [comment]
@yarongilor 

I would also suggest using building a reproducer with this nemesis only, so a dev looking into this, could rerun the exact nemesis with the correct tablet configuration, to investigate this.

**Comment by bhalevy** [comment]
@yarongilor is this happening only with tablets or is the regression also without tablets?

**Comment by bhalevy** [comment]
> @yarongilor is this happening only with tablets or is the regression also without tablets?

Based on https://github.com/scylladb/scylla-cluster-tests/issues/7448#issuecomment-2122852919

> The issue is reproduced in the exact scenario except no tablets.
> opened https://github.com/scylladb/scylladb/issues/18802

Please confirm.
If so, we can remove the `area/tablets` label and I suggest the investigation be led by @kbr-scylla and team.

**Comment by yarongilor** [comment]
> > @yarongilor is this happening only with tablets or is the regression also without tablets?
> 
> Based on [scylladb/scylla-cluster-tests#7448 (comment)](https://github.com/scylladb/scylla-cluster-tests/issues/7448#issuecomment-2122852919)
> 
> > The issue is reproduced in the exact scenario except no tablets.
> > opened #18802
> 
> Please confirm. If so, we can remove the `area/tablets` label and I suggest the investigation be led by @kbr-scylla and team.


Exactly. the bug was only opened after reproduced WITHOUT tablets.
As can be seen, no "tablets" in bug description except for "Test: longevity-100gb-4h-test-**no-tablets**".
(It was just discovered with tablets, that selected this nemesis at the beginning of test)

**Comment by yarongilor** [comment]
> @yarongilor
> 
> I would also suggest using building a reproducer with this nemesis only, so a dev looking into this, could rerun the exact nemesis with the correct tablet configuration, to investigate this.

The scenario is 100% easily reproduced by simply rerunning this staging job and the add-node operation will immediately start at the beginning of the first nemesis.

**Comment by kbr-scylla** [comment]
@yarongilor the report did not mention a **very important fact** (which instantaneously leads to explanation why we get this behavior):

The test started bootstrapping the node, **then interrupted the procedure and restarted the node to try bootstrap again**.

```
2024-05-21T10:08:42.660+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[6858]:  [shard  0:main] init - Scylla version 5.5.0~dev-0.20240520.a517fcf970ec with build-id 156473840db1bc25a83a123598850e7a1e07f184 starting ...

...

2024-05-21T10:08:51.645+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7   !NOTICE | sudo[7023]: scyllaadm : PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/systemctl stop scylla-server.service
2024-05-21T10:08:51.646+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | sudo[7023]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
2024-05-21T10:08:51.779+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | systemd[1]: scylla-housekeeping-daily.timer: Deactivated successfully.
2024-05-21T10:08:51.779+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | systemd[1]: Stopped Run Scylla Housekeeping daily mode.
2024-05-21T10:08:51.779+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | systemd[1]: scylla-housekeeping-restart.timer: Deactivated successfully.
2024-05-21T10:08:51.779+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | systemd[1]: Stopped Run Scylla Housekeeping restart mode.
2024-05-21T10:08:51.780+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[6858]:  [shard  0:main] compaction_manager - Asked to stop
2024-05-21T10:08:51.780+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[6858]:  [shard  0:main] view_update_generator - Terminating background fiber
2024-05-21T10:08:51.780+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | systemd[1]: Stopping Scylla Server...

...

2024-05-21T10:09:51.543+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]: Scylla version 5.5.0~dev-0.20240520.a517fcf970ec with build-id 156473840db1bc25a83a123598850e7a1e07f184 starting ...
```

The reason for this behavior is that after a failed bootstrap attempt, **the node is permanently banned from the cluster**, meaning that existing members of the cluster refuse to communicate with it (they drop all messages). This ban is host ID based. So when you restart the node, it  tries to bootstrap again, and it uses the same ID as before (which is persisted early in the boot procedure), it tries to contant the cluster and hangs -- because it's getting no responses to its messages.


In order to restart bootstrap of a node which previously failed to bootstrap, you need to clear its work directories so it basically starts as a completely new node. (With new host ID, no data and so on.)


Now I see that we did not document this banning behavior for failed bootstraps, I'll open an issue.

**Comment by kbr-scylla** [comment]
Opened documentation issue: https://github.com/scylladb/scylladb/issues/18850

Other than that, the SCT nemeses will have to be adjusted to account for node ban. @yarongilor @fruch 

We similarly adjusted dtests, see for example: https://github.com/scylladb/scylladb/issues/17385, https://github.com/scylladb/scylla-dtest/pull/3959

**Comment by kbr-scylla** [comment]
> Other than that, the SCT nemeses will have to be adjusted to account for node ban. @yarongilor @fruch

Not sure who to assign it to. @kostja ?

**Comment by kbr-scylla** [comment]
Also the title of the report is confusing:

> A new node init takes more than an hour to complete

It suggests that **it completed but took longer than an hour**

but it actually **never completed**.

I'll adjust the title.

**Comment by kostja** [comment]
@kbr-scylla @roydahan should provide @temichus with the list of sct files @roydahan wants @temichus team to own. once we have this list and assuming this test ends up on @temichus plate, it's him.

**Comment by yarongilor** [comment]
> Also the title of the report is confusing:
> 
> > A new node init takes more than an hour to complete
> 
> It suggests that **it completed but took longer than an hour**
> 
> but it actually **never completed**.
> 
> I'll adjust the title.

this might indicate a report issue of SCT to check:
```
> source=SoftTimeout message=operation 'NEW_NODE' took 3625.333893299103s and soft-timeout was set to 3600s

```

**Comment by roydahan** [comment]
@aleksbykov and @temichus should know exactly which nemesis to adjust and how.

**Comment by aleksbykov** [comment]
It is not a scylla issue. It is problem in scr side. I have a draft pr with the fix for it

**Comment by mykaul** [comment]
> It is not a scylla issue. It is problem in scr side. I have a draft pr with the fix for it

Shall we close this one and continue on the SCT issue?

**Comment by aleksbykov** [comment]
Yes

**Comment by yarongilor** [comment]
> @yarongilor the report did not mention a **very important fact** (which instantaneously leads to explanation why we get this behavior):
> 
> The test started bootstrapping the node, **then interrupted the procedure and restarted the node to try bootstrap again**.
> 
> ```
> 2024-05-21T10:08:42.660+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[6858]:  [shard  0:main] init - Scylla version 5.5.0~dev-0.20240520.a517fcf970ec with build-id 156473840db1bc25a83a123598850e7a1e07f184 starting ...
> 
> ...
> 
> 2024-05-21T10:08:51.645+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7   !NOTICE | sudo[7023]: scyllaadm : PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/systemctl stop scylla-server.service
> 2024-05-21T10:08:51.646+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | sudo[7023]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
> 2024-05-21T10:08:51.779+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | systemd[1]: scylla-housekeeping-daily.timer: Deactivated successfully.
> 2024-05-21T10:08:51.779+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | systemd[1]: Stopped Run Scylla Housekeeping daily mode.
> 2024-05-21T10:08:51.779+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | systemd[1]: scylla-housekeeping-restart.timer: Deactivated successfully.
> 2024-05-21T10:08:51.779+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | systemd[1]: Stopped Run Scylla Housekeeping restart mode.
> 2024-05-21T10:08:51.780+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[6858]:  [shard  0:main] compaction_manager - Asked to stop
> 2024-05-21T10:08:51.780+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[6858]:  [shard  0:main] view_update_generator - Terminating background fiber
> 2024-05-21T10:08:51.780+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | systemd[1]: Stopping Scylla Server...
> 
> ...
> 
> 2024-05-21T10:09:51.543+00:00 longevity-100gb-4h-master-db-node-9d8db95e-7     !INFO | scylla[7133]: Scylla version 5.5.0~dev-0.20240520.a517fcf970ec with build-id 156473840db1bc25a83a123598850e7a1e07f184 starting ...
> ```
> 
> The reason for this behavior is that after a failed bootstrap attempt, **the node is permanently banned from the cluster**, meaning that existing members of the cluster refuse to communicate with it (they drop all messages). This ban is host ID based. So when you restart the node, it tries to bootstrap again, and it uses the same ID as before (which is persisted early in the boot procedure), it tries to contant the cluster and hangs -- because it's getting no responses to its messages.
> 
> In order to restart bootstrap of a node which previously failed to bootstrap, you need to clear its work directories so it basically starts as a completely new node. (With new host ID, no data and so on.)
> 
> Now I see that we did not document this banning behavior for failed bootstraps, I'll open an issue.

@kbr-scylla , that is not accurate :)
If you carefully read the issue description, you'll notice this:
```
So it looks like init process doesn't get to the step of init - starting system distributed keyspace at all. (it did get to it before the initial scylla-service stop/start)
```

**Comment by yarongilor** [comment]
https://github.com/scylladb/scylla-cluster-tests/issues/7448#issuecomment-2132941789
