### ISSUE TITLE
scylla-housekeeping error on Docker, while parsing scylla_release_version  6.0.0-rc0

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#18880]
Scylla 6.0.0-rc0
Running on a with a local Docker compose.
Cloud it be the "rc0" part?

```
scylla-node3    | 2024-05-27 05:36:03,259 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scylla-node3    | 2024-05-27 05:36:03,259 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scylla-node3    | 2024-05-27 05:36:03,259 INFO success: scylla-housekeeping entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scylla-node3    | 2024-05-27 05:36:03,260 INFO success: scylla-node-exporter entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scylla-node3    | Traceback (most recent call last):
scylla-node3    |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 196, in <module>
scylla-node3    |     args.func(args)
scylla-node3    |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 122, in check_version
scylla-node3    |     current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
scylla-node3    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
scylla-node3    |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 80, in get_api
scylla-node3    |     return get_json_from_url("http://" + api_address + path)
scylla-node3    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
scylla-node3    |   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 75, in get_json_from_url
scylla-node3    |     raise RuntimeError(f'Failed to get "{path}" due to the following error: {retval}')
scylla-node3    | RuntimeError: Failed to get "http://localhost:10000/storage_service/scylla_release_version" due to the following error: HTTP Error 404: Not Found
```

**Comment by tzach** [comment]
Closing. I suspect the issue was related to Docker volumes, not Scylla.
