### ISSUE TITLE
During 'disrupt_create_index' nemesis drop index fails with error "code=2200 [Invalid query] message="Index 'test_v_nemesis' could not be found in any of the tables of keyspace 'scylla_bench'"

### ISSUE THREAD

**Issue by dimakr** [scylladb/scylladb#19028]
## Packages

Scylla version: `6.1.0~dev-20240523.9adf74ae6c7a` with build-id `0e61ad9ecb33913aa59e185d2453859c9ed0fd1a`
Kernel Version: `5.15.0-1062-aws`

## Issue description

- [ ] This issue is a regression.
- [X] It is unknown if this issue is a regression.

During `disrupt_create_index` nemesis index "test_v_nemesis" is created, but then is not found on an attempt to drop it.

The Nemesis scenario is:
- create an index on a random column of a table with the most number of partitions
- wait until it gets build
- verify it can be used in a query
- drop the index

Drop index operation on node-3 failed. From SCT logs dropping index started at 08:38:57:
```
< t:2024-05-25 08:38:57,126 f:common.py       l:1833 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="DROP INDEX scylla_bench.test_v_nemesis", consistency=Not Set>' ...                     │
< t:2024-05-25 08:38:57,126 f:common.py       l:1841 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="DROP INDEX scylla_bench.test_v_nemesis", consistency=Not Set>' ...    
```
and failed a minute later with the error:
```
< t:2024-05-25 08:39:57,145 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <bound method Nemesis.disrupt_create_index of <sdcm.nemesis.Sisyphus
Monkey object at 0x7f16092204f0>> < t:2024-05-25 08:39:57,145 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: Unhandled exception in method <bound method Nemesis.disrupt_crea
te_index of <sdcm.nemesis.SisyphusMonkey object at 0x7f16092204f0>>
< t:2024-05-25 08:39:57,145 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > Traceback (most recent call last):
< t:2024-05-25 08:39:57,145 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5117, in wrapper
< t:2024-05-25 08:39:57,145 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >     result = method(*args[1:], **kwargs)
< t:2024-05-25 08:39:57,145 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4784, in disrupt_create_index
< t:2024-05-25 08:39:57,145 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >     drop_index(session, ks, index_name)
< t:2024-05-25 08:39:57,145 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/nemesis_utils/indexes.py", line 116, in drop_index
< t:2024-05-25 08:39:57,145 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >     session.execute(SimpleStatement(f'DROP INDEX {ks}.{index_name}'), timeout=300)
< t:2024-05-25 08:39:57,145 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/common.py", line 1834, in execute_verbose
< t:2024-05-25 08:39:57,145 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >     return execute_orig(*args, **kwargs)
< t:2024-05-25 08:39:57,145 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >   File "cassandra/cluster.py", line 2699, in cassandra.cluster.Session.execute
< t:2024-05-25 08:39:57,145 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR >   File "cassandra/cluster.py", line 5018, in cassandra.cluster.ResponseFuture.result
< t:2024-05-25 08:39:57,145 f:nemesis.py      l:5141 c:sdcm.nemesis         p:ERROR > cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Index 'test_v_nemesis' could not be found in any of the tables of keyspace 'scylla_bench'"
```

When the drop index was started, on nodes 2, 3 and 5 the following errors were logged (below is the log portion from node3):
```
2024-05-25T08:38:57.592+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3     !INFO | scylla[6831]:  [shard 0:strm] database - Dropping scylla_bench.test_v_nemesis_index with auto-snapshot
2024-05-25T08:38:57.592+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3  !WARNING | scylla[6831]:  [shard 2:stmt] storage_proxy - Failed to apply mutation from 10.4.10.167#2: data_dictionary::no_such_column_family (Can't find a column family with UUID 64703d20-1a5e-11ef-84b9-3b5466e86e7c)
2024-05-25T08:38:57.592+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3  !WARNING | scylla[6831]:  [shard 6:stmt] storage_proxy - Failed to apply mutation from 10.4.10.167#6: data_dictionary::no_such_column_family (Can't find a column family with UUID 64703d20-1a5e-11ef-84b9-3b5466e86e7c)
2024-05-25T08:38:57.592+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3  !WARNING | scylla[6831]:  [shard 2:stmt] storage_proxy - Failed to apply mutation from 10.4.10.167#2: data_dictionary::no_such_column_family (Can't find a column family with UUID 64703d20-1a5e-11ef-84b9-3b5466e86e7c)
2024-05-25T08:38:57.592+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3  !WARNING | scylla[6831]:  [shard 6:stmt] storage_proxy - Failed to apply mutation from 10.4.10.167#6: data_dictionary::no_such_column_family (Can't find a column family with UUID 64703d20-1a5e-11ef-84b9-3b5466e86e7c)
2024-05-25T08:38:57.592+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3  !WARNING | scylla[6831]:  [shard 3:stmt] storage_proxy - Failed to apply mutation from 10.4.10.167#3: data_dictionary::no_such_column_family (Can't find a column family with UUID 64703d20-1a5e-11ef-84b9-3b5466e86e7c)
2024-05-25T08:38:57.592+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3     !INFO | scylla[6831]:  [shard 0:strm] database - Truncating scylla_bench.test_v_nemesis_index with auto-snapshot
2024-05-25T08:38:57.593+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3  !WARNING | scylla[6831]:  [shard 5:stmt] storage_proxy - Failed to apply mutation from 10.4.10.167#5: data_dictionary::no_such_column_family (Can't find a column family with UUID 64703d20-1a5e-11ef-84b9-3b5466e86e7c)
2024-05-25T08:38:57.593+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3  !WARNING | scylla[6831]:  [shard 0:stmt] storage_proxy - Failed to apply mutation from 10.4.10.167#0: data_dictionary::no_such_column_family (Can't find a column family with UUID 64703d20-1a5e-11ef-84b9-3b5466e86e7c)
2024-05-25T08:38:57.593+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3  !WARNING | scylla[6831]:  [shard 4:stmt] storage_proxy - Failed to apply mutation from 10.4.10.167#4: data_dictionary::no_such_column_family (Can't find a column family with UUID 64703d20-1a5e-11ef-84b9-3b5466e86e7c)
2024-05-25T08:38:57.593+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3     !INFO | scylla[6831]:  [shard 6:strm] compaction_manager - Stopping 2 tasks for 2 ongoing compactions for table scylla_bench.test_v_nemesis_index compaction_group=0 due to user-triggered operation
2024-05-25T08:38:57.593+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3      !ERR | scylla[6831]:  [shard 6:stmt] view - Error applying view update to 10.4.8.131 (view: scylla_bench.test_v_nemesis_index, base token: 3426876154814388849, view token: 720195361136906225): data_dictionary::no_such_column_family (Can't find a column family with UUID 64703d20-1a5e-11ef-84b9-3b5466e86e7c)
2024-05-25T08:38:57.593+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3      !ERR | scylla[6831]:  [shard 3:stmt] view - Error applying view update to 10.4.8.131 (view: scylla_bench.test_v_nemesis_index, base token: 7572914961325832459, view token: 720195361136906225): data_dictionary::no_such_column_family (Can't find a column family with UUID 64703d20-1a5e-11ef-84b9-3b5466e86e7c)
2024-05-25T08:38:57.593+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3  !WARNING | scylla[6831]:  [shard 2:stmt] storage_proxy - Failed to apply mutation from 10.4.10.167#2: data_dictionary::no_such_column_family (Can't find a column family with UUID 64703d20-1a5e-11ef-84b9-3b5466e86e7c)
2024-05-25T08:38:57.593+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3      !ERR | scylla[6831]:  [shard 3:stmt] view - Error applying view update to 10.4.8.131 (view: scylla_bench.test_v_nemesis_index, base token: 3942890367139928216, view token: 720195361136906225): data_dictionary::no_such_column_family (Can't find a column family with UUID 64703d20-1a5e-11ef-84b9-3b5466e86e7c)
...
2024-05-25T08:38:57.596+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3      !ERR | scylla[6831]:  [shard 5:stmt] view - Error applying view update to 10.4.8.131 (view: scylla_bench.test_v_nemesis_index, base token: 7101469940238776247, view token: 720195361136906225): data_dictionary::no_such_column_family (Can't find a column family with UUID 64703d20-1a5e-11ef-84b9-3b5466e86e7c)
2024-05-25T08:38:57.596+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3  !WARNING | scylla[6831]:  [shard 3:stmt] storage_proxy - Failed to apply mutation from 10.4.10.167#3: data_dictionary::no_such_column_family (Can't find a column family with UUID 64703d20-1a5e-11ef-84b9-3b5466e86e7c)
2024-05-25T08:38:57.596+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3      !ERR | scylla[6831]:  [shard 5:stmt] view - Error applying view update to 10.4.8.131 (view: scylla_bench.test_v_nemesis_index, base token: 3205428870608983571, view token: 720195361136906225): data_dictionary::no_such_column_family (Can't find a column family with UUID 64703d20-1a5e-11ef-84b9-3b5466e86e7c)
messages.log|2024-05-25T08:38:57.596+00:00 longevity-twcs-48h-master-db-node-b9be39c9-3     !INFO | scylla[6831]:  [shard 6:comp] compaction - [Compact scylla_bench.test_v_nemesis_index e0db18e0-1a6c-11ef-9b86-22d15197903d] Compacting of 20 sstables interrupted due to: sstables::compaction_stopped_exception (Compaction for scylla_bench/test_v_nemesis_index was stopped due to: user-triggered operation), at 0x63a898e 0x63a8fa0 0x63a9288 0x263754c 0x627fed6
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

2 out of last 5 runs of the longevity test had this issue.

## Installation details

Cluster size: 4 nodes (i3en.2xlarge)

Scylla Nodes used in this run:
- longevity-twcs-48h-master-db-node-b9be39c9-7 (3.248.191.20 | 10.4.11.187) (shards: 7)
- longevity-twcs-48h-master-db-node-b9be39c9-6 (3.250.159.127 | 10.4.11.180) (shards: 7)
- longevity-twcs-48h-master-db-node-b9be39c9-5 (18.201.86.135 | 10.4.9.50) (shards: 7)
- longevity-twcs-48h-master-db-node-b9be39c9-4 (52.31.201.188 | 10.4.11.59) (shards: -1)
- longevity-twcs-48h-master-db-node-b9be39c9-3 (34.241.192.139 | 10.4.8.131) (shards: 7)
- longevity-twcs-48h-master-db-node-b9be39c9-2 (3.253.3.167 | 10.4.8.96) (shards: 7)
- longevity-twcs-48h-master-db-node-b9be39c9-1 (34.242.128.24 | 10.4.10.167) (shards: 7)

OS / Image: `ami-0927fb8b03edc430c` (aws: undefined_region)

Test: `longevity-twcs-48h-test`
Test id: `b9be39c9-0c24-410f-aadc-d981a784dfd4`
Test name: `scylla-master/tier1/longevity-twcs-48h-test`
Test config file(s):

- [longevity-twcs-48h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/fe35c3ad1f54bd1df2de8f082c388f7851d7fdfc/test-cases/longevity/longevity-twcs-48h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor b9be39c9-0c24-410f-aadc-d981a784dfd4`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=b9be39c9-0c24-410f-aadc-d981a784dfd4)
- Show all stored logs command: `$ hydra investigate show-logs b9be39c9-0c24-410f-aadc-d981a784dfd4`

## Logs:
- **db-cluster-b9be39c9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b9be39c9-0c24-410f-aadc-d981a784dfd4/20240526_033045/db-cluster-b9be39c9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b9be39c9-0c24-410f-aadc-d981a784dfd4/20240526_033045/db-cluster-b9be39c9.tar.gz)
- **sct-runner-events-b9be39c9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b9be39c9-0c24-410f-aadc-d981a784dfd4/20240526_033045/sct-runner-events-b9be39c9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b9be39c9-0c24-410f-aadc-d981a784dfd4/20240526_033045/sct-runner-events-b9be39c9.tar.gz)
- **sct-b9be39c9.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b9be39c9-0c24-410f-aadc-d981a784dfd4/20240526_033045/sct-b9be39c9.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b9be39c9-0c24-410f-aadc-d981a784dfd4/20240526_033045/sct-b9be39c9.log.tar.gz)
- **loader-set-b9be39c9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b9be39c9-0c24-410f-aadc-d981a784dfd4/20240526_033045/loader-set-b9be39c9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b9be39c9-0c24-410f-aadc-d981a784dfd4/20240526_033045/loader-set-b9be39c9.tar.gz)
- **monitor-set-b9be39c9.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/b9be39c9-0c24-410f-aadc-d981a784dfd4/20240526_033045/monitor-set-b9be39c9.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b9be39c9-0c24-410f-aadc-d981a784dfd4/20240526_033045/monitor-set-b9be39c9.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-twcs-48h-test/16/)
[Argus](https://argus.scylladb.com/test/ecd497c0-82d6-4269-b053-f5c2157e04ae/runs?additionalRuns[]=b9be39c9-0c24-410f-aadc-d981a784dfd4)
</details>

**Comment by piodul** [comment]
It looks like it takes around 60s for the session to execute the statement and get the error:

```
< t:2024-05-25 08:38:57,126 f:common.py       l:1841 c:utils                p:DEBUG > Executing CQL '<SimpleStatement query="DROP INDEX scylla_bench.test_v_nemesis", consistency=Not Set>' ...    
...
< t:2024-05-25 08:39:57,133 f:libevreactor.py l:370  c:cassandra.cluster    p:WARNING > Host 10.4.8.131:9042 error: Server error.
```

Curiously, SCT sets a 60s timeout for the session used to send the drop statement:

https://github.com/scylladb/scylla-cluster-tests/blob/b801f5a73ddd5277b98db2da1a45307bb6710daa/sdcm/cluster.py#L3485

This suggests to me that it might be a python driver issue. @Lorak-mmk told me that it might be https://github.com/scylladb/python-driver/issues/296 that we didn't manage to reproduce back then.

I'll continue looking at the python driver code tomorrow.

**Comment by mykaul** [comment]
> ## Impact
> _Describe the impact this issue causes to the user._

What's the impact here?

**Comment by mykaul** [comment]
@piodul - any luck with the Python driver?

**Comment by dani-tweig** [comment]
Is this issue still relevant?
Can we change the milestone to Backlog?

**Comment by dani-tweig** [comment]
@piodul , can we move this to the backlog or close it?

**Comment by mykaul** [comment]
Closing for the time being.
