### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'thrift'

### ISSUE THREAD

**Issue by PrabhuUdurg** [scylladb/scylladb#19298]
While trying to build a scylla following this guide https://github.com/scylladb/scylladb/blob/master/HACKING.md, after executing
 `./configure.py` it gives me following error:

 Linker gold found, but the compilation attempt failed, defaulting to default system linker
Traceback (most recent call last):
  File "/home/elmira/Documents/Projects/scylla/./configure.py", line 1852, in <module>
    if thrift_uses_boost_share_ptr():
  File "/home/elmira/Documents/Projects/scylla/./configure.py", line 375, in thrift_uses_boost_share_ptr
    proc_res = subprocess.run(["thrift", "-version"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'thrift'

Is it a bug or just some problems with my system?

**Comment by tchaikov** [comment]
@PrabhuUdurg please follow the instructions at https://github.com/scylladb/scylladb/blob/master/HACKING.md#dependencies , and run `install-dependencies.sh` on your system. 

to be more specific, not sure what distro you are using, but you might need to install `thrift-compiler` or `thrift-devel` or whatever package which provides `thrift` for you.
