### ISSUE TITLE
"Could not read configuration file" causes SIGSEGV on DPDK mode

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylladb#1947]
posix mode able to exit successfully, but DPDK mode causes SIGSEGV:
```
Checking link status 
Created DPDK device
...............................................done
Port 0 Link Up - speed 10000 Mbps - full-duplex
DHCP sending discover
DHCP Got offer for 172.16.0.2
DHCP sending request for 172.16.0.2
DHCP Got ack on request
DHCP  ip: 172.16.0.2
DHCP  nm: 255.255.255.0
DHCP  gw: 0.0.0.0
Scylla version 666.development-20161221.c05385c starting ...
ERROR 2016-12-21 01:57:13,552 [shard 0] init - Could not read configuration file conf/scylla.yaml: std::invalid_argument (Could not open file at conf/scylla.yaml. Make sure it exists)
ERROR 2016-12-21 01:57:13,552 [shard 0] seastar - Exiting on unhandled exception: std::invalid_argument (Could not open file at conf/scylla.yaml. Make sure it exists)
Segmentation fault (core dumped)
```

Seems like net::ipv4_udp::registration::unregister() triggers this:
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 1 --default-log-level debug -'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  std::__detail::_Mod_range_hashing::operator() (this=<optimized out>, 
    __den=<optimized out>, __num=<optimized out>)
    at /usr/include/c++/5/bits/hashtable_policy.h:446
446	    { return __num % __den; }
[Current thread is 1 (Thread 0x7fa28287b0c0 (LWP 6228))]
(gdb) bt
#0  std::__detail::_Mod_range_hashing::operator() (this=<optimized out>, 
    __den=<optimized out>, __num=<optimized out>)
    at /usr/include/c++/5/bits/hashtable_policy.h:446
#1  std::__detail::_Hash_code_base<unsigned short, std::pair<unsigned short const, lw_shared_ptr<net::udp_channel_state> >, std::__detail::_Select1st, std::hash<unsigned short>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, false>::_M_bucket_index (this=<optimized out>, __n=<optimized out>, 
    __p=<optimized out>) at /usr/include/c++/5/bits/hashtable_policy.h:1180
#2  std::_Hashtable<unsigned short, std::pair<unsigned short const, lw_shared_ptr<net::udp_channel_state> >, std::allocator<std::pair<unsigned short const, lw_shared_ptr<net::udp_channel_state> > >, std::__detail::_Select1st, std::equal_to<unsigned short>, std::hash<unsigned short>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::_M_bucket_index (
    this=<optimized out>, __n=<optimized out>)
    at /usr/include/c++/5/bits/hashtable.h:617
#3  std::_Hashtable<unsigned short, std::pair<unsigned short const, lw_shared_ptr<net::udp_channel_state> >, std::allocator<std::pair<unsigned short const, lw_shared_ptr<net::udp_channel_state> > >, std::__detail::_Select1st, std::equal_to<unsigned short>, std::hash<unsigned short>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::erase (__it=..., 
    this=0x600000722ed0) at /usr/include/c++/5/bits/hashtable.h:1741
#4  std::_Hashtable<unsigned short, std::pair<unsigned short const, lw_shared_ptr<net::udp_channel_state> >, std::allocator<std::pair<unsigned short const, lw_shared_ptr<net::udp_channel_state> > >, std::__detail::_Select1st, std::equal_to<unsigned short>, std::hash<unsigned short>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::erase (__it=..., 
    this=0x600000722ed0) at /usr/include/c++/5/bits/hashtable.h:745
#5  std::unordered_map<unsigned short, lw_shared_ptr<net::udp_channel_state>, std::hash<unsigned short>, std::equal_to<unsigned short>, std::allocator<std::pair<unsigned short const, lw_shared_ptr<net::udp_channel_state> > > >::erase (
    __position=..., this=0x600000722ed0)
    at /usr/include/c++/5/bits/unordered_map.h:523
#6  net::ipv4_udp::registration::unregister (this=0x6000001a8370)
    at net/ip.hh:269
#7  net::ipv4_udp_impl::native_channel::close (this=0x6000001a8360)
    at net/udp.cc:111
#8  0x000000000063acfd in net::ipv4_udp_impl::native_channel::~native_channel (
    this=0x6000001a8360, __in_chrg=<optimized out>) at net/udp.cc:87
#9  net::ipv4_udp_impl::native_channel::~native_channel (this=0x6000001a8360, 
    __in_chrg=<optimized out>) at net/udp.cc:88
#10 0x00007fa27e3a75ff in __GI___call_tls_dtors ()
    at cxa_thread_atexit_impl.c:155
#11 0x00007fa27e3a6f27 in __run_exit_handlers (status=1, 
    listp=0x7fa27e7305f8 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true) at exit.c:40
#12 0x00007fa27e3a7045 in __GI_exit (status=<optimized out>) at exit.c:104
#13 0x00007fa27e38d837 in __libc_start_main (
    main=0x474e80 <main(int, char**)>, argc=16, argv=0x7ffe216bede8, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7ffe216bedd8) at ../csu/libc-start.c:325
#14 0x00000000004e2349 in _start ()
```

**Comment by syuu1228** [comment]
It also happens on " NOFILE rlimit too low".
