### ISSUE TITLE
artifact test failed on `coredumpctl: not found`

### ISSUE THREAD

**Issue by Annamikhlin** [scylladb/scylladb#19643]
artifact test - https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ubuntu2204-test/576/
failed with error:
```
01:42:41  ======================================================================
01:42:41  ERROR: test_scylla_service (artifacts_test.ArtifactsTest)
01:42:41  ----------------------------------------------------------------------
01:42:41  sdcm.sct_events.system.TestResultEvent: ================================= TEST RESULTS =================================
01:42:41  
01:42:41  ----- LAST ERROR EVENT -------------------------------------------------------
01:42:41  2024-07-04 22:42:14.352: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=90f373cb-0106-491f-be0a-ceee3a5c70af, source=ArtifactsTest.SetUp()
01:42:41  exception=[Node artifacts-ubuntu2204-jenkins-db-node-35ca3602-0-1 [34.139.7.251 | 10.142.0.98]] NodeSetupFailed: Encountered a bad command exit code!
01:42:41  Command: 'sudo /usr/lib/scylla/scylla_setup --nic ens5 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
01:42:41  Exit code: 1
01:42:41  Stdout:
01:42:41  Creating XFS volume for scylla using 1 disk(s): /dev/nvme0n1
01:42:41  Command 'coredumpctl --version' returned non-zero exit status: 127
01:42:41  ----------  stdout  ----------
01:42:41  ------------------------------
01:42:41  ----------  stderr  ----------
01:42:41  /bin/sh: 1: coredumpctl: not found
01:42:41  ------------------------------
01:42:41  Debug log created: /var/tmp/scylla/scylla_coredump_setup-9231-debug.log
01:42:41  Unable to retrieve version information
01:42:41  coredump setup failed.
01:42:41  Stderr:
01:42:41  parser.add_argument('--compress', action='store_true', default=has_zstd(),
01:42:41  ^^^^^^^^^^
01:42:41  File "/opt/scylladb/scripts/libexec/scylla_coredump_setup", line 22, in has_zstd
01:42:41  coredump_version = out('coredumpctl --version').split('\n')
01:42:41  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:42:41  File "/opt/scylladb/scripts/scylla_util.py", line 53, in out
01:42:41  res.check_returncode()
01:42:41  File "/opt/scylladb/python3/lib64/python3.12/subprocess.py", line 502, in check_returncode
01:42:41  raise CalledProcessError(self.returncode, self.args, self.stdout,
01:42:41  subprocess.CalledProcessError: Command 'coredumpctl --version' returned non-zero exit status 127.
01:42:41  Traceback (most recent call last):
01:42:41  File "/tmp/workspace/scylla-master/artifacts/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/cluster.py", line 3835, in node_setup
01:42:41  cl_inst.node_setup(_node, **setup_kwargs)
01:42:41  File "/tmp/workspace/scylla-master/artifacts/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/cluster.py", line 4664, in node_setup
01:42:41  self._scylla_post_install(node, install_scylla, nic_devname)
01:42:41  File "/tmp/workspace/scylla-master/artifacts/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/cluster.py", line 4792, in _scylla_post_install
01:42:41  node.scylla_setup(disks, devname)
01:42:41  File "/tmp/workspace/scylla-master/artifacts/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 119, in inner
01:42:41  res = func(*args, **kwargs)
01:42:41  File "/tmp/workspace/scylla-master/artifacts/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/cluster.py", line 2221, in scylla_setup
01:42:41  self.remoter.run('sudo /usr/lib/scylla/scylla_setup --nic {} --disks {} --setup-nic-and-disks {}'
01:42:41  File "/tmp/workspace/scylla-master/artifacts/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
01:42:41  result = _run()
01:42:41  File "/tmp/workspace/scylla-master/artifacts/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
01:42:41  return func(*args, **kwargs)
01:42:41  File "/tmp/workspace/scylla-master/artifacts/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
01:42:41  return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
01:42:41  File "/tmp/workspace/scylla-master/artifacts/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
01:42:41  result = connection.run(**command_kwargs)
01:42:41  File "/tmp/workspace/scylla-master/artifacts/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
01:42:41  return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
01:42:41  File "/tmp/workspace/scylla-master/artifacts/artifacts-ubuntu2204-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
01:42:41  raise UnexpectedExit(result)
01:42:41  sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
01:42:41  Command: 'sudo /usr/lib/scylla/scylla_setup --nic ens5 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
01:42:41  Exit code: 1
01:42:41  Stdout:
01:42:41  Creating XFS volume for scylla using 1 disk(s): /dev/nvme0n1
01:42:41  Command 'coredumpctl --version' returned non-zero exit status: 127
01:42:41  ----------  stdout  ----------
01:42:41  ------------------------------
01:42:41  ----------  stderr  ----------
01:42:41  /bin/sh: 1: coredumpctl: not found
01:42:41  ------------------------------
01:42:41  Debug log created: /var/tmp/scylla/scylla_coredump_setup-9231-debug.log
01:42:41  Unable to retrieve version information
01:42:41  coredump setup failed.
01:42:41  Stderr:
01:42:41  parser.add_argument('--compress', action='store_true', default=has_zstd(),
01:42:41  ^^^^^^^^^^
01:42:41  File "/opt/scylladb/scripts/libexec/scylla_coredump_setup", line 22, in has_zstd
01:42:41  coredump_version = out('coredumpctl --version').split('\n')
01:42:41  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
01:42:41  File "/opt/scylladb/scripts/scylla_util.py", line 53, in out
01:42:41  res.check_returncode()
01:42:41  File "/opt/scylladb/python3/lib64/python3.12/subprocess.py", line 502, in check_returncode
01:42:41  raise CalledProcessError(self.returncode, self.args, self.stdout,
01:42:41  subprocess.CalledProcessError: Command 'coredumpctl --version' returned non-zero exit status 127.
01:42:41  ----- LAST NORMAL EVENT ------------------------------------------------------
01:42:41  2024-07-04 22:42:14.385: (InfoEvent Severity.NORMAL) period_type=not-set event_id=17a24dd4-6e7d-4416-99a0-f3c43250894c: message=TEST_END
01:42:41  ================================================================================
```
seems that need to add `coredumpctl` to scylla dependencies

**Comment by fruch** [comment]
@syuu1228 the code is using coredumpctl, before the call to `pkg_install('systemd-coredump')`

so
- move the installation part to before parsing  the command line
or 
- check the option available after the installation, and default the argument to None, so you'll know when it's was set by a user or not
