### ISSUE TITLE
test.py looks for build/{mode}/scylla even when not needed

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#19726]
HEAD: 53a6ec05ed311dfbdf04903e3bd5321c9261de59

```console
$ ./test.py --mode release logalloc_test::test_background_reclaim
Traceback (most recent call last):
  File "/home/avi/scylla/./test.py", line 2006, in workaround_python26789
    code = await main()
           ^^^^^^^^^^^^
  File "/home/avi/scylla/./test.py", line 1708, in main
    await find_tests(options)
  File "/home/avi/scylla/./test.py", line 1443, in find_tests
    suite = TestSuite.opt_create(f, options, mode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avi/scylla/./test.py", line 214, in opt_create
    suite = SpecificTestSuite(path, cfg, options, mode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avi/scylla/./test.py", line 409, in __init__
    self.scylla_exe = path_to(self.mode, "scylla")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avi/scylla/./test.py", line 97, in path_to
    raise FileNotFoundError(f"{exe_path} does not exist.")
FileNotFoundError: build/release/scylla does not exist.
[avi@avi scylla (master)]$ ./test.py --mode release logalloc_test
Traceback (most recent call last):
  File "/home/avi/scylla/./test.py", line 2006, in workaround_python26789
    code = await main()
           ^^^^^^^^^^^^
  File "/home/avi/scylla/./test.py", line 1708, in main
    await find_tests(options)
  File "/home/avi/scylla/./test.py", line 1443, in find_tests
    suite = TestSuite.opt_create(f, options, mode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avi/scylla/./test.py", line 214, in opt_create
    suite = SpecificTestSuite(path, cfg, options, mode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avi/scylla/./test.py", line 409, in __init__
    self.scylla_exe = path_to(self.mode, "scylla")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/avi/scylla/./test.py", line 97, in path_to
    raise FileNotFoundError(f"{exe_path} does not exist.")
FileNotFoundError: build/release/scylla does not exist.
```

Why is test.py looking for build/release/scylla? I'm not running a test that needs it.

**Comment by nyh** [comment]
The PythonTestSuite sets up scylla_exe and other stuff in its constructor. But this can be done lazily - we could only calculate scylla_exe et al. in the first time it's needed - when test.py really intends to run one of the Python tests and not when it just wants to list the tests.

**Comment by xtrey** [comment]
The path to the scylla binary calculated on when we are creating the test object. There are no any marks about who needs binary and who doesn't. So it will always check the binary and fail if it's absent.

**Comment by tchaikov** [comment]
it should have been fixed by #22224 . please reopen it if we still suffer from this issue.
