### ISSUE TITLE
[offline-installer][OEL8.1] cqlsh fail to execute

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#19775]
## Packages

Scylla version: `6.1.0~dev-20240715.144794a95216` with build-id `8097cdff1a5e544948c4b568b1b335069883b7b3`

Kernel Version: `4.18.0-147.0.3.el8_1.x86_64`

## Issue description

- [x] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

since we repackaged cqlsh per arch, we are running into this failure in OEL8.1:

```
2024-07-15 22:52:24.285: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=f4795550-880a-478a-a7cf-cc9fa57492d4, source=ArtifactsTest.test_scylla_service (artifacts_test.ArtifactsTest) [check cqlsh installation]() message=Traceback (most recent call last):
File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/artifacts_test.py", line 352, in test_scylla_service
self.check_cqlsh()
File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/artifacts_test.py", line 142, in check_cqlsh
output = self.node.run_cqlsh("desc keyspaces")
File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/cluster.py", line 2858, in run_cqlsh
cqlsh_out = self.remoter.run(cmd, timeout=timeout + 120,  # we give 30 seconds to cqlsh timeout mechanism to work
File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in run
result = _run()
File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
return func(*args, **kwargs)
File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _run_execute
result = connection.run(**command_kwargs)
File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/tmp/jenkins/workspace/scylla-master/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 655, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: '/usr/bin/cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "desc keyspaces" 10.4.7.115'
Exit code: 1
Stdout:
Stderr:
File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 674, in exec_module
File "<frozen importlib._bootstrap_external>", line 781, in get_code
File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/opt/scylladb/share/cassandra/bin/cqlsh.py", line 2
[[ -z "$LD_PRELOAD" ]] || { echo "$0: not compatible with LD_PRELOAD" >&2; exit 110; }
^
SyntaxError: invalid syntax
```

## Impact

user of OEL using offline install can't run cqlsh

## How frequently does it reproduce?

100%

## Installation details

Cluster size: 1 nodes (i3.large)

Scylla Nodes used in this run:
- artifacts-oel81-jenkins-db-node-a354e18d-1 (54.195.1.33 | 10.4.7.115) (shards: 2)

OS / Image: `ami-0e883e67243efea62` (aws: undefined_region)

Test: `artifacts-oel81-test`
Test id: `a354e18d-375a-47c7-a413-7af189e8885f`
Test name: `scylla-master/artifacts-offline-install/artifacts-oel81-test`
Test config file(s):

- [oel81.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/71a7266f609a30a8717525dd245d037bb4959a90/test-cases/artifacts/oel81.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor a354e18d-375a-47c7-a413-7af189e8885f`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a354e18d-375a-47c7-a413-7af189e8885f)
- Show all stored logs command: `$ hydra investigate show-logs a354e18d-375a-47c7-a413-7af189e8885f`

## Logs:
- **db-cluster-a354e18d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a354e18d-375a-47c7-a413-7af189e8885f/20240715_225240/db-cluster-a354e18d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a354e18d-375a-47c7-a413-7af189e8885f/20240715_225240/db-cluster-a354e18d.tar.gz)
- **sct-runner-events-a354e18d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a354e18d-375a-47c7-a413-7af189e8885f/20240715_225240/sct-runner-events-a354e18d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a354e18d-375a-47c7-a413-7af189e8885f/20240715_225240/sct-runner-events-a354e18d.tar.gz)
- **sct-a354e18d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a354e18d-375a-47c7-a413-7af189e8885f/20240715_225240/sct-a354e18d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a354e18d-375a-47c7-a413-7af189e8885f/20240715_225240/sct-a354e18d.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-oel81-test/427/)
[Argus](https://argus.scylladb.com/test/97e50ea3-21f7-4401-9d35-ee692d5b7274/runs?additionalRuns[]=a354e18d-375a-47c7-a413-7af189e8885f)
</details>

**Comment by yaronkaikov** [comment]
https://github.com/scylladb/scylla-cluster-tests/issues/7995

**Comment by mykaul** [comment]
It makes no sense to continue and test on 8.1. We should test on latest 8.x.

**Comment by syuu1228** [comment]
I'm trying to reproduce the error on same AMI with same unified package, but I did not able to reproduce that when I running cqlsh via SSH.
The error message suggests we are mistakenly running thunk shell script on python3, I initially thought we mistakenly added such bug on recent commit, but I haven't find such behavior when I tested.
Maybe it only occur on the artifact test?

BTW I hit different error while I tested it:
https://github.com/scylladb/scylla-cqlsh/issues/97
and PR for it:
https://github.com/scylladb/scylla-cqlsh/pull/98

**Comment by syuu1228** [comment]
> I'm trying to reproduce the error on same AMI with same unified package, but I did not able to reproduce that when I running cqlsh via SSH.
> The error message suggests we are mistakenly running thunk shell script on python3, I initially thought we mistakenly added such bug on recent commit, but I haven't find such behavior when I tested.
> Maybe it only occur on the artifact test?

Ah, now I able to reproduce it after several tries:

```
$ /usr/bin/cqlsh
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/scylladb/share/cassandra/bin/../libexec/cqlsh/__main__.py", line 3, in <module>
  File "/opt/scylladb/share/cassandra/bin/../libexec/cqlsh/_bootstrap/__init__.py", line 253, in bootstrap
  File "/opt/scylladb/share/cassandra/bin/../libexec/cqlsh/_bootstrap/__init__.py", line 59, in import_string
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/scylladb/share/cassandra/bin/cqlsh.py", line 2
    [[ -z "$LD_PRELOAD" ]] || { echo "$0: not compatible with LD_PRELOAD" >&2; exit 110; }
                      ^
SyntaxError: invalid syntax
```

It seems there is some condition to cause this error, I still cannot reproduce this on my local VMs, and even this will disappear when running cqlsh with sudo in same node.
Maybe this is related with ~/.shiv directory, since current user and root user uses different shiv directory.
And also it describes why I initially did not see this error.

The error message suggests the python code generated by shiv is trying to execute /opt/scylladb/share/cassandra/bin/cqlsh.py in python interpreter, and it failed.
If it always fails it probably means we cannot place thunk shell script on /opt/scylladb/share/cassandra/bin/cqlsh.py, but strange thing is it sometime just works.

Right now I'm comparing between working environment and failed environment, I guess there is difference in ~/.shiv.

**Comment by fruch** [comment]
@syuu1228 on the top there you see the issue start with it using python3.6 `/usr/lib64/python3.6` which it shouldn't

**Comment by fruch** [comment]
something with the relocatable of scylla-python3 is off here...

**Comment by fruch** [comment]
again, what's a packed inside the shiv, is designed to run with python3.12 i.e. with scylla-python3

it won't work without it, since it won't have the python-driver

so that's the root cause

and it's not related to cqlsh.py shabang

**Comment by fruch** [comment]
side note, we probably should pack cqlsh.py any more, since it should be coming with the shiv package.

**Comment by syuu1228** [comment]
> @syuu1228 on the top there you see the issue start with it using python3.6 `/usr/lib64/python3.6` which it shouldn't

Ah, you are right.
When I running cqlsh on strace, I found that permission denied occurs on /opt/scylladb/python3/bin/python3:
```
execve("/opt/scylladb/share/cassandra/bin/../../../python3/bin/python3", ["python3", "/opt/scylladb/share/cassandra/bin/../libexec/cqlsh"], 0x7ffe3a4375f8 /* 30 vars */) = -1 EACCES (Permission denied)
...
execve("/usr/bin/python3", ["python3", "/opt/scylladb/share/cassandra/bin/../libexec/cqlsh"], 0x7ffe3a4375f8 /* 30 vars */) = 0
```
And permission is wrong (likely not just this file):
```
$ ls -l /opt/scylladb/python3/bin/python3.12 
-rwx------. 1 root root 275 Jul 18 07:44 /opt/scylladb/python3/bin/python3.12
```
I think this is same bug as https://github.com/scylladb/scylladb/issues/10752, offline installer is still broken on this AMI which has non-standard umask settings.
(This AMI is not provided by Oracle but provided 3rdparty, and has customized hardened settings on default umask)

**Comment by fruch** [comment]
> > @syuu1228 on the top there you see the issue start with it using python3.6 `/usr/lib64/python3.6` which it shouldn't
> 
> Ah, you are right. When I running cqlsh on strace, I found that permission denied occurs on /opt/scylladb/python3/bin/python3:
> 
> ```
> execve("/opt/scylladb/share/cassandra/bin/../../../python3/bin/python3", ["python3", "/opt/scylladb/share/cassandra/bin/../libexec/cqlsh"], 0x7ffe3a4375f8 /* 30 vars */) = -1 EACCES (Permission denied)
> ...
> execve("/usr/bin/python3", ["python3", "/opt/scylladb/share/cassandra/bin/../libexec/cqlsh"], 0x7ffe3a4375f8 /* 30 vars */) = 0
> ```
> 
> And permission is wrong (likely not just this file):
> 
> ```
> $ ls -l /opt/scylladb/python3/bin/python3.12 
> -rwx------. 1 root root 275 Jul 18 07:44 /opt/scylladb/python3/bin/python3.12
> ```
> 
> I think this is same bug as #10752, offline installer is still broken on this AMI which has non-standard umask settings. (This AMI is not provided by Oracle but provided 3rdparty, and has customized hardened settings on default umask)

so... one more reason to ditch this one.

I don't know why we weren't using official ones.

**Comment by syuu1228** [comment]
> Ah, you are right. When I running cqlsh on strace, I found that permission denied occurs on /opt/scylladb/python3/bin/python3:
> 
> ```
> execve("/opt/scylladb/share/cassandra/bin/../../../python3/bin/python3", ["python3", "/opt/scylladb/share/cassandra/bin/../libexec/cqlsh"], 0x7ffe3a4375f8 /* 30 vars */) = -1 EACCES (Permission denied)
> ...
> execve("/usr/bin/python3", ["python3", "/opt/scylladb/share/cassandra/bin/../libexec/cqlsh"], 0x7ffe3a4375f8 /* 30 vars */) = 0
> ```
> 
> And permission is wrong (likely not just this file):
> 
> ```
> $ ls -l /opt/scylladb/python3/bin/python3.12 
> -rwx------. 1 root root 275 Jul 18 07:44 /opt/scylladb/python3/bin/python3.12
> ```
> 
> I think this is same bug as #10752, offline installer is still broken on this AMI which has non-standard umask settings. (This AMI is not provided by Oracle but provided 3rdparty, and has customized hardened settings on default umask)

Opened PRs to fix the umask issue:
- https://github.com/scylladb/scylladb/pull/19786
- https://github.com/scylladb/scylla-python3/pull/41

**Comment by fruch** [comment]
> > Ah, you are right. When I running cqlsh on strace, I found that permission denied occurs on /opt/scylladb/python3/bin/python3:
> > ```
> > execve("/opt/scylladb/share/cassandra/bin/../../../python3/bin/python3", ["python3", "/opt/scylladb/share/cassandra/bin/../libexec/cqlsh"], 0x7ffe3a4375f8 /* 30 vars */) = -1 EACCES (Permission denied)
> > ...
> > execve("/usr/bin/python3", ["python3", "/opt/scylladb/share/cassandra/bin/../libexec/cqlsh"], 0x7ffe3a4375f8 /* 30 vars */) = 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And permission is wrong (likely not just this file):
> > ```
> > $ ls -l /opt/scylladb/python3/bin/python3.12 
> > -rwx------. 1 root root 275 Jul 18 07:44 /opt/scylladb/python3/bin/python3.12
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think this is same bug as #10752, offline installer is still broken on this AMI which has non-standard umask settings. (This AMI is not provided by Oracle but provided 3rdparty, and has customized hardened settings on default umask)
> 
> Opened PRs to fix the umask issue:
> 
> * [install.sh: fix more incorrect permission on strict umask #19786](https://github.com/scylladb/scylladb/pull/19786)
> * [install.sh: fix incorrect permission on strict umask scylla-python3#41](https://github.com/scylladb/scylla-python3/pull/41)

@yaronkaikov @syuu1228  for those changes, I would recommend running all of the artifacts test, to validate it's not breaking anything else
