### ISSUE TITLE
test.py fails because `boost_to_junit()` cannot find "TestSuite" in the xunit report

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#20161]
```
15:32:14  CPU utilization: 45.9%
15:32:14  Traceback (most recent call last):
15:32:14    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 2078, in workaround_python26789
15:32:14      code = await main()
15:32:14             ^^^^^^^^^^^^
15:32:14    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1805, in main
15:32:14      boost_to_junit(xunit_file, junit_file)
15:32:14    File "/jenkins/workspace/scylla-master/scylla-ci/scylla/./test.py", line 1710, in boost_to_junit
15:32:14      test_suites = boost_root.find('TestSuite').findall('TestSuite')
15:32:14                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15:32:14  AttributeError: 'NoneType' object has no attribute 'findall'
15:32:15  �[0m
```

see 

- https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10921/ 
- https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10917/

**Comment by tchaikov** [comment]
@xtrey hi Andrey, could you please take a look? i spotted two occurrences of this issue today in two different PRs.

**Comment by tchaikov** [comment]
i am adding P1, because this issue failed a PR twice in a single day. see https://github.com/scylladb/scylladb/pull/20159
