### ISSUE TITLE
sct longevity-mv-si-4days-test failure with encryption

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#20510]
https://argus.scylladb.com/test/19e13996-f41e-432f-a706-87ae01d067a0/runs?additionalRuns[]=608c20c6-795b-4951-9641-d4b9cad0c5ec#:~:text=2024%2D09%2D05%2013%3A47%3A32.482%3A%20(AwsKmsEvent,None%2C%20None%2C%20None%2C%20None%2C%20None%2C%20None%2C%20None%5D

2024-09-05 13:47:32.482: (AwsKmsEvent Severity.ERROR) period_type=one-time event_id=40582aae-8d95-4a9f-bcfe-be2f4cb102e9: message=Failed to check the fact of encryption (KMS) for sstables
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4545, in _rotate_kms_key
SstableUtils(db_node=target_node, ks_cf=chosen_ks_cf).check_that_sstables_are_encrypted()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/sstable/sstable_utils.py", line 133, in check_that_sstables_are_encrypted
assert (encryption_results.count(expected_bool_value) / len(encryption_results) >= encryption_success_part), (
AssertionError: Sstables encryption check failed. Success part: '0.79'. Expected bool value: 'True'. Encryption results: [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]

**Comment by kostja** [comment]
https://argus.scylladb.com/test/19e13996-f41e-432f-a706-87ae01d067a0/runs?additionalRuns[]=608c20c6-795b-4951-9641-d4b9cad0c5ec#:~:text=2024%2D09%2D05%2013%3A47%3A32.482%3A%20(AwsKmsEvent,None%2C%20None%2C%20None%2C%20None%2C%20None%2C%20None%2C%20None%5D

**Comment by mykaul** [comment]
@vponomaryov - what is this magic number 0.79? (looking @ https://github.com/scylladb/scylla-cluster-tests/blob/e31af0141e41b973cf6b60af499e321536a1221c/sdcm/utils/sstable/sstable_utils.py#L131 )

**Comment by elcallio** [comment]
If I am reading the logs correctly, the failure is in fact 
```
< t:2024-09-05 07:16:40,750 f:sstable_utils.py l:125  c:SstableUtils         p:WARNING > Unexpected error reading sstable located at '/var/lib/scylla/data/mview/users-87233f706b4e11efaef2ef0f6d299b13/me-3gja_0hja_1qddc2kbt7wl0lmlg3-big-Data.db': DEBUG 2024-09-05 07:16:39,269 [shard 0:main] scylla-sstable - Successfully read scylla.yaml from user provided location of /etc/scylla/scylla.yaml
< t:2024-09-05 07:16:40,750 f:sstable_utils.py l:125  c:SstableUtils         p:WARNING > DEBUG 2024-09-05 07:16:39,269 [shard 0:main] scylla-sstable - Single schema source provided
< t:2024-09-05 07:16:40,750 f:sstable_utils.py l:125  c:SstableUtils         p:WARNING > error processing arguments: could not load schema via schema-tables: std::runtime_error (Failed to find mview.users in schema tables)

```

Caused by using `scylla sstable dump-scylla-metadata` to query metadata for the tables.
