### ISSUE TITLE
[AssertionError: Lists differ: [[1, 0], [0, 0], [0, 2]] != [[1, 0], [1, 3], [0, 0], [0, 2]]] Miscompare after 2 nodes were updated during rolling upgrade

### ISSUE THREAD

**Issue by timtimb0t** [scylladb/scylladb#20727]
## Packages

Base Scylla version: `6.0.3-20240808.a56f7ce21ad4` with build-id `00ad3169bb53c452cf2ab93d97785dc56117ac3e`
Target Scylla version (or git commit hash): `6.1.2-20240915.b60f9ef4c223` with build-id `c713ac9e819492d7560aa3ad461c43cf404c977b`

Kernel Version: `5.15.0-1070-azure`

## Issue description

- Happened after 2/2 nodes were updated and the test initiated written data verification

*Describe your issue in detail and steps it took to produce it.*

- Start rolling update.
- Wait till the second node updated.
- Run **remove_range_slice_test** :
           'name': 'remove_range_slice_test',
            'create_tables': ["""CREATE TABLE remove_range_slice_test (
                        k int PRIMARY KEY,
                        v int
                    )"""],
            'truncates': ["TRUNCATE remove_range_slice_test"],
            'inserts': [f"INSERT INTO remove_range_slice_test (k, v) VALUES ({i}, {i})" for i in
                        range(0, 3)] + [
                "DELETE FROM remove_range_slice_test WHERE k = 1"],
            'queries': ["SELECT * FROM remove_range_slice_test"],
            'results': [[[0, 0], [2, 2]]],
            'min_version': '',
            'max_version': '',
            'skip': ''},

```
[2024-09-15T16:18:19.426Z] < t:2024-09-15 16:18:08,282 f:fill_db_data.py l:3207 c:UpgradeTest          p:INFO  > Ran queries for test "remove_range_slice_test" in 0 seconds
[2024-09-15T16:18:19.426Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > SELECT blog_id, timestamp FROM indexes_composite_test WHERE author = 'bob' < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > SELECT blog_id, timestamp FROM indexes_composite_test WHERE author = 'bob'
[2024-09-15T16:18:19.426Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > Traceback (most recent call last):
[2024-09-15T16:18:19.426Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR >   File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3269, in _run_db_queries
[2024-09-15T16:18:19.426Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR >     self.assertEqual([list(row) for row in res], item['results'][i])
[2024-09-15T16:18:19.426Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR >   File "/usr/local/lib/python3.10/unittest/case.py", line 845, in assertEqual
[2024-09-15T16:18:19.426Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR >     assertion_func(first, second, msg=msg)
[2024-09-15T16:18:19.426Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR >   File "/usr/local/lib/python3.10/unittest/case.py", line 1051, in assertListEqual
[2024-09-15T16:18:19.426Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR >     self.assertSequenceEqual(list1, list2, msg, seq_type=list)
[2024-09-15T16:18:19.426Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR >   File "/usr/local/lib/python3.10/unittest/case.py", line 1033, in assertSequenceEqual
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR >     self.fail(msg)
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR >   File "/usr/local/lib/python3.10/unittest/case.py", line 675, in fail
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR >     raise self.failureException(msg)
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > AssertionError: Lists differ: [[1, 0], [0, 0], [0, 2]] != [[1, 0], [1, 3], [0, 0], [0, 2]]
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > 
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > First differing element 1:
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > [0, 0]
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > [1, 3]
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > 
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > Second list contains 1 additional elements.
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > First extra element 3:
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > [0, 2]
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > 
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > - [[1, 0], [0, 0], [0, 2]]
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > + [[1, 0], [1, 3], [0, 0], [0, 2]]
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,296 f:fill_db_data.py l:3271 c:sdcm.fill_db_data    p:ERROR > ?          ++++++++
[2024-09-15T16:18:19.427Z] < t:2024-09-15 16:18:08,311 f:tester.py       l:2947 c:UpgradeTest          p:INFO  > Post test validators are starting...
```

## How frequently does it reproduce?

Happened just once, after the job was reran the issue disappeared

## Installation details

Cluster size: 4 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-232e8781-eastus-4 (172.210.63.34 | 10.0.0.8) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-232e8781-eastus-3 (172.210.62.253 | 10.0.0.7) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-232e8781-eastus-2 (172.210.62.214 | 10.0.0.6) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-232e8781-eastus-1 (74.235.206.181 | 10.0.0.5) (shards: 7)

OS / Image: `/CommunityGalleries/scylladb-7e8d8a04-23db-487d-87ec-0e175c0615bb/Images/scylla-6.0/Versions/6.0.3` (azure: undefined_region)

Test: `rolling-upgrade-azure-image-test`
Test id: `232e8781-7f7b-42c9-97cd-40b08c1bb6da`
Test name: `scylla-6.1/rolling-upgrade/rolling-upgrade-azure-image-test`
Test method: `upgrade_test.UpgradeTest.test_rolling_upgrade`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/38e2ebe1ad2f7c5e4170261d974c25c875d48d63/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 232e8781-7f7b-42c9-97cd-40b08c1bb6da`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=232e8781-7f7b-42c9-97cd-40b08c1bb6da)
- Show all stored logs command: `$ hydra investigate show-logs 232e8781-7f7b-42c9-97cd-40b08c1bb6da`

## Logs:
*No logs captured during this run.*

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-6.1/job/rolling-upgrade/job/rolling-upgrade-azure-image-test/8/)
[Argus](https://argus.scylladb.com/test/8c27d7ad-12f9-4847-a606-c0e6726a7875/runs?additionalRuns[]=232e8781-7f7b-42c9-97cd-40b08c1bb6da)
</details>

**Comment by mykaul** [comment]
Were tablets enabled in this test?

**Comment by timtimb0t** [comment]
> Were tablets enabled in this test?

There are few mentions:
enable_tablets_on_upgrade: false
enable_tablets: true

**Comment by mykaul** [comment]
I'm looking @ https://argus.scylladb.com/test/8c27d7ad-12f9-4847-a606-c0e6726a7875/runs?additionalRuns%5B%5D=232e8781-7f7b-42c9-97cd-40b08c1bb6da and I don't see any logs?
