### ISSUE TITLE
test.py fails without --no-gather-metrics if run outside of a container.

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylladb#20763]
It fails with:

```
Traceback (most recent call last):
  File "./test.py", line 2113, in workaround_python26789
    code = await main()
           ^^^^^^^^^^^^
  File "./test.py", line 1807, in main
    setup_cgroup(options.gather_metrics)
  File "test/pylib/resource_gather.py", line 192, in setup_cgroup
    directory.mkdir()
  File "/usr/lib64/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/sys/fs/cgroup/user.slice/user-1042.slice/session-2.scope/initial'

```

According to @avikivity  it suppose to work and in fact it works for him. May be my user lacks some permission and that's why it fails, but in this case the error message should provide some hints about how it can be fixed.

**Comment by avikivity** [comment]
My cgroup path: /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-9524ee20-306b-4c54-875b-4556d6924e35.scope. And /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-9524ee20-306b-4c54-875b-4556d6924e35.scope is owned by me and has rw permissions.

**Comment by xtrey** [comment]
When using some desktop environments, they seem to handle this correctly. Some terminals seem to handle it by themselves, but I'm still not sure about that. On my laptop kitty terminal has the correct cgroup and foot terminal does not. The issue with cgroup for local run was raised in [this](https://github.com/scylladb/scylladb/pull/19881#discussion_r1723256042) thread. Moreover, I guess we are guaranteeing the [compatibility](https://github.com/scylladb/scylladb/pull/19942#discussion_r1708721854) with toolchain and are aiming for the best effort to support the local run.

Anyway, from my point of view, there are several solutions here:
1. Switch metrics gathering to off by default. So if someone wants to use metrics gathering, this person should be responsible for configuring a local machine with prerequisites.
2. Switch off metrics completely outside the container, so it will be available only in container where we have some control of how the system is configured.
3. Implement a solution that will try to go through all cgroups trying to find the first one that belongs to the user and use it.
4. Switch gathering metric if something goes wrong

|Solution|Pros|Cons|
|-|-|-|
|Switch metrics gathering to off by default|1.We can switch it when we need it <br>2.Anyone who needs it should have awareness of what can go wrong|1.Jenkins pipeline should be modified|
|Switch off metrics completely outside the container|1.Easy to implement|1.Can be fragile in detection|
|Implement a solution that will try to go through all cgroups trying to find the first one that belongs to the user and use it|1.Should allow using feature with local run without prior configuration|1.Additional logic to find a correct group is necessary <br>2.The cgroup can have some limitation set already <br>3.Need to implement checking the limits and enabled controllers<br>4.For now, this detection doesn't look very reliable|
|Switch gathering metric if something goes wrong|1.Easy to implement|1.If something goes wrong, in most cases a person will find it out only when the run finishes|

**Comment by gleb-cloudius** [comment]
Well, I do not use gnome and its default terminal, so may be this is the reason. @nyh you do AFAIK so I wonder if it works for you. I think it is not very reasonable to force certain windows manager + terminal emulation combo. I would go with the last one + warning at the start of the run that metrics gathering is disabled.

**Comment by nyh** [comment]
> Well, I do not use gnome and its default terminal, so may be this is the reason. @nyh you do AFAIK so I wonder if it works for you.

I never even bothered to check if it works for me (I already avoid test.py when I run suites that don't need it, namely cql-pytest, alternator and Boost tests - so I don't use it often). My point wasn't to complain that it doesn't work for me, but to rather complain about two bad things I see happening:

1. Running a test shouldn't depend on whether you are running Gnome+terminal or twm+xterm (by the way, I do use the latter on my personal machine :-)). As an analogy, imagine that you could only compile Scylla if you use the Emacs editor, or that you could only run Scylla if your clock application is xclock. It's ridiculous.
2. Recently add more and more features to test.py that we want for CI. That's great, but it should NEVER come at the cost of making things more difficult, slower, or harder to understand for devlopers running a single test during their development. This is a point we continue to miss every time (not just in test.py but across the board). 

> I think it is not very reasonable to force certain windows manager + terminal emulation combo.

I agree 100%. It's completely unreasonable. You should be able to run tests even in a text window on a DEC VT100 terminal you stole from some museum.

> I would go with the last one + warning at the start of the run that metrics gathering is disabled.

Why would you want to see that warning every time? I think that's excessive too.

The CI will **use** the metrics. If it's missing, CI will break, and we won't miss it. But if on your non-Gnome terminal you don't want to use these metrics anyway, you won't use them. Reminding you on every invocation that you won't be able to use them even if you want is silly.

If in the future these metrics will have an important function in some cases even in local development - e.g., to speed up running **all** the tests even locally, then definitely - you can print a warning in that case. But when a developer runs a single test or just a few tests (this is what I do in most test.py runs - is your case different?) it's silly to even warn.

**Comment by gleb-cloudius** [comment]
> > Well, I do not use gnome and its default terminal, so may be this is the reason. @nyh you do AFAIK so I wonder if it works for you.
> 
> I never even bothered to check if it works for me (I already avoid test.py when I run suites that don't need it, namely cql-pytest, alternator and Boost tests - so I don't use it often). My point wasn't to complain that it doesn't work for me, but to rather complain about two bad things I see happening:

I agree, but I am just curios why it works for @avikivity and I know you use similar setup.

**Comment by avikivity** [comment]
I use wayland + gnome-shell + gnome-terminal. No X11.

**Comment by andrzej-jackowski-scylladb** [comment]
Yesterday I encountered the same issue with xfce4-terminal on Fedora 40. The workaround mentioned by @xtrey (use of "kitty" terminal) worked.

**Comment by xtrey** [comment]
@andrzej-jackowski-scylladb it's a little bit extreme to give up using your own favorite terminal :) 
There are several workarounds:
1. Create an alias that will use automatically `--no-gather-metrics` like ` cat  "alias testpy='./test.py --no-gather-metrics --cluster-pool-size 4'" >> ~/.bashrc`
2. You can use the command ```systemd-run --user --scope test.py``` to run tests, or create an alias that will use it
3. You can find a cgroup where your user is an owner and put current PID to this group, but this will only work for current session, and you will need to do it every time you open a new terminal. `sudo echo $$ >>  /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/cgroup.procs`
4. You can modify .desktop file for your favorite terminal app to start it automatically with cgroup like this. For that, you need to change 'Exec' parameter in .desktop file like this `Exec=systemd-run --user --scope favorite_terminal_app`

**Comment by nuivall** [comment]
can we just fix test.py to work out of the box? maybe we don't need to run those stats locally at all. all those workarounds are pretty poor for various reasons.

**Comment by xtrey** [comment]
@nuivall you mean something like this https://github.com/scylladb/scylladb/pull/21625?

**Comment by nuivall** [comment]
Yes I think this should be it.

**Comment by avikivity** [comment]
I think a reasonable attempt should be made to make it work out of the box first. If something is optional, we can't build on it.

**Comment by avikivity** [comment]
I propose we fix it so it works on your machine too.

**Comment by gleb-cloudius** [comment]
> I propose we fix it so it works on your machine too.

Do you have a fix? Because nobody here has. Please send the patch if you have one.

**Comment by nuivall** [comment]
I think using python's http util for gathering metrics and constructing sqlite db offline would solve it, some simple csv/json can be created without having docker dependency (btw I fail to understand why it even fails, I used to have docker working fine at least some time ago).

**Comment by gleb-cloudius** [comment]
> I don't understand what http util has to do with it.
> 
> The problem is that test.py is unable to create containers in some environments.
> 
> However, podman is able to create containers in these environments. So test.py is doing something wrong.
> 

As far as I see podman has to ways to create containers: cgroupfs or systemd. The default is systemd.

**Comment by nuivall** [comment]
we don't need containers at all in test.py, otherwise it will become dtest 2.0 with 7 ways to simply debug a test depending on 12 parameters, half optional, half depending on current weather.

**Comment by gleb-cloudius** [comment]
You do not need containers for dtest!

**Comment by avikivity** [comment]
> we don't need containers at all in test.py, otherwise it will become dtest 2.0 with 7 ways to simply debug a test depending on 12 parameters, half optional, half depending on current weather.

Suggest an alternative to containers in test.py.

**Comment by gleb-cloudius** [comment]
> > we don't need containers at all in test.py, otherwise it will become dtest 2.0 with 7 ways to simply debug a test depending on 12 parameters, half optional, half depending on current weather.
> 
> Suggest an alternative to containers in test.py.

Lest not de-rail the conversation. So it looks like podman works because it delegates container creation to systemd Do you propose to do the same in test.py?

**Comment by xtrey** [comment]
podman is a service that already has some configuration done. test.py executed on unknown territory. The closest solution is the point 3 from my [message](https://github.com/scylladb/scylladb/issues/20763#issuecomment-2370750434), but this is not ideal as well.

**Comment by mykaul** [comment]
> podman is a service that already has some configuration done. test.py executed on unknown territory. The closest solution is the point 3 from my [message](https://github.com/scylladb/scylladb/issues/20763#issuecomment-2370750434), but this is not ideal as well.

I'm not sure I see a reason to run on any platform that doesn't support podman.

> 
> > Do you propose to do the same in test.py?
> 
> test.py does not create any containers. The issue is in the incorrect cgroup permissions where test.py is executed. When terminal located in the cgroup where the current user has RW access, everything will work.

That seems like a reasonable requirement.

**Comment by avikivity** [comment]
> > podman is a service that already has some configuration done. test.py executed on unknown territory. The closest solution is the point 3 from my [message](https://github.com/scylladb/scylladb/issues/20763#issuecomment-2370750434), but this is not ideal as well.
> 
> I'm not sure I see a reason to run on any platform that doesn't support podman.


We don't have such platforms.

> 
> > > Do you propose to do the same in test.py?
> > 
> > 
> > test.py does not create any containers. The issue is in the incorrect cgroup permissions where test.py is executed. When terminal located in the cgroup where the current user has RW access, everything will work.
> 
> That seems like a reasonable requirement.

Is is possible to run podman in such a terminal? If so, podman is able to work with those permissions.

**Comment by avikivity** [comment]
> > > we don't need containers at all in test.py, otherwise it will become dtest 2.0 with 7 ways to simply debug a test depending on 12 parameters, half optional, half depending on current weather.
> > 
> > 
> > Suggest an alternative to containers in test.py.
> 
> Lest not de-rail the conversation. So it looks like podman works because it delegates container creation to systemd Do you propose to do the same in test.py?

I think it's reasonable to try it.

**Comment by avikivity** [comment]
One way is to create a top-level container using systemd, and if the created container belongs to us, created nested cgroups directly. This way we make one change - to create the to-level container.

**Comment by gleb-cloudius** [comment]
> > 
> > test.py does not create any containers. The issue is in the incorrect cgroup permissions where test.py is executed. When terminal located in the cgroup where the current user has RW access, everything will work.
> 
> That seems like a reasonable requirement.

Not when this is not the case for everyone.

**Comment by gleb-cloudius** [comment]
> One way is to create a top-level container using systemd, and if the created container belongs to us, created nested cgroups directly. This way we make one change - to create the to-level container.

I am confused. You are talking about container creation @xtrey says test.py  does not create any containers.

**Comment by avikivity** [comment]
test.py does create containers: 

```
    def make_cgroup(self):
        os.makedirs(self.cgroup_path, exist_ok=True)
```

**Comment by avikivity** [comment]
In https://github.com/scylladb/scylladb/issues/22590 I found a way to gain access to /sys/fs/cgroup without problems.

**Comment by avikivity** [comment]
> > test.py does create containers:
> > ```
> >     def make_cgroup(self):
> >         os.makedirs(self.cgroup_path, exist_ok=True)
> > ```
> 
> Correct me if I'm wrong, but cgroup is not a container. cgroup plays a crucial role in containerization, but is not the same.

You're right, namespaces are the main technology.

But still, if we can use containers to make cgroups work for us reliably, let's do so.

**Comment by xtrey** [comment]
> But still, if we can use containers to make cgroups work for us reliably, let's do so.

No objections to using namespaces if it will be reliable. Until the recent fail on the CI metrics worked without issue in the container. All complaints, that are actually fully justified, about metrics were from folks who are not using containers and executing test.py directly on the host machine.
But it seems it's not [so trivial](https://github.com/scylladb/scylladb/issues/22590#issuecomment-2625594831). Metrics works correctly inside the container's issue only with the host and the current cgroup where the terminal is located. I'm still thinking that metrics should be switched only with full awareness of what you are doing and why you need this, and agree to deal with consequences.

**Comment by avikivity** [comment]
I would like metrics to be switched on even in the host environment. The reason is that I would like test.py to manage concurrency based on the metrics it measures at runtime. We can't do that if the metrics are disabled.

**Comment by xtrey** [comment]
> I would like metrics to be switched on even in the host environment. The reason is that I would like test.py to manage concurrency based on the metrics it measures at runtime. We can't do that if the metrics are disabled.

That's the plan to manage concurrency based on the metrics. But plan to have some DB/bucket on S3 where this information will be located. `test.py` will get this information during the run and will arrange how it's more efficient to run tests and store it locally (not metrics, but the order of execution and time needed for each test). With each consequent run, it will check if we have new information. In the worst case, it will have no such information, and it will execute not in the optimal way, but how it can do it right now.
This will allow us to not switch metrics by default on developer's machine and still have information about how to schedule tests more efficiently. Potentially, `next` job can update this information or specific job will check this weekly/daily and update this information

**Comment by avikivity** [comment]
I don't know if we can trust metrics generated on one run on one machine on a different run on another machine.

**Comment by xtrey** [comment]
>I don't know if we can trust metrics generated on one run on one machine on a different run on another machine.

The hardware on different machines is different, but the time of one test case I suppose will be more or less the same. Even if the time is different, the ratio between them will be the same.

Mostly we are interested in time, how long tests are executed. We will be scheduling the tests according to the time they are needed and increasing the number of threads according to the current machine, plus checking how much memory we still have. This is an initial assumption, and we can change after gathering feedback from developers.

**Comment by avikivity** [comment]
My guess is that it's going to be different, especially since we can reuse clusters across tests.

**Comment by xtrey** [comment]
In normal condition if test reuses the cluster, it will reuse it on CI, on local machine, etc. So the condition is the same. Anyway, the idea to implement the interface for scheduler. With that in mind, we can create several schedulers and switch them on by configuration parameter.

**Comment by temichus** [comment]
In addition to @xtrey, here is a doc with a described idea of the new scheduler https://docs.google.com/document/d/1x2_zxENyS6GNkU2BRqn73L_ODPDtskExE8LQInsntrY/edit?tab=t.0

**Comment by avikivity** [comment]
> In normal condition if test reuses the cluster, it will reuse it on CI, on local machine, etc. So the condition is the same. Anyway, the idea to implement the interface for scheduler. With that in mind, we can create several schedulers and switch them on by configuration parameter.

If you have different core counts (or just different performance) different tests will complete at different times (some tests consume wall time, some tests consume CPU time)

**Comment by nyh** [comment]
> If you have different core counts (or just different performance) different tests will complete at different times (some tests consume wall time, some tests consume CPU time)

I think you guys are over-engineering things. Yes, it's interesting to classify individual tests as: "cpu intensive on N cores", "wall clock intensive (i.e., sleeps a lot)", or "memory intensive" (rare tests which use non-default amount of memory for the test), but I don't think that to get reasonable online scheduling it will ever matter to know is last time a particular test ran for 1.7 seconds or 2.8 seconds.

Perhaps having perfect knowledge of the exact CPU usage of each test on your machine can squeeze out some few more percentages of runtime, but I don't think any developer will care. Developers won't want to spend 2 hours running tests on their laptop even if you assure that that 2 hours is the perfect minimum time. Developers will - in my experience - want to run a small subset of the tests or even one test while doing their development, and don't want to be forced to switch their terminal emulator (?!) or docker package (?!) to be able to do this one millisecond faster.

**Comment by temichus** [comment]
Let's back to the original problem 

@avikivity. Could you please review https://github.com/scylladb/scylladb/pull/21625#issuecomment-2621516612
