### ISSUE TITLE
non-boost tests.cql-pytest.cassandra_tests/validation/entities/frozen_collections_test failed with ConnectionException

### ISSUE THREAD

**Issue by kreuzerkrieg** [scylladb/scylladb#21219]
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12623/testReport/junit/(root)/non-boost%20tests/Tests___Unit_Tests___cql_pytest_cassandra_tests_validation_entities_frozen_collections_test_debug_2/

```
=== TEST.PY STARTING TEST cql-pytest.cassandra_tests/validation/entities/frozen_collections_test.2 ===
export UBSAN_OPTIONS='halt_on_error=1:abort_on_error=1:suppressions=/jenkins/workspace/scylla-master/scylla-ci/scylla/ubsan-suppressions.supp'
export ASAN_OPTIONS='disable_coredump=0:abort_on_error=1:detect_stack_use_after_return=1'
python --host=127.185.177.37 -s --log-level=DEBUG -o junit_family=xunit2 -o junit_suite_name=cql-pytest --junit-xml=/scylladir/testlog/x86_64/debug/xml/cql-pytest.cassandra_tests/validation/entities/frozen_collections_test.2.xunit.xml -rs --run_id=2 --mode=debug --alluredir=/scylladir/testlog/x86_64/debug/allure --allure-no-capture test/cql-pytest/cassandra_tests/validation/entities/frozen_collections_test.py
=== TEST.PY TEST cql-pytest.cassandra_tests/validation/entities/frozen_collections_test.2 OUTPUT ===
Driver name Scylla Python Driver, version 3.26.9
============================= test session starts ==============================
platform linux -- Python 3.12.6, pytest-7.4.3, pluggy-1.3.0
rootdir: /jenkins/workspace/scylla-master/scylla-ci/scylla/test/cql-pytest
configfile: pytest.ini
plugins: allure-pytest-2.13.5, asyncio-0.23.5.post1
asyncio: mode=Mode.STRICT
collected 33 items

test/cql-pytest/cassandra_tests/validation/entities/frozen_collections_test.py ................F  + Exception Group Traceback (most recent call last):
  |   File "<frozen runpy>", line 198, in _run_module_as_main
  |   File "<frozen runpy>", line 88, in _run_code
  |   File "/usr/lib/python3.12/site-packages/pytest/__main__.py", line 5, in <module>
  |     raise SystemExit(pytest.console_main())
  |                      ^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/_pytest/config/__init__.py", line 192, in console_main
  |     code = main()
  |            ^^^^^^
  |   File "/usr/lib/python3.12/site-packages/_pytest/config/__init__.py", line 169, in main
  |     ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 493, in __call__
  |     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 115, in _hookexec
  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 113, in _multicall
  |     raise exception.with_traceback(exception.__traceback__)
  |   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 77, in _multicall
  |     res = hook_impl.function(*args)
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/_pytest/main.py", line 318, in pytest_cmdline_main
  |     return wrap_session(config, _main)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/_pytest/main.py", line 306, in wrap_session
  |     config.hook.pytest_sessionfinish(
  |   File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 493, in __call__
  |     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 115, in _hookexec
  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 130, in _multicall
  |     teardown[0].send(outcome)
  |   File "/usr/lib/python3.12/site-packages/_pytest/terminal.py", line 857, in pytest_sessionfinish
  |     outcome.get_result()
  |   File "/usr/lib/python3.12/site-packages/pluggy/_result.py", line 114, in get_result
  |     raise exc.with_traceback(exc.__traceback__)
  |   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 77, in _multicall
  |     res = hook_impl.function(*args)
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 108, in pytest_sessionfinish
  |     session._setupstate.teardown_exact(None)
  |   File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 537, in teardown_exact
  |     raise exceptions[0]
  | ExceptionGroup: errors while tearing down <Session cql-pytest exitstatus=<ExitCode.INTERRUPTED: 2> testsfailed=1 testscollected=33> (3 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 526, in teardown_exact
    |     fin()
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 701, in <lambda>
    |     subrequest.node.addfinalizer(lambda: fixturedef.finish(request=subrequest))
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 1031, in finish
    |     raise exc
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 1024, in finish
    |     func()
    |   File "/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py", line 221, in __call__
    |     return self._fixture_function(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 911, in _teardown_yield_fixture
    |     next(it)
    |   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/cql-pytest/conftest.py", line 118, in test_keyspace_vnodes
    |     cql.execute("DROP KEYSPACE " + name)
    |   File "cassandra/cluster.py", line 2729, in cassandra.cluster.Session.execute
    |   File "cassandra/cluster.py", line 5120, in cassandra.cluster.ResponseFuture.result
    | cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.185.177.37:9042 datacenter1>: ConnectionException('Host has been marked down or removed')})
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 526, in teardown_exact
    |     fin()
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 701, in <lambda>
    |     subrequest.node.addfinalizer(lambda: fixturedef.finish(request=subrequest))
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 1031, in finish
    |     raise exc
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 1024, in finish
    |     func()
    |   File "/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py", line 221, in __call__
    |     return self._fixture_function(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 911, in _teardown_yield_fixture
    |     next(it)
    |   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/cql-pytest/conftest.py", line 107, in test_keyspace_tablets
    |     cql.execute("DROP KEYSPACE " + name)
    |   File "cassandra/cluster.py", line 2729, in cassandra.cluster.Session.execute
    |   File "cassandra/cluster.py", line 5120, in cassandra.cluster.ResponseFuture.result
    | cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.185.177.37:9042 datacenter1>: ConnectionException('Host has been marked down or removed')})
    +---------------- 3 ----------------
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 526, in teardown_exact
    |     fin()
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 701, in <lambda>
    |     subrequest.node.addfinalizer(lambda: fixturedef.finish(request=subrequest))
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 1031, in finish
    |     raise exc
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 1024, in finish
    |     func()
    |   File "/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py", line 221, in __call__
    |     return self._fixture_function(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 911, in _teardown_yield_fixture
    |     next(it)
    |   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/cql-pytest/conftest.py", line 139, in test_keyspace
    |     cql.execute("DROP KEYSPACE " + name)
    |   File "cassandra/cluster.py", line 2729, in cassandra.cluster.Session.execute
    |   File "cassandra/cluster.py", line 5120, in cassandra.cluster.ResponseFuture.result
    | cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.185.177.37:9042 datacenter1>: ConnectionException('Host has been marked down or removed')})
    +------------------------------------

! _pytest.outcomes.Exit: Scylla appears to have crashed in test cassandra_tests/validation/entities/frozen_collections_test.py::testClusteringColumnFiltering.debug.2 !
=== TEST.PY SUMMARY START ===
Test exited with code 1

=== TEST.PY SUMMARY END ===
```

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12623/

**Comment by yaronkaikov** [comment]
@kreuzerkrieg please add the link to the job failure, otherwise we will not be able to see the logs

**Comment by bhalevy** [comment]
I hit a similar issue in https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12694/testReport/(root)/non-boost%20tests/Tests___Unit_Tests___cql_pytest_cassandra_tests_validation_entities_frozen_collections_test_debug_3/
```
...
! _pytest.outcomes.Exit: Scylla appears to have crashed in test cassandra_tests/validation/entities/frozen_collections_test.py::testClusteringColumnFiltering.debug.3 !
```

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12694/artifact/testlog/x86_64/debug/scylla-271.log
```
Scylla version 6.3.0~dev-0.20241022.5ef1dd9775b4 with build-id f12769411574a10a7bc8a1bc017c5ac0a547f9b2 starting ...
...
DEBUG 2024-10-23 00:20:14,462 [shard 0: gms] query_processor - get_mutations_internal: "INSERT INTO system.view_build_status_v2 (keyspace_name, view_name, host_id, status) VALUES (?, ?, ?, ?)" (cql_test_1729632001951, d_index_index, d5397005-bc99-4547-ac2d-bfe92e314976, STARTED)
TRACE 2024-10-23 00:20:14,472 [shard 0: gms] group0_raft_sm - apply() is called with 1 commands
TRACE 2024-10-23 00:20:14,503 [shard 0: gms] group0_raft_sm - cmd: prev_state_id: optional(6d832ff2-90bb-11ef-09b7-f04b4099baaa), new_state_id: 6da57ddc-90bb-11ef-283c-38068c4a32ae, creator_addr: 127.68.18.64, creator_id: d5397005-bc99-4547-ac2d-bfe92e314976
TRACE 2024-10-23 00:20:14,503 [shard 0: gms] group0_raft_sm - cmd.history_append: {canonical_mutation: table_id 027e42f5-683a-3ed7-b404-a0100762063c schema_version c9c345e1-428f-36e0-b7d5-9af5f985021e partition_key pk{0007686973746f7279} partition_tombstone {tombstone: none}, row tombstone {range_tombstone: start={position: clustered, ckp{001044c13ddc8b3b11ef8080808080808080}, 1}, end={position: clustered, ckp{}, 1}, {tombstone: timestamp=1729632014462102, deletion_time=1729632014}}{row {position: clustered, ckp{00106da57ddc90bb11ef283c38068c4a32ae}, 0} tombstone {row_tombstone: none} marker {row_marker: 1729632014462102 0 0}, column description atomic_cell{view builder: mark view build STARTED,ts=1729632014462102,expiry=-1,ttl=0}}}
ERROR 2024-10-23 00:20:14,535 [shard 0: gms] view - Schema version used for view updates (6d8324d0-90bb-11ef-a563-24b52dc1b077) does not match the current base schema version of the view (6d502df0-90bb-11ef-a563-24b52dc1b077) for view cql_test_1729632001951.d_index_index of cql_test_1729632001951.cql_test_1729632010808, at: 0x303da95 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4623fb7 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4623c01 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x4627e50 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x462a9ef /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x34743d1 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3473fe7 0x74810d2 0x75a1cee 0x75682cb 0x75656e1 0x756d8fe 0x7563fd9 0x7563e5a 0x75634b1 0x7562ad3 0x756267e 0x754f428 0x74a4186 0x74f820a /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x335e612 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3bb3d09
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> ()>, seastar::future<void>::then_impl_nrvo<seastar::noncopyable_function<seastar::future<void> ()>, seastar::future<void> >(seastar::noncopyable_function<seastar::future<void> ()>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> ()>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
   --------
   seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
Aborting on shard 0, in scheduling group gossip.
Backtrace:
  0x303da95
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3853447
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x38530d5
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3694f1b
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x36ca775
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x37b8f49
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x37b9277
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x37b909e
  /lib64/libc.so.6+0x40cff
  /lib64/libc.so.6+0x99663
  /lib64/libc.so.6+0x40c4d
  /lib64/libc.so.6+0x28901
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x347400f
  0x74810d2
  0x75a1cee
  0x75682cb
  0x75656e1
  0x756d8fe
  0x7563fd9
  0x7563e5a
  0x75634b1
  0x7562ad3
  0x756267e
  0x754f428
  0x74a4186
  0x74f820a
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x335e612
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/debug/seastar/libseastar.so+0x3bb3d09
------ Ending test cql-pytest.cassandra_tests/validation/entities/frozen_collections_test.3 ------
```

Decoded
```
[Backtrace #0]
__interceptor_backtrace at /mnt/clang_build/llvm-project-x86_64/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:4358
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/debug/seastar/./seastar/include/seastar/util/backtrace.hh:68
seastar::backtrace_buffer::append_backtrace() at ./build/debug/seastar/./build/debug/seastar/./seastar/src/core/reactor.cc:805
seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/debug/seastar/./build/debug/seastar/./seastar/src/core/reactor.cc:838
seastar::print_with_backtrace(char const*, bool) at ./build/debug/seastar/./build/debug/seastar/./seastar/src/core/reactor.cc:850
seastar::sigabrt_action() at ./build/debug/seastar/./build/debug/seastar/./seastar/src/core/reactor.cc:3973
seastar::install_oneshot_signal_handler<6, (void (*)())(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::operator()(int, siginfo_t*, void*) const at ./build/debug/seastar/./build/debug/seastar/./seastar/src/core/reactor.cc:3950
seastar::install_oneshot_signal_handler<6, (void (*)())(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::__invoke(int, siginfo_t*, void*) at ./build/debug/seastar/./build/debug/seastar/./seastar/src/core/reactor.cc:3945
/data/scylla-s3-reloc.cache/by-build-id/f12769411574a10a7bc8a1bc017c5ac0a547f9b2/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=77c77fee058b19c6f001cf2cb0371ce3b8341211, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
__pthread_kill_implementation at ??:?
__GI_raise at :?
__GI_abort at :?
seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/debug/seastar/./build/debug/seastar/./seastar/src/core/on_internal_error.cc:56
db::view::make_view_update_builder(data_dictionary::database, replica::table const&, seastar::lw_shared_ptr<schema const> const&, std::vector<db::view::view_and_base, std::allocator<db::view::view_and_base> >&&, mutation_reader&&, seastar::optimized_optional<mutation_reader>&&, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >) at ././db/view/view.cc:1607
db::view::view_update_generator::populate_views(replica::table const&, std::vector<db::view::view_and_base, std::allocator<db::view::view_and_base> >, dht::token, mutation_reader&&, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >) at ././db/view/view_update_generator.cc:337
db::view::view_builder::consumer::flush_fragments() at ././db/view/view.cc:2956
_ZN22compact_mutation_stateIL20compact_for_sstables0EE24consume_end_of_partitionIN2db4view12view_builder8consumerE33noop_compacted_fragments_consumerQaa28CompactedFragmentsConsumerV2ITL0__E28CompactedFragmentsConsumerV2ITL0_0_EEEN7seastar10bool_classINSA_18stop_iteration_tagEEERT_RT0_ at ././db/view/view.cc:2970
seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::bool_class<seastar::stop_iteration_tag> >::invoke<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::consume(partition_end&&)::{lambda()#1}>(mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::consume(partition_end&&)::{lambda()#1}&&) at ././mutation/mutation_compactor.hh:700
auto seastar::futurize_invoke<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::consume(partition_end&&)::{lambda()#1}>(mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::consume(partition_end&&)::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:2063
 (inlined by) mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::consume(partition_end&&) at ././readers/mutation_reader.hh:290
 (inlined by) decltype(auto) mutation_fragment_v2::consume<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >(mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&) && requires MutationFragmentConsumerV2<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >, decltype ((((std::declval<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >)()).consume)((std::declval<range_tombstone_change>)()))> at ././mutation/mutation_fragment_v2.hh:287
mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::operator()(mutation_fragment_v2&&) at ././readers/mutation_reader.hh:270
 (inlined by) seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > std::__invoke_impl<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> >, mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2>(std::__invoke_other, mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2&&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/invoke.h:61
 (inlined by) std::__invoke_result<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2>::type std::__invoke<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2>(mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2&&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/invoke.h:96
 (inlined by) std::__invoke_result<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2>::type std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >::operator()<mutation_fragment_v2>(mutation_fragment_v2&&) const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/refwrap.h:363
 (inlined by) mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>)::{lambda()#1}::operator()() at ././readers/mutation_reader.hh:251
 (inlined by) seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >::invoke<mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>)::{lambda()#1}>(mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>)::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:2032
 (inlined by) auto seastar::futurize_invoke<mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>)::{lambda()#1}>(mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>)::{lambda()#1}&&) at ././seastar/include/seastar/core/future.hh:2063
void mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>) at ././readers/mutation_reader.hh:250
auto mutation_reader::impl::consume_in_thread<compact_for_query_v2<db::view::view_builder::consumer>, mutation_reader::no_filter>(compact_for_query_v2<db::view::view_builder::consumer>, mutation_reader::no_filter) requires (FlattenedConsumerV2<compact_for_query_v2<db::view::view_builder::consumer> >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>) at ././readers/mutation_reader.hh:337
auto mutation_reader::consume_in_thread<compact_for_query_v2<db::view::view_builder::consumer>, mutation_reader::no_filter>(compact_for_query_v2<db::view::view_builder::consumer>, mutation_reader::no_filter) requires (FlattenedConsumerV2<compact_for_query_v2<db::view::view_builder::consumer> >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>) at ././readers/mutation_reader.hh:479
auto mutation_reader::consume_in_thread<compact_for_query_v2<db::view::view_builder::consumer> >(compact_for_query_v2<db::view::view_builder::consumer>) requires FlattenedConsumerV2<compact_for_query_v2<db::view::view_builder::consumer> > at ././readers/mutation_reader.hh:486
db::view::view_builder::execute(db::view::view_builder::build_step&, exponential_backoff_retry) at ././db/view/view.cc:3015
seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::async<db::view::view_builder::do_build_step()::$_0>(seastar::thread_attributes, db::view::view_builder::do_build_step()::$_0&&)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) at ././db/view/view.cc:2554
```

**Comment by bhalevy** [comment]
Duplicate of https://github.com/scylladb/scylladb/issues/20216
