### ISSUE TITLE
test/cql-pytest/cassandra_tests/validation/entities/frozen_collections_test.py is flaky

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#21271]
```
Test python --host=127.224.227.30 -s --log-level=DEBUG -o junit_family=xunit2 -o junit_suite_name=cql-pytest --junit-xml=/scylladir/testlog/x86_64/debug/xml/cql-pytest.cassandra_tests/validation/entities/frozen_collections_test.1.xunit.xml -rs --run_id=1 --mode=debug --alluredir=/scylladir/testlog/x86_64/debug/allure --allure-no-capture test/cql-pytest/cassandra_tests/validation/entities/frozen_collections_test.py failed, check the log at /scylladir/testlog/x86_64/debug/cql-pytest.cassandra_tests/validation/entities/frozen_collections_test.1.log
```

```
=== TEST.PY STARTING TEST cql-pytest.cassandra_tests/validation/entities/frozen_collections_test.1 ===
export UBSAN_OPTIONS='halt_on_error=1:abort_on_error=1:suppressions=/jenkins/workspace/scylla-master/scylla-ci/scylla/ubsan-suppressions.supp'
export ASAN_OPTIONS='disable_coredump=0:abort_on_error=1:detect_stack_use_after_return=1'
python --host=127.224.227.30 -s --log-level=DEBUG -o junit_family=xunit2 -o junit_suite_name=cql-pytest --junit-xml=/scylladir/testlog/x86_64/debug/xml/cql-pytest.cassandra_tests/validation/entities/frozen_collections_test.1.xunit.xml -rs --run_id=1 --mode=debug --alluredir=/scylladir/testlog/x86_64/debug/allure --allure-no-capture test/cql-pytest/cassandra_tests/validation/entities/frozen_collections_test.py
=== TEST.PY TEST cql-pytest.cassandra_tests/validation/entities/frozen_collections_test.1 OUTPUT ===
Driver name Scylla Python Driver, version 3.26.9
============================= test session starts ==============================
platform linux -- Python 3.12.6, pytest-7.4.3, pluggy-1.3.0
rootdir: /jenkins/workspace/scylla-master/scylla-ci/scylla/test/cql-pytest
configfile: pytest.ini
plugins: allure-pytest-2.13.5, asyncio-0.23.5.post1
asyncio: mode=Mode.STRICT
collected 33 items

test/cql-pytest/cassandra_tests/validation/entities/frozen_collections_test.py ................F  + Exception Group Traceback (most recent call last):
  |   File "<frozen runpy>", line 198, in _run_module_as_main
  |   File "<frozen runpy>", line 88, in _run_code
  |   File "/usr/lib/python3.12/site-packages/pytest/__main__.py", line 5, in <module>
  |     raise SystemExit(pytest.console_main())
  |                      ^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/_pytest/config/__init__.py", line 192, in console_main
  |     code = main()
  |            ^^^^^^
  |   File "/usr/lib/python3.12/site-packages/_pytest/config/__init__.py", line 169, in main
  |     ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 493, in __call__
  |     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 115, in _hookexec
  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 113, in _multicall
  |     raise exception.with_traceback(exception.__traceback__)
  |   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 77, in _multicall
  |     res = hook_impl.function(*args)
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/_pytest/main.py", line 318, in pytest_cmdline_main
  |     return wrap_session(config, _main)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/_pytest/main.py", line 306, in wrap_session
  |     config.hook.pytest_sessionfinish(
  |   File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 493, in __call__
  |     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 115, in _hookexec
  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 130, in _multicall
  |     teardown[0].send(outcome)
  |   File "/usr/lib/python3.12/site-packages/_pytest/terminal.py", line 857, in pytest_sessionfinish
  |     outcome.get_result()
  |   File "/usr/lib/python3.12/site-packages/pluggy/_result.py", line 114, in get_result
  |     raise exc.with_traceback(exc.__traceback__)
  |   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 77, in _multicall
  |     res = hook_impl.function(*args)
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 108, in pytest_sessionfinish
  |     session._setupstate.teardown_exact(None)
  |   File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 537, in teardown_exact
  |     raise exceptions[0]
  | ExceptionGroup: errors while tearing down <Session cql-pytest exitstatus=<ExitCode.INTERRUPTED: 2> testsfailed=1 testscollected=33> (3 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 526, in teardown_exact
    |     fin()
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 701, in <lambda>
    |     subrequest.node.addfinalizer(lambda: fixturedef.finish(request=subrequest))
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 1031, in finish
    |     raise exc
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 1024, in finish
    |     func()
    |   File "/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py", line 221, in __call__
    |     return self._fixture_function(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 911, in _teardown_yield_fixture
    |     next(it)
    |   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/cql-pytest/conftest.py", line 118, in test_keyspace_vnodes
    |     cql.execute("DROP KEYSPACE " + name)
    |   File "cassandra/cluster.py", line 2729, in cassandra.cluster.Session.execute
    |   File "cassandra/cluster.py", line 5120, in cassandra.cluster.ResponseFuture.result
    | cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.224.227.30:9042 datacenter1>: ConnectionException('Host has been marked down or removed')})
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 526, in teardown_exact
    |     fin()
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 701, in <lambda>
    |     subrequest.node.addfinalizer(lambda: fixturedef.finish(request=subrequest))
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 1031, in finish
    |     raise exc
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 1024, in finish
    |     func()
    |   File "/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py", line 221, in __call__
    |     return self._fixture_function(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 911, in _teardown_yield_fixture
    |     next(it)
    |   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/cql-pytest/conftest.py", line 107, in test_keyspace_tablets
    |     cql.execute("DROP KEYSPACE " + name)
    |   File "cassandra/cluster.py", line 2729, in cassandra.cluster.Session.execute
    |   File "cassandra/cluster.py", line 5120, in cassandra.cluster.ResponseFuture.result
    | cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.224.227.30:9042 datacenter1>: ConnectionException('Host has been marked down or removed')})
    +---------------- 3 ----------------
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 526, in teardown_exact
    |     fin()
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 701, in <lambda>
    |     subrequest.node.addfinalizer(lambda: fixturedef.finish(request=subrequest))
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 1031, in finish
    |     raise exc
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 1024, in finish
    |     func()
    |   File "/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py", line 221, in __call__
    |     return self._fixture_function(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 911, in _teardown_yield_fixture
    |     next(it)
    |   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/cql-pytest/conftest.py", line 139, in test_keyspace
    |     cql.execute("DROP KEYSPACE " + name)
    |   File "cassandra/cluster.py", line 2729, in cassandra.cluster.Session.execute
    |   File "cassandra/cluster.py", line 5120, in cassandra.cluster.ResponseFuture.result
    | cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.224.227.30:9042 datacenter1>: ConnectionException('Host has been marked down or removed')})
    +------------------------------------

! _pytest.outcomes.Exit: Scylla appears to have crashed in test cassandra_tests/validation/entities/frozen_collections_test.py::testClusteringColumnFiltering.debug.1 !
=== TEST.PY SUMMARY START ===
Test exited with code 1

=== TEST.PY SUMMARY END ===
```

```
Backtrace:
  0x305dc15
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3860027
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x385fcb5
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x369c04b
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x36d3575
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x37c5819
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x37c5b47
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x37c596e
  /lib64/libc.so.6+0x40cff
  /lib64/libc.so.6+0x99663
  /lib64/libc.so.6+0x40c4d
  /lib64/libc.so.6+0x28901
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x347b03f
  0x4fb8132
  0x510780e
  0x50b00ab
  0x50acd31
  0x50b7efe
  0x50ab629
  0x50ab4aa
  0x50aab01
  0x50aa123
  0x50a9cce
  0x50883b8
  0x4fdb1e6
  0x502f1da
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3365642
  /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3bc09f9
```
decoded
```
Backtrace:
[Backtrace #0]
__interceptor_backtrace at /mnt/clang_build/llvm-project-x86_64/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:4358
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/Debug/seastar/./seastar/include/seastar/util/backtrace.hh:68
seastar::backtrace_buffer::append_backtrace() at ./build/Debug/seastar/./build/Debug/seastar/./seastar/src/core/reactor.cc:805
seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/Debug/seastar/./build/Debug/seastar/./seastar/src/core/reactor.cc:838
seastar::print_with_backtrace(char const*, bool) at ./build/Debug/seastar/./build/Debug/seastar/./seastar/src/core/reactor.cc:850
seastar::sigabrt_action() at ./build/Debug/seastar/./build/Debug/seastar/./seastar/src/core/reactor.cc:3981
seastar::install_oneshot_signal_handler<6, (void (*)())(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::operator()(int, siginfo_t*, void*) const at ./build/Debug/seastar/./build/Debug/seastar/./seastar/src/core/reactor.cc:3958
seastar::install_oneshot_signal_handler<6, (void (*)())(&seastar::sigabrt_action)>()::{lambda(int, siginfo_t*, void*)#1}::__invoke(int, siginfo_t*, void*) at ./build/Debug/seastar/./build/Debug/seastar/./seastar/src/core/reactor.cc:3953
/data/scylla-s3-reloc.cache/by-build-id/626895b52f96d289a030aeea5e001a8510286e0e/extracted/scylla/libreloc/libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=77c77fee058b19c6f001cf2cb0371ce3b8341211, for GNU/Linux 3.2.0, not stripped

__GI___sigaction at :?
__pthread_kill_implementation at ??:?
__GI_raise at :?
__GI_abort at :?
seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/Debug/seastar/./build/Debug/seastar/./seastar/src/core/on_internal_error.cc:56
db::view::make_view_update_builder(data_dictionary::database, replica::table const&, seastar::lw_shared_ptr<schema const> const&, std::vector<db::view::view_and_base, std::allocator<db::view::view_and_base> >&&, mutation_reader&&, seastar::optimized_optional<mutation_reader>&&, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >) at /jenkins/workspace/scylla-master/scylla-ci/scylla/db/view/view.cc:1611
db::view::view_update_generator::populate_views(replica::table const&, std::vector<db::view::view_and_base, std::allocator<db::view::view_and_base> >, dht::token, mutation_reader&&, std::chrono::time_point<gc_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >) at /jenkins/workspace/scylla-master/scylla-ci/scylla/db/view/view_update_generator.cc:337
db::view::view_builder::consumer::flush_fragments() at /jenkins/workspace/scylla-master/scylla-ci/scylla/db/view/view.cc:2960
_ZN22compact_mutation_stateIL20compact_for_sstables0EE24consume_end_of_partitionIN2db4view12view_builder8consumerE33noop_compacted_fragments_consumerQaa28CompactedFragmentsConsumerV2ITL0__E28CompactedFragmentsConsumerV2ITL0_0_EEEN7seastar10bool_classINSA_18stop_iteration_tagEEERT_RT0_ at /jenkins/workspace/scylla-master/scylla-ci/scylla/db/view/view.cc:2974
seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::bool_class<seastar::stop_iteration_tag> >::invoke<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::consume(partition_end&&)::{lambda()#1}>(mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::consume(partition_end&&)::{lambda()#1}&&) at /jenkins/workspace/scylla-master/scylla-ci/scylla/mutation/mutation_compactor.hh:700
auto seastar::futurize_invoke<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::consume(partition_end&&)::{lambda()#1}>(mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::consume(partition_end&&)::{lambda()#1}&&) at /jenkins/workspace/scylla-master/scylla-ci/scylla/seastar/include/seastar/core/future.hh:2063
 (inlined by) mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::consume(partition_end&&) at /jenkins/workspace/scylla-master/scylla-ci/scylla/readers/mutation_reader.hh:290
 (inlined by) decltype(auto) mutation_fragment_v2::consume<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >(mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&) && requires MutationFragmentConsumerV2<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >, decltype ((((std::declval<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >)()).consume)((std::declval<range_tombstone_change>)()))> at /jenkins/workspace/scylla-master/scylla-ci/scylla/mutation/mutation_fragment_v2.hh:287
mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >::operator()(mutation_fragment_v2&&) at /jenkins/workspace/scylla-master/scylla-ci/scylla/readers/mutation_reader.hh:270
 (inlined by) seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > std::__invoke_impl<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> >, mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2>(std::__invoke_other, mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2&&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/invoke.h:61
 (inlined by) std::__invoke_result<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2>::type std::__invoke<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2>(mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2&&) at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/invoke.h:96
 (inlined by) std::__invoke_result<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> >&, mutation_fragment_v2>::type std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >::operator()<mutation_fragment_v2>(mutation_fragment_v2&&) const at /usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/bits/refwrap.h:363
 (inlined by) mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>)::{lambda()#1}::operator()() at /jenkins/workspace/scylla-master/scylla-ci/scylla/readers/mutation_reader.hh:251
 (inlined by) seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > seastar::futurize<seastar::future<seastar::bool_class<seastar::stop_iteration_tag> > >::invoke<mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>)::{lambda()#1}>(mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>)::{lambda()#1}&&) at /jenkins/workspace/scylla-master/scylla-ci/scylla/seastar/include/seastar/core/future.hh:2032
 (inlined by) auto seastar::futurize_invoke<mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>)::{lambda()#1}>(mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>)::{lambda()#1}&&) at /jenkins/workspace/scylla-master/scylla-ci/scylla/seastar/include/seastar/core/future.hh:2063
void mutation_reader::impl::consume_pausable_in_thread<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter>(std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > >, mutation_reader::no_filter) requires (FlatMutationReaderConsumerV2<std::reference_wrapper<mutation_reader::impl::consumer_adapter<compact_for_query_v2<db::view::view_builder::consumer> > > >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>) at /jenkins/workspace/scylla-master/scylla-ci/scylla/readers/mutation_reader.hh:250
auto mutation_reader::impl::consume_in_thread<compact_for_query_v2<db::view::view_builder::consumer>, mutation_reader::no_filter>(compact_for_query_v2<db::view::view_builder::consumer>, mutation_reader::no_filter) requires (FlattenedConsumerV2<compact_for_query_v2<db::view::view_builder::consumer> >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>) at /jenkins/workspace/scylla-master/scylla-ci/scylla/readers/mutation_reader.hh:337
auto mutation_reader::consume_in_thread<compact_for_query_v2<db::view::view_builder::consumer>, mutation_reader::no_filter>(compact_for_query_v2<db::view::view_builder::consumer>, mutation_reader::no_filter) requires (FlattenedConsumerV2<compact_for_query_v2<db::view::view_builder::consumer> >)&&(FlattenedConsumerFilterV2<mutation_reader::no_filter>) at /jenkins/workspace/scylla-master/scylla-ci/scylla/readers/mutation_reader.hh:479
auto mutation_reader::consume_in_thread<compact_for_query_v2<db::view::view_builder::consumer> >(compact_for_query_v2<db::view::view_builder::consumer>) requires FlattenedConsumerV2<compact_for_query_v2<db::view::view_builder::consumer> > at /jenkins/workspace/scylla-master/scylla-ci/scylla/readers/mutation_reader.hh:486
db::view::view_builder::execute(db::view::view_builder::build_step&, exponential_backoff_retry) at /jenkins/workspace/scylla-master/scylla-ci/scylla/db/view/view.cc:3019
seastar::noncopyable_function<void ()>::direct_vtable_for<seastar::async<db::view::view_builder::do_build_step()::$_0>(seastar::thread_attributes, db::view::view_builder::do_build_step()::$_0&&)::{lambda()#1}>::call(seastar::noncopyable_function<void ()> const*) at /jenkins/workspace/scylla-master/scylla-ci/scylla/db/view/view.cc:2558
seastar::noncopyable_function<void ()>::operator()() const at ./build/Debug/seastar/./seastar/include/seastar/util/noncopyable_function.hh:215
seastar::thread_context::main() at ./build/Debug/seastar/./build/Debug/seastar/./seastar/src/core/thread.cc:312
```

**Comment by tchaikov** [comment]
[scylla-268.zip](https://github.com/user-attachments/files/17515311/scylla-268.zip)

**Comment by tchaikov** [comment]
so we crashed at https://github.com/scylladb/scylladb/blob/298cafff3537950f1b17b1fcf119e3d831bcd786/db/view/view.cc#L1611

**Comment by tchaikov** [comment]
dup of #9059
