### ISSUE TITLE
[c-s] failed validation after  destroying files and rebuild

### ISSUE THREAD

**Issue by timtimb0t** [scylladb/scylladb#21428]
## Packages

Scylla version: `6.3.0~dev-20241101.19a43b58599c` with build-id `8db6e96d95afbd2686d3ceaa32521f5696ac3b23`

Kernel Version: `6.8.0-1017-azure`

## Issue description
- Known issue

Issue occurred after test (**disrupt_repair_streaming_err nemeses**)  stopped scylla, deleted some amount of sstables and then started scylla, which is led to c-s failure but scylla itself is alive and never generated errors due to such test behavior.

```
java.io.IOException: Operation x0 on key(s) [4d31304c33364e354e30]: Data returned was not validated
```

Also, there is already opened [issue](https://github.com/scylladb/scylladb/issues/10887) but seems it is dead by this moment

## Impact

No visible impact on scylla but c-s generates critical errors

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 4 nodes (Standard_L16s_v3)

Scylla Nodes used in this run:
- longevity-tls-1tb-7d-master-db-node-327f9b62-eastus-7 (null | 10.0.0.6) (shards: 14)
- longevity-tls-1tb-7d-master-db-node-327f9b62-eastus-6 (null | 10.0.0.14) (shards: 14)
- longevity-tls-1tb-7d-master-db-node-327f9b62-eastus-5 (null | 10.0.0.14) (shards: 14)
- longevity-tls-1tb-7d-master-db-node-327f9b62-eastus-4 (null | 10.0.0.8) (shards: 14)
- longevity-tls-1tb-7d-master-db-node-327f9b62-eastus-3 (null | 10.0.0.7) (shards: 14)
- longevity-tls-1tb-7d-master-db-node-327f9b62-eastus-2 (null | 10.0.0.6) (shards: 14)
- longevity-tls-1tb-7d-master-db-node-327f9b62-eastus-1 (null | 10.0.0.5) (shards: 14)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/SCYLLA-IMAGES/providers/Microsoft.Compute/images/scylla-6.3.0-dev-x86_64-2024-11-02T02-16-27` (azure: undefined_region)

Test: `longevity-1tb-5days-azure-test`
Test id: `327f9b62-4806-4c0d-9e65-d49b897e6bc8`
Test name: `scylla-master/tier1/longevity-1tb-5days-azure-test`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-1TB-5days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/ba373698898e0c53406abaecd82ac311fa012f25/test-cases/longevity/longevity-1TB-5days-authorization-and-tls-ssl.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 327f9b62-4806-4c0d-9e65-d49b897e6bc8`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=327f9b62-4806-4c0d-9e65-d49b897e6bc8)
- Show all stored logs command: `$ hydra investigate show-logs 327f9b62-4806-4c0d-9e65-d49b897e6bc8`

## Logs:
- **longevity-tls-1tb-7d-master-db-node-327f9b62-eastus-5** - [https://cloudius-jenkins-test.s3.amazonaws.com/327f9b62-4806-4c0d-9e65-d49b897e6bc8/20241102_041856/longevity-tls-1tb-7d-master-db-node-327f9b62-eastus-5-327f9b62.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/327f9b62-4806-4c0d-9e65-d49b897e6bc8/20241102_041856/longevity-tls-1tb-7d-master-db-node-327f9b62-eastus-5-327f9b62.tar.gz)
- **longevity-tls-1tb-7d-master-db-node-327f9b62-eastus-4** - [https://cloudius-jenkins-test.s3.amazonaws.com/327f9b62-4806-4c0d-9e65-d49b897e6bc8/20241102_041856/longevity-tls-1tb-7d-master-db-node-327f9b62-eastus-4-327f9b62.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/327f9b62-4806-4c0d-9e65-d49b897e6bc8/20241102_041856/longevity-tls-1tb-7d-master-db-node-327f9b62-eastus-4-327f9b62.tar.gz)
- **longevity-tls-1tb-7d-master-db-node-327f9b62-eastus-2** - [https://cloudius-jenkins-test.s3.amazonaws.com/327f9b62-4806-4c0d-9e65-d49b897e6bc8/20241102_041856/longevity-tls-1tb-7d-master-db-node-327f9b62-eastus-2-327f9b62.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/327f9b62-4806-4c0d-9e65-d49b897e6bc8/20241102_041856/longevity-tls-1tb-7d-master-db-node-327f9b62-eastus-2-327f9b62.tar.gz)
- **db-cluster-327f9b62.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/327f9b62-4806-4c0d-9e65-d49b897e6bc8/20241103_070221/db-cluster-327f9b62.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/327f9b62-4806-4c0d-9e65-d49b897e6bc8/20241103_070221/db-cluster-327f9b62.tar.gz)
- **sct-runner-events-327f9b62.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/327f9b62-4806-4c0d-9e65-d49b897e6bc8/20241103_070221/sct-runner-events-327f9b62.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/327f9b62-4806-4c0d-9e65-d49b897e6bc8/20241103_070221/sct-runner-events-327f9b62.tar.gz)
- **sct-327f9b62.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/327f9b62-4806-4c0d-9e65-d49b897e6bc8/20241103_070221/sct-327f9b62.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/327f9b62-4806-4c0d-9e65-d49b897e6bc8/20241103_070221/sct-327f9b62.log.tar.gz)
- **loader-set-327f9b62.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/327f9b62-4806-4c0d-9e65-d49b897e6bc8/20241103_070221/loader-set-327f9b62.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/327f9b62-4806-4c0d-9e65-d49b897e6bc8/20241103_070221/loader-set-327f9b62.tar.gz)
- **monitor-set-327f9b62.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/327f9b62-4806-4c0d-9e65-d49b897e6bc8/20241103_070221/monitor-set-327f9b62.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/327f9b62-4806-4c0d-9e65-d49b897e6bc8/20241103_070221/monitor-set-327f9b62.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/tier1/job/longevity-1tb-5days-azure-test/41/)
[Argus](https://argus.scylladb.com/test/1e333df8-a7e8-4171-8ab7-1d7bdea907d5/runs?additionalRuns[]=327f9b62-4806-4c0d-9e65-d49b897e6bc8)
</details>

**Comment by timtimb0t** [comment]
@aleksbykov, could you please check this issue?

**Comment by aleksbykov** [comment]
After additional investigation, 
Looks like it cassandra stress internal error.
```
WARN  [cluster1-nio-worker-7] 2024-11-03 06:52:33,299 Connection.java:284 - Error creating netty channel to /10.0.0.5:9042
com.datastax.shaded.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /10.0.0.5:9042
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
        at com.datastax.shaded.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at com.datastax.shaded.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at com.datastax.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
WARN  [cluster1-nio-worker-1] 2024-11-03 06:57:16,626 Connection.java:284 - Error creating netty channel to /10.0.0.8:9042
com.datastax.shaded.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: /10.0.0.8:9042
Caused by: java.net.NoRouteToHostException: No route to host
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
        at com.datastax.shaded.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at com.datastax.shaded.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at com.datastax.shaded.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
FAILURE
java.lang.RuntimeException: Failed to execute stress action
3 c-s processes failed and exited with exit code: 1. It happened for some c-s threads which lost connection to :
10.0.0.8 - which was decommissioned earlier
10.0.0.5 - which was stopped

This happened for 3 loader nodes from 4th
This happened, when c-s processes was finishing its execution, and looks like it exited with exit code 1, because some threads failed.

**Comment by aleksbykov** [comment]
@temichus , should we move it to driver?

**Comment by fruch** [comment]
@dkropachev 
seem yet again issue with session closing, when some node are not available.

want to connect it to a specific java-driver issue ?

**Comment by dkropachev** [comment]
@fruch , let's create `c-s` issue on that link all these issues to it I will take a look when get a time, which is unfortunately not soon, maybe next sprint.

**Comment by fruch** [comment]
> [@temichus](https://github.com/temichus) , should we move it to driver?

we shouldn't move it,

2 things need to be look at

1) there 2 `disrupt_destroy_data_then_rebuild` on after the other, we need to see we are not deleting the same sstables in both
 
2)
after reading again and again @slivne comments at https://github.com/scylladb/scylladb/issues/10887

this nemesis isn't completely safe, and can break read validation in some cases. especially when we don't have hinted handoff anymore.

for reducing the changes of that happening, we need to add a repair at the beginning of this nemesis.
even that in this case, there were multiple nemesis that did repairs across the whole cluster (manager one and others)
so the data written during prepare should be all there and available on all nodes.

> [@fruch](https://github.com/fruch) , let's create an issue in https://github.com/scylladb/cassandra-stress repo and link all these issues to it I will take a look when get a time, which is unfortunately not soon, maybe next sprint.

raised an issue https://github.com/scylladb/cassandra-stress/issues/34

**Comment by aleksbykov** [comment]
1. Make nemesis more safely by adding repair
2. Rerun reproducer
