### ISSUE TITLE
tests.cql-pytest.test_permissions fails due to unreachable scylla when tearing down

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#21472]
```
=== TEST.PY STARTING TEST cql-pytest.test_permissions.3 ===
export UBSAN_OPTIONS='halt_on_error=1:abort_on_error=1:suppressions=/jenkins/workspace/scylla-master/scylla-ci/scylla/ubsan-suppressions.supp'
export ASAN_OPTIONS='disable_coredump=0:abort_on_error=1:detect_stack_use_after_return=1'
python --host=127.218.49.30 -s --log-level=DEBUG -o junit_family=xunit2 -o junit_suite_name=cql-pytest --junit-xml=/scylladir/testlog/x86_64/debug/xml/cql-pytest.test_permissions.3.xunit.xml -rs --run_id=3 --mode=debug --alluredir=/scylladir/testlog/x86_64/debug/allure --allure-no-capture test/cql-pytest/test_permissions.py
=== TEST.PY TEST cql-pytest.test_permissions.3 OUTPUT ===
Driver name Scylla Python Driver, version 3.26.9
============================= test session starts ==============================
platform linux -- Python 3.12.6, pytest-7.4.3, pluggy-1.3.0
rootdir: /jenkins/workspace/scylla-master/scylla-ci/scylla/test/cql-pytest
configfile: pytest.ini
plugins: allure-pytest-2.13.5, asyncio-0.23.5.post1
asyncio: mode=Mode.STRICT
collected 26 items

test/cql-pytest/test_permissions.py .................xxxx  + Exception Group Traceback (most recent call last):
  |   File "<frozen runpy>", line 198, in _run_module_as_main
  |   File "<frozen runpy>", line 88, in _run_code
  |   File "/usr/lib/python3.12/site-packages/pytest/__main__.py", line 5, in <module>
  |     raise SystemExit(pytest.console_main())
  |                      ^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/_pytest/config/__init__.py", line 192, in console_main
  |     code = main()
  |            ^^^^^^
  |   File "/usr/lib/python3.12/site-packages/_pytest/config/__init__.py", line 169, in main
  |     ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 493, in __call__
  |     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 115, in _hookexec
  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 113, in _multicall
  |     raise exception.with_traceback(exception.__traceback__)
  |   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 77, in _multicall
  |     res = hook_impl.function(*args)
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/_pytest/main.py", line 318, in pytest_cmdline_main
  |     return wrap_session(config, _main)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/_pytest/main.py", line 306, in wrap_session
  |     config.hook.pytest_sessionfinish(
  |   File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 493, in __call__
  |     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 115, in _hookexec
  |     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 130, in _multicall
  |     teardown[0].send(outcome)
  |   File "/usr/lib/python3.12/site-packages/_pytest/terminal.py", line 857, in pytest_sessionfinish
  |     outcome.get_result()
  |   File "/usr/lib/python3.12/site-packages/pluggy/_result.py", line 114, in get_result
  |     raise exc.with_traceback(exc.__traceback__)
  |   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 77, in _multicall
  |     res = hook_impl.function(*args)
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 108, in pytest_sessionfinish
  |     session._setupstate.teardown_exact(None)
  |   File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 537, in teardown_exact
  |     raise exceptions[0]
  | ExceptionGroup: errors while tearing down <Session cql-pytest exitstatus=<ExitCode.INTERRUPTED: 2> testsfailed=0 testscollected=26> (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 526, in teardown_exact
    |     fin()
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 701, in <lambda>
    |     subrequest.node.addfinalizer(lambda: fixturedef.finish(request=subrequest))
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 1031, in finish
    |     raise exc
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 1024, in finish
    |     func()
    |   File "/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py", line 221, in __call__
    |     return self._fixture_function(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 911, in _teardown_yield_fixture
    |     next(it)
    |   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/cql-pytest/conftest.py", line 118, in test_keyspace_vnodes
    |     cql.execute("DROP KEYSPACE " + name)
    |   File "cassandra/cluster.py", line 2729, in cassandra.cluster.Session.execute
    |   File "cassandra/cluster.py", line 5120, in cassandra.cluster.ResponseFuture.result
    | cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.218.49.30:9042 datacenter1>: ConnectionException('Host has been marked down or removed')})
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/usr/lib/python3.12/site-packages/_pytest/runner.py", line 526, in teardown_exact
    |     fin()
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 701, in <lambda>
    |     subrequest.node.addfinalizer(lambda: fixturedef.finish(request=subrequest))
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 1031, in finish
    |     raise exc
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 1024, in finish
    |     func()
    |   File "/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py", line 221, in __call__
    |     return self._fixture_function(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/lib/python3.12/site-packages/_pytest/fixtures.py", line 911, in _teardown_yield_fixture
    |     next(it)
    |   File "/jenkins/workspace/scylla-master/scylla-ci/scylla/test/cql-pytest/conftest.py", line 107, in test_keyspace_tablets
    |     cql.execute("DROP KEYSPACE " + name)
    |   File "cassandra/cluster.py", line 2729, in cassandra.cluster.Session.execute
    |   File "cassandra/cluster.py", line 5120, in cassandra.cluster.ResponseFuture.result
    | cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.218.49.30:9042 datacenter1>: ConnectionException('Host has been marked down or removed')})
    +------------------------------------
Exception in thread Task Scheduler:
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "cassandra/cluster.py", line 4383, in cassandra.cluster._Scheduler.run
  File "/usr/lib64/python3.12/concurrent/futures/thread.py", line 172, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
Exception in thread Task Scheduler:
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "cassandra/cluster.py", line 4383, in cassandra.cluster._Scheduler.run
  File "/usr/lib64/python3.12/concurrent/futures/thread.py", line 172, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
Exception in thread Task Scheduler:
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "cassandra/cluster.py", line 4383, in cassandra.cluster._Scheduler.run
  File "/usr/lib64/python3.12/concurrent/futures/thread.py", line 172, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
Exception in thread Task Scheduler:
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "cassandra/cluster.py", line 4383, in cassandra.cluster._Scheduler.run
  File "/usr/lib64/python3.12/concurrent/futures/thread.py", line 170, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown

! _pytest.outcomes.Exit: Scylla appears to have crashed in test test_permissions.py::test_auto_grant_cdc[True-vnodes].debug.3 !
=== TEST.PY SUMMARY START ===
Test exited with code 1

=== TEST.PY SUMMARY END ===
```

see https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/12974

**Comment by tchaikov** [comment]
[scylla-268.log.gz](https://github.com/user-attachments/files/17655278/scylla-268.log.gz)
[scylla-279.log.gz](https://github.com/user-attachments/files/17655280/scylla-279.log.gz)

**Comment by tchaikov** [comment]
unfortunately, seems scylla-279.log was truncated. the last couple lines in it are:
```
INFO  2024-11-05 12:48:00,372 [shard 0:comp] compaction - [Compact system.raft 6cdc28d0-9b63-11ef-9211-fe98a4c25445] Compacted 9 sstables to [/scylladir/testlog/x86_64/debug/scylla-279/data/system/raft-3e17774c57f539939625327cbafbf5bb/me-3gkz_0u00_1dq4g27yu11llltnb9-big-Data.db:level=0]. 465kB to 419kB (~90% of original) in 104ms = 4MB/s. ~1152 total partitions merged to 1.
INFO  2024-11-05 12:48:00,377 [shard 0:comp] compaction - [Compact system_schema.triggers 6cf3cf80-9b63-11ef-9211-fe98a4c25445] Compacting [/scylladir/testlog/x86_64/debug/scylla-279/data/system_schema/triggers-4df70b666b05325195a132b54005fd48/me-3gkz_0tzy_3ztgw27yu11llltnb9-big-Data.db:level=0:origin=memtable,/scylladir/testlog/x86_64/debug/scylla-279/data/system_schema/triggers-4df70b666b05325195a132b54005fd48/me-3gkz_0tzy_4xols27yu11llltnb9-big-Data.db:level=0:origin=compaction]
INFO  2024-11-05 12:48:00,425 [shard 0:comp] sstable - Rebuilding bloom filter /scylladir/testlog/x86_64/debug/scylla-279/data/system_schema/triggers-4df70b666b05325195a132b54005fd48/me-3gkz_0u00_29g3k27yu11llltnb9-big-Filter.db: resizing bitset from 328 bytes to 16 bytes. sstable origin: compaction
INFO  2024-11-05 12:48:00,483 [shard 0:comp] compaction - [Compact system_schema.triggers 6cf3cf80-9b63-11ef-9211-fe98a4c25445] Compacted 2 sstables to [/scylladir/testlog/x86_64/debug/scylla-279/data/system_schema/triggers-4df70b666b05325195a132b54005fd48/me-3gkz_0u00_29g3k27yu11llltnb9-big-Data.db:level=0]. 11kB to 5916 bytes (~51% of original) in 97ms = 118kB/s. ~256 total partitions merged to 7.
INFO  2024-11-05 12:48:03,142 [shard 0:strm] api - Profile will not be dumped, executable is not instrumented with profile dumping.
```
