### ISSUE TITLE
test.py requers combined_tests to be built even though it is not asked to run it.

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylladb#22038]
`$ ./test.py --mode debug  test_topology_ops` results is:

```
Traceback (most recent call last):
  File "/home/gleb/work/seastar/./test.py", line 2252, in workaround_python26789
    code = await main()
           ^^^^^^^^^^^^
  File "/home/gleb/work/seastar/./test.py", line 1946, in main
    await find_tests(options)
  File "/home/gleb/work/seastar/./test.py", line 1597, in find_tests
    suite = TestSuite.opt_create(f, options, mode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gleb/work/seastar/./test.py", line 217, in opt_create
    suite = SpecificTestSuite(path, cfg, options, mode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gleb/work/seastar/./test.py", line 401, in __init__
    self._generate_cache()
  File "/home/gleb/work/seastar/./test.py", line 377, in _generate_cache
    exe = path_to(self.mode, "test", self.name, 'combined_tests')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gleb/work/seastar/./test.py", line 100, in path_to
    raise FileNotFoundError(f"{exe_path} does not exist.")
FileNotFoundError: build/debug/test/boost/combined_tests does not exist.

```

**Comment by kostja** [comment]
@gleb-cloudius it's a regression from https://github.com/scylladb/scylladb/pull/21443
There was a lot of debate whether this is needed at all. Then SUDDENLY it got merged. 
Honestly, @avikivity I think this discredits the whole idea of maintainership. 
Why are people who're not maintaining test.py are actually merging patches into it and people who are doing the work have to run after them to ask for their patches to be merged?

I know @xtrey have been adding some regressions too, but at least he's got the full focus on test.py and he gets all the bugs in it, so he should be given a say.

**Comment by avikivity** [comment]
> [@gleb-cloudius](https://github.com/gleb-cloudius) it's a regression from [#21443](https://github.com/scylladb/scylladb/pull/21443) There was a lot of debate whether this is needed at all. Then SUDDENLY it got merged.

There was a debate about whether it affects modularity or not, then we found a way to avoid affecting modularity, then it was merged.

> Honestly, [@avikivity](https://github.com/avikivity) I think this discredits the whole idea of maintainership. 

Let's give everyone write access so they can push directly.

>Why are people who're not maintaining test.py are actually merging patches into it and people who are doing the work have to run after them to ask for their patches to be merged?

This was not a test.py change (maybe there were some impacts, but it's mainly a build change).

If there's problems in review throughput for test.py, let's address them.

> 
> I know [@xtrey](https://github.com/xtrey) have been adding some regressions too, but at least he's got the full focus on test.py and he gets all the bugs in it, so he should be given a say.

**Comment by nyh** [comment]
> ... There was a lot of debate whether this is needed at all. Then SUDDENLY it got merged. Honestly, [@avikivity](https://github.com/avikivity) I think this discredits the whole idea of maintainership. 

This has been a common theme recently - a patch was being pushed for many weeks (in this case, **two months**, after **three years** as an issue), and when a maintainer finally merges it reluctantly, people complain why it "suddenly" got merged and why this maintainer had no backbone to rejct it. Well, I have been trying to explain why this is happening and what is really broken in our review process - for a couple of years now, but got very little attention. These are the things at work that I keep warning about:

1. As the company management structure becomes more complex and more "official", the decision of what to work on, why and when, almost always comes from managers and not from maintainers or even the developers themselves. When a maintainer sees a developer was instructed by a manager to work on something for weeks, or at least allowed to do so, it becomes hard to say "no, I hate this, I refuse to commit this". It's easy to say "no" when you see the code has bugs or ugly warts - but when the code appears fine and you just don't like the whole approach or even the entire feature - it's no longer possible to say "no" in the current corporate structure. It's easier to say "Hmm, I am not a fan of this, I'll commit but I really hope you'll continue improving it later".
2. Hardly any non-maintainer ever does reviews. If you and Gleb and many others don't like this patch (and this is just an example, I don't want to put down this specific patch, I have no opinions on it myself) - why didn't any of them loudly object to it during the two months it was in review? Why didn't these non-maintainers leave **negative** reviews (the maintainers don't ignore those and they are more or less "veto" power)? Why didn't these non-maintainers go to the developer or their managers and say "hey, stop working on that - it's all wrong"?

>Why are people who're not maintaining test.py are actually merging patches into it and people who are doing the work have to run after them to ask for their patches to be merged?

Since when do we have the notion of "people who are maintaining test.py"? Who are those people? 
Did you look at who merged this patch? It was @avikivity. Are you suggesting that Avi shouldn't be merging patches?

If you have a list of "people who are maintaining test.py", please ask them why they didn't review this patch (which sat in github for a long time) and leave a **negative review**, which would not have been ignored by any maintainer.

**Comment by kostja** [comment]
@nyh I like the idea of the patch. And I was following the review process. Exactly because it was reluctantly accepted it was hard to catch the timing of what I care about - what it does in test.py
I have a very practical suggestion - test.py CODEOWNERS is updated to include @xtrey so he's nominated by github more frequently to review stuff.

**Comment by kostja** [comment]
@nyh on a different tangent, "managers" don't set priorities, we merely execute. And I was thinking RFC process is in place to prevent bad decisions. But we can continue on that in adifferent forum. With test.py I think we are not executing, we're mostly bikeshedding, to be honest.

**Comment by gleb-cloudius** [comment]
>     2. Hardly any non-maintainer ever does reviews. If you and Gleb and many others don't like this patch (and this is just an example, I don't want to put down this specific patch, I have no opinions on it myself) 

I am not sure what this rant was about, but I have to reply to that. The patch introduced a regression. You give me too much credit if you think that the way to never introduce any regressions it to make me review all the patches. As far as I understand @kostja complains that the regression was noticed during review and the patch was merged regardless.

**Comment by nyh** [comment]
> > ```
> > 2. Hardly any non-maintainer ever does reviews. If you and Gleb and many others don't like this patch (and this is just an example, I don't want to put down this specific patch, I have no opinions on it myself) 
> > ```
> 
> I am not sure what this rant was about, but I have to reply to that. The patch introduced a regression. You give me too much credit if you think that the way to never introduce any regressions it to make me review all the patches.

My rant was a response to Kostja's rant that suggested it's not fine that this patch was merged without consulting the "test.py maintainers" which I (perhaps wrongly) assumed included you since you are one of the people who cared most about the implications of this change.

> As far as I understand [@kostja](https://github.com/kostja) complains that the regression was noticed during review and the patch was merged regardless.

I don't think a regression was noticed during the review, and even if it was, whoever noticed a regression during review should have posted a negative review ("request changes") and I doubt Avi would have overrided a negative review.

**Comment by gleb-cloudius** [comment]
> > > ```
> > > 2. Hardly any non-maintainer ever does reviews. If you and Gleb and many others don't like this patch (and this is just an example, I don't want to put down this specific patch, I have no opinions on it myself) 
> > > ```
> > 
> > 
> > I am not sure what this rant was about, but I have to reply to that. The patch introduced a regression. You give me too much credit if you think that the way to never introduce any regressions it to make me review all the patches.
> 
> My rant was a response to Kostja's rant that suggested it's not fine that this patch was merged without consulting the "test.py maintainers" which I (perhaps wrongly) assumed included you since you are one of the people who cared most about the implications of this change.

I care when thing do not work as expected for me. I do not care much about test.py internals as long as it works. Actually I thought you are the maintainer of the test.py :)

> 
> > As far as I understand [@kostja](https://github.com/kostja) complains that the regression was noticed during review and the patch was merged regardless.
> 
> I don't think a regression was noticed during the review, and even if it was, whoever noticed a regression during review should have posted a negative review ("request changes") and I doubt Avi would have overrided a negative review.

In that case I do not know what we are arguing about. Regressions happen. Lets fix them and move on.

**Comment by nyh** [comment]
> I have a very practical suggestion - test.py CODEOWNERS is updated to include [@xtrey](https://github.com/xtrey) so he's nominated by github more frequently to review stuff.

@kostja unfortunately, as we discussed several times in the past, this doesn't work: Github only allows **maintainers** to be listed in CODEOWNERS (this five year old discussion https://github.com/orgs/community/discussions/23042 is just one of the many people who don't like this limitation). Which makes it, well, crap, for us... If @xtrey is not in @scylladb/scylla-maint he will not be suggested even if in CODEOWNERS.

In the past, Glauber suggested to write our own script that will use CODEOWNERS in the way **we** decide. People didn't like this approach because it had to be manual, but perhaps @scylladb/releng can automate this: Imagine a bot that goes to new pull requests and runs a script (that should inside scylla.git) that decides based on CODEOWNERS and random number generation or other techniques - who to invite to review this pull request.
