### ISSUE TITLE
scylla sstable tool bad output for max_column_names

### ISSUE THREAD

**Issue by hopugop** [scylladb/scylladb#22078]
Tested on 6.2.2

The json output generated by scylla sstable tool apparently contains a formatting issue that causes some json libs to break while interpreting it.

```
$ scylla sstable dump-statistics /var/lib/scylla/data/system/cdc_generations_v3-91327c90c41f11efb3aa346b1d3be8e1/me-3gmf_0ksi_36gdc2qcxn60mu0mox-big-Scylla.db  
{"sstables":{"/var/lib/scylla/data/system/cdc_generations_v3-91327c90c41f11efb3aa346b1d3be8e1/me-3gmf_0ksi_36gdc2qcxn60mu0mox-big-Data.db":{"offsets":{"validation":36,"compaction":89,"stats":117,"serialization":4523},"validation":{"partitioner":"org.apache.cassandra.dht.Murmur3Partitioner","filter_chance":0.01},"compaction":{"cardinality":[255,255,255,254,4,0,0,16,0,0,0,0,1,9,2,0,0,0,0,0,0,0,0,0]},"stats":{"estimated_partition_size":[{"offset":1,"value":0},{"offset":1,"value":0},{"offset":2,"value":0},{"offset":3,"value":0},{"offset":4,"value":0},{"offset":5,"value":0},{"offset":6,"value":0},{"offset":7,"value":0},{"offset":8,"value":0},{"offset":10,"value":0},{"offset":12,"value":0},{"offset":14,"value":0},{"offset":17,"value":0},{"offset":20,"value":0},{"offset":24,"value":0},{"offset":29,"value":0},{"offset":35,"value":0},{"offset":42,"value":0},{"offset":50,"value":0},{"offset":60,"value":0},{"offset":72,"value":0},{"offset":86,"value":0},{"offset":103,"value":0},{"offset":124,"value":0},{"offset":149,"value":0},{"offset":179,"value":0},{"offset":215,"value":0},{"offset":258,"value":0},{"offset":310,"value":0},{"offset":372,"value":0},{"offset":446,"value":0},{"offset":535,"value":0},{"offset":642,"value":0},{"offset":770,"value":0},{"offset":924,"value":0},{"offset":1109,"value":0},{"offset":1331,"value":0},{"offset":1597,"value":0},{"offset":1916,"value":0},{"offset":2299,"value":0},{"offset":2759,"value":0},{"offset":3311,"value":0},{"offset":3973,"value":0},{"offset":4768,"value":0},{"offset":5722,"value":0},{"offset":6866,"value":0},{"offset":8239,"value":0},{"offset":9887,"value":0},{"offset":11864,"value":1},{"offset":14237,"value":2},{"offset":17084,"value":0},{"offset":20501,"value":0},{"offset":24601,"value":0},{"offset":29521,"value":0},{"offset":35425,"value":0},{"offset":42510,"value":0},{"offset":51012,"value":0},{"offset":61214,"value":0},{"offset":73457,"value":0},{"offset":88148,"value":0},{"offset":105778,"value":0},{"offset":126934,"value":0},{"offset":152321,"value":0},{"offset":182785,"value":0},{"offset":219342,"value":0},{"offset":263210,"value":0},{"offset":315852,"value":0},{"offset":379022,"value":0},{"offset":454826,"value":0},{"offset":545791,"value":0},{"offset":654949,"value":0},{"offset":785939,"value":0},{"offset":943127,"value":0},{"offset":1131752,"value":0},{"offset":1358102,"value":0},{"offset":1629722,"value":0},{"offset":1955666,"value":0},{"offset":2346799,"value":0},{"offset":2816159,"value":0},{"offset":3379391,"value":0},{"offset":4055269,"value":0},{"offset":4866323,"value":0},{"offset":5839588,"value":0},{"offset":7007506,"value":0},{"offset":8409007,"value":0},{"offset":10090808,"value":0},{"offset":12108970,"value":0},{"offset":14530764,"value":0},{"offset":17436917,"value":0},{"offset":20924300,"value":0},{"offset":25109160,"value":0},{"offset":30130992,"value":0},{"offset":36157190,"value":0},{"offset":43388628,"value":0},{"offset":52066354,"value":0},{"offset":62479625,"value":0},{"offset":74975550,"value":0},{"offset":89970660,"value":0},{"offset":107964792,"value":0},{"offset":129557750,"value":0},{"offset":155469300,"value":0},{"offset":186563160,"value":0},{"offset":223875792,"value":0},{"offset":268650950,"value":0},{"offset":322381140,"value":0},{"offset":386857368,"value":0},{"offset":464228842,"value":0},{"offset":557074610,"value":0},{"offset":668489532,"value":0},{"offset":802187438,"value":0},{"offset":962624926,"value":0},{"offset":1155149911,"value":0},{"offset":1386179893,"value":0},{"offset":1663415872,"value":0},{"offset":1996099046,"value":0},{"offset":2395318855,"value":0},{"offset":2874382626,"value":0},{"offset":3449259151,"value":0},{"offset":4139110981,"value":0},{"offset":4966933177,"value":0},{"offset":5960319812,"value":0},{"offset":7152383774,"value":0},{"offset":8582860529,"value":0},{"offset":10299432635,"value":0},{"offset":12359319162,"value":0},{"offset":14831182994,"value":0},{"offset":17797419593,"value":0},{"offset":21356903512,"value":0},{"offset":25628284214,"value":0},{"offset":30753941057,"value":0},{"offset":36904729268,"value":0},{"offset":44285675122,"value":0},{"offset":53142810146,"value":0},{"offset":63771372175,"value":0},{"offset":76525646610,"value":0},{"offset":91830775932,"value":0},{"offset":110196931118,"value":0},{"offset":132236317342,"value":0},{"offset":158683580810,"value":0},{"offset":190420296972,"value":0},{"offset":228504356366,"value":0},{"offset":274205227639,"value":0},{"offset":329046273167,"value":0},{"offset":394855527800,"value":0},{"offset":473826633360,"value":0},{"offset":568591960032,"value":0},{"offset":682310352038,"value":0},{"offset":818772422446,"value":0},{"offset":982526906935,"value":0},{"offset":1179032288322,"value":0},{"offset":1414838745986,"value":0}],"estimated_cells_count":[{"offset":1,"value":0},{"offset":1,"value":0},{"offset":2,"value":0},{"offset":3,"value":0},{"offset":4,"value":0},{"offset":5,"value":0},{"offset":6,"value":0},{"offset":7,"value":0},{"offset":8,"value":0},{"offset":10,"value":0},{"offset":12,"value":0},{"offset":14,"value":0},{"offset":17,"value":0},{"offset":20,"value":0},{"offset":24,"value":0},{"offset":29,"value":0},{"offset":35,"value":0},{"offset":42,"value":0},{"offset":50,"value":0},{"offset":60,"value":0},{"offset":72,"value":0},{"offset":86,"value":0},{"offset":103,"value":0},{"offset":124,"value":0},{"offset":149,"value":0},{"offset":179,"value":0},{"offset":215,"value":0},{"offset":258,"value":0},{"offset":310,"value":0},{"offset":372,"value":0},{"offset":446,"value":0},{"offset":535,"value":0},{"offset":642,"value":0},{"offset":770,"value":0},{"offset":924,"value":3},{"offset":1109,"value":0},{"offset":1331,"value":0},{"offset":1597,"value":0},{"offset":1916,"value":0},{"offset":2299,"value":0},{"offset":2759,"value":0},{"offset":3311,"value":0},{"offset":3973,"value":0},{"offset":4768,"value":0},{"offset":5722,"value":0},{"offset":6866,"value":0},{"offset":8239,"value":0},{"offset":9887,"value":0},{"offset":11864,"value":0},{"offset":14237,"value":0},{"offset":17084,"value":0},{"offset":20501,"value":0},{"offset":24601,"value":0},{"offset":29521,"value":0},{"offset":35425,"value":0},{"offset":42510,"value":0},{"offset":51012,"value":0},{"offset":61214,"value":0},{"offset":73457,"value":0},{"offset":88148,"value":0},{"offset":105778,"value":0},{"offset":126934,"value":0},{"offset":152321,"value":0},{"offset":182785,"value":0},{"offset":219342,"value":0},{"offset":263210,"value":0},{"offset":315852,"value":0},{"offset":379022,"value":0},{"offset":454826,"value":0},{"offset":545791,"value":0},{"offset":654949,"value":0},{"offset":785939,"value":0},{"offset":943127,"value":0},{"offset":1131752,"value":0},{"offset":1358102,"value":0},{"offset":1629722,"value":0},{"offset":1955666,"value":0},{"offset":2346799,"value":0},{"offset":2816159,"value":0},{"offset":3379391,"value":0},{"offset":4055269,"value":0},{"offset":4866323,"value":0},{"offset":5839588,"value":0},{"offset":7007506,"value":0},{"offset":8409007,"value":0},{"offset":10090808,"value":0},{"offset":12108970,"value":0},{"offset":14530764,"value":0},{"offset":17436917,"value":0},{"offset":20924300,"value":0},{"offset":25109160,"value":0},{"offset":30130992,"value":0},{"offset":36157190,"value":0},{"offset":43388628,"value":0},{"offset":52066354,"value":0},{"offset":62479625,"value":0},{"offset":74975550,"value":0},{"offset":89970660,"value":0},{"offset":107964792,"value":0},{"offset":129557750,"value":0},{"offset":155469300,"value":0},{"offset":186563160,"value":0},{"offset":223875792,"value":0},{"offset":268650950,"value":0},{"offset":322381140,"value":0},{"offset":386857368,"value":0},{"offset":464228842,"value":0},{"offset":557074610,"value":0},{"offset":668489532,"value":0},{"offset":802187438,"value":0},{"offset":962624926,"value":0},{"offset":1155149911,"value":0},{"offset":1386179893,"value":0},{"offset":1663415872,"value":0},{"offset":1996099046,"value":0}],"position":{"id":297786,"pos":294920},"min_timestamp":1735283121130985,"max_timestamp":1735283127098929,"min_local_deletion_time":2147483647,"max_local_deletion_time":2147483647,"min_ttl":0,"max_ttl":0,"compression_ratio":0.5144708806818182,"estimated_tombstone_drop_time":{},"sstable_level":0,"repaired_at":0,"min_column_names":["\u0000\u0000\u0000\u0000"],"max_column_names":["\u0000\u0000\u0003�"],"has_legacy_counter_shards":0,"columns_count":3000,"rows_count":3000,"commitlog_lower_bound":{"id":0,"pos":0},"commitlog_intervals":[],"originating_host_id":"f6066261-10f1-460c-a52f-c00eeb3eafcd"},"serialization_header":{"min_timestamp_base":292403121130985,"min_local_deletion_time_base":9223372035411895807,"min_ttl_base":9223372036854775807,"pk_type_name":"org.apache.cassandra.db.marshal.Int32Type","clustering_key_types_names":["org.apache.cassandra.db.marshal.Int32Type"],"static_columns":[],"regular_columns":[{"name":"v","type_name":"org.apache.cassandra.db.marshal.Int32Type"}]}}}}
$
```

It contains this key:value combination:
```json
"max_column_names":["\u0000\u0000\u0003�"]
```

Which causes some tools such as `jq` and Python json libs to break:

```
$ cat output.json | jq
jq: parse error: Invalid escape at line 1, column 8348
```

```
Traceback (most recent call last):
  File "/tmp/ss.py", line 313, in <module>
    main()
  File "/tmp/ss.py", line 283, in main
    data = json.loads(result.stdout)
  File "/usr/lib/python3.10/json/__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 8336: invalid continuation byte
```

This happened with an actual user data table, but I found it reproduced on system tables such as `system.cdc_generations_v3`

**Comment by raphaelsc** [comment]
@denesb this problem prevents the output from being processed by a script when loading the json, so we've to think about how to overcome that in the serialization of min/max column names.

**Comment by denesb** [comment]
Turns out that `{min,max}_column_names` is in fact binary data storing `position_in_partition`, so it has to be treated as an exploded clustering key.

**Comment by denesb** [comment]
Fix here: https://github.com/scylladb/scylladb/pull/22225.
