### ISSUE TITLE
start and stop a table scrub causes "Storage I/O error: 28: No space left on device"

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#22088]
## Packages

Scylla version: `2024.3.0~dev-20241223.b8fe6e17c6a3` with build-id `0ac66e4fdafa71257cafa4345cffeb2909d388bc`

Kernel Version: `6.8.0-1021-aws`

## Issue description

- Started random_disrupt_method start_stop_validation_compaction
- Current Target: Node elasticity-test-nemesis-master-db-node-e7a94519-1 [54.154.97.78 | 10.4.13.241] with running nemesis: StartStopValidationCompaction
- Running command "curl -v -X GET "http://localhost:10000/storage_service/keyspace_scrub/keyspace1?cf=standard1&scrub_mode=VALIDATE"
- Running command "/usr/bin/nodetool -u scylla-qa -pw 'scylla-0'  stop SCRUB

log scneario:
start scrubbing c-s table on node-1:
```
< t:2024-12-29 22:47:32,354 f:remote_base.py  l:560  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.133>: Running command "curl -v -X GET "http://localhost:10000/storage_service/keyspace_scrub/keyspace1?cf=standard1&scrub_mode=VALIDATE""...
< t:2024-12-29 22:47:33,005 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.133>: > GET /storage_service/keyspace_scrub/keyspace1?cf=standard1&scrub_mode=VALIDATE HTTP/1.1
< t:2024-12-29 22:47:36,020 f:base.py         l:141  c:RemoteLibSSH2CmdRunner p:DEBUG > > GET /storage_service/keyspace_scrub/keyspace1?cf=standard1&scrub_mode=VALIDATE HTTP/1.1
< t:2024-12-29 22:47:36,020 f:base.py         l:143  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.133>: Command "curl -v -X GET "http://localhost:10000/storage_service/keyspace_scrub/keyspace1?cf=standard1&scrub_mode=VALIDATE"" finished with status 0
```
Stop scrubbing after few seconds:
```
< t:2024-12-29 22:47:32,354 f:compaction_ops.py l:101  c:sdcm.utils.compaction_ops p:INFO  > Starting to watch for user compaction logged...
< t:2024-12-29 22:47:33,005 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.133>: > GET /storage_service/keyspace_scrub/keyspace1?cf=standard1&scrub_mode=VALIDATE HTTP/1.1
< t:2024-12-29 22:47:35,509 f:compaction_ops.py l:95   c:sdcm.utils.compaction_ops p:INFO  > Stopping compaction with nodetool stop SCRUB
< t:2024-12-29 22:47:35,510 f:remote_base.py  l:560  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.133>: Running command "/usr/bin/nodetool -u scylla-qa -pw 'scylla-0'  stop SCRUB "...
< t:2024-12-29 22:47:35,511 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2024-12-29 22:47:35.510: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=77dff916-45bc-4f25-bb77-42b7ef859b0a: nodetool_command=stop node=elasticity-test-nemesis-master-db-node-e7a94519-1 options=SCRUB
< t:2024-12-29 22:47:35,551 f:db_log_reader.py l:125  c:sdcm.db_log_reader   p:DEBUG > 2024-12-29T22:47:35.509+00:00 elasticity-test-nemesis-master-db-node-e7a94519-1     !INFO | scylla[6555]:  [shard 0:strm] compaction - Scrubbing in validate mode /var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1qc4_05sc02fq15lj3ermmb-big-Data.db
```
Then it ran a bloom filter rebuild + compactions for ~ 12 minutes and failed for no-space-left:
```
2024-12-29T23:00:57.008+00:00 elasticity-test-nemesis-master-db-node-e7a94519-1     !INFO | scylla[6555]:  [shard 0:comp] compaction - [Compact keyspace1.standard1 c3391121-c638-11ef-a03c-937c3a7cd543] Compacting [/var/lib/scylla/data/keyspace1/st
andard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1lrv_2n5xc2fq15lj3ermmb-big-Data.db:level=0:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1jqw_0lfls2fq15lj3ermmb-big-Data.db:level=0:origin=com
paction,/var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1pt5_4djao2fq15lj3ermmb-big-Data.db:level=0:origin=compaction]
2024-12-29T23:00:57.008+00:00 elasticity-test-nemesis-master-db-node-e7a94519-1     !INFO | scylla[6555]:  [shard 0:comp] compaction - [Compact keyspace1.standard1 c3391120-c638-11ef-a03c-937c3a7cd543] Compacting [/var/lib/scylla/data/keyspace1/st
andard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1n26_2onxs2fq15lj3ermmb-big-Data.db:level=0:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1mlc_4btkg2fq15lj3ermmb-big-Data.db:level=0:origin=com
paction,/var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1mnm_5mz3k2fq15lj3ermmb-big-Data.db:level=0:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1ooz_08kn42fq
15lj3ermmb-big-Data.db:level=0:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1oqx_0zskw2fq15lj3ermmb-big-Data.db:level=0:origin=compaction]
2024-12-29T23:00:57.008+00:00 elasticity-test-nemesis-master-db-node-e7a94519-1     !INFO | scylla[6555]:  [shard 0:comp] compaction - [Compact keyspace1.standard1 c3393830-c638-11ef-a03c-937c3a7cd543] Compacting [/var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1pwb_0ffk02fq15lj3ermmb-big-Data.db:level=0:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1px0_5qm9s2fq15lj3ermmb-big-Data.db:level=0:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1nu0_3syk02fq15lj3ermmb-big-Data.db:level=0:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1nwg_0xv4w2fq15lj3ermmb-big-Data.db:level=0:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1rwp_338mo2fq15lj3ermmb-big-Data.db:level=0:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1rxg_5qm9s2fq15lj3ermmb-big-Data.db:level=0:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1lvr_5x9gw2fq15lj3ermmb-big-Data.db:level=0:origin=compaction,/var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1lyy_0857k2fq15lj3ermmb-big-Data.db:level=0:origin=compaction]
2024-12-29T23:01:01.662+00:00 elasticity-test-nemesis-master-db-node-e7a94519-1     !INFO | scylla[6555]:  [shard 1:comp] sstable - Rebuilding bloom filter /var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1rwb_1381c2omoils14c6rn-big-Filter.db: resizing bitset from 1056136 bytes to 1173760 bytes. sstable origin: compaction
2024-12-29T23:01:01.663+00:00 elasticity-test-nemesis-master-db-node-e7a94519-1      !ERR | scylla[6555]:  [shard 0:comp] storage_service - Shutting down communications due to I/O errors until operator intervention: Disk error: std::system_error (error system:28, No space left on device)
```
- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 3 nodes (i4i.large)

Scylla Nodes used in this run:
- elasticity-test-nemesis-master-db-node-e7a94519-3 (63.34.207.135 | 10.4.12.243) (shards: 2)
- elasticity-test-nemesis-master-db-node-e7a94519-2 (54.155.176.113 | 10.4.13.178) (shards: 2)
- elasticity-test-nemesis-master-db-node-e7a94519-1 (54.154.97.78 | 10.4.13.241) (shards: 2)

OS / Image: `ami-0d544310101b7dd0a` (aws: undefined_region)

Test: `byo-longevity-test-yg2`
Test id: `e7a94519-4913-4a3b-9125-b8d92a8f0118`
Test name: `scylla-staging/yarongilor/byo-longevity-test-yg2`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [perf-regression-latency-i4i_2xlarge-elasticity-90-percent-with-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/38ffa9aef8985c39ebad79bcde260c0d294ef4ac/test-cases/performance/perf-regression-latency-i4i_2xlarge-elasticity-90-percent-with-nemesis.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor e7a94519-4913-4a3b-9125-b8d92a8f0118`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=e7a94519-4913-4a3b-9125-b8d92a8f0118)
- Show all stored logs command: `$ hydra investigate show-logs e7a94519-4913-4a3b-9125-b8d92a8f0118`

## Logs:
- **db-cluster-e7a94519.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e7a94519-4913-4a3b-9125-b8d92a8f0118/20241229_232050/db-cluster-e7a94519.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e7a94519-4913-4a3b-9125-b8d92a8f0118/20241229_232050/db-cluster-e7a94519.tar.gz)
- **sct-runner-events-e7a94519.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e7a94519-4913-4a3b-9125-b8d92a8f0118/20241229_232050/sct-runner-events-e7a94519.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e7a94519-4913-4a3b-9125-b8d92a8f0118/20241229_232050/sct-runner-events-e7a94519.tar.gz)
- **sct-e7a94519.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e7a94519-4913-4a3b-9125-b8d92a8f0118/20241229_232050/sct-e7a94519.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e7a94519-4913-4a3b-9125-b8d92a8f0118/20241229_232050/sct-e7a94519.log.tar.gz)
- **loader-set-e7a94519.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e7a94519-4913-4a3b-9125-b8d92a8f0118/20241229_232050/loader-set-e7a94519.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e7a94519-4913-4a3b-9125-b8d92a8f0118/20241229_232050/loader-set-e7a94519.tar.gz)
- **monitor-set-e7a94519.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e7a94519-4913-4a3b-9125-b8d92a8f0118/20241229_232050/monitor-set-e7a94519.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e7a94519-4913-4a3b-9125-b8d92a8f0118/20241229_232050/monitor-set-e7a94519.tar.gz)
- **ssl-conf-e7a94519.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/e7a94519-4913-4a3b-9125-b8d92a8f0118/20241229_232050/ssl-conf-e7a94519.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/e7a94519-4913-4a3b-9125-b8d92a8f0118/20241229_232050/ssl-conf-e7a94519.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/byo-longevity-test-yg2/17/)
[Argus](https://argus.scylladb.com/test/3ff6f750-9e72-40ed-a58c-ad87c2a8f505/runs?additionalRuns[]=e7a94519-4913-4a3b-9125-b8d92a8f0118)
</details>

**Comment by avikivity** [comment]
Unrelated:

```
2024-12-29T23:01:01.662+00:00 elasticity-test-nemesis-master-db-node-e7a94519-1     !INFO | scylla[6555]:  [shard 1:comp] sstable - Rebuilding bloom filter /var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1rwb_1381c2omoils14c6rn-big-Filter.db: resizing bitset from 1056136 bytes to 1173760 bytes. sstable origin: compaction
```

This resize seems wasteful. @Lakshmipathi

**Comment by avikivity** [comment]
Maybe it's a manifestation of https://github.com/scylladb/scylladb/issues/22028.

**Comment by yarongilor** [comment]
Possibly reproduced with "nodetool scrub" command as well:
```
disrupt_corrupt_then_scrub	elasticity-test-nemesis-master-db-node-922fea83-3	Failed	2024-12-31 15:20:36	2024-12-31 15:34:07
Nemesis Information
Class: Sisyphus
Name: disrupt_corrupt_then_scrub
Status: Failed
Failure reason
Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 5452, in wrapper
    result = method(*args[1:], **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 4189, in disrupt_corrupt_then_scrub
    self.target_node.run_nodetool("scrub", args=f"--skip-corrupted {ks}")
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2671, in run_nodetool
    runner(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose, retry=retry)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 653, in run
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 72, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 644, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 577, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 625, in run
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 660, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: "/usr/bin/nodetool -u scylla-qa -pw 'scylla-0'  scrub --skip-corrupted keyspace1"

Exit code: 4

Stdout:



Stderr:

error executing GET request to http://localhost:10000/storage_service/keyspace_scrub/keyspace1 with parameters {"scrub_mode": "SKIP"}: remote replied with status code 500 Internal Server Error:
storage_io_error (Storage I/O error: 28: No space left on device)
```
```
2024-12-31 15:34:06.554 <2024-12-31 15:34:06.474>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=ac778c41-6c35-4d83-80d9-d26b94625456: type=NO_SPACE_ERROR regex=No space left on device line_number=4834 node=elasticity-test-nemesis-master-db-node-922fea83-3
2024-12-31T15:34:06.474+00:00 elasticity-test-nemesis-master-db-node-922fea83-3      !ERR | scylla[5829]:  [shard 1:strm] storage_service - Shutting down communications due to I/O errors until operator intervention: Disk error: std::system_error (error system:28, No space left on device)
0x1f0cadd
```


## Packages

Scylla version: `2024.3.0~dev-20241229.307c8f6dce8b` with build-id `11053057c6c9439a10501c8cf06bdd71b8d49157`





Kernel Version: `6.8.0-1021-aws`


## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 3 nodes (i4i.large)

Scylla Nodes used in this run:
- elasticity-test-nemesis-master-db-node-922fea83-3 (34.253.54.183 | 10.4.14.145) (shards: 2)
- elasticity-test-nemesis-master-db-node-922fea83-2 (34.255.65.164 | 10.4.15.53) (shards: 2)
- elasticity-test-nemesis-master-db-node-922fea83-1 (63.33.32.128 | 10.4.12.113) (shards: 2)


OS / Image: `ami-0abef21093ec08085` (aws: undefined_region)

Test: `byo-longevity-test-yg2`
Test id: `922fea83-e70f-4c08-90ac-baa46eae1c0b`
Test name: `scylla-staging/yarongilor/byo-longevity-test-yg2`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [perf-regression-latency-i4i_2xlarge-elasticity-90-percent-with-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/5a01287b6552672a90accaa4846077835945da38/test-cases/performance/perf-regression-latency-i4i_2xlarge-elasticity-90-percent-with-nemesis.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 922fea83-e70f-4c08-90ac-baa46eae1c0b`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=922fea83-e70f-4c08-90ac-baa46eae1c0b)
- Show all stored logs command: `$ hydra investigate show-logs 922fea83-e70f-4c08-90ac-baa46eae1c0b`


## Logs:
- **db-cluster-922fea83.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/922fea83-e70f-4c08-90ac-baa46eae1c0b/20241231_153817/db-cluster-922fea83.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/922fea83-e70f-4c08-90ac-baa46eae1c0b/20241231_153817/db-cluster-922fea83.tar.gz)
- **sct-runner-events-922fea83.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/922fea83-e70f-4c08-90ac-baa46eae1c0b/20241231_153817/sct-runner-events-922fea83.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/922fea83-e70f-4c08-90ac-baa46eae1c0b/20241231_153817/sct-runner-events-922fea83.tar.gz)
- **sct-922fea83.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/922fea83-e70f-4c08-90ac-baa46eae1c0b/20241231_153817/sct-922fea83.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/922fea83-e70f-4c08-90ac-baa46eae1c0b/20241231_153817/sct-922fea83.log.tar.gz)
- **loader-set-922fea83.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/922fea83-e70f-4c08-90ac-baa46eae1c0b/20241231_153817/loader-set-922fea83.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/922fea83-e70f-4c08-90ac-baa46eae1c0b/20241231_153817/loader-set-922fea83.tar.gz)
- **monitor-set-922fea83.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/922fea83-e70f-4c08-90ac-baa46eae1c0b/20241231_153817/monitor-set-922fea83.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/922fea83-e70f-4c08-90ac-baa46eae1c0b/20241231_153817/monitor-set-922fea83.tar.gz)
- **ssl-conf-922fea83.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/922fea83-e70f-4c08-90ac-baa46eae1c0b/20241231_153817/ssl-conf-922fea83.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/922fea83-e70f-4c08-90ac-baa46eae1c0b/20241231_153817/ssl-conf-922fea83.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/yarongilor/job/byo-longevity-test-yg2/18/)
[Argus](https://argus.scylladb.com/test/3ff6f750-9e72-40ed-a58c-ad87c2a8f505/runs?additionalRuns[]=922fea83-e70f-4c08-90ac-baa46eae1c0b)
</details>

**Comment by lkshminarayanan** [comment]
> Unrelated:
> 
> ```
> 2024-12-29T23:01:01.662+00:00 elasticity-test-nemesis-master-db-node-e7a94519-1     !INFO | scylla[6555]:  [shard 1:comp] sstable - Rebuilding bloom filter /var/lib/scylla/data/keyspace1/standard1-d0ced870c61e11efa03c937c3a7cd543/me-3gmh_1rwb_1381c2omoils14c6rn-big-Filter.db: resizing bitset from 1056136 bytes to 1173760 bytes. sstable origin: compaction
> ```

@avikivity We do not rebuild if the effective false positive rate of the initial bloom filter based on the partition estimate is within 0.75 - 1.25 times the configured false positive rate.

In this case, with the inital bloom filter based on partition estimate  (bitset size : 1056136), the effective false positive rate is almost 1.5 times the configured false positive rate (0.01), so the rebuild is triggered.

> 
> This resize seems wasteful. [@Lakshmipathi](https://github.com/Lakshmipathi)

different Lakshmi btw!
