### ISSUE TITLE
Crash in gossiper during node stop

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#2864]
*Installation details*
Scylla version (or git commit hash): e265c916168314ab01b10138a1ad9bccda480a2a

```
#0  seastar::shared_ptr<db::system_keyspace::local_cache>::shared_ptr (x=..., this=0x7f4af4df4c20)
    at /jenkins/workspace/scylla-2.0-dtest/label/monster/mode/release/smp/2/scylla/seastar/core/shared_ptr.hh:377
#1  seastar::sharded<db::system_keyspace::local_cache>::get_local_service (this=0x26e4be0 <db::system_keyspace::_local_cache>) at ./seastar/core/sharded.hh:317
#2  0x0000000000eb5e73 in seastar::sharded<db::system_keyspace::local_cache>::<lambda(unsigned int)>::<lambda()>::operator() (__closure=0x6000001352a8)
    at ./seastar/core/sharded.hh:431
#3  seastar::futurize<seastar::future<> >::apply<seastar::sharded<Service>::invoke_on_all(Func&&)::<lambda(unsigned int)> [with Func = db::system_keyspace::update_cached_values(gms::inet_address, seastar::sstring, Value) [with Value = seastar::basic_sstring<char, unsigned int, 15u>]::<lambda(db::system_keyspace::local_cache&)>; Service = db::system_keyspace::local_cache]::<lambda()>&> (func=...) at ./seastar/core/future.hh:1312
#4  seastar::smp_message_queue::async_work_item<seastar::sharded<Service>::invoke_on_all(Func&&)::<lambda(unsigned int)> [with Func = db::system_keyspace::update_cached_values(gms::inet_address, seastar::sstring, Value) [with Value = seastar::basic_sstring<char, unsigned int, 15u>; seastar::sstring = seastar::basic_sstring<char, unsigned int, 15u>]::<lambda(db::system_keyspace::local_cache&)>; Service = db::system_keyspace::local_cache]::<lambda()> >::process(void) (this=0x6000001352a0)
    at /jenkins/workspace/scylla-2.0-dtest/label/monster/mode/release/smp/2/scylla/seastar/core/reactor.hh:339
#5  0x00000000004c2857 in seastar::smp_message_queue::<lambda(seastar::smp_message_queue::work_item*)>::operator() (wi=0x6000001352a0, __closure=<synthetic pointer>)
    at core/reactor.cc:3160
#6  seastar::smp_message_queue::process_queue<2ul, seastar::smp_message_queue::process_incoming()::<lambda(seastar::smp_message_queue::work_item*)> >(seastar::smp_message_queue::lf_queue &, seastar::smp_message_queue::<lambda(seastar::smp_message_queue::work_item*)>) (q=..., process=..., process@entry=..., this=0x600000982400)
    at core/reactor.cc:3133
#7  0x00000000004c3358 in seastar::smp_message_queue::process_incoming (this=0x600000982400) at core/reactor.cc:3163
#8  seastar::smp::poll_queues () at core/reactor.cc:3749
#9  0x0000000000496c95 in seastar::reactor::poll_once (this=<optimized out>) at core/reactor.cc:2871
#10 seastar::reactor::<lambda()>::operator() (__closure=0x7f4af4df53c0) at core/reactor.cc:2768
#11 std::_Function_handler<bool(), seastar::reactor::run()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/6.3.1/functional:1717
#12 0x00000000004ec5a8 in std::function<bool ()>::operator()() const (this=0x7f4af4df53c0) at /usr/include/c++/6.3.1/functional:2127
#13 seastar::reactor::run (this=0x6010005c3000) at core/reactor.cc:2793
#14 0x00000000004ede22 in seastar::smp::<lambda()>::operator()(void) const (__closure=0x6000000ad7c0) at core/reactor.cc:3707
#15 0x0000000000543f0e in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/include/c++/6.3.1/functional:2127
#16 seastar::posix_thread::start_routine (arg=<optimized out>) at core/posix.cc:52
#17 0x00007f4af905e73a in start_thread () from /lib64/libpthread.so.0
#18 0x00007f4af8d98e0f in clone () from /lib64/libc.so.6
```

Stop was due to:
```
ERROR 2017-10-04 13:14:45,791 [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (A node required to move the data consistently is down (127.0.0.1).  If you wish to move the data from a potentially inconsistent replica, restart the node with consistent_rangemovement=false)
```

**Comment by tzach** [comment]
@tgrabiec is this issue still relevant?

**Comment by tgrabiec** [comment]
@tzach I have no reason to believe it's not.

**Comment by bhalevy** [comment]
The code has changed significantly and this issue wasn't reproduced, so closing.
