### ISSUE TITLE
compaction failed: std::bad_alloc (std::bad_alloc) during nodetool refresh 

### ISSUE THREAD

**Issue by harelassayag** [scylladb/scylladb#3614]
*Installation details*
Scylla version (or git commit hash): 2.2.0-0.20180709.240b9f122
Cluster size: 3 nodes 500GB
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI ami-0a785275

**stress commands**
we are running write with verify
```
prepare_verify_cmd: cassandra-stress read cl=ALL n=200200300  -schema 'replication(factor=3) compaction(strategy=LeveledCompactionStrategy)' -port jmx=6868 -mode cql3 native user=cassandra password=cassandra -rate threads=2000 -col 'size=FIXED(1024) n=FIXED(1)' -pop seq=1..200200300 -log interval=15
stress_cmd: ["cassandra-stress write cl=QUORUM duration=2860m  -schema 'replication(factor=3) compaction(strategy=LeveledCompactionStrategy)' -
port jmx=6868 -mode cql3 native user=cassandra password=cassandra -rate threads=250  -col 'size=FIXED(1024) n=FIXED(1)' -pop seq=400200300..600200300 -log interval=15"]
stress_read_cmd: ["cassandra-stress read cl=ONE duration=2860m -schema 'replication(factor=3) compaction(strategy=LeveledCompactionStrategy)' -
port jmx=6868 -mode cql3 native user=cassandra password=cassandra -rate threads=250  -col 'size=FIXED(1024) n=FIXED(1)' -pop seq=1..200200300 -log interval=5"]
```
Refresh nemesis:
```
2018-07-18 20:29:00,057 nemesis          L0185 DEBUG| sdcm.nemesis.LimitedChaosMonkey: Set current_disruption -> Refresh keyspace1.standard1 on longevity-200gb-48h-verify-limited-tls-db-node-ae550088-2
```
write timeouts:
```
2018-07-18 20:33:19,839 remote           L0194 DEBUG| [172.16.99.73] [stderr] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2018-07-18 20:33:19,840 remote           L0194 DEBUG| [172.16.99.73] [stderr] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2018-07-18 20:33:19,840 remote           L0194 DEBUG| [172.16.99.73] [stderr] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
2018-07-18 20:33:19,844 remote           L0194 DEBUG| [172.16.99.73] [stderr] com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
```
sstable inactive read queue over loaded
```
2018-07-18 20:36:55,941 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:36:55 err    |  [shard 12] storage_proxy - Exception when communicating with 172.16.99.82: sstable inactive read queue over
loaded
2018-07-18 20:36:55,943 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:36:55 err    |  [shard 12] storage_proxy - Exception when communicating with 172.16.99.82: sstable inactive read queue over
loaded
2018-07-18 20:36:55,943 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:36:55 err    |  [shard 8] storage_proxy - Exception when communicating with 172.16.99.82: sstable inactive read queue overl
oaded
2018-07-18 20:36:55,944 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:36:55 err    |  [shard 12] storage_proxy - Exception when communicating with 172.16.99.82: sstable inactive read queue over
loaded
```
compaction failed bad alloc
```
2018-07-18 20:58:46,289 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:46 err    |  [shard 5] storage_proxy - exception during mutation write to 172.16.99.78: std::bad_alloc (std::bad_alloc)
2018-07-18 20:58:46,292 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:46 warning|  [shard 5] storage_proxy - Failed to apply mutation from 172.16.99.82#7: std::bad_alloc (std::bad_alloc)
2018-07-18 20:58:46,295 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:46 err    |  [shard 11] storage_proxy - Exception when communicating with 172.16.99.78: std::bad_alloc
2018-07-18 20:58:46,298 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:46 warning|  [shard 8] storage_proxy - Failed to apply mutation from 172.16.99.40#6: std::bad_alloc (std::bad_alloc)
2018-07-18 20:58:46,301 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:46 warning|  [shard 9] storage_proxy - Failed to apply mutation from 172.16.99.82#3: std::bad_alloc (std::bad_alloc)
2018-07-18 20:58:46,305 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:46 err    |  [shard 4] storage_proxy - exception during mutation write to 172.16.99.78: std::bad_alloc (std::bad_alloc)
2018-07-18 20:58:46,307 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:46 warning|  [shard 11] storage_proxy - Failed to apply mutation from 172.16.99.82#2: std::bad_alloc (std::bad_alloc)
2018-07-18 20:58:46,308 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:46 warning|  [shard 0] storage_proxy - Failed to apply mutation from 172.16.99.40#3: std::bad_alloc (std::bad_alloc)
2018-07-18 20:58:46,310 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:46 err    |  [shard 3] storage_proxy - exception during mutation write to 172.16.99.78: std::bad_alloc (std::bad_alloc)
2018-07-18 20:58:46,311 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:46 warning|  [shard 8] storage_proxy - Failed to apply mutation from 172.16.99.40#6: std::bad_alloc (std::bad_alloc)
2018-07-18 20:58:46,312 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:46 err    |  [shard 6] database - failed to write sstable /var/lib/scylla/data/keyspace1/standard1-8050a14089d411e8a5030
00000000001/keyspace1-standard1-ka-177596-Data.db: std::bad_alloc (std::bad_alloc)
...
2018-07-18 20:58:47,794 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:47 err    |  [shard 6] compaction_manager - compaction failed: std::runtime_error (SSTable reader found an exception when reading sstable /var/lib/scylla/data/keyspace1/standard1-8050a14089d411e8a503000000000001/keyspace1-standard1-ka-177274-Data.db : std::bad_alloc (std::bad_alloc))
...
2018-07-18 20:58:47,894 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:47 err    |  [shard 6] sstable - components_writer failed to close file: std::bad_alloc (std::bad_alloc)
2018-07-18 20:58:47,900 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:47 err    |  [shard 6] compaction_manager - compaction failed: std::bad_alloc (std::bad_alloc)
2018-07-18 20:58:47,901 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:47 info   |  [shard 6] compaction_manager - compaction task handler sleeping for 5 seconds
2018-07-18 20:58:47,902 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:47 err    |  [shard 6] compaction_manager - compaction failed: std::bad_alloc (std::bad_alloc)
2018-07-18 20:58:47,903 remote           L0194 DEBUG| [172.16.99.78] [stdout] Jul 18 20:58:47 info   |  [shard 6] compaction_manager - compaction task handler sleeping for 5 seconds
```
write failure and load crash
```
2018-07-18 20:58:48,176 remote           L0194 DEBUG| [172.16.99.73] [stderr] com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency QUORUM (2 responses we
re required but only 1 replica responded, 2 failed)
2018-07-18 20:58:48,176 remote           L0194 DEBUG| [172.16.99.73] [stderr] com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency QUORUM (2 responses we
re required but only 1 replica responded, 2 failed)
2018-07-18 20:58:48,177 remote           L0194 DEBUG| [172.16.99.73] [stderr] com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency QUORUM (2 responses we
re required but only 1 replica responded, 2 failed)
...
2018-07-18 20:59:43,360 remote           L0194 DEBUG| [172.16.99.73] [stdout] java.io.IOException: Operation x10 on key(s) [314c30343637354f3830]: Error executing: (WriteFailureException): Cassandra failure duri
ng write query at consistency QUORUM (2 responses were required but only 1 replica responded, 1 failed)
2018-07-18 20:59:43,361 remote           L0194 DEBUG| [172.16.99.73] [stdout] 
2018-07-18 20:59:43,361 remote           L0194 DEBUG| [172.16.99.73] [stdout]   at org.apache.cassandra.stress.Operation.error(Operation.java:135)
2018-07-18 20:59:43,361 remote           L0194 DEBUG| [172.16.99.73] [stdout]   at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:113)
2018-07-18 20:59:43,361 remote           L0194 DEBUG| [172.16.99.73] [stdout]   at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:98)
2018-07-18 20:59:43,361 remote           L0194 DEBUG| [172.16.99.73] [stdout]   at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:106)
2018-07-18 20:59:43,361 remote           L0194 DEBUG| [172.16.99.73] [stdout]   at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:261)
2018-07-18 20:59:43,362 remote           L0194 DEBUG| [172.16.99.73] [stdout]   at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:321)
```
read spike:
```
2018-07-18 20:59:07,674 remote           L0194 DEBUG| [172.16.99.73] [stderr] com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency ONE (1 responses were re
quired but only 0 replica responded)
2018-07-18 20:59:07,695 remote           L0194 DEBUG| [172.16.99.73] [stderr] com.datastax.driver.core.exceptions.ReadTimeoutException: Cassandra timeout during read query at consistency ONE (1 responses were re
quired but only 0 replica responded)

```
**coredump**

```
2018-07-18 21:23:55,972 remote           L0194 DEBUG| [172.16.99.78] [stdout] /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.aa
2018-07-18 21:23:55,972 remote           L0194 DEBUG| [172.16.99.78] [stdout] /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.ab
2018-07-18 21:23:55,972 remote           L0194 DEBUG| [172.16.99.78] [stdout] /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.ac
2018-07-18 21:23:55,972 remote           L0194 DEBUG| [172.16.99.78] [stdout] /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.ad
2018-07-18 21:23:55,973 remote           L0194 DEBUG| [172.16.99.78] [stdout] /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.ae
2018-07-18 21:23:55,973 remote           L0194 DEBUG| [172.16.99.78] [stdout] /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.af
2018-07-18 21:23:55,973 remote           L0194 DEBUG| [172.16.99.78] [stdout] /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.ag
2018-07-18 21:23:55,973 remote           L0194 DEBUG| [172.16.99.78] [stdout] /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.ah
2018-07-18 21:23:55,974 remote           L0194 DEBUG| [172.16.99.78] [stdout] /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.ai
2018-07-18 21:23:55,974 remote           L0194 DEBUG| [172.16.99.78] [stdout] /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.aj
2018-07-18 21:23:55,974 remote           L0194 DEBUG| [172.16.99.78] [stdout] /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.ak
2018-07-18 21:23:55,974 remote           L0194 DEBUG| [172.16.99.78] [stdout] /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.al
2018-07-18 21:23:55,974 remote           L0194 DEBUG| [172.16.99.78] [stdout] /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.am
2018-07-18 21:23:55,974 remote           L0194 DEBUG| [172.16.99.78] [stdout] /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.an
2018-07-18 21:23:55,974 remote           L0194 DEBUG| [172.16.99.78] [stdout] /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.ao
2018-07-18 21:23:55,974 remote           L0194 DEBUG| [172.16.99.78] [stdout] /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.ap
2018-07-18 21:23:55,975 cluster          L0448 INFO | Node longevity-200gb-48h-verify-limited-tls-db-node-ae550088-4 [52.202.118.182 | 172.16.99.78] (seed: None): Uploading coredump /var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.aa to upload.scylladb.com/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.aa
2018-07-18 21:23:55,975 remote           L0895 DEBUG| Remote [centos@172.16.99.78]: Running 'sudo curl --request PUT --upload-file '/var/lib/systemd/coredump/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.aa' 'upload.scylladb.com/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz/core.scylla.996.883ab7c447bb4f05a81c4719e5270d8f.2485.1531947542000000.gz.aa''


```
![image](https://user-images.githubusercontent.com/15847218/42957651-fde75cc6-8b8b-11e8-8e40-6d7163d81e03.png)

**Comment by slivne** [comment]
@harelassayag we need the logs from the "green" node that I hink on it you did the refresh - can you please confirm.

What I am looking at is to look at what happend on that node once refresh was requested - it seems it was "stuck" - I am not sure it crashed.

So which node was it that refresh happend on and can we get its logs

**Comment by harelassayag** [comment]
@slivne uploaded the combined logs of all the nodes here. [scylladb-users-upload.s3.amazonaws.com/3614/log.tar.gz](scylladb-users-upload.s3.amazonaws.com/3614/log.tar.gz)
I stall have the entire cluster live

**Comment by bhalevy** [comment]
@DoronArazii this issues hasn't reproduced again.
I suggest closing it for aging out

**Comment by DoronArazii** [comment]
Closing per @bhalevy suggestion.

/Cc @roydahan
