### ISSUE TITLE
ReshardingTest_nodes4_with_DateTieredCompactionStrategy.resharding_by_same_smp_test: Error running cassandra-stress: WARN  21:50:42,581 No schema agreement from live replicas

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#4388]
scylla version 77a0d5c5da46521d70a29df62338ee27f6b5a518

Seen in [dtest-release/75/testReport/resharding_test/ReshardingTest_nodes4_with_DateTieredCompactionStrategy/resharding_by_same_smp_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/75/testReport/resharding_test/ReshardingTest_nodes4_with_DateTieredCompactionStrategy/resharding_by_same_smp_test/):
```
Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release@2/scylla-dtest/resharding_test.py", line 207, in resharding_by_same_smp_test
    self._resharding_basic(self.smp, rows=1000, murmur3=self.murmur3)
  File "/jenkins/workspace/scylla-master/dtest-release@2/scylla-dtest/resharding_test.py", line 143, in _resharding_basic
    self._run_stress(op_cnt, stress_cmd)
  File "/jenkins/workspace/scylla-master/dtest-release@2/scylla-dtest/resharding_test.py", line 116, in _run_stress
    raise Exception('Error running cassandra-stress: {}'.format(res))

Error running cassandra-stress: WARN  21:50:42,581 No schema agreement from live replicas after 10 s. The schema may not be up to date on some nodes.
```

[node1.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/75/artifact/logs-release.2/1554069062325_resharding_test.ReshardingTest_nodes4_with_DateTieredCompactionStrategy.resharding_by_same_smp_test/node1.log):
```
INFO  2019-03-31 21:50:54,816 [shard 0] database - Schema version changed to cd0c77f3-900a-3b2a-bfce-4f80057c98ca
```

[node2.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/75/artifact/logs-release.2/1554069062325_resharding_test.ReshardingTest_nodes4_with_DateTieredCompactionStrategy.resharding_by_same_smp_test/node2.log):
```
INFO  2019-03-31 21:50:54,901 [shard 0] database - Schema version changed to cd0c77f3-900a-3b2a-bfce-4f80057c98ca
...
INFO  2019-03-31 21:50:55,272 [shard 0] database - Schema version changed to cd0c77f3-900a-3b2a-bfce-4f80057c98ca
INFO  2019-03-31 21:50:55,272 [shard 0] migration_manager - Schema merge with 127.0.77.3:0 completed
```

[node3.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/75/artifact/logs-release.2/1554069062325_resharding_test.ReshardingTest_nodes4_with_DateTieredCompactionStrategy.resharding_by_same_smp_test/node3.log):
```
INFO  2019-03-31 21:50:46,111 [shard 0] database - Schema version changed to cd0c77f3-900a-3b2a-bfce-4f80057c98ca
...
INFO  2019-03-31 21:50:55,001 [shard 0] database - Schema version changed to cd0c77f3-900a-3b2a-bfce-4f80057c98ca
INFO  2019-03-31 21:50:55,002 [shard 0] migration_manager - Schema merge with 127.0.77.1:0 completed
```

[node4.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/75/artifact/logs-release.2/1554069062325_resharding_test.ReshardingTest_nodes4_with_DateTieredCompactionStrategy.resharding_by_same_smp_test/node4.log):
```
INFO  2019-03-31 21:50:54,828 [shard 0] database - Schema version changed to cd0c77f3-900a-3b2a-bfce-4f80057c98ca
```
INFO  2019-03-31 21:50:55,320 [shard 0] database - Schema version changed to cd0c77f3-900a-3b2a-bfce-4f80057c98ca
INFO  2019-03-31 21:50:55,320 [shard 0] migration_manager - Schema merge with 127.0.77.3:0 completed
INFO  2019-03-31 21:50:55,320 [shard 0] migration_manager - Pulling schema from 127.0.77.3:0
...
INFO  2019-03-31 21:50:55,689 [shard 0] database - Schema version changed to cd0c77f3-900a-3b2a-bfce-4f80057c98ca
INFO  2019-03-31 21:50:55,690 [shard 0] migration_manager - Schema merge with 127.0.77.1:0 completed
...
INFO  2019-03-31 21:50:55,993 [shard 0] database - Schema version changed to cd0c77f3-900a-3b2a-bfce-4f80057c98ca
INFO  2019-03-31 21:50:55,994 [shard 0] migration_manager - Schema merge with 127.0.77.2:0 completed
...
INFO  2019-03-31 21:50:56,223 [shard 0] database - Schema version changed to cd0c77f3-900a-3b2a-bfce-4f80057c98ca
INFO  2019-03-31 21:50:56,224 [shard 0] migration_manager - Schema merge with 127.0.77.3:0 completed
```

**Comment by bhalevy** [comment]
We hit `Timed out waiting for server response` in [dtest-release/116/testReport/resharding_test/ReshardingTest_nodes4_with_DateTieredCompactionStrategy/resharding_by_same_smp_test](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/116/testReport/resharding_test/ReshardingTest_nodes4_with_DateTieredCompactionStrategy/resharding_by_same_smp_test/)
```
Connected to cluster: test, max pending requests per connection 128, max connections per host 8
Datatacenter: datacenter1; Host: /127.0.19.1; Rack: rack1
Datatacenter: datacenter1; Host: /127.0.19.2; Rack: rack1
Datatacenter: datacenter1; Host: /127.0.19.3; Rack: rack1
Datatacenter: datacenter1; Host: /127.0.19.4; Rack: rack1

stderr: java.lang.RuntimeException: Encountered exception creating schema
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:100)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:69)
	at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:228)
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:57)
	at org.apache.cassandra.stress.Stress.run(Stress.java:143)
	at org.apache.cassandra.stress.Stress.main(Stress.java:62)
Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/127.0.19.3:9042] Timed out waiting for server response
	at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:44)
	at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:26)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
	at org.apache.cassandra.stress.util.JavaDriverClient.execute(JavaDriverClient.java:188)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:89)
	... 5 more
Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/127.0.19.3:9042] Timed out waiting for server response
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onTimeout(RequestHandler.java:825)
	at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1392)
	at com.datastax.shaded.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
	at com.datastax.shaded.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
	at com.datastax.shaded.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
	at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

[node3.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/116/artifact/logs-release.2/1557157103987_resharding_test.ReshardingTest_nodes4_with_DateTieredCompactionStrategy.resharding_by_same_smp_test/node3.log):
```
INFO  2019-05-06 15:38:10,227 [shard 1] schema_tables - Creating keyspace keyspace1
INFO  2019-05-06 15:38:10,238 [shard 1] database - Schema version changed to fbfddbc2-1218-3034-bcde-86f7d224a11b
INFO  2019-05-06 15:38:11,577 [shard 0] migration_manager - Create new ColumnFamily: org.apache.cassandra.config.CFMetaData@0x6000013fdc00[cfId=f488be90-7014-11e9-8d08-000000000003,ksName=keyspace1,cfName=standard1,cfType=Standard,comparator=org.apache.cassandra.db.marshal.UTF8Type,comment=,readRepairChance=0,dcLocalReadRepairChance=0.1,gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.BytesType,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=key, type=org.apache.cassandra.db.marshal.BytesType, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=C0, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=C1, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=C2, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=C3, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=C4, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.DateTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=f488be91-7014-11e9-8d08-000000000003,droppedColumns={},collections={},indices={}]
INFO  2019-05-06 15:38:16,911 [shard 0] migration_manager - Requesting schema pull from 127.0.19.2:0
INFO  2019-05-06 15:38:16,912 [shard 0] migration_manager - Pulling schema from 127.0.19.2:0
```

**Comment by bhalevy** [comment]
Typo in PR auto-closed this issue by mistake...

**Comment by avikivity** [comment]
Since the issue is open, removing the backport candidate label.

**Comment by DoronArazii** [comment]
@bhalevy can we close it? (it seems like we didn't hit it for a couple of years)

**Comment by bhalevy** [comment]
yes, let's close as unreprodcible
