### ISSUE TITLE
IPv6 - routing in scylla AMI isn't configured properly

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylladb#5179]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20191015.7f1a2156c7a
ami-id: ami-0b6e2ffe315180ea3 (eu-west-1)

After starting the ami in VPC that support ipv6 and configured to automatically assigned ipv6, the IP is assigned correctly but isn't reachable.
Doing the same for clean centos works perfectly.

```
[centos@ip-10-0-232-44 ~]$ ifconfig -a
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 10.0.232.44  netmask 255.255.0.0  broadcast 10.0.255.255
        inet6 2a05:d018:223:f00:cbe8:f9d5:c1de:e0d3  prefixlen 128  scopeid 0x0<global>
        inet6 fe80::8c6:fff:fe77:ce18  prefixlen 64  scopeid 0x20<link>
        ether 0a:c6:0f:77:ce:18  txqueuelen 1000  (Ethernet)
        RX packets 229  bytes 28464 (27.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 229  bytes 25741 (25.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 6  bytes 416 (416.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6  bytes 416 (416.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[centos@ip-10-0-232-44 ~]$ ping6 2a05:d018:223:f00:db6a:f286:f06c:b40
connect: Network is unreachable

[centos@ip-10-0-232-44 ~]$ ip -6 r s
unreachable ::/96 dev lo metric 1024 pref medium
unreachable ::ffff:0.0.0.0/96 dev lo metric 1024 pref medium
unreachable 2002:a00::/24 dev lo metric 1024 pref medium
unreachable 2002:7f00::/24 dev lo metric 1024 pref medium
unreachable 2002:a9fe::/32 dev lo metric 1024 pref medium
unreachable 2002:ac10::/28 dev lo metric 1024 pref medium
unreachable 2002:c0a8::/32 dev lo metric 1024 pref medium
unreachable 2002:e000::/19 dev lo metric 1024 pref medium
2a05:d018:223:f00:cbe8:f9d5:c1de:e0d3 dev eth0 proto kernel metric 256 expires 387sec pref medium
unreachable 3ffe:ffff::/32 dev lo metric 1024 pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium

```

In order to workaround it one can do either:
1. configure the following in /etc/sysconfig/network-scripts/ifcfg-eth0

IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
(rebooting the node will reset the file because of cloud-init).

2. setting the routing (won't persist reboot as well):
`[centos@ip-10-0-232-44 ~]$ sudo ip r a 2a05:d018:223:f00::/64 dev eth0`

**Comment by amoskong** [comment]
If we have those two parameters:
- IPV6_AUTOCONF=yes
- IPV6_DEFROUTE=yes

Then we don't need to set the route manually.

**Comment by juliayakovlev** [comment]
When I created the instance using master ami ```ami-04ad5084bb452c5cf``` (scylla version ```666.development-0.20191015.7f1a2156c7a```), Scylla wasn't started.
Found error in the journalctl

```
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: [ERROR] EC2 is experiencing some issues and has not allocated all of the resources in under 10 minutes.
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: Aborting the clustering of this reservation. Please try again.
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: Traceback (most recent call last):
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: File "/opt/scylladb/scylla-ami/ds2_configure.py", line 524, in <module>
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: get_seed_list()
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: File "/opt/scylladb/scylla-ami/ds2_configure.py", line 331, in get_seed_list
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: exit_path('EC2 is experiencing some issues and has not allocated all of the resources in under 10 minutes.', '\n\nAborting the clustering of this reservatio
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: File "/opt/scylladb/scylla-ami/ds2_configure.py", line 55, in exit_path
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: raise AttributeError(errorMsg)
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: AttributeError: EC2 is experiencing some issues and has not allocated all of the resources in under 10 minutes.
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: Aborting the clustering of this reservation. Please try again.
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: Traceback (most recent call last):
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: File "/opt/scylladb/scylla-ami/libexec/scylla_ami_setup", line 30, in <module>
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: run('/opt/scylladb/scylla-ami/ds2_configure.py')
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: File "/opt/scylladb/scripts/scylla_util.py", line 334, in run
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr, env=scylla_env)
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 347, in check_call
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: raise CalledProcessError(retcode, cmd)
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal scylla_ami_setup[1624]: subprocess.CalledProcessError: Command '['/opt/scylladb/scylla-ami/ds2_configure.py']' returned non-zero exit status 1.
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal systemd[1]: scylla-ami-setup.service: main process exited, code=exited, status=1/FAILURE
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal systemd[1]: Failed to start Scylla AMI Setup.
Oct 17 11:02:18 ip-10-0-254-8.eu-west-1.compute.internal systemd[1]: Dependency failed for Scylla Server.
```
After using workaround, described above, Scylla was started.

**Comment by roydahan** [comment]
@slivne are we going to fix this somehow?

**Comment by roydahan** [comment]
It seems like there is a bug with cloud-init (https://bugs.launchpad.net/cloud-init/+bug/1808647) that was resolved very recently (not released in CentOs yet).

**Comment by roydahan** [comment]
@syuu1228,  Now, when switching to Amazon Linux 2, maybe there is an easy and working option to set the IPv6 routing persistent and fix this issue.

**Comment by roydahan** [comment]
It looks like the AMI that is based on Amazon Linux 2 won't need the workaround or any other fix.
After verifying this and merging we will be able to close this issue.

**Comment by slivne** [comment]
Move to Amazon Linux 2 was reverted - we still need to resolve this

**Comment by mykaul** [comment]
@roydahan - can you please assign someone to re-test this?

**Comment by roydahan** [comment]
There is no need to, it's very old issue that happened when we switched our AMI to Amazon Linux 2.
Our longevity-3h-ipv6-test passed many times since.
