### ISSUE TITLE
cql: forbid inserting NULL values into columns with collection types (via prepared statement)

### ISSUE THREAD

**Issue by ManManson** [scylladb/scylladb#5825]
*Installation details*
Scylla version (or git commit hash): 70d914ad5b35d9c6b93032427461d2dbac47561f

Assume the following test table setup:
```
CREATE TABLE IF NOT EXISTS t (
    k INT PRIMARY KEY,
    test list<boolean>
)
```

If we try to insert a `[null]` value into `test` using an ordinary non-prepared statement, we observe the following error message, which is expected:
```
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="null is not supported inside collections"
```

But if the same query with the same arguments is executed via prepared statement, Scylla does not validate the values properly and accepts to insert erroneous row into table:
```
insert_stmt = prepare_statement(session, '''
    INSERT INTO t (k, test) VALUES(?, ?)
'''.format(table_name=table_name))
# This succeeds, but should fail instead with "null is not supported inside collections"
session.execute(insert_stmt, [0, [None]])
```
This test case is available [here](https://github.com/scylladb/scylla-dtest/blob/3d1e9883a8e49981fa6b3aa1dec81bb8d67e30df/cql_prepared_test.py#L602).

What really happens is that an "empty" value (i.e. zero-length byte-array in serialized form) is inserted into a list instead of null (a special value with length specified as `-1`). This is represented in our code as one of possible distinct values of `cql3::raw_value_view`.

In such case Cassandra (3.11.5) fails with a NullPointerException:
```
20:58:28,574 conftest ERROR Unexpected error in node1 log, error: 
ERROR [MutationStage-3] 2020-02-17 20:58:28,480 StorageProxy.java:1404 - Failed to apply mutation locally : {}
java.lang.NullPointerException: null
        at org.apache.cassandra.db.rows.Cell$Serializer.serialize(Cell.java:187) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.rows.UnfilteredSerializer.writeComplexColumn(UnfilteredSerializer.java:275) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.rows.UnfilteredSerializer.lambda$serializeRowBody$0(UnfilteredSerializer.java:250) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.utils.btree.BTree.applyForwards(BTree.java:1221) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.utils.btree.BTree.apply(BTree.java:1176) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.rows.BTreeRow.apply(BTreeRow.java:172) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.rows.UnfilteredSerializer.serializeRowBody(UnfilteredSerializer.java:236) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.rows.UnfilteredSerializer.serialize(UnfilteredSerializer.java:205) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.rows.UnfilteredSerializer.serialize(UnfilteredSerializer.java:137) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.rows.UnfilteredSerializer.serialize(UnfilteredSerializer.java:125) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.rows.UnfilteredRowIteratorSerializer.serialize(UnfilteredRowIteratorSerializer.java:137) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.rows.UnfilteredRowIteratorSerializer.serialize(UnfilteredRowIteratorSerializer.java:92) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.partitions.PartitionUpdate$PartitionUpdateSerializer.serialize(PartitionUpdate.java:815) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.Mutation$MutationSerializer.serialize(Mutation.java:393) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.commitlog.CommitLog.add(CommitLog.java:239) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.Keyspace.applyInternal(Keyspace.java:593) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:470) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:227) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:232) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.db.Mutation.apply(Mutation.java:241) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.service.StorageProxy$8.runMayThrow(StorageProxy.java:1398) ~[apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.service.StorageProxy$LocalMutationRunnable.run(StorageProxy.java:2637) [apache-cassandra-3.11.5.jar:3.11.5]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_242]
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:165) [apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:137) [apache-cassandra-3.11.5.jar:3.11.5]
        at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:113) [apache-cassandra-3.11.5.jar:3.11.5]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_242]
```

What should be done here is that we need to make prepared and non-prepared statements behavior equal.

Allowing to execute such queries can lead to obscure bugs, such as https://github.com/scylladb/scylla/issues/5791. For example, this issue can manifest itself in many different ways under different circumstances: if executed from dtest/boost tests/cql_repl tests various values can become either `null` or `empty` while evaluating the statement.

And it turns out we don't have an adequate handling of such corner cases and testing all the combinations of interplay between nulls and empties can make proper testing impossible.

**WORKAROUND NOTES:** One probable way to deal with such discrepancies is to always treat "empty" values (zero-sized byte arrays) as nulls instead and get rid of "empty" value notion at all, only except for variable-length types (e.g. strings/byte-strings), where null<->empty distinction is still important.

**Comment by avikivity** [comment]
This is a driver bug. The documentation states that NULLs should be encoded as bytes with length -1, not empty values.

We should indeed reject empty values coming from CQL, but not convert them to NULLs.

**Comment by avikivity** [comment]
Wireshark decode shows a list of length 1, with a single empty element:

![image](https://user-images.githubusercontent.com/1017210/210150129-f4a3cdbe-710c-496e-b682-31b70b34bce2.png)

**Comment by nyh** [comment]
> This is a driver bug.

Interesting. Then I guess it should be fixed there (but we don't know which, if any, driver besides the Python one has this bug...).

> We should indeed reject empty values coming from CQL, but not convert them to NULLs.

I agree that for some type (like integer types) the empty value is weird and not useful, and we could have rejected it - though this would be a backward-incompatible change at this point (Cassandra and Scylla in the past allowed it, and although unlikely, users might be relying on it...). Other types like string do have a meaningful empty value and cannot be rejected - but the same driver bug would (if I understand correctly) replace NULL by an empty string - so it still needs to be fixed.

By the way, I have in test/cql-pytest/test_empty.py a bunch of tests for the weird "empty" concept. I conceded in a comment that "This is not an important behavior to preserve in modern CQL", but that the tests are useful because "we should probably be aware if we ever break it". Perhaps I should add more tests, like how empty values in lists are handled (you noticed that Cassandra even has a null-pointer-exception in that case).

**Comment by nyh** [comment]
I wrote tests that verified:
1. Both Cassandra and Scylla handle empty values in lists - both empty strings and empty int (inserted inline as `blobAsInt(0x)`)  - can be inserted to a list inline (non-prepared statement) and read correctly.
2. The empty string case also works well with a prepared statement.
3. For the empty int case, there is no official way (at least not that I could figure out) to cause the Python driver to insert an **empty** int. There is an unofficial, buggy way - using a None which driver seems to convert into an empty value instead of a null. When done this way, Scylla seems to work correctly (the empty int in the list can be read back, and as usual in the python driver appears as a None)  but Cassandra failes with a NullPointerException.
I'll consider sending a patch with these tests, although I'm not very happy about tests that rely on a weird driver bug.

**Comment by mykaul** [comment]
> This is a driver bug. The documentation states that NULLs should be encoded as bytes with length -1, not empty values.

Wireshark did not handle the -1 length in results, btw. Sent a patch (https://gitlab.com/wireshark/wireshark/-/merge_requests/9266 ) which coincidentally fixed the parsing for me.

**Comment by nyh** [comment]
Closing this issue because:
1. **empty** (not null) values are allowed in Scylla and Cassandra, and we don't want to stop allowing it.
2. It is a **driver** bug that a null the user sent is converted into an empty value - opened https://github.com/scylladb/python-driver/issues/201 but nobody's working on it (I'll report now also upstream).
