### ISSUE TITLE
sstableloader --ignore-missing-columns doesn't work

### ISSUE THREAD

**Issue by slivne** [scylladb/scylladb#6990]
reproducer

run on a single node

cqlsh 
```
CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE ks.tb (
    key int PRIMARY KEY,
    v1 int,
    v2 int,
    v3 int
)
insert INTO ks.tb (key, v1, v2, v3 ) VALUES (1,1,1,1);
insert INTO ks.tb (key, v1, v2, v3 ) VALUES (2,1,1,1);
insert INTO ks.tb (key, v1, v2, v3 ) VALUES (3,1,1,1);
```

```
nodetool flush
```

stop scylla

copy /var/lib/scylla/data /var/lib/scylla/data1

start scylla

cqlsh
```

CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE ks.tb (
    key int PRIMARY KEY,
    v1 int,
    v3 int
)
```

attempt to load sstables

```
sstableloader --nodes 172.17.0.2 --ignore-missing-columns v2 /var/lib/scylla/data1/ks/tb-12128600d81811eaa51d000000000007/ 
===== Using optimized driver!!! =====
WARN  19:29:00,421 dclocal_read_repair_chance and read_repair_chance table options have been deprecated and will be removed in version 4.0
java.lang.RuntimeException: Unknown column v2 during deserialization
	at org.apache.cassandra.db.SerializationHeader$Component.toHeader(SerializationHeader.java:321)
	at org.apache.cassandra.io.sstable.format.SSTableReader.openForBatch(SSTableReader.java:441)
	at com.scylladb.tools.BulkLoader.openFile(BulkLoader.java:1504)
	at com.scylladb.tools.BulkLoader.process(BulkLoader.java:1549)
	at com.scylladb.tools.BulkLoader.lambda$main$1(BulkLoader.java:1364)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: Unknown column v2 during deserialization
	at org.apache.cassandra.db.SerializationHeader$Component.toHeader(SerializationHeader.java:321)
	at org.apache.cassandra.io.sstable.format.SSTableReader.openForBatch(SSTableReader.java:441)
	at com.scylladb.tools.BulkLoader.openFile(BulkLoader.java:1504)
	at com.scylladb.tools.BulkLoader.process(BulkLoader.java:1549)
	at com.scylladb.tools.BulkLoader.lambda$main$1(BulkLoader.java:1364)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: Unknown column v2 during deserialization
	at org.apache.cassandra.db.SerializationHeader$Component.toHeader(SerializationHeader.java:321)
	at org.apache.cassandra.io.sstable.format.SSTableReader.openForBatch(SSTableReader.java:441)
	at com.scylladb.tools.BulkLoader.openFile(BulkLoader.java:1504)
	at com.scylladb.tools.BulkLoader.process(BulkLoader.java:1549)
	at com.scylladb.tools.BulkLoader.lambda$main$1(BulkLoader.java:1364)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
  0% done.        0 statements sent (in        0 batches,        0 failed).
       0 statements generated.
       0 cql rows processed in        0 partitions.
       0 cql rows and        0 partitions deleted.
       0 local and        0 remote counter shards where skipped.
```

**Comment by slivne** [comment]
trying to run ```--simulate``` also failed - lets fix the bugs and also add dtests to make sure this works

**Comment by elcallio** [comment]
See /scylladb/scylla-tools-java#193

**Comment by roydahan** [comment]
task created.

**Comment by slivne** [comment]
@elcallio is ```--simulate``` also fixed ?

**Comment by elcallio** [comment]
What do mean "is `--simulate` fixed"? It was never broken.

**Comment by juliayakovlev** [comment]
@slivne @elcallio 
When I ran sstableloader with 2 missed columns using command:

```
sstableloader -d 127.0.89.1 --ignore-missing-columns c2,c3 /tmp/tmpgjrz94sl/ks/cf
```

it failed with error:
```
===== Using optimized driver!!! =====
java.lang.RuntimeException: Unknown column c3 during deserializationailed).
	at org.apache.cassandra.db.SerializationHeader$Component.toHeader(SerializationHeader.java:321)
	at org.apache.cassandra.io.sstable.format.SSTableReader.openForBatch(SSTableReader.java:441)
	at com.scylladb.tools.BulkLoader.openFile(BulkLoader.java:1517)
	at com.scylladb.tools.BulkLoader.process(BulkLoader.java:1562)
	at com.scylladb.tools.BulkLoader.lambda$main$1(BulkLoader.java:1364)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Scenario:
1. CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
2. CREATE COLUMNFAMILY cf (key int, c1 varchar, c2 varchar, c3 varchar, PRIMARY KEY(key, c1))
3. Insert 10 rows
4. node.flush
5. Copy data files to the tmp (```/tmp/tmpgjrz94sl/ks/cf``` in my example)
6. Drop table and create again as ```CREATE COLUMNFAMILY cf (key varchar, c1 varchar, PRIMARY KEY(key, c1))``` - remove c2 and c3 columns
7. run sstableloader

If I ran same scenario but DROP the columns instead of table recreation - it successes 

If I run similar scenario, but with ONE missed column (not two) - it successes

**Comment by elcallio** [comment]
Wrong syntax. Partly because the command line parser lib is a bit ancient, but IIRC you have to write it like `-g c3 -g c3` (-g == --ignore-missing-columns)

**Comment by juliayakovlev** [comment]
> Wrong syntax. Partly because the command line parser lib is a bit ancient, but IIRC you have to write it like `-g c3 -g c3` (-g == --ignore-missing-columns)

Thanks, I'll check
But why if I run scenario like:
```
CREATE COLUMNFAMILY cf (key int, c1 varchar, c2 varchar, c3 varchar, PRIMARY KEY(key, c1))

ALTER TABLE cf DROP (c2, c3)

Run: sstableloader -d 127.0.89.1 --ignore-missing-columns c2,c3 /tmp/tmpgjrz94sl/ks/cf
```

it passed . What is the difference?

**Comment by elcallio** [comment]
Hm, I might be wrong about the arg parser (or the version thereof). 
The success/failure is probably due to the schema changes info available from the server. With a drop columns there is info available from schema tables that there once existed said columns. 
Which sstable format is the failing case using? It might be that we're hitting an mc/ka issue here.

**Comment by juliayakovlev** [comment]
> Hm, I might be wrong about the arg parser (or the version thereof).
> The success/failure is probably due to the schema changes info available from the server. With a drop columns there is info available from schema tables that there once existed said columns.
> Which sstable format is the failing case using? It might be that we're hitting an mc/ka issue here.

It's md

**Comment by elcallio** [comment]
Ugh, just command line parsing, just as I though. Your example will work fine with one column, but not two.

**Comment by elcallio** [comment]
See /scylladb/scylla-tools-java/pull/215
