### ISSUE TITLE
nodetool status: |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE]

### ISSUE THREAD

**Issue by asias** [scylladb/scylladb#702]
```
On a 10 nodes cluster, I saw:

[fedora@ip-172-30-0-19 ~]$ rpm -qa|grep scylla
scylla-server-development-20151221.5b09239.fc22.x86_64
scylla-jmx-1.0-20151218.7547953.fc22.noarch
scylla-tools-0.10-20151218.34e80ad.fc22.noarch

Failed to create parent directories for [/etc/scylla/cassandra.logdir_IS_UNDEFINED/system.log

[fedora@ip-172-30-0-17 scylla]$ nodetool status
03:37:30,128 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-tools.xml]
03:37:30,128 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
03:37:30,128 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
03:37:30,128 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/tmp/tmp.oRLz5xt4SC/logback.xml]
03:37:30,179 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
03:37:30,183 |-INFO in ReconfigureOnChangeFilter{invocationCounter=0} - Will scan for changes in [[/tmp/tmp.oRLz5xt4SC/logback.xml]] every 60 seconds.
03:37:30,183 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter
03:37:30,187 |-INFO in ch.qos.logback.classic.joran.action.JMXConfiguratorAction - begin
03:37:30,232 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
03:37:30,235 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
03:37:30,275 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@5c072e3f - Will use zip compression
03:37:30,302 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
03:37:30,319 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: cassandra.logdir_IS_UNDEFINED/system.log
03:37:30,319 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [cassandra.logdir_IS_UNDEFINED/system.log]
03:37:30,320 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Failed to create parent directories for [/etc/scylla/cassandra.logdir_IS_UNDEFINED/system.log]
03:37:30,321 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(cassandra.logdir_IS_UNDEFINED/system.log,true) call failed. java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/system.log (No such file or directory)
    at java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/system.log (No such file or directory)
    at  at java.io.FileOutputStream.open0(Native Method)
    at  at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at  at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at  at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:28)
    at  at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:150)
    at  at ch.qos.logback.core.FileAppender.start(FileAppender.java:108)
    at  at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:86)
    at  at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
    at  at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
    at  at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
    at  at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
    at  at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
    at  at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
    at  at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
    at  at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
    at  at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
    at  at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
    at  at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
    at  at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
    at  at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
    at  at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
    at  at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
    at  at org.apache.cassandra.utils.FBUtilities.<clinit>(FBUtilities.java:67)
    at  at org.apache.cassandra.tools.NodeTool.printHistory(NodeTool.java:233)
    at  at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:201)
03:37:30,321 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
03:37:30,322 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
03:37:30,324 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
03:37:30,325 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
03:37:30,325 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
03:37:30,325 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
03:37:30,326 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.thinkaurelius.thrift] to ERROR
03:37:30,326 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
03:37:30,326 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@149494d8 - Registering current configuration as safe fallback point

Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens  Owns    Host ID                               Rack
UN  172.30.0.26  120.93 KB  256     ?       24674e14-ebdc-4e56-a0be-f486d98d802b  rack1
UN  172.30.0.24  120.93 KB  256     ?       2a6f6d4f-feab-435f-80e0-b4251b2755e6  rack1
UN  172.30.0.25  120.93 KB  256     ?       bf591b1c-f0b8-4376-b5e5-9e34711b9534  rack1
UN  172.30.0.22  120.41 KB  256     ?       661c4ada-7faa-4268-850f-e94126aa1a12  rack1
UN  172.30.0.23  120.93 KB  256     ?       71fec3c8-baef-4022-bf14-f5ae1a9ac133  rack1
UN  172.30.0.20  120.93 KB  256     ?       846a27af-0055-48c7-9567-68eae8988a9e  rack1
UN  172.30.0.21  120.93 KB  256     ?       7b7b1900-b768-41b6-a46b-2fdc64832dd7  rack1
UN  172.30.0.18  120.41 KB  256     ?       8948b041-4600-4e73-9572-a9e4484c2db1  rack1
UN  172.30.0.19  120.93 KB  256     ?       5fa33776-ebbe-41e6-8a58-dd2ea6ce59d6  rack1
UN  172.30.0.17  120.93 KB  256     ?       1be8b319-0d65-4140-bab1-60f0712441bd  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

**Comment by slivne** [comment]
could it be that you were running cassandra-stress from the /etc/scylla directory and you did not have write permission to that directory ? 

I get the same with regular cassandra cassandra-stress when I do not have permission to write.

```
shlomi@localhost/$ ~/apache-cassandra-2.1.7//tools/bin/cassandra-stress write -mode cql3 native
09:40:16,899 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
09:40:16,899 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
09:40:16,899 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/home/shlomi/apache-cassandra-2.1.7/conf/logback.xml]
09:40:16,962 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
09:40:16,968 |-INFO in ReconfigureOnChangeFilter{invocationCounter=0} - Will scan for changes in [[/home/shlomi/apache-cassandra-2.1.7/conf/logback.xml]] every 60 seconds. 
09:40:16,968 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Adding ReconfigureOnChangeFilter as a turbo filter
09:40:16,976 |-INFO in ch.qos.logback.classic.joran.action.JMXConfiguratorAction - begin
09:40:17,038 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
09:40:17,042 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
09:40:17,073 |-INFO in ch.qos.logback.core.rolling.FixedWindowRollingPolicy@598067a5 - Will use zip compression
09:40:17,099 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:40:17,120 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: cassandra.logdir_IS_UNDEFINED/system.log
09:40:17,121 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [cassandra.logdir_IS_UNDEFINED/system.log]
09:40:17,121 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Failed to create parent directories for [/cassandra.logdir_IS_UNDEFINED/system.log]
09:40:17,122 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(cassandra.logdir_IS_UNDEFINED/system.log,true) call failed. java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/system.log (No such file or directory)
	at java.io.FileNotFoundException: cassandra.logdir_IS_UNDEFINED/system.log (No such file or directory)
	at 	at java.io.FileOutputStream.open0(Native Method)
	at 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at 	at ch.qos.logback.core.recovery.ResilientFileOutputStream.<init>(ResilientFileOutputStream.java:28)
	at 	at ch.qos.logback.core.FileAppender.openFile(FileAppender.java:150)
	at 	at ch.qos.logback.core.FileAppender.start(FileAppender.java:108)
	at 	at ch.qos.logback.core.rolling.RollingFileAppender.start(RollingFileAppender.java:86)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:96)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:317)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:196)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:182)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:128)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:107)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:295)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at 	at org.apache.cassandra.utils.FBUtilities.<clinit>(FBUtilities.java:66)
	at 	at org.apache.cassandra.db.marshal.TypeParser.getAbstractType(TypeParser.java:346)
	at 	at org.apache.cassandra.db.marshal.TypeParser.parse(TypeParser.java:90)
	at 	at org.apache.cassandra.stress.settings.SettingsColumn.<init>(SettingsColumn.java:72)
	at 	at org.apache.cassandra.stress.settings.SettingsColumn.<init>(SettingsColumn.java:56)
	at 	at org.apache.cassandra.stress.settings.SettingsColumn.get(SettingsColumn.java:183)
	at 	at org.apache.cassandra.stress.settings.StressSettings.get(StressSettings.java:257)
	at 	at org.apache.cassandra.stress.settings.StressSettings.parse(StressSettings.java:220)
	at 	at org.apache.cassandra.stress.Stress.main(Stress.java:58)
09:40:17,122 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:40:17,123 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
09:40:17,124 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:40:17,124 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
09:40:17,125 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
09:40:17,125 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
09:40:17,125 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.thinkaurelius.thrift] to ERROR
09:40:17,125 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.

```

**Comment by avikivity** [comment]
Is this issue still valid? I don't think I've ever seen anything similar.

**Comment by denesb** [comment]
Closing, we deprecated the java nodetool.
