### ISSUE TITLE
Load failed due cql_server exception  while processing connection: Invalid argument 

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#8009]
*Installation details*
Scylla version (or git commit hash): `4.4.rc1-0.20210131.fd868722d`
Cluster size: 4 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `-` (gce: eu-west-1)

Test: `longevity-1tb-7days-GCE-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-1TB-7days-authorization-and-tls-ssl.yaml] (https://github.com/scylladb/scylla-cluster-tests/blob/7bcf0e08f179facf6ebcbe03fff2b716a88065a6/test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl.yaml)

**Issue description**

Cassandra-stress load failed to run in the beginning of test (no nemesis were started) with error:
```
< t:2021-01-31 23:31:39,659 f:base.py         l:144  c:RemoteCmdRunner      p:ERROR > Error executing command: "echo TAG: loader_idx:0-cpu_idx:0-keyspace_idx:1; STRESS_TEST_MARKER=BNCCWUE0O6TCQ6LQJ0V0; cassandra-stress write         cl=QUORUM n=50000000   -schema keyspace=keyspace_zstd 'replication(factor=3) compression=ZstdCompressor    compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native compression=none     user=cassandra password=cassandra -rate threads=50 -pop seq=1..50000000 -log interval=5 -transport "truststore=/etc/scylla/ssl_conf/client/cacerts.jks truststore-password=cassandra" -node 10.142.0.94 -errors skip-unsupported-columns"; Exit status: 1
< t:2021-01-31 23:31:39,659 f:base.py         l:146  c:RemoteCmdRunner      p:DEBUG > STDOUT: , max connections per host 8
< t:2021-01-31 23:31:39,659 f:base.py         l:146  c:RemoteCmdRunner      p:DEBUG > Datatacenter: us-east1; Host: /10.142.0.124; Rack: c
< t:2021-01-31 23:31:39,659 f:base.py         l:146  c:RemoteCmdRunner      p:DEBUG > Datatacenter: us-east1; Host: /10.142.0.94; Rack: c
< t:2021-01-31 23:31:39,659 f:base.py         l:146  c:RemoteCmdRunner      p:DEBUG > Datatacenter: us-east1; Host: /10.142.0.126; Rack: c
< t:2021-01-31 23:31:39,659 f:base.py         l:146  c:RemoteCmdRunner      p:DEBUG > Datatacenter: us-east1; Host: /10.142.0.127; Rack: c
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG > STDERR: java.lang.RuntimeException: Encountered exception creating schema
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG >   at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:100)
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG >   at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:69)
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG >   at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:228)
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG >   at org.apache.cassandra.stress.StressAction.run(StressAction.java:58)
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG >   at org.apache.cassandra.stress.Stress.run(Stress.java:143)
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG >   at org.apache.cassandra.stress.Stress.main(Stress.java:62)
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG > Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.142.0.126:9042] Timed out waiting for server response
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG >   at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:43)
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG >   at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:25)
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG >   at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG >   at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:293)
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG >   at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG >   at org.apache.cassandra.stress.util.JavaDriverClient.execute(JavaDriverClient.java:188)
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG >   at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:89)
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG >   ... 5 more
< t:2021-01-31 23:31:39,660 f:base.py         l:148  c:RemoteCmdRunner      p:DEBUG > Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.142.0.126:9042] Timed out waiting for server response
```

Timed out waiting for response from ```10.142.0.126```. It's node 3. Exception in its log in the same time:
```
Jan 31 23:31:40 longevity-tls-1tb-7d-4-4-db-node-f02c0c36-0-3 scylla[4746]:  [shard 9] schema_tables - Creating keyspace_deflate.standard1 id=705f5590-641c-11eb-9305-000000000001 version=90d47a6e-7ac8-349b-931f-
3bc1c39c0b87
Jan 31 23:31:40 longevity-tls-1tb-7d-4-4-db-node-f02c0c36-0-3 scylla[4746]:  [shard 9] schema_tables - Schema version changed to aee4c4d7-7367-30a4-9532-a12d6abd013b
Jan 31 23:31:40 longevity-tls-1tb-7d-4-4-db-node-f02c0c36-0-3 scylla[4746]:  [shard 1] compaction - [Compact system_schema.computed_columns 78354130-641c-11eb-a6f5-00000000000a] Compacted 2 sstables to []. 10kB 
to 0 bytes (~0% of original) in 32ms = 0 bytes/s. ~256 total partitions merged to 0.
Jan 31 23:31:40 longevity-tls-1tb-7d-4-4-db-node-f02c0c36-0-3 scylla[4746]:  [shard 6] cql_server - exception while processing connection: seastar::nested_exception: std::system_error (error system:22, Invalid a
rgument) (while cleaning up after std::system_error (error system:22, Invalid argument))
Jan 31 23:31:40 longevity-tls-1tb-7d-4-4-db-node-f02c0c36-0-3 scylla[4746]:  [shard 6] cql_server - exception while processing connection: seastar::nested_exception: std::system_error (error system:22, Invalid a
rgument) (while cleaning up after std::system_error (error system:22, Invalid argument))
Jan 31 23:31:40 longevity-tls-1tb-7d-4-4-db-node-f02c0c36-0-3 scylla[4746]:  [shard 6] cql_server - exception while processing connection: seastar::nested_exception: std::system_error (error system:22, Invalid argument) (while cleaning up after std::system_error (error system:22, Invalid argument))
```

Same exception on the all nodes in this time

Restore Monitor Stack command: `$ hydra investigate show-monitor f02c0c36-2f2a-4e9b-97c4-028a64e8ef96`
Show all stored logs command: `$ hydra investigate show-logs f02c0c36-2f2a-4e9b-97c4-028a64e8ef96`

Test id: `f02c0c36-2f2a-4e9b-97c4-028a64e8ef96`

Logs:

db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/f02c0c36-2f2a-4e9b-97c4-028a64e8ef96/20210131_235045/db-cluster-f02c0c36.zip](https://cloudius-jenkins-test.s3.amazonaws.com/f02c0c36-2f2a-4e9b-97c4-028a64e8ef96/20210131_235045/db-cluster-f02c0c36.zip)

loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/f02c0c36-2f2a-4e9b-97c4-028a64e8ef96/20210131_235045/loader-set-f02c0c36.zip](https://cloudius-jenkins-test.s3.amazonaws.com/f02c0c36-2f2a-4e9b-97c4-028a64e8ef96/20210131_235045/loader-set-f02c0c36.zip)

sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/f02c0c36-2f2a-4e9b-97c4-028a64e8ef96/20210131_235045/sct-runner-f02c0c36.zip](https://cloudius-jenkins-test.s3.amazonaws.com/f02c0c36-2f2a-4e9b-97c4-028a64e8ef96/20210131_235045/sct-runner-f02c0c36.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.4/job/longevity/job/longevity-1tb-7days-GCE-test/3/)

**Comment by slivne** [comment]
not sure what is the source - but we are not able to close connections of cql for some reason - lets try to make the closing nicer and have the error more meanigfull if possible,

**Comment by kostja** [comment]
https://github.com/scylladb/scylla-enterprise/issues/1937 fixed in the open source and enterprise repositories.
