### ISSUE TITLE
Semaphore timed out and repair failure on CorruptThenRepair nemesis

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylladb#8545]
failure scenario:
1. started a nemesis of corrupt-then-repair on node-7 - deleting some sstables while node down.
```
< t:2021-04-11 07:43:55,417 f:nemesis.py      l:821  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method destroy_data_then_repair
< t:2021-04-11 07:43:55,418 f:nemesis.py      l:493  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Set current_disruption -> CorruptThenRepair Node longevity-cdc-100gb-4h-4-3-db-node-467c0dbf-7 [13.51.108.139 | 10.0.1.249] (seed: False)
```
2. started getting a lot of semaphore timeouts for a lot of time.
```
< t:2021-04-11 08:24:51,770 f:cluster.py      l:1356 c:sdcm.cluster         p:DEBUG > 2021-04-11T08:24:41+00:00  longevity-cdc-100gb-4h-4-3-db-node-467c0dbf-7 !ERR     | scylla: [shard 13] storage_proxy - exception during mutation write to 10.0.1.249: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 5->13 semaphore)
```
3. node-7 started a repair when it is up, then repair failed with error:
```
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during UNLOGGED_BATCH write query at consistency QUORUM (2 replica were required but only 0 acknowledged the write)
error: Repair job has failed with the error message: [2021-04-11 08:26:52,640] Repair session 2 failed
```

*Installation details*
Scylla version (or git commit hash): `4.3.3-0.20210408.28f5e0bd2 with build-id e15c01c2027d60ca12ad9dcb04f1fa295f42105e`
Cluster size: 6 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0a0b3a48cf8132551` (aws: eu-north-1)

Test: longevity-cdc-100gb-4h-test
Test name: longevity_test.LongevityTest.test_custom_time
Test config file(s):
- [longevity-cdc-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d743c85b8327aee48e9ed6fe618973fa871d8a25/test-cases/longevity/longevity-cdc-100gb-4h.yaml)

**Issue description**

====================================

PUT ISSUE DESCRIPTION HERE

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 467c0dbf-b44f-4d38-9eca-82174126ad5a`
Show all stored logs command: `$ hydra investigate show-logs 467c0dbf-b44f-4d38-9eca-82174126ad5a`

Test id: `467c0dbf-b44f-4d38-9eca-82174126ad5a`

Logs:
prometheus - [https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/prometheus_snapshot_20210411_084433.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/prometheus_snapshot_20210411_084433.tar.gz)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/20210411_083458/grafana-screenshot-overview-20210411_083459-longevity-cdc-100gb-4h-4-3-monitor-node-467c0dbf-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/20210411_083458/grafana-screenshot-overview-20210411_083459-longevity-cdc-100gb-4h-4-3-monitor-node-467c0dbf-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/20210411_083458/grafana-screenshot-scylla-per-server-metrics-nemesis-20210411_083840-longevity-cdc-100gb-4h-4-3-monitor-node-467c0dbf-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/20210411_083458/grafana-screenshot-scylla-per-server-metrics-nemesis-20210411_083840-longevity-cdc-100gb-4h-4-3-monitor-node-467c0dbf-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/20210411_084454/grafana-screenshot-overview-20210411_084454-longevity-cdc-100gb-4h-4-3-monitor-node-467c0dbf-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/20210411_084454/grafana-screenshot-overview-20210411_084454-longevity-cdc-100gb-4h-4-3-monitor-node-467c0dbf-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/20210411_084454/grafana-screenshot-scylla-per-server-metrics-nemesis-20210411_084804-longevity-cdc-100gb-4h-4-3-monitor-node-467c0dbf-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/20210411_084454/grafana-screenshot-scylla-per-server-metrics-nemesis-20210411_084804-longevity-cdc-100gb-4h-4-3-monitor-node-467c0dbf-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/20210411_085546/db-cluster-467c0dbf.zip](https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/20210411_085546/db-cluster-467c0dbf.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/20210411_085546/loader-set-467c0dbf.zip](https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/20210411_085546/loader-set-467c0dbf.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/20210411_085546/monitor-set-467c0dbf.zip](https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/20210411_085546/monitor-set-467c0dbf.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/20210411_085546/sct-runner-467c0dbf.zip](https://cloudius-jenkins-test.s3.amazonaws.com/467c0dbf-b44f-4d38-9eca-82174126ad5a/20210411_085546/sct-runner-467c0dbf.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.3/job/longevity/job/longevity-cdc-100gb-4h-test/52/)

```
Test details
Test: longevity_test.LongevityTest.test_custom_time
Build number: 52
Backend: aws: eu-north-1
Test-id: 467c0dbf-b44f-4d38-9eca-82174126ad5a
Start time: 2021-04-11 06:54:31
End time: 2021-04-11 08:44:54
Started by user: timer
Test result
FAILED
System under test
Scylla version: 4.3.3-0.20210408.28f5e0bd2 with build-id e15c01c2027d60ca12ad9dcb04f1fa295f42105e (ami-0a0b3a48cf8132551)
Instance type: i3.4xlarge
Number of scylladb nodes: 6
Nemesis Details

Name | Count | Runs | Failures
-- | -- | -- | --
DecommissionStreamingErr | 1 | nodestartenddurationNode longevity-cdc-100gb-4h-4-3-db-node-467c0dbf-6 [13.51.159.188 \| 10.0.0.53] (seed: False)2021-04-11 07:00:172021-04-11 07:36:392181 | Node longevity-cdc-100gb-4h-4-3-db-node-467c0dbf-6 [13.51.159.188 \| 10.0.0.53] (seed: False) | 2021-04-11 07:00:17 | 2021-04-11 07:36:39 | 2181 | nodestartenddurationerror

Node longevity-cdc-100gb-4h-4-3-db-node-467c0dbf-6 [13.51.159.188 \| 10.0.0.53] (seed: False) | 2021-04-11 07:00:17 | 2021-04-11 07:36:39 | 2181

CorruptThenRepair | 1 | nodestartendduration | nodestartenddurationerrorNode longevity-cdc-100gb-4h-4-3-db-node-467c0dbf-7 [13.51.108.139 \| 10.0.1.249] (seed: False)2021-04-11 07:43:552021-04-11 08:26:522577Encountered a bad command exit code! Command: '/usr/bin/nodetool repair ' Exit code: 2 Stdout: Using /etc/scylla/scylla.yaml as the config file [2021-04-11 07:46:54,367] Starting repair command #1, repairing 1 ranges for keyspace system_traces (parallelism=SEQUENTIAL, full=true) [2021-04-11 07:46:58,488] Repair session 1 [2021-04-11 07:46:58,491] Repair session 1 finished [2021-04-11 07:46:58,574] Starting repair command #2, repairing 1 ranges for keyspace cdc_test (parallelism=SEQUENTIAL, full=true) [2021-04-11 08:26:52,640] Repair session 2 failed [2021-04-11 08:26:52,641] Repair session 2 finished Stderr: error: Repair job has failed with the error message: [2021-04-11 08:26:52,640] Repair session 2 failed -- StackTrace -- java.lang.RuntimeException: Repair job has failed with the error message: [2021-04-11 08:26:52,640] Repair session 2 failed at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124) at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77) at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583) at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533) at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452) at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108) | Node longevity-cdc-100gb-4h-4-3-db-node-467c0dbf-7 [13.51.108.139 \| 10.0.1.249] (seed: False) | 2021-04-11 07:43:55 | 2021-04-11 08:26:52 | 2577 | Encountered a bad command exit code! Command: '/usr/bin/nodetool repair ' Exit code: 2 Stdout: Using /etc/scylla/scylla.yaml as the config file [2021-04-11 07:46:54,367] Starting repair command #1, repairing 1 ranges for keyspace system_traces (parallelism=SEQUENTIAL, full=true) [2021-04-11 07:46:58,488] Repair session 1 [2021-04-11 07:46:58,491] Repair session 1 finished [2021-04-11 07:46:58,574] Starting repair command #2, repairing 1 ranges for keyspace cdc_test (parallelism=SEQUENTIAL, full=true) [2021-04-11 08:26:52,640] Repair session 2 failed [2021-04-11 08:26:52,641] Repair session 2 finished Stderr: error: Repair job has failed with the error message: [2021-04-11 08:26:52,640] Repair session 2 failed -- StackTrace -- java.lang.RuntimeException: Repair job has failed with the error message: [2021-04-11 08:26:52,640] Repair session 2 failed at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124) at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77) at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583) at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533) at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452) at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)


Node longevity-cdc-100gb-4h-4-3-db-node-467c0dbf-7 [13.51.108.139 \| 10.0.1.249] (seed: False) | 2021-04-11 07:43:55 | 2021-04-11 08:26:52 | 2577 | Encountered a bad command exit code! Command: '/usr/bin/nodetool repair ' Exit code: 2 Stdout: Using /etc/scylla/scylla.yaml as the config file [2021-04-11 07:46:54,367] Starting repair command #1, repairing 1 ranges for keyspace system_traces (parallelism=SEQUENTIAL, full=true) [2021-04-11 07:46:58,488] Repair session 1 [2021-04-11 07:46:58,491] Repair session 1 finished [2021-04-11 07:46:58,574] Starting repair command #2, repairing 1 ranges for keyspace cdc_test (parallelism=SEQUENTIAL, full=true) [2021-04-11 08:26:52,640] Repair session 2 failed [2021-04-11 08:26:52,641] Repair session 2 finished Stderr: error: Repair job has failed with the error message: [2021-04-11 08:26:52,640] Repair session 2 failed -- StackTrace -- java.lang.RuntimeException: Repair job has failed with the error message: [2021-04-11 08:26:52,640] Repair session 2 failed at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124) at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77) at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583) at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533) at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452) at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)

```

**Comment by roydahan** [comment]
@slivne this is for 4.3.3, I don't know if it's a regression or not.

**Comment by eliransin** [comment]
@slivne ping

**Comment by slivne** [comment]
we have this messages 

```
2021-04-11T07:51:00+00:00  longevity-cdc-100gb-4h-4-3-db-node-467c0dbf-7 !WARNING | scylla: [shard 10] repair - repair id [id=2, uuid=f237289d-1e34-49e7-99f5-c99dc895f68c] on shard 10, keyspace=cdc_test, cf=test_table_preimage_postimage_scylla_cdc_log, range=(-4111862039702374379, -4100043861521190796], got error in row level repair: std::runtime_error (get_full_row_hashes: Peer failed to process)
2021-04-11T07:51:00+00:00  longevity-cdc-100gb-4h-4-3-db-node-467c0dbf-7 !WARNING | scylla: [shard 10] repair - repair id [id=2, uuid=f237289d-1e34-49e7-99f5-c99dc895f68c] on shard 10, keyspace=cdc_test, cf=test_table_preimage, range=(-4531445297508685156, -4520932050125351506], got error in row level repair: std::runtime_error (get_repair_meta: repair_meta_id 58319 for node 10.0.1.249 does not exist)
2021-04-11T07:51:00+00:00  longevity-cdc-100gb-4h-4-3-db-node-467c0dbf-7 !WARNING | scylla: [shard 10] repair - repair id [id=2, uuid=f237289d-1e34-49e7-99f5-c99dc895f68c] on shard 10, keyspace=cdc_test, cf=test_table_postimage_scylla_cdc_log, range=(-4369837176001198601, -4356194356880002302], got error in row level repair: std::runtime_error (get_repair_meta: repair_meta_id 58141 for node 10.0.1.249 does not exist)
2021-04-11T07:51:00+00:00  longevity-cdc-100gb-4h-4-3-db-node-467c0dbf-7 !INFO    | scylla: [shard 10] repair - Repair 215 out of 791 ranges, id=[id=2, uuid=f237289d-1e34-49e7-99f5-c99dc895f68c], shard=10, keyspace=cdc_test, table={test_table_preimage_postimage, test_table_preimage_postimage_scylla_cdc_log, test_table_postimage_scylla_cdc_log, test_table_postimage, test_table_scylla_cdc_log, test_table_preimage_scylla_cdc_log, test_table_preimage, test_table}, range=(-4005258384176051274, -4001886490634572558]
2021-04-11T07:51:00+00:00  longevity-cdc-100gb-4h-4-3-db-node-467c0dbf-7 !WARNING | scylla: [shard 10] repair - repair id [id=2, uuid=f237289d-1e34-49e7-99f5-c99dc895f68c] on shard 10, keyspace=cdc_test, cf=test_table_scylla_cdc_log, range=(-4424336865558366236, -4410191572133642932], got error in row level repair: std::runtime_error (get_repair_meta: repair_meta_id 58300 for node 10.0.1.249 does not exist)
2021-04-11T07:51:00+00:00  longevity-cdc-100gb-4h-4-3-db-node-467c0dbf-7 !WARNING | scylla: [shard 10] repair - repair id [id=2, uuid=f237289d-1e34-49e7-99f5-c99dc895f68c] on shard 10, keyspace=cdc_test, cf=test_table_preimage_postimage, range=(-4024555565547848140, -4005258384176051274], got error in row level repair: std::runtime_error (get_row_diff: Peer failed to process)
```

this seems simillar to https://github.com/scylladb/scylla/issues/7570 - that we hit in 4.4 testing and did not backport to 4.3.

So this is not a regression, its bad and we need to fix it - yet lets see its better in 4.4 testing and then backport to 4.3 - not before we pass in 4.4
