### ISSUE TITLE
Add support for Cassandra NB format (Cassandra 4.0)

### ISSUE THREAD

**Issue by slivne** [scylladb/scylladb#8583]
Cassandra 4 introduced the NA format which is a set of changes

- I collected the following - yet it should certainly be double checked.

One of the changes we have introduced is the ability to stream information internally in scylla at nodetool refresh instead of using the sstableloader - as such it would be appropriate for scylla to support the NA format naively - even only for reads

```
        // na (4.0.0): uncompressed chunks, pending repair session, isTransient, checksummed sstable metadata file, new Bloomfilter format

CASSANDRA-9425 Make node-local schema fully immutable
CASSANDRA-9143 Fix consistency of incrementally repaired data across replicas
CASSANDRA-10520 Compressed writer and reader should support non-compressed data.
CASSANDRA-13420 Pending repair info was added in 4.0
CASSANDRA-13321 Add a checksum component for the sstable metadata (-Statistics.db) file
CASSANDRA-9067 BloomFilter serialization format should not change byte ordering
CASSANDRA-14404 Transient Replication & Cheap Quorums: Decouple storage requirements from consensus group size using incremental repair

```

**Comment by slivne** [comment]
@avikivity - need your input on this

I want to break it into three parts

- tools (sstableloader)
- reading na (nodetool refresh - Asias new feature in 4.5)
- read/write - and this is something I think we can discuss if we want an support.

**Comment by fee-mendes** [comment]
@slivne FYI -- NA format is C* 4 format up to release candidate.
Starting with C* 4.0 GA, the new format is NB. See [here](https://github.com/apache/cassandra/blob/trunk/src/java/org/apache/cassandra/io/sstable/format/big/BigFormat.java#L118:L128).

```
 // na (4.0-rc1): uncompressed chunks, pending repair session, isTransient, checksummed sstable metadata file, new Bloomfilter format
 // nb (4.0.0): originating host id
```

Currently, both sstableloader and nodetool refresh fail badly with NA format:

```
# nodetool refresh ks tbl
nodetool: Scylla API server HTTP POST to URL '/storage_service/sstables/ks' failed: Failed to load new sstables: sstables::malformed_sstable_exception (invalid version for file na-1-big-CompressionInfo.db. Name doesn't match any known version.)
```

```
# sstableloader -d 127.0.0.1 ks/tbl-b7dc81e0306311ec9779b50119569f33/
===== Using optimized driver!!! =====
java.lang.ArrayIndexOutOfBoundsException: Index 640228101 out of bounds for length 4
	at org.apache.cassandra.io.sstable.metadata.MetadataSerializer.deserialize(MetadataSerializer.java:114)
	at org.apache.cassandra.io.sstable.metadata.MetadataSerializer.deserialize(MetadataSerializer.java:93)
	at org.apache.cassandra.io.sstable.format.SSTableReader.openForBatch(SSTableReader.java:416)
	at com.scylladb.tools.BulkLoader.openFile(BulkLoader.java:1525)
	at com.scylladb.tools.BulkLoader.process(BulkLoader.java:1570)
	at com.scylladb.tools.BulkLoader.lambda$main$1(BulkLoader.java:1367)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
  0% done.        0 statements sent (in        0 batches,        0 failed).
       0 statements generated.
       0 cql rows processed in        0 partitions.
       0 cql rows and        0 partitions deleted.
       0 local and        0 remote counter shards where skipped.
```

**Comment by dorlaor** [comment]
@asias @denesb so what's your call regarding this format?

**Comment by asias** [comment]
> It's not a good idea to expose the internal RPC to clients. It's not authenticated and it has a separate deprecation schedule.

Load and Stream feature can load any sstables scylla supports. We could have a HTTP API to stream files to scylla instead of scp to a node. Then we trigger load and stream to distribute the data to scylla nodes.

So that we can  have lightweight external tool or even a simple script to load sstables to scylla. 

I think we should support 4.0 format at least for read otherwise its hard to migrate 4.0 clusters.

**Comment by dorlaor** [comment]
Ok, load and stream is indeed a simple way to load data to Scylla.
What's special about the .NA format - is there anything in the file we need
to add

**Comment by asias** [comment]
> Ok, load and stream is indeed a simple way to load data to Scylla. What's special about the .NA format - is there anything in the file we need to add

Avi mentioned [here]( https://github.com/scylladb/scylla/issues/8583#issuecomment-946523129) that the NA change is small.  No change is needed from load and stream part.

**Comment by dorlaor** [comment]
Well, I just want to assign it to someone (Botond or Asias or another volunteer) to get it done

**Comment by asias** [comment]
> Well, I just want to assign it to someone (Botond or Asias or another volunteer) to get it done

It is more efficient to assign to people who is familiar with the sstable formats. So I am not volunteering here.

**Comment by denesb** [comment]
I think we should ask @bhalevy to volunteer someone from our team.

**Comment by bhalevy** [comment]
my plan is for @cmm to work on this after #9869

**Comment by denesb** [comment]
We already need to update our java tools for the `ME` format (https://github.com/scylladb/scylla-tools-java/issues/291), we might as well update it from a C* version which also supports `NB`, to kill two birds with one stone.

**Comment by tzach** [comment]
Adding Doc label as this feature impact docs

**Comment by roydahan** [comment]
Do we still not supporting the NB format?

**Comment by denesb** [comment]
> Do we still not supporting the NB format?

Yes, still not supported.

**Comment by danielvargasmey007** [comment]
Do we still not supporting the NB format in 2024?
Is there any way to apply a snapshot of Cassandra(>= 4.0) in the latest versions of Scylla?  

Thanks in advance.

**Comment by dorlaor** [comment]
Hmm, let me check if there is a workaround, it's time to support it

**Comment by bhalevy** [comment]
@regevran please add to your queue.
It is a good issue to get familiarized with the sstables module code
and it's off the critical path.

**Comment by bhalevy** [comment]
@denesb please see if and how the NB related changes interact with the activities in your team, in particular:
```
CASSANDRA-13420 Pending repair info was added in 4.0
CASSANDRA-13321 Add a checksum component for the sstable metadata (-Statistics.db) file
CASSANDRA-9067 BloomFilter serialization format should not change byte ordering
```

**Comment by denesb** [comment]
> CASSANDRA-13420 Pending repair info was added in 4.0

This is a comment change basically.

> CASSANDRA-13321 Add a checksum component for the sstable metadata (-Statistics.db) file

We want to go all the way and add checksums for all components.

> CASSANDRA-9067 BloomFilter serialization format should not change byte ordering

@lkshminarayanan can you please check https://issues.apache.org/jira/browse/CASSANDRA-9067 and see if we have the same reversing?

**Comment by lkshminarayanan** [comment]
> > CASSANDRA-13420 Pending repair info was added in 4.0
> 
> This is a comment change basically.
> 
> > CASSANDRA-13321 Add a checksum component for the sstable metadata (-Statistics.db) file
> 
> We want to go all the way and add checksums for all components.
> 
> > CASSANDRA-9067 BloomFilter serialization format should not change byte ordering
> 
> @lkshminarayanan can you please check https://issues.apache.org/jira/browse/CASSANDRA-9067 and see if we have the same reversing?

Bloom filter is written from and read into a Chunked Vector and yes, we flip the bytes to the Big Endian format when [writing](https://github.com/scylladb/scylladb/blob/15f8046fcb771e496d7e0db36ff2051c100d2593/sstables/writer.hh#L337) to and [reading](https://github.com/scylladb/scylladb/blob/15f8046fcb771e496d7e0db36ff2051c100d2593/sstables/sstables.cc#L357) from chunked vector to disk. It is efficient than the old Cassandra implementation though as our implementation uses `__builtin_bswap`s to flip them. 

We can do what CASSANDRA-9067 did - skip the flipping when writing the filter and while reading decide whether to flip or not based on the version number. We just have to make sure updating how a Chunked Vector is written/read from disk doesn't affect any components other than the filter.
