### ISSUE TITLE
"Unexpected error while querying" c-s error during `scylla-server` service restart and after the restart was competed

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylladb#9460]
*Installation details*
Kernel version: `5.11.0-1020-gcp`
Scylla version (or git commit hash): `4.5.0-0.20211006.47be33a10`
Cluster size: 6 nodes (n1-highmem-16)
Scylla running with shards number (live nodes):
   longevity-10gb-3h-4-5-db-node-526b36bd-0-1 (34.75.206.9 | 10.142.0.100): 14 shards
   longevity-10gb-3h-4-5-db-node-526b36bd-0-3 (35.185.127.172 | 10.142.0.106): 14 shards
   longevity-10gb-3h-4-5-db-node-526b36bd-0-4 (35.237.155.114 | 10.142.0.116): 14 shards
   longevity-10gb-3h-4-5-db-node-526b36bd-0-5 (34.75.71.56 | 10.142.0.120): 14 shards
   longevity-10gb-3h-4-5-db-node-526b36bd-0-8 (34.74.149.21 | 10.142.0.10): 14 shards
   longevity-10gb-3h-4-5-db-node-526b36bd-0-9 (35.243.144.226 | 10.142.0.12): 14 shards
   longevity-10gb-3h-4-5-db-node-526b36bd-0-10 (35.243.179.67 | 10.142.0.13): 14 shards
Scylla running with shards number (terminated nodes):
   longevity-10gb-3h-4-5-db-node-526b36bd-0-6 (34.75.53.67 | 10.142.0.127): 14 shards
   longevity-10gb-3h-4-5-db-node-526b36bd-0-2 (35.237.136.43 | 10.142.0.105): 14 shards
   longevity-10gb-3h-4-5-db-node-526b36bd-0-7 (35.237.240.235 | 10.142.0.121): 14 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `-` (gce: eu-west-1)

Test: `longevity-10gb-3h-gce-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9c05a112686c84edddf5fb3617188b8f67abcbbd/test-cases/longevity/longevity-10gb-3h.yaml)

**Issue description**

The test fails because of reached its timeout.
It happened because of cassandra-stress load that should be finished after 180 minutes 
```
cassandra-stress write cl=QUORUM duration=180m -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=1000 -pop seq=1..10000000 -log interval=5
```

was not finished in the time.

From c-s logs I found that c-s load stopped report about load due "Unexpected error while querying".

The error started during `RollingRestartCluster` nemesis (at `01:53:07`), that restart `scylla-server` service on node 3. During the nemesis c-s complained on connection problem different nodes:
```
< t:2021-10-07 01:53:07,370 f:file_logger.py  l:80   c:sdcm.sct_events.file_logger p:INFO  > 2021-10-07 01:53:07.360: (DisruptionEvent Severity.NORMAL): type=RollingRestartCluster subtype=start target_node=Node longevity-10gb-3h-4-5-db-node-526b36bd-0-3 [35.185.127.172 | 10.142.0.106] (seed: False) duration=None

ERROR 01:53:07,809 Unexpected error while querying longevity-10gb-3h-4-5-db-node-526b36bd-0-1.c.skilled-adapter-452.internal/10.142.0.100
com.datastax.driver.core.exceptions.ConnectionException: [longevity-10gb-3h-4-5-db-node-526b36bd-0-1.c.skilled-adapter-452.internal/10.142.0.100:9042] Pool is shutdown
        at com.datastax.driver.core.HostConnectionPool.closeAsync(HostConnectionPool.java:841) ~[scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.SessionManager.removePool(SessionManager.java:437) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.SessionManager.onDown(SessionManager.java:525) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.Cluster$Manager.onDown(Cluster.java:2033) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.Cluster$Manager.access$1200(Cluster.java:1393) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.Cluster$Manager$5.runMayThrow(Cluster.java:1988) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at com.datastax.driver.core.ExceptionCatchingRunnable.run(ExceptionCatchingRunnable.java:32) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_302]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_302]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_302]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_302]
        at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [scylla-driver-core-3.7.1-scylla-2-shaded.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_302]
```

2 c-s threads (see `cassandra-stress-l0-c0-k1-6ecfcdb7-eeae-4f38-984d-846795d56a48.log` and `cassandra-stress-l1-c0-k1-b3bb657a-0827-41ec-b4b5-48e84cd0e93b.log` from loader logs) continued to report about querying failures after this nemesis finished (successfully) and stopped to report about load.

But by monitor - load continue running.

![Screenshot from 2021-10-10 20-54-30](https://user-images.githubusercontent.com/34435448/136707660-9f2b361e-727a-47fd-bbbe-444a054db4bc.png)

Restore Monitor Stack command: `$ hydra investigate show-monitor 526b36bd-d5d5-4097-9062-1cf7eab7c8c5`
Show all stored logs command: `$ hydra investigate show-logs 526b36bd-d5d5-4097-9062-1cf7eab7c8c5`

Test id: `526b36bd-d5d5-4097-9062-1cf7eab7c8c5`

Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/526b36bd-d5d5-4097-9062-1cf7eab7c8c5/20211007_044359/db-cluster-526b36bd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/526b36bd-d5d5-4097-9062-1cf7eab7c8c5/20211007_044359/db-cluster-526b36bd.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/526b36bd-d5d5-4097-9062-1cf7eab7c8c5/20211007_044359/loader-set-526b36bd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/526b36bd-d5d5-4097-9062-1cf7eab7c8c5/20211007_044359/loader-set-526b36bd.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/526b36bd-d5d5-4097-9062-1cf7eab7c8c5/20211007_044359/monitor-set-526b36bd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/526b36bd-d5d5-4097-9062-1cf7eab7c8c5/20211007_044359/monitor-set-526b36bd.tar.gz)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/526b36bd-d5d5-4097-9062-1cf7eab7c8c5/20211007_044359/sct-runner-526b36bd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/526b36bd-d5d5-4097-9062-1cf7eab7c8c5/20211007_044359/sct-runner-526b36bd.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.5/job/longevity/job/longevity-10gb-3h-gce-test/45/)

**Comment by slivne** [comment]
This seems like a bug in the driver not in Scylla - why would the driver continue to send requests to a session that is closed ?

**Comment by roydahan** [comment]
@slivne if we are not worried about this issue, we will start filtering this error during this nemesis (only in 4.6 for now).

**Comment by soyacz** [comment]
@roydahan it's not only matter of filtering. It somehow freezes c-s process - thus cannot finish after specified period. This makes jobs to fail on timeout.

**Comment by slivne** [comment]
@haaawk ping

**Comment by slivne** [comment]
This kills the load on QA side so we are trying to resolve this

**Comment by soyacz** [comment]
BTW. This happens on 4.6 branch in the same test `longevity-10gb-3h-gce-test`.
Kernel version: `5.11.0-1023-gcp`
scylla version: `4.6.rc1-0.20211208.542394c82`

It freezed c-s right after starting restart of third node in a row.

test_id: `36ad154f-65f1-43a6-a6d1-e40dcc5511cc`


db-cluster:  | https://cloudius-jenkins-test.s3.amazonaws.com/36ad154f-65f1-43a6-a6d1-e40dcc5511cc/20211208_234513/db-cluster-36ad154f.tar.gz  |
 monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/36ad154f-65f1-43a6-a6d1-e40dcc5511cc/20211208_234513/monitor-set-36ad154f.tar.gz |
 loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/36ad154f-65f1-43a6-a6d1-e40dcc5511cc/20211208_234513/loader-set-36ad154f.tar.gz  |
 sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/36ad154f-65f1-43a6-a6d1-e40dcc5511cc/20211208_234513/sct-runner-36ad154f.tar.gz  |

**Comment by haaawk** [comment]
Would you be able to write a dtest that reproduces this @soyacz? or does this depend on something SCT does?

**Comment by soyacz** [comment]
@haaawk I've tried to reproduce it locally, but failed. Maybe it's related to sct loader's cassandra-stress version and related dependencies - which are quite old on loaders.

I've looked at stress command from loader and looks like this:
```
java -server -ea -cp /usr/share/scylla/cassandra/conf:/usr/share/scylla/cassandra/tools/lib/*.jar:/usr/share/scylla/cassandra/lib/airline-0.6.jar:/usr/share/scylla/cassandra/lib/ant-1.9.7.jar:/usr/share/scylla/cassandra/lib/ant-junit-1.9.7.jar:/usr/share/scylla/cassandra/lib/ant-launcher-1.9.7.jar:/usr/share/scylla/cassandra/lib/antlr-3.5.2.jar:/usr/share/scylla/cassandra/lib/antlr-runtime-3.5.2.jar:/usr/share/scylla/cassandra/lib/apache-rat-0.10.jar:/usr/share/scylla/cassandra/lib/apache-rat-core-0.10.jar:/usr/share/scylla/cassandra/lib/apache-rat-tasks-0.10.jar:/usr/share/scylla/cassandra/lib/asm-5.0.4.jar:/usr/share/scylla/cassandra/lib/byteman-4.0.2.jar:/usr/share/scylla/cassandra/lib/byteman-bmunit-4.0.2.jar:/usr/share/scylla/cassandra/lib/byteman-install-4.0.2.jar:/usr/share/scylla/cassandra/lib/byteman-submit-4.0.2.jar:/usr/share/scylla/cassandra/lib/caffeine-2.2.6.jar:/usr/share/scylla/cassandra/lib/cassandra-driver-core-3.5.1-shaded.jar:/usr/share/scylla/cassandra/lib/commons-beanutils-1.7.0.jar:/usr/share/scylla/cassandra/lib/commons-beanutils-core-1.8.0.jar:/usr/share/scylla/cassandra/lib/commons-cli-1.1.jar:/usr/share/scylla/cassandra/lib/commons-cli-1.2.jar:/usr/share/scylla/cassandra/lib/commons-codec-1.4.jar:/usr/share/scylla/cassandra/lib/commons-codec-1.9.jar:/usr/share/scylla/cassandra/lib/commons-collections-3.2.1.jar:/usr/share/scylla/cassandra/lib/commons-compress-1.5.jar:/usr/share/scylla/cassandra/lib/commons-configuration-1.6.jar:/usr/share/scylla/cassandra/lib/commons-digester-1.8.jar:/usr/share/scylla/cassandra/lib/commons-el-1.0.jar:/usr/share/scylla/cassandra/lib/commons-httpclient-3.0.1.jar:/usr/share/scylla/cassandra/lib/commons-io-2.2.jar:/usr/share/scylla/cassandra/lib/commons-lang-2.4.jar:/usr/share/scylla/cassandra/lib/commons-lang3-3.1.jar:/usr/share/scylla/cassandra/lib/commons-math-2.1.jar:/usr/share/scylla/cassandra/lib/commons-math3-3.2.jar:/usr/share/scylla/cassandra/lib/commons-net-1.4.1.jar:/usr/share/scylla/cassandra/lib/compile-command-annotations-1.2.0.jar:/usr/share/scylla/cassandra/lib/compress-lzf-0.8.4.jar:/usr/share/scylla/cassandra/lib/concurrentlinkedhashmap-lru-1.4.jar:/usr/share/scylla/cassandra/lib/concurrent-trees-2.4.0.jar:/usr/share/scylla/cassandra/lib/disruptor-3.0.1.jar:/usr/share/scylla/cassandra/lib/ecj-4.4.2.jar:/usr/share/scylla/cassandra/lib/ftplet-api-1.0.0.jar:/usr/share/scylla/cassandra/lib/ftpserver-core-1.0.0.jar:/usr/share/scylla/cassandra/lib/ftpserver-deprecated-1.0.0-M2.jar:/usr/share/scylla/cassandra/lib/guava-18.0.jar:/usr/share/scylla/cassandra/lib/guava-19.0.jar:/usr/share/scylla/cassandra/lib/hadoop-core-1.0.3.jar:/usr/share/scylla/cassandra/lib/hadoop-minicluster-1.0.3.jar:/usr/share/scylla/cassandra/lib/hadoop-test-1.0.3.jar:/usr/share/scylla/cassandra/lib/HdrHistogram-2.1.9.jar:/usr/share/scylla/cassandra/lib/high-scale-lib-1.0.6.jar:/usr/share/scylla/cassandra/lib/hppc-0.5.4.jar:/usr/share/scylla/cassandra/lib/hsqldb-1.8.0.10.jar:/usr/share/scylla/cassandra/lib/jackson-core-asl-1.0.1.jar:/usr/share/scylla/cassandra/lib/jackson-core-asl-1.9.13.jar:/usr/share/scylla/cassandra/lib/jackson-mapper-asl-1.0.1.jar:/usr/share/scylla/cassandra/lib/jackson-mapper-asl-1.9.13.jar:/usr/share/scylla/cassandra/lib/jacocoagent.jar:/usr/share/scylla/cassandra/lib/jamm-0.3.0.jar:/usr/share/scylla/cassandra/lib/jasper-compiler-5.5.12.jar:/usr/share/scylla/cassandra/lib/jasper-runtime-5.5.12.jar:/usr/share/scylla/cassandra/lib/javax.inject.jar:/usr/share/scylla/cassandra/lib/jbcrypt-0.3m.jar:/usr/share/scylla/cassandra/lib/jcl-over-slf4j-1.7.7.jar:/usr/share/scylla/cassandra/lib/jctools-core-1.2.1.jar:/usr/share/scylla/cassandra/lib/jersey-core-1.0.jar:/usr/share/scylla/cassandra/lib/jersey-server-1.0.jar:/usr/share/scylla/cassandra/lib/jets3t-0.7.1.jar:/usr/share/scylla/cassandra/lib/jetty-6.1.26.jar:/usr/share/scylla/cassandra/lib/jetty-util-6.1.26.jar:/usr/share/scylla/cassandra/lib/jffi-1.2.16.jar:/usr/share/scylla/cassandra/lib/jffi-1.2.16-native.jar:/usr/share/scylla/cassandra/lib/jflex-1.6.0.jar:/usr/share/scylla/cassandra/lib/jmh-core-1.21.jar:/usr/share/scylla/cassandra/lib/jmh-generator-annprocess-1.21.jar:/usr/share/scylla/cassandra/lib/jna-4.1.0.jar:/usr/share/scylla/cassandra/lib/jna-4.2.2.jar:/usr/share/scylla/cassandra/lib/jnr-constants-0.9.9.jar:/usr/share/scylla/cassandra/lib/jnr-ffi-2.1.7.jar:/usr/share/scylla/cassandra/lib/jnr-posix-3.0.44.jar:/usr/share/scylla/cassandra/lib/jnr-x86asm-1.0.2.jar:/usr/share/scylla/cassandra/lib/joda-time-2.4.jar:/usr/share/scylla/cassandra/lib/jopt-simple-4.6.jar:/usr/share/scylla/cassandra/lib/json-simple-1.1.jar:/usr/share/scylla/cassandra/lib/jsp-2.1-6.1.14.jar:/usr/share/scylla/cassandra/lib/jsp-api-2.1-6.1.14.jar:/usr/share/scylla/cassandra/lib/jsr305-2.0.2.jar:/usr/share/scylla/cassandra/lib/jsr311-api-1.0.jar:/usr/share/scylla/cassandra/lib/jstackjunit-0.0.1.jar:/usr/share/scylla/cassandra/lib/junit-4.6.jar:/usr/share/scylla/cassandra/lib/kfs-0.3.jar:/usr/share/scylla/cassandra/lib/libthrift-0.9.2.jar:/usr/share/scylla/cassandra/lib/log4j-over-slf4j-1.7.7.jar:/usr/share/scylla/cassandra/lib/logback-classic-1.1.3.jar:/usr/share/scylla/cassandra/lib/logback-core-1.1.3.jar:/usr/share/scylla/cassandra/lib/lz4-1.3.0.jar:/usr/share/scylla/cassandra/lib/metrics-core-3.1.5.jar:/usr/share/scylla/cassandra/lib/metrics-core-3.2.2.jar:/usr/share/scylla/cassandra/lib/metrics-jvm-3.1.5.jar:/usr/share/scylla/cassandra/lib/metrics-logback-3.1.5.jar:/usr/share/scylla/cassandra/lib/mina-core-2.0.0-M5.jar:/usr/share/scylla/cassandra/lib/netty-all-4.0.56.Final.jar:/usr/share/scylla/cassandra/lib/ohc-core-0.4.4.jar:/usr/share/scylla/cassandra/lib/ohc-core-j8-0.4.4.jar:/usr/share/scylla/cassandra/lib/org.jacoco.agent-0.7.5.201505241946.jar:/usr/share/scylla/cassandra/lib/org.jacoco.ant-0.7.5.201505241946.jar:/usr/share/scylla/cassandra/lib/org.jacoco.core-0.7.5.201505241946.jar:/usr/share/scylla/cassandra/lib/org.jacoco.report-0.7.5.201505241946.jar:/usr/share/scylla/cassandra/lib/oro-2.0.8.jar:/usr/share/scylla/cassandra/lib/reporter-config3-3.0.3.jar:/usr/share/scylla/cassandra/lib/reporter-config-base-3.0.3.jar:/usr/share/scylla/cassandra/lib/scylla-driver-core-3.7.1-scylla-2-shaded.jar:/usr/share/scylla/cassandra/lib/servlet-api-2.5-6.1.14.jar:/usr/share/scylla/cassandra/lib/sigar-1.6.4.jar:/usr/share/scylla/cassandra/lib/slf4j-api-1.7.25.jar:/usr/share/scylla/cassandra/lib/slf4j-api-1.7.7.jar:/usr/share/scylla/cassandra/lib/snakeyaml-1.11.jar:/usr/share/scylla/cassandra/lib/snappy-java-1.1.1.7.jar:/usr/share/scylla/cassandra/lib/snowball-stemmer-1.3.0.581.1.jar:/usr/share/scylla/cassandra/lib/ST4-4.0.8.jar:/usr/share/scylla/cassandra/lib/stream-2.5.2.jar:/usr/share/scylla/cassandra/lib/thrift-server-0.3.7.jar:/usr/share/scylla/cassandra/lib/xmlenc-0.52.jar:/usr/share/scylla/cassandra/apache-cassandra-3.11.3-SNAPSHOT.jar:/usr/share/scylla/cassandra/apache-cassandra-clientutil-3.11.3-SNAPSHOT.jar:/usr/share/scylla/cassandra/apache-cassandra.jar:/usr/share/scylla/cassandra/apache-cassandra-thrift-3.11.3-SNAPSHOT.jar:/usr/share/scylla/cassandra/maven-ant-tasks-2.1.3.jar:/usr/share/scylla/cassandra/scylla-tools-3.11.3-SNAPSHOT.jar:/usr/share/scylla/cassandra/stress.jar -Djdk.attach.allowAttachSelf=true --add-exports java.base/jdk.internal.misc=ALL-UNNAMED --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-exports java.management.rmi/com.sun.jmx.remote.internal.rmi=ALL-UNNAMED --add-exports java.rmi/sun.rmi.registry=ALL-UNNAMED --add-exports java.rmi/sun.rmi.server=ALL-UNNAMED --add-exports java.sql/java.sql=ALL-UNNAMED --add-opens java.base/java.lang.module=ALL-UNNAMED --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/jdk.internal.reflect=ALL-UNNAMED --add-opens java.base/jdk.internal.math=ALL-UNNAMED --add-opens java.base/jdk.internal.module=ALL-UNNAMED --add-opens java.base/jdk.internal.util.jar=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED -Dcassandra.storagedir=/usr/share/scylla/cassandra/data -Dlogback.configurationFile=logback-tools.xml org.apache.cassandra.stress.Stress read cl=ONE duration=2860m -schema keyspace=keyspace1 replication(factor=3) compaction(strategy=LeveledCompactionStrategy) -port jmx=6868 -mode cql3 native user=cassandra password=cassandra -rate threads=250 -col size=FIXED(1024) n=FIXED(1) -pop seq=1..200200300 -log interval=5 -node 127.0.0.1 -errors skip-unsupported-columns

```

**Comment by slivne** [comment]
another c-s issue - pushing it out

**Comment by roydahan** [comment]
This issue isn't relevant anymore, we don't see it with latest drivers and c-s.
