### ISSUE TITLE
fatal error: in "fuzzy_test": std::runtime_error: Truncated frame

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#9482]
Unit test flakiness seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/4056/artifact/testlog/x86_64_dev/multishard_mutation_query_test.262.log
Scylla version 33f8ec09df309b055766aec5c2845f0c4e525bd4 (that was promoted later)
```
INFO  2021-10-11 20:31:33,148 [shard 0] testlog - fuzzy test seed: 2234014921
INFO  2021-10-11 20:31:33,149 [shard 0] testlog - Generating combinations...
INFO  2021-10-11 20:31:33,149 [shard 0] testlog - Done. Generated 123 combinations, 461 partitions in total.
INFO  2021-10-11 20:31:33,149 [shard 0] migration_manager - Create new Keyspace: KSMetaData{name=multishard_mutation_query_test, strategyClass=org.apache.cassandra.locator.SimpleStrategy, strategyOptions={replication_factor=1}, cfMetaData={}, durable_writes=1, userTypes=org.apache.cassandra.config.UTMetaData@0x6010000d1b18}
INFO  2021-10-11 20:31:33,149 [shard 0] schema_tables - Creating keyspace multishard_mutation_query_test
INFO  2021-10-11 20:31:33,151 [shard 0] schema_tables - Schema version changed to cda8c2b0-da45-3553-a3fd-4711464cbbad
INFO  2021-10-11 20:31:33,152 [shard 0] migration_manager - Create new ColumnFamily: org.apache.cassandra.config.CFMetaData@0x60100045a380[cfId=13d27a00-2ab9-11ec-80dd-9a414492289a,ksName=multishard_mutation_query_test,cfName=fuzzy_test,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.UTF8Type),comment=,readRepairChance=0,dcLocalReadRepairChance=0,gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.Int32Type,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=pk, type=org.apache.cassandra.db.marshal.Int32Type, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=ck, type=org.apache.cassandra.db.marshal.Int32Type, kind=CLUSTERING_COLUMN, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=s, type=org.apache.cassandra.db.marshal.BytesType, kind=STATIC, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=v, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=13d27a01-2ab9-11ec-80dd-9a414492289a,droppedColumns={},collections={},indices={}]
INFO  2021-10-11 20:31:33,153 [shard 0] schema_tables - Creating multishard_mutation_query_test.fuzzy_test id=13d27a00-2ab9-11ec-80dd-9a414492289a version=6daa10a7-47c2-3625-a76e-088b9fee24f8
INFO  2021-10-11 20:31:33,156 [shard 0] schema_tables - Schema version changed to 57155834-6e2b-3c97-a92e-f9511f8fa74f
INFO  2021-10-11 20:31:33,158 [shard 0] testlog - Populating test data...
INFO  2021-10-11 20:31:37,515 [shard 0] view - Stopping view builder
INFO  2021-10-11 20:31:37,515 [shard 0] view - Draining view builder
INFO  2021-10-11 20:31:37,515 [shard 1] view - Stopping view builder
INFO  2021-10-11 20:31:37,515 [shard 1] view - Draining view builder
INFO  2021-10-11 20:31:37,516 [shard 0] gossip - My status = NORMAL
INFO  2021-10-11 20:31:37,516 [shard 0] gossip - Announcing shutdown
INFO  2021-10-11 20:31:37,516 [shard 0] gossip - Disable and wait for gossip loop started
INFO  2021-10-11 20:31:38,055 [shard 0] gossip - Gossip is now stopped
INFO  2021-10-11 20:31:38,055 [shard 0] compaction_manager - Asked to stop
INFO  2021-10-11 20:31:38,056 [shard 0] compaction_manager - Stopping 0 ongoing compactions due to shutdown
INFO  2021-10-11 20:31:38,056 [shard 0] compaction_manager - Stopped
INFO  2021-10-11 20:31:38,056 [shard 1] compaction_manager - Asked to stop
INFO  2021-10-11 20:31:38,056 [shard 1] compaction_manager - Stopping 0 ongoing compactions due to shutdown
INFO  2021-10-11 20:31:38,056 [shard 1] compaction_manager - Stopped
INFO  2021-10-11 20:31:38,299 [shard 0] view_update_generator - leaving 0 unstaged sstables unprocessed
INFO  2021-10-11 20:31:38,299 [shard 1] view_update_generator - leaving 0 unstaged sstables unprocessed
INFO  2021-10-11 20:31:38,300 [shard 0] migration_manager - stopping migration service
INFO  2021-10-11 20:31:38,300 [shard 1] migration_manager - stopping migration service
INFO  2021-10-11 20:31:47,544 [shard 0] gossip - gossip is already stopped
unknown location(0): fatal error: in "fuzzy_test": std::runtime_error: Truncated frame
./seastar/src/testing/seastar_test.cc(43): last checkpoint
test/boost/multishard_mutation_query_test.cc(0): Leaving test case "fuzzy_test"; testing time: 14605486us
Leaving test module "test/boost/multishard_mutation_query_test.cc"; testing time: 20886630us
```

**Comment by bhalevy** [comment]
@denesb please also look into this issue as you wrote fuzzy_test.
It might be related to #9483 as they both popped up together in next at the same version

**Comment by bhalevy** [comment]
@slivne since this isn't reproducible, I suggest removing the `high` label.
@denesb added some more diagnostics so if/when this is reproduced we'll have more information to make progress.

**Comment by slivne** [comment]
fair enough - removed high

**Comment by tatatodd** [comment]
I'm running into this in my prod environment.  Do you folks have tips on how I can capture more info, to help track this down?

I posted this on the general slack channel, with the info below:
https://scylladb-users.slack.com/archives/C2NLNBXLN/p1639765387279100

I’m hitting an issue doing scans on a 42 node cluster running scylla 4.5.1.  I can repro via cqlsh, using a query like this:
```
SELECT pk, static1, static2, ck1, ck2, ck3 FROM keyspace.table WHERE token(pk) >= 7397144373557530183 AND token(pk) <= 7415591117631239733 BYPASS CACHE;
```
It’s not completely deterministic, but after a few pages of output I get a server error:
```
<Error from server: code=0000 [Server error] message="Truncated frame">
``
We’re seeing this issue in a prod cronjob, which started failing a few days ago.  We’ve never seen this error before, but now we’re seeing it on every table scan, for various token ranges.

The server logs show occasional compaction messages, and a bunch of:
```
INFO  2021-12-17 18:03:11,561 [shard 3] cql_server - exception while processing connection: std::system_error (error system:22, Invalid argument)
```

Our table schema is:
```
CREATE TABLE keyspace.table (
    pk text,
    ck1 text,
    ck2 text,
    ck3 text,
    static1 text static,
    static2 text static,
    data text,
    PRIMARY KEY (pk, ck1, ck2, ck3)
) WITH CLUSTERING ORDER BY (ck1 ASC, ck2 ASC, ck3 ASC)
```

**Comment by avikivity** [comment]
There's a tcp problem somewhere.

```c++
future<fragmented_temporary_buffer> cql_server::connection::read_and_decompress_frame(size_t length, uint8_t flags)
{
    using namespace compression_buffers;
    if (flags & cql_frame_flags::compression) {
        if (_compression == cql_compression::lz4) {
            if (length < 4) {
                throw std::runtime_error("Truncated frame");
            }
```

If you can capture traffic on port 9042 (ideally with just the reproducer running) it can shed a lot of light here.

**Comment by avikivity** [comment]
There's another candidate, in serialization_visitors.hh:

```c++
template<typename Input>
size_type read_frame_size(Input& in) {
    auto sz = deserialize(in, boost::type<size_type>());
    if (sz < sizeof(size_type)) {
        throw std::runtime_error("Truncated frame");
    }
    return sz - sizeof(size_type);
}
```

If it's this one, it may indicate a problem related to static columns (just picking on them because they're relatively rare).

**Comment by avikivity** [comment]
also: 9ec55e054de865c8480974b82b12cd27beefa4ac

**Comment by slivne** [comment]
@avikivity lets backport the patch from botond to 4.5 so we will have the additional info when the error happens.

**Comment by slivne** [comment]
@bhalevy / @denesb (just as an FYI - an open source user reproduced this or something similar on 4.5 :) )

**Comment by denesb** [comment]
Backported to 4.5 as 5c8057749b0ef36f4e849276656782ec54dbd199.

**Comment by tatatodd** [comment]
Thanks for the info folks!  We're trying to figure out the least disruptive way to isolate our repro; it's occurring in one of our prod tables, with various tradeoffs.

Question: is there a timeline for when a 4.5.x image will be available that includes https://github.com/scylladb/scylla/commit/5c8057749b0ef36f4e849276656782ec54dbd199?  Once we have that image, we can roll it out pretty quickly, and at least it'll identify which codepath to focus on.

**Comment by tatatodd** [comment]
@avikivity  
Follow-up to my comment above (https://github.com/scylladb/scylla/issues/9482#issuecomment-996934270).
We're now running 4.5.3 and see the following error:
```
Error from server: code=0000 [Server error] message="IDL frame truncated: expected to have at least 4 bytes, got 0"
```
Digging through the code, that's the `read_frame_size` codepath, which is called by the IDL serializers auto-generated by `idl-compiler.py`.
https://github.com/scylladb/scylla/blob/scylla-4.5.3/serialization_visitors.hh#L88-L95

FWIW here's the results of grepping for `read_frame_size` after a build:
```
./build/release/gen/idl/query.dist.impl.hh:        v.skip(read_frame_size(v));
./build/release/gen/idl/frozen_schema.dist.impl.hh:        v.skip(read_frame_size(v));
./build/release/gen/idl/idl_test.dist.impl.hh:        v.skip(read_frame_size(v));
./build/release/gen/idl/commitlog.dist.impl.hh:        v.skip(read_frame_size(v));
./build/release/gen/idl/mutation.dist.impl.hh:        v.skip(read_frame_size(v));
```

QUESTIONS
1. I'm not familiar with the codebase; does the `read_frame_size` failure imply that the problem is related to persistent artifacts (e.g. corrupted commitlog, sstables, ...), or is it still possible that there's a protocol error elsewhere?  It looks like `query.dist.impl.hh` is used to marshal query results.
2. We're going to try more aggressive major compaction and repairs, do you think that might help?
3. You mentioned static columns might be involved (since they're rare), any tips on what we might try, given that assumption?
4. Can you suggest how we can dig further to discover or fix the problem?

As always we're open to all suggestions.  Thanks!

**Comment by denesb** [comment]
@tatatodd to make forward progress with this, we'd need a coredump to examine what exactly is happening. But this would require a custom binary because to get a coredump we'd need to change the `throw std::runtime_error(` to `on_internal_error()` and trigger a crash when the problem happens. Would you be able and willing to deploy such a custom binary? It is enough to deploy it one one node only -- the one experiencing these errors the most.

One other thing that could help shed more light on where the problem might lie is doing a validation compaction. Sadly this is not available in 4.5, only in >4.6.

As to your questions:
> I'm not familiar with the codebase; does the read_frame_size failure imply that the problem is related to persistent artifacts (e.g. corrupted commitlog, sstables, ...), or is it still possible that there's a protocol error elsewhere? It looks like query.dist.impl.hh is used to marshal query results.

For now I suspect a problem in the code, rather than a problem in the sstables. The key is determinism: if there is a problem in the sstable, the problems are usually reproducible all the time, the same way.

> We're going to try more aggressive major compaction and repairs, do you think that might help?

Did this change or reveal anything?

> You mentioned static columns might be involved (since they're rare), any tips on what we might try, given that assumption?

We have seen in the past the the presence of static columns exercises some less used code paths in sstable parser code, causing different behavior with corrupt sstables.

> Can you suggest how we can dig further to discover or fix the problem?

Like I mentioned a coredump would be best. A less intrusive thing we could try is to search the token-space to see if the problem relates to a given token-range. Are queries against any token-range equally likely to produce the error? Or did you notice any patterns? It would be great if we could reduce the problem-space to a small range or ideally just a single sstable/partition.

**Comment by denesb** [comment]
I think we should be able to reproduce it with running the `multishard_mutation_query_test` with a high repeat count. I'll try to do that and reproduce locally. We need a coredump to get to the bottom of this and we won't get one from jenkins.

**Comment by tatatodd** [comment]
@denesb Thanks for the info!  Here's some updates from our end:
1. Unfortunately we can't send over a coredump; the table it's occurring on contains sensitive data.
2. We ran multiple rounds of major compactions and repairs, and we're still seeing the same failures.
3. We've tried to isolate the problem to specific token ranges, but AFAICT it's occurring all over the place.  I.e. we split the full token range (that covers all tokens) into 1000 equally-sized sub-ranges for scans, and the same failure occurs in all of these subranges.

We're now trying various things to workaround the implications of this in our prod pipelines, but if you have any other tips or ideas, we're all ears!

**Comment by denesb** [comment]
I have reproduced this on a branch of mine with a certain seed. With this seed it reproduces 100% of the time. It only reproduces in dev/release and it doesn't reproduce on master with the same seed.

**Comment by avikivity** [comment]
Wow, I'm really curious what happened there.

**Comment by denesb** [comment]
```
#0  0x00007fa69da182a2 in raise () from /lib64/libc.so.6
#1  0x00007fa69da01950 in abort () from /lib64/libc.so.6
#2  0x00007fa69da01789 in __assert_fail_base.cold () from /lib64/libc.so.6
#3  0x00007fa69da10a16 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000017079e3 in ser::read_frame_size<seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator> > (in=...) at ./serialization_visitors.hh:79
#5  ser::serializer<ser::qr_partition_view>::skip<seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator> >(seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator>&)::{lambda(auto:1&)#1}::operator()<seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator> >(seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator>&) const (this=<optimized out>, v=...) at build/release/gen/idl/query.dist.impl.hh:249
#6  seastar::with_serialized_stream<seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator>, ser::serializer<ser::qr_partition_view>::skip<seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator> >(seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator>&)::{lambda(auto:1&)#1}, void, void>(seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator>&, ser::serializer<ser::qr_partition_view>::skip<seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator> >(seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator>&)::{lambda(auto:1&)#1}&&) (stream=..., visitor=...) at ./seastar/include/seastar/core/simple-stream.hh:633
#7  ser::serializer<ser::qr_partition_view>::skip<seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator> > (v=...) at build/release/gen/idl/query.dist.impl.hh:248
#8  ser::serializer<ser::qr_partition_view>::read<seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator> >(seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator>&)::{lambda(auto:1&)#1}::operator()<seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator> >(seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator>&) const (this=<optimized out>, v=...) at build/release/gen/idl/query.dist.impl.hh:238
#9  seastar::with_serialized_stream<seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator>, ser::serializer<ser::qr_partition_view>::read<seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator> >(seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator>&)::{lambda(auto:1&)#1}, void, void>(seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator>&, ser::serializer<ser::qr_partition_view>::read<seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator> >(seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator>&)::{lambda(auto:1&)#1}&&) (stream=..., visitor=...) at ./seastar/include/seastar/core/simple-stream.hh:633
#10 ser::serializer<ser::qr_partition_view>::read<seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator> > (v=...) at build/release/gen/idl/query.dist.impl.hh:235
#11 ser::deserialize<ser::qr_partition_view, seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator> > (in=..., t=...) at ./serializer.hh:261
#12 ser::deserialize_array_helper<false, ser::qr_partition_view>::doit<seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator>, utils::chunked_vector<ser::qr_partition_view, 131072ul> > (in=..., v=..., sz=<optimized out>)
    at ./serializer_impl.hh:188
#13 0x00000000024b06d7 in ser::deserialize_array<ser::qr_partition_view, seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator>, utils::chunked_vector<ser::qr_partition_view, 131072ul> > (in=..., v=..., sz=2)
    at ./serializer_impl.hh:201
#14 ser::idl::serializers::internal::vector_serializer<utils::chunked_vector<ser::qr_partition_view, 131072ul> >::read<seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator> > (in=...) at ./serializer_impl.hh:219
#15 ser::deserialize<utils::chunked_vector<ser::qr_partition_view, 131072ul>, seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator> > (in=..., t=...) at ./serializer.hh:261
#16 ser::query_result_view::partitions() const::{lambda(auto:1&)#1}::operator()<seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator> const>(seastar::fragmented_memory_input_stream<bytes_ostream::fragment_iterator> const&) const (
    this=<optimized out>, v=...) at build/release/gen/idl/query.dist.impl.hh:262
#17 seastar::memory_input_stream<bytes_ostream::fragment_iterator>::with_stream<ser::query_result_view::partitions() const::{lambda(auto:1&)#1}>(ser::query_result_view::partitions() const::{lambda(auto:1&)#1}&&) const (this=<optimized out>, visitor=...)
    at ./seastar/include/seastar/core/simple-stream.hh:481
#18 seastar::with_serialized_stream<seastar::memory_input_stream<bytes_ostream::fragment_iterator> const, ser::query_result_view::partitions() const::{lambda(auto:1&)#1}, void>(seastar::memory_input_stream<bytes_ostream::fragment_iterator> const&, ser::query_result_view::partitions() const::{lambda(auto:1&)#1}&&) (stream=..., visitor=...) at ./seastar/include/seastar/core/simple-stream.hh:626
#19 ser::query_result_view::partitions (this=<optimized out>) at build/release/gen/idl/query.dist.impl.hh:259
#20 query::result_merger::get()::$_2::operator()(query::result_view) const (this=<optimized out>, rv=...) at query.cc:357
#21 query::result_view::do_with<query::result_merger::get()::$_2>(query::result const&, query::result_merger::get()::$_2&&) (res=..., func=...) at ./query-result-reader.hh:148
#22 query::result_merger::get (this=<optimized out>) at query.cc:356
#23 0x0000000001a6308f in seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}::operator()() (this=0x603000812830)
    at ./seastar/include/seastar/core/map_reduce.hh:46
#24 std::__invoke_impl<seastar::future<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > >, seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&>(std::__invoke_other, seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&) (__f=...)
    at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
#25 std::__invoke<seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&>(seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&) (__fn=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:96
#26 std::invoke<seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&>(seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&) (__fn=...) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/functional:97
#27 seastar::internal::future_invoke<seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&, seastar::internal::monostate>(seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&, seastar::internal::monostate&&) (func=..., v=...) at ./seastar/include/seastar/core/future.hh:1209
#28 seastar::future<void>::then_impl_nrvo<seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}, seastar::future<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >(seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&&)::{lambda(seastar::internal::promise_base_with_type<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > >&&, seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}::operator()(seastar::internal::promise_base_with_type<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > >&&, seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&) const::{lambda()#1}::operator()() const (this=<optimized out>) at ./seastar/include/seastar/core/future.hh:1582
#29 seastar::futurize<seastar::future<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >::satisfy_with_result_of<seastar::future<void>::then_impl_nrvo<seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}, seastar::future<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >(seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&&)::{lambda(seastar::internal::promise_base_with_type<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > >&&, seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}::operator()(seastar::internal::promise_base_with_type<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > >&&, seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&) const::{lambda()#1}>(seastar::internal::promise_base_with_type<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > >&&, seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&&) (pr=..., func=...) at ./seastar/include/seastar/core/future.hh:2120
#30 seastar::future<void>::then_impl_nrvo<seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}, seastar::future<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >(seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&&)::{lambda(seastar::internal::promise_base_with_type<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > >&&, seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}::operator()(seastar::internal::promise_base_with_type<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > >&&, seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&) const (this=0x603000812800, pr=..., func=..., state=...) at ./seastar/include/seastar/core/future.hh:1575
#31 seastar::continuation<seastar::internal::promise_base_with_type<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > >, seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}, seastar::future<void>::then_impl_nrvo<seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}, seastar::future<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > > >(seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&&)::{lambda(seastar::internal::promise_base_with_type<seastar::foreign_ptr<seastar::lw_shared_ptr<query::result> > >&&, seastar::reducer_with_get_traits<query::result_merger, false>::maybe_call_get(seastar::future<void>, seastar::lw_shared_ptr<query::result_merger>)::{lambda()#1}&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>::run_and_dispose() (this=0x603000812800) at ./seastar/include/seastar/core/future.hh:767
#32 0x00000000030bb915 in seastar::reactor::run_tasks (this=0x6030000a6000, tq=...) at ./seastar/src/core/reactor.cc:2344
#33 seastar::reactor::run_some_tasks (this=this@entry=0x6030000a6000) at ./seastar/src/core/reactor.cc:2754
#34 0x00000000030bcce8 in seastar::reactor::do_run (this=0x6030000a6000) at ./seastar/src/core/reactor.cc:2923
#35 0x00000000030db626 in seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100::operator()() const (this=0x601000014ee0) at ./seastar/src/core/reactor.cc:4140
#36 std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&) (__f=...)
    at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
#37 std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&) (__fn=...)
    at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:111
#38 std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100>::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:291
#39 0x000000000309fa1b in std::function<void ()>::operator()() const (this=0x2) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:560
#40 seastar::posix_thread::start_routine (arg=0x2) at ./seastar/src/core/posix.cc:60
#41 0x00007fa69e6f92a5 in start_thread () from /lib64/libpthread.so.0
#42 0x00007fa69dadb323 in clone () from /lib64/libc.so.6
```
The error happens on the coordinator-side, during a range-scan, while merging results from individual sub-scans.

**Comment by denesb** [comment]
One of the sub-results is completely empty.

**Comment by denesb** [comment]
When I iterate over all the buffers in the individual result objects, none of them are empty. So somewhere processing goes sideways. Still investigating where.

**Comment by denesb** [comment]
Looks like the problem is caused by a missing call to `consume_end_of_partition()` on the query result builder.

**Comment by denesb** [comment]
The problem is ultimately caused by a missing partition end fragment, right before the stream ends. This seems to cause the serializer to corrupt the serialized data such that on deserialization the "Truncated frame" error is hit.
The missing partition end fragment was caused by a bug that is only present on my branch, so the cause of the bug reported here will be something else. Nevertheless it is useful to know a possible cause for this error.

**Comment by denesb** [comment]
The underlying bug is the multishard reader code (used in range scans) mishandling the page being cut in a partition only containing a static row. This ends up generating a missing partition-end fragment on the next page, leading to a corrupt query-result being written, in turn leading to the IDL frame truncated error on the coordinator.

**Comment by bhalevy** [comment]
Why didn't the promoter mark this automatically with `Backport candidate`?

**Comment by bhalevy** [comment]
Reopened with https://github.com/scylladb/scylladb/commit/00cec159d68643e1379f7f954f86a90421cf1e94

**Comment by bhalevy** [comment]
@avikivity can we prevent the bot from closing issues when a fix is merged into a different branch / repo?

In this case, the fix was reverted in master and got reopened manually
