### ISSUE TITLE
resetlocalschema_api_issue_7811_test: Schema versions are different on the nodes

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#9732]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/646/testReport/junit/nodetool_additional_test/TestNodetool/resetlocalschema_api_issue_7811_test/
Scylla version db5678bb7f92e5e128e1edc80ec2d1465e8662b9

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/nodetool_additional_test.py", line 1265, in resetlocalschema_api_issue_7811_test
    self._verify_nodes_schema_versions(node1, 1)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/nodetool_additional_test.py", line 1192, in _verify_nodes_schema_versions
    f"Schema versions are different on the nodes: {','.join(desc_cluster[schema_version_ind + 1:])} " \
AssertionError: Schema versions are different on the nodes: 3ab9dc49-f30b-3f29-b93e-a0ce041cb413: [127.0.67.1],9e277eb9-701c-3a80-92bf-d74c8b4318a1: [127.0.67.2] unexpectedly
```

**Comment by mykaul** [comment]
@bhalevy - have you seen this recently?

**Comment by bhalevy** [comment]
> @bhalevy - have you seen this recently?

Nope
